= Versand vorbereiten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Versanddienstleister, Fulfillment-Dienstleister, Fulfillment, Fulfilment, shipping provider, shipping service provider, Lieferländer, Lieferland, Regionen, Region, Versandprofil, Versandprofile, Portotabelle, Versandpaket, Versandpakete, Versandkosten, DHL-Packstation, DHL-Postfinder, Tracking-URL, Tracking URL, c.b.c. logistics, cbc logistics, PARCEL.ONE, parcel one, DHL Easylog, DHL Freight, DHL Intraship, DHL Versenden, DHL Intraship, Intraship/Versenden, DHL plentymarkets Import, DHL Retoure Beilegeretiketten, DHL Retoure Online, DHL Supply Chain, DHL UK, DPD Cloud Webservice, DPD DELISprint, EasyPak, GLS Germany, Hermes 2-Mann-Handling, Hermes ProfiPaketService, MY DPD Business / iloxx, Royal Mail, UK Mail, NetDespatch, Swiss Post, UPS, DHL Fulfillment, IDS Logistik, iLOPACK, DHL Exportdokument, Exportdokumente, DHL Zollinhaltserklärung, CN23-Dokument, CN23, CN 23, CP71-Dokument, CP71, CP 71
:description: Erfahren Sie, wie Sie Versandprofile, Versandpakete und Versanddienstleister in plentymarkets einrichten.
:position: 10
:url: fulfillment/versand-vorbereiten

In plentymarkets haben Sie als Händler die Möglichkeit, für den Versand Ihrer Artikel einen Dienstleister zu beauftragen, der je nach Vertrag die Waren bei Ihnen abholt und versendet und dann den Status an Ihr plentymarkets System zurückmeldet.

plentymarkets ermöglicht genau abgestimmte Versandprozesse, die in hohem Maß automatisiert ablaufen. Von der Verknüpfung der Artikel mit den Versandprofilen über die Versandanmeldung bis zur Ausgabe eines Versandlabels steuert Ihr plentymarkets System die gesamten Abläufe - und das besonders effizient mit den <<automatisierung/prozesse/prozesse-einrichten#, Prozessen>>. Der anfängliche Aufwand beim Einrichten zahlt sich durch eine reibungslose Abwicklung aus, die ein sorgfältig eingestelltes System ermöglicht.

Auf dieser Handbuchseite wird beschrieben, wie Sie den Versand vorbereiten und <<fulfillment/versand-vorbereiten#2500, versanddienstleisterspezifische Einstellungen>> vornehmen. Einige Dienstleister bieten einen kompletten Service an, der die Lagerung der Artikel einschließt. Weitere Informationen dazu finden Sie im Kapitel <<fulfillment/versand-vorbereiten#4700, Fulfillment-Dienstleister im Überblick>>.

[#100]
== Lieferländer einrichten

Im Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Lieferländer* richten Sie die Länder ein, die Sie beliefern möchten. Die Übersicht enthält alle in plentymarkets verfügbaren Lieferländer. In der Spalte *Standardname* ist die Systembezeichnung des Landes dargestellt. Der Standardname kann nicht geändert werden und wird Ihren Kunden nicht angezeigt. In der Spalte *Name* geben Sie den Namen ein, der Ihren Kunden angezeigt werden soll.

[#200]
=== Lieferländer bearbeiten und aktivieren

Im Tab *Übersicht* bearbeiten und aktivieren Sie die Lieferländer.

[.instruction]
Lieferländer bearbeiten und aktivieren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Lieferländer » Tab: Übersicht*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-uebersicht-lieferlaender>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-uebersicht-lieferlaender]]
.Übersicht der Lieferländer im Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Lieferländer*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ID*
|Interne ID des Lieferlandes. Wird automatisch vergeben und kann nicht geändert werden.

|*Name (xy)*
|Ländername eingeben, wie er im Webshop und auf Dokumenten angezeigt werden soll. +
*_Wichtig:_* Der Name des Lieferlandes kann in verschiedenen Sprachen eingegeben werden. Dazu im Tab *Filter* in der Dropdown-Liste *Sprache (Name)* das Sprachkürzel wählen und auf *Suchen* klicken. Die eingegebenen Namen der Sprache werden angezeigt. Die Bezeichnungen in der Spalte *Name (xy)* in der Übersicht nach Wunsch anpassen oder ergänzen und speichern.

|*Standardname*
|Systembezeichnung des Lieferlandes. Kann nicht geändert werden.

|*Aktiv*
|Eine der folgenden Optionen wählen: +
*Aktiv* = Lieferland steht zur Verfügung. +
*Inaktiv* = Lieferland steht nicht zur Verfügung. +
*Backoffice aktiv* = Lieferländer mit dieser Eigenschaft sind nur im plentymarkets System und nicht im Webshop sichtbar. +
*Lieferant aktiv* = Lieferländer mit dieser Eigenschaft stehen für die Einstellung als *Standardlieferland* im Menü <<omni-channel/online-shop/webshop-einrichten/bestellvorgang#, System » Systemeinstellungen » Mandant » Mandant wählen » Bestellvorgang » Einstellungen>> nicht zur Verfügung.

|*Lager*
|Lager wählen, das dem Lieferland als Hauptlager zugeordnet werden soll und z.B. in Aufträgen automatisch eingestellt sein soll. *ALLE* wählen, wenn alle Lager dem Lieferland zugeordnet werden sollen. In diesem Fall wird für Aufträge automatisch das Lager mit der kleinsten ID gewählt. Dazu auch die <<auftraege/auftraege-verwalten#, Lagereinstellungen>> im Menü *System » Systemeinstellungen » Aufträge » Einstellungen* beachten.

|*Sprache*
|Festlegen, welches Lieferland für welche Sprache das Standardlieferland sein soll. Einem Lieferland kann nur eine Sprache zugeordnet werden.
|====

[#300]
=== Lieferländer suchen und anzeigen

Standardmäßig werden alle Lieferländer im Tab *Übersicht* angezeigt. Im Tab *Filter* können Sie die Auswahl der angezeigten Lieferländer anhand verschiedener Parameter filtern und damit entscheiden, welche Lieferländer in der Übersicht angezeigt werden sollen.

[.instruction]
Lieferländer suchen und anzeigen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Lieferländer » Tab: Filter*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-filter-lieferlaender>>.
. Klicken Sie auf *Suchen*. +
→ Die gefundenen Lieferländer werden im Tab *Übersicht* angezeigt.

[[tabelle-filter-lieferlaender]]
.Filteroptionen für Lieferländer
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ID*
|Filtert Lieferländer anhand der internen ID des Lieferlandes.

|*Name*
|Filtert Lieferländer anhand des Namens des Lieferlandes.

|*Standardname*
|Filtert Lieferländer anhand des Standardnamens des Lieferlandes.

|*Lager*
|Lager wählen, wenn nur die Lieferländer eines Lagers angezeigt werden sollen.

|*Aktiv*
|*Inaktiv* = Nur die Lieferländer anzeigen, die nicht aktiviert sind. +
*Aktiv* = Nur die Lieferländer anzeigen, die aktiviert sind. +
*Backoffice aktiv* = Nur Lieferländer mit der Eigenschaft *Backoffice aktiv* anzeigen. +
*Lieferant aktiv* = Nur Lieferländer mit der Eigenschaft *Lieferant aktiv* anzeigen.

|*Sprache (Name)*
|Sprache wählen.
|====

[#400]
== Region erstellen

Unter einer Region fassen Sie Lieferländer zusammen, für die gemeinsame Versandkosten gelten.

Im Tab *Neue Region* erstellen Sie die Regionen, indem Sie jeder Region die passenden Lieferländer zuordnen. Die Regionen sind dann im Tab *Übersicht* verfügbar und können dort angepasst werden. Überlegen Sie sich vor dem Erstellen, in wie viele und in welche Regionen sich Ihre Lieferländer sinnvoll zusammenfassen lassen, da in den Versandprofilen die Versandkosten pro Region und nicht für jedes Lieferland eingegeben werden. Aus europäischer Sicht sind z.B. mindestens die 3 folgenden Regionen sinnvoll: Inland, Europa und Welt.

[TIP]
.Sind alle benötigten Lieferländer aktiviert?
====
Bevor Sie Regionen erstellen können, müssen Sie alle Lieferländer aktivieren, die Sie für den Versand benötigen. Ein Lieferland kann nur einer Region zugeordnet werden und ist dann für weitere Regionen nicht mehr verfügbar.
====

[.instruction]
Region erstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Regionen*.
. Klicken Sie auf das Tab *Neue Region*. +
→ Unter *Verfügbare Länder* sehen Sie alle Lieferländer, die noch keiner Region zugeordnet wurden.
. Wählen Sie die Lieferländer unter *Verfügbare Länder*.
. Verwenden Sie die Pfeile, um die markierten Lieferländer in das Fenster *Ausgewählte Länder* zu verschieben. +
*_Hinweis:_* Die Doppelpfeil-Schaltflächen verschieben alle Länder eines Fensters in das andere Fenster.
. Geben Sie in der Zeile *Name* den Namen für die Region ein.
. *Speichern* Sie die Einstellungen. +
→ Die neu angelegte Region wird im Tab *Übersicht* angezeigt.
. Legen Sie nach gleichem Muster ggf. weitere Regionen an, bis alle Lieferländer einer Region zugeordnet sind und die Liste der verfügbaren Länder im Fenster *Verfügbare Länder* vollständig leer ist.

[IMPORTANT]
.Alle Lieferländer verteilen
====
Alle Lieferländer müssen einer Region zugeordnet werden, da sonst kein gültiges Versandprofil erstellt werden kann.
====

[.subhead]
Region bearbeiten

Gehen Sie wie im Folgenden beschrieben vor, um die Region zu bearbeiten.

[.instruction]
Region bearbeiten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Regionen*.
. Klappen Sie die Region im Tab *Übersicht* auf.
. Passen Sie die Einstellungen ein.
. *Speichern* Sie die Einstellungen.

[IMPORTANT]
.Bedingungen zum Löschen einer Region
====
Eine Region kann nur gelöscht werden, wenn sie in den Versandprofilen nicht mehr verwendet wird. Wenn Sie beim Löschen einer Region eine Fehlermeldung erhalten, prüfen Sie, ob in den Portotabellen noch Einstellungen zu dieser Region vorhanden sind. Eine Region kann erst gelöscht werden, wenn diese Querverbindungen vollständig entfernt wurden.
====

[#500]
== Artikelpakete und Absenderdaten eingeben

Im Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » Einstellungen* entscheiden Sie, welche Daten zum Versanddienstleister übermittelt werden sollen, wenn <<artikel/artikel-verwalten#920, Artikelpakete>> verwendet werden. Sie können entweder die Versanddaten der Basisartikel oder des Artikelpakets übermitteln. Die Einstellung zu Artikelpaketen gilt für alle Versanddienstleister in Ihrem plentymarkets System. Außerdem speichern Sie in diesem Menü Absenderdaten für alle in Ihrem plentymarkets System erstellten <<warenwirtschaft/lager-einrichten#, Lager>>. Die Absenderdaten werden pro Lager gespeichert. Sie finden in diesem Menü die Lager aller aktiven Lieferländer aufgelistet.

[.instruction]
Artikelpakete und Absenderdaten eingeben:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » Einstellungen*.
. Wählen Sie die Einstellung für *Artikelpakete*.
. Klappen Sie das Lager im Bereich *Absenderdaten* auf.
. Geben Sie die Daten ein.
. *Speichern* Sie die Einstellungen.

[#600]
== Beim Versanddienstleister registrieren

Um die Schnittstelle zum Versanddienstleister in plentymarkets einzurichten, registrieren Sie sich zunächst bei dem Versanddienstleister. Informieren Sie sich auf der Website des Versanddienstleisters.

[#700]
== Schnittstelle zum Versanddienstleister einrichten

Die Schnittstelle eines Versanddienstleisters richten Sie nach dem folgenden Schema ein. Welche Daten Sie im Menü des Versanddienstleisters eingeben müssen, erfahren Sie in den Unterkapiteln des Kapitels <<fulfillment/versand-vorbereiten#2500, Versanddienstleister im Überblick>>.

[.instruction]
Schnittstelle zum Versanddienstleister einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister*.
. Öffnen Sie das Menü des Versanddienstleisters.
. Geben Sie die Daten ein.
. Beachten Sie die Informationen zum Versanddienstleister in den Unterkapiteln des Kapitels <<fulfillment/versand-vorbereiten#2500, Versanddienstleister im Überblick>>.
. *Speichern* Sie die Einstellungen.

[#800]
== Versanddienstleister erstellen

Erstellen Sie den Versanddienstleister nach folgendem Schema.

[.instruction]
Versanddienstleister erstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versanddienstleister*.
. Klicken Sie im Tab *Übersicht* auf *Neu*. +
→ Ganz unten wird eine neue Zeile hinzugefügt.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versanddienstleister-erstellen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-versanddienstleister-erstellen]]
.Übersicht im Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versanddienstleister*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ID*
|Interne ID des Versanddienstleisters. Wird automatisch vergeben und kann nicht geändert werden.

|*Name (xy)*
|Name des Versanddienstleisters eingeben, wie er im Warenkorb und auf der Rechnung angezeigt werden soll. Den tatsächlichen Namen des Versanddienstleisters oder eine allgemeine Bezeichnung eingeben, z.B. Versicherter Versand. Dieser Name ist für Kunden sichtbar.

|*Name (Backend)*
|Name des Versanddienstleisters eingeben, wie er systemintern angezeigt werden soll. Den tatsächlichen Namen des Versanddienstleisters oder eine alternative Bezeichnung, die den Dienstleister charakterisiert, z.B. Pakete Schweiz, eingeben. Dieser Name ist für Kunden nicht sichtbar.

|*Versanddienstleister*
|Versanddienstleister wählen. Dies ist besonders wichtig, wenn unter *Name* eine abweichende Bezeichnung eingegeben und/oder keine Tracking-URL verwendet wurde.

|*Tracking-URL*
|Tracking-URL des Versanddienstleisters eingeben.

|*Adresse*
|Vollständige Adresse des Versanddienstleisters eingeben. +
*_Hinweis:_* Wenn im Versandprofil die Option *Einwilligung zur Datenübermittlung* aktiviert ist, wird die Adresse des Versanddienstleisters dann im Ceres-Webshop in einer Checkbox angezeigt. Wenn der Kunde die Checkbox aktiviert, stimmt er der Übertragung seiner Telefonnummer und E-Mail-Adresse an den Versandddienstleister zu.

|====

[#840]
[TIP]
.Tracking-URL
====
Viele Versanddienstleister bieten eine Sendungsverfolgung mittels Tracking-URL an. Kunden sehen die Tracking-URL während der Auftragsabwicklung oder erhalten die URL in einer E-Mail zur Versandmitteilung. Fügen Sie dazu die Template-Variable *$TrackingURL* in Ihre E-Mail-Vorlage ein.

Eine funktionsfähige Tracking-URL enthält die Paketnummer und oftmals die Postleitzahl des Empfängers. Beachten Sie daher, dass die Template-Variablen *$PaketNr* und ggf. *$PLZ* in der Tracking-URL enthalten sind.

Die aktuell gültigen, plentymarkets bekannten Tracking-URLs finden Sie im Kapitel des Versanddienstleisters. Über das Kapitel <<fulfillment/versand-vorbereiten#2500, Versanddienstleister im Überblick>> gelangen Sie auf die Kapitel der Versanddienstleister.
====

[#900]
== Versanddienstleister suchen

Standardmäßig werden alle erstellten Versanddienstleister im Tab *Übersicht* angezeigt. Im Tab *Filter* können Sie die Auswahl der angezeigten Versanddienstleister anhand verschiedener Parameter filtern und damit entscheiden, welche Versanddienstleister in der Übersicht angezeigt werden sollen. Sie können die Versanddienstleister jederzeit im Tab *Übersicht* bearbeiten.

[.instruction]
Versanddienstleister suchen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versanddienstleister*.
. Nehmen Sie die Einstellungen im Tab *Filter* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-filter-versanddienstleister>>.
. Klicken Sie auf *Suchen*. +
→ Die gefundenen Versanddienstleister werden im Tab *Übersicht* angezeigt.

[[tabelle-filter-versanddienstleister]]
.Filteroptionen für Versanddienstleister
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Suche ausführen. Die Versanddienstleister, die mit den eingestellten Filterkriterien übereinstimmen, werden im Tab *Übersicht* aufgelistet.

|*Reset*
|Eingestellte Filterkriterien zurücksetzen.

|*ID*
|Filtert Versanddienstleister anhand der internen ID des Versanddienstleisters.

|*Name*
|Filtert Versanddienstleister anhand des Namens des Versanddienstleisters.

|*Standardname*
|Filtert Versanddienstleister anhand des Standardnamen des Versanddienstleisters.

|*Tracking-URL*
|Filtert Versanddienstleister anhand der Tracking-URL des Versanddienstleisters.

|*Versanddienstleister*
|Filtert Versanddienstleister anhand der Option, die in der Dropdown-Liste *Versanddienstleister* gewählt wurde.

|*Sprache*
|Filtert Versanddienstleister anhand der Sprache.
|====

[#1000]
== Versandprofil erstellen

In den Versandprofilen stellen Sie Versandmöglichkeiten ein, die Ihre Kunden in der Kaufabwicklung wählen können oder die der Webshop bestimmten Auftragsarten automatisch zuweist. Zum Beispiel können Sie Ihren Kunden einen günstigen Standardversand und einen Expressversand gegen Aufpreis anbieten. Für eBay-Listings können Sie ein weiteres Versandprofil speichern, das Ihr Shop dann ausschließlich für Aufträge vom Marktplatz eBay verwendet. In den Unterkapiteln finden Sie Tipps und Tricks, die Sie beim Erstellen Ihrer Versandprofile anwenden können. Im Anschluss daran wird beschrieben, wie Sie in den Versandprofilen für jeden Versanddienstleister passende <<fulfillment/versand-vorbereiten#1500, Portotabellen>> für Ihre Regionen erstellen.

Erstellen Sie nun das Versandprofil für den Versanddienstleister. Die Anzahl der Versandprofile ist abhängig von den benötigten Versandservices. Erstellen Sie also pro Versandservice ein eigenes Versandprofil.

[.instruction]
Versandprofil erstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Klicken Sie auf *Neu*.
. Wählen Sie den eben erstellten Versanddienstleister aus der Dropdown-Liste.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-grundeinstellungen-versandprofil>>.
. *Speichern* Sie die Einstellungen. +
→ Das Tab *Portotabelle* wird angezeigt.

[[tabelle-grundeinstellungen-versandprofil]]
.Grundeinstellungen eines Versandprofils
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ID*
|Die ID des Versandprofils wird vom System vergeben und kann nicht geändert werden. Die ID wird nach dem Speichern des Versandprofils im Tab *Übersicht* angezeigt.

|*Versanddienstleister*
|Den zuvor erstellten Versanddienstleister aus der Dropdown-Liste wählen.

|*Name*
|Der Name in diesem Feld wird im Webshop angezeigt. Name wählen, der dem Kunden angezeigt werden soll, z.B. Standard oder Express. Wenn der Webshop in mehreren Sprachen betrieben wird, die Dropdown-Liste verwenden, um den Namen in jeder benötigten Sprache zu speichern.

|*Name (Backend)*
|Name für das Versandprofil eingeben. Der Name wird nur im System angezeigt und ist nicht sichtbar für Kunden.

|*Markierung*
|Icon wählen, das in der Auftragsübersicht angezeigt wird. Anhand der Markierung ist auf den ersten Blick sichtbar, welches Versandprofil gespeichert ist.

|*Priorität*
|Bestimmt die Reihenfolge, in der Versandprofile einer Region aufgelistet werden.

|*Kategorie*
|Ermöglicht eine zusätzliche Priorisierung der Versandprofile im Warenkorb. Standardmäßig ist immer Kategorie *1* eingestellt, d.h. alle Versandprofile werden gleichwertig angezeigt. Weitere Informationen sowie ein Beispiel finden Sie im Kapitel <<fulfillment/versand-vorbereiten#1300, Tipps und Tricks: Kategorie>>.

|*Artikel-Portoaufschlag*
|Aktivieren, um die im Artikeldatensatz gespeicherten Portoaufschläge zu aktivieren. Bis zu 2 Portoaufschläge können bei der Hauptvariante eines Artikels im Bereich *Versand* eingegeben werden. *Portoaufschlag 1* fügt den Versandkosten den dort gespeicherten Preis für den ersten Artikel hinzu, *Portoaufschlag 2* gilt ab dem zweiten Artikel. Portoaufschläge bieten sich für größere oder sperrige Artikel an, deren Versand teurer ist. +
Weitere Informationen finden Sie im Kapitel <<fulfillment/versand-vorbereiten#1100, Tipps und Tricks: Portoaufschläge>>.

|*POSTIDENT*
|Legitimationsprüfung durch die Deutsche Post AG. Dient zur Verifizierung von Personen, z.B. im Zusammenhang mit dem nötigen Altersnachweis für FSK 18-Artikel. Zur Aktivierung Häkchen setzen. +
Für den Versand von FSK 18-Artikeln müssen diese Artikel mit einem Versandprofil verknüpft sein, bei dem die POSTIDENT-Funktion aktiviert ist.

|*Bei neuen Artikeln aktivieren*
|Aktivieren, wenn das Versandprofil neuen Artikeln automatisch zugeordnet werden soll. +
Diese Option sollte bei mindestens einem Versandprofil gewählt sein, damit neuen Artikeln immer automatisch dieses Versandprofil zugewiesen wird. Ist ein Artikel nicht mit mindestens einem Versandprofil verknüpft, kann dieser Artikel auch nicht versendet werden.

|*Nachnahme*
|Option aktivieren, damit der Kunde im Ceres-Checkout im Webshop die Zahlungsart *Nachnahme* wählen kann. +
*_Wichtig:_* Voraussetzung ist, dass das Nachnahme-Plugin installiert ist. Das Plugin finden Sie im link:https://marketplace.plentymarkets.com/plugins/payment/cashondelivery_5255[plentyMarketplace^].

|*Paketstation aktiv*
|Option aktivieren, damit für den Kunden im Ceres-Checkout im Webshop verbesserte Eingabemöglichkeiten für das Feld *Paketstation* verfügbar sind. +
*_Wichtig:_* Voraussetzung ist, dass die Plugins link:https://marketplace.plentymarkets.com/plugins/templates/Ceres_4697[Ceres^] und link:https://marketplace.plentymarkets.com/plugins/templates/IO_4696[IO^] installiert sind.

|*Postfiliale aktiv*
|Option aktivieren, damit für den Kunden im Ceres-Checkout im Webshop verbesserte Eingabemöglichkeiten für das Feld *Postfiliale* verfügbar sind. +
*_Wichtig:_* Voraussetzung ist, dass die Plugins link:https://marketplace.plentymarkets.com/plugins/templates/Ceres_4697[Ceres^] und link:https://marketplace.plentymarkets.com/plugins/templates/IO_4696[IO^] installiert sind.

|*Einwilligung zur Datenübermittlung*
|Option aktivieren, damit im Ceres-Webshop eine Checkbox angezeigt wird. Aktiviert der Kunde diese Checkbox, stimmt er zu, dass ggf. seine Telefonnummer und E-Mail-Adresse an den Versanddienstleister übertragen werden.

|*Inselzuschlag*
|Viele Versanddienstleister verlangen für den Versand in Inselregionen höhere Gebühren. Auf diesen Kosten sollte der Händler nicht sitzenbleiben. Daher pro Versandprofil einen pauschalen Aufschlag für den Versand in Inselregionen festlegen. Die Postleitzahlen der Inselregionen sind systemseitig gespeichert. Der Auftrag wird automatisch abgeglichen. Bei Aktivierung des Inselzuschlags erfolgt eine Berechnung nur, wenn die Postleitzahl im System als Inselregion erkannt wird. +
Beim Berechnungstyp *Artikelporto* gilt der Inselzuschlag pro Stück.

|*Mandanten (Shops)*
|Eine der Optionen oder die Option *ALLE* wählen, wenn das Versandprofil für alle Webshops gelten soll. +
Diese Option wird nur angezeigt, wenn mindestens ein Mandant (Shop) eingerichtet ist.

|*Auftragsherkunft*
|Eine oder mehrere der Optionen wählen, um mögliche Auftragsherkünfte für dieses Versandprofil zu bestimmen, oder die Auswahl auf *ALLE* lassen, um alle Herkünfte freizugeben.

|*Gesperrte Zahlungsarten*
|Alle Zahlungsarten wählen, die für das Versandprofil nicht angeboten werden sollen. Bei Versandprofilen, die keine Nachnahmeoption enthalten oder bei denen Nachnahme nicht gewünscht wird, alle Optionen wählen, die mit Nachnahme in Verbindung stehen.

|*Gesperrte Kundenklassen*
|Eine oder mehrere Kundenklassen für das Versandprofil sperren.

|*Letzte Änderung*
|Bei Änderungen an den Einstellungen wird hier das Datum aktualisiert.

|*Versandgruppen*
|Wenn für Ihre Versandprofile Gruppen angelegt werden sollen, hier einen Namen für die Versandgruppe eingeben und auf *Hinzufügen* klicken. Diesen Namen in jedem Versandprofil, das zu dieser Gruppe gehören soll, eingeben. Somit entstehen verschiedene Gruppen, die unterschiedliche Versandprofile enthalten. +
*_Beispiel:_* Versandgruppe A enthält die Versandprofile 1 und 2. Versandgruppe B enthält die Versandprofile 3 und 4. Wenn einem Artikel nun die Versandprofile 3 und 4 zugewiesen werden sollen, am Artikel im Tab *Global* im Bereich *Versandprofile* die Versandgruppe B aus der Dropdown-Liste wählen. +
Mit dieser Funktion können sehr einfach die Versandprofile für neue Artikel zugewiesen werden.

|*Versandkennung*
|Dieses Feld ist derzeit ohne Funktion.

2+|eBay

|*Konto*
|Ein oder mehrere eBay-Konten oder die Option *ALLE* wählen. +
*_Wichtig:_* Mindestens 2 Konten müssen angelegt sein, andernfalls ist diese Option nicht sichtbar. Weitere Informationen finden Sie im Kapitel <<fulfillment/versand-vorbereiten#1200, Tipps und Tricks: Versandkosten von Bestellungen über eBay>>.

|*Listingtyp*
|Festlegen, für welchen Listing-Typ bei eBay dieses Versandprofil freigegeben werden soll.

2+|Weitere Optionen

|*Expressversand*
|Aktivieren, wenn dieses Versandprofil für einen Expressversand genutzt werden soll. +
*_Wichtig:_* Prüfen, ob Expressversand vom Service des Versanddienstleisters unterstützt wird. Nur dann kann die Option genutzt werden.

|*Treueprogramm*
|Ein oder mehrere Treueprogramme wählen. Die Treueprogramme können Sie mit <<maerkte/ebay/ebay-einrichten#6600, eBay Plus>> oder <<maerkte/amazon/amazon-einrichten#4200, Amazon>> verwenden. +
*_Wichtig:_* Versandprofile, bei denen hier ein Treueprogramm gewählt wurde, können ausschließlich für Aufträge des Marktplatzes genutzt werden und nicht für den Webshop. Wenn in einem Versandprofil z.B. die Option *eBay Plus* aktiviert ist, wird das Versandprofil nur noch für Aufträge von *eBay Plus* verwendet. Es gilt daher die Empfehlung, für die Nutzung eines Treueprogramms ein eigenes Versandprofil anzulegen.
|====

[#1100]
=== Tipps und Tricks: Portoaufschläge

Bei der Bestellung von Artikeln mit verschiedenen Portoaufschlägen werden die folgenden Teilbeträge addiert:

* Die im Versandprofil eingegebenen Versandkosten (Grundporto)
* Der Portoaufschlag 1 des Artikels mit dem höchsten eingegebenen Portoaufschlag
* Der Portoaufschlag 2 für jeden weiteren Artikel

[.subhead]
Beispiel: Portoaufschläge unterschiedlicher Artikel addieren

In diesem Beispiel bestellt ein Kunde 2 PCs und 2 Monitore. Für die Artikel sind folgende Versandkosten eingegeben:

*Artikel 1: PC*

* Grundporto (Versandprofil) = 3,99 EUR
* Portoaufschlag 1 = 5,00 EUR
* Portoaufschlag 2 = 3,00 EUR

*Artikel 2: Monitor*

* Grundporto (Versandprofil) = 3,99 EUR
* Portoaufschlag 1 = 4,00 EUR
* Portoaufschlag 2 = 2,00 EUR

Der Kunde bestellt 2 PCs und 2 Monitore. Bei der Bestellung ergeben sich folgende Versandkosten:

* 3,99 EUR (Grundporto) + 5,00 EUR (PC: Portoaufschlag 1) + 3,00 EUR (PC: Portoaufschlag 2) + 2,00 EUR (Monitor: Portoaufschlag 2) + 2,00 EUR (Monitor: Portoaufschlag 2) = 15,99 EUR

[.subhead]
Beispiel: Portoaufschläge für mehrere Exemplare des gleichen Artikels

In diesem Beispiel bestellt ein Kunde einmal einen PC, dann 2 PCs und dann 3 PCs. Für den Artikel sind folgende Versandkosten eingegeben:

*Artikel 1: PC*

* Grundporto (Versandprofil) = 3,99 EUR
* Portoaufschlag 1 = 5,00 EUR
* Portoaufschlag 2 = 3,00 EUR

Der Kunde bestellt einen PC, dann 2 PCs, dann 3 PCs. Bei der Bestellung ergeben sich folgende Versandkosten:

* Bei 1 PC: 3,99 EUR (Grundporto) + 5,00 EUR (Portoaufschlag 1) = 8,99 EUR
* Bei 2 PCs: 3,99 EUR (Grundporto) + 5,00 EUR (Portoaufschlag 1) + 3,00 EUR (Portoaufschlag 2) = 11,99 EUR
* Bei 3 PCs: 3,99 EUR (Grundporto) + 5,00 EUR (Portoaufschlag 1) + 3,00 EUR (Portoaufschlag 2) + 3,00 EUR (Portoaufschlag 2) = 14,99 EUR

[TIP]
.Versand nur über Aufschläge berechnen
====
Sie können die Funktion *Portoaufschlag* auch nutzen, um Ihre Versandkosten ausschließlich auf Basis der bestellten Ware berechnen zu lassen. Dazu müssen Sie allerdings Ihre Versandkosten pro Artikel in den Artikelstammdaten eingeben und im Versandprofil alle Portobeträge auf den Wert *Null* setzen.
====

[#1200]
=== Tipps und Tricks: Versandkosten von Bestellungen über eBay

Stellen Sie die Versandkosten für Bestellungen über eBay im Menü *System » Systemeinstellungen » Listings » Kaufabwicklung* ein. Wählen Sie dazu bei der Option *Versandkosten neuer eBay-Aufträge* die Einstellung *von eBay übernehmen* oder *von plentymarkets berechnen lassen*.

Sollen für eBay andere Versandkosten berechnet werden als bei Bestellungen über den Webshop, muss dafür ein eigenes Versandprofil erstellt werden. Bei diesem Versandprofil muss bei der Option *Auftragsherkunft* ausschließlich *eBay* eingestellt werden. Bei jedem Artikel, für den diese Einstellung gelten soll, muss dieses Versandprofil aktiviert werden. Demzufolge sind für diese Artikel mindestens 2 Versandprofile aktiviert: Einmal das Versandprofil mit den "normalen" Versandkosten und einmal das Versandprofil mit den eBay-Versandkosten.

[IMPORTANT]
.Eigenes Versandprofil pro eBay-Konto
====
Wenn Sie in Ihrem plentymarkets System mehrere eBay-Konten aktiviert haben, können Sie für jedes eBay-Konto ein eigenes Versandprofil festlegen. Die Konten können Sie dann unter der Option *eBay-Konto* im Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile » Tab: Base* wählen.
====

[#1300]
=== Tipps und Tricks: Kategorie

Die Kategorieoption ermöglicht eine zusätzliche Priorisierung der Versandprofile. Sie können damit bestimmen, welche Versandprofile im Warenkorb angezeigt werden. In der Grundeinstellung ist immer die Kategorie *1* eingestellt, d.h. es werden alle Versandprofile gleichwertig angezeigt.

Folgende Regeln gelten:

* Das Versandprofil mit der niedrigsten Kategorie wird immer angezeigt.
* Bei mehreren Artikeln wird das gemeinsame Versandprofil mit der niedrigsten Kategorie angezeigt.
* Haben die Artikel kein gemeinsames Versandprofil, wird das Versandprofil mit der niedrigsten Kategorie gewählt.

[TIP]
."Ausfall-Versandprofil" erstellen
====
Erstellen Sie ein Versandprofil, dessen Kategorie höher ist als die der anderen Versandprofile. Dieses "Ausfall-Versandprofil" wird nur gewählt, wenn alle anderen Versandprofile nicht greifen bzw. nicht gewählt werden können.
====

[.subhead]
Beispiel: FSK 18-Artikel zusammen mit anderen Artikeln verkaufen

Mit der Kategorieeinstellung können Sie Artikel mit dem Versandprofil *Übergabe eigenhändig* (z.B. FSK 18-Artikel) auch zusammen mit anderen Artikeln verkaufen. Dies lösen Sie wie im Folgenden beschrieben:

*Artikel A*

* Versandprofil 1 (Kategorie 1)
* Versandprofil 2 (Kategorie 2)

*Artikel B* (FSK 18-Artikel)

* Versandprofil 2 (Kategorie 2)
* Versandprofil 3 (Kategorie 5)

Wenn nur der Artikel A gekauft wird, wird das Versandprofil 2 nicht angezeigt, da ein Versandprofil mit niedrigerer Kategorie vorhanden ist. Wenn Artikel A und B zusammen gekauft werden, hat Versandprofil 2 die niedrigste gemeinsame Kategorie und wird somit ausschließlich angezeigt.

[#1400]
=== Tipps und Tricks: Versandprofilkombinationen zur Fehlervermeidung

Achten Sie darauf, dass bei allen Artikeln, die zusammen gekauft werden können, mindestens ein übereinstimmendes Versandprofil gespeichert ist. Befinden sich 2 oder mehr Artikel im Warenkorb, die kein gemeinsames Versandprofil haben, wird das Porto von beiden Versandprofilen addiert. Allerdings wird nur der Versanddienstleister mit der höheren Priorität im Warenkorb angezeigt. Solch eine Versandprofilkombination ist nicht vorgesehen und führt zu unerwünschten Ergebnissen.

Um dieses Fehlverhalten zu vermeiden, können Sie z.B. für alle Artikel ein DHL-Versandprofil speichern und nur für bestimmte Artikel ein zusätzliches Versandprofil.

[.subhead]
Beispiel: Kein gemeinsames Versandprofil

2 Artikel, die kein gemeinsames Versandprofil haben, befinden sich im Warenkorb.

*Artikel A*

* Versandprofil von DPD
* Pauschales Porto von 3,95 EUR

*Artikel B*

* Versandprofil von DHL
* Pauschales Porto von 2,95 EUR

Die Portobeträge der Versandprofile werden dann in der Kaufabwicklung im Webshop addiert. Der Kunde sieht also ein Gesamtporto von 6,90 EUR. Jedoch wird dem Kunden nur der Versanddienstleister mit der höheren Priorität im Warenkorb angezeigt.

[#1500]
== Portotabelle erstellen

Speichern Sie nun die Versandkosten für das Versandprofil im Tab *Portotabelle*. Speichern Sie die Portoeinstellungen für jede Region, die Sie im Versandprofil verwenden möchten. Wählen Sie zuerst den Berechnungstyp und das Porto. Nachdem Sie die Portotabelle gespeichert und neu geladen haben, sehen Sie ggf. weitere versanddienstleisterspezifische Einstellungen. Nehmen Sie daher zunächst die allgemeinen Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-portotabelle-versandprofil>>.

[IMPORTANT]
.Versandservices nicht bei jedem Versanddienstleister vorhanden
====
Nicht für alle Versanddienstleister ist die Auswahl eines Versandservices vorgesehen. Wenn vorhanden, werden die Versandservices in der Portotabelle des Versanddienstleisters angezeigt, nachdem Sie die Portotabelle gespeichert und neu geladen haben. Öffnen Sie das Versandprofil im Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*. Wechseln Sie in das Tab *Portotabelle* und klappen die Region auf. Im unteren Teil der Portotabelle werden die Versandservices angezeigt.
====

[.instruction]
Portotabelle erstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie das Versandprofil.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Wählen Sie einen Berechnungstyp aus der Dropdown-Liste. +
→ Je nachdem, welchen Berechnungstyp Sie wählen, werden im Folgenden unterschiedliche Feldnamen angezeigt.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-portotabelle-versandprofil>>.
. *Speichern* Sie die Einstellungen.
. Laden Sie die Portotabelle neu. +
→ Wenn vorhanden, werden nun die Versandservices angezeigt.
. Wählen Sie den Versandservice aus der Dropdown-Liste.

[[tabelle-portotabelle-versandprofil]]
.Portotabelle eines Versandprofils
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Speichern*
|Einstellungen speichern.

|*Einstellungen kopieren nach*
|Überträgt die Einstellungen einer Region auf eine andere Region. Ein Fenster mit einer Dropdown-Liste, die die Regionen zur Auswahl enthält, wird geöffnet. Region wählen und auf *Ausführen* klicken.

|*Verknüpfung löschen*
|Setzt alle Einstellungen zurück. Diese Funktion ist z.B. nötig, bevor eine Region gelöscht werden kann.

|*Berechnungstyp*
|<<fulfillment/versand-vorbereiten#1600, Berechnungstyp>> wählen. Der Berechnungstyp bildet die Grundlage für die Berechnung der Versandkosten.

2+|Versandkosten

|*Pauschales Porto*
|Versandkosten eingeben. +
Der angezeigte Feldname ist abhängig vom gewählten Berechnungstyp.

2+|Pauschalen

|*Versandkostenfrei ab Warenwert*
|Warenwert eingeben, ab dem die Lieferung für den Kunden versandkostenfrei ist. Der Warenwert bezieht sich auf den Bruttowarenwert. +
*_Wichtig:_* Wenn durch das Einlösen eines Aktionsgutscheins der Wert wieder unter dem hier eingegebenen Wert liegt, werden auch wieder Versandkosten berechnet.

|*Ab Warenwert ... ; +
... pauschale Versandkosten von*
|In das Feld *Ab Warenwert ...* den Warenwert eingeben, ab dem die Lieferung zu einer festen Pauschale erfolgt. Die Pauschale im Feld *... pauschale Versandkosten von* eingeben. +
Dieser Betrag darf nicht höher sein als der Betrag für die Pauschale *Versandkostenfrei ab Warenwert*, da der Versand ab diesem Wert bereits kostenfrei ist.

2+|Beschränkungen

|*Beschränkungstyp*
|Beschränkungstyp wählen. +
Die Standardwährung wird verwendet, wenn eine Beschränkung anhand des Warenwerts gewählt wurde. +
Das beim Artikel gespeicherte Bruttogewicht wird verwendet, wenn eine Beschränkung anhand des Gewichts gewählt wurde.

|*Mindestwert*
|Wert eingeben. Erst ab diesem Wert, bezogen auf den angegebenen Beschränkungstyp, ist das Versandprofil gültig. +
Wenn unter *Beschränkungstyp* die Einstellung *Maximum (Kubikmeter)* gewählt wurde, muss der Wert hier in mm eingegeben werden.

|*Maximalwert*
|Wert eingeben. Bis zu diesem Wert, bezogen auf den angegebenen Beschränkungstyp, ist das Versandprofil gültig. +
Wenn unter *Beschränkungstyp* die Einstellung *Maximum (Kubikmeter)* gewählt wurde, muss der Wert hier in mm eingegeben werden.

2+|Allgemeine Konfiguration

|*Standardpaket*
|<<fulfillment/versand-vorbereiten#1900, Versandpaket>> wählen, das als Standardpaket für dieses Versandprofil verwendet werden soll. +
Diese Option wird erst sichtbar, nachdem die Portotabelle gespeichert und neu geladen wurde.

|*E-Mail und Telefonnr. übertragen*
|Wählen, ob die E-Mail-Adresse und die Telefonnummer an den Dienstleister übertragen werden sollen oder nicht oder ob ein alternativer Wert übertragen werden soll. +
*_Hinweis:_* Standardmäßig werden diese Daten nicht an den Dienstleister übertragen (DSGVO-Konformität).

|*Alternative E-Mail*
|Diese Einstellung ist nur sichtbar, wenn in der Dropdown-Liste *E-Mail und Telefonnr. übertragen* die Option *Alternative übertragen* gewählt wurde. Alternative E-Mail-Adresse, die an den Dienstleister übertragen werden soll, eingeben.

|*Alternative Telefonnr.*
|Diese Einstellung ist nur sichtbar, wenn in der Dropdown-Liste *E-Mail und Telefonnr. übertragen* die Option *Alternative übertragen* gewählt wurde. Alternative Telefonnummer, die an den Dienstleister übertragen werden soll, eingeben.

|*Lieferfrist (in Tagen)*
|Die zu erwartende Lieferfrist in Tagen eingeben. Diese Angabe bezieht sich auf die Anzahl der Tage, die der Versanddienstleister normalerweise für das Versenden der Artikel benötigt. +
*_Hinweis:_* Diese Funktion kann erst mit der neuen Version von Ceres verwendet werden. Bitte dazu die Kategorie link:https://forum.plentymarkets.com/c/changelog/version-7[Changelog^] im Forum beobachten.

2+|Versanddienstleisterspezifische Einstellungen

|Versanddienstleistername
|*_Hinweis:_* Die Einstellungen des Versanddienstleisters werden erst sichtbar, nachdem die Portotabelle gespeichert und neu geladen wurde.

2+|Weitere Konfigurationen

|*Amazon Prime*
|Nur verfügbar bei Buchung des Moduls Multi-Channel.
|====

[#1600]
== Berechnungstyp in der Portotabelle wählen

Die Berechnungstypen im Tab *Portotabelle* bieten unterschiedliche Möglichkeiten, Versandkosten je nach Artikel zu berechnen. So können Sie eine gewichts- oder volumenabhängige Versandkostenberechnung oder eine mengenabhängige Staffelung speichern. Pro Region können Sie einen eigenen Berechnungstyp wählen. Im Folgenden wird jeder Berechnungstyp kurz erläutert. In <<tabelle-einstellungen-berechnungstypen>> finden Sie Hinweise, die generell für die Berechnungstypen gelten.

[[tabelle-einstellungen-berechnungstypen]]
.Allgemeine Einstellungen zu den Berechnungstypen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Maximumwerte*
|Wird der maximal gespeicherte Wert (Volumen, Gewicht, Preis, Menge) überschritten, können keine Versandkosten ermittelt werden. Daher sollte immer ein ausreichend hohes Maximum vorhanden sein.

|*Pauschalen*
|Zusätzlich kann ab einem bestimmten Warenwert ein pauschaler Versandkostenbetrag gespeichert werden. Erreicht die Bestellung diesen Warenwert oder wird dieser Warenwert überschritten, wird der pauschale Versandkostenbetrag berechnet. Diese Pauschalen sind dominant gegenüber den Werten der gespeicherten Gewichts-, Volumen- oder Mengentabellen.

|*Beschränkungen*
|Beschränkungen ermöglichen die Festlegung von Minimum- und Maximumwerten pro Versandprofil. Wenn ein Auftrag die eingegebenen Werte über- oder unterschreitet, kann das Versandprofil nicht für den Auftrag verwendet werden. Als Ausweichmöglichkeit für solche Fälle kann ein weiteres Versandprofil, z.B. von einem anderen Versanddienstleister, erstellt werden, das einen an die Beschränkungen anschließenden Wertebereich bereitstellt.
|====

[TIP]
.Template-Variablen
====
Zu den verschiedenen Berechnungstypen finden Sie <<omni-channel/online-shop/webshop-einrichten/cms-syntax#grundlagen-template-variablen, Template-Variablen>> im Menü <<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewsingleitem, CMS » Webdesign » Layout » ItemView » ItemViewSingleItem>>. Die Template-Variable *+$Volumen+* gibt keine Maße zurück, sondern das Volumen in Kubikmeter.
====

[#1610.subhead]
Berechnungstyp: Pauschal

Bei diesem Berechnungstyp stellen die eingegebenen Versandkosten die Gesamtsumme dar, d.h. unabhängig davon, wie viele Artikel der Kunde kauft, er bezahlt nur die hier eingegebenen Versandkosten.

Einen Aufschlag für jeden weiteren Artikel können Sie bei diesem Berechnungstyp einstellen, indem Sie am Artikel im Bereich *Versand* <<artikel/artikel-verwalten#290, Portoaufschläge>> eingeben und im Tab *Base* des Versandprofils die Option *Artikel-Portoaufschlag* aktivieren.

[#1620.subhead]
Berechnungstyp: Gewichtsabhängig

Bei dem Berechnungstyp *Gewichtsabhängig* werden in die Spalte *Maximum (g)* Grenzwerte für das Bruttogewicht in Gramm und in die Spalte *Betrag (EUR)* die Versandkostenbeträge eingefügt. Sie erstellen so eine Staffelung der Portokosten nach Gewicht. Mit einem Klick auf *Hinzufügen* fügen Sie weitere Staffelpreise hinzu.

[#1630.subhead]
Berechnungstyp: Volumenabhängig

Bei dem Berechnungstyp *Volumenabhängig* werden in die Spalte *Maximum (Kubikmeter)* Grenzwerte für das Volumen in Kubikmeter und in die Spalte *Betrag (EUR)* die Versandkostenbeträge eingefügt. Sie erstellen so eine Staffelung der Portokosten nach dem Volumen eines Artikels. Mit einem Klick auf *Hinzufügen* fügen Sie weitere Staffelpreise hinzu.

[WARNING]
.Maße müssen am Artikel gespeichert werden
====
Volumen werden nur korrekt berechnet, wenn Sie im Menü *Artikel » Artikel bearbeiten » Artikel öffnen* im Tab *Einstellungen* der Hauptvariante und dort im Bereich <<artikel/artikel-verwalten#270, Maße>> die Länge, Breite und Höhe des Artikels eingegeben haben. Fehlen diese Angaben, wird kein Volumen berechnet und die Berechnung der Versandkosten kann ebenfalls nicht erfolgen.
====

[#1640.subhead]
Berechnungstyp: Mengenabhängig

Bei dem Berechnungstyp *Mengenabhängig* werden in die Spalte *Maximum (Stk.)* Grenzwerte für die Stückzahlen und in die Spalte *Betrag (EUR)* die Versandkostenbeträge eingefügt. Sie erstellen so eine Staffelung der Portokosten nach Stückzahlen. Mit einem Klick auf *Hinzufügen* fügen Sie weitere Staffelpreise hinzu.

[#1650.subhead]
Berechnungstyp: Preisabhängig

Bei dem Berechnungstyp *Preisabhängig* werden in die Spalte *Maximum (EUR)* Grenzwerte für die Gesamtsumme eines Auftrags und in die Spalte *Betrag (EUR)* die Versandkostenbeträge eingefügt. Sie erstellen so eine Staffelung der Portokosten nach Einkaufswert des Artikels. Wenn alle eingekauften Artikel das gleiche Versandprofil verwenden, dann erhalten Sie eine Staffelung der Portokosten für den gesamten Einkauf.

[#1660.subhead]
Berechnungstyp: Artikelporto

Bei dem Berechnungstyp *Artikelporto* sind die Versandkosten abhängig von der Anzahl der Artikel. Je nachdem, welchen Betrag Sie im Feld *Jeder weitere Artikel* eingeben, erhöhen sich die Versandkosten für jeden weiteren Artikel um diesen Betrag.

[#1700]
== Versandkosten berechnen

Im Tab *Versandkosten berechnen* konfigurieren Sie die Versandkosten, die für den Artikelexport an Preisportale benötigt werden. Die allgemeinen Versandprofile werden für Preisportale nicht herangezogen. Konfigurieren Sie Einstellungen, die zu allen Artikeln, die Sie an Preisportale exportieren möchten, passen. Werden diese Einstellungen nicht konfiguriert, werden die Versandkosten fehlerhaft oder mit dem Eintrag "0" exportiert.

Weitere Informationen finden Sie auf der Handbuchseite <<daten/export-import/daten-exportieren#, Daten exportieren>> im Kapitel <<daten/export-import/daten-exportieren#30, Datenformate für Preissuchmaschinen exportieren>>.

Wählen Sie die Standardherkunft möglichst allgemein, z.B. *Mandant (Shop)*. Wählen Sie für die Standardversandregion eine Region, die alle Lieferländer der zu exportierenden Artikel enthält.

[TIP]
.Zahlungsart Vorabüberweisung/Vorkasse
====
Wählen Sie in jedem Fall auch die Zahlungsart *vorab Überweisung/Vorkasse* aus einer der Dropdown-Listen, damit diese Zahlungsart bei Ablehnung anderer Zahlungsarten als Alternative verwendet werden kann.
====

[.instruction]
Versandkosten berechnen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandkosten berechnen*.
. Wählen Sie für beide Konfigurationen die *Standardherkunft*, *Standardversandregion*, *Zahlungsart 1* und *Zahlungsart 2*.
. *Speichern* Sie die Einstellungen.

[#1800]
== Versandprofil aktivieren

Das Versandprofil muss am Artikel aktiviert werden, um einen Artikel mit den im Versandprofil gespeicherten Einstellungen zu versenden. Aktivieren Sie pro Artikel mindestens ein Versandprofil, da es sonst zu ungewollten Effekten bei der Versandkostenberechnung kommen kann.

[.instruction]
Versandprofil aktivieren:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab *Global*.
. Aktivieren Sie die Versandprofile.
. *Speichern* Sie die Einstellungen.

[IMPORTANT]
.Standardversandprofil
====
Wenn ein Auftrag Artikel enthält, bei denen kein Versandprofil aktiviert wurde, wird das Standardversandprofil aus dem Standard-Webshop für die Artikel verwendet. Das Standardversandprofil wählen Sie im Menü <<omni-channel/online-shop/webshop-einrichten/bestellvorgang#, System » Systemeinstellungen » Mandant » Mandant wählen » Bestellvorgang » Einstellungen>>. Wenn kein Standardversandprofil eingerichtet ist, wird das Versandprofil mit der höchsten Priorität verwendet.
====

[#1900]
== Versandpaket erstellen

Im Menü *System » Systemeinstellungen » Aufträge » Versand » Versandpakete* erstellen Sie Versandpakete für Ihre Versandprozesse. Sie können Versandpakete mit definierten Größen erstellen oder die Größe  von Ihrem plentymarkets System aus den Artikeldaten automatisch bestimmen lassen. Wenn Sie kein Versandpaket erstellen und einem Auftrag zuordnen, wird bei der Anmeldung automatisch ein Standardpaket eingestellt, dessen Volumen aus den Artikeldaten berechnet wird.

[TIP]
.Beispiele: Definierte Versandpakete und flexible Verpackung
====
Definierte Versandpakete: Ein Händler verschickt seine Artikel mit 2 verschiedenen Kartongrößen. Er legt dazu 2 Versandpakete an. Das Volumen ergibt sich aus den Abmessungen. +
Versandpaket 1: 30 cm x 25 cm x 40 cm +
Versandpaket 2: 50 cm x 50 cm x 25 cm

Flexible Verpackung: Für den Versand von Möbeln verwendet ein Händler Verpackungsmaterial, das je nach Größe des Versandguts individuell angepasst wird (Wellpappe, Folie etc.). Das Volumen wird aus den Artikeldaten berechnet.
====

Gehen Sie wie im Folgenden beschrieben vor, um ein Versandpaket zu erstellen.

[.instruction]
Versandpaket erstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Versandpakete*.
. Wechseln Sie in das Tab *Neues Versandpaket*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versandpaket-erstellen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-versandpaket-erstellen]]
.Einstellungen im Tab *Neues Versandpaket*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Bezeichnung*
|Name eingeben.

|*Volumenangabe*
|*vom Versandpaket beziehen* (Länge, Breite, Höhe) oder *von Artikeldaten beziehen (summiert)* wählen. +
Wenn die Option *von Artikeldaten beziehen (summiert)* gewählt wird, sind die Zeilen *Länge*, *Breite* und *Höhe* nicht mehr sichtbar.

|*Länge*, *Breite*, *Höhe*
|Maße des Versandpakets in Abhängigkeit zur Einheit eingeben.

|*Einheit*
|Einheit aus der Dropdown-Liste wählen.

|*Maximales Gewicht (KG)*
|Maximal zulässiges Gewicht in Kilogramm eingeben. +
*_Hinweis:_* Wenn dieses Gewicht überschritten wird, wird das Versandpaket mit der niedrigsten ID verwendet. Die Einstellungen in diesem Versandpaket haben keine weiteren Auswirkungen, da es sich um das Standardpaket in Ihrem System handelt. +
*_Beispiel:_* 2 Versandpakete sind im System eingerichtet: Versandpaket A mit der niedrigsten ID und keinen weiteren Einstellungen sowie Versandpaket B mit einem maximal zulässigen Gewicht von 10 kg. Wenn nun ein Auftrag mit einem Gewicht von 12 kg ins System kommt, greift Versandpaket B nicht mehr und Versandpaket A wird verwendet.


|*Maximales Volumen (summiert)*
|Maximal zulässiges Volumen in Kubikmeter eingeben. +
*_Hinweis:_* Dieser Wert bezieht sich auf das Gesamtvolumen des Versandpakets und setzt sich zusammen aus den Volumina der enthaltenen Artikel. Sie haben mit dieser Angabe einen Richtwert und können besser abschätzen, ob die Artikel eines Auftrags in das Versandpaket passen.

|*Mandant (Shop)*
|Mandant (Shop) aus der Dropdown-Liste wählen. Die Option *ALLE* wählen, wenn das Versandpaket für alle Webshops verfügbar sein soll.
|====

Wie Sie Versandpakete bearbeiten, hinzufügen oder löschen, ist auf der Handbuchseite <<fulfillment/versand-center#, Versand-Center nutzen>> beschrieben.

[#2300]
== Versandprozess über Prozesse steuern

Mit den <<automatisierung/prozesse/prozesse-einrichten#, Prozessen>> steht Ihnen ein Werkzeug zur Verfügung, mit dem Sie den gesamten Versandprozess abbilden können. Eine detaillierte und individuelle Einrichtung der Prozesse ist nötig, damit diese dann automatisiert ablaufen. Für die Versandabwicklung stehen z.B. die Aktionen <<automatisierung/prozesse/aktionen#340, Polling>>, <<automatisierung/prozesse/aktionen#380, Retourenetikett>>, <<automatisierung/prozesse/aktionen#390, Rücksendeschein>> und <<automatisierung/prozesse/aktionen#430, Versand-Center>> zur Verfügung.

[#2400]
== API-Log abrufen

Im Menü *Daten » API-Log » Tab: Versand Center API-Log* finden Sie Meldungen zu Sendungen, die Sie im Menü *Aufträge » Versand-Center* angemeldet haben. Wählen Sie den Versanddienstleister aus der Dropdown-Liste *Vorgang* sowie ein Datum und die angezeigten Vorgänge pro Seite. Nach einem Klick auf *Suchen* werden die Vorgänge angezeigt.

Weitere Informationen zu den API-Log-Einträgen von DHL Fulfillment und DPD Cloud Webservice finden Sie auf der Handbuchseite <<daten/api-log#, API-Log>>.

[#2500]
== Versanddienstleister im Überblick

<<tabelle-ueberblick-versanddienstleister>> listet die in plentymarkets verfügbaren Versanddienstleister auf. Mit einem Klick auf den Dienstleister in der Tabelle gelangen Sie in das Unterkapitel, in dem die versanddienstleisterspezifischen Einstellungen beschrieben sind.

[IMPORTANT]
.Versandservices nicht bei jedem Versanddienstleister vorhanden
====
Nicht für alle Versanddienstleister ist die Auswahl eines Versandservices vorgesehen. Wenn vorhanden, werden die Versandservices in der Portotabelle des Versanddienstleisters angezeigt, nachdem Sie die Portotabelle gespeichert und neu geladen haben. Öffnen Sie das Versandprofil im Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*. Wechseln Sie in das Tab *Portotabelle* und klappen die Region auf. Im unteren Teil der Portotabelle werden die Versandservices angezeigt.
====

[[tabelle-ueberblick-versanddienstleister]]
.In plentymarkets verfügbare Versanddienstleister im Überblick
[cols="1,3"]
|====
|Versanddienstleister |Erläuterung

|<<fulfillment/versand-vorbereiten#2700, DHL Easylog>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<fulfillment/versand-vorbereiten#2800, DHL Freight>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<fulfillment/versand-vorbereiten#2900, DHL Intraship/Versenden>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<fulfillment/versand-vorbereiten#3000, DHL plentymarkets Import>>
|Pollingformat. Für Händler innerhalb Deutschlands. Versand: international.

|<<fulfillment/versand-vorbereiten#3100, DHL Retoure Beilegeretiketten>>
|Für Händler innerhalb Deutschlands. Retoure: Deutschland.

|<<fulfillment/versand-vorbereiten#3200, DHL Retoure Online>>
|Für Händler innerhalb Deutschlands. Retoure: international.

|<<fulfillment/versand-vorbereiten#3300, DHL Supply Chain>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<fulfillment/versand-vorbereiten#3400, DHL UK>>
|Für Händler innerhalb des Vereinigten Königreichs. Versand: international.

|<<fulfillment/versand-vorbereiten#3500, DPD Cloud Webservice>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<fulfillment/versand-vorbereiten#3600, DPD DELISprint>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<fulfillment/versand-vorbereiten#3700, EasyPAK>>
|Für Händler innerhalb Österreichs. Versand: international.

|<<fulfillment/versand-vorbereiten#3800, GLS Germany>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<fulfillment/versand-vorbereiten#3900, Hermes 2-Mann-Handling>>
|Für Händler innerhalb Deutschlands. Versand: Deutschland und Europa.

|<<fulfillment/versand-vorbereiten#4000, Hermes ProfiPaketService>>
|Für Händler innerhalb Deutschlands. Versand: Deutschland und Europa.

|<<fulfillment/versand-vorbereiten#4100, MyDPD Business / iloxx>>
|Für Händler innerhalb Deutschlands. Versand: Deutschland und Europa.

|<<fulfillment/versand-vorbereiten#4210, Royal Mail (via NetDespatch)>>
|Für Händler innerhalb des Vereinigten Königreichs. Versand: international.

|<<fulfillment/versand-vorbereiten#4230, UK Mail (via NetDespatch)>>
|Für Händler innerhalb des Vereinigten Königreichs. Versand: Vereinigtes Königreich.

|<<fulfillment/versand-vorbereiten#4250, Parcelforce Worldwide>>
|Für Händler innerhalb des Vereinigten Königreichs. Versand: international.

|<<fulfillment/versand-vorbereiten#2600, PARCEL.ONE>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<fulfillment/versand-vorbereiten#4300, Swiss Post>>
|Für Händler innerhalb der Schweiz. Versand: Schweiz.

|<<fulfillment/versand-vorbereiten#4400, UPS>>
|Für Händler innerhalb Deutschlands. Versand: international.
|====


[#2700]
=== DHL Easylog

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://www.dhl.de/de/paket/geschaeftskunden/versandsoftware.html[DHL Easylog^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » DHL Easylog*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-dhl-easylog>>.
. *Speichern* Sie die Einstellungen.

[IMPORTANT]
.Absenderreferenznummern und Nachnahmeservice
====
Als Standardwert wird für das Datenfeld der Absenderreferenznummern, *POOL_V_ABS_REFNR*, die Ziffer 1 ausgegeben. Andere Absenderreferenznummern sind möglich, z.B. für die Zahlungsart *Nachnahme*. Stimmen Sie diese Einstellungen ggf. mit dem DHL-Support ab. +
Wählen Sie für den Nachnahmeservice für Inland die ID 114 oder 134. Für Ausland ist die ID 5311 die Standardeinstellung.
====

[[tabelle-schnittstelle-dhl-easylog]]
.Einstellungen der Schnittstelle zu DHL Easylog
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Standard-Absenderreferenznummer* +
*Nachnahme-Absenderreferenznummer* +
*Nachnahmeservice Inland* +
*Nachnahmeservice Ausland*
|Daten eingeben, wie von DHL erhalten.

|*Artikelmenge berücksichtigen (Zollwarenliste)*
|Option aktivieren, wenn bei Ausfuhrlieferungen für die Warenwertermittlung die Artikelmenge gemäß des Auftrags berücksichtigt werden soll.
|====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich *DHL Easylog* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versandservices-dhl-easylog>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-versandservices-dhl-easylog]]
.Versandservices von DHL Easylog im Tab *Portotabelle*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*DHL-Verfahren*
|Die Verfahrensnummer legt fest, ob es sich um einen nationalen, europäischen, internationalen oder Expressversand handelt.

|*DHL-Produkt*
|Je nach Verfahren stehen unterschiedliche Produkte zur Verfügung.

|*DHL-Service*
|Je nach Verfahren stehen unterschiedliche Services, wie z.B. Rückschein oder Transportversicherung, zur Verfügung.

|*DHL-Teilnahme*
|Bei der DHL-Teilnahme handelt es sich um eine Art Vertrag über die Transportdienstleistung.
|====

[IMPORTANT]
.Berechnung des Nachnahmebetrags
====
Wenn bei einem Auftrag eine Paketanzahl größer gleich 1 gespeichert wurde, wird an DHL als Nachnahmebetrag der Rechnungsbetrag geteilt durch die Anzahl der Pakete übermittelt.
====

[#2800]
=== DHL Freight

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:http://www.dhl.de/de/logistik/frachttransport/land-schienentransport.html[DHL Freight^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » DHL Freight*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-dhl-freight>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-dhl-freight]]
.Einstellungen der Schnittstelle zu DHL Freight
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Niederlassung*
|Dreistellige Abkürzung eingeben, wie von DHL erhalten.

|*Absenderdaten*
|Firmenname eingeben.

|*Beschreibung der Güter*
|Beschreibung der Branche eingeben.

|*Versendernummer, FTP-Benutzer, FTP-Passwort*
|Daten eingeben, wie von DHL erhalten.

|*FTP-In/Out-Verzeichnis*
|Aktivieren, um die FTP-Verzeichnisstruktur von DHL Freight zu nutzen.
|====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich *DHL Freight* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versandservices-dhl-freight>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-versandservices-dhl-freight]]
.Versandservices von DHL Freight im Tab *Portotabelle*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*DHL-Produkt*
|Eines der folgenden Produkte aus der Dropdown-Liste wählen: +
*Standard* +
*Express nächster Tag* +
*Express, Zustellung nächster Tag vor 10 Uhr* +
*Express, Zustellung nächster Tag vor 12 Uhr* +
*Europlus*

|*DHL-Frankatur*
|Eine der folgenden Frankaturen aus der Dropdown-Liste wählen: +
*Unfrei* +
*Freigrenze Versandland* +
*Freigrenze Empfangsland* +
*Frei Haus unverzollt/unversteuert* +
*Frei Haus verzollt/unversteuert* +
*Frei Haus verzollt/versteuert*
|====

[#2900]
=== DHL Intraship/Versenden

[IMPORTANT]
.Verwendung des Plugins DHL Shipping (Versenden)
====
Nutzen Sie über die Schnittstelle zum DHL Geschäftskundenportal die Funktion *Versenden*. Das Plugin *DHL Shipping (Versenden)* steht Ihnen im link:https://marketplace.plentymarkets.com/plugins/integration[plentyMarketplace^] zur Verfügung.

Die in plentymarkets integrierte Schnittstelle wird weiterhin unter *DHL Intraship/Versenden* geführt, bis DHL uns darüber informiert hat, dass alle Kunden *DHL Versenden* nutzen. Die Schnittstelle DHL Intraship/Versenden sowie Einstellungen, die diese Schnittstelle in anderen Menüs betreffen, gelten bis zur Abschaltung von DHL Intraship für bestehende DHL Intraship-Kunden.
====

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Weiter unten in diesem Kapitel finden Sie Informationen über DHL-Exportdokumente.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:http://www.dhl.de/de/paket/geschaeftskunden/versandsoftware.html[DHL Intraship/Versenden^] in plentymarkets einzurichten.



[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » DHL Intraship/Versenden*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-dhl-intraship-versenden>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-dhl-intraship-versenden]]
.Einstellungen der Schnittstelle zu DHL Intraship/Versenden
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Stammdaten

|*Abrechnungsnummern*
|Gemäß des DHL-Vertrages Abrechnungsnummern eingeben. Pro Abrechnungsnummer können eigene Absenderdaten gepflegt werden. Die 14-stellige DHL-Abrechnungsnummer setzt sich folgendermaßen zusammen: +
*EKP* = Kundennummer; besteht aus den ersten 10 Ziffern der Abrechnungsnummer. +
*Verfahren* = Legt das DHL-Produkt fest, das für diese Abrechnungsnummer gilt. Dies sind die mittleren beiden Ziffern der Abrechnungsnummer. +
*_Wichtig:_* Beachten Sie dazu die Erläuterungen in der Box unterhalb der Tabelle. +
*Teilnahme* = Die letzten beiden Zeichen der Abrechnungsnummer (nur Ziffern oder Buchstaben sind zulässig).

|*Login-Name*
|Login-Name darf keine Umlaute enthalten. Die Verwendung von Umlauten kann zu einer Abweisung über die Schnittstelle führen, auch wenn die Webseite den Login-Namen akzeptiert.

|*Passwort*
|Passwort darf maximal 20 Zeichen lang sein. Zwar ist bei DHL die Verwendung eines längeren Passworts möglich, über die plentymarkets Schnittstelle erlaubt DHL jedoch maximal 20 Zeichen. Ein Passwort mit mehr als 20 Zeichen führt zu Fehlern bei der SOAP-Übergabe.

|*Alternative Telefonnummer für Auslandskunden*
|Bei Auslandssendungen wird die Telefonnummer des Empfängers standardmäßig von DHL auf dem Etikett gedruckt, damit DHL diesen bei Bedarf erreichen kann. Wenn das nicht gewünscht ist, hier z.B. eine Folge von Nullen oder "Keine Tel.-Nr." eingeben. Dieser Eintrag überschreibt dann die Telefonnummer von Auslandskunden. +
Die Option ist auch wichtig für den Fall, dass im Layout die Telefonnummer für Auslandskunden nicht als Pflichtfeld markiert wurde und die Sendung somit von DHL abgelehnt würde.

|*Etiketterzeugung erzwingen*
|Festlegen, ob bei der Anmeldung einer Sendung im Versand-Center über DHL Intraship/Versenden auch dann ein Versandetikett erzeugt werden soll, wenn keine oder unvollständige Daten für die Adresse vorhanden sind. +
*Ja* = DHL führt die Korrektur der fehlerhaften Daten durch und berechnet diese Korrektur (Standardeinstellung). +
*Nein* = Nicht kodierbare Sendungen werden bei der Anmeldung bei DHL Intraship/Versenden mit einer Fehlermeldung abgelehnt. Der Auftrag wird nicht angemeldet und in plentymarkets wird kein Versandetikett generiert.

|*Empfänger-E-Mail*
|Wählen, ob die E-Mail-Adresse des Empfängers übertragen werden soll.

2+|Absenderdaten

|*Firma, Absenderadresse, Kontaktperson, Bankdaten*
|Absenderdaten eingeben.

|*Mischkalkulation*
|Wählen, ob die Mischkalkulation aktiviert werden soll.

|*Frankatur bei Ausfuhrsendungen*
|Wählen, ob Zoll und Steuern vom Kunden (DAP) oder vom Händler (DDP) bezahlt werden.

|*Versandetikett*
|*Logo* = Die Dateigröße eines Logos ist auf 100 KB begrenzt. Das Logo sollte einem Seitenverhältnis von 3:4 und einer effektiven Größe von 15 x 20 mm entsprechen (Höhe x Breite). +
*_Wichtig:_* Die URL des Logos darf nur mit *http://* hinterlegt werden. +
*Alternativ benutze Adressdaten von folgender Abrechnungsnummer* = Eine zuvor gespeicherte Abrechnungsnummer aus der Dropdown-Liste wählen, um die Daten zu übernehmen.
|====

[IMPORTANT]
.DHL-Abrechnungsnummer
====
Die mittleren beiden Ziffern der Abrechnungsnummer *Verfahren* stehen für folgende DHL-Produkte: DHL Paket (01), Regionalpaket AT (02), DHL Europaket (54), DHL Paket International (53), DHL Domestic Express (71) und DHL Officepack (72). +
*_Wichtig:_* DHL Intraship/Versenden nutzt für das Verfahren Regionalpaket AT die 01. Da es in plentymarkets zu Konflikten mit DHL Paket kommt, benutzen wir intern die 02. Für DHL Domestic Express wird die 71 benutzt, damit es nicht zu Konflikten mit DHL Officepack kommt. An DHL wird selbstverständlich die korrekte Nummer gesendet.
====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich *DHL Intraship/Versenden* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versandservices-dhl-intraship-versenden>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-versandservices-dhl-intraship-versenden]]
.Versandservices von DHL Intraship/Versenden im Tab *Portotabelle*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*DHL-Abrechnungsnummer*
|Abrechnungsnummer aus der Dropdown-Liste wählen.

|*DHL-Service*
|Einen, mehrere oder *ALLE* Services wählen.
|====

[#2950.subhead]
DHL-Exportdokumente

DHL-Exportdokumente werden ausschließlich für Aufträge erzeugt, die mit dem Produkt *DHL Paket International* versendet werden und bei denen es sich um Ausfuhrlieferungen handelt. Ausfuhrlieferungen muss eine Zollinhaltserklärung, ein sogenanntes CN23-Dokument, und eine Paketkarte, ein sogenanntes CP 71-Dokument, beigelegt werden. *DHL Paket International* kann auch für innergemeinschafltiche Lieferungen genutzt werden, allerdings werden dann keine Exportdokumente erzeugt.

Ausfuhrlieferungen dürfen maximal 5 Artikelpositionen enthalten. Pro Artikelposition werden die folgenden Parameter gemeldet: Gewicht, Zolltarifnummer, Herstellerland, Artikelname, Warenwert und Menge.

Wenn Sie die DHL Intraship/Versenden-Schnittstelle verwenden, können Sie die Exportdokumente über das Menü *Aufträge » Fulfillment* manuell erzeugen. Damit Aufträge für das Erzeugen der Exportdokumente gefunden werden können, müssen diese zuvor erfolgreich über das Menü *Aufträge » Versand-Center* bei DHL Intraship/Versenden angemeldet worden sein. Außerdem muss eine Rechnung für diese Aufträge vorhanden sein.

[TIP]
.Exportdokumente über DHL Shipping-Plugin automatisch im Versand-Center
====
Wenn Sie das DHL Shipping-Plugin verwenden, werden die Exportdokumente automatisch mit der Anmeldung im Versand-Center beim Versandetikett gespeichert. Diese Funktion ist ab Version 1.3 verfügbar. Das DHL Shipping-Plugin steht Ihnen kostenlos im link:https://marketplace.plentymarkets.com/plugins/integration/DHLShipping_4871[plentyMarketplace] zur Verfügung.

====

[.instruction]
Exportdokument für DHL Intraship/Versenden erzeugen:

. Öffnen Sie das Menü *Aufträge » Fulfillment*.
. Klappen Sie das Untermenü *DHL Intraship-Exportdokumente erzeugen* auf.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-dhl-exportdokumente>>.
. Klicken Sie auf das Zahnrad.  +
→ Die Exportdokumente werden als PDF erzeugt.

[[tabelle-dhl-exportdokumente]]
.DHL-Exportdokumente erzeugen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Auftragsstatus*
|Auftragsstatus der Daten, für die Exportdokumente erzeugt werden sollen, wählen.

|*Versanddatum*
|Versanddatum, für das die Daten gesucht werden sollen, wählen.

|*Limit*
|Limit für die Dokumenterzeugung wählen.
|====

[TIP]
.Warenausgang per Ereignisaktion buchen
====
Wenn Sie mit dem Erzeugen der Exportdokumente gleichzeitig den Warenausgang buchen möchten, können Sie das über eine Ereignisaktion im Menü *System » Systemeinstellungen » Aufträge » Ereignisse* erledigen. Weitere Informationen finden Sie auf der Handbuchseite <<automatisierung/ereignisaktionen#, Ereignisaktionen>>.
====

[.subhead]
Tracking-URL von DHL

Die aktuell gültige, plentymarkets bekannte Tracking-URL von DHL lautet: +
*+https://nolp.dhl.de/nextt-online-public/de/search?piececode=[PaketNr]+*.

[#3000]
=== DHL plentymarkets Import

Das <<automatisierung/prozesse/aktionen#340, Pollingformat>> DHL plentymarkets Import bietet Ihnen die Möglichkeit, DHL mit einer link:https://www.dhl.de/de/paket/information/geschaeftskunden/service-alterssichtpruefung.html[Alterssichtprüfung^] bei der Lieferung Ihrer Artikel, wie z.B. Liquids für E-Zigaretten, zu beauftragen. Mit diesem Pollingformat erzeugen Sie eine CSV-Datei für den Datenimport zu DHL. Die Datei wird dann im DHL Geschäftskundenportal hochgeladen, um die Sendungen anzumelden und Labels zu erhalten. Die Einstellungen im DHL Geschäftskundenportal sind Bedingung für die Nutzung der Services in plentymarkets. Dort geben Sie auch die Referenzen an, die Sie beim Einrichten der Portotabellen in plentymarkets benötigen.

Nehmen Sie die im Folgenden beschriebenen Einstellungen vor, um den DHL-Service *Alterssichtprüfung* einzurichten:

* Einstellungen im DHL Geschäftskundenportal vornehmen
* Merkmal erstellen
* Grundeinstellung vornehmen
* Merkmal am Artikel verknüpfen
* Versandoption wählen
* CSV-Datei erzeugen und zu DHL hochladen

[TIP]
.Aufträge mit Altersgrenzen
====
Sind in einem Auftrag Artikel mit unterschiedlichen Altersgrenzen enthalten, "sticht" die 18. Sobald mindestens eine Artikelposition im Auftrag eine Prüfung auf 18 verlangt, gilt diese Altersgrenze für den gesamten Auftrag.
====

[#3010]
==== Einstellungen im DHL Geschäftskundenportal vornehmen

Nehmen Sie zunächst die Einstellungen im link:https://www.dhl-geschaeftskundenportal.de/webcenter/portal/gkpExternal?_afrLoop=2465780077903302#!%40%40%3F_afrLoop%3D2465780077903302%26_adf.ctrl-state%3D11moofew5r_4[DHL Geschäftskundenportal^] vor.

[#3020]
==== Merkmal erstellen

Erstellen Sie im Menü *System » Systemeinstellungen » Artikel » Merkmale* ein Merkmal vom Merkmaltyp *Auswahl*. Speichern Sie für die Auswahl zur Altersgrenze 16 Jahre den Wert *A16* und zur Altersgrenze 18 Jahre den Wert *A18*.

Weitere Informationen finden Sie auf der Handuchseite <<artikel/artikel-verwalten#, Artikel verwalten>> im Kapitel <<artikel/artikel-verwalten#500, Merkmale erstellen>>.

[#3030]
==== Grundeinstellung vornehmen

Wählen Sie im Menü *System » Systemeinstellungen » Artikel » Einstellungen* das soeben erstellte Merkmal aus der Dropdown-Liste *Artikelmerkmal zur Alterssichtprüfung*. *Speichern* Sie die Einstellungen.

[#3040]
==== Merkmal am Artikel verknüpfen

Verknüpfen Sie das Merkmal bei jedem Artikel, der die Alterssichtprüfung erhalten soll.

[.instruction]
Merkmal am Artikel verknüpfen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Merkmale*.
. Aktivieren Sie das soeben erstellte Merkmal im Bereich *Weitere Merkmale aktivieren*.
. *Speichern* Sie die Einstellungen. +
→ Das Merkmal wird im Bereich *Merkmale* angezeigt.
. Wählen Sie den Wert für den Artikel gemäß der Altersfreigabe wie oben erstellt aus der Dropdown-Liste.
. *Speichern* Sie die Einstellungen.

Weitere Informationen finden Sie auf der Handbuchseite <<artikel/artikel-verwalten#, Artikel verwalten>> im Kapitel <<artikel/artikel-verwalten#80, Merkmale aktivieren>>.

[#3050]
==== Versandoption wählen

Der Service *Alterssichtprüfung* ist in der Portotabelle verfügbar.

[.instruction]
Versandoption wählen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen*.
. Wechseln Sie in das Tab *Versandprofile*.
. Öffnen Sie das Versandprofil von DHL.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Wählen Sie im Bereich *DHL plentymarkets Import* aus der Dropdown-Liste *Produkt* die Option *DHL Paket*.
. Aktivieren Sie unter *Services* die Option *Alterssichtprüfung*.
. *Speichern* Sie die Einstellungen.

[#3060]
==== CSV-Datei erzeugen und zu DHL hochladen

Erzeugen Sie nun die CSV-Datei in den Prozessen oder im Menü *Aufträge » Versand-Center » Tab: Polling*. Speichern Sie Datei und laden Sie sie im DHL Geschäftskundenportal hoch.

[#3100]
=== DHL Retoure Beilegeretiketten

Mit DHL Retoure Beilegeretiketten erzeugen Sie Etiketten für Aufträge, die über DHL innerhalb Deutschlands ausgeliefert werden. Ihr Kunde erhält bereits bei der Lieferung ein komplett vorbereitetes Retourenlabel. Im Fall der Rücksendung, z.B. aufgrund von Gewährleistungen oder Reparaturen, muss die Ware nur noch eingepackt und das Label angebracht werden. Die Etiketten werden per Ereignisaktion erzeugt und sind dann im Versand-Center zum Abruf und Ausdruck verfügbar.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://www.dhl.de/de/paket/geschaeftskunden/ab-200-pakete/nationaler-versand/retoure.html[DHL Retoure Beilegeretiketten^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » DHL RETOURE Beilegeretiketten*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-dhl-retoure-beilegeretiketten>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-dhl-retoure-beilegeretiketten]]
.Einstellungen der Schnittstelle zu DHL Retoure Beilegeretiketten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Empfänger*
|Daten des Empfängers eingeben.

|*Abrechnungsnummer*
|Abrechnungsnummer eingeben, wie von DHL erhalten.

|*Kundenkennung*
|Kundenkennung eingeben, wie von DHL erhalten.

|*Leitcode-Sequenz*
|Daten eingeben. Straßencode und Hausnummer immer dreistellig eingeben, d.h. die Zahl 10 als 010 eingeben.

|*Service*
|Service wählen.
|====

Richten Sie nun eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um die Retourenetiketten automatisch zu erzeugen.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das *Ereignis* gemäß <<tabelle-ereignisaktion-dhl-retourenetiketten>>.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß <<tabelle-ereignisaktion-dhl-retourenetiketten>> vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
[[tabelle-ereignisaktion-dhl-retourenetiketten]]
.Ereignisaktion zum automatischen Erstellen von Retourenetiketten für DHL
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage: Neuer Auftrag*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*; ggf. weitere wie Gewährleistung und Reparatur

|*Filter 2*
|*Versand &gt; Lieferland*
|*Deutschland*

|*Filter 3*
|*Auftrag &gt; Auftragslager* (optional)
|

|*Filter 4*
|*Auftrag &gt; Herkunft* (optional)
|

|*Aktion 1*
|*Retoure &gt; DHL Retouren-Label generieren*
|*DHL Retoure Beileger*

|*Aktion 2*
|*Auftrag &gt; Status ändern* (optional)
|
|
|====


[#3200]
=== DHL Retoure Online

DHL Retoure Online ermöglicht das Erzeugen von Retourenetiketten für Aufträge aus verschiedenen Lieferländern. Die Etiketten sind dann im Menü *Aufträge » Versand-Center » Tab: Retoure* verfügbar. Sie können Ihrem Kunden das Etikett auch im *Mein Konto*-Bereich des Webshops zur Verfügung stellen oder dem Kunden das Etikett über eine Ereignisaktion automatisch per E-Mail senden.

[#3210]
==== Lager einrichten

Sie benötigen ein Lager, um die Informationen, die Sie von DHL für Retouren erhalten, zu speichern. In plentymarkets gibt es verschiedenen Lagertypen. Für Retouren eignet sich insbesondere der Lagertyp *Reparatur*. Das Reparaturlager kann dann über die Einstellung *Zugeordnetes Reparaturlager* im Menü *System » Systemeinstellungen » Waren » Lager » Lager wählen » Einstellungen* einem Hauptlager vom Typ *Vertrieb* zugeordnet werden. Wenn später ein Retourenetikett erzeugt wird, wird anhand des Lagers des Auftrags das zugehörige Vertriebs- oder Reparaturlager verwendet.

Wenn Sie noch kein Lager erstellt haben, erstellen Sie zunächst ein Lager oder ein Vertriebs- und Reparaturlager im Menü *System » Systemeinstellungen » Waren » Lager*. Wie Sie ein Lager erstellen, ist auf der Handbuchseite <<warenwirtschaft/lager-einrichten#, Lager einrichten>> beschrieben.

[IMPORTANT]
.Verfügbare Lagertypen für DHL Online Retoure
====
Nur Lager der Typen *Vertrieb* und *Reparatur* stehen für DHL Online Retoure zur Verfügung.
====

[#3220]
==== Schnittstelle einrichten

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:http://www.dhl.de/de/paket/geschaeftskunden/ab-200-pakete/nationaler-versand/retoure.html[DHL Retoure Online^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » DHL Retoure Online*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-dhl-retoure-online>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-dhl-retoure-online]]
.Einstellungen der Schnittstelle zu DHL Retoure Online
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Portal-ID, Benutzername, Passwort*
|Daten eingeben, wie von DHL erhalten.

|*Gültigkeit zugeordneter Etiketten*
|Dauer der Gültigkeit von zugeordneten Etiketten aus der Dropdown-Liste wählen. +
Zugeordnet heißt, dass die Etiketten bereits einer Retoure zugeordnet sind. Nach dem gewählten Zeitraum sind die Etiketten nicht mehr zum Download verfügbar.

|*Gültigkeit unzugeordneter Etiketten*
|Dauer der Gültigkeit von unzugeordneten Etiketten aus der Dropdown-Liste wählen. Nach dem gewählten Zeitraum sind die Etiketten nicht mehr zum Download verfügbar.

|*Retourenempfänger*
|Lager aufklappen. Die Einstellungen für die Länder, wie von DHL erhalten, bei dem Lager eingeben. Wenn in einem Reparaturlager keine Einträge stehen und das Lager einem Vertriebslager zugeordnet ist, werden die Einstellungen des Vertriebslagers verwendet. +
Das Eingeben der Informationen im Vertriebslager dient somit der Sicherheit und ist nicht zwingend notwendig. Die Auswahl des Retourenempfängers erfolgt anhand des Auftragslagers. Nur Lager der Typen *Vertrieb* und *Reparatur* stehen zur Verfügung.
|====

[#3230]
==== Alter Webshop: Retourenanlage erlauben

Legen Sie fest, ob Sie Ihren Kunden erlauben, Retouren im Mein Konto-Bereich im alten Webshop (Callisto-Webshop) selbst anzulegen oder nicht.

[.instruction]
Retourenanlage im alten Webshop erlauben:

. Öffnen Sie das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Mein Konto » Einstellungen*.
. Wählen Sie in der Zeile *Retoure* eine Option aus der Dropdown-Liste. Beachten Sie dazu die Erläuterungen in <<tabelle-retourenanlage-erlauben>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-retourenanlage-erlauben]]
.Retourenanlage im alten Webshop erlauben
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Retoure*
|*aktiviert* = Kunde kann Retouren im Mein Konto-Bereich im alten Webshop (Callisto-Webshop) anlegen. Etiketten werden jedoch nicht bereitgestellt. Wie Sie weiter verfahren, wenn der Kunde eine Retoure anmeldet, bleibt Ihnen überlassen. Sie können dem Kunden z.B. ein Etikett per E-Mail zusenden. +
Wenn Sie erlauben, dass Kunden Retouren selbst anlegen können, stehen die <<auftraege/auftraege-verwalten#410, Retourengründe>>, die Sie eingegeben haben, auch im *Mein Konto*-Bereich zur Auswahl. +
*DHL Retoure Online* = Kunde kann Retouren im Mein Konto-Bereich im alten Webshop (Callisto-Webshop) anlegen und kann anschließend das Retourenetikett von DHL herunterladen und ausdrucken. +
*deaktiviert* = Kunde kann keine Retoure anlegen. Wie Sie Retouren stattdessen handhaben, müssen Sie selbst entscheiden. Kunden können z.B. auch telefonisch oder per E-Mail Retouren bei Ihnen melden.
|====

[NOTE]
.Ereignisaktionen: Retourenetikett automatisch generieren und per E-Mail an den Kunden versenden
====
Sie haben die Möglichkeit, das Retourenetikett automatisch zu erzeugen. Richten Sie dazu eine Ereignisaktion im Menü *System » Systemeinstellungen » Aufträge » Ereignisse* ein. Wählen Sie ein Ereignis Ihrer Wahl und als Aktion die Option *Retoure > DHL-Retourenlabel generieren*.

Um das Retourenetikett dann automatisch an Ihren Kunden zu versenden, müssen Sie eine eine E-Mail-Vorlage im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen* einrichten und aus der Dropdown-Liste *PDF-Anhang* die Option *Retourenlabel* wählen. Anschließend richten Sie eine weitere Ereignisaktion ein und wählen als Ereignis *Dokumente > Retourenlabel gespeichert* und als Aktion *Kunde > E-Mail versenden*.
====

[#3300]
=== DHL Supply Chain

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:http://www.dhl.de/de/logistik/supply-chain-loesungen.html[DHL Supply Chain^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » DHL Supply Chain*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-dhl-supply-chain>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-dhl-supply-chain]]
.Einstellungen der Schnittstelle zu DHL Supply Chain
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Versender-ID, FTP-Host, FTP-Benutzer, FTP-Passwort*
|Daten eingeben, wie von DHL erhalten.

|*Service*
|Service aus der Dropdown-Liste wählen.
|====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Wählen Sie im Bereich *DHL Supply Chain* in der Zeile *DHL-Produkt* die Option *Einmann-Handling* oder *Zweimann-Handling* aus der Dropdown-Liste.
. *Speichern* Sie die Einstellungen.

[#3400]
=== DHL UK

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:http://www.dhl.co.uk/en.html[DHL UK^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » DHL UK*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-dhl-uk>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-dhl-uk]]
.Einstellungen der Schnittstelle zu DHL UK
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Stammdaten

|*Site-ID*
|Daten eingeben, wie von DHL erhalten.

|*Passwort*
|Passwort eingeben, wie von DHL erhalten.

2+|Absenderkonten

|*Abrechnungsinformationen*
|Abrechnungsinformationen eingeben.

|*Absenderadresse*
|Absenderdaten eingeben.
|====

[TIP]
.Absenderkonten hinzufügen
====
Nachdem Sie im Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » DHL UK* die Daten in den Bereichen *Abrechnungsinformationen* und *Absenderadresse* eingegeben haben und diese Daten gespeichert haben, wird ein neues Tab im Bereich *Absenderkonten* hinzugefügt. Dieses Tab wird nach der Absender-Kontonummer benannt, die Sie im Bereich *Abrechnungsinformationen* eingegeben haben. Fügen Sie beliebig viele Absenderkonten über das Tab *Neu* hinzu.
====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich *DHL UK* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versandservices-dhl-uk>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-versandservices-dhl-uk]]
.Versandservices von DHL UK im Tab *Portotabelle*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Absender-Kontonummer*
|Absender-Kontonummer aus der Dropdown-Liste wählen.

|*Handelsbedingungen*
|Handelsbedingung aus der Dropdown-Liste wählen.
|====

[#3500]
=== DPD Cloud Webservice

[IMPORTANT]
.Verwendung des Plugins DPD Versand-Services
====
Verwenden Sie das Plugin DPD Versand-Services. Das Plugin steht Ihnen im link:https://marketplace.plentymarkets.com/plugins/integration/dpdshippingservices_6320[plentyMarketplace^] zur Verfügung.
====

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

[TIP]
.Automatische Zuordnung des Anmeldedatums zum nächsten Werktag
====
Wenn der Tag, an dem der Auftrag angemeldet wird, kein für DPD gültiger Werktag ist, wird automatisch der nächste Werktag gewählt. +
Wenn der Auftrag über das Versand-Center im Menü *Aufträge » Versand-Center » Tab: Anmelden* angemeldet wird, darf unter *Versanddatum* kein Datum gewählt werden. Andernfalls kann die automatische Zuordnung zum nächsten Werktag nicht erfolgen.
====

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://esolutions.dpd.com/entwickler/dpd-cloud-webservice.aspx[DPD Cloud Webservice^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » DPD Cloud Webservice*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-dpd-cloud-webservice>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-dpd-cloud-webservice]]
.Einstellungen der Schnittstelle zu DPD Cloud Webservice
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*User-ID*
|User-ID eingeben, wie von DPD erhalten.

|*User-Token*
|User-Token eingeben, wie von DPD erhalten.

|*Adresszusatz auf Label*
|Wählen, ob der Adresszusatz, der in der Lieferanschrift eingegeben wurde, auf dem DPD-Versandlabel ausgegeben werden soll. DPD begrenzt die Zeichenlänge auf 35. +
*Hinter Name ergänzen* = Der Adresszusatz wird hinter dem Namen ausgegeben. +
*In Referenz 1 ausgeben* = Der Adresszusatz wird unter *Referenz 1* ausgegeben. +
*Nicht ergänzen* = Der Adresszusatz wird nicht ausgegeben.

|*E-Mail-Adresse auf Label unterbinden*
|Option aktivieren, wenn die E-Mail-Adresse nicht auf das DPD-Versandlabel gedruckt werden soll.

|====


Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Wählen Sie im Bereich *DPD Cloud Webservice* in der Zeile *Versandservice* einen Service aus der Dropdown-Liste.
. *Speichern* Sie die Einstellungen.

Beachten Sie die Meldungen zu Sendungen, die Sie später über das <<fulfillment/versand-center#700, Versand-Center>> bei DPD Cloud Webservice anmelden. Diese Meldungen finden Sie im Menü *Daten » API-Log » Tab: Versand Center API-Log*. Weitere Informationen zu den API-Log-Einträgen von DPD Cloud Webservice finden Sie auf der Handbuchseite <<daten/api-log#, API-Log>>.

[.subhead]
Tracking-URL von DPD

Die aktuell gültige, plentymarkets bekannte Tracking-URL von DPD lautet: +
*+https://tracking.dpd.de/parcelstatus?query=[PaketNr]&locale=de_DE+*.

[#3600]
=== DPD DELISprint

Bevor Sie die Schnittstelle zu DPD DELISprint in plentymarkets einrichten, registrieren Sie sich bei link:https://www.dpd.com/portal_de[DPD^]. Mit dem Programm DPD DELISprint erstellen Sie als DPD-Kunde DPD-Paketscheine.

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://www.dpd.com/ch/home/esolutions/clientloesungen/delisprint_6[DPD DELISprint^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » DPD DELISprint*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-dpd-delisprint>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-dpd-delisprint]]
.Einstellungen der Schnittstelle zu DPD DELISprint
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Versandart*
|Versandart aus der Dropdown-Liste wählen. +
*NP - Normalpaket* = CLASSIC-Versand von Normalpaketen +
*KP - Kleinpaket* = CLASSIC-Versand von Kleinpaketen +
*NCP - B2C Normalpaket* = gewerblicher Versand von Normalpaketen +
*SCP - B2C Kleinpaket* = gewerblicher Versand von Kleinpaketen

|*Flex/Predict aktiv*
|Aktivieren, um bei DPD den kostenpflichtigen Vorankündigungsservice link:https://www.dpd.com/de/home/produkte_services/zusatzleistungen/national/predict[Predict^] (ehemals Flexzustellung) anzumelden. In der CSV-Datei wird dann der Zusatz *PRO* ausgegeben.
|====

[TIP]
.Zahlungsart Nachnahme
====
Bei Aufträgen mit der Zahlungsart *Nachnahme*, die über DPD versendet werden sollen, wird der Nachnahme-Service automatisch gewählt. Zusätzliche Einstellungen sind nicht erforderlich.
====

[#3700]
=== EasyPAK

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://www.post.at/geschaeftlich.php[EasyPAK^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » EasyPAK*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-easypak>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-easypak]]
.Einstellungen der Schnittstelle zu EasyPAK
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Absender-Referenz-Nr., Mandanten-Referenz-Nr., IBAN*
|Daten eingeben, wie von EasyPAK erhalten.  +
Wenn die Versandart Nachnahme genutzt wird, ist die Angabe der IBAN eine Pflichtangabe.
|====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich *PAT Easypak* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versandservices-easypak>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-versandservices-easypak]]
.Versandservices von EasyPak im Tab *Portotabelle*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Vertragstyp*
|Vertragstyp wählen.

|*Produkte*
|Produkt wählen.

|*Zusatzleistungen*
|Eine oder mehrere Zusatzleistungen wählen.
|====

[#3800]
=== GLS Germany

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um link:https://gls-group.eu/DE/de/home[GLS Germany^] mit plentymarkets zu nutzen. Beachten Sie, dass die Daten, die Sie im Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » GLS Germany* eingeben, ausschließlich in der CSV-Datei, die Sie im Menü *Aufträge » Fulfillment » Bereich: Lieferanschriftenliste* mit dem Datenformat *GLS preadvise* generieren, ausgegeben werden. Eine direkte Schnittstelle zu GLS Germany existiert nicht in plentymarkets.

[.instruction]
GLS Germany einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » GLS Germany*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-gls-germany>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-gls-germany]]
.Einstellungen für GLS Germany
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Internationale Kundennummer, +
Nationale Kundennummer, Annahmestelle*
|Daten eingeben, wie von GLS erhalten. +
*_Wichtig:_* Die hier eingegebenen Daten werden ausschließlich in der CSV-Datei ausgegeben, die im Menü *Aufträge » Fulfillment » Bereich: Lieferanschriftenliste* mit dem Datenformat *GLS preadvise* generiert wird.
|====

[.subhead]
Tracking-URL von GLS

Die aktuell gültige, plentymarkets bekannte Tracking-URL von GLS lautet: +
*+http://www.gls-group.eu/276-I-PORTAL-WEB/content/GLS/DE03/DE/5004.htm?txtRefNo=[PaketNr]&txtAction=71000+*.

[#3900]
=== Hermes 2-Mann-Handling

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Damit Ihr Kunde im Bestellvorgang wählen kann, ob er den Montageservice von link:https://www.hermesworld.com/de/unsere-dienstleistungen/distribution/2-mann-handling/2-mann-handling/[Hermes (2-Mann-Handling)^] nutzen möchte, müssen Sie diesen Service als Bestellmerkmal anlegen. Legen Sie ein Bestellmerkmal mit den Optionen *Ja* und *Nein* an. Je nach Wahl der Option *Merkmaltyp* sind mehrere Möglichkeiten der Auswahl im Webshop konfigurierbar.

[TIP]
.Schnittstelle nur für Bestandskunden
====
Die Schnittstelle zu Hermes 2-Mann-Handling kann nur noch von Bestandskunden genutzt werden. Neukunden werden gebeten, sich an die link:https://www.hermesworld.com/de/unsere-dienstleistungen/distribution/2-mann-handling/2-mann-handling/[HERMES Einrichtungs Service GmbH &amp; Co.KG^] zu wenden.
====

[.instruction]
Montageservice als Bestellmerkmal anlegen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Artikel » Merkmale » Tab: Neues Merkmal*.
. Geben Sie einen Namen ein, z.B. Montageservice.
. Aktivieren Sie die Option *Bestellmerkmal*.
. Wählen Sie als *Merkmaltyp* die Einstellung *Auswahl*. +
→ Weitere Optionen werden angezeigt.
. *Speichern* Sie die Einstellungen. +
→ Das Merkmal wird angelegt.
. Wechseln Sie in das Tab *Merkmale* und öffnen Sie das zuvor angelegte Merkmal.
. Geben Sie bei der Option *Name* unterhalb des Merkmaltyps *Ja* ein.
. *Speichern* Sie die Einstellungen. +
→ Ein weiteres Namensfeld wird angezeigt.
. Geben Sie in dieses Namensfeld *Nein* ein.
. *Speichern* Sie die Einstellungen.

Verknüpfen Sie nun das Bestellmerkmal mit dem Artikel.

[.instruction]
Merkmal mit dem Artikel verknüpfen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab *Merkmale*.
. Aktivieren Sie das zuvor angelegte Merkmal.
. *Speichern* Sie die Einstellungen.

Wenn ein Kunde den Artikel in den Warenkorb legt, werden die Optionen *Ja* und *Nein* des Bestellmerkmals in einer Dropdown-Liste zur Auswahl angeboten.

[IMPORTANT]
.Montageservice nur bei Versand mit Hermes
====
Das Bestellmerkmal ist mit dem Artikel und nicht mit dem Versanddienstleister verknüpft. Wenn für den Artikel mehr als eine Versandart bzw. andere Versanddienstleister als Hermes hinterlegt sind, fügen Sie für die Endkunden einen Hinweis in den Webshop ein, dass der Montageservice nur bei Versand mit Hermes erfolgt.
====

Gehen Sie nun wie im Folgenden beschrieben vor, um die Schnittstelle zu Hermes 2-Mann-Handling in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » Hermes (2-Mann-Handling)*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-hermes-2mannhandling>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-hermes-2mannhandling]]
.Einstellungen der Schnittstelle zu Hermes (2-Mann-Handling)
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Mandanten-Nr., FTP-Host, FTP-Benutzer, FTP-Passwort*
|Daten eingeben, wie von Hermes erhalten.

|*Montageservice*
|Montageservice aus der Dropdown-Liste wählen. Erst sichtbar, wenn wie oben beschrieben, das Bestellmerkmal angelegt und mit dem Artikel verknüpft wurde.
|====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich *Hermes 2-Mann-Handling* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versandservices-hermes-2mannhandling>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-versandservices-hermes-2mannhandling]]
.Versandservices von Hermes (2-Mann-Handling) im Tab *Portotabelle*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Versandtyp*
|*Normalversand* oder *48-Stunden-Service* wählen.  +
Eine Unterteilung in diese 2 Versandprofile ist sinnvoll, da auch beim Versanddienstleister selbst sich die Preise für diese 2 Versandmöglichkeiten unterscheiden und so die Kosten an die Kunden weitergegeben werden können.
|====

[.subhead]
Tracking-URL von Hermes

Die aktuell gültige, plentymarkets bekannte Tracking-URL von Hermes lautet: +
*+http://myhermes.de/wps/portal/PRIPS_DEU/SISYR?auftragsNummer=[PaketNr]+*.

[#4000]
=== Hermes ProfiPaketService

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://profipaketservice.hlg.de/wps/portal/PROPS_DEU/Home/Start/[Hermes ProfiPaketService^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » Hermes (ProfiPaketService)*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-hermes-profipaketservice>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-hermes-profipaketservice]]
.Einstellungen der Schnittstelle zu Hermes (ProfiPaketService)
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Stammdaten

|*Zugangsdaten*
|Interner Name, Login-Name und Passwort eingeben, wie von Hermes erhalten.

|*Abrechnung zum Staffelpreis*
|AGB von Hermes sowie den Hinweis auf die Limitierung des Paketwerts akzeptieren. +
Die beiden Häkchen setzen. Andernfalls steht der Hermes-Dienst nicht zur Verfügung. Die AGB können über den Link aufgerufen werden.

2+|Verfügbare Produkte

|*Interner Name, Paketklasse, Max. Paketgewicht, Nettopreis, Lieferländer*
|Hier werden die Daten, wie über die Schnittstelle von Hermes erhalten, angezeigt.
|====

[.subhead]
Tracking-URL von Hermes

Die aktuell gültige, plentymarkets bekannte Tracking-URL von Hermes lautet: +
*+http://myhermes.de/wps/portal/PRIPS_DEU/SISYR?auftragsNummer=[PaketNr]+*.

[#4100]
=== MyDPD Business / iloxx

Der Versanddienstleister iloxx gehört jetzt zu DPD und firmiert unter dem Namen DPD iloxx DPD eService GmbH. Bestehende iloxx-Schnittstellen in plentymarkets sind davon nicht berührt. Die neue Schnittstelle heißt jetzt MyDPD Business / iloxx.

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:http://www.dpd.iloxx.de/home.aspx[MyDPD Business / iloxx^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » MyDPD Business / iloxx*.
. Geben Sie *User-ID* und *User-Token* ein, wie von MyDPD Business / iloxx erhalten.
. *Speichern* Sie die Einstellungen.

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Wählen Sie im Bereich *MyDPD Business/iloxx* in der Zeile *Versandservice* einen Service aus der Dropdown-Liste.
. *Speichern* Sie die Einstellungen.

[TIP]
.Versandetiketten drucken
====
Sobald der Auftrag den Status *[5] Freigabe Versand* hat, können Sie im Versand-Center im Tab *Label* das Versandetikett drucken. Die Versandetiketten werden im Format DIN A-6 generiert.
====

[.subhead]
Tracking-URL von DPD

Die aktuell gültige, plentymarkets bekannte Tracking-URL von DPD lautet: +
*+https://tracking.dpd.de/parcelstatus?query=[PaketNr]&locale=de_DE+*.

[#4200]
=== NetDespatch

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie in den folgenden Unterkapiteln beschrieben vor, um link:http://www.royalmail.com/[Royal Mail^] und link:https://www.ukmail.com/[UK Mail^] über die integrierte Schnittstelle zu link:http://www.netdespatch.com/[NetDespatch^] in plentymarkets einzurichten.

[#4210]
==== Royal Mail

Gehen Sie wie im Folgenden beschrieben vor, um link:http://www.royalmail.com/[Royal Mail^] über die integrierte Schnittstelle zu link:http://www.netdespatch.com/[NetDespatch^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » NetDespatch*.
. Klappen Sie den Bereich *Royal Mail Einstellungen* auf.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-netdespatch-royalmail>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-netdespatch-royalmail]]
.Einstellungen der Schnittstelle zu NetDespatch (Royal Mail)
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Inländisch

|*Schnittstelle aktiv*
|Häkchen setzen, um die Schnittstelle zu aktivieren.

|*Modus*
|*Testsystem* oder *Produktivsystem* wählen.

|*Benutzername*
|Benutzername eingeben.

|*Passwort*
|Passwort eingeben.

2+|International

|*Schnittstelle aktiv*
|Häkchen setzen, um die Schnittstelle zu aktivieren.

|*Modus*
|*Testsystem* oder *Produktivsystem* wählen.

|*Benutzername*
|Benutzername eingeben.

|*Passwort*
|Passwort eingeben.

2+|Royal Mail Konto ID

|*Konto-ID*
|Konto-ID eingeben.
|====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich *NetDespatch* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versandservices-netdespatch-royalmail>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-versandservices-netdespatch-royalmail]]
.Versandservices von NetDespatch (Royal Mail) im Tab *Portotabelle*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Versanddienstleister*
|*Royal Mail* aus der Dropdown-Liste wählen.

|*Versandgebiet*
|*Royal Mail International* oder *Royal Mail Inländisch* aus der Dropdown-Liste wählen.

|*Produktgruppe*
|Produktgruppe aus der Dropdown-Liste wählen.

|*Versandservice*
|Versandservice aus der Dropdown-Liste wählen. Abhängig vom gewählten Versandservice wird der zugehörige Code unter *Service-Code* in der nächsten Zeile automatisch angezeigt.

|*Service-Code*
|Der Service-Code wird in Abhängigkeit zum vorher gewählten Versandservice hier automatisch angezeigt.

|*Nichtzustellbarkeitsanweisung*
|Eine Option aus der Dropdown-Liste wählen. Die Dropdown-Liste wird nur angezeigt, wenn unter *Versandgebiet* die Einstellung *Royal Mail International* gewählt wurde. Mit Wahl dieser Option wird festgelegt, wie vorgegangen werden soll, wenn das Paket nicht zugestellt werden kann. Bei CN23-Formularen ist die Auswahl einer Option eine Pflichtauswahl.
|====

[#4230]
==== UK Mail

Gehen Sie wie im Folgenden beschrieben vor, um link:https://www.ukmail.com/[UK Mail^] über die integrierte Schnittstelle zu link:http://www.netdespatch.com/[NetDespatch^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » NetDespatch*.
. Klappen Sie den Bereich *UK Mail Einstellungen* auf.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-netdespatch-ukmail>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-netdespatch-ukmail]]
.Einstellungen der Schnittstelle zu NetDespatch (UK Mail)
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Inländisch

|*Schnittstelle aktiv*
|Häkchen setzen, um die Schnittstelle zu aktivieren.

|*Modus*
|*Testsystem* oder *Produktivsystem* wählen.

|*Benutzername*
|Benutzername eingeben.

|*Passwort*
|Passwort eingeben.

2+|UK Mail Konto ID

|*Konto-ID*
|Konto-ID eingeben.
|====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich *NetDespatch* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versandservices-netdespatch-ukmail>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-versandservices-netdespatch-ukmail]]
.Versandservices von NetDespatch (UK Mail) im Tab *Portotabelle*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Versanddienstleister*
|*UK Mail* aus der Dropdown-Liste wählen.

|*Versandgebiet*
|*Inländisch* aus der Dropdown-Liste wählen.

|*Produktgruppe*
|Produktgruppe aus der Dropdown-Liste wählen.

|*Versandservice*
|Versandservice aus der Dropdown-Liste wählen. Abhängig vom gewählten Versandservice wird der zugehörige Code unter *Service-Code* in der nächsten Zeile automatisch angezeigt.

|*Service-Code*
|Der Service-Code wird in Abhängigkeit zum vorher gewählten Versandservice hier automatisch angezeigt.

|*Nichtzustellbarkeitsanweisung*
|Diese Option ist nur bei internationalem Versand relevant und daher für UK Mail nicht verfügbar.
|====

[#4250]
=== Parcelforce Worldwide

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:http://www.parcelforce.com/[Parcelforce Worldwide^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » Parcelforce Worldwide*.
. Geben Sie die Vertragsnummer ein.
. *Speichern* Sie die Einstellungen.

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich *Parcelforce Worldwide* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versandservices-parcelforce-worldwide>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-versandservices-parcelforce-worldwide]]
.Versandservices von Parcelforce Worldwide im Tab *Portotabelle*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Service*
|Service aus der Dropdown-Liste wählen.

|*Zusatzservice*
|Zusatzservice aus der Dropdown-Liste wählen. Aktuell ist die Option *Saturday delivery* verfügbar.

|*Erweiterte Entschädigung*
|Option aus der Dropdown-Liste wählen.
|====

[#2600]
=== PARCEL.ONE

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://parcel.one/[PARCEL.ONE^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » PARCEL.ONE*.
. Geben Sie Benutzer und Passwort ein, wie von PARCEL.ONE erhalten.
. *Speichern* Sie die Einstellungen.

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich *PARCEL.ONE* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versandservices-parcel-one>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-versandservices-parcel-one]]
.Versandservices von PARCEL.ONE im Tab *Portotabelle*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Profil*
|Profil aus der Dropdown-Liste wählen.

|*Absender*
|Absender aus der Dropdown-Liste wählen.

|*Versanddienstleister*
|Versanddienstleister aus der Dropdown-Liste wählen.

|*Produkt*
|Produkt aus der Dropdown-Liste wählen.

|*Services*
|Einen Service oder *ALLE* wählen.
|====


[#4300]
=== Swiss Post

Bevor Sie die Schnittstelle zu link:https://www.post.ch/de/geschaeftlich/themen-a-z/swiss-post-gls[Swiss Post^] in plentymarkets einrichten, registrieren Sie sich bei Swiss Post.

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Richten Sie für Swiss Post einen technischen Benutzer ein. Dazu benötigen Sie den Webservice Barcode. Diesen Webservice müssen Sie bei der Schweizerischen Post beauftragen, da er standardmäßig nicht vorhanden ist. Dieser Webservice ist kostenlos. Wenn der Webservice zur Verfügung steht, können Sie den Technischen Benutzer einrichten.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu Swiss Post in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » Swiss Post*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-swiss-post>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-swiss-post]]
.Einstellungen der Schnittstelle zu Swiss Post
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Swiss Post Benutzer, Swiss Post Passwort, Frankierlizenz-Nr.*
|Daten eingeben, wie von Swiss Post erhalten.

|*Nachnahmebetrag*
|*Mit dem ersten Versandpaket* oder *Auf Versandpakete verteilen* wählen.

|*Neuen Webservice-Endpoint nutzen*
|*JA* wählen. Aufgrund einer Umstellung bei Swiss Post wird die Schnittstelle angepasst. Alle Kunden erhalten neue Zugangsdaten. Diese Zugangsdaten hier eingeben. Bei Problemen mit der neuen Konfiguration Swiss Post direkt kontaktieren.
|====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versandservices-swiss-post>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-versandservices-swiss-post]]
.Versandservices von Swiss Post im Tab *Portotabelle*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Service-Gruppe*
|Service-Gruppe im Bereich *Die Schweizerische Post* aus der Dropdown-Liste wählen. Je nachdem, welche Service-Gruppe gewählt wird, werden weitere Einstellungsmöglichkeiten angezeigt. +
*_Wichtig:_* Die Service-Gruppen stehen erst nach dem Einrichten des technischen Benutzers zur Verfügung.

|*Validierung*
|Auf *Ausführen* klicken, damit die gewählten Werte von der Schweizerischen Post validiert werden.
|====

[#4400]
=== UPS

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>> bis <<fulfillment/versand-vorbereiten#2400, API-Log abrufen>> beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://www.ups.com/one-to-one/register?sysid=myups&loc=de_DE&WT.svl=Footer[UPS^] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » UPS*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-ups>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-ups]]
.Einstellungen der Schnittstelle zu UPS
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*UPS-Benutzer, UPS-Passwort, UPS-Kundennummer, Zugriffsschlüssel*
|Daten eingeben, wie von UPS erhalten.

|*Anmeldung*
|Wählen, wie Versandaufträge mit mehreren Paketen bei UPS angemeldet werden sollen. +
*Gesammelt anmelden* = Alle Pakete werden zusammenhängend angemeldet und erreichen gleichzeitig den Empfänger. +
*_Wichtig:_* Die Einstellung *Gesammelt anmelden* ist Pflicht bei Nachnahmeaufträgen mit mehreren Paketen. +
*Separat anmelden* = Jedes Versandpaket wird einzeln als Versandauftrag angemeldet. Die Pakete können den Empfänger zeitlich versetzt erreichen.
|====

[IMPORTANT]
.Zahlungsart Nachnahme
====
Bei Nachnahmesendungen per UPS sind nur Schecks erlaubt. Sollen Schecks nicht berücksichtigt werden, muss im UPS-Versandprofil die Zahlungsart Nachnahme verboten werden, damit Sendungen dieser Art nicht über UPS angemeldet werden können.
====

[WARNING]
.Telefonnummer des Empfängers bei Auslandssendungen angeben
====
Geben Sie in den Absenderdaten die Telefonnummer des Empfängers generell auf Sendungen ins Ausland an.
====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab *Portotabelle*.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich *UPS Service* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versandservices-ups>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-versandservices-ups]]
.Versandservices von UPS im Tab *Portotabelle*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Api Service*
|Versandart aus der Dropdown-Liste wählen.

|*alternative Telefonnummer*
|Alternative Telefonnummer eingeben.
|====

[.subhead]
Tracking-URL von UPS

Die aktuell gültige, plentymarkets bekannte Tracking-URL von UPS lautet: +
*+http://wwwapps.ups.com/WebTracking/track?track=yes&trackNums=[PaketNr]&loc=de_de+*.

[#4500]
== DHL-Packstation einrichten

DHL unterhält ein Netz von Packstationen, die rund um die Uhr verfügbar sind. Eine DHL-Packstation oder eine DHL-Postfiliale kann von Ihren Kunden optional als Lieferadresse angegeben werden. Nehmen Sie die Einstellungen für DHL-Packstationen im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Bestellvorgang » DHL-Packstation* vor.

Beachten Sie, dass die Angabe einer Packstation nur als Lieferanschrift möglich ist.

[.instruction]
DHL-Packstation einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Bestellvorgang » DHL-Packstation*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-dhl-packstation>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-dhl-packstation]]
.Optionen für DHL-Packstationen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Packstation in Lieferadressen erlauben*
|Wählen, ob die Angabe einer Packstation in einer Lieferadresse im Webshop grundsätzlich erlaubt sein soll oder nicht. Wenn diese Option aktiviert ist, ist für den Webshop auch der DHL-Postfinder verfügbar. Mit dem Postfinder können Sie Packstationen und Postfilialen in den Lieferanschriftformularen suchen. +
Details zum Einrichten des Postfinder finden Sie im Kapitel <<fulfillment/versand-vorbereiten#4600, DHL-Postfinder einrichten>>.

|*Maximalbestellwert bei Packstation*
|Maximalbestellwert eingeben. Wenn der Bestellwert höher liegt als der festgelegte Grenzwert, bekommt der Kunde eine Fehlermeldung beim Versuch, die Bestellung abzuschließen. +
*_Wichtig:_* Der Eintrag 0,00 (Standard) bedeutet, dass es keine Einschränkung des Bestellwertes gibt.

|*Packstationsvalidierung*
|Wählen, ob die Validierung von DHL-Packstationen erfolgen soll (aktiv) oder nicht (inaktiv). Der bei der Validierung vorgenommene Datenabgleich dient der zusätzlichen Sicherheit und kann Betrugsfälle verhindern. Die Adressdaten des Kunden (Rechnungsanschrift und E-Mail-Adresse) werden mit der Postnummer abgeglichen. Bei Unstimmigkeiten, z.B. die Postnummer passt nicht zum Kunden oder der Kunde ist gesperrt, kommt es zu einer Fehlermeldung.

|*Postnummer in Adressdaten abfragen*
|Käufer haben im Webshop auch die Möglichkeit, die Postnummer des DHL-Services *Postfinder* einzugeben. Wählen, ob die Postnummer im Bestellvorgang abgefragt werden soll. +
Die Bezeichnungen, die im Bestellvorgang angezeigt werden, werden im Menü *CMS » Webdesign » Bestellvorgang » Kaufabwicklung* in den Untermenüs *Kundenregistrierung*, *Rechnungsanschrift* und *Lieferanschrift* gespeichert.
|====

[WARNING]
.Rechnungsadresse
====
Eine gültige Rechnungsadresse muss für den Kunden existieren. Die Angabe der Packstation wird mit den Daten der Rechnungsanschrift abgeglichen. +
Somit kann auch keine Packstation als Lieferadresse angegeben werden, für die die Person in der Rechnungsanschrift nicht registriert ist. +
*Ausnahme*: Dies gilt nicht für die Auftragsbearbeitung. Sie können hier Lieferadressen speichern, es erfolgt keine Validierung.
====

Nachdem Sie die Option *Packstation in Lieferadressen erlauben* auf *JA* gestellt haben, können sowohl Ihre Kunden im Webshop als auch der Sie selbst im Adminbereich eine Packstation als Lieferanschrift angeben.

[.instruction]
Packstation beim Kunden als Lieferadresse eingeben:

. Öffnen Sie das Menü *Kunde » Kunde bearbeiten*.
. Öffnen Sie den Kunden, dessen Lieferanschrift Sie durch eine Packstation ersetzen möchten.
. Wechseln Sie in das Tab *Lieferanschriften*.
. Klicken Sie auf *Lieferanschrift bearbeiten*.
. Klicken Sie auf *DHL Packstation*.
. Geben Sie Postnummer, Packstation, PLZ und Ort der Packstation ein.
. *Speichern* Sie die Einstellungen.

[#4600]
== DHL-Postfinder einrichten

Mit dem DHL-Postfinder werden Ihren Kunden im Mein Konto-Bereich bei der <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-kaufabwicklung#, Kaufabwicklung>> anhand der Postleitzahl die in der Nähe liegenden Postfilialen und Packstation angezeigt. Ihre Kunden haben dann die Möglichkeit, die Auswahl direkt in die Lieferanschrift zu übernehmen.

Um den DHL-Postfinder zu nutzen, müssen Sie Einstellungen in mehreren Menüs vornehmen. Diese Einstellungen sind auf der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-dhl-postfinder#, DHL-Postfinder>> zusammengefasst.

[#4700]
== Fulfillment-Dienstleister im Überblick

In plentymarkets haben Sie als Händler die Möglichkeit, Ihren Warenbestand einem externen Dienstleister anzuvertrauen, der für Sie den Warenbestand oder einen Teil davon verwaltet, den Status an Ihr plentymarkets System zurückmeldet und auch den Versand der Artikel übernimmt. Und das alles automatisch, ohne dass Sie viel tun müssen. plentymarkets bietet auch Lösungen, um Ihren Versand über mehrere Dienstleister und Lager abzubilden.

In <<tabelle-ueberblick-fulfillment-dienstleister>> finden Sie die in plentymarkets verfügbaren Fulfillment-Dienstleister aufgelistet. Mit einem Klick auf den Dienstleister in der Tabelle gelangen Sie in das Unterkapitel, in dem dienstleisterspezifische Einstellungen beschrieben sind.

[[tabelle-ueberblick-fulfillment-dienstleister]]
.Fulfillment-Dienstleister im Überblick
[cols="1,3"]
|====
|Einstellung |Erläuterung

|<<fulfillment/versand-vorbereiten#4800, DHL Fulfillment>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<fulfillment/versand-vorbereiten#5400, IDS Logistik>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<fulfillment/versand-vorbereiten#5500, iLOPACK>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<fulfillment/versand-vorbereiten#5600, Fulfillment by Amazon>>
|Für Händler innerhalb Deutschlands. Versand: international.
|====

[#4800]
=== DHL Fulfillment

Richten Sie link:http://www.dhl.de/fulfillment[DHL Fulfillment^] in Ihrem plentymarkets System ein. Gehen Sie dazu wie im Folgenden beschrieben vor.

[IMPORTANT]
.Klarna-Aufträge werden nicht an DHL Fulfillment übertragen
====
Die Auftragsübergabe von mit <<payment/klarna#, Klarna>> bezahlten Aufträgen an DHL Fulfillment ist noch nicht möglich. Nur Aufträge mit einem vorhandenen Rechnungsdokument können an DHL Fulfillment übertragen werden. Klarna übermittelt die Rechnung jedoch erst nach Warenausgang an plentymarkets.
====

Die Sendungsanmeldung an DHL Fulfillment erfolgt automatisch über die Schnittstelle. Meldungen zu Sendungen, die bei DHL Fulfillment angemeldet wurden, finden Sie im Menü *Daten » API-Log*. Weitere Informationen zu den API-Log-Einträgen von DHL Fulfillment finden Sie auf der Handbuchseite <<daten/api-log#, API-Log>>.

[#4850]
==== Voraussetzungen für die Artikelübertragung an DHL Fulfillment

Die folgenden Voraussetzungen müssen erfüllt sein, damit die Variante an DHL Fulfillment übertragen werden kann:

* Die Variante ist aktiv.
* Als Hauptlager der Variante ist ein gültiges Vertriebslager vom Typ *DHL Fulfillment* gewählt.
* Die Variante darf nicht schon einmal an DHL Fulfillment gemeldet geworden sein.

[#4900]
==== Lager erstellen

Erstellen Sie zunächst im Menü *System » Systemeinstellungen » Waren » Lager* die Lager für die von DHL Fulfillment verwalteten Artikel. Geben Sie bei allen Lagern den gleichen Namen ein, z.B. DHL Fulfillment. Wählen Sie diese Lager dann auch als Hauptlager für die von DHL Fulfillment verwalteten Artikel. Öffnen Sie dazu den Artikel im Menü *Artikel » Artikel bearbeiten* und wählen Sie das Hauptlager im Bereich *Versand*. Weitere Informationen zum Erstellen von Lagern finden Sie auf der Handbuchseite <<warenwirtschaft/lager-einrichten#, Lager einrichten>>.

Erstellen Sie für die Einrichtung von DHL Fulfillment die folgenden Lagertypen:

* *Vertrieb*
* *Vorrat*
* *Reparatur*
* *Sonstiges*

Für die korrekte Abwicklung über die DHL Fulfillment-Schnittstelle benötigen Sie mindestens ein Lager des Lagertyps *Vertrieb* mit dem Logistiktyp *DHL Fulfillment*. Bis zu 4 Lager sind möglich. Die Zuordnung erfolgt seitens DHL anhand der von DHL verwendeten Bestandstypen. Dem Vertriebslager ordnet DHL z.B. Waren des Bestandstyps *Prime Selection* zu. Diese Waren sind direkt zum Verkauf bestimmt. Waren des Bestandstyps *Second Quality* sind nicht für den Verkauf bestimmt und benötigen ein separates Lager, z.B. des Lagertyps *Vorrat*. Werden solche Waren nach Prüfung für gut befunden, erhalten sie den Bestandstyp *Prime Selection* und somit die Zuordnung zum Vertriebslager.

[WARNING]
.Lagerzuordnung erfolgt durch DHL
====
Die Zuordnung zu den für DHL Fulfillment konfigurierten Lagern wird von DHL vorgenommen. Nehmen Sie selbst keine Änderungen an den Beständen, die für DHL Fulfillment bestimmt sind, vor.
====

Folgende Bestandstypen werden von DHL Fulfillment verwendet:

* *Prime Selection*: Erste Wahl, für den Verkauf bestimmt, Zuordnung zum Vertriebslager
* *Second Quality*: Zweite Wahl, nicht für den Verkauf bestimmt, Zuordnung zum Vorratslager
* *Damaged*: Beschädigte Ware, nicht für den Verkauf bestimmt, Zuordnung zum Reparaturlager
* *Blocked* und *Clearing*: Gesperrte Waren und Waren, deren Zustand geprüft werden muss, kein Verkauf, Zuordnung zum Sonderlager (Lagertyp: Sonstiges)

Beschädigte Waren können Retouren sein, aber auch Artikel, die z.B. bei der Bewegung im Lager beschädigt werden oder beschädigt geliefert wurden.

Wenn Sie für Ihre Artikel eine Nachbestellung im Menü *Waren » Bestellwesen » Nachbestellungen* anlegen, stellen Sie sicher, dass sich die Nachbestellung in *Status [2] Bestätigt* befindet. Nur wenn sich die Nachbestellung in diesem Status befindet, wird die Nachbestellung an DHL Fulfillment übertragen. Weitere Informationen zu Nachbestellungen finden Sie auf der Handbuchseite <<warenwirtschaft/nachbestellungen-verwalten#, Nachbestellungen verwalten>>.

Beachten Sie, dass Ihr plentymarkets System Anpassungen am Artikelbestand nur übernehmen kann, wenn die Artikeldaten über plentymarkets an DHL Fulfillment übertragen wurden. Wichtig ist, dass DHL Fulfillment die Artikel bestätigt, damit diese Artikel berücksichtigt werden können.

[#5000]
==== Auftragsstatus erstellen

Zur Zuordnung legen Sie im Menü *System » Systemeinstellungen » Aufträge » Auftragsstatus* 2 <<auftraege/auftraege-verwalten#1200, Auftragsstatus>> für die an DHL Fulfillment übermittelten Aufträge an. Im Folgenden finden Sie 2 Beispiele:

* [6.5] Beim Fulfillment-Dienstleister im Versand +
→ Für korrekt angemeldete Aufträge

* [5.6] Fehler beim Fulfillment-Dienstleister +
→ Für Aufträge, die DHL Fulfillment aufgrund fehlerhafter Auftragsdaten nicht verarbeiten kann. Beispiel: Artikelstammdaten wurden noch nicht an DHL Fulfillment übergeben.

[TIP]
.Aufträge im Statusbereich 5.x
====
Alle Aufträge im *Statusbereich 5.x*, für die Rechnungen erzeugt wurden, werden zu den definierten Übertragungszeiten (in der Regel viertelstündlich) automatisch an DHL Fulfillment übermittelt. Einzige Ausnahme ist der Auftragsstatus, der für die Option *Auftragsstatus bei Fehler* festgelegt wurde. Aufträge in diesem Status werden nicht an DHL Fulfillment übermittelt.

Meldungen zu Sendungen, die bei DHL Fulfillment angemeldet wurden, finden Sie im Menü *Daten » API-Log*. Weitere Informationen zu den API-Log-Einträgen von DHL Fulfillment finden Sie auf der Handbuchseite <<daten/api-log#, API-Log>>.
====

Soll ein eigener Workflow für den Auftragsdurchlauf der DHL Fulfillment-Aufträge hinterlegt werden, empfiehlt sich die Einführung eines weiteren Status, z.B. *5.4 Vorbereitung für Fulfillment-Dienstleister*, um DHL Fulfillment-Aufträge bereits vor der Übertragung an DHL von anderen Aufträgen abzugrenzen.

[#5100]
==== Retourengründe anlegen

Wenn die Retouren von DHL Fulfillment in Ihr plentymarkets System importiert werden sollen, benötigen Sie Retourengründe. Diese Retourengründe legen Sie im Menü <<auftraege/auftraege-verwalten#410, System » Systemeinstellungen » Aufträge » Auftragstypen » Retoure>> an. Verknüpfen Sie dann die von Ihnen konfigurierten Retourengründe mit den von DHL Fulfillment vorgegebenen Gründen im Menü *System » Systemeinstellungen » Aufträge » Versand » Fulfillment » DHL Fulfillment*.

[#5200]
==== Schnittstelle einrichten

In den Schnittstelleneinstellungen speichern Sie die Zugangsdaten, ordnen die Auftragsstatus zu und verknüpfen die Retourengründe.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Fulfillment » DHL Fulfillment*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-dhl-fulfillment>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-dhl-fulfillment]]
.Einstellungen der Schnittstelle zu DHL Fulfillment
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Schnittstelle aktiv*
|Option aktivieren, um die Schnittstelle zu aktivieren. Schnittstelle erst aktivieren, wenn die <<afulfillment/versand-vorbereiten#4900, Lager erstellt>> wurden.

|*Mandantenkennung*
|DHL Fulfillment-Mandantenkennung, d.h. Kundennummer, eingeben.

|*FTP-Zugang*
|Bevor die Schnittstelle produktiv genutzt werden kann, ist ein Testbetrieb vorgesehen. Zum Testen der Schnittstelle hier die Option *Testbetrieb* wählen und die von DHL erhaltenen Zugangsdaten eingeben. Diese sind für Test- und Produktivbetrieb unterschiedlich. +
Die Zugangsdaten für den Produktivbetrieb werden von DHL nach erfolgreichem Testbetrieb zur Verfügung gestellt. Nach Wahl der Option *Produktivbetrieb* wird die Option *Testdaten zurücksetzen* angezeigt. Aktivieren, wenn die Testdaten gelöscht werden sollen.

|*FTP-Login*
|Login-Name für das FTP-Verzeichnis eingeben.

|*FTP-Passwort*
|Passwort für das FTP-Verzeichnis eingeben.

|*Auftragsstatus nach Meldung*
|Auftragsstatus wählen, der für die Meldung bei DHL Fulfillment verwendet werden soll. +
*_Wichtig:_* Der hier gewählte Auftragsstatus hat Auswirkungen auf die Anmeldung neuer Aufträge an DHL Fulfillment, d.h. neue Aufträge mit diesem Status werden bei der Anmeldung nicht berücksichtigt.

|*Auftragsstatus bei Fehler*
|Auftragsstatus wählen, der bei Fehlern verwendet werden soll.

|*Aufbau Produktnummer*
|Wählen, wie die Produktnummer an DHL Fulfillment übermittelt werden soll. +
*SKU* = (Standardeinstellung) Die SKU besteht aus der Artikel-ID, der Preis-ID und der Varianten-ID. +
*Variantennummer* = Ist erforderlich, wenn mit DHL Fulfillment bereits eine andere Software verwendet wurde und die dortigen Bestände korrekt auf plentymarkets Artikel abgebildet werden sollen.

|*Produktname*
|*Artikelname;Attribut;Variante* (Standardeinstellung) oder *Variantenname* wählen. Dieser Produktname wird dann an DHL Fulfillment übermittelt.

|*Mindesthaltbarkeitsdatum, Originalkarton, Zerbrechlich, Seriennummer*
|Merkmalverknüpfung zur Übermittlung der Artikeleigenschaft an DHL Fulfillment. Details dazu im Abschnitt <<fulfillment/versand-vorbereiten#5300, Merkmale übermitteln>>.

|*E-Mail und Telefonnr. übertragen*
|Wählen, ob die E-Mail-Adresse und die Telefonnummer an den Dienstleister übertragen werden sollen oder nicht oder ob ein alternativer Wert übertragen werden soll. +
*_Hinweis:_* Standardmäßig werden diese Daten nicht an den Dienstleister übertragen (DSGVO-Konformität).

|*Alternative E-Mail*
|Diese Einstellung ist nur sichtbar, wenn in der Dropdown-Liste *E-Mail und Telefonnr. übertragen* die Option *Alternative übertragen* gewählt wurde. Alternative E-Mail-Adresse, die an den Dienstleister übertragen werden soll, eingeben.

|*Alternative Telefonnr.*
|Diese Einstellung ist nur sichtbar, wenn in der Dropdown-Liste *E-Mail und Telefonnr. übertragen* die Option *Alternative übertragen* gewählt wurde. Alternative Telefonnummer, die an den Dienstleister übertragen werden soll, eingeben.

|*Retourengründe*
|Retourengründe von DHL Fulfillment mit den im Menü <<auftraege/auftraege-verwalten#400, System » Systemeinstellungen » Aufträge » Auftragstypen » Retoure>> angelegten Retourengründen verknüpfen.
|====

[#5300]
==== Merkmale übermitteln

Erstellen Sie im Menü *System » Systemeinstellungen » Artikel » Merkmale* Eigenschaften wie z.B. "Zerbrechlich" oder "Originalkarton", die Sie anschließend an DHL Fulfillment übermitteln, damit die Artikel logistisch vorbereitet werden können. Wie Sie ein Merkmal erstellen, ist auf der Handbuchseite <<artikel/artikel-verwalten#, Artikel verwalten>> im Kapitel <<artikel/artikel-verwalten#500, Merkmale erstellen>> beschrieben. Die folgenden Merkmale können an DHL Fulfillment übermittelt werden:

* *Mindesthaltbarkeitsdatum*: Der Artikel wird als MHD-pflichtiger Artikel im Lager bei DHL Fulfillment geführt. Beim Wareneingang erfasst DHL Fulfillment für Artikel mit diesem Merkmal ein Mindesthaltbarkeitsdatum.
* *Originalkarton*: Der Artikel wird von DHL Fulfillment einzeln im Originalkarton versendet.
* *Zerbrechlich*: Der Artikel wird von DHL Fulfillment mit zusätzlichem Füllmaterial am Packplatz verpackt.
* *Seriennummer*: Die am Packplatz erfassten Seriennummern werden mit der Versandmeldung (Auftragsrückmeldung) an plentymarkets von DHL Fulfillment zurückgespielt, damit die Seriennummer z.B. auf die Rechnung gedruckt und vom Kunden für weitere Verwendungen (z.B. Dokumentation, Gutscheinfreigabe) verwendet werden kann.

[IMPORTANT]
.Korrekten Merkmaltyp für die Merkmale wählen
====
Erstellen Sie im Menü *System » Systemeinstellungen » Artikel » Merkmale* die folgenden 3 Merkmale mit dem Merkmaltyp *Kein*:

* *Mindesthaltbarkeitsdatum*
* *Originalkarton*
* *Zerbrechlich*

Erstellen Sie das Merkmal *Seriennummer* mit dem Merkmaltyp *Auswahl* und speichern Sie die folgenden 3 Werte:

* *SN* (Erfassung der Seriennummer eines Artikels)
* *SNK* (Erfassung von Seriennummernbereichen pro Artikel)
* *SNK2* (Erfassung von Seriennummernbereichen pro Auftragsposition)

Weitere Informationen zu Merkmalen finden Sie auf der Handbuchseite <<artikel/artikel-verwalten#, Artikel verwalten>> im Kapitel <<artikel/artikel-verwalten#480, Merkmale verwalten>>.
====

Nachdem Sie die Merkmale erstellt haben, <<artikel/artikel-verwalten#80, aktivieren>> Sie die Merkmale am Artikel im Tab *Merkmale*. Abschließend ordnen Sie die Merkmale in der Schnittstellenkonfiguration im Menü *System » Systemeinstellungen » Aufträge » Versand » Fulfillment » DHL Fulfillment* zu.

Vor der Übertragung des Auftrags an DHL Fulfillment findet eine Prüfung der Empfängeradresse auf Richtigkeit der Form und Struktur statt, d.h. plentymarkets prüft z.B., ob alle Pflichtfelder wie beispielsweise der Name ausgefüllt wurden. +
Sollten fehlerhafte HTML-Zeichen bzw. für die API ungültige Zeichen in der Adresse enthalten sein, werden die Zeichen korrigiert. Wenn dennoch ein nicht korrigierbarer Fehler in der Adresse enthalten ist, wird der Auftrag nicht übermittelt. Dies verhindert eine Störung im Prozess, da DHL Fulfillment keine ungültigen bzw. fehlerhaften XML-Dateien von dem FTP-Server abholen kann.

[#5310]
==== Für Deutschland: Briefe versenden

Um den Briefversand mit DHL Fulfillment nutzen zu können und so z.B. Einschreiben sowohl national als auch international zu versenden, müssen Sie den <<fulfillment/versand-vorbereiten#800, Versanddienstleister>> erstellen sowie <<fulfillment/versand-vorbereiten#1000, Versandprofil>> und <<fulfillment/versand-vorbereiten#1500, Portotabelle>> einrichten. Dafür müssen <<fulfillment/versand-vorbereiten#100, Lieferländer>> aktiviert und <<fulfillment/versand-vorbereiten#400, Regionen>> erstellt sein. +

Anschließend wählen Sie in der Portotabelle die Region *Deutschland*, das Versandprodukt für den nationalen oder internationalen Versand und aktivieren die Versandservices. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben. Beachten Sie auch, dass das Versandprofil am Artikel <<fulfillment/versand-vorbereiten#1800, aktiviert>> sein muss.

[#5320]
==== Für UK: National und international versenden

Damit Sie als Händler im Vereinigten Königreich über DHL Fulfillment Ihre Artikel sowohl national als auch international versenden können, müssen Sie den <<fulfillment/versand-vorbereiten#800, Versanddienstleister>> erstellen sowie <<fulfillment/versand-vorbereiten#1000, Versandprofil>> und <<fulfillment/versand-vorbereiten#1500, Portotabelle>> einrichten. Dafür müssen <<fulfillment/versand-vorbereiten#100, Lieferländer>> aktiviert und <<fulfillment/versand-vorbereiten#400, Regionen>> erstellt sein.

Anschließend wählen Sie in der Portotabelle die Region *Vereinigtes Königreich*, das Versandprodukt für den nationalen oder internationalen Versand und aktivieren die Versandservices. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben. Beachten Sie auch, dass das Versandprofil am Artikel <<fulfillment/versand-vorbereiten#1800, aktiviert>> sein muss.

[#5400]
=== IDS Logistik

Bevor Sie die Schnittstelle zu IDS Logistik einrichten, registrieren Sie sich bei link:http://www.ids-logistik.de[IDS Logistik^].

Erstellen Sie dann im Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versanddienstleister* den Fulfillment-Dienstleister. Wählen Sie in der Spalte *Versanddienstleister* die Option *Sonstiges* aus der Dropdown-Liste. Weitere Informationen finden Sie im Kapitel <<fulfillment/versand-vorbereiten#800, Versanddienstleister erstellen>>.

Richten Sie anschließend das Versandprofil im Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile* ein. Wie Sie dazu vorgehen, ist im Kapitel <<fulfillment/versand-vorbereiten#1000, Versandprofil erstellen>> beschrieben.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu IDS Logistik einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Fulfillment » IDS Logistik*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-ids-logistik>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-ids-logistik]]
.Einstellungen der Schnittstelle zu IDS Logistik
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Depotnummer, Standard 800*
|Depotnummer eingeben, wie von IDS Logistik erhalten. Standard: 800

|*Versender-Kundennummer, Feld: VKDNR (vierstellig)*
|4-stellige Kundennummer des Versenders eingeben.

|*Sendungsnummer (vierstellig)*
|4-stellige Sendungsnummer eingeben, wie von IDS Logistik erhalten.

|*Lieferscheinnummer*
|Wählen, welcher Wert als Lieferscheinnummer übermittelt werden soll oder ob kein Wert als Lieferscheinnummer übermittelt werden soll. +
Eine der folgenden Optionen wählen: +
*Artikel-ID +
Artikelnummer +
Externe Artikel-ID +
Nicht übermitteln +
[Freitextfeld 1 bis 20]*

|*Inhalt*
|Wählen, welcher Wert als Inhalt übermittelt werden soll oder ob kein Wert als Inhalt übermittelt werden soll. +
Optionen: +
*Artikel-ID +
Artikelnummer +
Externe Artikel-ID +
Nicht übermitteln +
[Freitextfeld 1 bis 20]*

|*Empfänger-Kundennummer, Feld: KDNR*
|*Kundennummer* oder *Auftragsnummer* des Empfängers wählen.

|*Übertragene Artikel (Maximum 99)*
|Anzahl der zu übertragenden Artikel eingeben (maximal 99).

|*Hinweistextschlüssel 1 / 2*
|Festlegen, ob und ggf. welcher Hinweistext an IDS Logistik übermittelt werden soll.

|*Auftragstyp*
|*Abholauftrag* oder *Zustellauftrag* wählen.

|*Mobiltelefonnummern übertragen*
|Festlegen, ob die Mobiltelefonnummern der Empfänger an IDS Logistik übertragen werden sollen oder nicht.

|*Anzahl Ziffern für AUFTRAGSNR, Minimum 16*
|Die Auftragsnummer wird mit der <<fulfillment/dokumente-erzeugen#200, Lieferanschriftenliste>> in eine CSV-Datei exportiert und enthält folgende Parameter: +
- IDS-spezifische ID (3 Ziffern) +
- Kundennummer (4 Ziffern) +
- plentymarkets Auftragsnummer (6 Ziffern) +
- Anzahl der Colli (2 Stellen) +
- Prüfziffer (1 Stelle) +
*_Beispiel:_* 800 6913 000001 00 0 +
Im Standard ist 16 voreingetragen, was für bis zu 6-stellige Auftragsnummern ausreichend ist. +
Wenn die Anzahl der Ziffern nicht ausreicht, einen höheren Wert eingeben. Wenn z.B. 7-stellige Auftragsnummern verwendet werden, 17 eingeben.
|====

[#5500]
=== iLOPACK

Bevor Sie die Schnittstelle zu iLOPACK einrichten, registrieren Sie sich bei link:http://www.ilopack.de/[iLOPACK^].

Erstellen Sie dann im Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versanddienstleister* den Fulfillment-Dienstleister. Wählen Sie in der Spalte *Versanddienstleister* die Option *Sonstiges* aus der Dropdown-Liste. Weitere Informationen finden Sie im Kapitel <<fulfillment/versand-vorbereiten#800, Versanddienstleister erstellen>>.

Richten Sie anschließend das Versandprofil im Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile* ein. Wie Sie dazu vorgehen, ist im Kapitel <<fulfillment/versand-vorbereiten#1000, Versandprofil erstellen>> beschrieben.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu iLOPACK einzurichten. Unterhalb von <<tabelle-schnittstelle-ilopack>> wird beschrieben, wie Sie die Datenübergabe zu iLOPACK einrichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Fulfillment » iLopack*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelle-ilopack>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelle-ilopack]]
.Einstellungen der Schnittstelle zu iLOPACK
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*iLopack-User-ID*
|User-ID eingeben, wie von iLOPACK erhalten.

|*Standardlager*
|Standardlager für Aufträge wählen, die mit iLOPACK versendet werden.

|*Nach Hauptlager filtern*
|Aktivieren, wenn nur Ware berücksichtigt werden soll, für die das unter Standardlager gewählte Lager das Hauptlager ist.

|*E-Mail und Telefonnr. übertragen*
|Wählen, ob die E-Mail-Adresse und die Telefonnummer an den Dienstleister übertragen werden sollen oder nicht oder ob ein alternativer Wert übertragen werden soll. +
*_Hinweis:_* Standardmäßig werden diese Daten nicht an den Dienstleister übertragen (DGSVO-Konformität).

|*Alternative E-Mail*
|Alternative E-Mail-Adresse, die an den Dienstleister übertragen werden soll, eingeben. +
*_Wichtig:_* Damit der alternative Wert übertragen wird, muss unter *E-Mail und Telefonnr. übertragen* die Option *Alternative übertragen* gewählt sein.

|*Alternative Telefonnr.*
|Alternative Telefonnummer, die an den Dienstleister übertragen werden soll, eingeben. +
*_Wichtig:_* Damit der alternative Wert übertragen wird, muss unter *E-Mail und Telefonnr. übertragen* die Option *Alternative übertragen* gewählt sein.

|====

[.subhead]
Datenübergabe zu iLOPACK einrichten

Im Menü *Aufträge » Fulfillment » iLOPACK-Datenübergabe* richten Sie die Datenübergabe zum Fulfillment-Dienstleister iLOPACK ein. Bei der Datenübergabe werden CSV-Dateien für iLOPACK generiert und automatisch in einem Ordner auf dem FTP-Server gespeichert. iLOPACK greift dann auf diesen Ordner zu.

[.instruction]
Datenübergabe zu iLOPACK einrichten:

. Öffnen Sie das Menü *Aufträge » Fulfillment » iLOPACK-Datenübergabe*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-datenuebergabe-ilopack>>.
. Klicken Sie auf das Zahnrad, um die CSV-Datei zu erzeugen.

[[tabelle-datenuebergabe-ilopack]]
.Einstellungen im Menü *Aufträge » Fufillment » iLOPACK-Datenübergabe*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Daten*
|Wählen, ob *Aufträge* oder *Artikelstammdaten* übertragen werden sollen.

|*Mandant (Shop)*
|Einen Mandant (Shop) oder *ALLE* wählen.

|*Auftragsstatus*
|Auftragsstatus der Daten, die exportiert werden sollen, wählen.

|*Lager*
|Ein Lager oder *ALLE* wählen.

|*Ändere Auftragsstatus*
|Auftragsstatus einstellen, in den die Daten nach der Datenübergabe wechseln sollen.
|====

[#5600]
=== Fulfillment by Amazon

FBA ist das Kürzel für Fulfillment by Amazon, einem Service von Amazon, bei dem Amazon die Lagerhaltung sowie die gesamte Logistik übernimmt. Welche Einstellungen Sie vornehmen müssen, um diesen Service zu nutzen, lesen Sie auf der Handbuchseite von <<maerkte/amazon/amazon-einrichten#, Amazon einrichten>> im Kapitel <<maerkte/amazon/amazon-einrichten#3300, FBA-Service von Amazon nutzen>>.

== Amazon Prime

Sie haben in plentymarkets die Möglichkeit, Filter einzustellen, damit Aufträge mit den Versandbedingungen von Amazon Prime gesondert behandelt werden. Außerdem können Sie Versandlabel für Amazon Prime-Aufträge über die Amazon Merchant Fulfillment API generieren. Welche Einstellungen Sie vornehmen müssen, ist auf der Handbuchseite von <<maerkte/amazon/amazon-einrichten#, Amazon einrichten>> im Kapitel <<maerkte/amazon/amazon-einrichten#4200, Amazon Prime-Aufträge bearbeiten>> beschrieben.
