= Entwurf_KB_8alt
:lang: de
include::{includedir}/_header.adoc[]
:position: 9

== CBC Logistics

Dieser Versanddienstleister bietet Ihnen maßgeschneiderte Versandlösungen. CBC Logistics arbeitet mit allen Versanddienstleistern zusammen und bietet Ihnen für jeden Ihrer Versandwege die am besten passende Verbindung von A nach B an, national und international. Das kann bedeuten, dass ein Paket bis zum Ziel von mehreren Versanddienstleistern befördert wird, weil diese Kombination günstiger ist, als mit nur einem Dienstleister.

[cols="a"]
|====
2+|CBC Logistics

|**Nutzung**
|Für Händler innerhalb Deutschlands +
Versand: International

2+|Einstellungen

|<<entwurfsseiten/entwurf-kb/entwurf-kb-9alt#30, **Schnittstelle** >>
|**Einstellungen » Aufträge » Versand » Versanddienstleister » CBC Logistics**

|**Umgebung**
|Testmodus oder Live

|**Login**
|Benutzerlogin eintragen, wie von CBC Logistics erhalten.

|**Passwort**
|Passwort eintragen, wie von CBC Logistics erhalten.

|<<entwurfsseiten/entwurf-kb/entwurf-kb-9alt#50, **Versandprofil** >>
|**Einstellungen » Aufträge » Versand » Versandoptionen**

|**Versanddienstleister**
|CBC Logistics

|<<entwurfsseiten/entwurf-kb/entwurf-kb-9alt#60, **Versandservices (Portotabelle)** >>
a|Die Services richten sich nach der Auswahl der Optionen in der Portotabelle. Diese sind:
* **Profil**
* **Absender**
* **Versanddienstleister**
* **Produkt**

Je nach Wahl des Profils, des Absenders und des Versanddienstleisters werden Produkte, wie z.B. **Weltpaket** oder Services, wie **Nachnahme** oder **Sperrgut** zur Auswahl angezeigt. Es können mehrere Services pro Portotabelle gewählt werden.

|**Hinweise**
|Eine **Tagesabschlussliste** steht im **Versand-Center** zur Verfügung. Es sind dabei die Filter **Profil**, **Absender** und **Versanddienstleister** wählbar. Über die Option **Abgeschlossene Sendungen** kann eine Tagesabschlussliste vergangener Sendungen des aktuellen Tages erneut abgerufen werden.
|====

__Tab. X: CBC**Logistics**; Einstellungen__

