[.instruction]
Mapping catalogue fields:

. Go to *Data » Catalogues*.
. Click on the catalogue. +
→ The *Mapping* tab opens. +
ifdef::amazon-flatfile[]
*_Note:_* The catalogue may appear to be empty at first. Depending on the size of the flatfile, it may take several minutes before the data fields are loaded and shown. +
endif::amazon-flatfile[]
→ In the left-hand column, the market's data fields are listed. +
*_Tip:_* Mandatory fields are flagged with an asterisk (*). +
→ In the right column, you map the plentymarkets data fields. Any plentymarkets data fields that are already assigned are also shown in the right column.
. Now, map suitable plentymarkets data fields to the market data fields. Expand the info boxes below these instructions to see the different ways in which you can map the data fields. +
. *Save* (icon:save[role="green"]) the catalogue. +
→ The mappings are saved.


[.collapseBox]
.1 marketplace data field, 1 plentymarkets data field (1:1 mapping)
--
In a 1:1 mapping, you map a plentymarkets data field to the marketplace data field.

So this mapping specifies:

* I want to fill this marketplace data field with the data from this plentymarkets setting.
* If the data field is empty for a variation, no value is exported for this variation.

[.instruction]
Carrying out 1:1 mappings:

. Next to the marketplace data field, click on *+ Add data field*. +
→ To the left, the list of available plentymarkets data fields are shown in groups.
. Click on a group to expand the associated plentymarkets data fields. +
→ The plentymarkets data fields are shown.
. Click on the plus to the right of the plentymarkets data field you want to select. +
→ The plentymarkets data field is added to the right.
. Click on *Confirm*.
--

[.collapseBox]
.1 marketplace data field, 1 plentymarkets data field with alternatives (1:1 mapping with a fallback data field)
--
In a 1:1 mapping with a fallback data field, you map a plentymarkets data field to the marketplace data field. In addition, you specify one or more fallback data fields. This ensures that the system keeps looking if the first plentymarkets data field is empty or contains an invalid value.

So this mapping specifies:

* I want to fill this marketplace data field with the data from this plentymarkets setting.
* If the data field is empty or invalid for a variation, the first fallback data field is checked and the value of that fallback data field is exported instead.
* If the first fallback data field also is empty or invalid for a variation, the value of the second fallback data field is exported and so on.

[.instruction]
Carrying out 1:1 mappings with a fallback data field:

. Next to the marketplace data field, click on *+ Add data field*. +
→ To the left, the list of available plentymarkets data fields are shown in groups.
. Click on a group to expand the associated plentymarkets data fields. +
→ The plentymarkets data fields are shown.
. Click on the plus to the right of the plentymarkets data field you want to select. +
→ The plentymarkets data field is added to the right.
. In the list of plentymarkets data fields, click on the plus icon next to the plentymarkets data field that you want to map. +
→ The fallback data field is exported when the first data field does not exist or is empty. +
*_Note:_* Even if you map one or more fallback data fields to a marketplace data field, only one value is exported for each variation. For each variation, the plentymarkets data fields are checked in the order in which you mapped them. This means that if the first data field does not provide a value for a variation, the first fallback data field is exported etc.
. Click on *Confirm*.
--

[.collapseBox]
.1 marketplace data field, several plentymarkets data fields (1:n mapping)
--
In a 1:n mapping, you map several plentymarkets data fields to the marketplace data field. You can link these settings with a separator.

So this mapping specifies:

* I want to combine these plentymarkets data fields during export so that the marketplace data field is filled with the data of these two or more plentymarkets settings.

[.instruction]
Carrying out 1:n mappings:

. Next to the marketplace data field, click on *+ Add data field*. +
→ To the left, the list of available plentymarkets data fields are shown in groups.
. Click on a group to expand the associated plentymarkets data fields. +
→ The plentymarkets data fields are shown.
. Click on the plus to the right of the plentymarkets data field you want to select. +
→ The plentymarkets data field is added to the right.
. Click on *Confirm*.
. To the right of the mapped plentymarkets data field, click on *Add data field* (icon:link[rotate=90]). +
→ To the left, the list of available plentymarkets data fields again are shown in groups.
. Map one or several additional plentymarkets data fields to the marketplace data field as described above.
. Click on *Confirm*.
. To the very right of the row, click on *Settings* (icon:cog[]).
. Select a separator from the drop-down list *Separator* or add a custom separator.
. *Save* the settings.
. *Save* (icon:save[role="green"]) the catalogue. +
→ The mappings are saved. +
→ During the export, the content of the plentymarkets data fields is combined and exported as one field.
--

[.collapseBox]
.1 marketplace data field, the same value for all variations (own value mapping)
--
You are sure that you want to export the same value for all variations of a catalogue for a marketplace data field? Then specify an own value. This own value is then exported for all variations.

So this mapping specifies:

* For this marketplace data field, I want to export the value that I entered in the field *Own value* for _all_ variations of this catalogue.

[.instruction]
Mapping an own value:

. Next to the marketplace data field, click on *+ Add data field*. +
→ To the left, the list of available plentymarkets data fields are shown in groups.
. Click on the plus next to *Own value* at the top of the list. +
→ The field for the own value is added to the view.
. Enter a value into the input field. +
→ This value is exported for all variations.
--

////
[#datenfelder-zuordnen]
=== Datenfelder im Katalog zuordnen

include::../../_textblocks/catalogues/instructions/catalogue-mapping.adoc[]
////


////
[#map-data-fields]
=== Mapping data fields in the catalogue

include::../../_textblocks/catalogues/instructions/catalogue-mapping.adoc[]
////
