[.instruction]
ifdef::catalogue-assistant[]
Mapping additional data fields in the catalogue:
endif::catalogue-assistant[]
ifndef::catalogue-assistant[]
Mapping data fields in the catalogue:
endif::catalogue-assistant[]

. Go to *Data » Catalogues*.
. Click on the catalogue. +
→ The *Mapping* tab with the market data fields opens. +
ifdef::amazon-flatfile[]
*_Note:_* The catalogue appears to be empty at first. Depending on the size of the flatfile, it may take several minutes before the data fields are loaded and shown. +
endif::amazon-flatfile[]
→ In the left-hand column, the market's data fields are listed. +
*_Tip:_* Mandatory fields are flagged with an asterisk (*).
. Next to the marketplace data field, click on *+ Add data field*. +
→ To the left, the list of available plentymarkets data fields are shown in groups.
. Map the field:
* *_Alternative 1:_ Map a plentymarkets data field + optional fallback data fields*
  .. Click on a group to expand the associated plentymarkets data fields. +
  → The data fields are shown.
  .. Click on the plus to the right of the plentymarkets data field you want to select.
  .. *_Optional:_* Add one or more fallback data fields. To do so, click on the plus to the right of the plentymarkets data field you want to select. +
  → The fallback data field is exported when the first data field does not exist or is empty. +
  *_Note:_* Even if you assign a fallback data field to a market data field, only one value is exported. The fields are checked in the order in which you mapped them. This means that if the first data field does not provide a value, the first fallback data field is exported etc.
  .. Click on *Confirm*.
* *_Alternative 2:_ Always export the same value for a market data field*
    .. Click on the plus next to *Own value* at the top of the list. +
    → The field for the own value is added to the view.
    .. Enter a value into the input field. +
    → This value is exported for all variations.
. Continue to map all data fields of the market for which you want to export product information. +
. *Save* (icon:save[role="green"]) the catalogue. +
→ The mappings are saved.

[.collapseBox]
.*_Optional:_* 1:n mappings - 1 marketplace data field, several plentymarkets data fields
--
. Map a plentymarkets data field or an own value to the marketplace data field as described above.
. To the right of the mapped plentymarkets data field, click on *Add data field* (icon:link[rotate=90]). +
→ To the left, the list of available plentymarkets data fields again are shown in groups.
. Map one or several additional plentymarkets data fields to the marketplace data field as described above.
. Click on *Confirm*.
. To the very right of the row, click on *Settings* (icon:cog[]).
. Select a separator from the drop-down list *Separator* or add a custom separator.
. *Save* the settings.
. *Save* (icon:save[role="green"]) the catalogue. +
→ The mappings are saved. +
→ During the export, the content of the plentymarkets data fields is combined and exported as one field.
--

////
[#map-data-fields]
=== Mapping data fields in the catalogue

include::../../_textblocks/catalogues/instructions/catalogue-map-data-fields.adoc[]
////
