= Old online store: ADU-Inkasso
:lang: en
include::{includedir}/_header.adoc[]
:keywords: ADU-Inkasso, debt collection service provider
:description: Payment in plentymarkets: Set up the debt collection service provider ADU-Inkasso in your plentymarkets system.
:position: 30

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *ADU-Inkasso* in Callisto online stores. The following instructions are not valid for Ceres online stores!
====

Set up link:http://www.adu-inkasso.de/en/home/[ADU-Inkasso^] (Allgemeiner Debitoren- und Inkassodienst GmbH) in plentymarkets to manage outstanding debts by transferring the data automatically to ADU-Inkasso with the help of a specific sales order status. The current processing status of outstanding debts is visible in the back end. Learn how to set up the interface to ADU-Inkasso in your plentymarkets system.

[#10]
== Registering with ADU-Inkasso

Register with link:https://www.auskunft.inkassounternehmen.de/?action=register[ADU-Inkasso^] (German only) in order to use its services. You will receive your access data to the ADU-Inkasso online portal once you have registered and signed a contract.

[#20]
== Carrying out settings in the ADU-Inkasso account

Log into the link:https://www.auskunft.inkassounternehmen.de[ADU-Inkasso online portal^] with your access data and open the menu *Aktenimport* (file import) in order to activate the interface. Carry out the following settings in this menu.

* Enter access data
* Enter PlentyID and SOAP-WSDL. This information can be found in the *System » Settings » API » Data* menu.
* Save login data

Once you have activated the interface, you can select an <<orders/managing-orders#1200, order status>> to display the corresponding debts in the online portal. Furthermore, you can specify whether debts should be transferred to ADU-Inkasso automatically or manually. For further information, refer to the link:http://www.adu-inkasso.de/fileadmin/user_upload/Beschreibung_plentymarkets.pdf[Interface description^] page (German only) of ADU-Inkasso.

[#30]
== Viewing the processing status

The dunning procedure will be started once the debts were transferred. You can easily see the status of debts that were transferred. Open the corresponding order in your plentymarkets system to access the information in the customer note. You can also access the ADU-Inkasso online portal for more detailed information. It can be accessed directly from the customer note. This allows you to always keep an eye on your debts.

[.instruction]
Displaying a customer note:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Notes*. +
→ The *Customer notes* window will open.
. In the customer note, click on *zu ADU Inkasso* (to ADU Inkasso). +
→ You will be forwarded to the ADU-Inkasso online portal.
