= Old online store: Amazon Pay
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Amazon Pay, Amazon Payments Advanced, payment method
:description: Payment in plentymarkets: Set up the interface to Amazon Pay in your plentymarkets system.
:position: 40
:url: payment/payment-providers/amazon-pay

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *Amazon Pay* in Callisto online stores. For further information on using *Amazon Pay* in Ceres online stores, refer to the detailed information in the plugin description available in the link:https://marketplace.plentymarkets.com/plugins/payment/AmazonLoginAndPay_5072[plentyMarketplace^].
====

*Pay with Amazon* is a comprehensive payment solution for online sellers. Offer *Pay with Amazon* and enable millions of Amazon customers to shop securely on your website without re-entering their delivery and payment information. Customers can complete purchases quickly without leaving your website. The advanced option for Payment with Amazon is special because it offers pure payment processing. This means that you only transfer the necessary amount due in order to process the payment. No details about the shopping cart or item data will be transferred (see Amazon).

[#10]
== Important notes

This chapter provides you with important information about integrating the payment provider in plentymarkets.

[IMPORTANT]
.Amazon Pay and store design
====
Note that the following conditions must be met before integrating Amazon Pay successfully in plentymarkets:

* Use of the standard design Callisto (Version 3.4 or higher)
* Use of the individual order process
* Safe handling of the plentymarkets CMS
* Experience with integrating payment providers
====

[IMPORTANT]
.Pay attention to the delivery periods
====
If you use this payment method, then make sure that you can process your orders in 30 days or less. Otherwise they will automatically be cancelled after 30 days. If you sell items that generally take longer to process and deliver, then get in contact with the customer support provided by Amazon Pay. The deadline can be extended in individual cases.
====

[#20]
== Payment process with Amazon Pay

After the customer has added an item to the shopping cart (template: *ItemViewItemToBasketConfirmationOverlay*) a button is displayed (template variable: *$AmazonPaymentsAdvancedButton*). By clicking this button, the customer will be forwarded directly to Amazon Pay. The customer then has to log into Amazon Pay. The customer will then go through the widgets confirming the delivery address and the payment method in your online store. The customer will then go through the rest of the order process as usual. The payment by Amazon Pay will not be triggered before the order has been completed. +
Amazon Pay payments can also be started directly from the shopping cart, if the customer clicks on the corresponding button there. Furthermore, the customer can select Amazon Pay later when selecting the payment method during the checkout. In this case, the customer will be forwarded to the Amazon Pay page  and continues with the same process as described above.

[#30]
=== SSL certificate

Your online store needs to have an <<basics/admin-tasks/plentymarkets-account#ssl-certificate, SSL certificate>> in order for you to be able to use Amazon Pay. Several elements of this payment method are also included in the *CMS*. This makes it necessary to <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design, publish the design>> after configurations or changes have been carried out.

[#40]
== Registering with Amazon Pay

You need to set up a separate account for Amazon for the *Amazon Pay* payment method. You cannot use the Amazon Seller Central account that you created in the *System » System settings » Markets » Amazon » Settings* menu for this payment method. For further information about how to register with *Pay with Amazon*, refer to the link:https://payments.amazon.co.uk/help/201212200[Amazon Pay Integration Guide^].

Creating a seller account usually takes about 1 to 2 weeks. This estimate includes the time needed for information to be verified. During this time, you will receive emails from Amazon Pay containing further instructions. Make sure that these emails are forwarded to the correct employee and that they follow the instructions in the emails to avoid any unnecessary delays.

[IMPORTANT]
.Entering the merchant URL and the integrator URL
====
You have to save the merchant URL and the integrator URL *your-plentystore.co.uk/plenty/api/payment_notification.php?payment=apa* in Amazon Pay. Replace *your-plentystore.co.uk* with the address of your online store. The address of your online store can be found under *Host* in the *System » System settings » Settings » API » Data* menu. The *https://* protocol must be entered. Refer to the link:https://payments.amazon.co.uk/help/201212200[Amazon Pay registration manual^] for further information.
====

[#50]
== Setting up Amazon Pay for Callisto

Proceed as follows to set up the interface to Amazon Pay for your Callisto online store in plentymarkets.

[.instruction]
Setting up the interface to Amazon Pay:

. Go to *System » System settings » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
.  Click on *Amazon Pay*. +
→ The *Settings* tab will open.
. Click on the *Interface* tab.
.  Expand the client.
.  Carry out the settings as desired. Pay attention to the information given in <<table-setup-amazon-pay-interface>>.
. *Save* the settings.

[[table-setup-amazon-pay-interface]]
.Setting up the interface to Amazon Pay
[cols="1,3"]
|====
| Setting | Explanation

|*Seller ID*
| Enter the seller ID that you received from Amazon.

|*Market ID*
| Select a country.

|*MWS Access Key ID*
| Enter the MWS Access Key ID that you received from Amazon.

|*Secret Key*
| Enter the Secret Key that you received from Amazon.

|*Sandbox mode*
|*Yes* = Test mode is activated in order to test the payment method. +
*No* = Test mode is deactivated. This means that the interface is active.

|*AddressWidget Width*
| Enter the amount of pixels in order to determine the width of the Amazon address widget. The Amazon address widget is displayed instead of a delivery address selection.

|*AddressWidget Height*
| Enter the amount of pixels in order to determine the height of the Amazon address widget. The Amazon address widget is displayed instead of a delivery address selection.

|*AddressWidget ReadOnly Width*
| Enter the amount of pixels in order to determine the width of the Amazon address widget in the order overview. The Amazon address widget in the order overview cannot be edited.

|*WalletWidget Width*
| Enter the amount of pixels in order to determine the width of the Amazon payment method widget. If Amazon Pay was selected, then this widget will be displayed instead of the payment methods during the checkout. The selected payment method will be displayed to the customer.

|*WalletWidget Height*
| Enter the amount of pixels in order to determine the height of the Amazon payment method widget.

|*WalletWidget ReadOnly Width*
| Enter the amount of pixels in order to determine the width of the Amazon payment method widget in the order overview. The selected payment method is displayed in this widget in the order overview and cannot be edited.

|*Availability*
| Select the availability. +
*1* - *10* = Only items available up to the selected availability can be paid with Amazon Pay. +
*Do not check* = The availability of the items will not be checked. +
Set the <<item/managing-items#170, availability>> in the tab of a variation. +
*Important:* Amazon Pay generally requires you to ship an item within a maximum of 30 days. Otherwise the payment will be cancelled.
|====

[IMPORTANT]
.One account per client (store)
====
You must have a separate Amazon Pay account for every client. Therefore, you will find a submenu for each client in the *Interface* tab. Enter the individual access data for each store.
====

[#60]
== Activating the payment method

Set up and activate the Amazon Pay <<payment/managing-payment-methods#20, payment method>> in the *Settings* tab of the payment method. In addition, check the settings for *Permitted payment methods* in the <<payment/managing-payment-methods#30, customer classes>> and for *Blocked payment methods* in the <<fulfilment/preparing-the-shipment#1000, shipping profiles>>.

[#70]
== Displaying Amazon Pay in the online store

An option to the default display of Amazon Pay in the online store, the template functions *Container_CheckoutAmazonPaymentsAdvancedAddressWidget()* and *Container_CheckoutAmazonPaymentsAdvancedPaymentWidget()* can be used to display the address and payment widgets for Amazon Pay individually in the online store. In addition, you will find multiple examples for integrating the *Pay with Amazon* button at the desired position in the design.

[WARNING]
.No changes to the active design
====
Do not make changes to your active design. Before making changes to the design, make a backup copy so that you can restore the original state of the design.
====

[#80]
=== Displaying the Amazon Pay widgets

Proceed as described below to display the address and payment widgets for Amazon Pay individually in the online store.

[.instruction]
Displaying the Amazon Pay widgets in the order process:

. Go to *Item » Categories*.
. Open the design's folder, e.g. the folder for Callisto Light 3.
. Open the category *Payment &amp; shipping*.
. Click on the *Description 1* tab.
. Insert the code example at a desired position.
. *Save* the settings.

[.subhead]
Code example for the Amazon Pay widgets:

[source,plenty]
----
include::assets/EX-EN-Amazon-Payments-Advanced-Payment-Shipping.html[]

----
[#90]
=== Editing ItemViewItemToBasketConfirmationOverlay

Proceed as described below to integrate the *Pay with Amazon* button at the desired position in the overlay for the shopping cart. The overlay will be displayed after the customer clicked on the *Add to shopping cart* button in the online store.

[.instruction]
Editing ItemViewItemToBasketConfirmationOverlay:

. Go to *CMS » Web design*.
. Open the folder *Layout » ItemView*.
. Open the template *ItemViewItemToBasketConfirmationOverlay*.
. Insert the code example at a desired position.
. *Save* the settings.

[.subhead]
Code example for integrating the *Pay with Amazon* button in the overlay:

[source,plenty]
----
include::assets/EX-EN-Amazon-Payments-Advanced-Overlay.html[]

----
[#100]
=== Editing ItemViewBasketPreviewList

Proceed as described below to integrate the *Pay with Amazon* button at the desired position in the shopping cart preview.

[.instruction]
Editing ItemViewBasketPreviewList:

. Go to *CMS » Web design*.
. Open the folder *Layout » ItemView*.
. Open the template *ItemViewBasketPreviewList*.
. Insert the code example at a desired position.
. *Save* the settings.

[.subhead]
Code example for integrating the *Pay with Amazon* button in the shopping cart preview:

[source,plenty]
----
include::assets/EX-EN-Amazon-Payments-Advanced-Shopping-Cart-Preview.html[]

----
[#110]
=== Customising the Shopping cart category

Proceed as described below to integrate the *Pay with Amazon* button at the desired position in the shopping cart.

[.instruction]
Customising the Shopping cart category:

. Go to *Item » Categories*.
. Open the design's folder, e.g. the folder for Callisto Light 3.
. Open the category *Shopping cart*.
. Click on the *Description 1* tab.
. Insert the code example at a desired position.
. *Save* the settings.

[.subhead]
Code example for integrating the *Pay with Amazon* button in the shopping cart:

[source,plenty]
----
include::assets/EX-EN-Amazon-Payments-Advanced-Shopping-Cart.html[]

----
[#120]
=== Customising the Log in category

Proceed as described below to integrate the *Pay with Amazon* button at the desired position in the registration.

[.instruction]
Customising the Log in category:

. Go to *Item » Categories*.
. Open the design's folder, e.g. the folder for Callisto Light 3.
. Open the category *Log in*.
. Click on the *Description 1* tab.
. Insert the code example at a desired position.
. *Save* the settings.

[.subhead]
Code example for integrating the *Pay with Amazon* button in the log in:

[source,plenty]
----
include::assets/EX-EN-Amazon-Payments-Advanced-Log-In.html[]

----
[#130]
== Automatically sending notifications

Automate communication with your customers using Amazon Pay as payment methods for their orders. The following chapters list the necessary event procedures to automatically send <<payment/payment-providers/amazon-pay#140, shipping confirmations>>, <<payment/payment-providers/amazon-pay#150, cancellations>> as well as for processing <<payment/payment-providers/amazon-pay#160, refunds>> and reporting <<payment/payment-providers/amazon-pay#170, rejected payments>>.

[IMPORTANT]
.Sending order confirmations
====
In addition to the event procedures described below, you can also set up an event procedure that automatically sends order confirmations to customers via email. However, note that Amazon Pay only imports customers' email addresses into your plentymarkets system after payment has been effected. To avoid mistakes, we recommend to set up the event procedure so that the email is not sent when the order comes in, but when incoming payment has been booked.
====

[#140]
=== Automatically sending shipping confirmations

Set up an <<automation/event-procedures#, event procedure>> to automatically send shipping confirmations to Amazon when the outgoing items are booked. Booking the outgoing items and sending the shipping confirmation should not take place within the same event procedure. Otherwise, shipping of items might be confirmed before the outgoing items have been booked. Therefore, set up a separate event procedure to book the outgoing items that at the same time changes the status to 7.1, for example. Use the same status as event for the event procedure to send the shipping confirmation. In doing so, only those orders will be taken into consideration that have this status. If you have not created the status yet, go to <<orders/managing-orders#1200, System » System settings » Orders » Order status>> to do so.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » System settings » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter name.
.  Select the *event* listed in table 2.
. *Save* the settings.
.  Pay attention to the explanations given in table 2 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for automatically booking outgoing items
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Outgoing items booked*
|

|*Filter 1*
|*Order &gt; Payment method*
|*Amazon Pay*

|*Filter 2*
|*Order &gt; Order type*
|*Order*

|*Procedure*
|*Order &gt; Change status*
|
|====

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » System settings » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter name.
.  Select the *event* listed in table 3.
. *Save* the settings.
.  Pay attention to the explanations given in table 3 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for automatically sending shipping confirmations to Amazon Pay
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Status change*
|*Select status from previous event procedure.*

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Payment method*
|*Amazon Pay*

|*Procedure*
|*Shipping &gt; Send shipping confirmation to Amazon Pay*
|
|====

[#150]
=== Automatically sending cancellations

Set up an <<automation/event-procedures#, event procedure>> to automatically inform Amazon of cancellations.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » System settings » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter name.
.  Select the *event* listed in table 4.
. *Save* the settings.
.  Pay attention to the explanations given in table 4 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for automatically sending cancellations to Amazon Pay
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Status change*
| Select status for *cancelled orders*.

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Payment method*
|*Amazon Pay*

|*Procedure*
|*Payment methods &gt; Send cancellations to Amazon Pay*
|
|====

[#160]
=== Automatically sending refunds

Create an *order status* for *returns* from Amazon Pay. This status will indicate that the return was checked and the correct amount was refunded. Corresponding returns then have to be given this order status. Give this order status an appropriate name, e.g. *Return checked*. Save this order status for the event procedures described below.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » System settings » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter name.
.  Select the *event* listed in table 5.
. *Save* the settings.
.  Pay attention to the explanations given in table 5 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for automatically sending refunds to Amazon Pay
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Status change*
| Select the order status that you created for *checked returns*.

|*Filter 1*
|*Order &gt; Order type*
|*Return*

|*Filter 2*
|*Order &gt; Payment method*
|*Amazon Pay*

|*Procedure*
|*Payment methods &gt; Send refund to Amazon Pay*
|
|====

Alternatively, the refund can be created through the order. Create an order status for credit notes from Amazon Pay. This status will indicate that the credit note was checked and the correct amount was refunded. Corresponding credit notes then have to be given this order status. Give this order status an appropriate name, e.g. "credit note checked". Save this order status for the event procedures described below.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » System settings » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter name.
.  Select the *event* listed in table 6.
. *Save* the settings.
.  Pay attention to the explanations given in table 6 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for automatically sending refunds to Amazon Pay
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Status change*
| Select the status for the *Credit note to Amazon Pay*.

|*Filter*
|*Order &gt; Order type*
|*Credit note*

|*Procedure*
|*Payment methods &gt; Send refund to Amazon Pay*
|
|====

[#170]
=== Automatically reporting rejected payments

Set up an <<automation/event-procedures#, event procedure>> to automatically inform your customers of rejected payments. In order to inform your customers by email of rejected Amazon payments and change the status of these payments, create an *order status* for *rejected payments* by Amazon Pay or use an existing order status.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » System settings » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter a name.
.  Select the *event* listed in table 7.
. *Save* the settings.
.  Pay attention to the explanations given in table 7 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for automatically reporting rejected payments by Amazon Pay
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Payment: Rejected*
|

|*Filter 1*
|*Order &gt; Payment method*
|*Amazon Pay*

|*Filter 2*
|*Order &gt; Payment status*
|*Rejected*

|*Procedure 1*
|*Customer &gt; Send email*
| Select email template; +
Select *Customer*

|*Procedure 2*
|*Order &gt; Change status*
| Select the order status, e.g. *[3.2] In waiting position*
|====
