= Old online store: BitPay
:lang: en
include::{includedir}/_header.adoc[]
:keywords: BitPay, payment method
:description: Payment in plentymarkets: Set up the interface to BitPay in your plentymarkets system.
:position: 60

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *BitPay* in Callisto online stores. The following instructions are not valid for Ceres stores!
====

BitPay is a leading payment service provider specialising in the peer-to-peer virtual currency Bitcoin. BitPay provides for instantaneous transactions from anywhere in the world with no risk of fraud or chargebacks.

[#10]
== Important notes

This chapter provides you with important information about integrating the payment provider in plentymarkets.

[.subhead]
Payment process

Once the order has been placed, the customer will receive a message asking them to click on a link and make the payment. The customer will be forwarded to the BitPay website after having clicked on the link. The customer has to enter the necessary data for the payment. Once the customer has entered and confirmed the data, they will be forwarded to the order confirmation page.

[.subhead]
Manual payment import

BitPay payments will not be automatically imported into plentymarkets. BitPay payments must be <<order-processing/payment/managing-payments#40, booked manually>>.

[#20]
== Registering with BitPay

You need to register with BitPay before you can set up the payment method in plentymarkets. link:https://bitpay.com/start[Contact^] the payment provider in order to complete the registration process. You will then receive the necessary information as well as the access data that you need for the configuration in plentymarkets.

[#30]
== Setting up BitPay for Callisto

Proceed as described below to set up the interface to BitPay for your Callisto online store in plentymarkets.

[.instruction]
Setting up the interface to BitPay:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
.  Click on *BitPay*. +
→ The *Settings* tab will open.
. Click on the *Interface* tab.
.  Expand the client.
.  Carry out the settings as desired. Pay attention to the information given in <<table-setup-bitpay-interface>>.
. *Save* the settings.

[[table-setup-bitpay-interface]]
.setting up the interface to BitPay
[cols="1,3"]
|====
|Setting |Explanation

|*ApiKey*
|Enter the ApiKey from BitPay. The link:https://bitpay.com/api-keys[ApiKey^] can be generated after having registered with BitPay.

|*Email notification to*
|Enter the email address that payment notifications should be sent to.

|*Data transfer rate*
|Select the data transfer rate. +
*low* = low transfer rate +
*medium* = medium transfer rate +
*high* = high transfer rate

|*Activate test mode*
|Activate the test mode and check the BitPay functions before working live with the system.

2+|Client (store) options

|*Activate access data for all clients (stores)*
|Only visible if clients (stores) were set up. Activate to apply the account settings saved for the main store by clicking on *Add account* for all clients (shops). This setting is dominant over the settings saved for each client. Deactivate to use separate access data for your clients (stores). Online stores that do not have account settings saved for them cannot be used with BitPay. +
Go to <<omni-channel/online-store/setting-up-clients/online-store#, System » Client » Select client » Online store » Settings>> and make sure that you have selected the option *Enable login for every store* in the line *Login*. This makes it possible to support several clients.
|====

[#40]
== Activating the payment method

Set up and activate the BitPay <<order-processing/payment/managing-payment-methods#20, payment method>> in the *Settings* tab of the payment method. In addition, check the settings for *Permitted payment methods* in the <<order-processing/payment/managing-payment-methods#30, customer classes>> and for *Blocked payment methods* in the <<order-processing/fulfilment/preparing-the-shipment#1000, shipping profiles>>.

[#50]
== Viewing the API log

In the rare case that an error occurs during data transmission, you will find details about the corresponding error in the API Log. Depending on the type of error, the payment may be booked in BitPay but may not be verified in plentymarkets. This will cause an erroneous booking in plentymarkets.

[.instruction]
Viewing the API log:

.  Go to *Data » API log » Tab: API log*.
.  Select a format from the drop-down list *Process*.
.  Select a *Date* if you only want to see entries for a specific day.
.  Click on *Search* to carry out the search. +
→ The processes will be displayed.
