= Old online store: heidelpay
:lang: en
include::{includedir}/_header.adoc[]
:keywords: heidelpay, payment method
:description: Payment in plentymarkets: Set up the interface to heidelpay in your plentymarkets system.
:position: 100

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *heidelpay* in Callisto online stores. For further information on using *heidelpay* in Ceres online stores, refer to the detailed information in the plugin description available in the link:https://marketplace.plentymarkets.com/plugins/payment/Heidelpay_5700[plentyMarketplace^].
====

Heidelberger Payment GmbH, in short heidelpay, is a leading European Service Provider that deals with the topic of payment. The services offered by this PCI/DSS certified company range from worldwide E-Payment solutions to debtor management and risk management functions all the way to various offers for alternative payment procedures - quick, secure, simple and comprehensive.

[#10]
== Important notes

This chapter provides you with important information about integrating the payment provider in plentymarkets.

[#20]
=== Payment process

The customer is forwarded to heidelpay for the payment process and an iframe prompts the customer to enter their necessary data. The payment method is selected in the online store. Afterwards, the customer is forwarded directly to heidelpay. The additional content is made available in an iframe. The customer enters their data here. In other words, the data is not entered in the online store, but rather in heidelpay. Once the customer has entered and confirmed the data, they will be forwarded to the order confirmation page.

[#30]
=== SSL certificate

You need to have an <<basics/admin-tasks/plentymarkets-account#ssl-certificate, SSL certificate>> in order to correctly use the payment method.

[WARNING]
.Ask your bank
====
Ask your bank whether it can process payments with iframe before you integrate this payment method.
====

[#40]
=== Available heidelpay payment methods

Below you will find an overview of the heidelpay payment methods that are available for plentymarkets. They are displayed along with the corresponding System ID in parentheses.

* Online debit (1000)
* Cash in advance (1020)
* Invoice (1030)
* Credit cards (1040)
* Electronic cash cards (1050)
* Bank transfer with PIN/TAN (1060)
* Virtual account (1070)
* User account (1080)
* Sofortbanking (1090)
* T-Pay (1091)
* Giropay (1092)
* IDEAL (NL) (1093)
* EPS (AT) (1094)
* Carte Bleue (1095)

[#50]
== Registering with heidelpay

Contact the heidelpay sales team at Tel. +49 (0)6221-6517020 or link:mailto:sales@heidelpay.de[sales@heidelpay.de] and ask for an offer. Sign the offer and send it back to heidelpay. You will receive your credit card acceptance contract from heidelpay, which you can sign. Once the bank has agreed you will receive the heidelpay access data. You will need the access data for activation in plentymarkets.

[#60]
== Setting up heidelpay for Callisto

Proceed as described below to set up the interface to heidelpay for your Callisto online store in plentymarkets. The <<order-processing/payment/heidelpay#80, Options>> submenu is also used for heidelpay where you save a stylesheet (CSS) for heidelpay.

[.instruction]
Setting up the interface to heidelpay:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
.  Click on *heidelpay*. +
→ The *Interface* tab will open.
.  Expand the client.
.  Carry out the settings as desired. Pay attention to the information given in <<table-setup-heidelpay-interface>>.
. *Save* the settings.

[[table-setup-heidelpay-interface]]
.setting up the interface to heidelpay
[cols="1,3"]
|====
|Setting |Explanation

2+|Login details

|*User name*
|Enter 32-digit login code that you received from heidelpay.

|*Password*
|Enter 8-digit password that you received from heidelpay.

|*SENDER*
|Enter 32-digit code that you received from heidelpay.

|*Channel*
|Enter 32-digit code that you received from heidelpay.

|*Transaction mode*
|Enter *LIVE*.

|*Server*
|Enter the payment server's URL that you received from heidelpay. +
Enter the payment URL *POST* (UTF-8 encoded).

2+|Online transfer payment methods: channel ID

|*Sofortüberweisung, T-Pay, Giropay, IDEAL, EPS*
|Enter the channel ID for the payment methods.

2+|Client (store) options

|*Activate access data for all clients (stores)*
|Only visible if clients (stores) were set up. Activate to apply the account settings saved for the main store by clicking on *Add account* for all clients (shops). This setting is dominant over the settings saved for each client. Deactivate to use separate access data for your clients (stores). Online stores that do not have account settings saved for them cannot be used with heidelpay. +
Go to <<omni-channel/online-store/setting-up-clients/online-store#, System » Client » Select client » Online store » Settings>> and make sure that you have selected the option *Enable login for every store* in the line *Login*. This makes it possible to support several clients.
|====

[#70]
== Activating payment methods

For heidelpay, a large variety of payment methods is available. Go to <<order-processing/payment/managing-payment-methods#20, System » Orders » Payment » Payment methods>> to activate the payment methods. In addition, check the settings for *Permitted payment methods* in the <<order-processing/payment/managing-payment-methods#30, customer classes>> and for *Blocked payment methods* in the <<fulfilment/preparing-the-shipment#1000, shipping profiles>>.

[#80]
== Displaying heidelpay in the Callisto online store

In the *Options* submenu, you can set up a stylesheet and banner, as well as a front end link.

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
.  Click on *heidelpay*. +
→ The *Interface* tab will open.
.  Expand the *Options* area.
.  Carry out the settings as desired. Pay attention to the information given in <<table-options-heidelpay>>.
. *Save* the settings.

[[table-options-heidelpay]]
.options for heidelpay
[cols="1,3"]
|====
|Setting |Explanation

2+|Stylesheet and banner

|*Active stylesheet file*
|A *preview icon* will be shown here, which displays the stylesheet file that was uploaded.

|*Upload stylesheet file (CSS)*
|Click on *Browse...* to upload a file. After saving the settings, the file will be displayed under *Active stylesheet file*. Only files in CSS format can be uploaded.

|*Active banner file*
|A *preview icon* will be shown here, which displays the banner file that was uploaded.

|*Upload banner file (PNG)*
|Click on *Browse...* to upload a file. After saving the settings, the file will be displayed under *Active banner file*. Only files in PNG format can be uploaded. The maximum size of a banner is 570 x 40 pixels.

2+|Link document

|*Select link document*
|Select the document that you would like to be displayed after clicking on the link. If you would like to link a document that is not found in this selection, then choose the option *user-defined*.

|*"User-defined" text*
|Enter the user-defined link to be displayed when selecting the option *user-defined* under *Select link document*. +
You can also use these text lines in order to only display the entered text in the link position, e.g. a note.

|*Orientation*
|Select *left*, *centered* or *right*.

|*Active link file*
|A preview icon will be shown here, which displays the link file that was uploaded.

|*Upload link file (HTML)*
|Click on *Browse...* to upload a file. After saving the settings, the file will be displayed under *Active link file*. Only files in HTML format can be uploaded.

|*Pop-up window: width*
|Enter the width of the window in pixels.

|*Pop-up window: height*
|Enter the height of the window in pixels.
|====

[.subhead]
CSS stylesheet

You can use the following example code for the stylesheet for heidelpay.

[source,plenty]
----
include::assets/EX-EN-heidelpay-CSS.html[]

----
