= Old online store: mediafinanz
:lang: en
include::{includedir}/_header.adoc[]
:keywords: mediafinanz, debt collection service provider
:description: Payment in plentymarkets: Set up the interface to the debt collection service provider mediafinanz in your plentymarkets system.
:position: 150

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *mediafinanz* in Callisto online stores. The following instructions are not valid for Ceres online stores!
====

mediafinanz AG is Germany's first debt recovery management organisation to be TÜV (Technical Inspection Authority) tested and certified. The company is now firmly established in the sector, thanks to over ten years' experience as a pioneering supplier of web-based debt recovery services. Learn how to set up the debt collection service provider mediafinanz in plentymarkets.

[#10]
== Registering with mediafinanz

You need to register with link:https://www.mediafinanz.de/en/collection-services[mediafinanz^] before setting up the interface in plentymarkets.

[#20]
== Setting up mediafinanz for Callisto

In order to set up mediafinanz for your Callisto online store in plentymarkets, you must check and complete your company details, if needed.

[.instruction]
Entering company details:

. Go to *System » Settings » Master data*.
. Enter the company name.
. Enter the chief executive officer.
. Enter the company's address.
. Enter a telephone number.
. Enter an email address.
. *Save* the settings.

After reloading the *Settings* tab, the updated data will be visible in the *Company details* tab under *mediafinanz*. Then activate the interface to mediafinanz.

[.instruction]
Activating the interface to mediafinanz:

. Go to *System » Orders » Debt collection » mediafinanz*. +
→ The *Settings* tab will open.
. Click on *Activate Mediafinanz*. +
→ The interface will be activated.

[#30]
== Assigning a dunning level

In order to assign a dunning level to unpaid orders, an <<order-processing/orders/managing-sales-orders#order-status, order status>> is required. You can use one of the standard statuses or set up your own order status. The following procedure will assign a dunning level to unpaid orders.

[.instruction]
Assigning a dunning level with the procedure manager:

. Go to *System » Orders » Procedures*.
. Click on the *New procedure* tab.
. Place a check mark next to the option *Active* to activate the procedure.
. Select a time from the *Execute every day at* drop-down list.
. Enter a *name* for the procedure.
. Click on the *Filter* tab.
. Select the status for unpaid orders.
. Select *Enter the days* from the *Last status change* option. +
→ The *Days* field will be shown.
. Enter the number of days for an order in the respective status.
. Select the option *OPEN* under *Incoming payment*.
. Click on the *Procedure* tab.
. Select the status for assigning the dunning level under *Change order status*.
. Select a dunning level under *Change dunning level*.
. *Save* the settings.

[#40]
== Adding a dunning charge

The information will be transferred to mediafinanz as an item, e.g. with the name *dunning charge* and the charge as its price. This item will be added to unpaid orders that have been filtered by the procedure above. This will be done manually or automatically with the help of an event procedure. Unpaid orders will only be transferred to mediafinanz if a dunning charge item was added. Learn how to create items on the <<item/managing-items#20, Creating items>> page. Then, save the item ID in the *mediafinanz* menu.

[.instruction]
Saving the item ID:

. Go to *System » Orders » Debt collection » mediafinanz*.
. Enter the ID of the previously created item under *Item ID dunning charge*.
. *Save* the settings.

Set up an <<basics/automation/event-procedures#, event procedure>> to automatically assign the dunning charge item to unpaid orders.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter a name.
.  Select the *Event* listed in <<table-event-procedure-mediafinanz-dunning-charge-item>>.
. *Save* the settings.
.  Pay attention to the explanations given in <<table-event-procedure-mediafinanz-dunning-charge-item>> and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[table-event-procedure-mediafinanz-dunning-charge-item]]
.Event procedure for automatically assigning dunning charge items to unpaid orders
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order change: Status change*
|Select the status for *assigning the dunning level*.

|*Filter*
|*Order > Dunning level*
|*Dunning level*

|*Procedure 1*
|*Item > Generate dunning letter*
|*Enter variation ID*

|*Procedure 2*
|*Order > Change dunning level*
|*Higher dunning level*
|====

[#50]
== Transferring orders to mediafinanz

You can now go to the procedure manager and set up a procedure for automatically transferring specific orders to mediafinanz. For example, you could use an order status or a dunning level to filter the orders. Doing so would allow you to transfer unpaid orders with the respective dunning level to mediafinanz.

[.instruction]
Transferring orders to mediafinanz with the procedure manager:

. Go to *System » Orders » Procedures*.
. Click on the *New procedure* tab.
. Place a check mark next to the option *Active* to activate the procedure.
. Select a time from the *Execute every day at* drop-down list.
. Enter a *name* for the procedure.
. Click on the *Filter* tab.
. Select the status for unpaid orders.
. Select *Order* as the *order type*.
. Select the dunning level set with the event procedure from the *Dunning level* drop-down list.
. Click on the *Procedure* tab.
. Select *ACTIVE* from the *mediafinanz* drop-down list.
. *Save* the settings.

[#60]
== Displaying transmitted orders

An overview of all orders transmitted to mediafinanz can be displayed in the *Orders » Handover for debt collection* menu in the *Mediafinanz* area.
