= Old online store: PAYONE
:lang: en
include::{includedir}/_header.adoc[]
:keywords: PAYONE, payment method
:description: Payment in plentymarkets: Set up the interface to PAYONE in your plentymarkets system.
:position: 180

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *PAYONE* in Callisto online stores. For further information on using *PAYONE* in Ceres online stores, refer to the detailed information in the plugin description available in the link:https://marketplace.plentymarkets.com/en/plugins/payment/Payone_5434[plentyMarketplace^].
====

PAYONE is a payment provider with a large variety of <<payment/payment-providers/payone#40, payment methods>>. This page contains information on how to set up the interfaces to PAYONE and how to display PAYONE in the online store.

[#10]
== Important notes

This chapter provides you with important information about integrating the payment provider in plentymarkets.

[#20]
=== Payment process with PAYONE

The payment process varies depending on the respective PAYONE payment method and is described in detail for all <<payment/payment-providers/payone#40, available payment methods>>.

[#30]
=== Incoming payments

The incoming payment is booked immediately for credit cards and online bank transfers. The incoming payment is not booked for cash in advance, cash on delivery or invoice until the corresponding status was transmitted with the <<payment/payment-providers/payone#50, transaction status URL>>. The incoming payment will not be booked for cash on delivery or invoice until shipping was confirmed.

[#40]
=== Available PAYONE payment methods

Below you will find an overview of the PAYONE payment methods that are available for plentymarkets. They are displayed along with the corresponding System ID in parentheses.

[.subhead]
Credit / debit cards (3000)

Once the customer has selected one of the following payment methods, they will be prompted to enter their credit card data. This data will be directly sent to PAYONE for pre-validation. The data will not be saved with the seller. If a card participates in 3D-Secure, then the customer will see a corresponding note after having completed the order. The note will inform the customer that they still have to click on a link to verify the card. The customer will be forwarded to a corresponding page after having clicked on the link. Once the process has been confirmed or cancelled, the customer will be returned to the online store.

The following payment methods are available:

* Visa (3010)
* MasterCard (3020)
* American Express (3030)
* Carte Bleue (3040)
* Diners Club (3050)
* Discover (3060)
* JCB (3070)
* Maestro (3080)

[.subhead]
Online bank transfers (3200)

Once the customer has selected one of the following payment methods, they will be prompted to enter their bank transfer data. This bank transfer data will be sent directly to PAYONE for pre-validation. The data will not be saved with the seller. Once the order has been completed, the customer will be forwarded to the corresponding payment provider page. The customer has to follow the steps described. Once the process has been confirmed or cancelled, the customer will be returned to the online store.

The following payment methods are available:

* Sofort Überweisung (3210)
* giropay (3220)
* eps (3230) - only for Austria
* PostFinance E-Finance (3240)
* PostFinance Card (3250)
* iDEAL (3260) - only for the Netherlands

[.subhead]
e-Wallet (3400)

Once the order has been completed, the customer will be forwarded to the payment provider. They will need to log in there and confirm the data. Once the process has been confirmed or cancelled, the customer will be returned to the online store.

The following payment methods are available:

* PayPal (3410)

[.subhead]
Account-based payment methods (3500)

Once the customer has selected the payment method *debit*, they will be prompted to enter their bank data in an entry form. This data will be sent directly to PAYONE. A plausibility check will be carried out. The data will not be saved with the seller. The payment will be triggered once the order has been completed.

The following payment methods are available:

* Debit (3510)
* Invoice (3520)
* Cash in advance (3530)
* Cash on delivery (3540)

[.subhead]
PAYONE: Purchase on invoice (3600)

Once the order has been completed, the order will be sent to the payment provider, e.g. <<payment/payment-providers/klarna#, Klarna>>. As soon as positive feedback is received, the order will be saved. The customer will receive a confirmation message. If an error occurs or the payment request is rejected, the order will not be saved. The customer will receive an error message in the order overview.

The following payment methods are available:

* Klarna payment on invoice (3610)

[.subhead]
PAYONE: Purchase on consumer credit (3700)

When selecting e.g. Klarna account as the payment method, the customer can see the intervals and the instalments directly. Once the order has been completed, the order will be sent. As soon as positive feedback is received, the order will be saved and the customer will receive a confirmation message. If an error occurs or the payment request is rejected, the order will not be saved. The customer will receive an error message in the order overview.

The following payment methods are available:

* Klarna account (3710)

[#50]
== Registering with PAYONE

You need to register with PAYONE before setting it up in plentymarkets. Register with PAYONE and set up an account there. Fill out the link:https://www.payone.de/en/contact/request-a-quote/[form^] on the PAYONE website. You will receive the access data that you need for the configuration in plentymarkets. Then, save the transaction status URL according to the following pattern in the PAYONE back end:

*YOUR_DOMAIN/plenty/api/payone.php*

Change this URL to match your store's domain name and save it in your account in the PAYONE back end area.

[#60]
== Setting up PAYONE for Callisto

Proceed as follows to set up the interface to PAYONE for your Callisto online store in plentymarkets.

[.instruction]
Setting up the interface to PAYONE:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
.  Click on *PAYONE*. +
→ The *Settings* tab will open.
.  Expand the client.
.  Carry out the settings as desired. Pay attention to the information given in <<table-setup-payone-interface>>.
. *Save* the settings.

[[table-setup-payone-interface]]
.setting up the PAYONE interface
[cols="1,3"]
|====
|Setting |Explanation

|*Customer number*
|Enter the *merchant ID* that you received from PAYONE.

|*Payment gateway ID*
|Enter the *gateway ID* that you received from PAYONE.

|*Sub account ID*
|Enter the sub account ID that is found in the *ACCOUNTS* area on PAYONE.

|*Key*
|Enter the *key* that you received from PAYONE.

|*Active test mode*
|Select *Yes* to activate the test mode. Select *No* to deactivate the test mode. The interface is in live mode.

|*Shopware PAYONE authorization*
|Activate if you want to use PAYONE for link:https://docs.google.com/document/d/10mPeV3xqx4We71dYQdPmJK2qvb21Rpym6FG_tKwHKfc/edit#heading=h.h38ew7hip4tl[Shopware^] (German link). For further information, refer to <<payment/payment-providers/payone#140, Using PAYONE for Shopware>>.
|====

[#70]
=== Setting up the address validation

Set up an address validation if needed. During address validation, any errors entered into the address fields will be recognised and corrected automatically if this option has been selected. Furthermore, the address validation ensures additional security regarding the customer's identity.

[.instruction]
Setting up the address validation:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
.  Click on *PAYONE*. +
→ The *Settings* tab will open.
.  Expand the *Address validation* area.
.  Carry out the settings as desired. Pay attention to the information given in <<table-setup-address-validation-payone>>.
. *Save* the settings.

[[table-setup-address-validation-payone]]
.setting up the address validation
[cols="1,3"]
|====
|Setting |Explanation

|*Active*
|Select *Yes* to activate the address validation.

|*Active test mode*
|Select *Yes* to activate the test mode. Select *No* to deactivate the test mode. The address validation is in live mode.

|*Invoice address; +
Delivery address*
|Select the address validation type. +
*Basic* = Address will be checked. +
*do not check* = The address will not be checked. +
*Person (only possible in Germany)* = In addition to the address, the name will also be checked.

|*Automatic correction*
|Activate automatic correction. +
*Yes* = Errors will be corrected automatically during address entry. +
*No* = Errors will not be corrected automatically during address entry. +
*User decision* = The user decides if a suggested correction is accepted or not.

|*Error characteristics*
|Select whether the check should be cancelled or continued if an error occurs.

|*Minimum value of items*
|Enter a minimum value from which the address validation should be carried out. This entry is optional.

|*Maximum value of items*
|Enter a maximum value up to which the address validation should be carried out. This entry is optional.

|*Validity*
|Enter a numerical value in days for which the check should be valid. Customers who are making several orders in this time period will not be checked after the second time.

|*Person status mapping*
|Assign the desired traffic light values to the options. +
*GREEN* = Immaculate credit ranking, lowest risk for payment failures. +
*YELLOW* = Tolerant but increases the risk +
*RED* = Highest risk, as the highest payment failures are to be expected.
|====

[#80]
=== Setting up the credit rating

Set up a credit rating if needed. Use the credit ranking e.g. to make only certain payment methods available to customers. In the case of a negative credit ranking, you could prohibit payment on invoice, you could stop the order or determine a maximum order value that may not be exceeded.

[.instruction]
Setting up the credit rating:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
.  Click on *PAYONE*. +
→ The *Settings* tab will open.
.  Expand the *Credit rating* area.
.  Carry out the settings as desired. Pay attention to the information given in <<table-setup-credit-rating-payone>>.
. *Save* the settings.

[[table-setup-credit-rating-payone]]
.setting up the credit rating
[cols="1,3"]
|====
|Setting |Explanation

|*Active*
|Select *Yes* to activate the credit rating.

|*Active test mode*
|Select *Yes* to activate the test mode. Select *No* to deactivate the test mode. The credit rating is in live mode.

|*Validation type*
|Select validation criteria. +
*Infoscore (hard criteria)* = Checks only for proven payment problems, e.g. foreclosure etc. +
*Infoscore (all properties)* = All credit rating criteria is checked, e.g. orders for payments. +
*Infoscore (all properties + Boni Score)* = All credit rating criteria is checked, e.g. orders for payments. In addition, a score value is used for checking. The score value (between 100 and 990) is calculated based on different customer characteristics, e.g. occupation and place of residence.

|*Default value for new customers*
|Select a traffic light value for the credit rating which is used as a default value for new customers. +
*GREEN* = Immaculate credit ranking, lowest risk for payment failures. +
*YELLOW* = Tolerant but increases the risk +
*RED* = Highest risk, as the highest payment failures are to be expected.

|*Validity*
|Enter a numerical value in days for which the check should be valid. Customers who are making several orders in this time period will not be checked after the second time.

|*Minimum value of items*
|Enter a minimum value from which the credit rating should be carried out. This entry is optional.

|*Maximum value of items*
|Enter a maximum value up to which the address validation should be carried out. This entry is optional.

|*Error characteristics*
|Select whether the check should be cancelled or continued if an error occurs.

|*A/B testing*
|Activate and enter a value to check the credit rating on a random basis. For example, enter a 3 if only every third process is to be checked.
|====

[#90]
=== Setting up interfaces for PAYONE payment methods

There are further options for the interfaces of the different PAYONE payment methods. The most important options are described below.

[.instruction]
Setting up interfaces for PAYONE payment methods:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
.  Open the folder *PAYONE*.
. Click on the folder of the payment method. +
→ The *Interface* tab will open.
.  Expand the client.
.  Carry out the settings as desired. Pay attention to the information given in <<table-options-payone-payment-methods>>.
. *Save* the settings.

[[table-options-payone-payment-methods]]
.further interface options for PAYONE payment methods
[cols="1,3"]
|====
|Setting |Explanation

|*Use global settings*
|Use the global settings of the interface. +
*YES* = Apply the settings of the main interface (<<table-setup-payone-interface>>). These options will then be hidden in the interface. +
*NO* = Create a separate account with its own access data.

|*Permitted traffic light colour*
|The strictest regulations and the lowest risk for payment failures apply for *green*. *Yellow* indicates a higher risk of payment failures. *Red*indicates the highest risk, as the highest payment failures are to be expected.

|*Klarna settings*
|Enter values as received from Klarna, e.g. the country specific *Klarna shop ID*, the *Klarna campaign code* or the *Klarna campaign name*.
|====

[#100]
=== Setting up SEPA for debit

If you want to offer the payment method *Debit* in the folder *account-based payment method* with PAYONE, then you also have to set up SEPA. To do this, proceed as described below.

[.instruction]
Setting up SEPA (debit):

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
.  Open the folder *PAYONE*.
. Click on the folder *account-based payment method*. +
→ The *Interface* tab will open.
.  Expand the client.
.  Carry out the settings as desired. Pay attention to the information given in <<table-setup-sepa-payone>>.
. *Save* the settings.

[[table-setup-sepa-payone]]
.setting up SEPA (debit)
[cols="1,3"]
|====
|Setting |Explanation

|*show additional account number / sort code*
|Select *YES* so that customers can enter their account number and sort code along with the SEPA data, IBAN and BIC.

|*Grant of a mandate*
|Select *YES* to create a mandate. This mandate will be displayed to the customer and must be accepted. +
Granting a mandate is subject to costs. It is not possible to request the POS block list along with this.

|*Download mandate as PDF*
|Select *YES* so that customers can download the mandate as a PDF document in the *My account area* of the online store. +
You can only select this option if you booked the product *SEPA-Mandate als PDF* (SEPA mandates as PDF) from PAYONE.
|====

[#110]
== Activating payment methods

For PAYONE, a large variety of payment methods is available. Go to <<payment/managing-payment-methods#20, System » Orders » Payment » Payment methods>> to activate the payment methods.

[#115]
== Displaying PAYONE in the Callisto online store

In the *CMS* menu, you can customise the text that is displayed during the order process when customers select the payment method PAYONE. In addition, you will find out where to customise the design by modifying the CSS. You can customise the forms for credit card data and online bank transfers. For further information, refer to the <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design-order-process-checkout, Checkout>> page.

[.instruction]
Customising the online forms:

. Go to *CMS » Web design*.
. Open the folder *Order process » Checkout*.
. Expand a *PAYONE payment method*.
. Enter a text into the *Text in front of* or *Text behind* field.
. *Save* the settings.

You can also customise the order confirmation form. For further information, refer to the <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design-order-process-order-confirmation, Order confirmation>> page.

[.instruction]
Customising the order confirmation:

. Go to *CMS » Web design*.
. Open the folder *Order process » Order confirmation*.
. Expand a *PAYONE payment method*.
. Enter a text into the *Text in front of* or *Text behind* field.
. *Save* the settings.

You can find the CSS for the PAYONE payment methods in the *CMS » Web design » Layout » CSS » CSSOrder* menu.

[#120]
==  Automatically sending shipping confirmations

Set up an <<basics/automation/event-procedures#, event procedure>> to automatically send shipping confirmations to PAYONE when the outgoing items are booked.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter name.
.  Select the *event* listed in table 6.
. *Save* the settings.
.  Pay attention to the explanations given in table 6 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for sending automatic shipping confirmations to PAYONE
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Outgoing items booked*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Payment method*
|*PAYONE payment method*

|*Procedure*
|*Shipping &gt; Send shipping confirmation to PAYONE*
|
|====

[#130]
== Automatically sending refunds

To send refunds automatically, an <<orders/managing-orders#1200, order status>> for credit notes is required. You can use one of the standard statuses or set up your own order status. This status is then only assigned to completed credit notes. These credit notes must not be changed after creation.

[IMPORTANT]
.Condition for refunds
====
In order to send PAYONE refunds from credit notes, a shipping confirmation must have already been sent to PAYONE.
====

Set up an <<basics/automation/event-procedures#, event procedure>> to automatically send refunds to PAYONE.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter a name.
.  Select the *event* listed in table 7.
. *Save* the settings.
.  Pay attention to the explanations given in table 7 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for sending automatic refunds to PAYONE
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Status change*
| Select a status for the *Refund to PAYONE*.

|*Filter 1*
|*Order &gt; Order type*
|*Credit note*

|*Filter 2*
|*Order &gt; Payment method*
|*PAYONE payment method*

|*Procedure*
|*Payment methods &gt; Send credit note to PAYONE*
|
|====

[#140]
== Using PAYONE for Shopware

If you want to use PAYONE with Shopware, save the <<payment/payment-providers/payone#50, transaction status URL>> in the Shopware plugin. Save the URL to the Shopware system in the back end of PAYONE.

[WARNING]
.PAYONE cannot be used simultaneously
====
If you want to use PAYONE with Shopware, then you cannot simultaneously use it in the plentymarkets online store.
====

The interaction with link:http://github.com/plentymarkets/plentymarkets-shopware-connector[Shopware] works as follows:

* The order is created in Shopware.
* The order will be transmitted from Shopware to plentymarkets.
* The payment will be imported once the order has been marked as paid in Shopware.
* The order will be processed within the *Orders* menu in plentymarkets. The processing steps carried out here are preparation for shipping, actual shipping etc. +
→ For this, you will need to set up the event procedure for <<payment/payment-providers/payone#120, shipping confirmations>>.
* If needed, a credit note can be created in the plentymarkets system. +
→ For this, you will need to set up the event procedure for <<payment/payment-providers/payone#130, refunds>>.
