= Old online store: POSTPAY
:lang: en
include::{includedir}/_header.adoc[]
:keywords: POSTPAY, payment method
:description: Payment in plentymarkets: Set up the interface to POSTPAY in your plentymarkets system.
:position: 190

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *POSTPAY* in Callisto online stores. The following instructions are not valid for Ceres online stores!
====

link:http://www.postpay.de/de/p/postpay/postpay.html[POSTPAY^] (only available in German) is a payment service offered by Deutsche Post. This service provider allows you to offer your customers a payment and order process that is already used by many Deutsche Post customers. POSTPAY offers the payment methods *Direct debit*, *Cash in advance*, *Giropay*, *Sofortbanking*, *Credit card* and *Purchase on invoice*.

[#10]
== Important notes

This chapter provides you with important information about integrating the payment provider in plentymarkets.

[IMPORTANT]
.Order generation
====
An order is not generated in plentymarkets until the incoming payment is received. In other words, the order is not yet created during the order process when the customer clicks on the *POSTPAY* button in the shopping cart.
====

[.subhead]
Payment process

After confirming the order, the customer will be redirected to the POSTPAY website. The customer logs into their POSTPAY account, selects a payment option and confirms the payment. The customer may have to enter their invoice and delivery address on POSTPAY. It depends on whether the customer has already gone through the checkout process in your online store and selected POSTPAY as the payment method or whether the customer clicked on the POSTPAY button in the shopping cart without logging in.

Here is an overview of both variations:

* The customer logged into your online store and has already entered the invoice and delivery address. This data will automatically be entered when the customer is forwarded to POSTPAY. However, the customer can still change this data if desired.
* The customer has not logged into your online store and clicks on the POSTPAY button in the shopping cart. The customer is forwarded to POSTPAY where they can log in using the POSTPAY data. The primary payment method and the address are already saved there. The purchase can be completed with only one click. If the customer does not already have a POSTPAY account, they have to enter the invoice and delivery addresses here.

[#20]
== Registering with POSTPAY

If you already have an link:https://de.allyouneed.com/de/customerlogin.html[Allyouneed.com^] seller contract, you do not need to register again. You can directly begin to <<payment/payment-providers/postpay#30, set up POSTPAY>>.

If you do not have a contract yet, register with link:https://de.allyouneed.com/de/dealer/page/selfsignup/step1?ssu=postpay[POSTPAY^] (German only). Afterwards you will receive the Allyouneed.com &amp; POSTPAY seller contract by post or by email. Sign the contract and send it back. Add information about the beneficial owner and the legal representative. Your account will be activated once it was checked by POSTPAY. You will receive an email confirmation that includes your access data. You need the access data to set up the interface in plentymarkets.

[#30]
== Setting up POSTPAY for Callisto

Proceed as described below to set up the interface to POSTPAY for your Callisto online store in plentymarkets.

[.instruction]
Setting up the POSTPAY interface:

. Go to *System » System settings » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *DE*.
.  Click on *POSTPAY*. +
→ The *Settings* tab will open.
. Click on the *Interface* tab.
.  Expand the client.
.  Carry out the settings as desired. Pay attention to the information given in <<table-setup-postpay-interface>>.
. *Save* the settings.

[[table-setup-postpay-interface]]
.setting up the POSTPAY interface
[cols="1,3"]
|====
|Setting |Explanation

|*User name*
|Enter the user name that you received from POSTPAY.

|*Password*
|Enter the password that you received from POSTPAY.

|*Activate test mode*
|Activate the test mode and check the POSTPAY functions before working live with the system.

|*Activate access data for all clients (stores)*
|Only visible if clients (stores) were set up. Activate to apply the account settings saved for the main store by clicking on *Add account* for all clients (shops). This setting is dominant over the settings saved for each client. Deactivate to use separate access data for your clients (stores). Online stores that do not have account settings saved for them cannot be used with POSTPAY. +
Go to <<omni-channel/online-store/setting-up-clients/online-store#, System » System settings » Client » Select client » Online store » Settings>> and make sure that you have selected the option *Enable login for every store* in the line *Login*. This makes it possible to support several clients.
|====

[#40]
== Activating the payment method

Set up and activate the POSTPAY <<payment/managing-payment-methods#20, payment method>> in the *Settings* tab of the payment method. In addition, check the settings for *Permitted payment methods* in the <<payment/managing-payment-methods#30, customer classes>> and for *Blocked payment methods* in the <<fulfilment/preparing-the-shipment#1000, shipping profiles>>.

[#50]
== Saving a URL for the push service

Log into POSTPAY with your access data and enter the *URL for the push service* in the tab *Verwaltung* (administration). This URL tells POSTPAY where payment confirmations should be sent to. The URL is structured as follows:

*YOUR_DOMAIN/plenty/api/payment_notification.php?payment=postpay&amp;*

Change this URL so that it matches your store's domain. Save the URL on *POSTPAY*.

[#60]
== Manually creating a credit note for a POSTPAY order

It may be necessary to create credit notes for individual orders that are processed with POSTPAY. You can send individual credit note amounts to POSTPAY.

[.instruction]
Sending a credit note to POSTPAY:

. Go to *Orders » Edit orders*.
. Open the POSTPAY order.  +
→ The *Overview* tab will open.
. Select the option *create* from the *Credit note...* drop-down list. +
→ The credit note will be created.
. Open the newly created credit note.
. Click on the *Settings* tab.
. Enter the amount into the *Send POSTPAY credit note* field.
. Click on *Send POSTPAY credit note*. +
→ The credit note will be sent to POSTPAY.

[#70]
== Automatically sending shipping confirmations

Set up an <<automation/event-procedures#, event procedure>> to automatically send shipping confirmations when the outgoing items are booked.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » System settings » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter a name.
.  Select the *event* listed in table 2.
. *Save* the settings.
.  Pay attention to the explanations given in table 2 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for sending automatic shipping confirmations to POSTPAY
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Outgoing items booked*
|

|*Filter 1*
|*Order &gt; Payment method*
|*POSTPAY*

|*Filter 2*
|*Order &gt; Order type*
|*Order*

|*Procedure*
|*Shipping &gt; Send shipping confirmation to POSTPAY*
|
|====

[#80]
== Automatically sending returns

Set up an <<automation/event-procedures#, event procedure>> to automatically send returns to POSTPAY. For further information about creating returns, refer to the <<orders/managing-orders#400, Return>> page of the manual.

[.collapseBox]
.Setting up an event procedure
--
. Go to *System » System settings » Orders » Events*.
. Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
. Enter a name.
. Select the *event* listed in table 3.
. *Save* the settings.
. Pay attention to the explanations given in table 3 and carry out the settings as desired.
. Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for automatically sending returns to POSTPAY
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order generation: New return (by customer)*
|

|*Filter 1*
|*Order &gt; Order type*
|*Return*

|*Filter 2*
|*Order &gt; Payment method*
|*POSTPAY*

|*Procedure*
|*Return &gt; Send return to POSTPAY*
|
|====

[#90]
== Automatically sending credit notes

To send credit notes automatically, an <<orders/managing-orders#1200, order status>> for credit notes is required. You can use one of the standard statuses or set up your own order status. This status is then only assigned to completed credit notes. These credit notes must not be changed after creation. Set up an <<automation/event-procedures#, event procedure>> to automatically send credit notes to POSTPAY.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » System settings » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter a name.
.  Select the *event* listed in table 4.
. *Save* the settings.
.  Pay attention to the explanations given in table 4 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for automatically sending credit notes to POSTPAY
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Status change*
| Select the status for the *credit note to POSTPAY*.

|*Filter 1*
|*Order &gt; Order type*
|*Credit note*

|*Filter 2*
|*Order &gt; Payment method*
|*POSTPAY*

|*Procedure*
|*Payment methods &gt; Send credit note to POSTPAY*
|
|====

[#100]
== Automatically sending cancellations

Set up an <<automation/event-procedures#, event procedure>> to automatically inform POSTPAY of cancellations.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » System settings » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter a name.
.  Select the *event* listed in table 5.
. *Save* the settings.
.  Pay attention to the explanations given in table 5 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for automatically sending cancellations to POSTPAY
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Status change*
| Select status for *cancelled orders*.

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Payment method*
|*POSTPAY*

|*Procedure*
|*Payment methods &gt; Send cancellation to POSTPAY*
|
|====
