= Old online store: Sage Pay
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Sage Pay, payment method
:description: Payment in plentymarkets: Set up the interface to Sage Pay in your plentymarkets system.
:position: 210
:url: payment/payment-providers/sage-pay
:id: 30W7BE5

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *Sage Pay* in Callisto online stores. The following instructions are not valid for Ceres online stores!
====

link:http://www.sagepay.co.uk/[Sage Pay^] is a payment provider that was founded in Great Britain and is available in the United Kingdom and in Ireland. Sage Pay offers various payment options, an integrated fraud prevention tool and e.g. transaction reports.

[#10]
== Important notes

This chapter provides you with important information about integrating Sage Pay in plentymarkets.

[#20]
=== Payment process

After confirming the order, the customer will be redirected to the Sage Pay website. Here, they needs to enter the data of the selected credit card. Once the customer has entered the data and confirmed the payment, they is directed back to your online store.

[#30]
=== Available Sage Pay payment methods

Below you will find an overview of the Sage Pay payment methods that are available for plentymarkets. They are displayed along with the corresponding System ID in parentheses.

* Sage Pay (Payment)
* Sage Pay deferred
* Sage Pay authenticate

If you use the first payment method, then the amount will be transferred to you directly. If you use the payment methods *deferred* and *authenticate*, then the amount will be transferred to you after you have requested payment. For further information about these payment methods, refer to link:http://www.sagepay.co.uk/support/15/36/transaction-types[Sage Pay^].

[#40]
== Registering with Sage Pay

You need to register with Sage Pay before setting it up in plentymarkets. link:http://www.sagepay.co.uk/contact[Contact^] Sage Pay in order to register. Once you have registered you will receive access data from Sage Pay. You need this access data for the setup in plentymarkets. After registering, access your Sage Pay account and enter the IP address of the server that your store runs on. Save this entry in the Sage Pay back end under *Settings » Valid IPs*.

[#50]
== Setting up Sage Pay for Callisto

Proceed as described below to set up the interface to Sage Pay for your Callisto online store in plentymarkets.

[.instruction]
Setting up the Sage Pay interface:

. Go to *Setup » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
.  Click on *Sage Pay*. +
→ The *Interface* tab will open.
.  Expand the client.
.  Carry out the settings as desired. Pay attention to the information given in <<table-setup-sage-pay-interface>>.
. *Save* the settings.

[[table-setup-sage-pay-interface]]
.setting up the Sage Pay interface
[cols="1,3"]
|====
|Setting |Explanation

|*Vendor*
|Enter the vendor name that you received from Sage Pay.

|*Activate iframe*
|Activate iframe so that customers will not be forwarded to Sage Pay. Instead, they will be able to enter their credit card details directly in your online store. +
Deactivate iframe so that your customers will be forwarded to Sage Pay. They will have to select their credit card and enter their information on the Sage Pay website. +
*_Important_*: Please note that the activated iframe option is not compatible with local European payment methods.

|*Activate test mode*
|Activate the test mode and check the Sage Pay functions before working live with the system.

2+|Client (store) options

|*Activate access data for all clients (stores)*
|Only visible if clients (stores) were set up. Activate to apply the account settings saved for the main store by clicking on *Add account* for all clients (shops). This setting is dominant over the settings saved for each client. Deactivate to use separate access data for your clients (stores). Online stores that do not have account settings saved for them cannot be used with Sage Pay. +
Go to <<omni-channel/online-store/setting-up-clients/online-store#, Setup » Client » Select client » Online store » Settings>> and make sure that you have selected the option *Enable login for every store* in the line *Login*. This makes it possible to support several clients.
|====

[#60]
== Activating the payment method

Set up and activate the <<payment/managing-payment-methods#20, payment methods>> Sage Pay, Sage Pay deferred and Sage Pay authenticate in the *Settings* tab of the payment methods. In addition, check the settings for *Permitted payment methods* in the <<payment/managing-payment-methods#30, customer classes>> and for *Blocked payment methods* in the <<fulfilment/preparing-the-shipment#1000, shipping profiles>>.

[#70]
== Authorising or cancelling payments

Orders that are paid for with Sage Pay are authorised or cancelled differently in plentymarkets depending on which Sage Pay payment method was used and how far the payment has progressed.

[TIP]
.Event procedure for cancellations
====
When the status changes to *cancelled*, the cancellation will automatically be reported to Sage Pay with the help of the *event procedure*. In this case, you do not have to click on *cancel* in the *Settings* tab.
====

[#80]
=== Cancelling a Sage Pay Payment

If an order was paid for with *Sage Pay Payment*, then the payment was automatically booked. Proceed as follows to cancel the payment.

[IMPORTANT]
.Same-day cancellation only
====
When using this payment method, it is only possible to cancel payment in plentymarkets on the same day that the order was received. It may be possible to cancel the payment later in your Sage Pay account.
====

[.instruction]
Cancelling a Sage Pay Payment:

. Go to *Orders » Edit orders*.
. Open the order that you want to cancel. +
→ The *Overview* will open.
. Click on the *Settings* tab.
. Click on *Cancel booked SagePay payment*.
. Change the order's *status* to *cancelled*.

With the help of an event procedure you send the <<payment/payment-providers/sage-pay#110, cancellation>> to Sage Pay.

[#90]
=== Cancelling a Sage Pay deferred or authenticate payment

Proceed as follows to cancel a payment that was not yet authorised or released.

[.instruction]
Cancelling a payment:

. Go to *Orders » Edit orders*.
. Open the order that contains a payment that you want to cancel. +
→ The *Overview* tab will open.
. Click on the *Settings* tab.
. Click on *Cancel SagePay payment*. +
→ The payment will be cancelled.

With the help of an event procedure you send the <<payment/payment-providers/sage-pay#110, cancellation>> to Sage Pay.

[#100]
=== Authorising a Sage Pay deferred or authenticate payment

Carry out the following steps to receive payment for an order that was paid for with Sage Pay deferred or authenticate.

[.instruction]
Authorising a payment:

. Go to *Orders » Edit orders*.
. Open the order that contains a payment that you want to authorise. +
→ The *Overview* tab will open.
. Click on the *Settings* tab.
. Click on *Authorise/release SagePay payment*. +
→ The payment will be released or authorised.

[IMPORTANT]
.Cancelling authorised or released payments
====
Once a payment was authorised or released, it can only be cancelled on the same day. Once an order was authorised/released, the option *Cancel booked SagePay payment* will appear in the order's *Settings*. Click the option to cancel the payment. +
Then change the order status to *cancelled* manually.
====

[#110]
==  Automatically sending cancellations

Set up an <<automation/event-procedures#, event procedure>> to automatically inform Sage Pay of cancellations.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *Setup » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter a name.
.  Select the *event* listed in table 2.
. *Save* the settings.
.  Pay attention to the explanations given in table 2 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for automatically sending cancellations to Sage Pay
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Status change*
| Select status for *cancelled orders*.

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Payment method*
|*Sage Pay*

|*Procedure 1*
|*Payment methods &gt; Send cancellation to Sage Pay (all)*
|

|*Procedure 2*
|*Payment methods &gt; Send cancellation to Sage Pay (authenticate)*
|

|*Procedure 3*
|*Payment methods &gt; Send cancellation to Sage Pay (deferred)*
|
|====

[TIP]
.One event procedure per payment method
====
Create an individual event procedure for each payment method. Otherwise unintended messages could be triggered. If you select multiple payment methods in the *Filter* tab, then the message that was triggered will also be sent to the other payment providers that were selected. Furthermore, always select 2 procedures for *deferred* and *authenticate*.
====

[#120]
== Automatically sending credit notes

If you already received a payment and you want to refund a customer, set up an <<automation/event-procedures#, event procedure>> to automatically send credit notes to Sage Pay.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *Setup » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter a name.
.  Select the *event* listed in table 3.
. *Save* the settings.
.  Pay attention to the explanations given in table 3 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for automatically sending credit notes to Sage Pay
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order generation: New credit note*
|

|*Filter*
|*Order &gt; Payment method*
|*Sage Pay*

|*Procedure*
|*Payment methods &gt; Send credit note to Sage Pay*
|
|====
