= Old online store: Santander Consumer Bank
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Santander Consumer Bank, payment method
:description: Payment in plentymarkets: Set up the interface to Santander Consumer Bank in your plentymarkets system.
:position: 220

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *Santander Consumer Bank* in Callisto online stores. The following instructions are not valid for Ceres online stores!
====

After the AKB Privat- und Handelsbank merged with the CC-Bank in Germany, the company began operating under the new name Santander Consumer Bank AG in 2006. The bank focuses on the areas of consumer finance, retail banking and online banking. Santander also specialises in instalment financing. Santander integrates several payment methods in your online store - via one interface only.

[#10]
== Important notes

This chapter provides you with important information about integrating the payment provider in plentymarkets.

[.subhead]
Payment process

Once the order has been placed, the customer will receive a message asking them to click on a link and finalise the payment. The customer will be forwarded to a page on the Santander Consumer Bank website after having clicked on the link. The customer has to enter the necessary data for the loan request. Once the customer has entered and confirmed the data, they will be forwarded to the order confirmation page.

[#20]
== Registering with Santander Consumer Bank

You need to register with Santander using the link:https://www.santander.de/de/waren/wir_und_der_handel/zusammenarbeit/Kontaktformular_Partnerschaft_Warenhaendler.html[Contact form^] (German only) before you can set up the payment method in plentymarkets. You will then receive the necessary information as well as the access data that you need for setting up the interface in plentymarkets. For further information refer the Santander link:http://santander.de/de/waren/wir_und_der_handel/zusammenarbeit/zusammenarbeit.html[Cooperation^] page (German only).

[#30]
== Setting up Santander for Callisto

Proceed as described below to set up the interface to Santander Consumer Bank for your Callisto online store in plentymarkets.

[.instruction]
Setting up the Santander interface:

. Go to *System » System settings » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *DE*.
.  Click on *Santander Consumer Bank*. +
→ The *Settings* tab will open.
. Click on the *Interface* tab.
.  Expand the client.
.  Carry out the settings as desired. Pay attention to the information given in <<table-setup-santander-interface>>.
. *Save* the settings.

[[table-setup-santander-interface]]
.setting up the Santander interface
[cols="1,3"]
|====
|Setting |Explanation

|*Seller number*
|Enter the Seller number of your Santander account.

|*Seller password*
|Enter the Seller password of your Santander account.

|*Minimum amount*
|Enter the minimum amount for orders. The minimum order value must be reached in order for customers to use this payment method.

|*Maximum amount*
|Enter the maximum amount for orders. The maximum order value must not be exceeded in order for customers to use this payment method.

2+|Client (store) options

|*Activate access data for all clients (stores)*
|Only visible if clients (stores) were set up. Activate to apply the account settings saved for the main store by clicking on *Add account* for all clients (shops). This setting is dominant over the settings saved for each client. Deactivate to use separate access data for your clients (stores). Online stores that do not have account settings saved for them cannot be used with Santander. +
Go to <<omni-channel/online-store/setting-up-clients/online-store#, System » System settings » Client » Select client » Online store » Settings>> and make sure that you have selected the option *Enable login for every store* in the line *Login*. This makes it possible to support several clients.
|====

[#40]
== Activating the payment method

Set up and activate the Santander Consumer Bank <<payment/managing-payment-methods#20, payment method>> in the *Settings* tab of the payment method. In addition, check the settings for *Permitted payment methods* in the <<payment/managing-payment-methods#30, customer classes>> and for *Blocked payment methods* in the <<fulfilment/preparing-the-shipment#1000, shipping profiles>>.

[#50]
== Displaying Santander in the Callisto online store

In the *CMS* menu, you can customise the text that is displayed during the order process when customers select the payment method Santander Consumer Bank. You can also customise the order confirmation form. For further information, refer to the <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design-order-process-order-confirmation, Order confirmation>> page.

[.instruction]
Customising the order confirmation:

. Go to *CMS » Web design*.
. Open the folder *Order process » Order confirmation*.
. Expand *Santander Consumer Bank*.
. Enter a text into the *Text in front of* or *Text behind* field.
. Enter an *error text*. +
→ This text will be displayed to the customer if cash payments cannot be made with the payment method or if an error occurred during transmission.
. Enter customer relevant information, such as e.g. Click here to finish the payment process, in the *link content*. +
→ This text will be displayed to the customers during checkout.
. *Save* the settings.

[#60]
== Viewing the API log

In the case that an error occurs during data transmission, you will find details about the error in the API Log.

[.instruction]
Viewing the API log:

.  Go to *Data » API log » Tab: API log*.
.  Select a format from the drop-down list *Process*.
.  Select a *Date* if you only want to see entries for a specific day.
.  Click on *Search* to carry out the search. +
→ The processes will be displayed.

Depending on the type of error, the payment may be booked in Santander but may not be verified in plentymarkets. This will cause an erroneous booking in plentymarkets.
