= Old online store: Skrill
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Skrill, payment method
:description: Payment in plentymarkets: Set up the interface to Skrill in your plentymarkets system.
:position: 230
:url: payment/payment-providers/skrill

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *Skrill* in Callisto online stores. For further information on using *Skrill* in Ceres online stores, refer to the detailed information in the plugin description available in the link:https://marketplace.plentymarkets.com/en/plugins/payment/Skrill_5142[plentyMarketplace^].
====

The payment provider link:https://www.skrill.com/en/[Skrill^] brings together a large number of <<payment/payment-providers/skrill#40, payment methods>> that are specific to particular countries.

[#10]
== Important notes

This chapter provides you with important information about integrating the payment provider in plentymarkets.

[#20]
=== Payment process

The payment method is selected in the online store. Afterwards, the customer is forwarded directly to Skrill. The additional content is made available in an iframe. The customer enters their data here. In other words, the data is not entered in the online store, but rather in Skrill. Once the customer has entered and confirmed the data, they will be forwarded to the order confirmation page.

[#30]
=== SSL certificate

You need to have an <<basics/admin-tasks/plentymarkets-account#ssl-certificate, SSL certificate>> in order to correctly use the payment method. The Skrill payment page is already secured with SSL.

[WARNING]
.Ask your bank
====
Ask your bank whether it can process payments with iframe before you integrate this payment method.
====

[#40]
=== Available Skrill payment methods

Below you will find an overview of the Skrill payment methods that are available for plentymarkets. They are displayed along with the corresponding System ID in parentheses.

* Carte Bleue (510)
* Digital Wallet (560)
* Giropay (530)
* iDEAL (580)
* Credit card (500)
* Debit (520)
* maestro (570)
* netpay eps (550)
* Sofortbanking (540)
* Online bank transfer (590)
* CartaSi (591)
* PostePay (592)
* Visa Delta/Debit (593)
* Dankort (595)
* Payolution Invoice (596)
* Payolution Ins (597)
* Payolution Mangirkart (598)

[#50]
==  Registering with Skrill

Open a link:https://content.skrill.com/en/ecommerce-solutions/plentymarkets/[seller account^] on Skrill first. For business registration, click the *Sign up now* button. Follow the next steps to complete the registration process. In one of these steps, you will be asked to enter a *secret word* that is used to encrypt payments. You need this secret word to set up the access data in plentymarkets. This secret word should be different from your login password and may contain no more than 10 characters. The secret word may only consist of lower-case letters and numbers. It may not contain special characters.

Familiarise yourself with the *history* section in your Skrill account as well. Later, you will be able to download your transaction history as an Excel table here and process it as needed.

[#60]
==  Setting up Skrill for Callisto

Skrill uses a two-stage security concept for activating accounts. Stage 1 is the verification of your email address. Stage 2 is the verification of your personal data. Proceed as described below to set up the interface to Skrill for your Callisto online store in plentymarkets.

[.instruction]
Setting up the Skrill interface:

. Go to *System » System settings » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
.  Click on *Skrill*. +
→ The *Interface* tab will open.
.  Enter the email address that you received from Skrill.
.  Enter the secret word that you received from Skrill.
. *Save* the settings.

[#70]
==  Activating payment methods

Set up and activate the Skrill <<payment/managing-payment-methods#20, payment methods>> in the *Settings* tab of the payment methods. In addition, check the settings for *Permitted payment methods* in the <<payment/managing-payment-methods#30, customer classes>> and for *Blocked payment methods* in the <<fulfilment/preparing-the-shipment#1000, shipping profiles>>.

[IMPORTANT]
.Changing the payment method after an order was placed
====
It is not possible for a customer to change the *payment method* within the *my account* area of the online store after they have placed an order and before they have received a confirmation of payment. A corresponding note is displayed in the *my account* area. If the payment was denied, the payment method can be changed.
====
