= Old online store: SOFORT Überweisung
:lang: en
include::{includedir}/_header.adoc[]
:keywords: sofortueberweisung, payment methods, sofortüberweisung, sofort ueberweisung
:description: Payment in plentymarkets: Set up the interface to SOFORT Überweisung in your plentymarkets system.
:position: 240

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *SOFORT Überweisung* in Callisto online stores. For further information on using *Sofort Überweisung* in Ceres online stores, refer to the detailed information in the plugin description available in the link:https://marketplace.plentymarkets.com/en/plugins/payment/SOFORT_5050[plentyMarketplace^].
====

link:https://www.sofort.com/eng-DE/kaeufer/su/online-zahlen-mit-sofort-ueberweisung/[*SOFORT Überweisung^] is the direct payment method of SOFORT GmbH. When using this payment method, the customer initiates the transfer directly from their online bank account when placing their order. A successful transfer is instantly confirmed to you as the seller. This allows you to instantly deliver stocked items and digital services - and allows the customer to receive their order even faster. Directly after the payment has been received, the order will be marked as paid in plentymarkets.

SOFORT Überweisung complies with the high security standards for online banking and offers TÜV-certified data security. Your customers neither have to register nor do they need a credit card. They can pay easily, quickly and securely from their online bank account.

[#10]
== Important notes

Once the order has been completed, the customer will see a form that includes a button. After clicking on this button, the customer will be forwarded to a page on the SOFORT Überweisung website where they can enter the necessary information. The customer will return to the online store after having entered and confirmed the data or cancelled the payment process.

In the status history of orders that have been paid with the payment method SOFORT Überweisung, a payment confirmation is saved and the orders are cleared for shipping.  The bank transfer has been executed by the customer, but the payment has not been transferred to your bank account yet. The payment confirmation entry is also saved in the payment history. If you already set up <<order-processing/payment/managing-bank-details#70, EBICS>> in your system, the order will be marked as paid automatically after payment import. A second entry will be created in the payment history section of the order. If you do not use EBICS, you have to <<order-processing/payment/managing-payments#40, book the payment manually>>.

[#20]
== Registering with SOFORT Überweisung

You need to register with link:https://www.sofortueberweisung.de/payment/createNew/go[SOFORT Überweisung^] before you can set up the payment method in plentymarkets. Once you have registered, you will receive the access data that you need to save in plentymarkets.

[#30]
== Setting up SOFORT Überweisung for Callisto

When setting up the interface to SOFORT Überweisung for your Callisto online store in plentymarkets, you can either link an existing project on SOFORT Überweisung with plentymarkets or create a new project.

[#40]
=== Linking an existing project

If you already have created a project on SOFORT Überweisung, set up the interface to SOFORT Überweisung in plentymarkets and carry out the settings in the admin area of SOFORT Überweisung. Incoming payments will then be transferred successfully from SOFORT Überweisung to plentymarkets.

[.instruction]
Setting up the SOFORT Überweisung interface:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
. Click on *Sofortüberweisung.de*.  +
→ The *Settings* tab will open.
. Click on the *Interface* tab.
.  Carry out the settings as desired. Pay attention to the information given in <<table-setup-sofort-interface>>.
. *Save* the settings.

[[table-setup-sofort-interface]]
.setting up the SOFORT Überweisung interface
[cols="1,3"]
|====
|Setting |Explanation

|*Customer No.; +
Project No.; +
Project password; +
Notification password*
|Enter the information as received from SOFORT.

|*Designated use*
|Select the designated use. +
*Customer number* = Transmit your customer number as the designated use. +
*Date* = Transmit the date of the transaction as the designated use. +
*User-defined free text* = Enter a text in the user-defined free text field to transmit the text as the designated use.

|*User-defined free text*
|If the option *User-defined free text* was selected as the *designated use*, then enter a text for the designated use here.
|====

The following settings must be carried out in the admin area of the respective project on SOFORT Überweisung in order to successfully transmit incoming payments from SOFORT Überweisung to plentymarkets:[#50]

* Enter the success link for the Shop interface: *https://-USER_VARIABLE_0-/?result=ok&amp;ak=-USER_VARIABLE_3_URLENCODE-&amp;id=-USER_VARIABLE_1_URLENCODE-*
* Enter the abort link for the Shop interface: *https://-USER_VARIABLE_0-/?result=cancel&amp;ak=-USER_VARIABLE_3_URLENCODE-&amp;id=-USER_VARIABLE_1_URLENCODE-* +
→ If you are not using SSL, then only enter *http*.
* Activate automatic forwarding
* Create an email notification: *Your email address*
* Create HTTP notification: *$IHRE_DOMAIN/plenty/api/payment_notification.php?payment=sofort_ueberweisung* +
→ If available, enter the SSL domain to transmit sensitive data via an encrypted connection.
* Activate non-changeable parameters for *amount* and *purpose*, so that your customers cannot change these parameters during checkout.
* Check whether the parameters *Customer no.* (User_id), *Project no.* (Project_id), *Project password* and *Notification password* are the same as in your SOFORT Überweisung account and as the ones you entered in plentymarkets. When you check this, *SHA1* must be selected as the hash algorithm.

[#60]
=== Creating a new project using plentymarkets

Click on *New project* to create a new project. You can create new projects either in plentymarkets or in your SOFORT Überweisung account. In both cases, the projects will be saved at SOFORT Überweisung. +
If you *manually* create projects in your SOFORT Überweisung account, you need to enter the project information in plentymarkets as well.

[.instruction]
Creating a new project:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
. Click on *Sofortüberweisung.de*.  +
→ The *Settings* tab will open.
. Click on the *Interface* tab.
.  Click on *New project*.
.  Enter your data. +
→ Mandatory fields are marked with an ***.
.  Enter a project name.
.  Click on *Create*. +
→ You will be forwarded to SOFORT Überweisung. Follow the setup wizard.

[#70]
== Activating the payment method

Set up and activate the <<order-processing/payment/managing-payment-methods#20, payment method>> Sofortüberweisung.de in your plentymarkets system. As soon as these settings have been made, the customer will have the option to select SOFORT Überweisung when choosing *bank transfer/cash in advance* as their payment method. In this way, your customer will have the choice of either paying with a normal bank transfer or using SOFORT Überweisung. In addition, check the settings for *Permitted payment methods* in the <<order-processing/payment/managing-payment-methods#30, customer classes>> and for *Blocked payment methods* in the <<order-processing/fulfilment/preparing-the-shipment#1000, shipping profiles>>.

[#80]
== Activating the test mode

The test mode allows you to carry out some dummy transactions in order to test notifications etc.

[.instruction]
Carrying out a test transaction:

. Log in to SOFORT Überweisung.
. Open the *My projects* area.
. Select a project.
. Activate the *test mode*.
. *Save* the settings.
. Place an order in your online store with the payment method SOFORT Überweisung.

[IMPORTANT]
.Sort code for test mode
====
Enter one of the following sort codes if you want to use the test mode:

Germany: 88888888

Belgium: 999

Other: 00000

When entering other sort codes than the ones given above, the transaction will be transmitted even though the test mode is activated. Further information such as the account number, PIN or TAN can be made up.
====

Once you have finished testing, deactivate the test mode.

[#90]
== Importing incoming payments

Payments are transmitted by SOFORT Überweisung until they have been successfully imported into plentymarkets. Furthermore, you are able to see the status of faulty transmissions (faulty HTTP notifications) in the *notification* area of your SOFORT Überweisung account. From here, you can re-send failed transmissions.

[WARNING]
.Domain transfer
====
In the event of a domain transfer, the <<order-processing/payment/sofort-ueberweisung#50, settings>> for SOFORT Überweisung need to be adjusted in the backend - the URLs will no longer be correct. The actual payment process will continue to work correctly, but payments will no longer be transferred into the system.
====
