= Old online store: UPG
:lang: en
include::{includedir}/_header.adoc[]
:keywords: UPG, payment method
:description: Payment in plentymarkets: Set up the interface to UPG in your plentymarkets system.
:position: 80

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *UPG* in Callisto online stores. The following instructions are not valid for Ceres online stores!
====

link:http://www.upgplc.com/[UPG^] is a fully integrated payment solution for e-commerce offered by Creditreform.

[#10]
== Important notes

This chapter provides you with important information about integrating the payment provider in plentymarkets.

[IMPORTANT]
.UPG and store design
====
Note that the following conditions must be met before integrating UPG successfully in plentymarkets:

* Use of the standard design Callisto (Version 2 or higher)
* Use of the individual order process
* Safe handling of the plentymarkets CMS
* Experience with integrating payment providers
====

[.subhead]
Payment process

Depending on which payment method is selected, customers will either have to enter their details into an iframe or they will be redirected to a UPG page after confirming their order. If customers are redirected, they will need to enter their details for the selected payment method there. Once customers have entered the data and confirmed the payment, they will be directed back to your online store. Customers are currently redirected if they select the payment methods Sofortbanking or PayPal (as of 1st June 2016).

[#20]
== Registering with UPG

Register with UPG before you carry out the relevant settings in plentymarkets. To do so, link:http://www.upgplc.com/services/online-payments/[contact^] UPG.

[#30]
== Setting up UPG for Callisto

Proceed as described below to set  up the interface to UPG for your Callisto online store in plentymarkets.

[.instruction]
Setting up the interface to UPG:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *DE*.
.  Click on *UPG*. +
→ The *Settings* tab will open.
. Click on the *Interface* tab.
.  Expand the client.
.  Carry out the settings as desired. Pay attention to the information given in <<table-setup-upg-interface>>.
. *Save* the settings.

[[table-setup-upg-interface]]
.setting up the interface to UPG
[cols="1,3"]
|====
|Setting |Explanation

|*Test mode*
|Activate the test mode to test the exchange of data between plentymarkets and UPG without the need for actual transactions.

|*Seller ID*
|Enter the seller ID that you received from UPG.

|*Private key*
|Enter the private key that you received from UPG.

|*Shop ID*
|Enter the store ID that you received from UPG.
|====

[#40]
== Activating the payment method

Set up and activate the UPG <<order-processing/payment/managing-payment-methods#20, payment method>> in the *Settings* tab of the payment method. In addition, check the settings for *Permitted payment methods* in the <<order-processing/payment/managing-payment-methods#30, customer classes>> and for *Blocked payment methods* in the <<order-processing/fulfilment/preparing-the-shipment#1000, shipping profiles>>. You need to select the payment methods that you want to offer in your UPG account.

[#50]
== Carrying out settings in the UPG account

Enter the integration URLs and select the payment methods that you want to offer with UPG. Do this in your UPG account. Other factors such as fraud rules also influence whether a payment method is offered to specific customers. Your UPG account includes an area for the integration. There, select the payment methods that you would like to offer and enter two URLs. The URLs must be structured as follows:

* Redirect URL: https://MY-PLENTYSTORE.co.uk/plenty/api/payment_notification.php?payment=crefopayredirectk
* Notification URL: https://MY-PLENTYSTORE.co.uk/plenty/api/payment_notification.php?payment=crefopay

[#60]
== Displaying UPG in the Callisto online store

This section explains how to display UPG in the online store of plentymarkets. This is done in several steps. To do so, edit the *Order confirmation* category first.

[WARNING]
.No changes to the active design
====
Do not make changes to your active design. Before making changes to the design, make a backup copy so that you can restore the original state of the design.
====

[#61]
=== Customising the order confirmation

Modify the category *Order confirmation* to make the payment methods offered through UPG available to customers of your online store.

[.instruction]
Adding the payment method selection to the order confirmation stage:

. Go to *Item » Categories*.
. Open the design's folder, e.g. the folder for Callisto Light 3.
. Open the category *Order confirmation*.
. Click on the *Description 1* tab.
. Search for the *div class="panel-body"* container.
. Replace the content of this div container with the example code below.
. *Save* the settings.

[source,plenty]
----
include::assets/EX-EN-Crefopay-Bestellbestaetigung.html[]

----
[#63"]
=== Editing CheckoutCustomerInvoiceAddress

A small change in the *CheckoutCustomerInvoiceAddress* template is necessary, to display only those address values that are valid for CrefoPay.

[.instruction]
Editing CheckoutCustomerInvoiceAddress:

. Go to *CMS » Web design*.
. Open the folder *Layout » Checkout*.
. Open the template *CheckoutCustomerInvoiceAddress*.
. Search for the line of code *&lt;option value="3"{% if $FormOfAddressID == 3 %} selected{% endif %}&gt;Familie&lt;/option&gt;*.
. Delete this line of code from the template.
. *Save* the settings.

[#64"]
=== Editing CheckoutCustomerShippingAddress

Edit the template *CheckoutCustomerShippingAddress* in the same way.

[.instruction]
Editing CheckoutCustomerShippingAddress:

. Go to *CMS » Web design*.
. Open the folder *Layout » Checkout*.
. Open the template *CheckoutCustomerShippingAddress*.
. Search for the line of code *&lt;option value="3"{% if $FormOfAddressID == 3 %} selected{% endif %}&gt;Familie&lt;/option&gt;*.
. Delete this line of code from the template.
. *Save* the settings.

[#65"]
=== Setting up name validation for B2B customers

When using the payment provider UPG for B2B orders, the first name and last name of the customer must be shown on the invoice address. The template variables *ValidateInvoiceAddressFirstNameIfCompany* and *ValidateInvoiceAddressLastNameIfCompany* allow you to validate first and last names of B2B customers for invoice addresses if the company name was entered in the *Company* text field.

[.instruction]
Setting up name validation for B2B customers:

. Go to *CMS » Web design*.
. Open the folder *Layout » PageDesign*.
. Click on *PageDesignPrepareMainColumn*.
. Search for the template variables *ValidateInvoiceAddressFirstNameIfCompany* and *ValidateInvoiceAddressLastNameIfCompany*.
. Change the values of both variables from *false* to *true*. Pay attention to the information given in <<table-template-variables-b2b>>.
. *Save* the settings.

[[table-template-variables-b2b]]
.template variables for B2B customers
[cols="1,3"]
|====
| Element | Explanation

|*ValidateInvoiceAddressFirstNameIfCompany*
|*true* = Check the *First name* text field if the company name was entered in the *Company* text field of the invoice address. +
*false* Do not check the *First name* text field.

|*ValidateInvoiceAddressLastNameIfCompany*
|*true* = Check the *Last name* text field if the company name was entered in the *Company* text field of the invoice address. +
*false* Do not check the *Last name* text field.
|====

[#70]
==  Automatically sending shipping confirmations

You need to confirm UPG that you have sent the items to your customer before you will receive the customers payment from UPG. Set up an <<basics/automation/event-procedures#, event procedure>> to automatically send shipping confirmations when the outgoing items are booked.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter a name.
.  Select the *event* listed in table 3.
. *Save* the settings.
.  Pay attention to the explanations given in table 3 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for sending automatic shipping confirmations to UPG
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Outgoing items booked*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order* +
Delivery order - optional for partial delivery

|*Filter 2*
|*Order &gt; Payment method*
|*UPG*

|*Procedure*
|*Shipping &gt; Send shipping confirmation to UPG*
|
|====

[#80]
==  Automatically sending refunds

Create a return and report this return to UPG if a customer has returned an item. The customer will only get a refund if you report the return. Set up an event procedure to automatically report returns to UPG.

[.instruction]
Creating a return:

[#90]

. Go to *Orders » Edit orders*.
. Open the UPG order.  +
→ The *Overview* tab will open.
. Select the option *create* from the *Return...* drop-down list.
. Select the items that were returned. +
→ The return will be created and opened.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter a name.
.  Select the *event* listed in table 4.
. *Save* the settings.
.  Pay attention to the explanations given in table 4 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for automatically reporting refunds to UPG
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order generation: New return*
|

|*Filter*
|*Order &gt; Payment method*
|*UPG*

|*Procedure*
|*Payment methods &gt; Send refund to UPG*
|
|====

[#100]
==  Automatically sending cancellations

Set up an <<basics/automation/event-procedures#, event procedure>> to automatically inform UPG of cancellations.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter a name.
.  Select the *event* listed in table 5.
. *Save* the settings.
.  Pay attention to the explanations given in table 5 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for sending automatic cancellations to UPG
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Status change*
| Select status for *cancelled orders*.

|*Filter*
|*Order &gt; Order type*
|*Order*

|*Filter*
|*Order &gt; Payment method*
|*UPG*

|*Procedure*
|*Payment methods &gt; Send cancellation to UPG*
|
|====

[#110]
== Reporting a refund for partial cancellation to UPG

If you cannot deliver an item that a customer has already paid for, you need to report this cancellation to UPG, so that the customer will get their money back. You can trigger this refund by completing the order. Once an order has been completed, the customer receives the amount of money that is left, when the delivered items are subtracted from the total the customer has paid.

[.instruction]
Sending a refund:

. Go to *Orders » Edit orders*.
. Open the UPG order.  +
→ The *Overview* tab will open.
. Click on the *Settings* tab.
. Click on *Complete UPG payment process*.

You can also complete an order to give the customer a refund if the customer has paid a higher amount than the invoice amount.
