= Inventur durchführen
:lang: de
include::{includedir}/_header.adoc[]
:position: 50
:url: app/funktionen/lagerverwaltung/inventur

Eine Inventur der Ware kann nicht nur <<warenwirtschaft/inventur-vornehmen#, im plentymarkets Backend>> sondern auch mit der plentymarkets App durchgeführt werden. Voraussetzung ist, dass die Person die Berechtigung für die Inventur hat. Außerdem müssen den <<warenwirtschaft/lager-einrichten, Lagerorten Barcodes zugeordnet>> sein. Optional kannst du den Inventurmodus aktivieren, um den Bestand während der Inventur einzufrieren. Das Aktivieren des Inventurmodus ist jedoch nicht erforderlich, da der neue Bestand direkt im Datensatz der Variante gespeichert wird.

[TIP]
.Hardware für plentymarkets App
====
Hardware-Empfehlungen für Inventuren mit der plentymarkets App findest du auf der Handbuchseite <<schnelleinstieg/systemvoraussetzungen#400, Systemvoraussetzungen>>.
====

[#100]
=== App-Inventur vorbereiten

Nimm die unten beschriebenen Einstellungen vor, um eine Inventur mit der plentymarkets App vorzubereiten.

[TIP]
.Lagerorte labeln
====
Für die Inventur müssen deinen Lagerorten Barcodes zugeordnet sein. Noch schneller geht die Inventur, wenn du deine <<warenwirtschaft/lager-einrichten#800, Lagerorte labelst>>. Bei der Inventur scannst du dann einfach die Labels des Lagerorts.
====

[#200]
==== Bestand über Datenformat Stock exportieren

Wenn du nach der Bestandszählung alle Bestandsabweichungen auf einmal prüfen möchtest, exportiere vor Beginn der Inventur den Bestand über das Datenformat <<daten/export-import/datenformate/stock#, Stock>>. Führe einen weiteren Export nach Ende der Inventur durch und vergleiche die Bestandsdaten.

[#300]
==== App-Berechtigungen für Inventur erteilen

Konten mit Admin-Rechten haben standardmäßig die Berechtigungen, um Inventuren über die App vorzunehmen. Personen mit den Benutzerklassen *Variabel* und *Logistik* musst du diese Berechtigungen erteilen.

[.instruction]
App-Berechtigungen für Inventur erteilen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer*.
. Öffne das Konto.
. Wechsele in das Tab *Mobile*.
. Aktiviere im Bereich *Sichtbare Funktionen* die Berechtigung *Inventur*. +
**__Tipp:__** Wenn dieses Tab nicht sichtbar ist, hat das Konto Admin-Rechte.
. *Speichere* die Einstellungen.
. Wechsele in das Tab *Berechtigungen*.
. Klicke auf *Menü und REST-API Rechte verwalten*. +
→ Die Ansicht *Rechte* wird geöffnet.
. Aktiviere in der Spalte *Berechtigungen* die Berechtigung *Warenbestände » Lager » Lagerort » Lagerort anzeigen*.
. *Speichere* die Einstellungen.

[#400]
==== App-Inventur personalisieren

In der plentymarkets App können Benutzer weitere Einstellungen vornehmen, um den Inventurvorgang zu personalisieren.

[.instruction]
Inventur über die plentymarkets App personalisieren:

. Melde sich bei der plentymarkets App an.
. Tippe in der Menüleiste auf das *Menüsymbol*.
. Tippe auf *Einstellungen*.
. Tippe auf *Inventur*. +
→ Das Einstellungsmenü *Inventur* wird angezeigt.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-inventur-app-einstellungen>>. +
*_Tipp:_* Die Einstellungen werden gespeichert, wenn du das Menü verlässt.

[[tabelle-inventur-app-einstellungen]]
.Inventur; App-Einstellungen
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Lagerortsuche

|*Fokus auf Barcode setzen*
|Aktivieren, um in der Lagerortsuche den Fokus in das Feld *Barcode* zu setzen. Bei gelabelten Lagerorten können Benutzer das Lagerort-Label dann sofort scannen.

2+|Artikelsuche

|*Fokus auf Barcode setzen*
|Aktivieren, um in der Artikelsuche den Fokus in das Feld *Barcode* zu setzen. Bei gelabelten Artikeln können Benutzer das Artikel-Label dann sofort scannen.

|*Artikel einzeln scannen*
|Wählen, ob die Menge per Scan oder über das Tastenfeld erfasst wird. +
Aktiviert = Jedes Exemplar des Artikels wird einzeln gescannt. +
**__Tipp:__** Die gescannte Menge kann manuell korrigiert werden. Dazu auf den Artikel tippen und die korrekte Menge eingeben. +
Deaktiviert = Nachdem ein Artikel-Label gescannt wird, geben Benutzer die gezählte Menge über das Tastenfeld ein.

|*Manuelle Artikelsuche ermöglichen*
|Wählen, ob Artikel manuell gesucht werden können. +
Aktiviert = Artikel können entweder durch Scannen des Artikel-Labels oder durch Eingabe eines Suchkriteriums über das Tastenfeld aufgerufen werden. +
Deaktiviert = Eine manuelle Suche von Artikeln ist nicht möglich. Artikel können nur durch Scannen des Artikel-Labels aufgerufen werden.

|*Auf Hauptlager begrenzen* +
(ab App-Version 1.9.3)
|Wählen, ob die vorgeschlagenen Artikel gefiltert werden sollen. +
Deaktiviert (Standardeinstellung) = Die Artikel werden nicht gefiltert. Wenn die gleichen Artikel an mehreren Lagerorten gelagert werden, werden alle Lagerorte vorgeschlagen. +
Aktiviert = Nur Artikel werden vorgeschlagen, bei denen das aktuelle Inventurlager mit dem an der Variante gespeicherten Hauptlager übereinstimmt.

2+|Bestand speichern

|*Speichern per Schaltfläche ermöglichen*
|Deaktivieren, um die Schaltfläche *Bestand speichern* auszublenden. +
Aktiviert = Der Bestand eines Lagerorts wird über die Schaltfläche *Bestand speichern* oder durch Scannen des Lagerort-Labels gespeichert. +
Deaktiviert = Der Bestand eines Lagerorts wird durch Scannen des Lagerort-Labels gespeichert.

|*Bestätigungsdialog anzeigen*
|Aktivieren, um vor dem Speichern des Bestands einen Bestätigungsdialog anzuzeigen. +
Aktiviert = Benutzer müssen den Vorgang bestätigen, bevor der Bestand gespeichert wird. +
Deaktiviert = Der Bestand wird sofort gespeichert.
|====

[#500]
=== Inventurbestand über die plentymarkets App erfassen

Bei der Inventur mit der plentymarkets App kannst du entweder jedes Exemplar eines Artikels einzeln scannen oder die vorhandenen Exemplare manuell zählen und die gezählte Stückzahl über das Tastenfeld eingeben. Welches Verfahren angewendet wird, wird über die Option *Artikel einzeln scannen* gesteuert.

[IMPORTANT]
.Bestand nicht erfasster Artikel eines Lagerorts wird auf Null gesetzt
====
Erfasse alle Artikel, die sich an einem Lagerort befinden. Wenn du verschiedene Artikel an demselben Lagerort lagerst, wird der Bestand aller Artikel, die du bei der Inventur nicht erfasst, auf Null gesetzt. Beispiel: +
Auf Lagerort 1 befinden sich laut plentymarkets Bestand 10 x Artikel A, 10 x Artikel B und 2 x Artikel C. Bei der Inventur werden 10 x Artikel A und 10 x Artikel B gescannt. Artikel C wird nicht gescannt. +
→ Die App bucht 10 x Artikel A, 10 x Artikel B und 0 x Artikel C. Der Bestand für Artikel C wird also genullt. +
Wenn du erst bei der Inventur beginnst, weitere Lagerorte anzulegen, werden diese nicht genullt. Dies gilt nur für die Lagerorte, die bearbeitet werden.
====

[#600]
==== Jedes Exemplar eines Artikels einzeln scannen

Benutzer müssen den Bestand nicht selbst zählen, sondern können die Labels jedes einzelnen Exemplars des Artikels einzeln scannen, bis alle Exemplare am Lagerort gescannt wurden. Die Zählung erfolgt inkrementell im Hintergrund. Für diese Art der Bestandskorrektur muss in den App-Einstellungen des Benutzers die Option *Artikel einzeln scannen* aktiviert sein.

[.instruction]
Jedes Exemplar eines Artikels einzeln scannen:

. Öffnee die plentymarkets App.
. Tippe in der Menüleiste auf das *Menüsymbol*.
. Tippe auf *Inventur*. +
→ Die Ansicht *Inventur* wird angezeigt.
. Scanne das Label des Lagerorts. +
→ Der Lagerort wird ermittelt. Erfasste Artikel werden auf diesen Lagerort gebucht.
. Scanne das Label jedes einzelnen Exemplars, bis du alle Artikel des Lagerorts erfasst hast. +
*_Tipp:_* Wenn sich verschiedene Artikel an einem Lagerort befinden, wird beim Scannen automatisch die Menge des korrekten Artikels erhöht. +
*_Hinweis:_* Um die gescannte Menge manuell zu korrigieren, tippe auf den Artikel und gib die korrekte Menge ein. +
→ Wenn für die Variante in dem gewählten Lager Mindesthaltbarkeitsdaten und/oder Chargeninformationen gepflegt werden, wirst du aufgefordert, diese Daten einzugeben.
. *_Optional:_* Wähle das Mindesthaltbarkeitsdatum und/oder gib die Charge ein und tippe auf *Artikel hinzufügen*. +
→ Der Bestand wird eingebucht.
. Um die Zählung abzuschließen, scanne das Label des Lagerorts erneut oder tippe auf *Bestand speichern*. +
→ Der gezählte Bestand wird gespeichert. +
→ Der gezählte Bestand wird im Menü *Waren » Lagerort-Verwaltung* des plentymarkets Backend angezeigt. +
→ Der Bestand wird im Menü *Artikel » Artikel verwalten* an der Variante gespeichert.

[#700]
==== Gezählte Stückzahl eingeben

Statt das Label jedes einzelnen Exemplars eines Artikels am Lagerort zu scannen, können Benutzer zählen, wie viele Exemplar eines Artikels am Lagerort vorhanden sind, und das Zählergebnis eingeben. Für diese Art der Bestandskorrektur muss in den App-Einstellungen des Benutzers die Option *Artikel einzeln scannen* deaktiviert sein.

[.instruction]
Gezählte Stückzahl eingeben:

. Öffne die plentymarkets App.
. Tippe in der Menüleiste auf das *Menüsymbol*.
. Tippe auf *Inventur*. +
→ Die Ansicht *Inventur* wird angezeigt.
. Scanne das Label des Lagerorts. +
→ Der Lagerort wird ermittelt. Erfasste Artikel werden auf diesen Lagerort gebucht.
. Scanne das Label eines Artikels oder führe eine Artikelsuche aus. +
→ Das Fenster *Menge eingeben* wird angezeigt.
. Gib die gezählte Menge für den Artikel ein.
. Um die Zählung abzuschließen, scanne das Label des Lagerorts erneut oder tippe auf *Bestand speichern*. +
→ Der gezählte Bestand wird gespeichert. +
→ Der gezählte Bestand wird im Menü *Waren » Lagerort-Verwaltung* des plentymarkets Backend angezeigt. +
→ Der Bestand wird im Menü *Artikel » Artikel verwalten* an der Variante gespeichert.
