= jQuery
:lang: de
// include::{includedir}/_header.adoc[]
:keywords: jQuery, Syntax, Webdesign, CMS
:position: 100

*CMS » Webdesign*

== Inhalt dieser Seite

Auf dieser Seite erhältst du Informationen zu *jQuery*.

== Wichtiges zu jQuery

link:http://jquery.com/[jQuery^] ist eine umfangreiche JavaScript-Klassenbibliothek, die komfortable Funktionen zur Manipulation und Navigation in deiner Website anbietet. Diese ist automatisch in deinem Webshop vorhanden und kann überall in deinem Layout genutzt werden. Zudem bieten wir dir die Zusatz-Bibliotheken link:http://jqueryui.com/[jQuery UI^] und link:http://jquerytools.github.io/[jQuery Tools^] an.

[WARNING]
.Vor Einbindung prüfen!
====
*Kompatibilität*

Solltest du beabsichtigen, mit anderen JavaScript-Klassenbibliotheken wie z.B. *Prototype* zu arbeiten, informiere dich vorher über die Kompatiblität beider Bibliotheken und berücksichtige mögliche Konfliktpotentiale.

*Bibliotheken*

Binde keine der genannten Bibliotheken in deinem Layout neu ein. Dies könnte unabsehbare Auswirkungen auf die Funktion der Bibliotheken haben.
====

[TIP]
.Tutorial
====
Ein Tutorial zu jQuery findest du über den Link link:http://www.very-clever.com/jquery-tutorial.php[http://www.very-clever.com/jquery-tutorial.php^].
====
