= Rakuten einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Rakuten, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz Rakuten in Ihrem plentymarkets System ein.
:position: 10

plentymarkets bietet Ihnen die Möglichkeit, Ihre Artikel auf der Plattform Rakuten.de zu verkaufen.

[#100]
== Bei Rakuten registrieren

Bevor Sie Rakuten in plentymarkets einrichten, müssen Sie sich bei Rakuten registrieren. Die Registrierungsformulare finden Sie unter link:http://leadgen.rakuten.de/form?leadsource=marketplace_header[rakuten.de^].

[#200]
==  Rakuten.de in plentymarkets einrichten

Nehmen Sie die folgenden Einstellungen in plentymarkets vor, um die Schnittstelle zu Rakuten.de einzurichten.

[.instruction]
Rakuten.de einrichten:

. Öffnen Sie das Menü *System » Märkte » Rakuten » Einstellungen*. +
→ Das Tab *Neues Konto* wird angezeigt.
. Klappen Sie *Rakuten-Einstellungen* auf.  +
→ Die Plattform *rakuten.de* ist vorausgewählt.
. Tragen Sie den *Authentifizierungsschlüssel* ein. +
→ Den Schlüssel finden Sie im Backend Ihres Rakuten.de-Kontos.
. Nehmen Sie die Einstellungen gemäß <<einstellungen-rakuten>> vor.
. *Speichern* Sie die Einstellungen.
. Laden Sie das Menü neu.  +
→ Das Konto wurde angelegt und die Einstellungen für die Plattform geladen.

Wenn Sie mehrere Konten bei Rakuten.de haben, benötigen Sie für jedes Konto einen Authentifizierungsschlüssel.

[[einstellungen-rakuten]]
.Rakuten konfigurieren
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Auftragsimport

|*Aktivieren*
|*Deaktivieren* = Schnittstelle ist inaktiv. +
*Aktivieren* = Schnittstelle ist aktiv. Neue Aufträge werden automatisch einmal pro Stunde abgerufen. Versendete Aufträge werden automatisch jede Stunde an Rakuten übermittelt.

|*Zahlung*
|*Zahlungseingang offen* = Aufträge als unbezahlt importieren. +
*Zahlungseingang gebucht* = Aufträge werden als unbezahlt importiert. Somit kann eine Kontrolle von Rakuten erfolgen. Bei Zahlungseingang von Rakuten wird der Auftrag auf bezahlt gesetzt. +
Unabhängig von der gewählten Option werden Artikel bei ausreichendem Bestand sofort für den Versand freigegeben.

|*Auftragsbestätigung senden*
|*Deaktivieren* = Keine Auftragsbestätigung übermitteln. +
*Aktivieren* = Auftragsbestätigung an den Kunden übermitteln. Die unter *System » Mandant » Mandant wählen » E-Mail » Automatischer Versand* eingetragene E-Mail-Vorlage wird an den Kunden versendet.

|*API-Log einsehen*
|Zum Abrufen des API-Logs auf *API-Log einsehen* klicken.
|====

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

* stündlicher Auftragsabgleich

Folgende Prozesse werden durch das link:https://marketplace.plentymarkets.com/plugins/markets/ElasticExportRakutenDE_4721[ElasticExportRakutenDE-Plugin^] abgebildet:

* stündlicher Bestandsabgleich
* stündlicher Preisabgleich

Mit dem *ElasticExportRakutenDE-Plugin* können Sie das Datenformat *RakutenDE-Plugin* für den elastischen Export nutzen. Das Plugin ist im link:https://marketplace.plentymarkets.com/plugins/markets[plentyMarketplace^] erhältlich. Weitere Informationen zur Einrichtung des Plugins finden Sie im User Guide des Plugins.

[#250]
=== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit Rakuten verknüpfen können, muss im Menü *System » Aufträge » Auftragsherkunft* die Auftragsherkunft Rakuten aktiviert werden.

[.instruction]
Auftragsherkunft für Rakuten aktivieren:

. Öffnen Sie das Menü *System » Aufträge » Auftragsherkunft*.
. Setzen Sie bei *Rakuten* ein Häkchen.
. *Speichern* Sie die Einstellungen.

[#300]
=== Artikelverfügbarkeit einstellen

Artikel, die Sie auf Rakuten.de verkaufen möchten, müssen im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Rakuten.de einstellen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktivieren Sie die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechseln Sie in das Tab *Verfügbarkeit*.
. Klicken Sie im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktivieren Sie die Option *Rakuten.de*.
. Klicken Sie auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichern* Sie die Einstellungen. +
→ Der Artikel ist auf Rakuten.de verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden.

[#350]
===  SKU für eine Herkunft festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügen Sie marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
.  Wechseln Sie in das Tab *Verfügbarkeit*.
.  Klicken Sie im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
.  Wählen Sie die Herkunft *Rakuten.de*.
.  Wählen Sie das dazugehörige Marktplatzkonto.
.  Geben Sie die SKU ein.
.  Klicken Sie auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

[#400]
=== Kategorien verknüpfen

Nachdem Sie den Artikel verfügbar gemacht haben, verknüpfen Sie den Artikel mit einer Rakuten-Kategorie.

[.instruction]
Kategorie verknüpfen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab *Multi-Channel*.
. Wählen Sie aus der Dropdown-Liste *Rakuten.de* im Bereich *Kategorieverknüpfung* die Hauptkategorie für den Artikel. +
→ Ein Fenster zur weiteren Kategorieauswahl wird geöffnet.
. Wählen Sie die Unterkategorien bis zur untersten Kategorie. +
→ Eine Kategorienummer wird angezeigt.
. Klicken Sie auf *Übernehmen*. +
→ Die Kategorieverknüpfung wird durch die Kategorienummer und die Rakuten-Kategorie angezeigt.
. *Speichern* Sie die Einstellungen.

[#500]
=== Versandgruppen mit Artikeln verknüpfen

Versandprofile werden direkt bei Rakuten eingerichtet. Die am Artikel gespeicherten Versandprofile werden nicht an Rakuten übertragen. Versandprofile werden bei Rakuten als Versandgruppen bezeichnet. Diese Versandgruppen verknüpfen Sie per *Freitextfeld* mit Ihren Artikeln.

[.instruction]
Freitextfeld für Versandgruppe einrichten:

. Öffnen Sie das Menü *System » Artikel » Freitextfelder*.
. Fügen Sie eine Feldbezeichnung, z.B. *Rakuten-Versandgruppe*, in eines der Freitextfelder ein.
. *Speichern* Sie die Einstellungen. +
→ Hinweis: Freitextfelder werden über Nacht aktiviert und sind am nächsten Morgen verfügbar.
. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Tragen Sie bei jedem Artikel, der übertragen werden soll, im Tab *Felder* die *Ziffer der Versandgruppe* ein.
. *Speichern* Sie die Einstellungen.
. Teilen Sie Rakuten das verwendete Freitextfeld mit.

[TIP]
.Kein Freitextfeld übermittelt
====
Wenn kein Freitextfeld an Rakuten übermittelt wird, wird der Artikel automatisch mit der Versandgruppe 1 verknüpft.
====

Weitere Lieferländer stellen Sie ebenfalls bei Rakuten ein.

[#600]
=== Energieeffizienz angeben

Die EU-Verordnung zur Energieeffizienzrichtlinie schreibt für die Auszeichnung Ihrer Artikel seit 01.01.2015 Angaben zur Energieeffizienz sowie die Bereitstellung von Produktdatenblättern vor. Diese Informationen sind auch an Rakuten zu übermitteln. Erstellen Sie dazu die <<artikel/artikel-verwalten#480, Merkmale>>:

* *Energieeffizienzklasse* +
Merkmal-Typ: *Kein*
* *Energieeffizienzklasse bis* +
Merkmal-Typ: *Kein* +

* *Energieeffizienzklasse-Gerätegruppe* +
Merkmal-Typ: *Kein*

Für jede Energieeffizienzklasse von A+++ bis G muss ein eigenes Merkmal angelegt werden.

[.instruction]
Merkmal anlegen:

. Öffnen Sie das Menü *System » Artikel » Merkmale*.
. Öffnen Sie das Tab *Neues Merkmal*.
. Tragen Sie unter *Name (intern)* einen Namen für das Merkmal ein.
. Wählen Sie aus der Dropdown-Liste im Feld *Merkmaltyp* die Option *Kein*.
. Wählen Sie aus der Dropdown-Liste im Feld *Rakuten.de-Merkmal* das Rakuten-Merkmal.
. *Speichern* Sie die Einstellungen.

Die Merkmale verknüpfen Sie im Tab <<artikel/artikel-verwalten#480, Merkmale>> eines Artikels.


Das Produktdatenblatt stellen Sie für Rakuten in elektrischer Form über einen Link in der Artikelbeschreibung zur Verfügung. Fügen Sie den Link zum Produktdatenblatt im Tab <<artikel/artikel-verwalten#50, Texte>> eines Artikels ein. Gehen Sie wie im Folgenden beschrieben vor.

[.instruction]
Produktdatenblatt in der Artikelbeschreibung speichern:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Laden Sie das Produktdatenblatt im Tab *Bilder* des Artikels hoch.
. Kopieren Sie die URL des Bildes.
. Fügen Sie den Link zum Produktdatenblatt im Tab *Texte* des Artikels ein.
. *Speichern* Sie die Einstellungen.

[#700]
=== Artikelexport einrichten

In diesem Kapitel wird beschrieben, wie Sie Ihre Artikel zu Rakuten.de übertragen. Artikel werden über den elastischen Export mit dem Datenformat RakutenDE zu Rakuten.de exportiert. Dafür müssen zuvor die Plugins *ElasticExport* und *ElasticExportRakutenDE* installiert worden sein. Legen Sie zunächst das Datenformat RakutenDE an und übermitteln im Anschluss die URL zu Rakuten.

[IMPORTANT]
.Für die Einrichtung Rakuten kontaktieren
====
Für das Einrichten des Imports muss Rakuten kontaktiert werden.
====

[.instruction]
Artikelexport einrichten:

. Öffnen Sie das Menü *Daten » Elastischer Export*.
. Klicken Sie auf *Neuer Export*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<einstellungen-artikelexport>>.
. Nehmen Sie weitere Einstellungen für Artikelfilter und Formateinstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 5 auf der Handbuchseite <<basics/datenaustausch/export-import/daten-exportieren#60, Daten über dynamischen Export exportieren>>.
. *Speichern* Sie die Einstellungen. +
→ Eine ID für das Exportformat wird vergeben und das Exportformat erscheint in der Übersicht *Exporte*.

[[einstellungen-artikelexport]]
.Einstellungen für Artikelexport
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Einstellungen

|*Name*
|Name eingeben. Unter diesem Namen erscheint das Exportformat in der Übersicht im Tab *Exporte*.

|*Typ*
|Typ *Artikel* aus der Dropdown-Liste wählen.

|*Format*
|Format *RakutenDE* aus der Dropdown-Liste wählen.

|*Limit*
|Zahl eingeben. Wenn mehr als 10000 Datensätze an rakuten.de übertragen werden sollen, wird die Ausgabedatei für 24 Stunden nicht noch einmal neu generiert, um Ressourcen zu sparen.

|*Cache-Datei generieren*
|Häkchen setzen, wenn mehr als 9999 Datensätze an Rakuten.de übertragen werden sollen. Um eine optimale Performance des elastischen Exports zu gewährleisten, darf diese Option bei maximal 20 Exportformaten aktiv sein.

|*Bereitstellung*
|*URL* wählen.

|*Dateiname*
|Der Dateiname muss auf *.csv* enden, damit Rakuten.de die Datei erfolgreich importieren kann.

|*Token*, +
*URL*
|Wenn unter *Bereitstellung* die Option *URL* gewählt wurde, auf *Token generieren* klicken. Der Token wird dann automatisch eingetragen. Die URL wird automatisch eingetragen, wenn unter *Token* der Token generiert wurde. Diese URL an Rakuten.de übergeben, damit die Artikel exportiert werden.

2+|Formateinstellungen

|*Produkt-URL*
|Wählen, ob die URL des Artikels oder der Variante an Rakuten.de übertragen wird. Varianten URLs können nur in Kombination mit dem Ceres Webshop übertragen werden.

|*Mandant*
|Mandanten wählen. Diese Einstellung wird für den URL-Aufbau verwendet.

|*URL-Parameter*
|Suffix für die Produkt-URL eingeben, wenn ein Suffix für den Export erforderlich ist. Die Produkt-URL wird dann um die eingegebene Zeichenkette erweitert, wenn weiter oben die Option *übertragen* für die Produkt-URL aktiviert wurde.

|*Auftragsherkunft*
|*Rakuten.de* wählen.

|*Marktplatzkonto*
|Wenn Artikeldaten zum ersten Mal exportiert werden, wird das hier gewählte Konto für die Generierung der SKU berücksichtigt.

|*Sprache*
|Sprache aus der Dropdown-Liste wählen.

|*Artikelname*
|Name 1, Name 2 oder Name 3 wählen. Die Namen sind im Tab *Texte* eines Artikels gespeichert. Im Feld *Maximale Zeichenlänge (def. Text)* optional eine Zahl eingeben, wenn Rakuten.de eine Begrenzung der Länge des Artikelnamen beim Export vorgibt.

|*Vorschautext*
|Diese Option ist für Rakuten.de nicht relevant.

|*Beschreibung*
|Wählen, welcher Text als Beschreibungstext übertragen werden soll. +
Im Feld *Maximale Zeichenlänge (def. Text)* optional eine Zahl eingeben, wenn Rakuten.de eine Begrenzung der Länge der Beschreibung beim Export vorgibt. +
Option *HTML-Tags entfernen* aktivieren, damit die HTML-Tags beim Exportieren entfernt werden. +
Im Feld *Erlaubte HTML-Tags, kommagetrennt (def. Text)* optional die HTML-Tags eingeben, die beim Export erlaubt sind. Wenn mehrere Tags eingegeben werden, mit Komma trennen.

|*Zielland*
|Zielland aus der Dropdown-Liste wählen.

|*Barcode*
|ISBN oder eine EAN aus der Dropdown-Liste wählen. Der gewählte Barcode muss mit der oben gewählten Auftragsherkunft verknüpft sein. Andernfalls wird der Barcode nicht exportiert.

|*Bild*
|*Position 0* oder *Erstes Bild* wählen, um dieses Bild zu exportieren. +
*Position 0* = Ein Bild mit der Position 0 wird übertragen. +
*Erstes Bild* = Das erste Bild wird übertragen.

|*Bildposition des Energieetiketts*
|Position des Energieetiketts eintragen. Alle Bilder, die als Energieetikette übertragen werden sollen, müssen diese Position haben.

|*Bestandspuffer*
|Der Bestandspuffer für Varianten mit der Beschränkung auf den Netto-Warenbestand. Zahl eingeben. Die eingegebene Menge wird vom Bestand abgezogen.

|*Bestand für Varianten ohne Bestandsbeschränkung*
|Der Bestand für Varianten ohne Bestandsbeschränkung.

|*Bestand für Varianten ohne Bestandsführung*
|Der Bestand für Varianten ohne Bestandsführung.

|*Währung live umrechnen*
|Aktivieren, damit der Preis je nach eingestelltem Lieferland in die Währung des Lieferlandes umgerechnet wird. Der Preis muss für die entsprechende Währung freigegeben sein.

|*Verkaufspreis*
|Brutto- oder Nettopreis aus der Dropdown-Liste wählen.

|*Angebotspreis*
|Aktivieren, um den Angebotspreis zu übertragen.

|*UVP*
|Aktivieren, um den UVP zu übertragen.

|*Versandkosten*
|Aktivieren, damit die Versandkosten aus der Konfiguration übernommen werden. Wenn die Option aktiviert ist, stehen in den beiden Dropdown-Listen Optionen für die Konfiguration und die Zahlungsart zur Verfügung. +
Option *Pauschale Versandkosten übertragen* aktivieren, damit die pauschalen Versandkosten übertragen werden. Wenn diese Option aktiviert ist, muss im Feld darunter ein Betrag eingegeben werden.

|*MwSt.-Hinweis*
|Text eingeben. Dieser Betrag enthält die Mehrwertsteuer zuzüglich Versand.

|*Artikelverfügbarkeit*
|Option *überschreiben* aktivieren und in die Felder *1* bis *10*, die die ID der Verfügbarkeit darstellen, Artikelverfügbarkeiten eintragen. Somit werden die Artikelverfügbarkeiten, die im Menü *System » Artikel » Verfügbarkeit* eingestellt wurden, überschrieben.
|====

[IMPORTANT]
.Exportinformationen
====
Wenn Sie eine oder mehrere Einstellungen ändern, müssen Sie den neuen Link an Rakuten übergeben.

Pro Export werden maximal 4000 Artikel exportiert. Wenn Sie mehr Artikel exportieren, wird automatisch ein zweiter Export ausgeführt. Um den zweiten Export anzuzeigen, setzen Sie den Parameter *&amp;Page* = im Export-Link auf *2*.

Technische Daten werden in der letzten Spalte der Exportdatei an Rakuten übergeben.
====

==== Lieferzeiten überschreiben

Rakuten erwartet bei Lieferzeit vordefinierte Werte. Sie können z.B. nicht die Werte 1 oder 2 als Lieferzeit übermitteln, da der Export in diesem Fall mit einem Fehler abgelehnt wird.
Deshalb müssen Sie die Lieferzeit im elastischen Export für Rakuten überschreiben. Der folgenden Liste entnehmen Sie die Bedeutungen der Rakuten-Lieferzeiten und ordnen diese Ihren Artikelverfügbarkeiten zu. Wenn die Artikelverfügbarkeit ID 1 in Ihrem System bedeutet, dass die Ware auf Lager ist und innerhalb der nächsten 1-3 Werktage geliefert wird, dann überschreiben Sie im elastischen Export die Artikelverfügbarkeit ID 1 mit der Liefezeit 0.

* 0 = Ab Lager lieferbar (= Lieferzeit 1-3 Werktage)
* 3 = versandfertig in 3 Werktagen (= Lieferzeit ca. 3 - 6 Werktage)
* 5 = versandfertig in 5 Werktagen (= Lieferzeit ca. 6 - 8 Werktage)
* 7 = versandfertig in 7 Werktagen (= Lieferzeit ca. 8 - 10 Werktage)
* 10 = versandfertig in 10 Werktagen (= Lieferzeit ca. 10 - 15 Werktage)
* 15 = versandfertig in 15 Werktagen (= Lieferzeit ca. 15 - 20 Werktage)
* 20 = versandfertig in 20 Werktagen (= Lieferzeit ca. 20 - 30 Werktage)
* 30 = versandfertig in 30 Werktagen (= Lieferzeit ca. 30 - 40 Werktage)
* 40 = versandfertig in 40 Werktagen (= Lieferzeit ca. 40 - 50 Werktage)
* 50 = versandfertig in 50 Werktagen (= Lieferzeit ca. 50 - 60 Werktage)
* 60 = versandfertig in 60 Werktagen (= Lieferzeit länger als 3 Monate)

Sie finden die Werte für Lieferzeiten auch in der link:http://doku.rakuten.de/doku.php/neuer_import/start[Schnittstellendokumentation^] von Rakuten.

==== Präfix und Suffix zu Parent-SKUs hinzufügen

Wenn Sie das link:https://marketplace.plentymarkets.com/plugins/markets/ElasticExportRakutenDE_4721[ElasticExportRakutenDE-Plugin^] in Ihrem plentymarkets System installiert haben, haben Sie die Möglichkeit, Parent-SKUs um Präfixe und Suffixe zu erweitern. Dadurch vermeiden Sie, dass die Parent-SKU und die zugehörigen Child-SKUs identisch sind und deshalb bei Rakuten als der gleiche Artikel angegeben werden.

Präfixe und Suffixe werden im Menü *Plugins » Plugin-Übersicht »  ElasticExportRakutenDE » Konfiguration » Parent-SKU* hinzugefügt.

[.instruction]
Präfixe und Suffixe hinzufügen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf das *ElasticExportRakutenDE*-Plugin.
. Gehen Sie zu *Konfiguration » Parent-SKU*.
. Geben Sie in die Felder *Präfix* und *Suffix* Präfix und Suffix ein wie benötigt.
. *Speichern* Sie die Einstellungen. +
→ Die eingegebenen Präfixe und Suffixe werden nun zu Parent-SKUs hinzugefügt, die Sie neu generieren.

[TIP]
.Alphanumerische Zeichen verwenden
====
Wir empfehlen, für die Präfixe und Suffixe nur Buchstaben und Ziffern zu verwenden. Vermeiden Sie Umlaute. Die Verwendung von Umlauten kann zu Problemen beim Datenaustausch führen.
====

[IMPORTANT]
.Änderungen gelten nur für neu generierte SKUs
====
Bitte beachten Sie, dass Präfix und Suffix nur zu den Parent-SKUs hinzugefügt werden, die Sie neu für Rakuten.de generieren, nachdem diese Einstellung gespeichert wurde. Bereits bestehende Parent-SKUs für Rakuten.de werden nicht berücksichtigt. Fügen Sie die Präfixe und Suffixe manuell für diese SKUs hinzu, wenn gewünscht.
====

[#800]
=== Preisabgleich einrichten

In diesem Kapitel erfahren Sie, wie Sie den Preisabgleich für Rakuten aktivieren. Preise werden über den elastischen Export mit dem Datenformat RakutenDE-Plugin mit Rakuten abgeglichen. Dafür müssen zuvor die Plugins *ElasticExport* und *ElasticExportRakutenDE* installiert worden sein. +
Preise werden stündlich abgeglichen.

[.instruction]
Preisabgleich aktivieren:

. Gehen Sie zu *Plugins » Plugin-Übersicht*.
. Klicken Sie auf das *ElasticExportRakutenDE*-Plugin.
. Gehen Sie zu *Konfiguration » Update-Einstellungen*.
. Setzen Sie ein Häkchen bei *Preis-Update*.
. *Speichern* Sie die Einstellungen.

[IMPORTANT]
.Anfrage zum Preis- und Bestandsabgleich
====
Falls die Anfragen an die Rakuten-Schnittstelle 5mal hintereinander unbeantwortet bleiben, wird der Preis- und Bestandsabgleich abgebrochen.
====

[#900]
=== Bestandsabgleich einrichten

In diesem Kapitel erfahren Sie, wie Sie den Bestandsabgleich für Rakuten aktivieren. Bestände werden über den elastischen Export mit dem Datenformat RakutenDE-Plugin mit Rakuten abgeglichen. Dafür müssen zuvor die Plugins *ElasticExport* und *ElasticExportRakutenDE* installiert worden sein. +
Bestände werden stündlich abgeglichen.

[.instruction]
Bestandsabgleich aktivieren:

. Gehen Sie zu *Plugins » Plugin-Übersicht*.
. Klicken Sie auf das *ElasticExportRakutenDE*-Plugin.
. Gehen Sie zu *Konfiguration » Update-Einstellungen*.
. Setzen Sie ein Häkchen bei *Bestands-Update*.
. *Speichern* Sie die Einstellungen.

[IMPORTANT]
.Anfrage zum Preis- und Bestandsabgleich
====
Falls die Anfragen an die Rakuten-Schnittstelle 5mal hintereinander unbeantwortet bleiben, wird der Preis- und Bestandsabgleich abgebrochen.
====

[#1400]
== Verkaufspreis festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für die Auftragsherkunft Rakuten.de einen Verkaufspreis festzulegen. Dieser Preis wird auf Rakuten.de angezeigt.

[.instruction]
Verkaufspreis für Rakuten festlegen:

. Öffnen Sie das Menü *System » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setzen Sie ein Häkchen bei der Herkunft *Rakuten.de*.
. *Speichern* Sie die Einstellungen.

[TIP]
.Ursprüngliche Währung ungleich der Standardwährung
====
Beim Auftragsimport wird zusätzlich die ursprüngliche Währung und der ursprüngliche Betrag in brutto und netto an der Artikelposition gespeichert, wenn die Währung nicht die in plentymarkets eingestellte Standardwährung ist.
====

[#1500]
==  Zahlungsarten aktivieren

Damit Zahlungen für Aufträge von Rakuten durchgeführt und in Ihrem plentymarkets System angezeigt werden, aktivieren Sie die Zahlungsarten *Rakuten Payment*, *Rakuten Rechnung* und *Klarna*.

[.instruction]
Rakuten-Zahlungsarten aktivieren:

.  Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
.  Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *DE* &gt; *Rakuten*.
. Wählen Sie die Rakuten-Zahlungsart. +
→ Das Tab *Einstellungen* wird geöffnet.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<einstellungen-zahlungsart>>.
.  Setzen Sie ein Häkchen bei der Option *Aktiv*.
. *Speichern* Sie die Einstellungen.

[[einstellungen-zahlungsart]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Sprache*
| Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit haben Sie die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzutragen. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|*Name*
| Name eintragen, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
| Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eintragen.

|*Infoseite (Extern)*
| Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eintragen.

|*Lieferländer*
| Kein Lieferland wählen. +
Sie können die Zahlungsart nicht in Ihrem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig konfiguriert.

|*Logo*
| Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standard-Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
| Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
| Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eintragen. *Wichtig*: Nicht in beide Felder einen Wert eintragen. +
Weitere Informationen finden Sie auf der Handbuchseite <<basics/statistik/statistiken-verwalten#, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten finden Sie auf der Handbuchseite <<payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » CRM » Kundenklassen* aktivieren oder deaktivieren Sie *erlaubte Zahlungsarten*. +
Weitere Informationen finden Sie im Kapitel <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

[TIP]
.Zahlungshinweis im Dokument Rechnung für die Zahlungsart Rakuten Rechnung
====
Bei der Zahlungsart Rakuten Rechnung wird die Rechnung an den Kunden direkt durch Rakuten gestellt. Wenn Sie ebenfalls eine Rechnung ausstellen, tragen Sie im Bereich *Optionale Elemente unter Artikelpositionstabelle* einen *Zahlungshinweis* ein, der den Kunden darauf hinweist, dass der Kunde an Rakuten zahlen muss.

*Beispieltext:* +
Aufgrund der Zahlungsabwicklung über die Rakuten GmbH, Geisfelder Str. 16 in 96050 Bamberg, wurde der in dieser Rechnung genannte Forderungsbetrag an diese abgetreten. Wir weisen Sie darauf hin, dass eine schuldbefreiende Leistung (Zahlung) nur an Rakuten möglich ist. Bitte überweisen Sie den Rechnungsbetrag innerhalb von 10 Tagen nach Erhalt der Ware auf das Konto von Rakuten: +
Kontoinhaber: Rakuten GmbH +
IBAN: DE86770200700021511501  +
BIC-/SWIFT-Code: HYVEDEMM411 (HypoVereinsbank ) +
Verwendungszweck 1: Bestellnummer +
Verwendungszweck 2: Vor- und Zuname
====

Weitere Informationen finden Sie auf der Handbuchseite <<payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[#1600]
== Lieferzeiten zuordnen

Rakuten verwendet Standard-Lieferzeiten. Allerdings werden keine Lieferzeiträume, sondern Fristen genannt, die sich an der längsten Lieferzeit orientieren. Versand- und Lieferfristen werden bei Rakuten automatisch anhand der *durchschnittlichen Lieferzeit* zugeordnet. Für eine durchschnittliche Lieferzeit von 2 Tagen als *Artikelverfügbarkeit* gibt es bei Rakuten z.B. keine Entsprechung. Daher wird bei Rakuten dann die nächst größere Versand- und Lieferfrist verwendet.

[[rakuten-lieferzeiten]]
.Rakuten-Lieferzeiten
[cols="1,3"]
|====
|Rakuten-Lieferzeit |Zeitraum

|*0*
|Ab Lager lieferbar (= Lieferzeit 1 bis 3 Werktage)

|*3*
|Versandfertig in 3 Werktagen (= Lieferzeit ca. 3 bis 6 Werktage)

|*5*
|Versandfertig in 5 Werktagen (= Lieferzeit ca. 6 bis 8 Werktage)

|*7*
|Versandfertig in 7 Werktagen (= Lieferzeit ca. 8 bis 10 Werktage)

|*10*
|Versandfertig in 10 Werktagen (= Lieferzeit ca. 10 bis 15 Werktage)

|*15*
|Versandfertig in 15 Werktagen (= Lieferzeit ca. 15 bis 20 Werktage)

|*20*
|Versandfertig in 20 Werktagen (= Lieferzeit ca. 20 bis 30 Werktage)

|*30*
|Versandfertig in 30 Werktagen (= Lieferzeit ca. 30 bis 40 Werktage)

|*40*
|Versandfertig in 40 Werktagen (= Lieferzeit ca. 40 bis 50 Werktage)

|*50*
|Versandfertig in 50 Werktagen (= Lieferzeit ca. 50 bis 60 Werktage)

|*60*
|Versandfertig in 60 Werktagen (= Lieferzeit länger als 3 Monate)
|====

[#170]
== Versandvorbereitung automatisch melden

Richten Sie eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Bestellungen als in Versandvorbereitung zu markieren.  Dadurch können Bestellung für 48 Stunden weder vom Kunden noch vom Rakuten Kundenservice storniert werden. In dieser Zeit können Sie die Bestellung intern bearbeiten und im Anschluss auf versendet aktualisieren.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Tragen Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß <<ereignisaktion-versandvorbereitung-rakuten>>.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß <<ereignisaktion-versandvorbereitung-rakuten>> vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-versandvorbereitung-rakuten]]
.Ereignisaktion zum automatischen Senden von Versandvorbereitungen an Rakuten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Statuswechsel: In Versandvorbereitung*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Rakuten*

|*Aktion*
|*Versand &gt; Versandvorbereitung an Rakuten melden*
|
|====

[#170]
== Versandbestätigungen automatisch senden

Richten Sie eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an Rakuten zu senden, nachdem ein Warenausgang gebucht wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Tragen Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß <<ereignisaktion-versandbestätigung-rakuten>>.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß <<ereignisaktion-versandbestätigung-rakuten>> vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-versandbestätigung-rakuten]]
.Ereignisaktion zum automatischen Senden von Versandbestätigung an Rakuten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Rakuten*

|*Aktion*
|*Versand &gt; Versandbestätigung an Rakuten senden*
|
|====

[#1800]
== Retouren automatisch senden

Richten Sie eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Retouren automatisch an Rakuten zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Tragen Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß <<ereignisaktion-retoure-rakuten>>.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß <<ereignisaktion-retoure-rakuten>> vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-retoure-rakuten]]
.Ereignisaktion zum automatischen Senden von Retouren an Rakuten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Rakuten*

|*Aktion*
|*Retoure &gt; Retoure an Rakuten senden*
|
|====

[#1900]
== Stornierungen automatisch senden

Richten Sie eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Stornierungen automatisch an Rakuten zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Tragen Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß <<ereignisaktion-stornierung-rakuten>>.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß <<ereignisaktion-stornierung-rakuten>> vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-stornierung-rakuten]]
.Ereignisaktion zum automatischen Senden von Stornierungen an Rakuten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel &gt; Storniert*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Rakuten*

|*Aktion*
|*Zahlungsarten &gt; Stornierung an Rakuten senden*
|
|====

[#2000]
== Log und API-Log abrufen

In den Menüs *Daten » Log* und *Daten » API-Log* finden Sie eine Historie über Vorgänge, die über die Rakuten-Schnittstelle ausgeführt wurden. +
Im *Log* finden Sie eine Übersicht über Ereignisaktionen und im *API-Log* finden Sie eine Übersicht über Auftragsimporte.

=== Log abrufen

Öffnen Sie das Menü *Daten » Log*, um eine Übersicht über Ereignisaktionen aufzurufen, die über die Rakuten-Schnittstelle ausgeführt wurden.

[.instruction]
Logeinträge für Rakuten.de aufrufen

. Öffnen Sie das Menü *Daten » Log*.
. Wählen Sie den Identifikator *Rakuten.de* aus der Dropdown-Liste *Identifikator*.
. Wählen Sie ggf. einen Filter aus der Dropdown-Liste *Referenztyp*, um nur Einträge eines bestimmten Referenztyps zu erhalten. Beachten Sie dazu die Erläuterungen in <<tabelle-referenztypen>>.
. Wählen Sie ggf. einen Filter aus der Dropdown-Liste *Referenzwert*, um nur Einträge eines bestimmten Referenzwerts zu erhalten. Beachten Sie dazu die Erläuterungen in <<tabelle-referenztypen>>.
. Wählen Sie ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
. Wählen Sie ggf. eine Uhrzeit, um nur Einträge einer bestimmten Uhrzeit zu erhalten.
. Klicken Sie auf *Suche*.

Nutzen Sie die folgenden Referenztypen und Referenzwerte, um die Suchergebnisse zu filtern.

[[tabelle-referenztypen]]
.Referenztypen und Referenzwerte für Rakuten.de
[cols="1,3,3"]
|====
|Referenztyp |Erläuterung |Referenzwerte

|*action*
|Filtert nach Ereignisaktionen.
|Wählen Sie einen Referenzwert, um nach Ereignisaktionen eines bestimmten Typs zu suchen. +
*SendOrderStatusInLogistics* = Filtert nach Ereignisaktionen des Typs *Versandvorbereitung an Rakuten melden*. +
*SendOrderStatusShipped* = Filtert nach Ereignisaktionen des Typs *Versandbestätigung an Rakuten senden*. +
*SendOrderTrackingData* = Filtert nach Ereignisaktionen des Typs *Sendungsverfolgung an Rakuten senden*. +
*SendOrderStatusCanceled* = Filtert nach Ereignisaktionen des Typs *Stornierung an Rakuten senden*. +
*SendOrderStatusReturned* = Filtert nach Ereignisaktionen des Typs *Retoure an Rakuten senden*.

|*externalOrderId*
|Filtert nach Einträgen zu einer spezifischen externen Auftrags-ID.
|

|*orderId*
|Filtert nach Einträgen zu einer spezifischen Auftrags-ID.
|
|====

=== API-Log abrufen

Öffnen Sie das Menü *Daten » API-Log » Tab: API-Log*, um eine Übersicht über Auftragsimporte zu erhalten, die über die Rakuten-Schnittstelle ausgeführt wurden. Das Format *Rakuten* steht Ihnen für Rakuten zur Verfügung.

[.instruction]
API-Log abrufen:

. Öffnen Sie das Menü *Daten » API-Log » Tab: API-Log*.
. Wählen Sie das Format *Rakuten* aus der Dropdown-Liste *Vorgang*.
. Wählen Sie ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
. Wählen Sie die Anzahl der Ergebnisse pro Seite.
. Klicken Sie auf *Suchen*, um die Ergebnisse anzuzeigen.

[#2100]
== FAQ

[.instruction]
Wie wird der Warenbestand in plentymarkets mit Rakuten.de abgeglichen?

[.indented]
Wenn bei Rakuten.de der automatische CSV-Import eingerichtet ist, werden die neuen Warenbestände durch den erneuten Import der CSV-Datei abgeglichen. Wie oft der Warenbestand abgeglichen wird, stellen Sie im Backend bei Rakuten.de ein.
