= Rakuten einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Rakuten, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz Rakuten in deinem plentymarkets System ein.
:position: 10
:url: maerkte/rakuten/rakuten-einrichten

plentymarkets bietet dir die Möglichkeit, deine Artikel auf der Plattform Rakuten.de zu verkaufen.

[#100]
== Bei Rakuten registrieren

Bevor du Rakuten in plentymarkets einrichtest, musst du dich bei Rakuten registrieren. Die Registrierungsformulare findest du unter link:http://leadgen.rakuten.de/form?leadsource=marketplace_header[rakuten.de^].

[#200]
==  Rakuten.de in plentymarkets einrichten

Nimm die folgenden Einstellungen in plentymarkets vor, um die Schnittstelle zu Rakuten.de einzurichten.

[.instruction]
Rakuten.de einrichten:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Rakuten » Einstellungen*. +
→ Das Tab *Neues Konto* wird angezeigt.
. Klappe *Rakuten-Einstellungen* auf.  +
→ Die Plattform *rakuten.de* ist vorausgewählt.
. Trage den *Authentifizierungsschlüssel* ein. +
→ Den Schlüssel findest du im Backend deines Rakuten.de-Kontos.
. Nimm die Einstellungen gemäß <<einstellungen-rakuten>> vor.
. *Speichere* die Einstellungen.
. Lade das Menü neu.  +
→ Das Konto wurde angelegt und die Einstellungen für die Plattform geladen.

Wenn du mehrere Konten bei Rakuten.de hast, benötigst du für jedes Konto einen Authentifizierungsschlüssel.

[[einstellungen-rakuten]]
.Rakuten einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Auftragsimport

|*Aktivieren*
|*Deaktivieren* = Schnittstelle ist inaktiv. +
*Aktivieren* = Schnittstelle ist aktiv. Neue Aufträge werden automatisch einmal pro Stunde abgerufen. Versendete Aufträge werden automatisch jede Stunde an Rakuten übermittelt.

|*Zahlung*
|*Zahlungseingang offen* = Aufträge als unbezahlt importieren. +
*Zahlungseingang gebucht* = Aufträge werden als unbezahlt importiert. Somit kann eine Kontrolle von Rakuten erfolgen. Bei Zahlungseingang von Rakuten wird der Auftrag auf bezahlt gesetzt. +
Unabhängig von der gewählten Option werden Artikel bei ausreichendem Bestand sofort für den Versand freigegeben.

|*Auftragsbestätigung senden*
|*Deaktivieren* = Keine Auftragsbestätigung übermitteln. +
*Aktivieren* = Auftragsbestätigung an Kund*innen übermitteln. Die unter *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Automatischer Versand* eingetragene E-Mail-Vorlage wird an Kund*innen versendet.

|*API-Log einsehen*
|Zum Abrufen des API-Logs auf *API-Log einsehen* klicken.
|====

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

* stündlicher Auftragsabgleich

Folgende Prozesse werden durch das link:https://marketplace.plentymarkets.com/plugins/markets/ElasticExportRakutenDE_4721[ElasticExportRakutenDE-Plugin^] abgebildet:

* stündlicher Bestandsabgleich
* stündlicher Preisabgleich

Mit dem *ElasticExportRakutenDE-Plugin* kannst du das Datenformat *RakutenDE-Plugin* für den elastischen Export nutzen. Das Plugin ist im link:https://marketplace.plentymarkets.com/plugins/markets[plentyMarketplace^] erhältlich. Weitere Informationen zur Einrichtung des Plugins findest du im User Guide des Plugins.

[#250]
=== Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit Rakuten verknüpfen kannst, muss im Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft* die Auftragsherkunft Rakuten aktiviert werden.

[.instruction]
Auftragsherkunft für Rakuten aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft*.
. Setze bei *Rakuten* ein Häkchen.
. *Speichere* die Einstellungen.

[#300]
=== Artikelverfügbarkeit einstellen

Artikel, die du auf Rakuten.de verkaufen möchtest, müssen im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Rakuten.de einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *Rakuten.de*.
. Klicke auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* die Einstellungen. +
→ Der Artikel ist auf Rakuten.de verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden.

[#350]
===  SKU für eine Herkunft festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügst du marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *Rakuten.de*.
. Wähle das dazugehörige Marktplatzkonto.
. Gib die SKU ein.
. Klicke auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

[#400]
=== Kategorien verknüpfen

Nachdem du den Artikel verfügbar gemacht hast, verknüpfe den Artikel mit einer Rakuten-Kategorie.

[.instruction]
Kategorie verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Multi-Channel*.
. Wähle aus der Dropdown-Liste *Rakuten.de* im Bereich *Kategorieverknüpfung* die Hauptkategorie für den Artikel. +
→ Ein Fenster zur weiteren Kategorieauswahl wird geöffnet.
. Wähle die Unterkategorien bis zur untersten Kategorie. +
→ Eine Kategorienummer wird angezeigt.
. Klicke auf *Übernehmen*. +
→ Die Kategorieverknüpfung wird durch die Kategorienummer und die Rakuten-Kategorie angezeigt.
. *Speichere* die Einstellungen.

[#500]
=== Versandgruppen mit Artikeln verknüpfen

Versandprofile werden direkt bei Rakuten eingerichtet. Die am Artikel gespeicherten Versandprofile werden nicht an Rakuten übertragen. Versandprofile werden bei Rakuten als Versandgruppen bezeichnet. Diese Versandgruppen verknüpfst du per *Freitextfeld* mit deinen Artikeln.

[.instruction]
Freitextfeld für Versandgruppe einrichten:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Freitextfelder*.
. Füge eine Feldbezeichnung, z.B. *Rakuten-Versandgruppe*, in eines der Freitextfelder ein.
. *Speichere* die Einstellungen. +
→ Hinweis: Freitextfelder werden über Nacht aktiviert und sind am nächsten Morgen verfügbar.
. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Trage bei jedem Artikel, der übertragen werden soll, im Tab *Felder* die *Ziffer der Versandgruppe* ein.
. *Speichere* die Einstellungen.
. Teile Rakuten das verwendete Freitextfeld mit.

[TIP]
.Kein Freitextfeld übermittelt
====
Wenn kein Freitextfeld an Rakuten übermittelt wird, wird der Artikel automatisch mit der Versandgruppe 1 verknüpft.
====

Weitere Lieferländer stellst du ebenfalls bei Rakuten ein.

[#600]
=== Energieeffizienz angeben

Die EU-Verordnung zur Energieeffizienzrichtlinie schreibt für die Auszeichnung deiner Artikel seit 01.01.2015 Angaben zur Energieeffizienz sowie die Bereitstellung von Produktdatenblättern vor. Diese Informationen sind auch an Rakuten zu übermitteln. Erstelle dazu die <<artikel/artikel-verwalten#480, Merkmale>>:

* *Energieeffizienzklasse* +
Merkmal-Typ: *Kein*
* *Energieeffizienzklasse bis* +
Merkmal-Typ: *Kein* +

* *Energieeffizienzklasse-Gerätegruppe* +
Merkmal-Typ: *Kein*

Für jede Energieeffizienzklasse von A+++ bis G muss ein eigenes Merkmal angelegt werden.

[.instruction]
Merkmal anlegen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Merkmale*.
. Öffne das Tab *Neues Merkmal*.
. Trage unter *Name (intern)* einen Namen für das Merkmal ein.
. Wähle aus der Dropdown-Liste im Feld *Merkmaltyp* die Option *Kein*.
. Wähle aus der Dropdown-Liste im Feld *Rakuten.de-Merkmal* das Rakuten-Merkmal.
. *Speichere* die Einstellungen.

Die Merkmale verknüpfst du im Tab <<artikel/artikel-verwalten#480, Merkmale>> eines Artikels.

Das Produktdatenblatt stellst du für Rakuten in elektronischer Form über einen Link in der Artikelbeschreibung zur Verfügung. Füge den Link zum Produktdatenblatt im Tab <<artikel/artikel-verwalten#50, Texte>> eines Artikels ein. Gehe wie im Folgenden beschrieben vor.

[.instruction]
Produktdatenblatt in der Artikelbeschreibung speichern:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Lade das Produktdatenblatt im Tab *Bilder* des Artikels hoch.
. Kopiere die URL des Bildes.
. Füge den Link zum Produktdatenblatt im Tab *Texte* des Artikels ein.
. *Speichere* die Einstellungen.

[#700]
=== Artikelexport einrichten

In diesem Kapitel wird beschrieben, wie du deine Artikel zu Rakuten.de überträgst. Artikel werden über den elastischen Export mit dem Datenformat RakutenDE zu Rakuten.de exportiert. Dafür müssen zuvor die Plugins *ElasticExport* und *ElasticExportRakutenDE* installiert worden sein. Lege zunächst das Datenformat RakutenDE an und übermittele im Anschluss die URL zu Rakuten.

[IMPORTANT]
.Für die Einrichtung Rakuten kontaktieren
====
Für das Einrichten des Imports muss Rakuten kontaktiert werden.
====

[.instruction]
Artikelexport einrichten:

. Öffne das Menü *Daten » Elastischer Export*.
. Klicke auf *Neuer Export*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<einstellungen-artikelexport>>.
. Nimm die weiteren Einstellungen für Artikelfilter und Formateinstellungen vor. Beachte dazu die Erläuterungen in Tabelle 5 auf der Handbuchseite <<daten/export-import/daten-exportieren#60, Daten über dynamischen Export exportieren>>.
. *Speichere* die Einstellungen. +
→ Eine ID für das Exportformat wird vergeben und das Exportformat erscheint in der Übersicht *Exporte*.

[[einstellungen-artikelexport]]
.Einstellungen für Artikelexport
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Einstellungen

|*Name*
|Name eingeben. Unter diesem Namen erscheint das Exportformat in der Übersicht im Tab *Exporte*.

|*Typ*
|Typ *Artikel* aus der Dropdown-Liste wählen.

|*Format*
|Format *RakutenDE* aus der Dropdown-Liste wählen.

|*Limit*
|Zahl eingeben. Wenn mehr als 10000 Datensätze an rakuten.de übertragen werden sollen, wird die Ausgabedatei für 24 Stunden nicht noch einmal neu generiert, um Ressourcen zu sparen.

|*Cache-Datei generieren*
|Häkchen setzen, wenn mehr als 9999 Datensätze an Rakuten.de übertragen werden sollen. Um eine optimale Performance des elastischen Exports zu gewährleisten, darf diese Option bei maximal 20 Exportformaten aktiv sein.

|*Bereitstellung*
|*URL* wählen.

|*Dateiname*
|Der Dateiname muss auf *.csv* enden, damit Rakuten.de die Datei erfolgreich importieren kann.

|*Token*, +
*URL*
|Wenn unter *Bereitstellung* die Option *URL* gewählt wurde, auf *Token generieren* klicken. Der Token wird dann automatisch eingetragen. Die URL wird automatisch eingetragen, wenn unter *Token* der Token generiert wurde. Diese URL an Rakuten.de übergeben, damit die Artikel exportiert werden.

2+|Formateinstellungen

|*Produkt-URL*
|Wählen, ob die URL des Artikels oder der Variante an Rakuten.de übertragen wird. Varianten URLs können nur in Kombination mit dem Ceres Webshop übertragen werden.

|*Mandant*
|Mandanten wählen. Diese Einstellung wird für den URL-Aufbau verwendet.

|*URL-Parameter*
|Suffix für die Produkt-URL eingeben, wenn ein Suffix für den Export erforderlich ist. Die Produkt-URL wird dann um die eingegebene Zeichenkette erweitert, wenn weiter oben die Option *übertragen* für die Produkt-URL aktiviert wurde.

|*Auftragsherkunft*
|*Rakuten.de* wählen.

|*Marktplatzkonto*
|Wenn Artikeldaten zum ersten Mal exportiert werden, wird das hier gewählte Konto für die Generierung der SKU berücksichtigt.

|*Sprache*
|Sprache aus der Dropdown-Liste wählen.

|*Artikelname*
|Name 1, Name 2 oder Name 3 wählen. Die Namen sind im Tab *Texte* eines Artikels gespeichert. Im Feld *Maximale Zeichenlänge (def. Text)* optional eine Zahl eingeben, wenn Rakuten.de eine Begrenzung der Länge des Artikelnamen beim Export vorgibt.

|*Vorschautext*
|Diese Option ist für Rakuten.de nicht relevant.

|*Beschreibung*
|Wählen, welcher Text als Beschreibungstext übertragen werden soll. +
Im Feld *Maximale Zeichenlänge (def. Text)* optional eine Zahl eingeben, wenn Rakuten.de eine Begrenzung der Länge der Beschreibung beim Export vorgibt. +
Option *HTML-Tags entfernen* aktivieren, damit die HTML-Tags beim Exportieren entfernt werden. +
Im Feld *Erlaubte HTML-Tags, kommagetrennt (def. Text)* optional die HTML-Tags eingeben, die beim Export erlaubt sind. Wenn mehrere Tags eingegeben werden, mit Komma trennen.

|*Zielland*
|Zielland aus der Dropdown-Liste wählen.

|*Barcode*
|ISBN oder eine EAN aus der Dropdown-Liste wählen. Der gewählte Barcode muss mit der oben gewählten Auftragsherkunft verknüpft sein. Andernfalls wird der Barcode nicht exportiert.

|*Bild*
|*Position 0* oder *Erstes Bild* wählen, um dieses Bild zu exportieren. +
*Position 0* = Ein Bild mit der Position 0 wird übertragen. +
*Erstes Bild* = Das erste Bild wird übertragen.

|*Bildposition des Energieetiketts*
|Position des Energieetiketts eintragen. Alle Bilder, die als Energieetikette übertragen werden sollen, müssen diese Position haben.

|*Bestandspuffer*
|Der Bestandspuffer für Varianten mit der Beschränkung auf den Netto-Warenbestand. Zahl eingeben. Die eingegebene Menge wird vom Bestand abgezogen.

|*Bestand für Varianten ohne Bestandsbeschränkung*
|Der Bestand für Varianten ohne Bestandsbeschränkung.

|*Bestand für Varianten ohne Bestandsführung*
|Der Bestand für Varianten ohne Bestandsführung.

|*Währung live umrechnen*
|Aktivieren, damit der Preis je nach eingestelltem Lieferland in die Währung des Lieferlandes umgerechnet wird. Der Preis muss für die entsprechende Währung freigegeben sein.

|*Verkaufspreis*
|Brutto- oder Nettopreis aus der Dropdown-Liste wählen.

|*Angebotspreis*
|Aktivieren, um den Angebotspreis zu übertragen.

|*UVP*
|Aktivieren, um den UVP zu übertragen.

|*Versandkosten*
|Aktivieren, damit die Versandkosten aus der Konfiguration übernommen werden. Wenn die Option aktiviert ist, stehen in den beiden Dropdown-Listen Optionen für die Konfiguration und die Zahlungsart zur Verfügung. +
Option *Pauschale Versandkosten übertragen* aktivieren, damit die pauschalen Versandkosten übertragen werden. Wenn diese Option aktiviert ist, muss im Feld darunter ein Betrag eingegeben werden.

|*MwSt.-Hinweis*
|Text eingeben. Dieser Betrag enthält die Mehrwertsteuer zuzüglich Versand.

|*Artikelverfügbarkeit*
|Option *überschreiben* aktivieren und in die Felder *1* bis *10*, die die ID der Verfügbarkeit darstellen, Artikelverfügbarkeiten eintragen. Somit werden die Artikelverfügbarkeiten, die im Menü *System » Systemeinstellungen » Artikel » Verfügbarkeit* eingestellt wurden, überschrieben.
|====

[IMPORTANT]
.Exportinformationen
====
Wenn du eine oder mehrere Einstellungen änderst, musst du den neuen Link an Rakuten übergeben.

Pro Export werden maximal 4000 Artikel exportiert. Wenn du mehr Artikel exportierst, wird automatisch ein zweiter Export ausgeführt. Um den zweiten Export anzuzeigen, setze den Parameter *&amp;Page* = im Export-Link auf *2*.

Technische Daten werden in der letzten Spalte der Exportdatei an Rakuten übergeben.
====

==== Lieferzeiten überschreiben

Rakuten erwartet bei der Lieferzeit vordefinierte Werte. Du kannst z.B. nicht die Werte 1 oder 2 als Lieferzeit übermitteln, da der Export in diesem Fall mit einem Fehler abgelehnt wird.
Deshalb musst du die Lieferzeit im elastischen Export für Rakuten überschreiben. Der folgenden Liste entnimmst du die Bedeutungen der Rakuten-Lieferzeiten und ordnest diese deinen Artikelverfügbarkeiten zu. Wenn die Artikelverfügbarkeit ID 1 in deinem System bedeutet, dass die Ware auf Lager ist und innerhalb der nächsten 1-3 Werktage geliefert wird, dann überschreibe im elastischen Export die Artikelverfügbarkeit ID 1 mit der Liefezeit 0.

* 0 = Ab Lager lieferbar (= Lieferzeit 1-3 Werktage)
* 3 = versandfertig in 3 Werktagen (= Lieferzeit ca. 3 - 6 Werktage)
* 5 = versandfertig in 5 Werktagen (= Lieferzeit ca. 6 - 8 Werktage)
* 7 = versandfertig in 7 Werktagen (= Lieferzeit ca. 8 - 10 Werktage)
* 10 = versandfertig in 10 Werktagen (= Lieferzeit ca. 10 - 15 Werktage)
* 15 = versandfertig in 15 Werktagen (= Lieferzeit ca. 15 - 20 Werktage)
* 20 = versandfertig in 20 Werktagen (= Lieferzeit ca. 20 - 30 Werktage)
* 30 = versandfertig in 30 Werktagen (= Lieferzeit ca. 30 - 40 Werktage)
* 40 = versandfertig in 40 Werktagen (= Lieferzeit ca. 40 - 50 Werktage)
* 50 = versandfertig in 50 Werktagen (= Lieferzeit ca. 50 - 60 Werktage)
* 60 = versandfertig in 60 Werktagen (= Lieferzeit länger als 3 Monate)

Du findest die Werte für Lieferzeiten auch in der link:http://doku.rakuten.de/doku.php/neuer_import/start[Schnittstellendokumentation^] von Rakuten.

==== Präfix und Suffix zu Parent-SKUs hinzufügen

Wenn du das link:https://marketplace.plentymarkets.com/plugins/markets/ElasticExportRakutenDE_4721[ElasticExportRakutenDE-Plugin^] in deinem plentymarkets System installiert hast, hast du die Möglichkeit, Parent-SKUs um Präfixe und Suffixe zu erweitern. Dadurch vermeidest du, dass die Parent-SKU und die zugehörigen Child-SKUs identisch sind und deshalb bei Rakuten als der gleiche Artikel angegeben werden.

Präfixe und Suffixe werden im Menü *Plugins » Plugin-Übersicht »  ElasticExportRakutenDE » Konfiguration » Parent-SKU* hinzugefügt.

[.instruction]
Präfixe und Suffixe hinzufügen:

. Öffne das Menü *Plugins » Plugin-Übersicht*.
. Klicke auf das *ElasticExportRakutenDE*-Plugin.
. Gehe zu *Konfiguration » Parent-SKU*.
. Gib in die Felder *Präfix* und *Suffix* Präfix und Suffix ein wie benötigt.
. *Speichere* die Einstellungen. +
→ Die eingegebenen Präfixe und Suffixe werden nun zu Parent-SKUs hinzugefügt, die du neu generierst.

[TIP]
.Alphanumerische Zeichen verwenden
====
Wir empfehlen, für die Präfixe und Suffixe nur Buchstaben und Ziffern zu verwenden. Vermeide Umlaute. Die Verwendung von Umlauten kann zu Problemen beim Datenaustausch führen.
====

[IMPORTANT]
.Änderungen gelten nur für neu generierte SKUs
====
Beachte, dass Präfix und Suffix nur zu den Parent-SKUs hinzugefügt werden, die du neu für Rakuten.de generierst, nachdem diese Einstellung gespeichert wurde. Bereits bestehende Parent-SKUs für Rakuten.de werden nicht berücksichtigt. Füge die Präfixe und Suffixe manuell für diese SKUs hinzu, wenn gewünscht.
====

[#800]
=== Preisabgleich einrichten

In diesem Kapitel erfährst du, wie du den Preisabgleich für Rakuten aktivierst. Preise werden über den elastischen Export mit dem Datenformat RakutenDE-Plugin mit Rakuten abgeglichen. Dafür müssen zuvor die Plugins *ElasticExport* und *ElasticExportRakutenDE* installiert worden sein. +
Preise werden stündlich abgeglichen.

[.instruction]
Preisabgleich aktivieren:

. Öffne das Menü *Plugins » Plugin-Übersicht*.
. Klicke auf das *ElasticExportRakutenDE*-Plugin.
. Gehe zu *Konfiguration » Update-Einstellungen*.
. Setze ein Häkchen bei *Preis-Update*.
. *Speichere* die Einstellungen.

[IMPORTANT]
.Anfrage zum Preis- und Bestandsabgleich
====
Falls die Anfragen an die Rakuten-Schnittstelle 5mal hintereinander unbeantwortet bleiben, wird der Preis- und Bestandsabgleich abgebrochen.
====

[#900]
=== Bestandsabgleich einrichten

In diesem Kapitel erfährst du, wie du den Bestandsabgleich für Rakuten aktivierst. Bestände werden über den elastischen Export mit dem Datenformat RakutenDE-Plugin mit Rakuten abgeglichen. Dafür müssen zuvor die Plugins *ElasticExport* und *ElasticExportRakutenDE* installiert worden sein. +
Bestände werden stündlich abgeglichen.

[.instruction]
Bestandsabgleich aktivieren:

. Öffne das Menü *Plugins » Plugin-Übersicht*.
. Klicke auf das *ElasticExportRakutenDE*-Plugin.
. Gehe zu *Konfiguration » Update-Einstellungen*.
. Setze ein Häkchen bei *Bestands-Update*.
. *Speichere* die Einstellungen.

[IMPORTANT]
.Anfrage zum Preis- und Bestandsabgleich
====
Falls die Anfragen an die Rakuten-Schnittstelle 5mal hintereinander unbeantwortet bleiben, wird der Preis- und Bestandsabgleich abgebrochen.
====

[#1400]
== Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft Rakuten.de einen Verkaufspreis festzulegen. Dieser Preis wird auf Rakuten.de angezeigt.

[.instruction]
Verkaufspreis für Rakuten festlegen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze ein Häkchen bei der Herkunft *Rakuten.de*.
. *Speichere* die Einstellungen.

[TIP]
.Ursprüngliche Währung ungleich der Standardwährung
====
Beim Auftragsimport wird zusätzlich die ursprüngliche Währung und der ursprüngliche Betrag in brutto und netto an der Artikelposition gespeichert, wenn die Währung nicht die in plentymarkets eingestellte Standardwährung ist.
====

[#1500]
==  Zahlungsarten aktivieren

Damit Zahlungen für Aufträge von Rakuten durchgeführt und in deinem plentymarkets System angezeigt werden, aktiviere die Zahlungsarten *Rakuten Payment*, *Rakuten Rechnung* und *Klarna*.

[.instruction]
Rakuten-Zahlungsarten aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *DE* &gt; *Rakuten*.
. Wähle die Rakuten-Zahlungsart. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<einstellungen-zahlungsart>>.
. Setze ein Häkchen bei der Option *Aktiv*.
. *Speichere* die Einstellungen.

[[einstellungen-zahlungsart]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Sprache*
| Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit hast du die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzutragen. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|*Name*
| Name eintragen, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
| Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eintragen.

|*Infoseite (Extern)*
| Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eintragen.

|*Lieferländer*
| Kein Lieferland wählen. +
Du kannst die Zahlungsart nicht in deinem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig eingerichtet.

|*Logo*
| Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standard-Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
| Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
| Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eintragen. *Wichtig*: Nicht in beide Felder einen Wert eintragen. +
Weitere Informationen findest du auf der Handbuchseite <<basics/statistik/statistiken-verwalten#, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » Systemeinstellungen » CRM » Kundenklassen* aktivierst oder deaktivierst du *erlaubte Zahlungsarten*. +
Weitere Informationen findest du im Kapitel <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

[TIP]
.Zahlungshinweis im Dokument Rechnung für die Zahlungsart Rakuten Rechnung
====
Bei der Zahlungsart Rakuten Rechnung wird die Rechnung an Kund*innen direkt durch Rakuten gestellt. Wenn du ebenfalls eine Rechnung ausstellst, trage im Bereich *Optionale Elemente unter Artikelpositionstabelle* einen *Zahlungshinweis* ein, der Kund*innen darauf hinweist, dass die Zahlung an Rakuten erfolgen muss.

*Beispieltext:* +
Aufgrund der Zahlungsabwicklung über die Rakuten GmbH, Geisfelder Str. 16 in 96050 Bamberg, wurde der in dieser Rechnung genannte Forderungsbetrag an diese abgetreten. Wir weisen Sie darauf hin, dass eine schuldbefreiende Leistung (Zahlung) nur an Rakuten möglich ist. Bitte überweisen Sie den Rechnungsbetrag innerhalb von 10 Tagen nach Erhalt der Ware auf das Konto von Rakuten: +
Kontoinhaber: Rakuten GmbH +
IBAN: DE86770200700021511501  +
BIC-/SWIFT-Code: HYVEDEMM411 (HypoVereinsbank ) +
Verwendungszweck 1: Bestellnummer +
Verwendungszweck 2: Vor- und Zuname
====

Weitere Informationen findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[#1600]
== Lieferzeiten zuordnen

Rakuten verwendet Standard-Lieferzeiten. Allerdings werden keine Lieferzeiträume, sondern Fristen genannt, die sich an der längsten Lieferzeit orientieren. Versand- und Lieferfristen werden bei Rakuten automatisch anhand der *durchschnittlichen Lieferzeit* zugeordnet. Für eine durchschnittliche Lieferzeit von 2 Tagen als *Artikelverfügbarkeit* gibt es bei Rakuten z.B. keine Entsprechung. Daher wird bei Rakuten dann die nächst größere Versand- und Lieferfrist verwendet.

[[rakuten-lieferzeiten]]
.Rakuten-Lieferzeiten
[cols="1,3"]
|====
|Rakuten-Lieferzeit |Zeitraum

|*0*
|Ab Lager lieferbar (= Lieferzeit 1 bis 3 Werktage)

|*3*
|Versandfertig in 3 Werktagen (= Lieferzeit ca. 3 bis 6 Werktage)

|*5*
|Versandfertig in 5 Werktagen (= Lieferzeit ca. 6 bis 8 Werktage)

|*7*
|Versandfertig in 7 Werktagen (= Lieferzeit ca. 8 bis 10 Werktage)

|*10*
|Versandfertig in 10 Werktagen (= Lieferzeit ca. 10 bis 15 Werktage)

|*15*
|Versandfertig in 15 Werktagen (= Lieferzeit ca. 15 bis 20 Werktage)

|*20*
|Versandfertig in 20 Werktagen (= Lieferzeit ca. 20 bis 30 Werktage)

|*30*
|Versandfertig in 30 Werktagen (= Lieferzeit ca. 30 bis 40 Werktage)

|*40*
|Versandfertig in 40 Werktagen (= Lieferzeit ca. 40 bis 50 Werktage)

|*50*
|Versandfertig in 50 Werktagen (= Lieferzeit ca. 50 bis 60 Werktage)

|*60*
|Versandfertig in 60 Werktagen (= Lieferzeit länger als 3 Monate)
|====

[#170]
== Versandvorbereitung automatisch melden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Bestellungen als in Versandvorbereitung zu markieren.  Dadurch können Bestellungen für 48 Stunden weder von Kund*innen noch vom Rakuten Kundenservice storniert werden. In dieser Zeit kannst du die Bestellung intern bearbeiten und im Anschluss auf versendet aktualisieren.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-versandvorbereitung-rakuten>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-versandvorbereitung-rakuten>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-versandvorbereitung-rakuten]]
.Ereignisaktion zum automatischen Senden von Versandvorbereitungen an Rakuten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Statuswechsel: In Versandvorbereitung*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Rakuten*

|*Aktion*
|*Versand &gt; Versandvorbereitung an Rakuten melden*
|
|====

[#170]
== Versandbestätigungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an Rakuten zu senden, nachdem ein Warenausgang gebucht wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-versandbestätigung-rakuten>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-versandbestätigung-rakuten>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-versandbestätigung-rakuten]]
.Ereignisaktion zum automatischen Senden von Versandbestätigung an Rakuten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Rakuten*

|*Aktion*
|*Versand &gt; Versandbestätigung an Rakuten senden*
|
|====

[#1800]
== Retouren automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Retouren automatisch an Rakuten zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-retoure-rakuten>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-retoure-rakuten>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-retoure-rakuten]]
.Ereignisaktion zum automatischen Senden von Retouren an Rakuten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Rakuten*

|*Aktion*
|*Retoure &gt; Retoure an Rakuten senden*
|
|====

[#1900]
== Stornierungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Stornierungen automatisch an Rakuten zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-stornierung-rakuten>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-stornierung-rakuten>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-stornierung-rakuten]]
.Ereignisaktion zum automatischen Senden von Stornierungen an Rakuten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel &gt; Storniert*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Rakuten*

|*Aktion*
|*Zahlungsarten &gt; Stornierung an Rakuten senden*
|
|====

[#2000]
== Log und API-Log abrufen

In den Menüs *Daten » Log* und *Daten » API-Log* findest du eine Historie über Vorgänge, die über die Rakuten-Schnittstelle ausgeführt wurden. +
Im *Log* findest du eine Übersicht über Ereignisaktionen und im *API-Log* findest du eine Übersicht über Auftragsimporte.

=== Log abrufen

Öffne das Menü *Daten » Log*, um eine Übersicht über Ereignisaktionen aufzurufen, die über die Rakuten-Schnittstelle ausgeführt wurden.

[.instruction]
Logeinträge für Rakuten.de aufrufen

. Öffne das Menü *Daten » Log*.
. Wähle den Identifikator *Rakuten.de* aus der Dropdown-Liste *Identifikator*.
. Wähle ggf. einen Filter aus der Dropdown-Liste *Referenztyp*, um nur Einträge eines bestimmten Referenztyps zu erhalten. Beachte dazu die Erläuterungen in <<tabelle-referenztypen>>.
. Wähle ggf. einen Filter aus der Dropdown-Liste *Referenzwert*, um nur Einträge eines bestimmten Referenzwerts zu erhalten. Beachte dazu die Erläuterungen in <<tabelle-referenztypen>>.
. Wähle ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
. Wähle ggf. eine Uhrzeit, um nur Einträge einer bestimmten Uhrzeit zu erhalten.
. Klicke auf *Suche*.

Nutze die folgenden Referenztypen und Referenzwerte, um die Suchergebnisse zu filtern.

[[tabelle-referenztypen]]
.Referenztypen und Referenzwerte für Rakuten.de
[cols="1,3,3"]
|====
|Referenztyp |Erläuterung |Referenzwerte

|*action*
|Filtert nach Ereignisaktionen.
|Wähle einen Referenzwert, um nach Ereignisaktionen eines bestimmten Typs zu suchen. +
*SendOrderStatusInLogistics* = Filtert nach Ereignisaktionen des Typs *Versandvorbereitung an Rakuten melden*. +
*SendOrderStatusShipped* = Filtert nach Ereignisaktionen des Typs *Versandbestätigung an Rakuten senden*. +
*SendOrderTrackingData* = Filtert nach Ereignisaktionen des Typs *Sendungsverfolgung an Rakuten senden*. +
*SendOrderStatusCanceled* = Filtert nach Ereignisaktionen des Typs *Stornierung an Rakuten senden*. +
*SendOrderStatusReturned* = Filtert nach Ereignisaktionen des Typs *Retoure an Rakuten senden*.

|*externalOrderId*
|Filtert nach Einträgen zu einer spezifischen externen Auftrags-ID.
|

|*orderId*
|Filtert nach Einträgen zu einer spezifischen Auftrags-ID.
|
|====

=== API-Log abrufen

Öffne das Menü *Daten » API-Log » Tab: API-Log*, um eine Übersicht über Auftragsimporte zu erhalten, die über die Rakuten-Schnittstelle ausgeführt wurden. Das Format *Rakuten* steht dir für Rakuten zur Verfügung.

[.instruction]
API-Log abrufen:

. Öffne das Menü *Daten » API-Log » Tab: API-Log*.
. Wähle das Format *Rakuten* aus der Dropdown-Liste *Vorgang*.
. Wähle ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
. Wähle die Anzahl der Ergebnisse pro Seite.
. Klicke auf *Suchen*, um die Ergebnisse anzuzeigen.

[#2100]
== FAQ

[.instruction]
Wie wird der Warenbestand in plentymarkets mit Rakuten.de abgeglichen?

[.indented]
Wenn bei Rakuten.de der automatische CSV-Import eingerichtet ist, werden die neuen Warenbestände durch den erneuten Import der CSV-Datei abgeglichen. Wie oft der Warenbestand abgeglichen wird, stellst du im Backend bei Rakuten.de ein.
