= plentymarkets POS for POS users
:lang: en
include::{includedir}/_header.adoc[]
:keywords: plentymarkets POS, point of sale, POS, plentymarkets POS, Pos user
:position: 20

////
p>Noch beschreiben:</p>

<ul>
<li>Artikel oder Variante???</li>
<li>Wie setzt sich die Belegnummer zusammen?</li>
<li>Preis bearbeiten</li>
<li>Dummy-Artikel, wenn Artikel nicht gefunden wird</li>
<li>Favoriten in der App anlegen</li>
<li>Umbuchen</li>
<li>Warenbestand prüfen</li>
<li>(Kasse sperren)</li>
<li>(Artikel synchronisieren)</li>
<li>(Aufträge hochladen)</li>
</ul
////

[#5]
== Installing the plentymarkets app

To get started, install the plentymarkets App on your mobile device.

* **link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=en[plentymarkets App in Google Play, window="_blank"]**

* **link:https://itunes.apple.com/app/plentymarkets/id957702618[plentymarkets App in iTunes, window="_blank"]**

[WARNING]
.Offline orders are deleted when you uninstall the app
====
If your internet connection is down, POS orders are saved on your device and uploaded to plentymarkets once connection returns. If you uninstall the app on your device before all orders were uploaded to plentymarkets, the orders saved on your device will be deleted permanently and cannot be recovered by you or the plentymarkets support team. As such, check that no offline orders exist on your device before uninstalling the app.
====

[#10]
== Logging into plentymarkets POS

Proceed as described below to log into plentymarkets POS.

[.instruction]
Logging into plentymarkets POS:

. Log into your mobile device.
. On the start screen, tap the plentymarkets App icon. +
→ The login screen is displayed.
. Enter your login details. Pay attention to the explanations given in table 1.
. Tap **Log in**. +
→ The start screen of the plentymarkets App is displayed.
. Tap the menu symbol at the top left of the screen. +
→ The menu is displayed.
. Tap **POS**. +
→ plentymarkets POS opens.

[TIP]
.Login details are saved
====
You will remain logged in to plentymarkets POS until you tap **Log out** in the app menu. That means that you can open and close the apps without having to log in again.
====

.Login
[cols="1,2"]
|====
|Setting |Explanation

|Language
|Select the language in which you want to use plentymarkets POS. Currently, the user interface of plentymarkets POS is available in English or German.

|**System (base URL)**
|Enter the domain of the plentymarkets system without https:// or http://, e.g. **your-shop.co.uk**.

|**User**; **Password**
|Enter the user name and password for the plentymarkets system.
|====

[#30]
== Selling items

Once you open plentymarkets POS, the POS menu is displayed. Tap **POS** to open the POS shopping cart and add items.

[#40]
=== Adding items to the POS shopping cart

You can add items to the current plentymarkets POS order by searching the items, opening the list of favourites or by scanning the label of an item.

[#50]
==== Searching for items

Use the item search to access all items of this client. You can search for items using the following item data:

* Item ID
* Variation number
* Barcode
* Item name
* Variation ID
* Supplier item No.

Proceed as described below to add items to the POS shopping cart by using the item search.

[.instruction]
Adding items using the item search:

. In the POS shopping cart, tap the magnifying glass. +
→ The item search opens.
. Enter a search criterion.
. Tap **Search**. +
→ A list of items matching the search criteria is displayed.
. Tap the green check mark to add an item to the shopping cart. +
→ The **Enter quantity** window is displayed.
. Enter the quantity for the item that you want to add to the shopping cart. +
→ The item is added to the shopping cart and the current order sum is updated. +
→ **__Tip:__** Items with no net stock are shown in red but can be sold.

[#60]
==== Opening the list of favourites

Quickly add favourite items to the POS shopping basket by accessing them through the favourites list. plentymarkets administrators can create a list of favourite items for the POS. However, you can also mark frequently bought items as favourites yourself in order to speed up the checkout process. Proceed as described below to add items to the POS shopping cart by using the list of favourites.

[.instruction]
Adding items from the list of favourites:

. In the POS shopping cart, tap the star. +
→ The favourites list is displayed.
. Tap the green check mark to add an item to the shopping cart. +
→ The **Enter quantity** window is displayed. +
. Enter the quantity for the item that you want to add to the shopping cart. +
→ The item is added to the shopping cart and the current order sum is updated.
. Finish processing the POS order as usual.

[#70]
==== Scanning labels

If you have saved labels for your items in the plentymarkets system, you can also add items to the POS shopping cart by scanning these labels. To do so, proceed as described below.

[.instruction]
Adding items by scanning the label:

. In the POS shopping cart, tap the label symbol. +
→ The mobile device's camera is activated.
. Tap the camera icon to scan the label. +
→ The **Enter quantity** window is displayed.
. Enter the quantity for the item that you want to add to the shopping cart. +
→ The item is added to the shopping cart and the current order sum is updated.

[#80]
=== Receiving a payment

Once you have added all items of a customer to the POS shopping cart and applied gift cards and/or discounts, you complete the order by accepting payment. You can currently accept payments in cash or via a POS terminal.

[NOTE]
.Cancelling an order
====
You can cancel a POS order directly after you accepted and booked the payment. To do so, tap **Cancel order** in the **Order created** view. Go to <<omni-channel/pos/plentymarkets-pos-for-pos-users#173, **POS » Cancel order**>> to cancel orders created for this POS since the last Z report.
====

[.instruction]
Booking cash payments:

. Tap in the amount you received from the customer.
. Tap **Payment received/Complete payment**. +
→ The **Order created** view is displayed. +
→ The order is created. +
→ A receipt is printed. Alternatively, tap **Print receipt** to print the receipt. +
→ **__Tip:__** Tap **Show order** to view the order details.
. Tap **New order** to create a new POS order.

[.instruction]
Booking card payments with an external payment terminal:

. Tap **POS terminal**. +
→ The order total to be payed is displayed.
. Book the payment using the POS terminal.
. Tap **Payment received/Complete payment** to complete the order. +
→ The **Order created** view is displayed. +
→ The order is created. +
→ A receipt is printed. Alternatively, tap **Print receipt** to print the receipt. +
→ **__Tip:__** Tap **Show order** to view the order details.
. Tap **New order** to create a new POS order.


[.instruction]
Booking card payments with a linked payment terminal:

. Tap **POS terminal**.
. Follow the instructions to complete payment on the terminal.
→ The view **Order created** is shown. +
→ The order is created. +
→ The receipts are printed. Alternatively, tap **Print merchant receipt** and/or **Print customer receipt** to start printing manually. +
→ **__Tip:__** Tap **Show order** to view the order details.
. Tap **New order** to create a new POS order.


[#250]
=== Selling a gift card

Every gift card is equivalent to a unique coupon code. However, this coupon code is not shown on the receipt when you sell a gift card. To allow you to sell gift cards, your employer will provide a separate list of coupon codes. As such, this description only consists of general information on selling gift cards. How gift cards are sold in your store depends on the specific processes set up for this purpose. For example, you may receive a list of coupon codes, cross out codes as you sell them and then note them down on the receipt/gift card form. Check with your employer to make sure you understand how gift cards are sold in your store.

[.instruction]
Selling a gift card:

. Add the gift card to the POS shopping cart.
. Finish processing the order as usual.
. Hand over the coupon code to the customer.
. Document the coupon code you sold. +
**__Note:__** Because the value of a gift card can only be redeemed once, each coupon code must be sold once only.

[#90]
== Optional POS operations

[#135]
=== Selecting an existing customer

By default, the default customer saved for the POS is used for POS orders. However, you can select a different customer record saved in plentymarkets to save with individual POS orders. Once a POS order is completed, the POS defaults back to the default customer for the next POS order.

Proceed as described below to select an existing customer. You can search for customers using the following customer details:

* **Contact ID** = The customer's contact ID
* **Customer data** = First name, last name, company, contact person, eBay name, additional name, street, postcode, town, email address, customer number, external customer ID, search tags, PostIdent
* **Postcode** = The customer's postcode

[.instruction]
Selecting an existing customer:

. In the POS shopping cart, tap on the customer symbol at the bottom right. +
→ The customer record of the default customer is displayed.
. Tap the **magnifying glass**. +
→ The **Customer search** view is displayed.
. Enter the customer data you know to search the customer record.
. Tap **Search**. +
→ The search results are displayed.
. Tap a customer record. +
→ A list of the addresses saved for the customer is displayed.
. Tap an address. If only one address exists for the customer record, this address is selected by default.
. Tap **Use address**. +
→ The customer record is selected.
. If you have already placed items in the POS shopping cart, you are asked if you want to **Update prices?**. If you select **Yes**, any discounts saved for the customer class of the selected customer are applied to all items of the order. +
→ The customer details are applied to the order. +
→ **__Tip:__** You can revert to the default customer by clicking on the **Reset** icon.
. Tap the **X** to the top right or tap the screen outside the window to return to the POS shopping cart. +
→ The selected customer is shown in the POS shopping cart.
. Finish processing the order as usual. +
→ Once you have completed this POS order, the system defaults back to the default customer.

[TIP]
.Email receipts to customers
====
You can email receipts to customers automatically when a receipt is generated. To do so, you need to <<omni-channel/pos/integrating-plentymarkets-pos#70, **create an event procedure**>> in the plentymarkets back end. Note that for POS orders created in the offline mode, the event procedure will only take effect once the POS order is uploaded.
====

[#100]
=== Adding a note to the order

To save additional information on the order, save a note before completing the order. Notes are imported to plentymarkets and saved with the order.

[.instruction]
Adding a note to the order:

. In the POS shopping cart, tap **Note**. +
→ A list of the notes saved with the orders is displayed.
. Click on **Add**. +
→ The **Add note** window is displayed.
. Enter the note text.
. Tap the check mark to save the note to the order. +
→ The note is displayed in the list of notes and is imported to plentymarkets.
. Tap **X** to close the window and return to the shopping cart view.

[#110]
=== Pausing a checkout process

If you need to interrupt a checkout process but have already added items to the POS shopping cart, you can save the current state of the shopping cart by parking the receipt. You can save several receipts at a time.

[#120]
==== Parking a receipt

Proceed as described below to park a receipt.

[.instruction]
Parking a receipt:

. In the POS shopping cart, tap the vertical ellipse at the top right of the screen. +
→ Additional options are displayed.
. Click on **Park receipt**. +
→ The **Park receipt** window is displayed.
. Tap **Yes**. +
→ The receipt is saved and a new POS shopping cart is displayed.

[#130]
==== Loading a parked receipt

Proceed as described below to load a parked receipt and complete the order.

[.instruction]
Loading a parked receipt:

. In the POS shopping cart, tap the vertical ellipse at the top right of the screen. +
→ Additional options are displayed.
. Tap **Load receipt**. +
→ A list of all parked receipts is displayed.
. Tap the receipt to load. +
→ The parked items of this receipt are displayed in the POS shopping cart.
. Finish processing the POS order as usual.

[#140]
=== Editing an order item

// Diese Einstellungen müssen noch in Einzelkapitel unterteilt und einzeln beschrieben werden.
You can edit items placed in the POS shopping cart. Any changes you make are applied only to this order. The item is not changed in the system.

[.instruction]
Editing order items:

. In the POS shopping cart, tap the order item. +
→ Additional options are displayed.
. Tap the preferred setting. Pay attention to the explanations given in table 2.

.Editing order items
[cols="1,2"]
|====
|Setting |Explanation

|**Change quantity**
|Open the **Change quantity** window. Enter the new quantity and tap **OK** to edit the item quantity in the shopping cart.

|**Rename order item**
|Enter the new name and tap **OK** to change the name of the order item. The name is changed only in this order. The item's name in the system remains unchanged.

|**Change single price**
|Enter the new price and tap **OK** to change the price of only one of the items of an order item with a quantity above 1. The price is changed only in this order. The item's price in the system remains unchanged.

|**Change total price**
|Enter the new price and tap **OK** to change the total price of all items of an order item. The price is changed only in this order. The item's price in the system remains unchanged.

|**Reset item price**
|Resets prices changed using the **Change single price** or the **Change total price** option to the original price.

|**Add discount**
|Enter the discount in percent and tap **OK** to offer a discount on the order item. The price is changed only in this order. The item's price in the system remains unchanged. +
**__Note:__** You cannot combine discounting individual order items with a discount on the complete POS shopping card.

|**Remove discount**
|Resets prices discounted using the **Add discount** option to the original price.

|**Delete**
|Deletes the item from the POS shopping cart.
|====

[#150]
=== Editing the shopping cart

Before completing the order, you can redeem coupon codes or grant a discount on the complete shopping cart amount.

[#160]
==== Redeeming a gift card

[.instruction]
Redeeming a gift card:

. Tap the green arrow at the bottom of the POS shopping cart. +
→ A summary of the order and the available payment methods are displayed.
. Tap **Coupon / discount**.
. Enter the coupon code in the **Coupon code/discount** field.
. Tap **Coupon**. +
→ The coupon total is deducted from the order total and the remaining coupon balance is displayed.
. Tap **Back**.
. Finish processing the POS order as usual.

[#170]
==== Applying discounts to the complete POS order

Instead of discounting individual order items, you can also apply a discount to all items in the POS shopping cart. However, you cannot apply a discount to the complete POS shopping card if a discount was applied to one or more order items. Proceed as described below to apply a discount to all items in the POS shopping cart.

[.instruction]
Applying discounts to the complete shopping cart:

. Tap the green arrow at the bottom of the POS shopping cart. +
→ A summary of the order and the available payment methods are displayed.
. Tap **Coupon / discount**.
. Enter the discount percentage in the **Coupon code/discount** field.
. Tap **Discount**. +
→ The discount total is deducted from the order total and the new order total is displayed.
. Tap **Back**.
. Finish processing the POS order as usual.

[#173]
== Cancelling an order

Go to **POS beta » Cancel order** to cancel orders created for this POS since the last Z report. Proceed as described below to cancel a POS order.

[WARNING]
.Only cancel POS orders in the plentymarkets app
====
Only cancel POS orders in the plentymarkets app and not in the plentymarkets back end. Orders cancelled in the plentymarkets back end are not synchronised with the app. This means that the POS data used for reporting (z reports, cash on hand, etc.) are no longer correct when you cancel POS orders in the plentymarkets back end.
====

[.instruction]
Cancelling an order:

. In the menu bar, tap the **menu symbol**.
. Tap **POS**.
. Tap **Cancel order**. +
**__Tipp:__** You can only select this option if you have the right to cancel orders. +
→ A list of all orders created for this POS since the last Z report is displayed.
. Tap the **Cancellation** icon. +
→ Alternatively, tap the order to open the order details. Tap the **Cancellation** icon in the detailed view.
. Confirm the cancellation. +
. **__On some card terminals:__** Select if the cancelled amount is to be returned in cash or booked back to the card account via the terminal.
. Pay out the cancelled amount in cash or process the refund via the POS terminal/payment provider. +
→ The order is cancelled.

[#175]
== Booking a return

POS returns are imported into the plentymarkets back end as returns without a main order. Proceed as described below to book a return.

[.instruction]
Book a return:

. Open the **POS** menu. Tap on **Return**. +
→ The Returns view is displayed.
. Add the items to be returned by scanning them or using the item search. +
→ If the price paid differs from the current price of the item, <<omni-channel/pos/plentymarkets-pos-for-pos-users#140, **adjust the price of the item**>>.
. Optionally, add a note to the return.
[.collapseBox]
.Adding a note
--
. Tap the pin. +
→ A list of the notes saved with the return is displayed.
. Click on **Add**. +
→ The **Add note** window is displayed.
. Enter the note text.
. Tap the check mark button to save the note to the return. +
→ The note is saved and will be imported to plentymarkets with the return.
. Tap the list icon to return to the returns view.
--
. When you have added all items to be returned, tap the green check mark button. +
→ the total amount of the return is shown.
. Tap **Complete return**. +
→ A return without main order is created in the plentymarkets back end.

[#180]
== Booking cash deposits/withdrawals

Withdrawals and deposits that are not the result of orders need to be booked and documented.

[#190]
=== Booking a cash deposit

[.instruction]
Booking a cash deposit:

. In the top left corner of the POS shopping cart, tap **Back**. +
→ The **POS menu** is displayed.
. Tap **Deposits and withdrawals**. +
→ A keypad is displayed. Enter the amount.
. Enter information on the deposit in the **Reason** field.
. Enter the amount that is deposited in the POS.
. Tap **Deposit** to book the deposit. +
→ The current cash on hand is updated. +
→ A receipt for the deposit is printed. +
→ The receipt is imported to plentymarkets and saved in the **Orders » Document archive** menu.

[#200]
=== Booking a cash withdrawal

[.instruction]
Booking a cash withdrawal:

. In the top left corner of the POS shopping cart, tap **Back**. +
→ The **POS menu** is displayed.
. Tap **Deposits and withdrawals**. +
→ A keypad is displayed. Enter the amount.
. Enter information on the withdrawal in the **Reason** field.
. Enter the amount that is withdrawn from the POS.
. Tap **Withdrawal** to book the withdrawal. +
→ The current cash on hand is updated. +
→ A receipt for the withdrawal is printed. +
→ The receipt is imported to plentymarkets and saved in the **Orders » Document archive** menu.

[#210]
== Creating reports

[#220]
=== Creating an x report

Use X reports to get an overview of the revenue generated for this POS since the last Z report during the day. You can create any number of X reports. X reports are not imported to plentymarkets, i.e. their creation is not documented.  

X reports contain the following information:

* Cash on hand: Initial cash on hand, withdrawals, deposits, expected cash on hand
* Revenue: since last Z report (sum) and since creation of POS (grand total)
* VAT report: VAT rate, VAT amount and net revenue
* Payment methods: Revenue by payment method
* Returns: Quantity and total
* Cancellations: Quantity and total
* Discounted items: Quantity and total
* Gift cards: Quantity and total for sold gift cards
* User: Revenue per user

[.instruction]
Creating an x report:

. In the top left corner of the POS shopping cart, tap **Back**. +
→ The **POS menu** is displayed.
. Tap **X report**. +
→ An x report is printed.

[#230]
=== Creating a Z report

A Z report documents the revenue accrued since the last Z report. By generating a Z report, the daily revenue is reset to 0. Z reports are assigned a sequential number and saved in plentymarkets. Depending on local law, the saving of Z reports may be required for fiscal purposes.  

Z reports contain the following information:

* Cash on hand: Withdrawals, deposits, expected cash on hand, actual cash on hand
* Revenue: since last Z report (sum) and since creation of POS (grand total)
* VAT report: VAT rate, VAT amount and net revenue
* Payment methods: Revenue by payment method
* Returns: Quantity and total
* Cancellations: Quantity and total
* Discounted items: Quantity and total
* Sold gift cards: Quantity and total
* User: Revenue per user

[.instruction]
Creating a Z report:

. In the top left corner of the POS shopping cart, tap **Back**. +
→ The **POS menu** is displayed.
. Tap **Z report**. +
→ The expected amount of cash on hand is displayed.
. Count the actual cash on hand and enter this amount.
. Tap **Create Z report**.
→ The Z report is imported to plentymarkets and saved in the **Orders » Document archive** menu. +
→ The Z report is printed. +
→ The daily revenue is reset to 0.

[TIP]
.Z report for card payments
====
For some card terminals linked to plentymarkets POS, you can create a z report for the card terminal revenue at the same time as you create the plentymarkets POS z report on some card terminals linked to plentymarkets POS. Answer **Yes** to the question **Also create z report for terminal?** to send the card revenue to the payment provider and reset it to 0.
====

=== Creating a till count report

A till count documents the cash on hand of a till, i.e. the amount of cash in coins and notes, at a specific point in time. For till counts, the cash on hand present in the till is physically counted and a count log is created. Currently, you can only enter Euro denominations.

==== Saving a till count result

When you carry out a till count and save the result in plentymarkets POS, you can enter either the quantity of each coin and note denominations or enter the total result of the till count. Document the result of a till count as described below.

[.instruction]
Saving a till count result:

. Log into the plentymarkets App.
. In the menu bar, tap the **menu symbol**.
. Tap **POS**. +
→ The POS menu is displayed.
. Tap **Till count**. +
→ The **Till count** menu is displayed. The lowest coin denomination is preselected.
. Use the keypad to enter the number of coins you counted for this denomination.
. Tap the green return arrow to jump to the next denomination.
. Repeat this process until you have entered the quantity of all coins and notes. +
→ **__Alternative:__** To enter the total amount counted instead of the quantity per denomination, tap the **Overwrite** field and enter the total amount you counted.
. Tap **Save till count**. +
→ A till count report is created and saved in the **plentymarkets » Orders » Document archive**.
. **__Optional:__** Tab **Print till count report** to print the report.
. If the actual cash on hand differs from the expected cash on hand, proceed as described below to book the difference.

==== Booking a till count discrepancy

If the actual cash on hand differs from the expected cash on hand after the count, you either need to balance the discrepancy or book the difference. When you book the difference, the actual cash on hand is saved as the new expected cash on hand. At the same time, either a deposit or a withdrawal is saved depending on whether the difference is positive or negative:

* If the actual cash on hand is larger than the expected cash on hand, a deposit is booked.
* If less cash than expected is in the till, a withdrawal is booked.

When you book a till count discrepancy, the reason **Till count discrepancy** is saved automatically for this booking.

[.instruction]
Booking a till count discrepancy:

. After saving the till count, tap **Book difference** to save the actual cash on hand as the new expected cash on hand. +
→ A deposit or withdrawal is created for the discrepancy with the reason **Till count discrepancy** and saved in the **plentymarkets » Orders » Document archive » POS receipt**. +
→ The actual cash on hand is saved as the new expected cash on hand.

[#240]
== Changing POS orders in the plentymarkets back end

An order is created for POS orders in the plentymarkets back end. The following order details can be modified after the POS order is imported to the plentymarkets back end:

* Language
* Status
* Amount paid
* Payment status
* Reasons for return
* Assign order to a multi-order
* Delivery address
* Emailing
* Order note
* Shipped on
* Return date
