= Einführung
:lang: de
include::{includedir}/_header.adoc[]
:position: 10

[IMPORTANT]
.Mobile Warehouse nur für Bestandskunden
====
Das Tool plentymarkets Mobile Warehouse steht nur noch für Bestandskunden zur Verfügung.
====

**Ihr Mobiles Endgerät » plentymarkets Mobile Warehouse**

Wenn Sie Einträge, Einstellungen oder Änderungen vorgenommen haben, klicken Sie vor Verlassen eines Bereichs jeweils auf das Speichern-Symbol, um Ihre Konfiguration zu sichern.

== plentymarkets Mobile Warehouse

plentymarkets Mobile Warehouse ist ein Backendbereich in plentymarkets für einfachere Buchungen von Warenbewegungen über ein mobiles Endgerät. Sie können damit über ein WLAN-Netz auf plentymarkets Mobile Warehouse zugreifen und Waren einbuchen, umbuchen oder eine Inventurbuchung durchführen.

[NOTE]
.SOAP-Modul erforderlich
====
Für die Verwendung von plentymarkets Mobile Warehouse benötigen Sie das SOP-Modul.
====

== Mobile Endgeräte

Es sind verschiedenste **mobile Endgeräte** für den Einsatz im plentymarkets Mobile Warehouse geeignet. Beachten Sie die Informationen zu den Systemvoraussetzungen auf der Handbuchseite **Login**. So können Sie ein **Handy** oder einen **PDA** mit **Windows CE**-Betriebssystem verwenden oder z.B. ein **Tablet-Notebook** oder einen **Handheld-PC**.

Für den Einsatz im Lager gibt es verschiedene speziell konzipierte Endgeräte mit robusten Eigenschaften. So zum Beispiel die Geräte von DATALOGIC, die u.a. auch einen Fall aus einer definierten Höhe überstehen (siehe Angaben des Herstellers) und gegen Nässe bzw. Feuchtigkeit geschützt sind.

Produktbeispiele

link:http://www.datalogic.com/deu/produkte/automatic-data-capture/mobile-computers/memor-x3-pd-636.html[**Memor**], von DATALOGIC MOBILE

link:http://www.datalogic.com/deu/produkte/automatic-data-capture/mobile-computers/skorpio-x3-pd-337.html[**Skorpio**], von DATALOGIC MOBILE

