= Suchfilter und Beispielartikel
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Artikelsuche, Backend-Suche, Backendsuche, Artikel suchen, Varianten suchen, Artikel bearbeiten, Artikel » Artikel bearbeiten, Suchoption, Suchoptionen, Filter, Tabellentyp, Aktiv, In Beschreibung, Artikelauflistung, Suchverhalten, Suchergebnis, Suchergebnisse, Beispielartikel, Beispiel-Artikel, Beispiel
:description: Lerne, wo du Artikeldaten in plentymarkets findest und schaue dir die Beispielartikel an.
:position: 30
:url: artikel/einleitung/suche
:id: 9ZXF92H
:author: team-item
//zuletzt bearbeitet 06.10.2020

Bevor du deine ersten Artikeldaten ins System einpflegst, solltest du dich kurz mit der Artikelübersicht vertraut machen. Auf dieser Seite lernst du, wie du dich im Menü zurechtfindest und wo du die Beispielartikel findest, die in neuen Systemen gespeichert sind.

[#100]
== Artikel und Varianten suchen

Das Menü *Artikel » Artikel bearbeiten* bietet dir eine Übersicht deiner Artikel und Varianten. Verwende die Suchoptionen in der Spalte links, um gezielt nach Artikeln und Varianten zu suchen. Die <<artikel/einleitung/suche#600, Suchergebnisse>> werden dir in einer Übersicht rechts angezeigt.

[.instruction]
Artikel suchen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Wähle die *Filter* in der Spalte links. Beachte <<table-filter-item-variations>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die gefilterten Artikel werden in der Übersicht angezeigt.

[TIP]
.Warum werden meine Artikel nicht gefunden?
====
Siehst du den Filter <<artikel/einleitung/suche#intable-aktiv, Aktiv>> in der linken Spalte? Mit diesem Filter legst du fest, ob nur Artikel und Varianten angezeigt werden, die für einen Webshop aktiviert sind. Standardmäßig ist dieser Filter auf *Ja* eingestellt. Das wird dir später, wenn du viele Artikel und Varianten hast, helfen, deine Artikel schneller zu bearbeiten. Am Anfang kann es aber verwirrend sein, denn Artikel, die nicht aktiv sind, werden nicht gefunden. Setze den Filter auf *Nein* oder *Alle* und führe die Suche erneut aus.
====

[[table-filter-item-variations]]
.Filtereinstellungen für Artikel und Varianten
[cols="1,4"]
|====
|Filter |Erläuterung

|[#intable-tabellentyp]*Tabellentyp*
a|Sollen <<artikel/einleitung/struktur#, Artikel und Varianten>> in den Suchergebnissen zusammengefasst werden? Soll die Tabelle also alle denkbaren Varianten oder nur die Artikel als Ganzes auflisten?

* *Artikel* = In der Übersicht werden nur ganze Artikel aufgelistet. Du musst den Artikeldatensatz öffnen, wenn du <<artikel/einleitung/suche#400, die darin enthaltenen Varianten sehen>> möchtest. Dies ist die Standardeinstellung. +
* *Varianten* = Jede einzelne Variante wird in der Übersicht aufgelistet. +
* *Erweitert* = Pro Zeile wird ein Artikel angezeigt. Klappe den Artikel auf (icon:chevron-down[role="darkGrey"]), um die darin enthaltenen Varianten zu sehen.

| *Artikel-ID*
|Gib eine ID ein, um nach dem Artikel mit dieser ID zu suchen.

| *Varianten-ID*
|Gib eine ID ein, um nach der Variante mit dieser ID zu suchen.

| *Variantennummer*
|Gib eine Variantennummer ein, um nach der Variante mit dieser Nummer zu suchen.

| *Barcode*
|Gib einen Barcode ein, um nach der <<artikel/artikel-verwalten#250, Variante mit diesem Code>> zu suchen.

|[#intable-artikeldaten]*Artikeldaten*
|Gib Artikeldaten ein, z.B. den Namen oder Modell eines Artikels oder ein passendes Stichwort.
Die Suchergebnisse liefern Produkte, die mit diesen Daten übereinstimmen.
Du kannst selbst entscheiden, <<artikel/anwendungsfaelle/suchverhalten#200, welche Artikeldaten die Suche berücksichtigen soll>>. +
*_Artikelbeschreibung durchsuchen_*: Möchtest du nach Artikeln suchen, deren Beschreibung ein bestimmtes Stichwort enthält? Gib das Stichwort in dieses Suchfeld ein und wähle die <<artikel/einleitung/suche#intable-beschreibung, *In Beschreibung* Option>> (icon:check-square[role="blue"]) weiter unten.

| *Seriennummer*
|Gib eine Seriennummer ein, um nach dem Artikel mit dieser Nummer zu suchen.

| *SKU*
a|. Gib eine SKU in das Textfeld ein.
. Wähle optional die Herkunft aus der Dropdown-Liste.
Damit wird bestimmt, auf welchen Marktplatz sich die eingegebene SKU bezieht.
. Die Suchergebnisse liefern Produkte, die <<artikel/artikel-verwalten#370, mit dieser SKU verknüpft>> wurden.

|[#intable-tags]*Klicken, um Tags hinzuzufügen*
a|. Klicke in das Feld und wähle ein Tag aus der Dropdown-Liste. +
*_Tipp_*: Gib die ersten Buchstaben des Tag-Namens ein und verwende die Autovervollständigung.
. Wiederhole den Vorgang, um beliebig viele Tags hinzuzufügen.
. Die Suchergebnisse liefern Produkte, die <<artikel/artikel-verwalten#268, mit diesen Tags verknüpft>> wurden.

*_Zusätzlicher Suchfilter_*:
Verwende diesen Suchfilter zusammen mit der Option *Tag Suchmodus* weiter unten.

| *Tag Suchmodus*
a|Möchtest du nach Varianten suchen, die mit _allen_ gewählten Tags oder nur mit _einem_ der gewählten Tags verknüpft sind?

Wähle den gewünschten Such-Modus aus der Dropdown-Liste.

* *Oder* = Die Variante muss mindestens eins der gewählten Tags besitzen.
* *Und* = Die Variante muss alle gewählten Tags besitzen.

*_Zusätzlicher Suchfilter_*: Verwende diesen Suchfilter zusammen mit der obigen Option *Klicken, um Tags hinzuzufügen*.

| *Notiztext*
|Gib Text ein, um nach Artikeln mit Varianten zu suchen, deren Notizen diesen Text enthalten.

| *Lieferanten-Artikelnummer*
|Gib die Artikelnummer des Lieferanten ein, um nach dem Artikel mit dieser Nummer zu suchen.

| *Typ*
|Möchtest du nach einem bestimmten Artikeltyp suchen? Verwende diesen Filter und grenze deine Suche so ein, dass sie nur Standardartikel, <<artikel/anwendungsfaelle/multipacks-pakete-sets#, Setartikel oder Multipacks>> enthält. +
*_Wie sieht es mit Artikelpaketen aus?_:* Es ist auch möglich, nach Artikelpaketen oder einzelnen Paketbestandteilen zu suchen. Verwende dazu den Filter <<artikel/einleitung/suche#intable-paket, Paket>>.

|[#intable-beschreibung]*In Beschreibung*
|Wähle diese Option (icon:check-square[role="blue"]), um nach einem Stichwort in der Artikelbeschreibung zu suchen. Gib das Stichwort in <<artikel/einleitung/suche#intable-artikeldaten, das Feld *Artikeldaten*>> weiter oben ein.

| *Artikelauflistung*
|Möchtest du nach Varianten suchen, deren <<artikel/artikel-verwalten#intable-artikelauflistung, Artikelauflistung-Einstellung>> auf sichtbar oder unsichtbar gesetzt ist?

| *Bild*
|Möchtest du nach Artikeln suchen, für die <<artikel/artikel-verwalten#90, ein Bild gespeichert>> ist?

| *Markierung 1; +
Markierung 2*
|Wähle jeweils eine Markierung oder die Option *ALLE* aus beiden Dropdown-Listen aus.
Die Suchergebnisse liefern nur Artikeln, die diese <<artikel/einstellungen/markierungen#300, Kombination von Markierungen>> besitzen.

|[#intable-hersteller]*Hersteller*
|Wähle einen Hersteller oder die Option *ALLE*.
Die Suchergebnisse liefern nur Artikeln, die <<artikel/artikel-verwalten#40, mit diesem Hersteller verknüpft>> sind.

Wähle die Option *Ohne*, um nach Artikeln zu suchen, die mit keinem Hersteller verknüpft sind.

*_Hinweis_*: Diese Liste enthält nur die <<artikel/einstellungen/hersteller#, Herstellerdatensätze>>, die du bereits in plentymarkets gespeichert hast.

|[#intable-alle]*ALLE* +
(Liste der Attribute)
a|. Wähle ein Attribut oder die Option *ALLE* aus der linken Dropdown-Liste.
. Wähle einen Attributwert oder die Option *ALLE* aus der rechten Dropdown-Liste.
. Die Suchergebnisse liefern Produkte, die mit diesem Attributwert verknüpft wurden.

*_Hinweis_*: Diese Listen enthalten nur die <<artikel/einstellungen/attribute#, Attribute und Attributwerte>>, die du bereits in plentymarkets gespeichert hast.

|[#intable-aktiv]*Aktiv*
a|Möchtest du nur nach <<artikel/artikel-verwalten#intable-aktiv, aktiven Artikeln>> suchen, d.h. nach Artikeln, die im Webshop verfügbar sind?

* *Ja* = Standardeinstellung. Nach allen aktiven Artikeln suchen. +
* *ALLE* = Nach allen Artikeln suchen. In der Übersicht werden sowohl aktive als auch inaktive Artikel angezeigt. +
* *Nein* = Nach allen inaktiven Artikeln suchen.

| *Mandant (Shop)*
|Wähle einen Mandanten (Shop) oder die Option *ALLE*.
Die Suchergebnisse liefern nur Produkte, die <<artikel/artikel-verwalten#360, mit diesem Mandanten verknüpft>> sind.

| *Verfügbar*
|Wähle eine Verfügbarkeitsstufe oder die Option *ALLE*.
Die Suchergebnisse liefern nur Produkte, die <<artikel/artikel-verwalten#200, mit dieser Verfügbarkeitsstufe verknüpft>> sind.

| *Verkaufspreis*
|Wähle einen Verkaufspreis oder die Option *ALLE*.
Die Suchergebnisse liefern nur Produkte, die <<artikel/artikel-verwalten#240, mit diesem Verkaufspreis verknüpft>> sind.

| *Versand*
|Wähle ein Versandprofil oder die Option *ALLE*.
Die Suchergebnisse liefern nur Produkte, die <<artikel/artikel-verwalten#_versandprofile, mit diesem Versandprofil verknüpft>> sind.

| *Lager*
|Wähle ein Lager oder die Option *ALLE*.
Die Suchergebnisse liefern nur Produkte, die <<artikel/artikel-verwalten#312, mit diesem Lager verknüpft>> sind.

| *WB-Beschränkung*
a|Dieser Filter schränkt die Suche so ein, dass sie nur Artikel mit einer bestimmten <<artikel/artikel-verwalten#intable-beschraenkung, Bestandsbeschränkung>> enthält.

* *keine Beschränkung* = Die Suchergebnisse enthalten nur Artikel, bei denen die *Beschränkung* Option auf *Keine* gesetzt wurde.
* *Beschränkung auf Nettowarenbestand* = Die Suchergebnisse enthalten nur Artikel, bei denen die *Beschränkung* Option auf *Auf Netto-WB* gesetzt wurde.
* *Keinen Warenbestand führen* = Die Suchergebnisse enthalten nur Artikel, bei denen die *Beschränkung* Option auf *Keinen WB für diese Variante führen* gesetzt wurde.
* *ALLE* = Die Suchergebnisse umfassen Artikel mit jeder Bestandsbeschränkung. Dies ist die Standardeinstellung

| *WB*
|Wähle eine Bestandsstufe oder die Option *ALLE*.
Die Suchergebnisse liefern nur Produkte, die <<warenwirtschaft/warenbestaende-verwalten#400, diesen Bestand haben>>.

| *Warentyp*
a|Wähle einen Warentyp oder die Option *ALLE*.
Die Suchergebnisse liefern nur Produkte, die <<artikel/artikel-verwalten#_grundeinstellungen, mit diesem Typ verknüpft>> sind.

* *Ohne Colli* = Artikel des Typs Colli werden von der Suche ausgeschlossen.

|[#intable-paket]*Paket*
a|Möchtest du nach <<artikel/anwendungsfaelle/multipacks-pakete-sets#, Artikelpaketen>> oder einzelnen Paketbestandteilen suchen?

* *Ja* = Die Suchergebnisse umfassen nur Artikel und Varianten, die den _Hauptartikel eines Artikelpakets_ darstellen.
* *Nein* = Die Suchergebnisse umfassen Artikel und Varianten, die weder der Hauptartikel noch Bestandteile eines Artikelpakets sind.
* *Bestandteil* = Die Suchergebnisse umfassen nur Artikel und Varianten, die _Bestandteile eines Artikelpakets_ sind.
* *ALLE* = Die Suchergebnisse umfassen sowohl Artikelpakete als auch Artikel, die keine Pakete sind. Dies ist die Standardeinstellung.

| *Listing*
a|Möchtest du nach Artikeln suchen, die Teil eines Listings oder einer Auktion sind?

* *Ja* = Die Suchergebnisse enthalten nur Artikel, die Teil eines Listings oder einer Auktion sind, d.h. Artikel mit einem <<artikel/einleitung/suche#800, gelben Listing-Symbol>> (icon:listings_show[set=plenty, role="yellow"]).
* *Nein* = Die Suchergebnisse enthalten nur Artikel, die _nicht_ Teil eines Listings oder einer Auktion sind, d.h. Artikel mit einem <<artikel/einleitung/suche#800, grauen Listing-Symbol>> (icon:listings_show[set=plenty]).
* *Auktion (Ja)* = Die Suchergebnisse enthalten nur Artikel, die Teil einer Auktion sind. Dies bedeutet, dass <<maerkte/ebay/ebay-einrichten#3500, die Option *Typ* auf *Auktion* gesetzt wurde>>.
* *Shop-Artikel/Festpreis (Ja)* = Die Suchergebnisse enthalten nur Artikel, die Teil eines Listings sind. Dies bedeutet, dass <<maerkte/ebay/ebay-einrichten#3500, die Option *Typ* auf *Festpreis* oder *Shop-Artikel* gesetzt wurde>>.
* *ALLE* = Die Suchergebnisse umfassen Artikel die Teil eines Listings und _nicht_ Teil eines Listings sind. Dies ist die Standardeinstellung.

| *Shop-Aktion*
|Dieser Filter schränkt die Suchergebnisse auf Artikel ein, die Teil einer <<artikel/webshop/shop-aktionen#200, Callisto-Shop-Aktion>> sind. Der Filter sucht nach Artikeln, die im Tab *Global* als *Sonderangebot*, *Neuheit* oder *Top-Artikel* markiert wurden. +
*_Wie sieht es mit Ceres-Shop-Aktionen aus?_*: <<artikel/webshop/shop-aktionen#100, Ceres-Shop-Aktionen>> werden mithilfe von Tags abgebildet. Verwende daher den <<artikel/einleitung/suche#intable-tags, Tags-Filter>>, um nach Artikeln zu suchen, die Teil einer Ceres-Shop-Aktion sind.

| *Altersfreigabe*
|Mit diesem Filter kannst du die Suchergebnisse so eingrenzen, dass nur Artikel mit einer bestimmten <<artikel/artikel-verwalten#40, Altersfreigabe>> angezeigt werden.

| *Update von; +
Update bis*
|Wähle Daten aus den Kalendern aus.
Die Suchergebnisse liefern nur Produkte, die während dieses Zeitraums geändert wurden.

| *Produkttyp*
|Dieser Filter grenzt die Suchergebnisse so ein, dass nur Artikel mit einem bestimmten <<artikel/artikel-verwalten#_amazon, Amazon-Produkttyp>> angezeigt werden.

| *Amazon Canada*; +
*Amazon FBA*; +
... +
*Zalando* +
*Zentralverkauf.de*
a|Möchtest du nur nach Artikeln suchen, die <<artikel/artikel-verwalten#350, auf einem bestimmten Marktplatz verfügbar>> sind?

* *Sichtbar* = Dieser Markt wurde im Tab *Verfügbarkeit* der Variante ausgewählt.
* *Unsichtbar* = Dieser Markt wurde _nicht_ im Tab *Verfügbarkeit* der Variante ausgewählt.
* *ALLE* = Die Suchergebnisse sollen sowohl Artikel enthalten, die auf diesem Markt erhältlich sind, als auch Artikel, die auf diesem Markt nicht erhältlich sind. Dies ist die Standardeinstellung.

*_Hinweis_*: Hier siehst du einen Filter für jeden Marktplatz, der im Menü *Einrichtung » Aufträge » Auftragsherkunft* aktiviert (icon:check-square[role="blue"]) wurde.
|====

[#200]
=== Artikel einer Kategorie suchen

Möchtest du nach Artikeln einer bestimmten Kategorie suchen? Gehe wie unten beschrieben vor, um die <<artikel/artikel-verwalten#300, Artikel einer Kategorie>> zu sehen.

[.instruction]
Artikel einer Kategorie suchen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Wechsele in das Tab *Kategorie* in der Spalte links.
. Klicke auf eine Kategorie oder auf eine Unterkategorie. +
→ Die Artikel dieser Kategorie bzw. Unterkategorie werden in der Artikelübersicht angezeigt.

[TIP]
.Wo finde ich die Unterkategorien?
====
Klicke ganz links auf das Ordner-Symbol (icon:folder[role="darkGrey"]) einer Kategorie, um die darin enthaltenen Unterkategorien zu sehen.
====

[TIP]
.Kategorien mit Filtern kombinieren
====
Verwende die Kategoriesuche zusammen mit den Filtereinstellungen aus <<table-filter-item-variations>> und grenze damit deine Suchergebnisse noch näher ein.
====

[TIP]
.Wieder nach Artikeln in allen Kategorien suchen
====
Wechsele zurück in das Tab *Filter* und entferne das Häkchen neben *Mit Kategorie*. Die nächste Suche erfolgt in allen Kategorien.
====

[#300]
=== Artikel eines Mandanten suchen

Bist du für die Artikeldaten mehrerer Webshops zuständig? Gehe wie unten beschrieben vor, um gezielt die <<artikel/artikel-verwalten#360, Artikel eines Mandanten>> abzurufen.

[.instruction]
Artikel eines Mandanten suchen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Wechsele in das Tab *Mandant* in der Spalte links.
. Klicke auf einen Mandanten. +
→ Die Artikel des Mandanten werden in der Artikelübersicht angezeigt.

[TIP]
.Mandant mit Kategorie und Filter kombinieren
====
Klicke ganz links auf das Ordner-Symbol (icon:folder[role="darkGrey"]) eines Mandanten und dann auf eine darin enthaltene Kategorie. Die Suchergebnisse werden auf Artikel einer bestimmten Kategorie _und_ eines bestimmten Mandanten eingegrenzt. Verwende die Mandantensuche auch zusammen mit den Filtereinstellungen aus <<table-filter-item-variations>> und grenze damit deine Suchergebnisse noch näher ein.
====

[TIP]
.Für einen Mandanten _nicht verfügbare_ Artikel suchen
====
Setze ein Häkchen neben *Nicht verfügbar* und klicke auf einen Mandanten. Die für den Mandanten nicht verfügbaren Artikel werden in der Artikelübersicht angezeigt.
====

[#400]
=== Varianten im Artikeldatensatz suchen

Artikel beinhalten immer eine oder mehrere Varianten. Beim Öffnen eines Artikels wird immer die erste Variante, d.h. die <<artikel/einleitung/struktur#600, Hauptvariante>>, automatisch mit geöffnet. Aber wie kommst du an die weiteren Untervarianten des Artikels ran? Gehe wie unten beschrieben vor, um die einzelnen Varianten eines Artikels zu suchen.

[.instruction]
Varianten im Artikel suchen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#100, Suche>> und öffne den Artikel.
. Wechsele in das Tab *Varianten*.
. Wähle die *Filter*. Beachte <<table-filter-variations>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die gefilterten Varianten werden innerhalb des Artikeldatensatzes angezeigt.

[[table-filter-variations]]
.Varianten im Artikeldatensatz suchen
[cols="1,3"]
|====
|Filter |Erläuterung

| *ID*
|ID eingeben, um nach der Variante mit dieser ID zu suchen.

| *Variantennummer*
|Variantennummer eingeben, um nach der Variante mit dieser Nummer zu suchen.

| *Ext. Varianten-ID*
|ID eingeben, um nach der Variante mit dieser externen Varianten-ID zu suchen.

| *Barcode*
|Barcode eingeben, um nach der Variante mit diesem Code zu suchen.

| *Attribute*
|Attributwert oder *ALLE* wählen, um nach Varianten mit diesem Attributwert zu suchen. Attribute werden dynamisch geladen. Nur mit Varianten verknüpfte Attribute werden also angezeigt.
|====

[TIP]
.Varianten lieber direkt in der Hauptübersicht sehen?
====
Verwende die in <<table-filter-item-variations>> beschriebenen Filter, um Varianten anstatt im Artikeldatensatz direkt in der Hauptübersicht zu sehen. Wähle beim Filter <<artikel/einleitung/suche#intable-tabellentyp, Tabellentyp>> die Option *Varianten* oder *Erweitert*. Verwende zusätzlich die Filter *Varianten-ID* oder *Variantennummer*, um gezielt nach bestimmten Varianten zu suchen.
====

[#500]
=== Vordefinierte Suchverhalten anpassen

Soll ein <<artikel/anwendungsfaelle/suchverhalten#100, bestimmter Verkaufspreis oder Barcode>> in der Artikelübersicht dargestellt werden? Möchtest du selbst definieren, <<artikel/anwendungsfaelle/suchverhalten#200, welche Artikelparameter vom Suchindex erfasst>> werden? Mit plentymarkets kannst du das Suchverhalten nach deinen Bedürfnissen anpassen!

[#600]
== Mit Suchergebnissen arbeiten

Hast du die <<artikel/einleitung/suche#100, Suchoptionen in der Spalte links>> verwendet, werden dir die Suchergebnisse in einer Übersicht rechts angezeigt. Klicke direkt auf einen Artikel in der Übersicht, um den Artikeldatensatz zu öffnen und <<artikel/artikel-verwalten#, manuell zu bearbeiten>>.

[#700]
=== Spalten- und Sortierreihenfolge anpassen

Wenn du mit dem Mauszeiger über die Spaltenüberschriften fährst, werden weitere Symbole eingeblendet. Nutze diese Symbole, um die Ansicht nach deinen Bedürfnissen anzupassen.

* Welche Spalten sollen in der Tabelle enthalten sein? Klicke auf *Ansicht einrichten* (icon:gear[role="darkGrey"]) und wähle allen von dir gewünschten Spalten (icon:check-square[role="blue"]).
* Sollen bestimmte Spalten weiter rechts oder links dargestellt werden? Sobald dein Mauszeiger seine Form verändert (icon:arrows[role="darkGrey"]), kannst du die Spalten verschieben. Klicke einfach auf den Spaltenkopf und ziehe die Spalte in die gewünschte Position.
* Sollen Nummern absteigend oder aufsteigend sortiert werden? Klicke auf das kleine Dreieck (icon:caret-down[role="darkGrey"]), um die Sortierreihenfolge anzupassen.

[#800]
=== Symbole in der Übersicht

Siehst du die Spalte *Aktionen* in der Tabelle? Darunter sind einige Symbole, die dir helfen, deine Artikel schnell und unkompliziert zu verwalten.

* Klicke auf *Artikel bearbeiten* (icon:pencil[role="yellow"]), um den Artikeldatensatz zu öffnen. Klicke alternativ direkt auf den Artikel in der Übersicht.
* Klicke auf *Sichtbar im Webshop* (icon:eye[role="blue"]), um die <<artikel/webshop#, Darstellung des Artikels im Webshop>> zu prüfen. Wird das Symbol durchgestrichen, ist der Artikel *Unsichtbar im Webshop* (icon:item_webshop_invisible[set=plenty, role="blue"]).
* Klicke auf *Listing* (icon:listings_show[set=plenty, role="yellow"]), um eine Übersicht aller Listings oder Auktionen mit dieser Artikel-ID zu sehen. Wird das Symbol ausgegraut, wurden noch keine Listings für den Artikel angelegt.
* Klicke auf *Neues Listing* (icon:listing_create[set=plenty, role="green"]), um diesen Artikel in einem <<maerkte/ebay/ebay-einrichten#3400, Listing oder Auktion auf eBay>>, <<maerkte/hood#2300, Hood>> oder <<maerkte/ricardo-ch#1900, ricardo>> zu verkaufen.
* Klicke auf *Notiz hinzufügen* (icon:order_note_create[set=plenty, role="green"]), um eine <<artikel/artikel-verwalten#2090, Notiz für die Variante>> zu schreiben.

[TIP]
.Weitere Symbole im Artikeldatensatz
====
//Baue ein Link um <<weitere Symbole in der Tab-Leiste>> ein, sobald das Kapitel steht
Hast du einen Artikel bereits geöffnet, findest du weitere Symbole in der Tab-Leiste.
====

[#900]
== Beispielartikel

[#1000]
=== Beispielartikel verstehen

include::../../willkommen/schnelleinstieg/_textblocks/beispielartikel-verstehen.adoc[]

[#1100]
==== Beispielartikel anzeigen

include::../../willkommen/schnelleinstieg/_textblocks/beispielartikel-anzeigen.adoc[]

[#1200]
=== Beispielartikel löschen

include::../../willkommen/schnelleinstieg/_textblocks/beispielartikel-loeschen.adoc[]
