= Nutzerführung und Beispielartikel
:lang: de
include::{includedir}/_header.adoc[]
:description: Lerne, wo du Artikeldaten in plentymarkets findest und schaue dir die Beispielartikel an.
:position: 30
:url: artikel/einleitung/suche
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

Bevor du deine ersten Artikeldaten ins System einpflegst, solltest du dich kurz mit der Artikelübersicht vertraut machen. Auf dieser Seite lernst du, wie du dich im Menü zurechtfindest und wo du die Beispielartikel findest, die in neuen Systemen gespeichert sind.

[#100]
== Artikel und Varianten suchen

Das Menü *Artikel » Artikel bearbeiten* bietet dir eine Übersicht deiner Artikel und Varianten. Verwende die Suchoptionen in der Spalte links, um gezielt nach Artikeln und Varianten zu suchen. Die <<artikel/einleitung/suche#600, Suchergebnisse>> werden dir in einer Übersicht rechts angezeigt.

[.instruction]
Artikel suchen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Wähle die *Filter* in der Spalte links. Beachte <<tabelle-artikel-varianten-filtern>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die gefilterten Artikel werden in der Übersicht angezeigt.

[TIP]
.Warum werden meine Artikel nicht gefunden?
====
Siehst du den Filter <<artikel/einleitung/suche#aktiv, Aktiv>> in der linken Spalte? Mit diesem Filter legst du fest, ob nur Artikel und Varianten angezeigt werden, die für einen Webshop aktiviert sind. Standardmäßig ist dieser Filter auf *Ja* eingestellt. Das wird dir später, wenn du viele Artikel und Varianten hast, helfen, deine Artikel schneller zu bearbeiten. Am Anfang kann es aber verwirrend sein, denn Artikel, die nicht aktiv sind, werden nicht gefunden. Setze den Filter auf *Nein* oder *Alle* und führe die Suche erneut aus.
====

[[tabelle-artikel-varianten-filtern]]
.Filtereinstellungen für Artikel und Varianten
[cols="1,2"]
|====
|Filter |Erläuterung

|[#tabellentyp]*Tabellentyp*
|Tabellentyp wählen. +
*Artikel* = Nur Hauptvarianten in der Übersicht anzeigen. +
*Varianten* = Alle Hauptvarianten und Varianten in der Übersicht anzeigen. +
*Erweitert* = Erweiterte Ansicht aller Artikel inklusive Varianten in der Übersicht anzeigen.

|*Artikel-ID*
|ID eingeben, um nach dem Artikel mit dieser ID zu suchen.

|*Varianten-ID*
|ID eingeben, um nach der Variante mit dieser ID zu suchen.

|*Variantennummer*
|Variantennummer eingeben, um nach der Variante mit dieser Nummer zu suchen.

|*Barcode*
|Barcode eingeben, um nach der Variante mit diesem Code zu suchen.

//Link <<artikel/artikel-verwalten#385, Suchindex>> und Satz-Formulierung ändern sobald neue Seiten-Struktur steht
|*Artikeldaten*
|Artikeldaten eingeben, um nach dem Artikel mit diesen Daten zu suchen. Welche Datenfelder durchsucht werden, legst du mit dem <<artikel/artikel-verwalten#385, Suchindex>> fest.

|*Seriennummer*
|Seriennummer eingeben, um nach dem Artikel mit dieser Nummer zu suchen.

|*SKU*
|SKU oder *ALLE* wählen, um nach dem Artikel mit dieser SKU zu suchen.

//Wird sich hier die Struktur ändern? Link <<basics/arbeiten-mit-plentymarkets/tags#, Tags>> ändern sobald neue Seiten-Struktur steht
|*Tags*
|Tag-Namen eingeben, um nach Varianten zu suchen, die mit diesen <<basics/arbeiten-mit-plentymarkets/tags#, Tags>> verknüpft wurden. Tags werden im Menü *Einrichtung » Einstellungen » Tags* erstellt. +
Stelle im Tag-Filter den gewünschten Such-Modus ein. Der UND-Modus filtert Varianten, die alle gewählten Tags besitzen. Der ODER-Modus filtert alle Varianten, die mindestens eins der gewählten Tags besitzt. +
*_Tipp:_* Den ersten Buchstaben des Tags eingeben und dann die Autovervollständigung nutzen.

|*Notiztext*
|Text eingeben, um nach Artikeln mit Varianten zu suchen, deren Notizen diesen Text enthalten.

|*Lieferanten-Artikelnummer*
|Artikelnummer des Lieferanten eingeben, um nach dem Artikel mit dieser Nummer zu suchen.

|*Typ*
|*ALLE* oder einen Artikeltyp wählen, um nach Artikeln dieses Typs zu suchen. +
*Standard* = Nach Artikeln des Typs *Standard* suchen. +
*Set* = Nach Artikeln des Typs *Set* suchen. Setartikel sind ein neues plentymarkets Feature. Setartikel können aktuell nicht im Webshop dargestellt werden. Daher wird das Erstellen von Setartikeln nicht empfohlen.

|*In Beschreibung*
|Aktivieren, um nach der Artikelbezeichnung oder einem Stichwort in der Beschreibung des Artikels zu suchen.

|*Artikelauflistung*
|*ALLE* oder eine Option wählen, um die Artikel zu filtern. +
*Sichtbar* = Nach Varianten suchen, die in der Artikelauflistung sichtbar sind. +
*Unsichtbar* = Nach Varianten suchen, die in der Artikelauflistung unsichtbar sind.

|*Bild*
|*ALLE* oder eine Option wählen, um die Artikel zu filtern. +
*Ja* = Nach Artikeln suchen, für die ein Bild gespeichert ist. +
*Nein* = Nach Artikeln suchen, für die kein Bild gespeichert ist.

|*Markierung 1; +
Markierung 2*
|Markierung oder *ALLE* wählen, um nach Artikeln mit dieser Markierung zu suchen.

|*Hersteller*
|Hersteller oder *ALLE* wählen, um nach Artikeln mit diesem Hersteller zu suchen. +
*Ohne* wählen, um nach Artikeln ohne Hersteller zu suchen. Damit ein Hersteller als Filteroption verfügbar ist, muss mindestens ein Artikel mit dem Hersteller verknüpft sein.

|*Attribute*
|In der linken Dropdown-Liste ein Attribut oder *ALLE* wählen. In der rechten Dropdown-Liste einen Attributwert oder *ALLE* wählen, um nach Artikeln und Varianten mit diesem Attributwert zu suchen.

|[#aktiv]*Aktiv*
|*Ja*, *ALLE* oder *Nein* wählen. +
*Ja* = Standardeinstellung. Nach allen aktiven Artikeln suchen. Aktive Artikel sind im Webshop verfügbar. +
*ALLE* = Nach allen Artikeln suchen. Aktive und inaktive Artikel werden angezeigt. +
*Nein* = Nach allen inaktiven Artikeln suchen. Inaktive Artikel sind nicht im Webshop verfügbar.

|*Mandant (Shop)*
|Mandant (Shop) oder *ALLE* wählen, um nach Artikeln und Varianten dieses Mandanten zu suchen.

|*Verfügbar*
|Verfügbarkeit oder *ALLE* wählen, um nach Artikeln und Varianten mit dieser Verfügbarkeit zu suchen.

|*Verkaufspreis*
|Verkaufspreis oder *ALLE* wählen, um nach Artikeln und Varianten mit diesem Verkaufspreis zu suchen.

|*Versand*
|Versandprofil oder *ALLE* wählen, um nach Artikeln mit diesem Versandprofil zu suchen.

|*Lager*
|Lager oder *ALLE* wählen, um nach Artikeln und Varianten mit diesem Lager zu suchen.

|*WB-Beschränkung*
|*ALLE*, *Keine Beschränkung*, *Beschränkung auf Netto-Warenbestand* oder *Keinen Warenbestand führen* wählen. +
*Keine Beschränkung* = Nach Artikeln ohne Beschränkung des Warenbestands suchen. +
*Beschränkung auf Netto-Warenbestand* = Nach Artikeln mit einer Beschränkung auf den Netto-Warenbestand suchen. +
*Keinen Warenbestand führen* = Nach Artikeln suchen, für die kein Warenbestand geführt wird.

|*WB*
|Warenbestand oder *ALLE* wählen, um nach Artikeln und Varianten mit diesem Warenbestand zu suchen.

|*Warentyp*
|Warentyp oder *ALLE* wählen, um nach Waren dieses Typs zu suchen. +
*Ohne Colli* wählen, um Artikel des Warentyps *Colli* von der Suche auszuschließen.

|*Paket*
|*ALLE*, *Ja*, *Nein* oder *Bestandteil* wählen. +
*Ja* = Nach Artikeln und Varianten suchen, die Hauptartikel eines Artikelpakets sind. +
*Nein* = Nach Artikeln und Varianten suchen, die weder Hauptartikel noch Bestandteil eines Artikelpakets sind. +
*Bestandteil* = Nach Artikeln und Varianten suchen, die Bestandteil eines Artikelpakets sind.

|*Listing*
|*ALLE*, *Ja*, *Nein* oder Listing-Typ wählen.

|*Shop-Aktion*
|*ALLE*, *Keine* oder eine Shop-Aktion wählen.

|*Altersfreigabe*
|*ALLE*, *Keine* oder eine Altersfreigabe wählen.

|*Update von; +
Update bis*
|Datum im Kalender wählen, um nach allen Artikeln zu suchen, an denen in diesem Zeitraum Änderungen vorgenommen wurden.

|*Produkttyp*
|*ALLE*, *Unbekannt* oder einen Amazon-Produkttyp wählen.

|*Marktplätze*
|*ALLE*, *Sichtbar* oder *Unsichtbar* bei einer oder mehreren Marktplätzen wählen.
|====

[#200]
=== Artikel einer Kategorie suchen

//Link führt zur Stelle, wo die Einstellung greift. Also in diesem Fall zur Tab: Kategorie. Link anpassen wenn Seitenstruktur steht
Möchtest du nach Artikeln einer bestimmten Kategorie suchen? Gehe wie unten beschrieben vor, um die <<artikel/artikel-verwalten#300, Artikel einer Kategorie>> zu sehen.

[.instruction]
Artikel einer Kategorie suchen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Wechsele in das Tab *Kategorie* in der Spalte links.
. Klicke auf eine Kategorie oder auf eine Unterkategorie. +
→ Die Artikel dieser Kategorie bzw. Unterkategorie werden in der Artikelübersicht angezeigt.

[TIP]
.Wo finde ich die Unterkategorien?
====
Klicke ganz links auf das Ordner-Symbol (icon:folder[role="darkGrey"]) einer Kategorie, um die darin enthaltenen Unterkategorien zu sehen.
====

[TIP]
.Kategorien mit Filtern kombinieren
====
Verwende die Kategoriesuche zusammen mit den Filtereinstellungen aus <<tabelle-artikel-varianten-filtern>> und grenze damit deine Suchergebnisse noch näher ein.
====

[TIP]
.Wieder nach Artikeln in allen Kategorien suchen
====
Wechsele zurück in das Tab *Filter* und entferne das Häkchen neben *Mit Kategorie*. Die nächste Suche erfolgt in allen Kategorien.
====

[#300]
=== Artikel eines Mandanten suchen

//Link führt zur Stelle, wo die Einstellung greift. Also in diesem Fall zur Tab: Verfügbar, Option: Mandant. Link anpassen wenn Seitenstruktur steht
Bist du für die Artikeldaten mehrerer Webshops zuständig? Gehe wie unten beschrieben vor, um gezielt die <<artikel/artikel-verwalten#_verfügbarkeit_für_mandanten_einstellen, Artikel eines Mandanten>> abzurufen.

[.instruction]
Artikel eines Mandanten suchen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Wechsele in das Tab *Mandant* in der Spalte links.
. Klicke auf einen Mandanten. +
→ Die Artikel des Mandanten werden in der Artikelübersicht angezeigt.

[TIP]
.Mandant mit Kategorie und Filter kombinieren
====
Klicke ganz links auf das Ordner-Symbol (icon:folder[role="darkGrey"]) eines Mandanten und dann auf eine darin enthaltene Kategorie. Die Suchergebnisse werden auf Artikel einer bestimmten Kategorie _und_ eines bestimmten Mandanten eingegrenzt. Verwende die Mandantensuche auch zusammen mit den Filtereinstellungen aus <<tabelle-artikel-varianten-filtern>> und grenze damit deine Suchergebnisse noch näher ein.
====

[TIP]
.Für einen Mandanten _nicht verfügbare_ Artikel suchen
====
Setze ein Häkchen neben *Nicht verfügbar* und klicke auf einen Mandanten. Die für den Mandanten nicht verfügbaren Artikel werden in der Artikelübersicht angezeigt.
====

[#400]
=== Varianten im Artikeldatensatz suchen

Artikel beinhalten immer eine oder mehrere Varianten. Beim Öffnen eines Artikels wird immer die erste Variante, d.h. die <<artikel/einleitung/struktur#600, Hauptvariante>>, automatisch mit geöffnet. Aber wie kommst du an die weiteren Untervarianten des Artikels ran? Gehe wie unten beschrieben vor, um die einzelnen Varianten eines Artikels zu suchen.

[.instruction]
Varianten im Artikel suchen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Varianten*.
. Wähle die *Filter*. Beachte <<tabelle-varianten-filtern>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die gefilterten Varianten werden innerhalb des Artikeldatensatzes angezeigt.

[[tabelle-varianten-filtern]]
.Varianten im Artikeldatensatz suchen
[cols="1,2"]
|====
|Filter |Erläuterung

|*ID*
|ID eingeben, um nach der Variante mit dieser ID zu suchen.

|*Variantennummer*
|Variantennummer eingeben, um nach der Variante mit dieser Nummer zu suchen.

|*Ext. Varianten-ID*
|ID eingeben, um nach der Variante mit dieser externen Varianten-ID zu suchen.

|*Barcode*
|Barcode eingeben, um nach der Variante mit diesem Code zu suchen.

|*Attribute*
|Attributwert oder *ALLE* wählen, um nach Varianten mit diesem Attributwert zu suchen. Attribute werden dynamisch geladen. Nur mit Varianten verknüpfte Attribute werden also angezeigt.
|====

[TIP]
.Varianten lieber direkt in der Hauptübersicht sehen?
====
Verwende die in <<tabelle-artikel-varianten-filtern>> beschriebenen Filter, um Varianten anstatt im Artikeldatensatz direkt in der Hauptübersicht zu sehen. Wähle beim Filter <<artikel/einleitung/suche#tabellentyp, Tabellentyp>> die Option *Varianten* oder *Erweitert*. Verwende zusätzlich die Filter *Varianten-ID* oder *Variantennummer*, um gezielt nach bestimmten Varianten zu suchen.
====

[#500]
=== Standard-Suchverhalten anpassen

//Beide Links anpassen wenn Seitenstruktur steht
Soll ein <<artikel/artikel-verwalten#_in_artikelübersicht_angezeigte_preise_und_barcodes_anpassen, bestimmter Verkaufspreis oder Barcode>> in der Artikelübersicht dargestellt werden? Möchtest du selbst definieren, <<artikel/artikel-verwalten#385, welche Artikelparameter vom Suchindex erfasst>> werden? Mit plentymarkets kannst du das Suchverhalten nach deinen Bedürfnissen anpassen!

[#600]
== Mit Suchergebnissen arbeiten

//Link <<artikel/artikel-verwalten#30, manuell zu bearbeiten>> ändern sobald neue Seiten-Struktur steht
Hast du die <<artikel/einleitung/suche#100, Suchoptionen in der Spalte links>> verwendet, werden dir die Suchergebnisse in einer Übersicht rechts angezeigt. Klicke direkt auf einen Artikel in der Übersicht, um den Artikeldatensatz zu öffnen und <<artikel/artikel-verwalten#30, manuell zu bearbeiten>>.

[#700]
=== Spalten- und Sortierreihenfolge anpassen

Wenn du mit dem Mauszeiger über die Spaltenüberschriften fährst, werden weitere Symbole eingeblendet. Nutze diese Symbole, um die Ansicht nach deinen Bedürfnissen anzupassen.

* Welche Spalten sollen in der Tabelle enthalten sein? Klicke auf *Ansicht einrichten* (icon:gear[role="darkGrey"]) und wähle allen von dir gewünschten Spalten (icon:check-square[role="blue"]).
* Sollen bestimmte Spalten weiter rechts oder links dargestellt werden? Sobald dein Mauszeiger seine Form verändert (icon:arrows[role="darkGrey"]), kannst du die Spalten verschieben. Klicke einfach auf den Spaltenkopf und ziehe die Spalte in die gewünschte Position.
* Sollen Nummern absteigend oder aufsteigend sortiert werden? Klicke auf das kleine Dreieck (icon:caret-down[role="darkGrey"]), um die Sortierreihenfolge anzupassen.

[#800]
=== Symbole in der Übersicht

Siehst du die Spalte *Aktionen* in der Tabelle? Darunter sind einige Symbole, die dir helfen, deine Artikel schnell und unkompliziert zu verwalten.

//Baue ein Link um "<<Darstellung des Artikels im Webshop>>" ein, sobald das Kapitel steht
//##<<Notiz für die Variante>>## auch ändern, sobald neue Seiten-Struktur steht
* Klicke auf *Artikel bearbeiten* (icon:pencil[role="yellow"]), um den Artikeldatensatz zu öffnen. Klicke alternativ direkt auf den Artikel in der Übersicht.
* Klicke auf *Sichtbar im Webshop* (icon:eye[role="blue"]), um die Darstellung des Artikels im Webshop zu prüfen. Wird das Symbol ausgekreuzt, ist der Artikel *Unsichtbar im Webshop* (icon:eye[role="blue", stack="times, blue", stackPosition="lr"]).
* Klicke auf *Listing* (icon:bars[role="yellow", stack="eye, yellow", stackPosition="lr"]), um eine Übersicht aller Listings oder Auktionen mit dieser Artikel-ID zu sehen. Wird das Symbol ausgegraut, wurden noch keine Listings für den Artikel angelegt.
* Klicke auf *Neues Listing* (icon:bars[role="green", stack="plus, green", stackPosition="lr"]), um diesen Artikel in einem <<maerkte/ebay/ebay-einrichten#3400, Listing oder Auktion auf eBay>>, <<maerkte/hood#2300, Hood>> oder <<maerkte/ricardo-ch#1900, ricardo>> zu verkaufen.
* Klicke auf *Notiz hinzufügen* (icon:calendar-minus-o[role="green", stack="plus, green", stackPosition="lr"]), um eine <<artikel/artikel-verwalten#2090, Notiz für die Variante>> zu schreiben.

[TIP]
.Weitere Symbole im Artikeldatensatz
====
//Baue ein Link um <<weitere Symbole in der Tab-Leiste>> ein, sobald das Kapitel steht
Hast du einen Artikel bereits geöffnet, findest du weitere Symbole in der Tab-Leiste.
====

[#900]
== Beispielartikel

[#1000]
=== Beispielartikel verstehen

include::../../../../schnelleinstieg/_textblocks/beispielartikel-verstehen.adoc[]

[#1100]
==== Beispielartikel anzeigen

include::../../schnelleinstieg/_textblocks/beispielartikel-anzeigen.adoc[]

[#1200]
=== Beispielartikel löschen

include::../../schnelleinstieg/_textblocks/beispielartikel-loeschen.adoc[]
