= Was ist Vererbung?
:lang: de
include::{includedir}/_header.adoc[]
:description: Lerne, wie deine Varianten Daten und Einstellungen von der Hauptvariante erben.
:position: 20
:url: artikel/einleitung/vererbung
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

Die <<artikel/einleitung/struktur#600, Hauptvariante>> eines Artikels unterscheidet sich von den Untervarianten dadurch, dass ihre Daten weitergegeben, also vererbt werden können. Die Hauptvariante ist also eine Elternvariante, die bestimmte Daten an ihre Kinder vererbt.

Die Vererbungsfunktion ist standardmäßig aktiviert. Wenn eine neue Variante eines Artikels erstellt wird, erbt diese Variante Einstellungen der Hauptvariante, solange keine davon abweichenden Daten gespeichert werden.

[#100]
== Arten von Vererbung

Es gibt zwei Arten von Vererbung in plentymarkets:

* Einzelvererbung
* 1-zu-N-Vererbung

Bei der _Einzelvererbung_ werden einzelne Einstellungen von der Hauptvariante an die Untervariante weitergegeben. Beispielsweise wird der Umsatzsteuersatz an der Hauptvariante gespeichert. Solange kein abweichender Umsatzsteuersatz an einer Untervariante gespeichert wird, wird diese Einstellung von der Hauptvariante geerbt.

//Link <<artikel/artikel-verwalten#240, Kombinationen aus Preisen und Bedingungen>> ändern sobald neue Seiten-Struktur steht
Bei der _1-zu-N-Vererbung_ werden vollständige Datensätze von der Hauptvariante an die Untervariante weitergegeben. Beispielsweise werden unterschiedliche <<artikel/artikel-verwalten#240, Kombinationen aus Preisen und Bedingungen>> an der Hauptvariante gespeichert. Solange keine abweichenden Preise an einer Untervariante gespeichert werden, werden alle Preise und Bedingungen von der Hauptvariante geerbt.

[#200]
== Vererbungsverhalten steuern

Beim Erstellen einer Variante werden die vererbbaren Einstellungen der Hauptvariante an die erstellte Variante vererbt. Sind für eine Variante andere Einstellungen erforderlich, muss die Vererbung an die Variante also deaktiviert und es müssen neue Einstellungen vorgenommen werden.

<<tabelle-vererbungseinstellungen>> stellt die verschiedenen Einstellungsarten von Vererbung dar. Die Tabelle beschreibt die Darstellung, das Verhalten und die Deaktivierung der Vererbung.

[[tabelle-vererbungseinstellungen]]
.Vererbungseinstellungen
[cols="1,3,3"]
|====
|Einstellungsart |Darstellung |Deaktivierung

|*Dropdown-Liste*
|Der erste Wert der Dropdown-Liste entspricht der Einstellung der Hauptvariante. Geerbte Werte werden in grauer Schrift angezeigt. Auch leere Felder werden vererbt.
|Die Vererbung wird deaktiviert, sobald ein anderer Wert gewählt wird.

|*Checkbox*
|Vererbbare Checkboxen haben drei mögliche Zustände: +
*Aktiviert* = Häkchen +
*Deaktiviert* = Kein Häkchen +
*Vererbt* = Rot durchgestrichen, daneben Checkbox mit der Einstellung der Hauptvariante
|Auf durchgestrichenes Kästchen klicken, um die Vererbung zu deaktivieren.

|*Textfeld*
|Geerbte Werte werden in grauer Schrift dargestellt. Auch ein leeres Feld wird vererbt.
|Die Vererbung wird automatisch deaktiviert, wenn ein Textfeld geleert, mit Text befüllt oder vererbter Inhalt geändert wird. +
Um einen leeren Wert in der Variante zu erzielen, muss der Wert in der Hauptvariante leer sein und stattdessen an den Varianten gepflegt werden.

|*Textfelder mit 1:n-Verknüpfung*
|Geerbte Werte werden in grauer Schrift dargestellt. +
Es werden entweder alle oder keine Daten vererbt. Eine Auswahl/Teilvererbung ist nicht möglich.
|Deaktivierung erfolgt über Schaltfläche im Header-Bereich. +
Die Vererbung wird außerdem automatisch deaktiviert, wenn ein Wert an der Variante geändert oder hinzugefügt wird. Nicht geänderte Werte werden aus der Vererbung übernommen und direkt an der Variante gespeichert. Wird die Vererbung wieder aktiviert, werden alle Werte gelöscht und wieder aus der Hauptvariante übernommen.
|====

[#300]
== Vererbung bei Wechsel der Hauptvariante

Du hast die Möglichkeit, eine andere Variante eines Artikels zur Hauptvariante zu machen. Dabei werden die vererbbaren Werte der Hauptvariante mit den Werten der weiteren Varianten abgeglichen. Bei einem Wechsel der Hauptvariante bleiben alle Werte erhalten und die folgende Vererbungslogik greift:

* Für Werte der Varianten, die mit den Werten der neuen Hauptvariante identisch sind, wird die Vererbung automatisch aktiviert.
* Werte, die nicht mit dem Wert der neuen Hauptvariante übereinstimmen, werden direkt an der Variante gespeichert, also nicht vererbt.
