= Hinzugefügte Plugins installieren
:lang: de
include::{includedir}/_header.adoc[]
:author: team-plugin-core
:keywords: plugin, plug in, plug-in, erweiterung, plugin-set, plug-in-set, plugin installieren, plug-in installieren, plug in installieren, backend-plugin-set, backend-plug-in-set, bereitstellen, veröffentlichen, mandant
:description: Alles zur Installation von Plugins und dem Verknüpfen mit Mandanten und Benutzerkonten.
:position: 20
:id: EGDTDOH

[.previous-next-navigation]
<<plugins/plugins-system-hinzufuegen#, icon:long-arrow-left[] Plugins dem System hinzufügen>>
<<plugins/installierte-plugins-konfigurieren#, Installierte Plugins konfigurieren icon:long-arrow-right[]>>

'''

Um Plugins nutzen zu können, musst du sie zunächst in einem Plugin-Set einbinden und das Plugin-Set bereitstellen. <<plugin-set-erstellen, Erstelle oder kopiere>> zunächst ein neues Plugin-Set. Dort kannst du das Plugin <<plugin-installieren, installieren und bereitstellen>>. Um das Plugin zu nutzen, verknüpfst du es abschließend noch mit einem <<plugin-set-verknuepfen, Mandanten>> oder <<backend-plugin-set, Benutzerkonto>>.

[#plugin-set-erstellen]
== Plugin-Set erstellen

Plugins können nur als Teil eines Plugin-Sets genutzt werden. Bevor du Plugins installieren kannst, musst du also zunächst ein neues Plugin-Set erstellen. Selbst wenn du Plugins in einem bestehenden Plugin-Set installieren möchtest, solltest du in einer Kopie des Sets arbeiten, damit du Änderungen bei Bedarf leicht verwerfen kannst.

include::./_textblocks/tips/sicherheitskopie.adoc[]

include::./_textblocks/instructions/plugin-set-erstellen.adoc[]

Du kannst den Namen jederzeit in den *Plugin-Set-Einstellungen* (icon:cog[]) ändern.

//Remove once there's a more complete error message in the back end.
include::./_textblocks/warnings/plugin-set-name.adoc[]

[#plugin-installieren]
== Plugin in einem Plugin-Set installieren

Der gesamte Installationsprozess eines Plugins umfasst drei Schritte. Zunächst musst du das Plugin in einem Plugin-Set installieren. Dabei werden die Dateien des Plugins auf dein System übertragen. Im zweiten Schritt aktivierst du das Plugin. Dadurch gibst du an, welche Plugins beim Laden deines Systems oder Webshops mit berücksichtigt werden soll. Abschließend stellst du das Plugin-Set mit allen aktiven Plugins bereit. Dadurch schließt du den Installationsvorgang ab.

include::./_textblocks/instructions/plugin-installieren.adoc[]

[#plugin-set-verknuepfen]
== Plugin-Set live schalten

Wenn du mit deinem Plugin-Set zufrieden bist, kannst du es live schalten, indem du es mit einem deiner Mandanten verlinkst. Gehe dazu wie im Folgenden beschrieben vor.

include::./_textblocks/tips/plugin-set-vorschau.adoc[]

include::./_textblocks/instructions/plugin-set-verknuepfen.adoc[]

[#backend-plugin-set]
== Plugin-Set mit Benutzerkonto verknüpfen

include::../basics/arbeiten-mit-plentymarkets/_textblocks/backend-plugin-sets.adoc[]

'''

[.previous-next-navigation]
<<plugins/plugins-system-hinzufuegen#, icon:long-arrow-left[] Plugins dem System hinzufügen>>
<<plugins/installierte-plugins-konfigurieren#, Installierte Plugins konfigurieren icon:long-arrow-right[]>>