= Installierte Plugins aktualisieren
:lang: de
include::{includedir}/_header.adoc[]
:author: none
:keywords: plugin, plug in, plug-in, erweiterung, plugin-update, plug-in-update, plugin aktualisieren, plug in aktualisieren, plug-in aktualisieren, git, branch, commit
:description: Installierte Plugins aktualisieren.
:position: 40
:id: YTCRHEX

Manchmal stellen Plugin-Anbieter eine neuere Version ihres Plugins zu Verfügung. Hast du so ein Plugin bereits in einem Plugin-Set installiert, musst du es aktualisieren, um es in der neueren Version zu nutzen. Da es sich hierbei um eine Änderung an dem Plugin-Set handelt, solltest du vor dem Aktualiseren des Plugins eine Kopie des Sets erstellen.

include::./_textblocks/tips/sicherheitskopie.adoc[]

include::./_textblocks/instructions/plugin-set-erstellen.adoc[]

Die Möglichkeiten zum Aktualisieren unterscheiden sich, je nachdem ob du das Plugin <<marketplace-plugins, auf plentyMarketplace erworben>> oder <<git-plugins, über Git eingebunden>> hast.

[#marketplace-plugins]
== Marketplace-Plugins

Wenn ein Update für ein Plugin verfügbar ist, wird in der Spalte *Aktion* die Schaltfläche *Aktualisieren* farbig gekennzeichnet.

include::./_textblocks/instructions/plugin-aktualisieren.adoc[]

Es ist bei Marketplace-Plugins nicht möglich, die Version auf eine ältere herunterzustufen. Wenn du eine ältere Version eines Plugins verwenden möchtest, musst du es <</plugins/installierte-plugins-entfernen#plugin-aus-plugin-set-loeschen, löschen>> und dann <<plugins/hinzugefuegte-plugins-installieren, neu installieren>>.

[#git-plugins]
== Git-Plugins

Git-Plugins können auf unterschiedliche Arten aktualisiert werden. Um mit einer neueren Version des aktuellen Branches zu arbeiten, kannst du den <<branch-pullen, Branch pullen>>. Du hast aber auch die Möglichkeit, mit dem Stand eines anderen Branches zu arbeiten, indem du den <<branch-wechseln, Branch wechselst>>, oder einen <<commit-wechseln, beliebigen Commit auszuchecken>>, wenn du eine bestimmte ältere Version des Plugins verwenden möchtest.

[#branch-pullen]
=== Branch pullen

Wenn in deinem Git-Repository ein neuerer Stand deines Plugins vorliegt und du diesen Stand in plentymarkets verwenden möchtest, kannst du den Branch pullen.

include::./_textblocks/instructions/git-branch-pullen.adoc[]

[#branch-wechseln]
=== Auf Branch wechseln

Du kannst zwischen den Branches eines Git-Repositorys wechseln. Bei der Auswahl des Branches handelt es sich um eine lokale Einstellungen. Das heißt, es kann für dasselbe Plugin in jedem Set ein anderer Branch ausgewählt werden. Somit kannst du beispielsweise den stabilen Branch in deinem aktiven Plugin-Set verwenden und gleichzeitig in einem inaktiven Set auf einem anderen Branch ein neues Feature testen.

include::./_textblocks/instructions/git-branch-wechseln.adoc[]

[#commit-wechseln]
=== Auf Commit wechseln

Wenn du einen anderen Stand deines Repositorys verwenden möchtest, für diesen Stand aber keinen eigenen Branch erstellt hast, kannst du auch auf einzelne Commits zugreifen.

include::./_textblocks/instructions/git-commit-wechseln.adoc[]