= Installierte Plugins konfigurieren
:lang: de
include::{includedir}/_header.adoc[]
:author: none
:keywords: plugin, plug in, plug-in, erweiterung, plugin konfigurieren, plug in konfigurieren, plug-in konfigurieren, plugin-konfiguration, plug-in-konfiguration, plugin-einstellungen, plug-in-einstellungen, container-verknüpfungen, konfiguration importieren, konfigurationsimport, konfiguration exportieren, konfigurationsexport, einstellungen exportieren, einstellungsexport, einstellungen importieren, einstellungsimport
:description: Optionen zum Konfigurieren von Plugins.
:position: 30
:id: H4HJIKA

[.previous-navigation]
<<plugins/hinzugefuegte-plugins-installieren#, icon:long-arrow-left[] Hinzugefügte Plugins installieren>>

'''

include::./_textblocks/notes/installierte-plugins-konfigurieren.adoc[]

Auf dieser Seite findest du Themen, die die Konfiguration von Plugins allgemein betreffen. Dazu gehören der <<lokale-vs-globale-konfiguration,Unterschied zwischen lokalen und globalen Einstellungen>> sowie das <<konfiguration-exportieren-importieren,Exportieren und Importieren von lokalen Konfigurationen>>. Außerdem werden <<container-verknuepfungen,Container-Verknüpfungen>> erläutert.
include::./_textblocks/explanations/container-verknuepfung.adoc[]

[#lokale-vs-globale-konfiguration]
== Lokale vs. globale Konfiguration

Plugin-Konfigurationen können entweder auf lokaler oder globaler Ebene definiert werden.

Eine lokale Konfiguration wird in der Detailansicht des Plugins vorgenommen. Wenn ein Plugin auf lokaler Ebene konfiguriert wird, ist diese Konfiguration nur für ein einziges Plugin-Set gültig. Das heißt, wenn das Plugin in zwei oder mehr Plugin-Sets installiert ist, muss es in jedem Set separat eingerichtet werden. Wird das Plugin gelöscht, wird auch die Konfiguration gelöscht.

Eine globale Konfiguration wird im Menü *Einrichtung* vorgenommen. Wenn ein Plugin auf globaler Ebene konfiguriert wird, ist diese Konfiguration für alle Plugin-Sets gültig, in denen das Plugin installiert ist.

// @TODO
// Add that global configs are retained according to our BPs (after writing said BPs), but that we cannot guarantee it.

include::./_textblocks/importants/plugin-konfigurationsausnahmen.adoc[]

[#konfiguration-exportieren-importieren]
== Lokale Konfigurationen exportieren und importieren

Du kannst lokale Konfigurationen eines Plugins exportieren und importieren. Durch das Exportieren und Importieren kannst du die Konfiguration von bestimmten Plugins leicht von einem Plugin-Set auf ein anderes übertragen. Gehe dazu wie folgt vor:

include::./_textblocks/instructions/plugin-konfiguration-exportieren.adoc[]

include::./_textblocks/instructions/plugin-konfiguration-importieren.adoc[]

include::./_textblocks/warnings/import-limitierung.adoc[]

include::./_textblocks/tips/batch-plugin-konfiguration.adoc[]

[#container-verknuepfungen]
== Container-Verknüpfungen

include::./_textblocks/explanations/container-verknuepfung.adoc[]
Du findest alle Container-Verknüpfungen im Menü *CMS » Container-Verknüpfungen*. Welche Container du verknüpfen kannst, kannst du der Anleitung des jeweiligen Plugins entnehmen.

In manchen Plugins sind Container-Verknüpfungen bereits vordefiniert. Dabei handelt es sich um sogenannte Standard-Container-Verknüpfungen. Um Standard-Container-Verknüpfungen zu wählen, gehe wie folgt vor:

include::./_textblocks/instructions/standard-container-verknuepfung.adoc[]

include::./_textblocks/warnings/vorhandene-verknuepfungen-geschuetzt.adoc[]

'''

[.previous-navigation]
<<plugins/hinzugefuegte-plugins-installieren#, icon:long-arrow-left[] Hinzugefügte Plugins installieren>>
