= Installierte Plugins entfernen
:lang: de
include::{includedir}/_header.adoc[]
:author: team-plugin-core
:keywords: plugin, plug in, plug-in, erweiterung, entfernen, löschen, deaktivieren, git repository, git, repository
:description: Plugins aus Plugin-Sets entfernen.
:position: 50
:id: MSCTNZP

Es gibt verschiedene Möglichkeiten, installierte Plugins zu entfernen. Du kannst Plugins einzeln <<plugin-deaktivieren, deaktiveren>>, damit sie nicht mehr in deinem Webshop und Backend geladen werden oder sie vollständig <<plugin-aus-plugin-set-loeschen, aus einem Plugin-Set löschen>>. Wenn du alle Plugins eines Sets löschen möchtest, kannst du stattdessen <<plugin-set-löschen, das Plugin-Set selbst löschen>>.

Du kannst Plugins, die du auf plentyMarketplace erworben hast, nicht vollständig aus deinem System entfernen. Handelt es sich allerdings um ein Git-Plugin, kannst du <<git-repository-loeschen, das zugehörige Repository löschen>>.

[#plugin-deaktivieren]
== Plugin deaktivieren

Wenn du ein Plugin deaktivierst, wird es nicht mehr in deinem Webshop und Backend geladen. Diese Änderung wird direkt übernommen, ohne dass ein erneutes Bereitstellen des Plugin-Sets notwendig ist. So deaktivierte Plugins können auf gleichem Wege auch wieder aktiviert werden, ohne dass das Plugin-Set bereitgestellt werden muss.

Deaktivierte Plugins werden beim Bereitstellen eines Plugin-Sets nicht berücksichtigt. Wenn du ein Plugin-Set einmal erfolgreich bereitgestellt hast, ohne dass ein bestimmtes Plugin aktiviert war, musst du nach dem Aktivieren des Plugins <<plugins/hinzugefuegte-plugins-installieren#plugin-installieren, das Plugin-Set erneut bereitstellen>> bevor das Plugin aktiv ist.

Ob du ein Plugin durch Aktivieren und Deaktivieren aktiv oder inaktiv schalten kannst, kannst du im Menü *Plugins » Plugin-Übersicht* an der Spalte *Aktive Version* erkennen. Ist hier eine Versionsnummer eingetragen, musst du das Set nicht bereitstellen, um das Plugin aktiv zu schalten.

Du solltest ein Plugin dann deaktivieren, wenn du es nur vorübergehend nicht nutzen möchtest. Anders als beim Löschen eines Plugins, bleibt beim Deaktivieren die <<plugins/installierte-plugins-konfigurieren#lokale-vs-globale-konfiguration, lokale Konfiguration>> des Plugin erhalten.

Zum Deaktivieren eines Plugins, klicke im Menü *Plugins » Plugin-Übersicht* auf die Schaltfläche *Aktiv* (icon:globe[role=skyBlue]).

[#plugin-aus-plugin-set-loeschen]
== Plugin aus einem Plugin-Set löschen

Beim Löschen eines Plugins werden alle Dateien des Plugins vollständig aus dem Plugin-Set entfernt. Nutze diese Funktion, wenn du ein Plugin nicht mehr verwenden möchtest.

include::./_textblocks/explanations/plugin-loeschen-einstellungen.adoc[]

Wenn du ein Plugin löschen möchtest, gehe wie folgt vor:

include::./_textblocks/instructions/plugin-loeschen.adoc[]

Nachdem du ein Plugin gelöscht hast, findest du es unter deinen nicht installierten Plugins. Handelt es sich um ein Plugin, das du auf plentyMarketplace erworben hast, ist es nicht möglich, das Plugin komplett aus dem System zu entfernen.

[#plugin-set-loeschen]
== Plugin-Set löschen

Beim Löschen eines Plugin-Sets werden die Dateien aller im Set enthaltenen Plugins vollständig aus deinem aktiven Speicher entfernt. Nutze diese Funktion, wenn du keins der Plugins mehr in dieser Konfiguration verwenden möchtest.

include::./_textblocks/explanations/plugin-loeschen-einstellungen.adoc[]

Wenn du ein Plugin-Set löschen möchtest, gehe wie folgt vor:

include::./_textblocks/instructions/plugin-set-loeschen.adoc[]

[#git-repository-loeschen]
== Git-Repository löschen

Wenn du ein Git-Plugin nicht mehr benötigst, kannst du das zugehörige Repository löschen, um das Plugin vollständig aus deinem System zu entfernen. Damit du ein Git-Repository löschen kannst, musst du vorher <<plugin-aus-plugin-set-loeschen, das zugehörige Plugin aus allen Plugin-Sets löschen>>.

include::./_textblocks/instructions/git-repository-loeschen.adoc[]
