= Plugins dem System hinzufügen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Plugins, Erweiterungen, Funktionen
:description: So fügen Sie Plugins zu plentymarkets hinzu.
:position: 10
:url: plugins/neue-plugins

[#marketplace-plugins-kaufen]
== Marketplace-Plugins kaufen

link:http://marketplace.plentymarkets.com/de/[plentyMarketplace^] ist die neue Plattform für die Distribution von hauseigenen und externen plentymarkets Software-Erweiterungen. Diese Plattform ermöglicht Ihnen einen leichten Zugang zu Plugins, damit Sie schnell und einfach von allen Vorteilen profitieren. Gehen Sie wie folgt vor, um ein Plugin zu kaufen.

include::_textblocks/instructions/marketplace-plugin-kaufen.adoc[]

[[tabelle-marketplace-kategorien]]
include::_textblocks/tables/marketplace-kategorien.adoc[]

[[tabelle-kaufoptionen]]
include::_textblocks/tables/marketplace-kaufoptionen.adoc[]

[#git-plugins-hinzufuegen]
== Plugins über Git hinzufügen

Wenn du plentymarkets erweitern möchtest, aber kein Plugin mit der entsprechenden Funktionalität auf plentyMarketplace finden, hast du die Möglichkeit, deinem System Plugins über Git hinzuzufügen. Manche externe Entwickler bieten Plugins auf diesem Weg an. Wenn du weitere Informationen zu so verfügbaren Plugins erhalten möchtest, solltest du direkt mit Entwicklern Kontakt aufnehmen. Nutze dafür entweder die link:https://www.plentymarkets.eu/service/partneragenturen/search/plugin-30/?aoff=s[Partnerübersicht^], schreibe eine Nachricht in der Forumskategorie link:https://forum.plentymarkets.com/c/suche-biete/suche-biete-plugins[Suche/Biete^] oder erstelle eine link:https://marketplace.plentymarkets.com/plentyprojects[neue Projektanfrage^] auf plentyMarketplace.

[[tabelle-git-plugins-hinzufuegen]]
include::_textblocks/tables/git-repository-verwaltung.adoc[]

[tabelle-git-plugin-detailansicht]]
include::_textblocks/tables/git-plugin-detailansicht.adoc[]

[#git-plugins-hinzufuegen]
=== Git-Plugins zum System hinzufügen

Möchtest du deinem System ein privates Repository hinzufügen, wird zusätzlich zur URL des Repositorys ein persönlicher Zugriffstoken benötigt. Dabei unterscheidet sich der Vorgang zum Erzeugen des Tokens leicht von Seite zu Seite. Hier werden exemplarisch die Vorgänge auf GitHub und Bitbucket beschrieben. Wenn du eine andere Seite nutzst und weitere Informationen benötigst, ziehe bitte die Dokumentation der entsprechenden Seite zu Rat.

[.collapseBox]
.GitHub-Zugriffstoken
--
include::_textblocks/instructions/git-zugriffstoken-github.adoc[]
--

[.collapseBox]
.Bitbucket-Zugriffstoken
--
include::_textblocks/instructions/git-zugriffstoken-bitbucket.adoc[]
--

Damit hast du jetzt alle notwendigen Informationen, um das Git-Repository deinem plentymarkets System hinzuzufügen.

include::_textblocks/tips/git-oeffentliches-repository.adoc[]

include::_textblocks/instructions/git-repository-hinzufuegen.adoc[]

include::_textblocks/warnings/git-valide-plugin-json.adoc[]

[#git-branches]
=== Zwischen Branches eines Git-Plugins wechseln

Es ist üblich, in einem Git-Repository mit verschiedenen Branches zu arbeiten, um Änderungen an Dateien vorzunehmen, ohne dass diese Änderungen direkte Auswirkungen auf die eigentliche Codebasis haben. Dadurch kann neuer Code vor dem tatsächlichen Implementieren nochmal überprüft werden. Auch in plentymarkets ist es möglich, mit verschiedenen Branches eines Repositorys zu arbeiten.

include::_textblocks/instructions/git-branch-wechseln.adoc[]

Bei der Auswahl des Branches handelt es sich um eine lokale Einstellungen. Das heißt, es kann für dasselbe Plugin in jedem Set ein anderer Branch ausgewählt werden. Somit kannst du beispielsweise den stabilen Branch in deinem aktiven Plugin-Set verwenden und gleichzeitig in einem inaktiven Set auf einem anderen Branch ein neues Feature testen.

[#git-commits]
=== Auf Commits wechseln

Wenn du eine andere Version deines Repositorys aktivieren möchtest, für diese Version aber keinen eigenen Branch erstellt hast, kannst du auch auf einzelne Commits zugreifen.

include::_textblocks/instructions/git-commit-wechseln.adoc[]

[#git-repository-loeschen]
=== Git-Repository aus dem System entfernen

Wenn ein Repository nicht mehr benötigt wird, kannst du es komplett aus dem System entfernen. Beachte, dass Repositorys nur gelöscht werden können, wenn das entsprechende Plugin in keinem Plugin-Set mehr installiert ist.

include::_textblocks/instructions/git-repository-loeschen.adoc[]