= Plugins dem System hinzufügen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Plugins, Erweiterungen, Funktionen
:description: So fügen Sie Plugins zu plentymarkets hinzu.
:position: 10
:url: plugins/neue-plugins

[#marketplace-plugins-kaufen]
== Marketplace-Plugins kaufen

link:http://marketplace.plentymarkets.com/de/[plentyMarketplace^] ist die neue Plattform für die Distribution von hauseigenen und externen plentymarkets Software-Erweiterungen. Diese Plattform ermöglicht Ihnen einen leichten Zugang zu Plugins, damit Sie schnell und einfach von allen Vorteilen profitieren. Gehen Sie wie folgt vor, um ein Plugin zu kaufen.

[.instruction]
Plugin kaufen:

. Öffnen Sie das Menü **Plugins » Plugins-Übersicht**.
. Klicken Sie auf **plentyMarketplace**. +
→ Der Marktplatz wird in einem neuen Tab geöffnet. +
→ _Oder_: Melden Sie sich direkt auf link:http://marketplace.plentymarkets.com/de/[plentyMarketplace^] mit Ihren Zugangsdaten aus dem Service-Center an.
. Wählen Sie ein Plugin aus einer Kategorie. Eine Übersicht aller Kategorien finden Sie in der Tabelle <<tabelle-marketplace-kategorien>>.
. Klicken Sie in der Detailansicht des Plugins auf **Plugin kaufen**. Eine Übersicht aller Kaufoptionen finden Sie in der Tabelle <<tabelle-kaufoptionen>>. +
→ Das Fenster **Kasse** wird geöffnet.
. Nehmen Sie die Nutzungsbedingungen zur Kenntnis.
. Klicken Sie auf **Jetzt kaufen**. +
→ Das gekaufte Plugin ist als nicht installiertes Plugin im Menü **Plugins » Plugin-Übersicht** verfügbar.

[[tabelle-marketplace-kategorien]]
.plentyMarketplace-Kategorien
[cols=”1,3”]
|====
|Kategorie |Erläuterung

|*Channels >> Marktplätze*
|Anbindung an andere Marktplätze wie Rakuten und idealo. Weitere Informationen zum Anbinden von von plentymarkets entwickelten Marktplätzen unter *Märkte*.

|*Channels >> Online-Shop*
|Verbindung zu anderen Shopsystemen wie Shopify. Enthält außerdem Templates für den Online-Shop. Weitere Informationen zu von plentymarkets entwickelten Templates unter *Online-Shop*.

|*Channels >> Preisportale*
|Fügen Exportformate für den elastischen Export hinzu. Weitere Informationen zu allen Exportformaten hier.

|*Storefront >> Themes*
|Ändern das Design des Online-Shops.

|*Storefront >> Widgets*
|Fügen dem Online-Shop neue Elemente wie Schaltflächen für soziale Netzwerke oder Kontaktinformationen hinzu.

|*Payment*
|Geben Kunden die Möglichkeit, andere Zahlungsmöglichkeiten zu verwenden. Weitere Informationen zum Installieren und Einrichten dieser Plugins in der Artikelbeschreibung auf plentyMarketplace.

|*Integration*
|Zusätzliche Funktionalität für das plentymarkets System durch externe Tools.

|*Services >> Support* +
*Services >> Einrichtung*
|Agenturen bieten verschiedene, auf individuelle Ansprüche ausgelegte, Leistungen an.

|*Services >> Hardware*
|Verkauf von Kassensystemen. Weitere Informationen zum Kassensystem plentyPOS unter *Kassensystem/POS*.
|====

[[tabelle-kaufoptionen]]
.Kaufoptionen
[cols=”1,3”]
|====
|Option |Erläuterung

|*Testen*
|Plugin kann in vollem Umfang 30 Tage lang umsonst genutzt werden. Nicht mehr möglich, nachdem das Plugin bereits abonniert wurde. Ablaufdatum kann im *Mein Konto*-Bereich eingesehen werden.

|*Kaufen*
|Einmalkauf. Plugins werden teilweise in verschiedenen Umfängen angeboten. Welche Funktionalitäten in welchem Umfang enthalten sind, kann der Artikelbeschreibung entnommen werden.

|*Abonnement*
|Plugins können abonniert werden, um sie in vollem Umfang für einen begrenzten Zeitraum zu nutzen. Je nach Plugin stehen unterschiedliche Zahlungszeiträume zu Verfügung. Abgerechnet wird immer am Anfang eines Zahlungszeitraums. Abonnements laufen nicht automatisch aus, sondern müssen im *Mein Konto*-Bereich gekündigt werden.
|====

[#git-plugins-hinzufuegen]
== Plugins über Git hinzufügen

Wenn Sie plentymarkets erweitern möchten, aber kein Plugin mit der entsprechenden Funktionalität auf plentyMarketplace finden, haben Sie die Möglichkeit, Ihrem System Plugins über Git hinzuzufügen. Manche externe Entwickler bieten Plugins auf diesem Wege an. Wenn Sie weitere Informationen zu so verfügbaren Plugins erhalten möchten, sollten Sie direkt mit Entwicklern Kontakt aufnehmen. Nutzen Sie dafür entweder die link:https://www.plentymarkets.eu/service/partneragenturen/search/plugin-30/?aoff=s[Partnerübersicht^], schreiben Sie eine Nachricht in der Forumskategorie link:https://forum.plentymarkets.com/c/suche-biete/suche-biete-plugins[Suche/Biete^] oder erstellen Sie eine link:https://marketplace.plentymarkets.com/plentyprojects[neue Projektanfrage^] auf plentyMarketplace.

Handelt es sich um ein privates Repository, wird zusätzlich zur URL des Repositorys ein persönlicher Zugriffstoken benötigt. Dabei unterscheidet sich der Vorgang zum Erzeugen des Tokens leicht von Seite zu Seite. Hier werden exemplarisch die Vorgänge auf GitHub und Bitbucket beschrieben. Wenn Sie eine andere Seite nutzen und weitere Informationen benötigen, ziehen Sie bitte die Dokumentation der entsprechenden Seite zu Rate.

[.instruction]
Einen persönlichen Zugriffstoken für private Repositorys auf GitHub erzeugen:

. Öffnen Sie die link:https://github.com/settings/tokens[Tokeneinstellungen^] auf GitHub.
. Klicken Sie auf *Generate new token*. +
→ Geben Sie Ihr Passwort ein, um fortzufahren.
. Geben Sie in das Feld *Token description* eine Beschreibung ein.
. Aktivieren Sie im Menü *Select scopes* das Kontrollkästchen *repo:status*. +
. Klicken Sie auf *Generate token*.
→ Es wird ein neuer Token erzeugt. Dieser wird im nächsten Schritt benötigt, also lassen Sie die Seite geöffnet oder speichern Sie den Token lokal. Wenn Sie den Token speichern, sollten Sie ihn nach dem Hinzufügen des Plugins wieder löschen.

[.instruction]
Einen persönlichen Zugriffstoken für private Repositorys auf Bitbucket erzeugen:

. Öffnen Sie Ihre Kontoeinstellungen auf Bitbucket.
. Öffnen Sie im Bereich **Zugriffsverwaltung** das Menü **App-Passwörter**.
. Klicken Sie auf **App-Passwort erstellen**.
. Geben Sie einen Namen für das Passwort ein und aktivieren das Kontrollkästchen Sie im Bereich **Webhooks**.
. Klicken Sie auf **Erstellen**. +
→ Es wird ein neuer Token erzeugt. Dieser wird im nächsten Schritt benötigt, also lassen Sie die Seite geöffnet oder speichern Sie den Token lokal. Wenn Sie den Token speichern, sollten Sie ihn nach dem Hinzufügen des Plugins wieder löschen.

Damit haben Sie jetzt alle notwendigen Informationen, um das Git-Plugin Ihrem plentymarkets System hinzuzufügen.

[.instruction]
Git-Plugin dem System hinzufügen:

. Öffnen Sie das Menü *Plugins » Git*.
. Klicken Sie auf *Neues Repository hinzufügen*. +
→ Die Repository-Einstellungen werden angezeigt.
. Geben Sie die URL des Repositorys, Ihren Benutzernamen sowie den zuvor erzeugten Zugriffstoken in die dafür vorgesehenen Felder ein.
. Geben Sie den Branch an, der für die Installation verwendet werden soll. Standardmäßig ist hier der master-Branch angegeben, Sie sollten sich aber vom Entwickler des Plugins bestätigen lassen, welches der richtige Branch ist und das Feld entsprechend aktualisieren.
. *Speichern* Sie die Einstellungen. +
→ Die Verbindung zum Git-Repository wird geprüft und hergestellt.

[NOTE]
.Öffentliche Repositorys
====
Bei öffentlichen Repositorys müssen keine tatsächlichen Zugangsdaten als Benutzername und Token eingegeben werden. Die beiden Felder dürfen aber auch nicht leer sein. Geben Sie also jeweils eine beliebige Zeichenfolge ein, beispielsweise „Gast“.
====

[[tabelle-git-plugins-hinzufuegen]]
.Tabellenansicht des Menüs **Plugins >> Git**
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Neues Repository hinzufügen
|Öffnet eine Ansicht, in der Einstellungen für ein neues Repository vorgenommen werden können.

|Name des Git-Repositorys
|Öffnet eine Ansicht, in der Einstellungen für das ausgewählte Repository vorgenommen werden können.

|**Löschen**
|Entfernt das Repository aus dem System. Nicht auswählbar, wenn das Plugin noch in mindestens einem Plugin-Set installiert ist.

|*Repository-URL*
|HTTPS oder HTTP URL des Git-Repositorys.

|*Benutzername*
|Der Benutzername ist Bestandteil der Benutzerdaten des Anbieters (z.B. GitHub) für das Git-Repository. +
Bei öffentlichen Repositorys einen beliebigen Wert in das Feld eingeben, z.B. *Gast*.

|*Token*
|Der Token ist Bestandteil der Benutzerdaten des Anbieters (z.B. GitHub) für das Git-Repository. Neue Tokens können in den Einstellungen des Anbieters erzeugt werden. +
Bei öffentlichen Repositorys einen beliebigen Wert in das Feld eingeben, z.B. *Gast*.

|*Name des zu installierenden Branch (muss gültige plugin.json-Datei enthalten).*
|Das Git-Repository muss eine valide Plugin.json-Datei enthalten. Die Eingabe ist für die Erstinstallation notwendig.
|====

[tabelle-git-plugin-detailansicht]]
.Tabellenansicht des Menüs **Plugins >> Plugin-Übersicht >> Plugin-Detailansicht >> Git**
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Fetch**
|Lädt alle Commits der ausgewählten Branch herunter. Die Liste der Commits wird entsprechend aktualisiert.

|**Pull**
|Lädt alle Commits der ausgewählten Branch herunter und aktualisiert alle Dateien. Die Liste der Commits wird entsprechend aktualisiert.

|**Branch**
|Dropdown-Menü, mit dem zwischen Branches des Repositorys gewechselt werden kann. Der aktuell ausgewählte Branch wird angezeigt.

|**Commit-ID**
|Textfeld für die Auswahl bestimmter Commits.

|**Checkout**
|Wechselt Branch auf die im Textfeld eingegebe Commit-ID, falls diese im Repository vorhanden ist.

|Name des Commits
|Durch Klicken kann der Commit wie über **Checkout** ausgewählt werden. Bestätigung notwendig.

|**Commit-ID in Zwischenablage kopieren.**
|Die ID des Commits wird in die Zwischenablage kopiert und kann dann in das Feld **Commit-ID** eingefügt werden.

|**Auf GitHub ansehen**
|Öffnet die in dem Commit vorgenommenen Änderungen in einem neuen Tab.
|====

[#git-plugins-hinzufuegen]
=== Git-Plugins zum System hinzufügen

[.instruction]
Git-Repository hinzufügen:

. Öffnen Sie das Menü **Plugins >> Git**.
. Klicken Sie auf **Neues Repository hinzufügen**. +
→ Die Ansicht **Repository Einstellungen** wird geöffnet.
. Geben Sie in das Feld **Repository URL** die URL des Git-Repositorys ein, das Sie hinzufügen möchten.
. Geben Sie in das Feld **Benutzername** den Namen Ihres Git-Kontos ein. Wenn Sie ein öffentliches Repository hinzufügen, geben Sie eine beliebige Zeichenfolge ein.
. Geben Sie in das Feld **Passwort oder Token** das mit dem Namen assoziierte Passwort oder den mit dem Namen assoziierten Token ein. Wenn Sie ein öffentliches Repository hinzufügen, geben Sie eine beliebige Zeichenfolge ein.
. Geben Sie in das Feld **Branchname für Installation (Muss valide plugin.json enthalten)** den Namen des Branches ein, auf den Sie standardmäßig zugreifen möchten. Standardmäßig ist **master** angegeben. Sie können nach der Installation zwischen den Branches des Repositorys wechseln. Beachten Sie, dass der ausgewählte Branch eine gültige plugin.json-Datei enthalten muss. Weitere Informationen zur plugin.json-Datei finden Sie auf unserer link:https://developers.plentymarkets.com/marketplace/plugin-requirements#marketplace-pluginjson[Entwicklerseite^] (nur auf Englisch verfügbar).
. **Speichern** Sie die Einstellungen.

[NOTE]
.plugin.json-Datei
====
Wenn ein Plugin keine gültige plugin.json-Datei enthält, führt dies beim Bereitstellen von plugin-Sets zu Fehlern. Deshalb wird beim Hinzufügen von Plugins über Git bereits überprüft, ob eine solche gültige Datei vorliegt.
====

[#git-branches]
=== Zwischen Branches eines Git-Plugins wechseln

Es ist üblich, in einem Git-Repository mit verschiedenen Branches zu arbeiten, um Änderungen an Dateien vorzunehmen, ohne dass diese Änderungen direkte Auswirkungen auf die eigentliche Codebasis haben. Dadurch kann neuer Code vor dem tatsächlichen Implementieren nochmal überprüft werden. Auch in plentymarkets ist es möglich, mit verschiedenen Branches eines Repositorys zu arbeiten.

[.instruction]
Branch wechseln:

. Öffnen Sie das Menü **Plugins >> Plugin-Übersicht**.
. Klicken Sie auf das Plugin-Set, das Sie bearbeiten möchten. +
→ Der Bereich, in dem Sie das ausgewählte Plugin-Set bearbeiten können, wird geöffnet.
. Klicken Sie auf das Git-Plugin, das Sie bearbeiten möchten. +
→ Die Plugin-Detailansicht wird geöffnet.
. Öffnen Sie im Menübaum das Menü **Git**.
. Wählen Sie aus dem Dropdown-Menü **Branch** den Branch aus, zu dem Sie wechseln möchten. +
→ Eine Meldung bestätigt, dass das Wechseln des Branches erfolgreich war. Die Einstellungen werden automatisch gespeichert.

Bei der Auswahl des Branches handelt es sich um eine lokale Einstellungen. Das heißt, es kann für dasselbe Plugin in jedem Set ein anderer Branch ausgewählt werden. Somit können Sie beispielsweise den stabilen Branch in Ihrem aktiven Plugin-Set verwenden und gleichzeitig in einem inaktiven Set auf einem anderen Branch ein neues Feature testen.

[#git-commits]
=== Auf Commits wechseln

Wenn Sie eine andere Version Ihres Repositorys aktivieren möchten, für diese Version aber keinen eigenen Branch erstellt haben, können Sie auch auf einzelne Commits zugreifen.

[.instruction]
Auf Commits wechseln:

. Öffnen Sie das Menü **Plugins >> Plugin-Übersicht**.
. Klicken Sie auf das Plugin-Set, das Sie bearbeiten möchten. +
→ Der Bereich, in dem Sie das ausgewählte Plugin-Set bearbeiten können, wird geöffnet.
. Klicken Sie auf das Git-Plugin, das Sie bearbeiten möchten. +
→ Die Plugin-Detailansicht wird geöffnet.
. Öffnen Sie im Menübaum das Menü **Git**.
. Kopieren Sie die Commit-ID des Commits, auf den Sie wechseln möchten. In der Detailansicht werden die letzten 50 Commits für den ausgewählten Branch angezeigt. Sie können die Commit-ID kopieren, indem Sie in der Zeile des gewünschten Commits auf **Commit-ID in Zwischenablage kopieren.** klicken. Wenn Sie auf einen Commit wechseln möchten, der mehr als 50 Commits zurückliegt, können Sie die gleichen Schritte in der Commits-Übersicht Ihres Git-Repositorys durchführen.
. Fügen Sie die kopierte ID in das Feld **Commit-ID** ein.
. Klicken Sie auf **Checkout**. +
→ **_Oder_**: Wenn Sie auf einen der letzten 50 Commits wechseln möchten, können Sie auch auf den Namen des Commits klicken und den Wechsel durch Klicken auf **Ok** bestätigen. +
→ Eine Meldung bestätigt, dass das Wechseln auf den eingegeben Commit erfolgreich war und als Branch wird **Head@Commit-ID** angezeigt. Die Einstellungen werden automatisch gespeichert.

[#git-plugins-loeschen]
=== Git-Plugins aus dem System entfernen

Wenn ein Git-Plugin nicht mehr benötigt wird, können Sie es komplett aus dem System entfernen. Beachten Sie, dass Plugins nur gelöscht werden können, wenn sie in keinem Plugin-Set mehr installiert sind.

[.instruction]
Git-Repository löschen:

. Öffnen Sie das Menü **Plugins >> Git**.
. Klicken Sie auf **Löschen**, um das entsprechende Repository aus dem System zu entfernen.