= Plugins einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Plugins, Erweiterungen, Funktionen
:description: So richtest du Plugins im plentymarkets Backend ein.
:position: 30
:url: plugins/plugins

[#plugin-konfiguration]
== Plugin-Konfiguration

Nach der Installation müssen Plugins teilweise noch konfiguriert werden. Je nach Plugin gibt es hierbei eine von zwei Möglichkeiten. Entweder öffnet sich ein Fenster mit Einstellungsmöglichkeiten, wenn du auf den Namen des Plugins im Plugin-Set klickst oder es wird bei Installation des Plugins eine Schnittstelle zu dem Menü *Systemeinstellungen* hinzugefügt. Werden Einstellungen innerhalb eines Plugin-Sets vorgenommen, sind sie auf dieses eine Plugin-Set beschränkt. Einstellungen, die im Menü *Systemeinstellungen* vorgenommen werden, sind global und betreffen alle Plugin-Sets, auch wenn das Plugin erst später in dem Set installiert wird.

include::_textblocks/importants/plugin-konfigurationsausnahmen.adoc[]

[#konfiguration-export-import]
=== Export und Import

==== Plugin-Konfiguration

Soll ein Plugin in mehr als einem Plugin-Set verwendet werden, kann die Konfiguration nicht direkt kopiert werden. Es ist allerdings möglich, die Plugin-Konfiguration zu exportieren und anschließend wieder zu importieren.

include::_textblocks/instructions/plugin-konfiguration-exportieren.adoc[]

include::_textblocks/importants/export-systemeinstellungen.adoc[]

include::_textblocks/instructions/plugin-konfiguration-importieren.adoc[]

include::_textblocks/warnings/import-limitierung.adoc[]

==== Plugin-Set-Konfiguration

Wenn nicht nur die Konfiguration eines Plugins benötigt wird, sondern die Konfigurationen aller Plugins innerhalb eines Set, können diese zusammengefasst exportiert und importiert werden. Öffne dafür das Menü **Plugin-Set-Einstellungen** des Plugin-Sets und gehe für den Export und Import jeweils wie oben beschrieben vor.

[#container-verknüpfungen]
== Container-Verknüpfungen

Wenn durch ein Plugin neue Elemente zum Webshop hinzugefügt werden sollen, etwa das Logo für eine Zahlungsmethode, müssen diese Angaben mit sogenannten Containern im Webshop verknüpft werden.

Standardmäßig können diese Verknüpfungen im Menü *CMS* » *Container-Verknüpfungen* angelegt werden. Teilweise geben Entwickler aber auch standardmäßig Verknüpfungen an, die mit einem Klick in der Plugin-Detailansicht angelegt werden können.

include::_textblocks/instructions/standard-container-verknuepfung.adoc[]

Ob für ein Plugin Standard-Container-Verknüpfungen vorliegen, kannst du in der Artikelansicht des Plugins auf plentyMarketplace einsehen.

include::_textblocks/warnings/vorhandene-verknuepfungen-geschuetzt.adoc[]