= Plugins und Plugin-Sets
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Plugins, Erweiterungen, Funktionen
:description: So verwalten Sie Plugins und Plugin-Sets im plentymarkets Backend.
:position: 20

[#plugin-sets-verwalten]
== Plugin-Übersicht - Plugin-Sets verwalten

Die nachfolgende Tabelle enthält eine Liste aller Elemente des Menüs *Plugin-Übersicht* sowie eine kurze Beschreibung dieser Elemente. Außerdem finden Sie in diesem Abschnitt Anweisungen zu der Erstellung, Bearbeitung und Löschung von Plugin-Sets.

[[tabelle-plugin-uebersicht]]
.Tabellenansicht des Menüs *Plugin » Plugin-Übersicht*
[cols="1,3"]
|====
|Element |Erläuterung

|*Neues Plugin-Set erstellen*
|Öffnet ein Fenster zur Erstellung eines neuen Plugin-Sets. +
*Speichern*: Speichert das neue Plugin-Set. +
*Plugin-Set-Name*: Der Name des Plugin-Sets. +
*Plugin-Set kopieren*: Wählt bestehendes Plugin-Set aus Dropdown-Menü aus, um Einstellungen zu übernehmen.

|*Plugin-Sets verknüpfen*
|Ein neues Fenster öffnet sich. Aus einem Dropdown-Menü kann für jedes Plugin-Set ein Mandant ausgewählt werden. Durch *Speichern* der Einstellungen werden die Plugin-Sets mit den ausgewählten Mandanten verknüpft. Eine Verknüpfung kann vollständig aufgehoben werden, indem aus dem Dropdown-Menü die leere Zeile für ein Set ausgewählt wird.

|Name des Plugin-Sets
|Lädt die Plugin-Übersicht des Plugin-Sets.

|*Plugin-Set löschen*
|Löscht das Plugin-Set. Bestätigung notwendig.

|Filter
|*Suchen*: Lädt für das ausgewählte Plugin-Set in der Plugin-Übersicht alle Plugins, die die gewählten Filtereinstellungen erfüllen. +
*Reset*: Setzt die Filtereinstellungen auf die Standardeinstellungen zurück. +
*Name*: Filtert nach Plugins, deren Namen die eingegebene Zeichenfolge beinhaltet. +
*plentyMarketplace*: Filtert nach Plugins, die dem System über plentyMarketplace hinzugefügt wurden. +
*Git*: Filtert nach Plugins, die dem System über ein Git-Repository hinzugefügt wurden. +
*Local*: Filtert nach Plugins, die dem System über einen lokalen Speicher hinzugefügt wurden. +
*Installiert*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set installiert sind. +
*Nicht installiert*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set nicht installiert sind. +
*Aktiv*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set aktiv sind. +
*Nicht akitv*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set nicht aktiv sind.

|*Speichern & Plugin bereitstellen*
|Speichert Änderungen am Plugin-Set und stellt das Plugin-Set zur weiteren Nutzung bereit.

|*Plugin-Set-Vorschau*
|Öffnet ein Tab, in dem eine Vorschau des Frontends mit den derzeitigen Einstellungen angezeigt wird. Plugin-Set muss zuvor mittels der Schaltfläche *Speichern & Bereitstellen* bereitgestellt worden sein.

|*plentyDrive: Änderungen automatisch bereitstellen*
|Wenn aktiviert und dem Plugin-Set ein Plugin mithilfe von plentyDrive hinzugefügt oder geändert wird, wird das Plugin-Set automatisch gespeichert und bereitgestellt.

|*Plugin-Set-Einstellungen*
|Öffnet ein Fenster zur Bearbeitung des ausgewählten Plugin-Sets. +
*Speichern*: Speichert die geänderten Einstellungen. +
*Name*: Ändert den Namen des Plugin-Sets. +
*Plugin-Set-ID*: Die ID des Plugin-Sets.

|*Log*
|Nur sichtbar, wenn Fehlermeldungen existieren. Zeigt diese an.

|*Aktiv*
|Zeigt an, ob das Plugin aktiv oder inaktiv ist.

|*Name*
|Der Name des Plugins. Wenn installiert, klicken um Informationen und Einstellungsmöglichkeiten anzuzeigen.

|*Installierte Version*
|Die neuste Version des Plugins, die installiert ist. Ein Symbol zeigt an, wenn eine neuere Version des Plugins existiert.

|*Aktive Version*
|Die Version des Plugins, die aktiv ist und für das ausgewählte Plugin-Set in Frontend und Backend geladen wird.

|*Herkunft*
|Die Herkunft des Plugins, also plentyMarkets, Git oder ein lokaler Speicher.

|*Aktion*
|*Plugin installieren*: Installiert das Plugin. Ein Fenster öffnet sich, in dem die zu installierende Version ausgewählt und der Changelog eingesehen werden kann. Wird nur angezeigt, wenn das Plugin nicht installiert ist. +
*Aktualisieren*: Aktualisiert das Plugin auf eine neuere Version. Ein Fenster öffnet sich, in dem die zu installierende Version ausgewählt und der Changelog eingesehen werden kann. Wird nur angezeigt, wenn eine neuere Version vorhanden ist. +
*Keine Aktualisierung verfügbar*: Die neuste Version des Plugins ist installiert. +
*Position festlegen*: Legt die Reihenfolge fest, in der Plugins geladen werden. Plugins mit niedrigerer Position werden zuerst ausgeführt. +
*Löschen*: Entfernt das Plugin aus dem Plugin-Set. Bestätigung notwendig.

|*plentyMarketplace*
|Öffnet plentyMarketplace in einem neuen Tab.
|====

Ein Plugin-Set ist eine Sammlung von verschiedenen Plugins, die für einen oder für mehrere Mandanten zentral in der *Plugin-Übersicht* verwaltet werden können. Plugin-Sets können ein Plugin oder mehrere Plugins enthalten und beinhalten darüber hinaus ebenfalls die Einstellungen der Plugin-Konfiguration und Layout-Container. Plugin-Sets eignen sich insbesondere für Händler, die mehrere Webshops gleichzeitig über plentymarkets verwalten, da unterschiedliche Plugin-Sets für unterschiedliche Mandanten gesondert aktiviert und konfiguriert werden können.

In den folgenden Abschnitten wird beschrieben, welche Aktionen Sie durchführen müssen, um neue Plugin-Sets zu erstellen, bereits existierende Plugin-Sets zu bearbeiten oder Plugin-Sets zu löschen.

[#plugin-sets-erstellen]
== Plugin-Sets erstellen

[.instruction]
Plugin-Sets erstellen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Hinzufügen*. +
→ Das Fenster *Plugin-Set erstellen* wird geöffnet.
. Geben Sie einen Namen für das Plugin-Set ein.
. Wählen Sie auf dem Dropdown-Menü *Plugin-Set kopieren* ein Plugin-Set aus, um dessen Einstellungen zu übernehmen.
. *Speichern* Sie die Einstellungen.

[.instruction]
Plugins installieren:

. Klicken Sie auf das Plugin-Set, das Sie bearbeiten möchten. +
→ Der Bereich, in dem Sie das ausgewählte Plugin-Set bearbeiten können, wird geöffnet.
. Nutzen Sie die Filterfunktion indem Sie das Kontrollkästchen *Nicht installiert* aktivieren und auf *Suchen* klicken. Möchten Sie Plugins installieren, die Sie über ein Git-Repository oder einen lokalen Speicher hinzugefügt haben, müssen Sie vor der Suche auch das Kontrollkästchen *Git* beziehungsweise *Lokal* auswählen. +
→ Die Plugin-Übersicht wird entsprechend aktualisiert.
. Wenn Sie ein Plugin installieren möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktion* auf die Schaltfläche *Plugin installieren*. +
→ Ein Fenster zur Auswahl der zu installierenden Version öffnet sich. Wählen Sie aus dem Dropdown-Menü *Zu installierende Version* die Version des Plugins aus, die Sie installieren möchten. Standardmäßig ist die neuste Version ausgewählt. In einem Textfeld unterhalb des Dropdown-Menüs wird der Changelog der aktuell ausgewählten Version angezeigt. Wenn Sie sich für eine Version entschieden haben, klicken Sie auf die Schaltfläche *Installieren*. +
→ Das Plugin wird installiert und ist in der Plugin-Übersicht des Plugin-Sets verfügbar. Eine Ansicht mit allen installierten Plugins wird angezeigt.

[.instruction]
Plugins aktivieren:

. Wenn Sie ein Plugin einem Plugin-Set aktivieren möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktiv* auf die Schaltfläche *Inaktiv*. +
→ Aktive Plugins werden in Frontend und Backend geladen.

[.instruction]
Position von Plugins ändern:

. Wenn Sie die Position eines Plugins verändern möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktion* auf die Schaltfläche *Position festlegen*. +
→ Das Fenster *Plugin-Position* öffnet sich. Geben Sie in das Textfeld die gewünschte Position des Plugins ein und klicken Sie auf *Speichern*. +
→ Die Position des Plugins wird aktualisiert.

[TIP]
.Plugin-Position
====
Die relative Position der Plugins bestimmt, in welcher Reihenfolge sie innerhalb des Sets geladen werden. Dabei gilt: Je niedriger die Position des Plugins desto früher wird es geladen. Aus diesem Grund sollte das Plugin IO die höchste Positionsnummer erhalten, das Plugin Ceres in der Regel die zweithöchste.
====

[.instruction]
Plugins als Vorschau öffnen:

. Klicken Sie auf *Plugin-Set-Vorschau*.
. Wählen Sie den Webshop, den Sie in der Vorschau öffnen wollen. +
→ Der gewählte Webshop wird mit dem gewählten Plugin-Set in einem neuen Browser-Tab geöffnet.

Wenn Sie mit den Anpassungen zufrieden sind, müssen sie noch gespeichert werden.

[.instruction]
Plugin-Set speichern und bereitstellen:

. Klicken Sie auf *Plugin-Set speichern und bereitstellen*.
→ Eine Fortschrittsanzeige wird eingeblendet. Wenn der Prozess erfolgreich abgeschlossen wurde, wird stattdessen ein Zeitstempel mit dem Datum der letzten erfolgreichen Bereitstellung angezeigt. Sollte es während des Bereitstellungsprozesses zu Fehlern kommen, wird stattdessen eine blinkende Schaltfläche angezeigt. Klicken Sie diese, um nährere Informationen zur Ursache des Problems zu erhalten.

[.instruction]
Plugin-Sets aktivieren:

. Klicken Sie auf *Plugin-Sets verknüpfen*. +
→ Das Fenster *Plugin-Sets verknüpfen* wird geöffnet.
. Wählen Sie das Plugin-Set, das Sie mit Ihrem Webshop verknüpfen wollen.
. *Speichern* Sie die Einstellungen.

[TIP]
.Plugin-Sets verknüpfen
====
Das Verknüpfen eines Plugin-Sets mit einem Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es verknüpfen.
====

[#plugin-sets-bearbeiten]
== Plugin-Sets bearbeiten

[#plugin-set-namen-aendern]
=== Plugin-Set-Name ändern

[.instruction]
Plugin-Set-Namen ändern:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf das Plugin-Set, das Sie bearbeiten möchten. +
→ Der Bereich, in dem Sie das ausgewählte Plugin-Set bearbeiten können, wird geöffnet.
. Klicken Sie auf die Schaltfläche *Plugin-Set-Einstellungen*. +
→ Der Bereich *Einstellungen* wird geöffnet.
. Geben Sie in das Textfeld *Name* den neuen Namen für Ihr Plugin-Set ein.
. Klicken Sie auf die Schaltfläche *Speichern*. +
→ Das Plugin-Set wird umbenannt.

[TIP]
.Sicherheitskopie
====
Wenn Sie ein Plugin-Set bearbeiten und entweder neue Plugins hinzufügen oder bereits existierende Plugins aktualisieren oder löschen möchten, ist es empfehlenswert, eine Kopie dieses Plugin-Sets zu erstellen und die Änderungen zunächst auf dieser vorzunehmen. Dadurch wird verhindert, dass die Änderungen unbeabsichtigte Auswirkungen auf Ihren aktiven Shop hat.
====

[#plugins-hinzufuegen]
=== Plugins hinzufügen

[.instruction]
Plugin-Set kopieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Hinzufügen*. +
→ Das Fenster *Plugin-Set erstellen* wird geöffnet.
. Geben Sie einen Namen für das Plugin-Set ein.
. Klicken Sie auf *Von Plugin-Set kopieren*, um Einstellungen aus einem existierenden Plugin-Set zu übernehmen.
. *Speichern* Sie die Einstellungen.

[.instruction]
Plugins installieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf das Plugin-Set, das Sie bearbeiten möchten. +
→ Der Bereich, in dem Sie das ausgewählte Plugin-Set bearbeiten können, wird geöffnet.
. Nutzen Sie die Filterfunktion indem Sie das Kontrollkästchen *Nicht installiert* aktivieren und auf *Suchen* klicken. Möchten Sie Plugins installieren, die Sie über ein Git-Repository oder einen lokalen Speicher hinzugefügt haben, müssen Sie vor der Suche auch das Kontrollkästchen *Git* beziehungsweise *Lokal* auswählen. +
→ Die Plugin-Übersicht wird entsprechend aktualisiert.
. Wenn Sie ein Plugin installieren möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktion* auf die Schaltfläche *Plugin installieren*. +
→ Ein Fenster zur Auswahl der zu installierenden Version öffnet sich. Wählen Sie aus dem Dropdown-Menü *Zu installierende Version* die Version des Plugins aus, die Sie installieren möchten. Standardmäßig ist die neuste Version ausgewählt. In einem Textfeld unterhalb des Dropdown-Menüs wird der Changelog der aktuell ausgewählten Version angezeigt. Wenn Sie sich für eine Version entschieden haben, klicken Sie auf die Schaltfläche *Installieren*. +
→ Das Plugin wird installiert und ist in der Plugin-Übersicht des Plugin-Sets verfügbar. Eine Ansicht mit allen installierten Plugins wird angezeigt.

[.instruction]
Plugins aktivieren:

. Wenn Sie ein Plugin aktivieren möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktiv* auf die Schaltfläche *Inaktiv*. +
→ Aktive Plugins werden in Frontend und Backend geladen.

[.instruction]
Position von Plugins ändern:

. Wenn Sie die Position eines Plugins verändern möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktion* auf die Schaltfläche *Position festlegen*. +
→ Das Fenster *Plugin-Position* öffnet sich. Geben Sie in das Textfeld die gewünschte Position des Plugins ein und klicken Sie auf *Speichern*. +
→ Die Position des Plugins wird aktualisiert.

[TIP]
.Plugin-Position
====
Die relative Position der Plugins bestimmt, in welcher Reihenfolge sie innerhalb des Sets geladen werden. Dabei gilt: Je niedriger die Position des Plugins desto früher wird es geladen. Aus diesem Grund sollte das Plugin IO die höchste Positionsnummer erhalten, das Plugin Ceres in der Regel die zweithöchste.
====

[.instruction]
Plugins als Vorschau öffnen:

. Klicken Sie auf *Plugin-Set-Vorschau*.
. Wählen Sie den Webshop, den Sie in der Vorschau öffnen wollen. +
→ Der gewählte Webshop wird mit dem gewählten Plugin-Set in einem neuen Browser-Tab geöffnet.

Wenn Sie mit den Anpassungen zufrieden sind, müssen sie noch gespeichert werden.

[.instruction]
Plugin-Set speichern und bereitstellen:

. Klicken Sie auf *Plugin-Set speichern und bereitstellen*.
→ Eine Fortschrittsanzeige wird eingeblendet. Wenn der Prozess erfolgreich abgeschlossen wurde, wird stattdessen ein Zeitstempel mit dem Datum der letzten erfolgreichen Bereitstellung angezeigt. Sollte es während des Bereitstellungsprozesses zu Fehlern kommen, wird stattdessen eine blinkende Schaltfläche angezeigt. Klicken Sie diese, um nährere Informationen zur Ursache des Problems zu erhalten.

[.instruction]
Plugin-Sets verknüpfen:

. Klicken Sie auf *Plugin-Set verknüpfen*. +
→ Das Fenster *Plugin-Set verknüpfen* wird geöffnet.
. Wählen Sie das Plugin-Set, das Sie mit Ihrem Webshop verknüpfen wollen.
. *Speichern* Sie die Einstellungen.

[TIP]
.Plugin-Sets verknüpfen
====
Das Verknüpfen eines Plugin-Sets mit einem Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es verknüpfen.
====

[#plugins-aktualisieren]
=== Plugins aktualisieren

[.instruction]
Plugin-Set kopieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Hinzufügen*. +
→ Das Fenster *Plugin-Set erstellen* wird geöffnet.
. Geben Sie einen Namen für das Plugin-Set ein.
. Klicken Sie auf *Von Plugin-Set kopieren*, um Einstellungen aus einem existierenden Plugin-Set zu übernehmen.
. *Speichern* Sie die Einstellungen.

[.instruction]
Plugins aktualisieren:

. Wenn ein Update für ein Plugin verfügbar ist, wird in der entsprechenden Zeile in der Spalte *Aktion* die Schaltfläche *Aktualisieren* farbig gekennzeichnet. Klicken Sie auf diese Schaltfläche, um das Plugin zu aktualisieren. +
→ Ein Fenster zur Auswahl der zu installierenden Version öffnet sich. Wählen Sie aus dem Dropdown-Menü *Zu installierende Version* die Version des Plugins aus, die Sie installieren möchten. Standardmäßig ist die neuste Version ausgewählt. In einem Textfeld unterhalb des Dropdown-Menüs wird der Changelog der aktuell ausgewählten Version angezeigt. Wenn Sie sich für eine Version entschieden haben, klicken Sie auf die Schaltfläche *Installieren*. +
→ Das Plugin wird aktualisiert.

[.instruction]
Position von Plugins ändern:

. Wenn Sie die Position eines Plugins verändern möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktion* auf die Schaltfläche *Position festlegen*. +
→ Das Fenster *Plugin-Position* öffnet sich. Geben Sie in das Textfeld die gewünschte Position des Plugins ein und klicken Sie auf *Speichern*. +
→ Die Position des Plugins wird aktualisiert.

[TIP]
.Plugin-Position
====
Die relative Position der Plugins bestimmt, in welcher Reihenfolge sie innerhalb des Sets geladen werden. Dabei gilt: Je niedriger die Position des Plugins desto früher wird es geladen. Aus diesem Grund sollte das Plugin IO die höchste Positionsnummer erhalten, das Plugin Ceres in der Regel die zweithöchste.
====

[.instruction]
Plugins als Vorschau öffnen:

. Klicken Sie auf *Plugin-Set-Vorschau*.
. Wählen Sie den Webshop, den Sie in der Vorschau öffnen wollen. +
→ Der gewählte Webshop wird mit dem gewählten Plugin-Set in einem neuen Browser-Tab geöffnet.

Wenn Sie mit den Anpassungen zufrieden sind, müssen sie noch gespeichert werden.

[.instruction]
Plugin-Set speichern und bereitstellen:

. Klicken Sie auf *Plugin-Set speichern und bereitstellen*.
→ Eine Fortschrittsanzeige wird eingeblendet. Wenn der Prozess erfolgreich abgeschlossen wurde, wird stattdessen ein Zeitstempel mit dem Datum der letzten erfolgreichen Bereitstellung angezeigt. Sollte es während des Bereitstellungsprozesses zu Fehlern kommen, wird stattdessen eine blinkende Schaltfläche angezeigt. Klicken Sie diese, um nährere Informationen zur Ursache des Problems zu erhalten.

[.instruction]
Plugin-Sets verknüpfen:

. Klicken Sie auf *Plugin-Set verknüpfen*. +
→ Das Fenster *Plugin-Set verknüpfen* wird geöffnet.
. Wählen Sie das Plugin-Set, das Sie mit Ihrem Webshop verknüpfen wollen.
. *Speichern* Sie die Einstellungen.

[TIP]
.Plugin-Sets verknüpfen
====
Das Verknüpfen eines Plugin-Sets mit einem Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es verknüpfen.
====

[#plugins-entfernen]
=== Plugins entfernen

Es gibt zwei Möglichkeiten, die Funktionalität eines Plugins von Ihrem Set zu entfernen. Wenn Sie ein Plugin deaktivieren, ist es weiterhin Teil des Sets und Sie können es später erneut aktivieren ohne es neu installieren zu müssen. Wenn Sie ein Plugin löschen, wird es vollständig aus dem Set entfernt.

[#plugins-deaktivieren]
==== Plugins deaktivieren

[.instruction]
Plugin-Set kopieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Hinzufügen*. +
→ Das Fenster *Plugin-Set erstellen* wird geöffnet.
. Geben Sie einen Namen für das Plugin-Set ein.
. Klicken Sie auf *Von Plugin-Set kopieren*, um Einstellungen aus einem existierenden Plugin-Set zu übernehmen.
. *Speichern* Sie die Einstellungen.

[.instruction]
Plugins deaktivieren:

. Wenn Sie ein Plugin deaktivieren möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktiv* auf die Schaltfläche *Aktiv*. +
→ Inaktive Plugins werden in Frontend und Backend nicht geladen.

[.instruction]
Plugins als Vorschau öffnen:

. Klicken Sie auf *Plugin-Set-Vorschau*.
. Wählen Sie den Webshop, den Sie in der Vorschau öffnen wollen. +
→ Der gewählte Webshop wird mit dem gewählten Plugin-Set in einem neuen Browser-Tab geöffnet.

Wenn Sie mit den Anpassungen zufrieden sind, müssen sie noch gespeichert werden.

[.instruction]
Plugin-Set speichern und bereitstellen:

. Klicken Sie auf *Plugin-Set speichern und bereitstellen*.
→ Eine Fortschrittsanzeige wird eingeblendet. Wenn der Prozess erfolgreich abgeschlossen wurde, wird stattdessen ein Zeitstempel mit dem Datum der letzten erfolgreichen Bereitstellung angezeigt. Sollte es während des Bereitstellungsprozesses zu Fehlern kommen, wird stattdessen eine blinkende Schaltfläche angezeigt. Klicken Sie diese, um nährere Informationen zur Ursache des Problems zu erhalten.

[.instruction]
Plugin-Sets verknüpfen:

. Klicken Sie auf *Plugin-Set verknüpfen*. +
→ Das Fenster *Plugin-Set verknüpfen* wird geöffnet.
. Wählen Sie das Plugin-Set, das Sie mit Ihrem Webshop verknüpfen wollen.
. *Speichern* Sie die Einstellungen.

[TIP]
.Plugin-Sets verknüpfen
====
Das Verknüpfen eines Plugin-Sets mit einem Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es verknüpfen.
====

[#plugins-loeschen]
==== Plugins löschen

[.instruction]
Plugin-Set kopieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Hinzufügen*. +
→ Das Fenster *Plugin-Set erstellen* wird geöffnet.
. Geben Sie einen Namen für das Plugin-Set ein.
. Klicken Sie auf *Von Plugin-Set kopieren*, um Einstellungen aus einem existierenden Plugin-Set zu übernehmen.
. *Speichern* Sie die Einstellungen.

[.instruction]
Plugins löschen:

. Wenn Sie ein Plugin löschen möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktion* auf die Schaltfläche *Löschen*. +
→ Gelöschte Plugins werden von dem Plugin-Set entfernt.

[.instruction]
Plugins als Vorschau öffnen:

. Klicken Sie auf *Plugin-Set-Vorschau*.
. Wählen Sie den Webshop, den Sie in der Vorschau öffnen wollen. +
→ Der gewählte Webshop wird mit dem gewählten Plugin-Set in einem neuen Browser-Tab geöffnet.

Wenn Sie mit den Anpassungen zufrieden sind, müssen sie noch gespeichert werden.

[.instruction]
Plugin-Set speichern und bereitstellen:

. Klicken Sie auf *Plugin-Set speichern und bereitstellen*.
→ Eine Fortschrittsanzeige wird eingeblendet. Wenn der Prozess erfolgreich abgeschlossen wurde, wird stattdessen ein Zeitstempel mit dem Datum der letzten erfolgreichen Bereitstellung angezeigt. Sollte es während des Bereitstellungsprozesses zu Fehlern kommen, wird stattdessen eine blinkende Schaltfläche angezeigt. Klicken Sie diese, um nährere Informationen zur Ursache des Problems zu erhalten.

[.instruction]
Plugin-Sets verknüpfen:

. Klicken Sie auf *Plugin-Set verknüpfen*. +
→ Das Fenster *Plugin-Set verknüpfen* wird geöffnet.
. Wählen Sie das Plugin-Set, das Sie in Ihrem Webshop aktivieren wollen.
. *Speichern* Sie die Einstellungen.

[TIP]
.Plugin-Sets verknüpfen
====
Das Verknüpfen eines Plugin-Sets mit einem Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es verknüpfen.
====

[#plugin-sets-loeschen]
== Plugin-Sets löschen

[.instruction]
Plugin-Sets löschen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie bei einem Plugin-Set auf *Löschen*. +
→ Das Fenster *Plugin-Set löschen* wird geöffnet.
. Bestätigen Sie die Löschung. +
→ Das Plugin-Set wird gelöscht.
