= Plugins und Plugin-Sets
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Plugins, Erweiterungen, Funktionen
:description: So verwalten Sie Plugins und Plugin-Sets im plentymarkets Backend.
:position: 20
:url: plugins/plugin-sets

[#plugin-sets-verwalten]
== Plugin-Übersicht - Plugin-Sets verwalten

Die nachfolgende Tabelle enthält eine Liste aller Elemente des Menüs *Plugin-Übersicht* sowie eine kurze Beschreibung dieser Elemente. Außerdem finden Sie in diesem Abschnitt Anweisungen zu der Erstellung, Bearbeitung und Löschung von Plugin-Sets.

[[tabelle-plugin-uebersicht]]
.Tabellenansicht des Menüs *Plugin » Plugin-Übersicht*
[cols="1,3"]
|====
|Element |Erläuterung

|*Neues Plugin-Set erstellen*
|Öffnet ein Fenster zur Erstellung eines neuen Plugin-Sets. +
*Speichern*: Speichert das neue Plugin-Set. +
*Plugin-Set-Name*: Der Name des Plugin-Sets. +
*Plugin-Set kopieren*: Wählt bestehendes Plugin-Set aus Dropdown-Menü aus, um Einstellungen zu übernehmen.

|*Plugin-Sets verknüpfen*
|Ein neues Fenster öffnet sich. Aus einem Dropdown-Menü kann für jedes Plugin-Set ein Mandant ausgewählt werden. Durch *Speichern* der Einstellungen werden die Plugin-Sets mit den ausgewählten Mandanten verknüpft. Eine Verknüpfung kann vollständig aufgehoben werden, indem aus dem Dropdown-Menü die leere Zeile für ein Set ausgewählt wird.

|Name des Plugin-Sets
|Lädt die Plugin-Übersicht des Plugin-Sets.

|*Plugin-Set löschen*
|Löscht das Plugin-Set. Bestätigung notwendig.

|Filter
|*Suchen*: Lädt für das ausgewählte Plugin-Set in der Plugin-Übersicht alle Plugins, die die gewählten Filtereinstellungen erfüllen. +
*Reset*: Setzt die Filtereinstellungen auf die Standardeinstellungen zurück. +
*Name*: Filtert nach Plugins, deren Namen die eingegebene Zeichenfolge beinhaltet. +
*plentyMarketplace*: Filtert nach Plugins, die dem System über plentyMarketplace hinzugefügt wurden. +
*Git*: Filtert nach Plugins, die dem System über ein Git-Repository hinzugefügt wurden. +
*Local*: Filtert nach Plugins, die dem System über einen lokalen Speicher hinzugefügt wurden. +
*Installiert*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set installiert sind. +
*Nicht installiert*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set nicht installiert sind. +
*Aktiv*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set aktiv sind. +
*Nicht akitv*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set nicht aktiv sind.

|*Speichern & Plugin bereitstellen*
|Speichert Änderungen am Plugin-Set und stellt das Plugin-Set zur weiteren Nutzung bereit.

|*Plugin-Set-Vorschau*
|Öffnet ein Tab, in dem eine Vorschau des Frontends mit den derzeitigen Einstellungen angezeigt wird. Plugin-Set muss zuvor mittels der Schaltfläche *Speichern & Bereitstellen* bereitgestellt worden sein.

|*plentyDrive: Änderungen automatisch bereitstellen*
|Wenn aktiviert und dem Plugin-Set ein Plugin mithilfe von plentyDrive hinzugefügt oder geändert wird, wird das Plugin-Set automatisch gespeichert und bereitgestellt.

|*Plugin-Set-Einstellungen*
|Öffnet ein Fenster zur Bearbeitung des ausgewählten Plugin-Sets. +
*Speichern*: Speichert die geänderten Einstellungen. +
*Name*: Ändert den Namen des Plugin-Sets. +
*Plugin-Set-ID*: Die ID des Plugin-Sets.

|*Log*
|Nur sichtbar, wenn Fehlermeldungen existieren. Zeigt diese an.

|*Aktiv*
|Zeigt an, ob das Plugin aktiv oder inaktiv ist.

|*Name*
|Der Name des Plugins. Wenn installiert, klicken um Informationen und Einstellungsmöglichkeiten anzuzeigen.

|*Installierte Version*
|Die neuste Version des Plugins, die installiert ist. Ein Symbol zeigt an, wenn eine neuere Version des Plugins existiert.

|*Aktive Version*
|Die Version des Plugins, die aktiv ist und für das ausgewählte Plugin-Set in Frontend und Backend geladen wird.

|*Herkunft*
|Die Herkunft des Plugins, also plentyMarkets, Git oder ein lokaler Speicher.

|*Aktion*
|*Plugin installieren*: Installiert das Plugin. Ein Fenster öffnet sich, in dem die zu installierende Version ausgewählt und der Changelog eingesehen werden kann. Wird nur angezeigt, wenn das Plugin nicht installiert ist. +
*Aktualisieren*: Aktualisiert das Plugin auf eine neuere Version. Ein Fenster öffnet sich, in dem die zu installierende Version ausgewählt und der Changelog eingesehen werden kann. Wird nur angezeigt, wenn eine neuere Version vorhanden ist. +
*Keine Aktualisierung verfügbar*: Die neuste Version des Plugins ist installiert. +
*Position festlegen*: Legt die Reihenfolge fest, in der Plugins geladen werden. Plugins mit niedrigerer Position werden zuerst ausgeführt. +
*Löschen*: Entfernt das Plugin aus dem Plugin-Set. Bestätigung notwendig.

|*plentyMarketplace*
|Öffnet plentyMarketplace in einem neuen Tab.
|====

Ein Plugin-Set ist eine Sammlung von verschiedenen Plugins, die für einen oder für mehrere Mandanten zentral in der *Plugin-Übersicht* verwaltet werden können. Plugin-Sets können ein Plugin oder mehrere Plugins enthalten und beinhalten darüber hinaus ebenfalls die Einstellungen der Plugin-Konfiguration und Layout-Container. Plugin-Sets eignen sich insbesondere für Händler, die mehrere Webshops gleichzeitig über plentymarkets verwalten, da unterschiedliche Plugin-Sets für unterschiedliche Mandanten gesondert aktiviert und konfiguriert werden können.

In den folgenden Abschnitten wird beschrieben, welche Aktionen Sie durchführen müssen, um neue Plugin-Sets zu erstellen, bereits existierende Plugin-Sets zu bearbeiten oder Plugin-Sets zu löschen.

[#plugin-sets-erstellen]
== Plugin-Sets erstellen

include::_textblocks/instructions/plugin-set-erstellen.adoc[]

[WARNING]
.Plugin-Set-Name
====
Die Namen von Plugin-Sets dürfen nur bestimmte Zeichen enthalten. Erlaubt sind alle Buchstaben des deutschen Alphabets, inklusive Umlauten und Eszett, Ziffern, sowie die Zeichen '-', '_', '.' und Leerzeichen. Insgesamt muss der Name zwischen 3 und 255 Zeichen lang sein.
====

include::_textblocks/instructions/plugin-installieren.adoc[]

include::_textblocks/instructions/plugin-aktivieren.adoc[]

include::_textblocks/instructions/plugin-position-aendern.adoc[]

[IMPORTANT]
.Plugin-Position
====
Die relative Position der Plugins bestimmt, in welcher Reihenfolge sie innerhalb des Sets geladen werden. Dabei gilt: Je niedriger die Position des Plugins desto früher wird es geladen. Aus diesem Grund sollte das Plugin IO die höchste Positionsnummer erhalten, das Plugin Ceres in der Regel die zweithöchste. Eine Ausnahme bilden Theme-Plugins. Diese müssen normalerweise zwischen Ceres und IO positioniert sein.
====

include::_textblocks/instructions/plugin-set-speichern.adoc[]

include::_textblocks/instructions/plugin-set-vorschau-oeffnen.adoc[]

include::_textblocks/instructions/plugin-set-verknuepfen.adoc[]

[IMPORTANT]
.Plugin-Sets verknüpfen
====
Das Verknüpfen eines Plugin-Sets mit einem Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es verknüpfen.
====

[#plugin-sets-bearbeiten]
== Plugin-Sets bearbeiten

[#plugin-set-namen-aendern]
=== Plugin-Set-Name ändern

include::_textblocks/instructions/plugin-set-namen-aendern.adoc[]

[TIP]
.Sicherheitskopie
====
Wenn Sie ein Plugin-Set bearbeiten und entweder neue Plugins hinzufügen oder bereits existierende Plugins aktualisieren oder löschen möchten, ist es empfehlenswert, eine Kopie dieses Plugin-Sets zu erstellen und die Änderungen zunächst auf dieser vorzunehmen. Dadurch wird verhindert, dass die Änderungen unbeabsichtigte Auswirkungen auf Ihren aktiven Shop hat.
====

[#plugins-hinzufuegen]
=== Plugins hinzufügen

include::_textblocks/instructions/plugin-set-kopieren.adoc[]

[WARNING]
.Plugin-Set-Name
====
Die Namen von Plugin-Sets dürfen nur bestimmte Zeichen enthalten. Erlaubt sind alle Buchstaben des deutschen Alphabets, inklusive Umlauten und Eszett, Ziffern, sowie die Zeichen '-', '_', '.' und Leerzeichen. Insgesamt muss der Name zwischen 3 und 255 Zeichen lang sein.
====

include::_textblocks/instructions/plugin-installieren.adoc[]

include::_textblocks/instructions/plugin-aktivieren.adoc[]

include::_textblocks/instructions/plugin-position-aendern.adoc[]

[IMPORTANT]
.Plugin-Position
====
Die relative Position der Plugins bestimmt, in welcher Reihenfolge sie innerhalb des Sets geladen werden. Dabei gilt: Je niedriger die Position des Plugins desto früher wird es geladen. Aus diesem Grund sollte das Plugin IO die höchste Positionsnummer erhalten, das Plugin Ceres in der Regel die zweithöchste. Eine Ausnahme bilden Theme-Plugins. Diese müssen normalerweise zwischen Ceres und IO positioniert sein.
====

include::_textblocks/instructions/plugin-set-vorschau-oeffnen.adoc[]

Wenn Sie mit den Anpassungen zufrieden sind, müssen sie noch gespeichert werden.

include::_textblocks/instructions/plugin-set-speichern.adoc[]

include::_textblocks/instructions/plugin-set-verknuepfen.adoc[]

[IMPORTANT]
.Plugin-Sets verknüpfen
====
Das Verknüpfen eines Plugin-Sets mit einem Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es verknüpfen.
====

[#plugins-aktualisieren]
=== Plugins aktualisieren

include::_textblocks/instructions/plugin-set-kopieren.adoc[]

[WARNING]
.Plugin-Set-Name
====
Die Namen von Plugin-Sets dürfen nur bestimmte Zeichen enthalten. Erlaubt sind alle Buchstaben des deutschen Alphabets, inklusive Umlauten und Eszett, Ziffern, sowie die Zeichen '-', '_', '.' und Leerzeichen. Insgesamt muss der Name zwischen 3 und 255 Zeichen lang sein.
====

include::_textblocks/instructions/plugin-aktualisieren.adoc[]

include::_textblocks/instructions/plugin-position-aendern.adoc[]

[IMPORTANT]
.Plugin-Position
====
Die relative Position der Plugins bestimmt, in welcher Reihenfolge sie innerhalb des Sets geladen werden. Dabei gilt: Je niedriger die Position des Plugins desto früher wird es geladen. Aus diesem Grund sollte das Plugin IO die höchste Positionsnummer erhalten, das Plugin Ceres in der Regel die zweithöchste. Eine Ausnahme bilden Theme-Plugins. Diese müssen normalerweise zwischen Ceres und IO positioniert sein.
====

include::_textblocks/instructions/plugin-set-vorschau-oeffnen.adoc[]

Wenn Sie mit den Anpassungen zufrieden sind, müssen sie noch gespeichert werden.

include::_textblocks/instructions/plugin-set-speichern.adoc[]

include::_textblocks/instructions/plugin-set-verknuepfen.adoc[]

[IMPORTANT]
.Plugin-Sets verknüpfen
====
Das Verknüpfen eines Plugin-Sets mit einem Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es verknüpfen.
====

[#plugins-entfernen]
=== Plugins entfernen

Es gibt zwei Möglichkeiten, die Funktionalität eines Plugins von Ihrem Set zu entfernen. Wenn Sie ein Plugin deaktivieren, ist es weiterhin Teil des Sets und Sie können es später erneut aktivieren ohne es neu installieren zu müssen. Wenn Sie ein Plugin löschen, wird es vollständig aus dem Set entfernt.

[#plugins-deaktivieren]
==== Plugins deaktivieren

include::_textblocks/instructions/plugin-set-kopieren.adoc[]

[WARNING]
.Plugin-Set-Name
====
Die Namen von Plugin-Sets dürfen nur bestimmte Zeichen enthalten. Erlaubt sind alle Buchstaben des deutschen Alphabets, inklusive Umlauten und Eszett, Ziffern, sowie die Zeichen '-', '_', '.' und Leerzeichen. Insgesamt muss der Name zwischen 3 und 255 Zeichen lang sein.
====

include::_textblocks/instructions/plugin-deaktivieren.adoc[]

include::_textblocks/instructions/plugin-set-vorschau-oeffnen.adoc[]

Wenn Sie mit den Anpassungen zufrieden sind, müssen sie noch gespeichert werden.

include::_textblocks/instructions/plugin-set-speichern.adoc[]

include::_textblocks/instructions/plugin-set-verknuepfen.adoc[]

[IMPORTANT]
.Plugin-Sets verknüpfen
====
Das Verknüpfen eines Plugin-Sets mit einem Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es verknüpfen.
====

[#plugins-loeschen]
==== Plugins löschen

include::_textblocks/instructions/plugin-set-kopieren.adoc[]

[WARNING]
.Plugin-Set-Name
====
Die Namen von Plugin-Sets dürfen nur bestimmte Zeichen enthalten. Erlaubt sind alle Buchstaben des deutschen Alphabets, inklusive Umlauten und Eszett, Ziffern, sowie die Zeichen '-', '_', '.' und Leerzeichen. Insgesamt muss der Name zwischen 3 und 255 Zeichen lang sein.
====

include::_textblocks/instructions/plugin-loeschen.adoc[]

include::_textblocks/instructions/plugin-set-vorschau-oeffnen.adoc[]

Wenn Sie mit den Anpassungen zufrieden sind, müssen sie noch gespeichert werden.

include::_textblocks/instructions/plugin-set-speichern.adoc[]

include::_textblocks/instructions/plugin-set-verknuepfen.adoc[]

[IMPORTANT]
.Plugin-Sets verknüpfen
====
Das Verknüpfen eines Plugin-Sets mit einem Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es verknüpfen.
====

[#plugin-sets-loeschen]
== Plugin-Sets löschen

Wenn Sie ein Plugin-Set nicht mehr benötigen, können Sie es löschen. Dabei können Plugin-Sets nur gelöscht werden, wenn sie nicht mit einem Mandanten verknüpft sind. Die Verknüpfung muss zunächst aufgehoben werden.

include::_textblocks/instructions/plugin-set-verknuepfung-aufheben.adoc[]

include::_textblocks/instructions/plugin-set-loeschen.adoc[]
