= Plugins einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Plugins, Erweiterungen, Funktionen
:description: So richten Sie Plugins im plentymarkets Backend ein.
:position: 30
:url: plugins/plugins

[#plugin-konfiguration]
== Plugin-Konfiguration

Nach der Installation müssen Plugins teilweise noch konfiguriert werden. Je nach Plugin gibt es hierbei eine von zwei Möglichkeiten. Entweder öffnet sich ein Fenster mit Einstellungsmöglichkeiten, wenn Sie auf den Namen des Plugins im Plugin-Set klicken oder es wird bei Installation des Plugins eine Schnittstelle zu dem Menü *Systemeinstellungen* hinzugefügt. Werden Einstellungen innerhalb eines Plugin-Sets vorgenommen, sind sie auf dieses eine Plugin-Set beschränkt. Einstellungen, die im Menü *Systemeinstellungen* vorgenommen werden, sind global und betreffen alle Plugin-Sets, auch wenn das Plugin erst später in dem Set installiert wird.

[NOTE]
.Ausnahmen
====
Wenn ein Plugin vor der Einführung von Plugin-Sets entwickelt wurde, sind möglicherweise andere Einstellungen notwendig.
====

[#konfiguration-export-import]
=== Export und Import

Soll ein Plugin in mehr als einem Plugin-Set verwendet werden, kann die Konfiguration nicht direkt kopiert werden. Es ist allerdings möglich, die Plugin-Konfiguration zu exportieren und anschließend wieder zu importieren.

[.instruction]
Plugin-Konfiguration exportieren:

. Öffnen Sie das Menü *Plugins* » *Plugin Übersicht*.
. Öffnen Sie die Detailansicht des Plugins, für das Sie Verknüpfungen anlegen möchten, indem Sie auf den Namen des Plugins klicken.
. Klicken Sie auf die Schaltfläche *Konfiguration Im-/Export*.
. Klicken Sie auf *Konfiguration exportieren*. +
→ Eine JSON-Datei mit der Konfiguration wird heruntergeladen.

[NOTE]
.Systemeinstellungen
====
Beim Export werden nur Einstellungen exportiert, die in der Plugin-Detailansicht vorgenommen werden. Einstellungen aus den *Systemeinstellungen* werden nicht exportiert.
====

[.instruction]
Plugin-Konfiguration importieren:

. Öffnen Sie das Menü *Plugins* » *Plugin Übersicht*.
. Öffnen Sie die Detailansicht des Plugins dessen Konfiguration Sie exportieren möchten, indem Sie auf den Namen des Plugins klicken.
. Klicken Sie auf die Schaltfläche *Konfiguration Im-/Export*.
. Klicken Sie auf das Textfeld und wählen Sie die zu importierende Datei aus.
. Klicken Sie auf *Konfiguration importieren*.
→ Die Konfiguration wird importiert.

Der Import kann nur mit einer validen JSON-Datei durchgeführt werden.

[#container-verknüpfungen]
== Container-Verknüpfungen

Wenn durch ein Plugin neue Elemente zum Webshop hinzugefügt werden sollen, etwa das Logo für eine Zahlungsmethode, müssen diese Angaben mit sogenannten Containern im Webshop verknüpft werden.

Standardmäßig können diese Verknüpfungen im Menü *CMS* >> *Container-Verknüpfungen* angelegt werden. Teilweise geben Entwickler aber auch standardmäßig Verknüpfungen an, die mit einem Klick in der Plugin-Detailansicht angelegt werden können.

[.instruction]
Standard-Container-Verknüpfung wählen:

. Öffnen Sie das Menü *Plugins* >> *Plugin Übersicht*.
. Öffnen Sie die Detailansicht des Plugins dessen Konfiguration Sie importieren möchten, indem Sie auf den Namen des Plugins klicken.
. Klicken Sie auf die Schaltfläche *Standard-Container-Verknüpfung*.
. Aktivieren Sie die Kontrollkästchen der Verknüpfungen, die Sie anlegen möchten.
. *Speichern* Sie die Einstellungen.

Ob für ein Plugin Standard-Container-Verknüpfungen vorliegen, können Sie in der Artikelansicht des Plugins auf plentyMarketplace einsehen.

[WARNING]
.Vorhandene Verknüpfungen werden nicht überschrieben
====
Beim Speichern der Standard-Container-Verknüpfungen werden bereits vorhandene Verknüpfungen nicht überschrieben. Wenn Sie nur die Standard-Container-Verknüpfungen nutzen möchten, müssen Sie zunächst alle Verknüpfungen im Menü *CMS* >> *Container-Verknüpfungen* löschen.
====