. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
//→ Eine Übersicht der zuvor erstellten Eigenschaften wird angezeigt.
. Klicke auf icon:plus[role="darkGrey"] *Eigenschaft erstellen*.
. Passe die Einstellungen an deine Bedürfnisse an.
. Speichere (icon:save[role="darkGrey"]) die Einstellungen.

[#property-details]
==== Details

[cols="1,4a"]
|======
|Einstellung |Erläuterung

| *ID*
|Sobald du die Eigenschaft erstmalig gespeichert hast, erhält sie automatisch eine fortlaufende und einzigartige ID.
Die ID kann nicht geändert werden.

| *Bereich*
|Wofür möchtest du die Eigenschaft nutzen?
Wähle den entsprechenden Bereich aus der Dropdown-Liste.
Je nachdem, welchen Bereich du hier wählst, ändern sich die weiteren Einstellungen im Menü.

*_Hinweis_*: Diese Einstellung kann nach dem Speichern nicht mehr geändert werden.

*_Hinweis_*: Diese Handbuchseite erklärt Eigenschaften vom Bereich *Artikel*.
Solche Eigenschaften werden zur Charakterisierung von Produkten verwendet.
Eigenschaften können aber auch für die nähere Charakterisierung von <<crm/kontakte-verwalten#950, Kontakte>> oder <<warenwirtschaft/lager-einrichten#850, Lagerorte>> verwendet werden.
Klicke auf die Links, um mehr über diese andere Anwendungsfälle zu erfahren.

| *Eigenschaftstyp*
|Welche Art von Eigenschaft möchtest du anlegen? Wähle den Eigenschaftstyp aus der Dropdown-Liste.

*_Hinweis_*: Diese Einstellung kann nach dem Speichern nicht mehr geändert werden.

[cols="1,4a"]
!======
!Typ !Wofür ist der Typ geeignet?

! *Kein*
!Der Name der Eigenschaft kann im plentyShop angezeigt werden.
Dies eignet sich, z.B. um die technischen Besonderheiten einer Variante hervorzuheben (Bluetooth, WLAN).
//* Filter zu erstellen (nur Bluetooh-fähige Produkte in die Suchergebnisse berücksichtigen)
//* <<artikel/einstellungen/eigenschaften#intable-bestellmerkmal, Als Bestellmerkmal>>: Eignet sich, z.B. um Kunden <<artikel/anwendungsfaelle/personalisierte-artikel#200, zusätzliche Optionen und Dienstleistungen>> während des Bestellvorgangs anzubieten.

! *Datum*
!Ein Datum kann im plentyShop angezeigt werden.

! *Datei*
!Eine Datei kann für die Variante verfügbar gemacht werden, z.B. eine Montageanleitung.

//<<artikel/einstellungen/eigenschaften#intable-bestellmerkmal, Als Bestellmerkmal>>: Ermöglicht es Kunden, z.B. <<artikel/anwendungsfaelle/personalisierte-artikel#100, ein eigenes Bild hochzuladen>>, das auf ein T-Shirt gedruckt werden soll.

! *Ganze Zahl*
!Eine ganze Zahl kann im plentyShop angezeigt werden.
Eignet sich, z.B. um ein Gewicht oder eine Länge anzugeben.
Beispielsweise ein HDMI-Kabel mit einer Länge von 10 m.

! *Kommazahl*
!Eine Zahl mit Kommastellen kann im plentyShop angezeigt werden.
Eignet sich z.B. um eine Versionsnummer anzugeben.
Beispielsweise Kopfhörer mit Bluetooth-Version 5.0.

! *Zeichenkette*
!Eine alphanumerische Zeichenkette kann im plentyShop angezeigt werden.
//Eine Zahl mit Kommastellen kann im plentyShop angezeigt werden.
//Eigent sich, z.B. um Maßangaben im plentyShop anzuzeigen. Beispielsweise ein Krug, der 1,4 Liter fasst.

! *HTML*
!Ein Text mit Formatierung kann im plentyShop angezeigt werden.
Eignet sich z.B., um variantenspezifische Produktbeschreibungen zu erstellen.

//<<artikel/einstellungen/eigenschaften#intable-bestellmerkmal, Als Bestellmerkmal>>: Ermöglicht es Kunden, z.B. <<artikel/anwendungsfaelle/personalisierte-artikel#100, einen persönlichen Text einzugeben>>, der auf ein T-Shirt gedruckt werden soll.

! *Text*
!Ein Text ohne Formatierung kann im plentyShop angezeigt werden.
Eignet sich z.B., um variantenspezifische Produktbeschreibungen zu erstellen.

! *Auswahl*
!Eignet sich zum Beispiel zur Umsetzung von Ja/Nein-Fragen.
Anders gesagt, dieser Typ eignet sich für Situationen, in denen es zwar mehrere Auswahlmöglichkeiten gibt - wie Ja und Nein -, aber nur eine davon auf die Variante zutrifft.

*_Anwendungsbeispiel_*: +
Stell dir vor, du verkaufst Kopfhörer.
Einige der Kopfhörer verfügen über ein integriertes Mikrofon.
Bei diesen Kopfhörern willst du also die Information "Mikrofon: Ja" anzeigen lassen und bei den anderen "Mikrofon: Nein".

. <<artikel/einstellungen/eigenschaften#710, Erstens>>: Erstellst du die verschiedenen Auswahlmöglichkeiten - wie Ja und Nein.
. <<artikel/einstellungen/eigenschaften#1400, Zweitens>>: Während du die Eigenschaft mit deinen Varianten verknüpfst, gibst du an, welche Kopfhörer den Wert "Ja" haben sollen und welche den Wert "Nein".
//. <<artikel/frontend-artikelsuche-verwalten#, Drittens>> erstellst du Webshop-Filter, die es deinen Kunden ermöglichen, gezielt nach Varianten mit einer bestimmten Wasserfestigkeitsstufe zu suchen.

! *Mehrfachauswahl*
!Eignet sich für Situationen, in denen es mehrere Auswahlmöglichkeiten gibt, und mehrere davon auf die Variante zutreffen.

*_Anwendungsbeispiel_*: +
Stell dir vor, du verkaufst Bluetooth-Kopfhörer.
Es gibt viele verschiedene Bluetooth-Profile.
Einige deiner Kopfhörer unterstützen alle Profile, andere unterstützen nur ein oder zwei Profile.
Du willst für jeden Kopfhörer angeben, welche Profile unterstützt werden, z.B. "Bluetooth Profil: A2DP, AVRCP, HFP, HSP".

. <<artikel/einstellungen/eigenschaften#710, Erstens>>: Erstellst du die verschiedenen Auswahlmöglichkeiten, d.h. alle Bluetooth-Profile.
. <<artikel/einstellungen/eigenschaften#1400, Zweitens>>: Während du die Eigenschaft mit deinen Varianten verknüpfst, gibst du an, welche Kopfhörer welche Profile unterstützen.
//. <<artikel/frontend-artikelsuche-verwalten#, Drittens>> erstellst du Webshop-Filter, die es deinen Kunden ermöglichen, gezielt nach Varianten mit solchen Besonderheiten zu suchen.
!======

| *Position*
|Welche Eigenschaft soll als erste, zweite, dritte, usw. angezeigt werden? Gib eine Positionsnummer in dieses Feld ein. Wenn eine Variante mehrere Eigenschaften hat, werden die Eigenschaften aufsteigend nach Positionsnummern in deinem plentyShop dargestellt.
|======

[#property-names]
==== Namen

[cols="1,4a"]
|======
|Einstellung |Erläuterung

| *Name*
|Gib einen Namen für die Eigenschaft in der angegebenen Sprache ein.
Dieser Name kann für Kunden <<artikel/einstellungen/eigenschaften#1500, im plentyShop sichtbar gemacht werden>>. Dies hängt davon ab, wie du das Layout mit ShopBuilder gestaltest.

*_Hinweis_*: Klicke auf icon:plus[role="darkGrey"], um den Namen in weitere Sprachen zu übersetzen.

| *Beschreibung*
|Gib eine Beschreibung für die Eigenschaft in der angegebenen Sprache ein.
Diese Beschreibung kann für Kunden <<artikel/einstellungen/eigenschaften#1500, im plentyShop sichtbar gemacht werden>>. Dies hängt davon ab, wie du das Layout mit ShopBuilder gestaltest.

Eine mögliche Anwendung ist die Darstellung eines erklärenden Textes für eine Bestelleigenschaft.

*_Hinweis_*: Klicke auf icon:plus[role="darkGrey"], um die Beschreibung in weitere Sprachen zu übersetzen.

| icon:plus[role="darkGrey"]
|Ist dein plentyShop in mehreren Sprachen verfügbar?

. Klicke auf icon:plus[role="darkGrey"] und wähle eine Sprachversion aus der Dropdown-Liste.
. Gib Übersetzungen für den Namen und die Beschreibung ein.

//sichtbar im Webshop je nachdem wie man ShopBuilder konfiguriert?
//Die Beschreibung wird angezeigt, wenn du mit dem Mauszeiger auf das Merkmal zeigst.
|======

[#property-selection-values]
==== Auswahlwerte

[IMPORTANT]
.Nicht für jeden Eigenschaftstyp sichtbar
====
Diesen Bereich siehst du nur, wenn du mit einer Eigenschaft vom Typ *Auswahl* oder *Mehrfachauswahl* arbeitest.
Dieser Bereich ist für alle anderen Eigenschaftstypen unsichtbar.
====

Hier definierst du die einzelnen Werte, die zur Auswahl stehen.

. Klicke auf *Auswahlwert anlegen* (icon:plus[role="darkGrey"]). +
→ Das Fenster *Auswahlwert anlegen* wird geöffnet.
. Gib einen Namen für den Wert in der angegebenen Sprache ein.
. Wähle bei Bedarf eine Positionsnummer.
. Klicke auf *Speichern*. +
→ Der Wert wird erstellt und in der Übersicht angezeigt.
Der Wert erhält automatisch eine fortlaufende und einzigartige ID, die nicht geändert werden kann.
. Ist dein plentyShop in mehreren Sprachen verfügbar?
Dann klicke auf den Wert, um eine Detailansicht zu öffnen.
Dort kannst du Übersetzungen und Beschreibungen für den Wert eingeben.

[#property-amazon]
==== Amazon

Bei Bedarf kannst du hier <<maerkte/amazon/varianten-vorbereiten#1390, die Eigenschaft mit Amazon-Felder verknüpfen>>.
Dazu muss vorab im Bereich *Sichtbarkeit* eine Amazon-Herkunft aktiviert werden.

. Klicke auf *Verknüpfung hinzufügen* (icon:plus[role="darkGrey"]).
. Wähle mit Hilfe der drei Dropdown-Listen die passende Amazon-Plattform, Kategorie und Feld.
. Wiederhole den Vorgang, wenn du weitere Amazon-Felder verknüpfen möchtest.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Die Eigenschaft ist mit Amazon verknüpft und wird beim nächsten Artikelexport übertragen.

[#property-groups]
==== Gruppen

Soll die Eigenschaft einer oder mehreren <<artikel/einstellungen/eigenschaften#1200, Gruppen>> zugewiesen werden?
Falls ja, wähle die passende Gruppe aus der Dropdown-Liste aus.
Die gewählten Gruppen werden hier als sogenannte "Chips" dargestellt.
Klicke auf icon:close[set=darkGrey], um eine Gruppe wieder zu entfernen.

*_Hinweis_*: Diese Dropdown-Liste enthält nur <<artikel/einstellungen/eigenschaften#1200, Eigenschaftsgruppen, die bereits angelegt wurden>>.

[discrete]
===== Mehrere Eigenschaften einer Gruppe zuordnen

Es würde viel Zeit in Anspruch nehmen, manuell die Gruppe für jede einzelne Eigenschaft auszuwählen.
 plentymarkets enthält eine Funktion, mit der du mehrere Eigenschaften gleichzeitig einer Gruppe zuordnen kannst.

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Wähle die Eigenschaften (icon:check-square[role="blue"]), die du der Gruppe zuordnen möchtest.
. Klicke auf *Gruppen verknüpfen* (icon:link[set=material]). +
→ Das Fenster *Gruppen verknüpfen* wird geöffnet.
. Wähle eine oder mehrere Eigenschaftsgruppen (icon:check-square[role="blue"]).
. Klicke auf *Link*. +
→ Die gewählten Eigenschaften werden den Gruppen zugeordnet.

[#property-visibilities]
==== Sichtbarkeiten

[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Herkunft*
|Auf welchen Verkaufskanälen soll die Eigenschaft sichtbar sein?
Wähle (icon:check-square[role="blue"]) eine, mehrere oder alle Herkünfte.
Gib ein Wort in die Suchleiste ein, um die Ergebnisliste in Echtzeit einzugrenzen.

*_Hinweis_*: Die Dropdown-Liste enthält nur aktivierte Auftragsherkünfte.
Falls du also einen bestimmten Marktplatz in der Liste nicht finden kannst, öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft* und stelle sicher, dass der Markt aktiviert wurde (icon:check-square[role="blue"]).

| *Mandant*
|Soll die Eigenschaft nur für bestimmte Mandanten (Shops) gelten? Falls ja, dann wähle alle Mandanten (icon:check-square[role="blue"]), für die diese Eigenschaft gelten soll.
Gib ein Wort in die Suchleiste ein, um die Ergebnisliste in Echtzeit einzugrenzen.

*_Hintergrund-Info_*: Mit plentymarkets kannst du mehrere Webshops, d.h. <<webshop/mandanten-verwalten#, mehrere Mandanten>>, mit nur einer Software verwalten. Somit ist es möglich, über ein plentymarkets System mehrere unterschiedliche Geschäftsbereiche zu realisieren. Das ist ein großer Vorteil. Aber es bedeutet auch, dass du plentymarkets immer mitteilen musst, für welchen Webshop die Eigenschaft gilt.

| *Überall anzeigen*
|Wo soll die Eigenschaft angezeigt werden? Wähle die Bereiche (icon:check-square[role="blue"]), wo deine Kunden die Eigenschaft sehen sollen.
|====

[#property-options]
==== Optionen

[cols="1,4a"]
|====
|Einstellung |Erläuterung

| *Einheiten*
|Handelt es sich bei der Eigenschaft um etwas wie ein Gewicht oder eine Länge, z.B. ein HDMI-Kabel mit einer Länge von 10 m?
Falls ja, dann wähle die passende <<artikel/einstellungen/einheiten#, Einheit>>.

| *Steuersatz*
|

[cols="1,4a"]
!======

! *Keine Besteuerung*
!Wähle diese Option (icon:check-square[role="blue"]), wenn _keine Mehrwertsteuer_ auf den eingegebenen Aufpreis berechnet werden soll.

Eine mögliche Anwendung ist z.B. die Darstellung von Pfandbeträgen, bei denen keine Mehrwertsteuer angewendet wird.
//In Rechnungen etc. erscheinen Merkmale, bei denen diese Option gewählt wurde, als eigene Position mit der ID -2.

! *Steuersatz von Variante*
!Wähle diese Option (icon:check-square[role="blue"]), wenn auf den eingegebenen Aufschlag _dieselbe Mehrwertsteuer_ berechnet werden soll, wie für die Variante.

Welcher Mehrwertsteuersatz für die Variante gespeichert ist, siehst du im Menü <<artikel/artikel-verwalten#280, Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Kosten » Dropdown-Liste: Umsatzsteuer>>.

! *Steuersatz A, B, C, D*
!Wähle diese Option (icon:check-square[role="blue"]), wenn _ein bestimmter Mehrwertsteuersatz_ auf den eingegebenen Aufschlag berechnet werden soll.

Die einzelnen Umsatzsteuersätze findest du im Menü <<auftraege/buchhaltung#550, Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Buchhaltung » Tab: Umsatzsteuersätze » [Konfiguration öffnen]>>.
!======

|
|

[cols="1,4a"]
!======

! *Bestelleigenschaft*
!Wähle diese Option (icon:check-square[role="blue"]), wenn die Eigenschaft dazu verwendet werden soll, dass Kunden ihre <<artikel/anwendungsfaelle/personalisierte-artikel#, Bestellungen personalisieren>> können.
Zum Beispiel:

* durch die Eingabe eines persönlichen Gravurtextes.
* durch die Auswahl zusätzlicher Serviceleistungen gegen Aufpreis.

! *zusätzliche Kosten anzeigen*
!
//stimmt das überhaupt, es ist nur eine Mutmaßung.
//fest steht, dass wenn man diese Option anklickt, dann wird die Eigenschaft im Artikeldatensatz unter Portlet "Bestelleigenschaften" sortiert
icon:check-square[role="blue"] = Der Aufpreis wird zur Gesamtsumme addiert.
Dabei wird auch der genaue Wert des Aufpreises separat angegeben.

icon:square-o[role="blue"] = Der Aufpreis wird zur Gesamtsumme addiert.
Der genaue Wert des Aufpreises wird aber nicht gesondert erwähnt.

! *als Mehrzeiliges Textfeld anzeigen*
!
//was macht diese Option?

//|[#intable-preiskalk]*Preiskalkulationseigenschaft*
//|Eigenschaften vom Typ "Ganze Zahl" oder "Kommazahl" können in <<artikel/einstellungen/preise#1000, Preiskalkulationen>> verwendet werden.
//Wähle diese Option (icon:check-square[role="blue"]), wenn du eine Eigenschaft vom Typ "Ganze Zahl" oder "Kommazahl" erstellst und sie in Preiskalkulationen verfügbar sein soll.
!======

| *Aufpreis*
|Willst du diese Eigenschaft gegen einen Aufpreis anbieten?
Aufpreise werden zum Beispiel erhoben für:

* zusätzliche Optionen oder Dienstleistungen, die Kunden bei der Bestellung wählen können.
* Pfandbeträge auf Glasflaschen

Wenn für die Eigenschaft ein Aufpreis berechnet werden soll, dann gib den Wert hier ein.
Aufpreise werden im plentyShop in der Artikelansicht und im Bestellvorgang automatisch zum Artikelpreis hinzu addiert.
//Standardmäßig ist 0,00 eingestellt und kein Aufpreis wird berechnet.
|====
