= Dein Vertrag mit plentymarkets
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Admin, Systemadministrator, System-Administrator, Systemadministration, System-Administration, Systemadmin, System-Admin, Konto, Mein Konto, Vertrag, Verträge, Service-Center, Service-Centre, Service Center, Service Centre, Tarif, Tarifwechsel, Tarif wechseln, Mandant, Mandant buchen, kündigen, plentymarkets kündigen, Vertrag kündigen, Kündigung, DSGVO, Domain, Agentur, Agenturen, Zugang, Zugriff
:description: Lerne, wie du auf den Mein Konto-Bereich zugreifst und Änderungen an deinem plentymarkets-Vertrag vornimmst.
:position: 10
:url: business-entscheidungen/dein-vertrag
:id: ZGJLXUS
:author: team-cloud

Im Menü *plentymarkets Logo (Start) » Mein Konto* findest du Informationen zu deinem plentymarkets System. Du kannst Änderungen an den hier gespeicherten Informationen selbst vornehmen.
Zum Beispiel kannst du:

* deinen Vertrag mit plentymarkets einsehen und bearbeiten.
* einen zusätzlichen Mandanten (Shop) buchen.
* die Kontaktinformationen, die wir für dich gespeichert haben, ändern.
* Partneragenturen Zugang zu deinem System ermöglichen.

[#20]
== Dein Vertrag mit plentymarkets

Im Menü *plentymarkets Logo (Start) » Mein Konto » Verträge* kannst du Informationen zu deinem Vertrag mit plentymarkets einsehen und bearbeiten.
Hier kannst du zum Beispiel:

* <<#30, zu einem anderen Tarif wechseln>>
* <<#40, gebuchte Leistungen einsehen>>
* <<#50, Buchungen im Verrechnngskonto nachvollziehen>>
* <<business-entscheidungen/rechtliches/dsgvo#500, DSGVO-relevante Dokumente einsehen>>

[TIP]
.Service-Center wurde aufgelöst
====
Vielleicht kannst du dich daran erinnern, deine Vertragsinformationen früher mal im Menü *plentymarkets Logo (Start) » Service-Center* eingesehen zu haben. Das Service-Center wurde aufgelöst.
Vertragsinformationen werden jetzt im Bereich "Mein Konto" verwaltet.
====

[#30]
=== Tarif wechseln

plentymarkets wächst mit deinen Anforderungen.
Du entscheidest selbst, z.B. welche Module dein Unternehmen benötigt und wie viele Aufträge du ungefähr pro Monat mit plentymarkets abwickeln wirst.
Wir stellen dir dafür die nötige Systemleistung zur Verfügung.

Im Bereich "Mein Konto" kannst du deinen plentymarkets Vertrag eigenständig im laufenden Betrieb anpassen.
Eine Anpassung des Vertrags ist zum Beispiel sinnvoll, wenn du mehr Aufträge generierst als im bestehenden Vertrag enthalten sind. Die Buchung einer höheren Anzahl an Aufträgen ist jederzeit möglich. Wenn du eine niedrigere Anzahl buchst, wird diese Änderung erst nach Ablauf der regulären Laufzeit deines aktuellen Vertrags wirksam.

[.instruction]
Vertrag ändern:

include::_textblocks/mein-konto/tarifkonfigurator-aufrufen.adoc[]

[#40]
=== Leistungen einsehen

Im Bereich "Mein Konto" siehst du alle in Rechnung gestellten Posten. 

[.instruction]
Leistungen einsehen:

. Öffne das Menü *plentymarkets Logo (Start) » Mein Konto*. +
*_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links. +
→ Der Bereich "Mein Konto" wird in einem neuen Browser-Tab geöffnet.
. Klicke auf icon:file-text[role="darkGrey"] *Verträge*. +
→ Informationen über deine laufenden Verträge werden angezeigt.

[discrete]
==== Leistungen kündigen

Gehe wie unten beschrieben vor, um Leistungen zu kündigen. Du kannst einzelne Module oder sogar deinen gesamten Vertrag mit plentymarkets kündigen.

[.instruction]
Leistungen kündigen:

. Öffne das Menü *plentymarkets Logo (Start) » Mein Konto*. +
*_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links. +
→ Der Bereich "Mein Konto" wird in einem neuen Browser-Tab geöffnet.
. Klicke auf icon:file-text[role="darkGrey"] *Verträge*. +
. Klappe die Vertragsinformationen auf (icon:chevron-down[role="darkGrey"]). +
→ Klicke auf icon:ban[role="red"] [red]#Vertrag kündigen# oben rechts, um eine Kündigung deines gesamten Vertrags in Auftrag zu geben. +
→ Klicke auf icon:trash[role="darkGrey"] *Jetzt kündigen* neben einem bestimmten Modul, um nur diese spezifische Dienstleistung zu kündigen.

[#50]
=== Buchungen im Verrechnungskonto nachvollziehen

Beinhaltet dein plentymarkets Tarif ein gewisses Kontingent an kostenpflichtigem Support oder hast du ein von der plentysystems AG angebotenes link:https://marketplace.plentymarkets.com/services/einrichtung[Einrichtungsangebot^] im plentyMarketplace erworben?
In diesem Fall bietet dir das Verrechnungskonto eine Übersicht über die Beträge und Buchungen, die plentymarkets dir zum kommenden Rechnungsdatum in Rechnung stellen wird. So kannst du jederzeit unkompliziert einsehen, welche Transaktionen anfallen und wie hoch das aktuell verbleibende Guthaben aus den von dir erworbenen Angeboten ist.

Gehe wie unten beschrieben vor, um die Buchungen im Verrechnungskonto nachzuvollziehen.

[.instruction]
Buchungen im Verrechnungskonto nachvollziehen:

. Öffne das Menü *plentymarkets Logo (Start) » Mein Konto*. +
*_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links. +
→ Der Bereich "Mein Konto" wird in einem neuen Browser-Tab geöffnet.
. Klicke auf icon:file-text[role="darkGrey"] *Verrechnungskonto*. +
→ Das Verrechnungskonto wird angezeigt. +
*_Hinweis:_* Das Verrechnungskonto wird nur angezeigt, wenn einer der <<#50, oben genannten Fälle>> auf dich zutrifft. Andernfalls wird dir standardmäßig ein Hinweis angezeigt, der besagt, dass kein Verrechnungskonto zur Verfügung steht.

[.collapseBox]
.*Was bedeuten die Einträge im Verrechnungskonto im Detail?*
--

[[tabelle-eintraege-verrechnungskonto]]
[width="100%"]
[cols="1,3"]
|====
|Information |Erläuterung

| *Datum*
| Das Datum der Buchung.

| *Unterkonto*
| Aktuell steht das Unterkonto vom Typ *Support* zur Verfügung. Künftig werden weitere Unterkonten hinzugefügt, sodass auch andere Verbrauchsarten aufgeschlüsselt dargestellt werden können.

| *Referenz*
| Dieses Feld gibt Aufschluss darüber, für welche Leistung und an welchem Datum eine Gutschrift oder eine Negativbuchung auf dem Verrechnungskonto vorgenommen wurde. In manchen plentymarkets Tarifen sind Supportleistungen monatlich inbegriffen. Für diese Gutschriften wird als Datumsbereich die reguläre einmonatige Rechnungsperiode angegeben.

| *Betrag*
| Der Betrag der Buchung. Positive Buchungen werden in grün, negative Buchungen in rot dargestellt.

|====

--
    
[TIP]
.Weitere Funktionalitäten in Planung
====
Unser Ziel ist es, dir mit dem Verrechnungskonto jederzeit einen aktuellen und transparenten Einblick in deine Buchungen zu ermöglichen. Dazu werden wir in naher Zukunft nach und nach weitere Funktionen einbauen und Informationen differenzierter darstellen. Abonniere unseren link:https://forum.plentymarkets.com/c/changelog[Changelog^], um über alle Neuerungen auf dem Laufenden zu bleiben.
====

[#370]
=== Praxisbeispiel: Einen zusätzlichen Webshop buchen

<<webshop#, Mandanten (Shops)>> sind weitere Webshops, die über den zugeordneten Hauptshop in deinem plentymarkets System konfigurierbar sind.
Im Bereich "Mein Konto" werden die vorhandenen Webshops angezeigt. Du kannst bei Bedarf zusätzliche Webshops buchen.

[IMPORTANT]
.Domain-Einstellungen von Mandanten (Shops)
====
Um einen Mandanten (Shop) zu bestellen, benötigst du eine <<business-entscheidungen/systemadministration/domains#, Domain>>. Diese Domain musst du vorher für das Hauptsystem erstellen.
====

[.instruction]
Mandanten (Shop) bestellen:

. Öffne das Menü *plentymarkets Logo (Start) » Mein Konto*. +
*_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links. +
→ Der Bereich "Mein Konto" wird in einem neuen Browser-Tab geöffnet.
. Klicke auf icon:file-text[role="darkGrey"] *Verträge*. +
→ Informationen über deine laufenden Verträge werden angezeigt.
. Klicke auf icon:pencil[role="darkGrey"] *Vertrag bearbeiten*. +
→ Der Tarifkonfigurator wird eingeblendet.
. Passe die Vertragsdetails wie gewünscht an.

[#440]
== Zertifizierten Agenturen Zugang zum System geben

Im Menü *plentymarkets Logo (Start) » Mein Konto » Agentur* gibst du zertifizierten Dienstleistern Zugriff auf dein System.
Es ist sinnvoll, einem Dienstleister Zugang zu deinem System zu gewähren, z.B. wenn du eine Design-Agentur mit der Erstellung deiner Website beauftragst oder wenn du mit einem Consultant zusammenarbeitest.
Der Dienstleister erhält dann unbegrenzten, d.h. Admin-Zugang zu deinem System.

[TIP]
.Entscheide selbst, welche Funktionen und Menüs zugänglich sein sollen!
====
Wenn du einer Agentur Zugang zu deinem System gewährst, gibst du dieser Agentur unbegrenzten, administrativen Zugang.

Wenn du der Agentur lieber nur Zugang zu bestimmten Funktionen oder Menüs geben möchtest, dann <<business-entscheidungen/benutzerkonten-zugaenge#, erstelle ein neues Benutzerkonto>>, z.B. ein Backend-Konto, und passe die Zugriffsrechte an.
====

[#450]
=== Zugriff gewähren

Gehe wie unten beschrieben vor, um der Agentur und/oder dem Consultant, mit denen du zusammenarbeitest, Zugriff auf dein System zu gewähren:

[.instruction]
Dienstleister zuweisen:

. Öffne das Menü *plentymarkets Logo (Start) » Mein Konto*. +
*_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links. +
→ Der Bereich "Mein Konto" wird in einem neuen Browser-Tab geöffnet.
. Klicke auf icon:handshake-o[role="darkGrey"] *Agenturen*. +
→ Informationen über die Agenturen, mit denen du bereits zusammenarbeitest, werden angezeigt.
. Klicke auf icon:plus[role="darkGrey"] *Agentur hinzufügen*. +
→ Eine Liste der zertifizierten Dienstleister wird angezeigt.
. Klicke auf icon:plus[role="darkGrey"] *Hinzufügen* neben der Agentur, die Zugang zu deinem System erhalten soll.

*_Hinweis_*: Du kannst diesen Zugang jederzeit entziehen.

[#460]
=== Zugriff entziehen

Möchtest du den Systemzugriff für eine Agentur dauerhaft entziehen? Dann gehe wie unten beschrieben vor.

. Öffne das Menü *plentymarkets Logo (Start) » Mein Konto*. +
*_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links. +
→ Der Bereich "Mein Konto" wird in einem neuen Browser-Tab geöffnet.
. Klicke auf icon:handshake-o[role="darkGrey"] *Agenturen*. +
→ Informationen über die Agenturen, mit denen du bereits zusammenarbeitest, werden angezeigt.
. Klicke im Bereich der Agentur, deren Zugriff entfernt werden soll, auf *Entfernen*. +
→ Ein Bestätigungsdialog wird angezeigt.
. Klicke auf *Jetzt entfernen*, um deine Auswahl zu bestätigen. +
→ Der Systemzugriff wird für die gewählte Agentur dauerhaft entzogen.

[IMPORTANT]
.Agenturzugriff effektiv entfernen
====
Folge unbedingt den oben beschriebenen Schritten, um den Agenturzugriff dauerhaft und sicher zu entziehen. Es reicht **nicht** aus, den von der Agentur angelegten <<business-entscheidungen/benutzerkonten-zugaenge#85, Benutzer im plentymarkets Backend zu löschen>>.
====


