= Dein Vertrag mit plentymarkets
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Admin, Systemadministrator, System-Administrator, Systemadministration, System-Administration, Systemadmin, System-Admin, Konto, Mein Konto, Vertrag, Verträge, Service-Center, Service-Centre, Service Center, Service Centre, Tarif, Tarifwechsel, Tarif wechseln, Mandant, Mandant buchen, kündigen, plentymarkets kündigen, Vertrag kündigen, Kündigung, DSGVO, Domain, Agentur, Agenturen, Zugang, Zugriff
:description: Lerne, wie du auf den Mein Konto-Bereich zugreifst und Änderungen an deinem plentymarkets-Vertrag vornimmst.
:position: 10
:url: business-entscheidungen/dein-vertrag
:id: ZGJLXUS
:author: team-cloud

Im Menü *plentymarkets Logo (Start) » Mein Konto* findest du Informationen zu deinem plentymarkets System. Du kannst Änderungen an den hier gespeicherten Informationen selbst vornehmen.
Zum Beispiel kannst du:

* deinen Vertrag mit plentymarkets einsehen und bearbeiten.
* einen zusätzlichen Mandanten (Shop) buchen.
* die Kontaktinformationen, die wir für dich gespeichert haben, ändern.
* Partneragenturen Zugang zu deinem System ermöglichen.

[#20]
== Dein Vertrag mit plentymarkets

Im Menü *plentymarkets Logo (Start) » Mein Konto » Verträge* kannst du Informationen zu deinem Vertrag mit plentymarkets einsehen und bearbeiten.
Hier kannst du zum Beispiel:

* <<#30, zu einem anderen Tarif wechseln>>
* <<#40, gebuchte Leistungen einsehen und bei Bedarf kündigen>>
* <<business-entscheidungen/rechtliches/dsgvo#500, DSGVO-relevante Dokumente einsehen>>

[TIP]
.Service-Center wurde aufgelöst
====
Vielleicht kannst du dich daran erinnern, deine Vertragsinformationen früher mal im Menü *plentymarkets Logo (Start) » Service-Center* eingesehen zu haben. Das Service-Center wurde aufgelöst.
Vertragsinformationen werden jetzt im Bereich "Mein Konto" verwaltet.
====

[#30]
=== Tarif wechseln

plentymarkets wächst mit deinen Anforderungen.
Du entscheidest selbst, z.B. welche Module dein Unternehmen benötigt und wie viele Aufträge du ungefähr pro Monat mit plentymarkets abwickeln wirst.
Wir stellen dir dafür die nötige Systemleistung zur Verfügung.

Im Bereich "Mein Konto" kannst du deinen plentymarkets Vertrag eigenständig im laufenden Betrieb anpassen.
Eine Anpassung des Vertrags ist zum Beispiel sinnvoll, wenn du mehr Aufträge generierst als im bestehenden Vertrag enthalten sind. Die Buchung einer höheren Anzahl an Aufträgen ist jederzeit möglich. Wenn du eine niedrigere Anzahl buchst, wird diese Änderung erst nach Ablauf der regulären Laufzeit deines aktuellen Vertrags wirksam.

[.instruction]
Vertrag ändern:

include::_textblocks/mein-konto/tarifkonfigurator-aufrufen.adoc[]

[#40]
=== Leistungen einsehen und bei Bedarf kündigen

Im Bereich "Mein Konto" siehst du alle in Rechnung gestellten Posten. Bei Bedarf kannst du hier einzelne Module oder sogar deinen gesamten Vertrag mit plentymarkets kündigen.

[.instruction]
Leistungen einsehen und kündigen:

. Öffne das Menü *plentymarkets Logo (Start) » Mein Konto*. +
*_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links. +
→ Der Bereich "Mein Konto" wird in einem neuen Browser-Tab geöffnet.
. Klicke auf icon:file-text[role="darkGrey"] *Verträge*. +
→ Informationen über deine laufenden Verträge werden angezeigt.
. Klappe die Vertragsinformationen auf (icon:chevron-down[role="darkGrey"]). +
→ Klicke auf icon:ban[role="red"] [red]#Vertrag kündigen# oben rechts, um eine Kündigung deines gesamten Vertrags in Auftrag zu geben. +
→ Klicke auf icon:trash[role="darkGrey"] *Jetzt Kündigen* neben einem bestimmten Modul, um nur diese spezifische Dienstleistung zu kündigen.

[.collapseBox]
.*Vertragsende: Daten*
--

Vor Vertragsende oder Kündigung solltest du dir überlegen, welche Daten du auch über das Bestehen deines Systems hinaus benötigst. Denn deine Daten werden nicht automatisch gespeichert und sind auch nicht zu einem späteren Punkt einseh- oder abrufbar. Überlege daher zum Beispiel, welche steuerrelevanten Informationen du später noch brauchst. Wir empfehlen mindestens die Beachtung der folgenden Punkte:

[[table-end-of-contract-data-export]]
.Empfohlene Exporte bei Vertragsende
[cols="1,3"]
|====
|Einstellung|Erläuterung

|*Buchhaltungsdaten*
| Nutze den Spezialexport im Menü *Daten » Spezialexport*, um einen Export deiner Finanzbuchhaltung durchzuführen. Wähle dafür in diesem Menü die Art des Exports aus der Dropdown-Liste (z.B. *Finanzbuchhaltung*) und nimm die für dich passenden Einstellungen vor.

|*Dokumente*
|Exportiere benötigte Dokumente über das Dokumentenarchiv. Gehe dazu ins Menü *Aufträge » Dokumentenarchiv* und wähle das Tab *Export*. Nimm die für dich passenden Einstellungen vor und exportiere alle relevanten Dokumente. Beachte sowohl bei der Auswahl der Dokumente als auch des Zeitraumes auch steuerrechtliche Vorgaben sowie gesetzliche Vorgaben zu Aufbewahrungszeiten.

|*Warenbestand*
|Erstelle im Menü *Daten » Elastischer Export* ein Exportformat für deinen <<daten/daten-exportieren/FormatDesigner/format-typen/warenbestand, Warenbestand>>. Wir empfehlen mindestens die Auswahl folgender Exportfelder: +
- Item.id = Artikel-ID +
- ItemDescription.name = Artikelname +
- Variation.name = Variantenname +
- Stock.averagePurchasePrice = Durchschnittlicher Einkaufspreis +
- Stock.stock.Physical = Physischer Bestand +
- Stock.stockNet = Netto-Bestand +
- Warehouse.name = Name des Lagers

|*Warenbewegungen*
|Erstelle im Menü *Daten » Elastischer Export* ein Exportformat für deine <<daten/daten-exportieren/FormatDesigner/format-typen/warenbewegungen, Warenbewegungen>>. Wir empfehlen mindestens die Auswahl folgender Exportfelder: +
- StockMovements.id = Vorgangs-ID der Warenbewegung +
- StockMovements.itemid = Artikel-ID +
- Variation.id = Varianten-ID +
- StockMovements.attributeValues = Attributwerte +
- StockMovements.warehouseName = Name des Lagers aus dem ein- oder ausgebucht wurde +
- StockMovements.reasonString = Name des Grundes der Warenbewegung +
- StockMovements.quantity = Anzahl des bewegten Warenbestands +
- User.user = Name des Benutzers, der die Warenbewegung gebucht hat +
- StockMovements.createdAt = Zeitstempel der Warenbewegung

|====

Diese Liste erhebt keinen Anspruch auf Vollständigkeit, erstelle ggf. weitere Exporte für wichtige Informationen und Daten.

Wende dich ansonsten an unser Sales-Team. In Einzelfällen greift eine Kulanzregelung und ein Downgrade in die Basic-Edition ist möglich. So könnt ihr das System weiterhin erhalten und bei Bedarf auch wieder reaktivieren und upgraden.

--

[#370]
=== Praxisbeispiel: Einen zusätzlichen Webshop buchen

<<webshop#, Mandanten (Shops)>> sind weitere Webshops, die über den zugeordneten Hauptshop in deinem plentymarkets System konfigurierbar sind.
Im Bereich "Mein Konto" werden die vorhandenen Webshops angezeigt. Du kannst bei Bedarf zusätzliche Webshops buchen.

[IMPORTANT]
.Domain-Einstellungen von Mandanten (Shops)
====
Um einen Mandanten (Shop) zu bestellen, benötigst du eine <<business-entscheidungen/systemadministration/domains#, Domain>>. Diese Domain musst du vorher für das Hauptsystem erstellen.
====

[.instruction]
Mandanten (Shop) bestellen:

. Öffne das Menü *plentymarkets Logo (Start) » Mein Konto*. +
*_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links. +
→ Der Bereich "Mein Konto" wird in einem neuen Browser-Tab geöffnet.
. Klicke auf icon:file-text[role="darkGrey"] *Verträge*. +
→ Informationen über deine laufenden Verträge werden angezeigt.
. Klicke auf icon:pencil[role="darkGrey"] *Vertrag bearbeiten*. +
→ Der Tarifkonfigurator wird eingeblendet.
. Passe die Vertragsdetails wie gewünscht an.

[#440]
== Zertifizierten Agenturen Zugang zum System geben

Im Menü *plentymarkets Logo (Start) » Mein Konto » Agentur* gibst du zertifizierten Dienstleistern Zugriff auf dein System.
Es ist sinnvoll, einem Dienstleister Zugang zu deinem System zu gewähren, z.B. wenn du eine Design-Agentur mit der Erstellung deiner Website beauftragst oder wenn du mit einem Consultant zusammenarbeitest.
Der Dienstleister erhält dann unbegrenzten, d.h. Admin-Zugang zu deinem System.

[TIP]
.Entscheide selbst, welche Funktionen und Menüs zugänglich sein sollen!
====
Wenn du einer Agentur Zugang zu deinem System gewährst, gibst du dieser Agentur unbegrenzten, administrativen Zugang.

Wenn du der Agentur lieber nur Zugang zu bestimmten Funktionen oder Menüs geben möchtest, dann <<business-entscheidungen/benutzerkonten-zugaenge#, erstelle ein neues Benutzerkonto>>, z.B. ein Backend-Konto, und passe die Zugriffsrechte an.
====

[#450]
=== Zugriff gewähren

Gehe wie unten beschrieben vor, um der Agentur und/oder dem Consultant, mit denen du zusammenarbeitest, Zugriff auf dein System zu gewähren:

[.instruction]
Dienstleister zuweisen:

. Öffne das Menü *plentymarkets Logo (Start) » Mein Konto*. +
*_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links. +
→ Der Bereich "Mein Konto" wird in einem neuen Browser-Tab geöffnet.
. Klicke auf icon:handshake-o[role="darkGrey"] *Agenturen*. +
→ Informationen über die Agenturen, mit denen du bereits zusammenarbeitest, werden angezeigt.
. Klicke auf icon:plus[role="darkGrey"] *Agentur hinzufügen*. +
→ Eine Liste der zertifizierten Dienstleister wird angezeigt.
. Klicke auf icon:plus[role="darkGrey"] *Hinzufügen* neben der Agentur, die Zugang zu deinem System erhalten soll.

*_Hinweis_*: Du kannst diesen Zugang jederzeit entziehen.

[#460]
=== Zugriff entziehen

Möchtest du den Systemzugriff für eine Agentur dauerhaft entziehen? Dann gehe wie unten beschrieben vor.

. Öffne das Menü *plentymarkets Logo (Start) » Mein Konto*. +
*_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links. +
→ Der Bereich "Mein Konto" wird in einem neuen Browser-Tab geöffnet.
. Klicke auf icon:handshake-o[role="darkGrey"] *Agenturen*. +
→ Informationen über die Agenturen, mit denen du bereits zusammenarbeitest, werden angezeigt.
. Klicke im Bereich der Agentur, deren Zugriff entfernt werden soll, auf *Entfernen*. +
→ Ein Bestätigungsdialog wird angezeigt.
. Klicke auf *Jetzt entfernen*, um deine Auswahl zu bestätigen. +
→ Der Systemzugriff wird für die gewählte Agentur dauerhaft entzogen.

[IMPORTANT]
.Agenturzugriff effektiv entfernen
====
Folge unbedingt den oben beschriebenen Schritten, um den Agenturzugriff dauerhaft und sicher zu entziehen. Es reicht **nicht** aus, den von der Agentur angelegten <<business-entscheidungen/benutzerkonten-zugaenge#85, Benutzer im plentymarkets Backend zu löschen>>.
====
