:lang: de
:keywords: Click & Collect, Abholung, Online bestellen und im Laden abholen
:position: 1



=== Zahlungsmethode

* Stellen Sie das Plugin link: https://marketplace.plentymarkets.com/plugins/payment/PayUponPickup_4757[Barzahlung] für den Mandanten bereit. +
→ Standardmäßig wird im Webshop der Name der Zahlungsart, also "Barzahlung" angezeigt. Ändern Sie auf Wunsch den Namen der Zahlungsart, z.B. in "Bezahlung im Laden".


=== Versandeinstellungen

Wenn Sie bereits eine Kasse nutzen, haben Sie bereits einen Versanddienstleister *Selbstabholung* und ein Versandprofil *Selbstabholung* erstellt.


////
Aus der POS-Beschreibung:
* Versanddienstleister Selbstabholung erstellen
* Versandprofil Selbstabholung erstellen
* Versandprofil Selbstabholung am Artikel aktivieren
////

* Aktivieren Sie das Versandprofil *Selbstabholung* für den Mandanten und die Auftragsherkunft. +
→ Standardmäßig wird im Webshop der Name des Versandprofils, also "Selbstabholung" angezeigt. Ändern Sie auf Wunsch den Namen des Versandprofils, z.B. in "Abholung in der Filiale". +
*_Tipp:_* Dieses Best Practice geht davon aus, dass die Versandkosten entfallen, wenn Kunden die Ware im Laden abholen. Wenn Sie Versandkosten erheben möchten, geben Sie im Tab *Portotabelle* des Versandprofils ein *Pauschales Porto* ein. In diesem Fall sollten Sie jedoch ein eigenes Versandprofil erstellen, das unabhängig von dem im der Kasse verwendeten Versandprofil ist, denn sonst werden für alle POS-Aufträge Versandkosten fällig.


=== Warenwirtschaft

EAs für Warenausgang

* Bei Lieferung in die Filiale
* Bei Übergabe an den Kunden
* Wenn Laden = Lager

Ware wird ausgebucht: Ware wird aus dem Lager ausgebucht, das im Auftrag definiert wurde.

Auftrag sollte nicht in den Prozessen verarbeitet werden.

Nicht bearbeiten: Im Prozess nach Versandprofil filtern und Selbstabholer ausschließen, damit Warenausgang nicht gebucht wird.
