= Best Practice: Click & Collect einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Click & Collect, Abholung, Online bestellen und im Laden abholen
:position: 1


Click & Collect ...




== Versandeinstellungen

Wenn Sie schon eine Kasse nutzen, haben Sie auch schon einen Versanddienstleister *Selbstabholung* und ein Versandprofil *Selbstabholung*. Wir empfehlen aber, für Click & Collect einen eigenen Versanddienstleister und ein eigenes Versandprofil zu erstellen.

[#190]
=== Versanddienstleister für Abholung in der Filiale erstellen

Gehen Sie wie unten beschrieben vor, um einen Versanddienstleister für die Abholung in der Filiale zu erstellen. In diesem Best Practice nennen wir diesen Versanddienstleister *Abholung in der Filiale*. Natürlich können Sie auch einen anderen Namen verwenden.

[.instruction]
Versanddienstleister für Abholung in der Filiale erstellen:

. Öffnen Sie das Menü *System » Aufträge » Versand » Optionen » Tab: Versanddienstleister*.
. Klicken Sie auf *Neu*. +
→ Ganz unten wird eine neue Zeile hinzugefügt.
. Geben Sie in die Spalte *Namen (de)* den Namen *Abholung in der Filiale* ein.
. Geben Sie in die Spalte *Namen (Backend)* den Namen *Abholung in der Filiale* ein.
. Wählen Sie in der Spalte *Versanddienstleister* die Option *Selbstabholer* aus der Dropdown-Liste.
. *Speichern* Sie die Einstellungen.

[#200]
=== Versandprofil für Abholung in der Filiale erstellen

Erstellen Sie nun ein Versandprofil für die Abholung in der Filiale. In diesem Best Practice nennen wir dieses Versandprofil *Abholung in der Filiale*. Natürlich können Sie auch einen anderen Namen verwenden.

[.instruction]
Versandprofil für Abholung in der Filiale erstellen:

. Öffnen Sie das Menü *System » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Klicken Sie auf *Neu*.
. Wählen Sie den Versanddienstleister *Abholung in der Filiale* aus der Dropdown-Liste, den Sie gerade erstellt haben.
. Geben Sie für die Option *Namen (de)* den Namen *Abholung in der Filiale* ein.
. Geben Sie für die Option *Namen (Backend)* den Namen *Abholung in der Filiale* ein.
. Aktivieren Sie den *Mandanten (Shop)*, für den Sie die Abholung in der Filiale anbieten möchten.
. Aktivieren Sie die *Auftragsherkunft*. Wir empfehlen die Herkünfte *0 Manuelle Eingabe* und den *Mandanten (Shop)*.
. **Speichern** Sie die Einstellungen. +
→ Das Tab **Portotabelle** wird angezeigt. +
*_Hinweis:_* Die Abholung in der Filiale ist in der Regel versandkostenfrei. Daher werden in diesem Best Practice keine <<auftragsabwicklung/fulfillment/versand-vorbereiten#1000, Versandkosten gespeichert>>.
. *Speichern* Sie die Einstellungen des Tabs *Portotabelle* ohne Änderungen.


[#210]
=== Versandprofil für Abholung in der Filiale am Artikel aktivieren

Aktivieren Sie nun das Versandprofil *Abholung in der Filiale* bei den Artikeln, die Kunden online bestellen und im Laden abholen können sollen.

[.instruction]
Versandprofil für Abholung in der Filiale am Artikel aktivieren:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab *Global*.
. Aktivieren Sie das Versandprofil *Selbstabholung*.
. *Speichern* Sie die Einstellungen.

Sie möchten das Versandprofil für eine größere Anzahl an Artikeln gleichzeitig aktivieren? Dann nutzen Sie die <<artikel/artikel-verwalten#155, Artikel-Gruppenfunktion>>.


////
== Warenwirtschaft

EAs für Warenausgang

* Bei Lieferung in die Filiale
* Bei Übergabe an den Kunden
* Wenn Laden = Lager

Ware wird ausgebucht: Ware wird aus dem Lager ausgebucht, das im Auftrag definiert wurde.

Auftrag sollte nicht in den Prozessen verarbeitet werden.

Nicht bearbeiten: Im Prozess nach Versandprofil filtern und Selbstabholer ausschließen, damit Warenausgang nicht gebucht wird.
////


== Zahlung im Laden: Zahlungsmethode aktivieren

* Stellen Sie das Plugin link:https://marketplace.plentymarkets.com/plugins/payment/PayUponPickup_4757[Barzahlung] für den Mandanten bereit. +
→ Standardmäßig wird im Webshop der Name der Zahlungsart, also "Barzahlung" angezeigt. Ändern Sie auf Wunsch den Namen der Zahlungsart, z.B. in "Bezahlung in der Filiale".
