= Kataloge verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Katalog, Kataloge, Katalog erstellen, Katalog verwalten, Katalog-Templates, Katalog Templates, Marktplatz, Marktplätze, Märkte, Verkaufskanal, Templates, Datenquellen, Datenquellen kombinieren, Zieldaten, Katalog kopieren, Katalog löschen, Daten übertragen
:description: Im Menü *Daten » Kataloge* konfigurierst du den Export von Variantendaten an Marktplätze.
:position: 50
:url: daten/daten-exportieren/kataloge-verwalten
:id: FHQHFWO
:author: team-elasticsync

Verwende Kataloge, um den Export von Variantendaten an Marktplätze und andere Verkaufskanäle durchzuführen. Aktuell kannst du Kataloge nutzen, um Daten an die Marktplätze REWE, Etsy, Metro und OTTO Market zu übertragen.

Kataloge dienen dazu, Variantendaten für den Export an einen Verkaufskanal vorzubereiten. Auf dieser Handbuchseite erfährst du, wie du Kataloge erstellst und verwaltest.

[#10]
== Was ist ein Katalog?

Jeder Verkaufskanal benötigt unterschiedliche Produktdaten. Häufig müssen auch für verschiedene Produktkategorien (Tierfutter, Haushalt, Lebensmittel) unterschiedliche Produktdaten an denselben Verkaufskanal übermittelt werden.

Kataloge ermöglichen es dir, die Informationen zu deinem Produktsortiment ganz auf die Anforderungen und die Zielgruppe eines Verkaufskanals zuzuschneiden. Denn in Katalogen ordnest du den einzelnen Datenfeldern eines Verkaufskanals eine passende plentymarkets Datenquelle zu. Beim Übermitteln deiner Variantendaten an den Verkaufskanal werden dann die Datenfelder des Verkaufskanal mit den richtigen Daten aus plentymarkets befüllt.

Kataloge bieten die folgenden Vorteile:

* Der Verkaufskanal gibt die Datenstruktur vor. Du weißt also genau, welche Variantendaten nötig sind, um deine Produkte über den Verkaufskanal anzubieten.
* Du bestimmst pro Verkaufskanal oder sogar pro Template, welche Variantendaten auf dem Verkaufskanal veröffentlicht werden. Über Eigenschaften kannst du zum Beispiel unterschiedliche Namen und Beschreibungen an die verschiedenen Marktplätze übertragen.

[TIP]
.Datenexport? FormatDesigner
====
Kataloge dienen dazu, Daten an Verkaufskanäle zu übertragen. Katalogdaten können nicht in eine Datei oder in ein anderes auslesbares Format exportiert werden. Verwende den <<daten/daten-exportieren/FormatDesigner#, FormatDesigner>>, um Daten zu exportieren.
====

[#20]
== Was ist ein Katalog-Template?

Ein Katalog-Template stellt ein Gerüst der Daten bereit, die der Verkaufskanal entgegennehmen kann. Über Katalog-Templates gibt der Verkaufskanal also vor, welche Daten übertragen werden können.

Ein Verkaufskanal kann mehrere Katalog-Templates anbieten, zum Beispiel für verschiedene Produktkategorien (Tiernahrung, Lebensmittel, Non-Food etc.) oder für verschiedene Sprachen. Informationen dazu, welche Katalog-Templates für einen Verkaufskanal verfügbar sind, findest du in der Dokumentation des Verkaufskanals.

[NOTE]
.Katalog-Template nicht gefunden?
====
Die Katalog-Templates bestimmter Verkaufskanäle werden erst in das Menü *Daten » Kataloge* geladen, wenn du das Plugin dieses Verkaufskanals bereitstellst.
====

[#30]
== Variantendaten mit Eigenschaften pflegen

Mit <<artikel/artikel-verwalten#3000, Eigenschaften des Bereichs Artikel>> speicherst du Daten an Varianten, für die es standardmäßig keine Datenfelder im plentymarkets Backend gibt. Im Folgenden findest du einige Beispiele dafür, wie du Eigenschaften nutzt.

==== Beispiel 1: Durchmesserangaben

*Anwendungsfall:* +
An den Verkaufskanal können die Variantendaten *Durchmesser* und *Durchmesser Einheit* übergeben werden. Durchmesserangaben können standardmäßig nicht im plentymarkets Backend gespeichert werden.

*Vorgehensweise:* +
Um Durchmesserdaten trotzdem an den Verkaufskanal zu übergeben, empfehlen wir die in <<tabelle-durchmesser>> beschriebenen Einstellungen.

[[tabelle-durchmesser]]
.Beispiel 1: Durchmesserangaben
[cols="1,3"]
|====
|Datenfeld Verkaufskanal |Eigenschaften in plentymarkets

2+| *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*

| *Durchmesser Einheit*
a| * Eine Eigenschaft *Durchmesser Einheit* erstellen: +
Bereich: *Artikel* +
Eigenschaftstyp: *Auswahl*
* Werte speichern, zum Beispiel *cm* und *mm*

| *Durchmesser*
a| * Eine Eigenschaft *Durchmesser* erstellen: +
Bereich: *Artikel* +
Eigenschaftstyp: *Kommazahl*

2+| *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen*

| *Durchmesser Einheit*
a| * Das Tab *Eigenschaften* öffnen.
* Die Eigenschaft *Durchmesser Einheit* hinzufügen.
* Die Einheit aus der Dropdown-Liste wählen.

| *Durchmesser*
a| * Das Tab *Eigenschaften* öffnen.
* Die Eigenschaft *Durchmesser* hinzufügen.
* Den Durchmesser in der für die Eigenschaft *Durchmesser Einheit* gewählten Einheit eingeben.

2+| *Daten » Kataloge » Katalog öffnen*

| *Durchmesser Einheit*
a| * Aus der Dropdown-Liste *Quelle* die Option *Eigenschaft » Durchmesser Einheit* wählen.

| *Durchmesser*
a| * Aus der Dropdown-Liste *Quelle* die Option *Eigenschaft » Durchmesser* wählen.
|====


==== Beispiel 2: Markennamen

*Anwendungsfall:* +
An den Verkaufskanal kann die Marke von Produkten übergeben werden. Standardmäßig können Hersteller, aber keine Markennamen im plentymarkets Backend gespeichert werden.

*Vorgehensweise:* +
Wenn die Hersteller in deinem System nicht den Markennamen der Produkte widerspiegeln, pflegst du die Marken als Eigenschaften. Wir empfehlen die in <<tabelle-marken>> beschriebenen Einstellungen, um Marken als Eigenschaften an den Verkaufskanal zu übergeben.

[[tabelle-marken]]
.Beispiel 2: Markenangaben
[cols="1,3"]
|====
|Datenfeld Verkaufskanal |Eigenschaften in plentymarkets

2+| *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*

| *Marke*
a| * Die Eigenschaft *Marke* erstellen: +
Bereich: *Artikel* +
Eigenschaftstyp: *Kurztext*

2+| *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen*

| *Marke*
a| * Tab *Texte* öffnen.
* Die Eigenschaft *Marke* hinzufügen.
* Den Markennamen eingeben.

2+| *Daten » Kataloge » Katalog öffnen*

a| * Aus Dropdown-Liste *Marke* die Marke wählen.
a| * Aus Dropdown-Liste *Quelle* die Option *Eigenschaft » Marke* wählen.
* In das Feld *Wert* den Markennamen eingeben. +
*_Hinweis:_* Auf dem Verkaufskanal wird das Produkt unter dem Markennamen des Verkaufskanals veröffentlicht.
|====

[#40]
== Kataloge verwalten

Kataloge erstellst, bearbeitest und löschst du im Menü *Daten » Kataloge*.

[NOTE]
.Katalog-Template nicht gefunden?
====
Die Katalog-Templates bestimmter Verkaufskanäle werden erst in das Menü *Daten » Kataloge* geladen, wenn du das Plugin dieses Verkaufskanals bereitstellst.
====

[#50]
=== Katalog erstellen

Gehe wie unten beschrieben vor, um einen Katalog zu erstellen.

[.instruction]
Katalog erstellen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird angezeigt.
. Klicke auf *Katalog erstellen* (icon:plus-square[role="green"]).
. Gib einen Namen für den Katalog ein.
. Wähle ein Katalog-Template aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Katalog wird erstellt. +
→ Der Katalog wird zur weiteren Bearbeitung geöffnet.

Die Umschaltfläche am rechten Rand in der Übersicht der Kataloge ermöglicht es dir, einen Katalog zu aktivieren oder zu deaktivieren. Den Namen eines Katalogs kannst du in den Einstellungen (icon:cog[role="black"]) ändern.

[#60]
=== Datenquellen zuordnen

Nachdem du einen Katalog erstellt hast, wird dieser Katalog geöffnet. Links werden die Daten des Verkaufskanals angezeigt. Pflichtfelder sind mit Sternchen gekennzeichnet. Rechts davon siehst du für jedes Datenfeld des Verkaufskanals eine Dropdown-Liste. Über diese Dropdown-Listen ordnest du den Datenfeldern des Verkaufskanals eine oder mehrere plentymarkets Datenquellen zu.

Je nachdem, um welche Produktdaten es sich handelt, wird als Datenquelle entweder ein Datenfeld oder ein Wert zugeordnet. Im oberen Bereich der Liste ordnest du Datenfelder zu. Du legst zum Beispiel fest, welches Datenfeld in plentymarkets das Gewicht von Varianten enthält, das an den Verkaufskanal übertragen werden soll. Im unteren Bereich ordnest du Werte zu. Du weist zum Beispiel der Verkaufskanalkategorie "Tierfutter" deine plentymarkets Kategorie "Tiernahrung" zu.

Gehe wie unten beschrieben vor, um den Datenfeldern des Verkaufskanals eine plentymarkets Datenquelle zuzuordnen.

[NOTE]
.Keine Freitextfelder und Merkmale
====
Freitextfelder und Merkmale wurden von den Eigenschaften abgelöst. Über Kataloge kannst du deshalb keine Freitextfelder und Merkmale mehr an Verkaufskanäle übermitteln. Nutze stattdessen die Eigenschaften.
====

[.instruction]
Datenquellen zuordnen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird angezeigt.
. Klicke auf den Katalog. +
→ Der Katalog wird geöffnet. +
→ Links werden die Datenfelder des Verkaufskanals angezeigt. +
*_Tipp:_* Pflichtfelder sind mit Sternchen gekennzeichnet. +
→ In der Mitte werden Dropdown-Listen mit plentymarkets Datenquellen angezeigt. +
. Wähle für die Datenfelder des Verkaufskanals eine plentymarkets Quelle aus der Dropdown-Liste. +
*_Hinweis:_* Informationen zu den Zieldatenfeldern erhältst du in der Dokumentation des Verkaufskanals. <<tabelle-katalog-felder>> enthält Informationen zu den plentymarkets Datenquellen und dazu, wie du diese Datenquellen zuordnest. +
. Um einem Datenfeld eine weitere plentymarkets Quelle zuzuordnen, klicke ganz rechts auf *Quelle hinzufügen*. Eine hinzugefügte Quelle kann mit Klick auf *Quelle entfernen* auch wieder gelöscht werden. +
→ Eine neue Zeile wird eingeblendet. +
*_Hinweis:_* Die gewählten Datenfelder werden in der Reihenfolge der Zuordnung geprüft. Enthält das erste Datenfeld keinen Wert, wird das zweite Datenfeld übertragen usw. Wenn du einem Datenfeld mehr als eine Datenquelle zuordnest, wird nur ein Wert übertragen. Es gibt allerdings die Möglichkeit, <<daten/daten-exportieren/kataloge-verwalten#70, Datenquellen zu kombinieren>>.
. Nimm alle gewünschten Zuordnungen vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Zuordnungen werden gespeichert.

[[tabelle-katalog-felder]]
.Verfügbare plentymarkets Datenquellen
[cols="1,1,2"]
|====
|Typ |Verfügbare Quellen |Erläuterung

|Variante
a| * *Varianten-ID*
* *Ist Hauptvariante* +
* *ID der Hauptvariante* +
* *Position* +
* *Aktiv* +
* *Grundpreisanzeige* +
* *Variantennr.* +
* *Modell* +
* *Externe Varianten-ID* +
* *EK netto* +
* *Kommissionierung* +
* *WB-Beschränkung* +
* *Webshop: sichtbar wenn Netto-WB positiv* +
* *Webshop: unsichtbar wenn kein Netto-WB* +
* *Verfügbar wenn Netto-WB positiv* +
* *Nicht verfügbar wenn kein Netto-WB* +
* *Max. Bestellmenge* +
* *Min. Bestellmenge* +
* *Intervallbestellmenge* +
* *Verfügbar bis* +
* *Erscheinungsdatum* +
* *Variantenname* +
* *Gewicht brutto g* +
* *Gewicht netto g* +
* *Breite mm* +
* *Länge mm* +
* *Höhe mm* +
* *Portoaufschlag 1* +
* *Portoaufschlag 2* +
* *VPE* +
* *Anzahl der Packstücke* +
* *Transportkosten netto* +
* *Lagerkosten netto* +
* *Zoll* +
* *Betriebskosten* +
* *Unsichtbar: in Artikelauflistung* +
* *Standard-Versandkosten* +
* *Mehrwertsteuersatz* +
* *Verfügbarkeit* +
* *Inhalt Einheit* +
* *Inhalt Menge*
|Der für das gewählte Datenfeld an der Variante gespeicherte Wert wird übermittelt.

|Attribut
a| * Im System gespeicherte Attributwerte
|Der interne Attributname wird im Data Picker verwendet.

|Barcode
a| * Im System gespeicherte Barcodes
|Der für diesen Barcode an der Variante gespeicherte Code wird übermittelt.

|Verkaufspreis
a| * Im System gespeicherte Verkaufspreise
|Der für diesen Verkaufspreis an der Variante gespeicherte Preis wird übermittelt.

|Eigenschaft
a| * Im System gespeicherte Eigenschaften
|Nach Auswahl der Quelle wird eine Dropdown-Liste für die Auswahl der Sprache eingeblendet.

|SKU
a| * *SKU* +
* *Parent-SKU*
|Der für das gewählte Datenfeld an der Variante gespeicherte Wert wird übermittelt.

|Artikel
a| * *Artikel-ID* +
* *Hersteller-ID* +
* *Herstellername* +
* *Externer Herstellername* +
* *Herstellerland-ID* +
* *Herstellerlandname*
|

|Bestand
a| * *Virtuelles Gesamtlager* +
* Im System gespeicherte Lager
|Der Lagerbestand des gewählten Lagers wird an den Verkaufskanal übermittelt.

|Artikeltext
a| * *Name 1* +
* *Name 2* +
* *Name 3* +
* *Vorschautext* +
* *Metabeschreibung* +
* *Artikeltext* +
* *Technische Daten* +
* *URL-Pfad*
|Nach Auswahl der Quelle wird eine Dropdown-Liste für die Auswahl der Sprache eingeblendet.

|Standardkategorie
a| * *Kategorie-ID* +
* *Kategoriename* +
* *Kategoriebeschreibung* +
* *URL-Name* +
* *Meta-Titel* +
* *Meta-Beschreibung* +
* *Meta-Keywords*
|

|Bild
a| * *Alle verfügbaren Bilder*
|

|ASIN
a| * *Alle* +
* *Amazon Germany* +
* *Amazon Espania* +
* *Amazon France* +
* *Amazon United Kingdom* +
* *Amazon Italy* +
* *Amazon United States*
|

|Hersteller
a| * Im System gespeicherte Hersteller
|Über die Dropdown-Listen für Ziel und Quelle werden die Hersteller des Verkaufskanals einzeln den Herstellern in plentymarkets zugeordnet. Links auf *Hersteller hinzufügen* (icon:plus-square[role="green"]) klicken, um weitere Zielhersteller zuzuordnen. +
*_Hinweis:_* Auf dem Verkaufskanal wird der Herstellername des Verkaufskanals veröffentlicht.

|Kategorie
a| * Im System gespeicherte Kategorien
|Über die Dropdown-Listen für Ziel und Quelle werden die Kategorien des Verkaufskanals einzeln den Kategorien in plentymarkets zugeordnet. Links auf *Kategorien hinzufügen* (icon:plus-square[role="green"]) klicken, um weitere Zielkategorien zuzuordnen. +
*_Hinweis:_* Auf dem Verkaufskanal wird der Kategoriename des Verkaufskanals veröffentlicht.
|====

[NOTE]
.Nur obligatorische Felder anzeigen
====
Standardmäßig werden sowohl Pflichtfelder (mit einem * gekennzeichnet) als auch nicht obligatorische Felder eines Katalogs angezeigt. Um nur die Pflichfelder angezeigt zu bekommen, aktiviere die Umschaltfläche oben in der Ansicht des Katalogs.
====

[#70]
=== Datenquellen kombinieren

Für den Export eines Datenfeldes können mithilfe des Eigenen Wertes beliebig viele Quellen miteinander kombiniert werden. Lege dazu *Zusätzliche Quellen* an und wähle ein Trennzeichen für jede Kombination.

[.instruction]
Datenquellen kombinieren:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Klicke auf einen Katalog. +
→ Der Katalog wird geöffnet.
. Wähle in der Zeile des Datenfeldes, das du exportieren möchtest, eine plentymarkets Quelle aus der Dropdown-Liste.
. Klicke unterhalb der Quelle, die du kombinieren möchtest, auf *Zusätzliche Quelle* (icon:plus-square[role="green"]). +
→ Eine weitere Quelle wird hinzugefügt.
. Wähle *Eigener Wert* aus der linken Dropdown-Liste.
. Gib im Feld *Wert* ein beliebiges Trennzeichen ein, das zwischen den Quellen stehen soll.
. Klicke unterhalb des Eigenen Wertes auf *Zusätzliche Quelle* (icon:plus-square[role="green"]). +
→ Eine weitere Quelle wird hinzugefügt.
. Wähle eine plentymarkets Quelle aus der Dropdown-Liste, die du mit der ersten Quelle kombinieren möchtest.
. Wenn gewünscht, wähle weitere zusätzliche Quellen und Trennzeichen über den Eigenen Wert. Zwischen zwei Quellen muss jeweils ein Trennzeichen stehen.
. Klicke auf *Speichern*. +
→ Die Quellen werden miteinander kombiniert und mit dem jeweils gewählten Trennzeichen ausgegeben. +
*_Hinweis_*: Legst du für ein Datenfeld mehrere Kombinationen von Quellen an, so wird nur die erste Kombination übertragen. Voraussetzung ist jedoch, dass alle dort gewählten Werte existieren. Ist beispielsweise der erste Wert leer oder nicht vorhanden, wird die Kombination ignoriert und die nächste Kombination von Datenquellen wird verwendet.

[#80]
=== Katalog kopieren

Du kannst einen Katalog kopieren und so bereits gut konfigurierte Kataloge nutzen, um schnell einen neuen Katalog anzulegen. Auch bei einem Wechsel des Formats werden bereits zugeordnete Datenfelder übernommen.

[.instruction]
Katalog kopieren:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Wähle den Katalog, den du kopieren möchtest.
. Klicke rechts auf das Dreipunkt-Menü.
. Klicke auf *Kopieren*. +
icon:map-signs[] *_Oder_*: Klicke oben auf *Kopieren* (icon:clone[role="yellow"]). +
→ Ein Fenster wird geöffnet.
. Wenn gewünscht, passe den automatisch vergebenen Namen für die Kopie an.
. Optional: Wähle ein anderes Format aus der Dropdown-Liste. Bereits zugeordnete Datenfelder werden dabei übernommen.
. Klicke auf *Kopieren*. +
→ Der Katalog wird kopiert und in der Katalog-Übersicht angezeigt. +

[#85]
=== Mehrere Kataloge kopieren

Du kannst auch mehrere Kataloge gleichzeitig zu kopieren. Allerdings ist es in diesem Fall nicht möglich, eine Formatänderung an den Katalogen vorzunehmen.

[.instruction]
Mehrere Kataloge kopieren:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Wähle die Kataloge, die du kopieren möchtest.
. Klicke auf *Kopieren* (icon:clone[role="yellow"]). +
→ Alle gewählten Kataloge werden kopiert und in der Katalog-Übersicht angezeigt. +
. Optional: Möchtest du die automatisch vergebenen Namen für die kopierten Kataloge ändern, öffne die Kataloge einzeln und passe den Namen in den Einstellungen (icon:cog[]) an.

[#90]
=== Katalog löschen

Gehe wie unten beschrieben vor, um einen Katalog zu löschen.

[.instruction]
Katalog löschen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Wähle den Katalog, den du löschen möchtest.
. Klicke rechts auf das Dreipunkt-Menü.
. Klicke auf *Löschen*. +
→ Eine Sicherheitsabfrage wird eingeblendet.
. Bestätige den Löschvorgang. +
→ Der Katalog wird gelöscht. +
icon:map-signs[] *_Oder_*: Öffne einen Katalog und klicke oben rechts auf *Löschen* (icon:minus-square[role="red"]), um den Katalog zu löschen.

[#95]
=== Mehrere Kataloge löschen

Gehe wie unten beschrieben vor, um mehrere Kataloge gleichzeitig zu löschen.

[.instruction]
Mehrere Kataloge löschen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Wähle die Kataloge, die du löschen möchtest.
. Klicke rechts oben auf *Löschen* (icon:minus-square[role="red"]). +
→ Eine Sicherheitsabfrage wird eingeblendet.
. Bestätige den Löschvorgang. +
→ Die Kataloge werden gelöscht.

[#100]
== Katalogdaten an Verkaufskanal übertragen

Die Kataloge im Menü *Daten » Kataloge* dienen dazu, den Datenfeldern eines Verkaufskanals die korrekten plentymarkets Datenquellen zuzuordnen. Das Übertragen der Variantendaten an den Verkaufskanal aktivierst du in den Einstellungen des Verkaufskanals.
