= Kataloge verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Katalog, Kataloge, Katalog-Templates, Marktplatz, Marktplätze, Märkte, Verkaufskanal, Templates, Datenquellen, Zieldaten
:description: Im Menü *Daten » Kataloge* konfigurierst du den Export von Variantendaten an Marktplätze.
:position: 50
:url: daten/daten-exportieren/kataloge-verwalten
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

[IMPORTANT]
.Die Kataloge sind neu!
====
Kataloge sind ein neues Feature für den Export von Variantendaten an Marktplätze und andere Verkaufskanäle und befinden sich noch in der Pilotphase. Aktuell kannst du Kataloge nutzen, um Daten an den Marktplatz REWE zu übertragen. plentymarkets arbeitet mit Hochdruck daran, weitere Marktplätze über das neue Katalog-Feature anzubinden.
====

Kataloge dienen dazu, Variantendaten für den Export an einen Verkaufskanal vorzubereiten. Auf dieser Handbuchseite erfährst du, wie du Kataloge erstellst und verwaltest.

[NOTE]
.Sichtbarkeit des Menüs *Daten » Kataloge*
====
Das Menü *Daten » Kataloge* ist erst sichtbar, wenn du ein Plugin bereitstellst, das ein Katalog-Template verfügbar macht.
====

== Was ist ein Katalog?

Jeder Verkaufskanal benötigt unterschiedliche Produktdaten. Häufig müssen auch für verschiedene Produktkategorien (Tierfutter, Haushalt, Lebensmittel), unterschiedliche Produktdaten an denselben Verkaufskanal übermittelt werden.

Kataloge ermöglichen es dir, die Informationen zu deinem Produktsortiment ganz auf die Anforderungen und die Zielgruppe eines Verkaufskanals zuzuschneiden. Denn in Katalogen ordnest du den einzelnen Datenfeldern eines Verkaufskanals eine passende plentymarkets Datenquelle zu. Beim Übermitteln deiner Variantendaten an den Verkaufskanal werden dann die Datenfelder des Verkaufskanal mit den richtigen Daten aus plentymarkets befüllt.

Kataloge bieten die folgenden Vorteile:

* Der Verkaufskanal gibt die Datenstruktur vor. Du weißt also genau, welche Variantendaten nötig sind, um deine Produkte über den Verkaufskanal anzubieten.
* Du bestimmst pro Verkaufskanal oder sogar pro Template, welche Variantendaten auf dem Verkaufskanal veröffentlicht werden. Über Eigenschaften kannst du zum Beispiel unterschiedliche Namen und Beschreibungen an die verschiedenen Marktplätze übertragen.

[TIP]
.Datenexport? FormatDesigner
====
Kataloge dienen dazu, Daten an Verkaufskanäle zu übertragen. Katalogdaten können nicht in eine Datei oder in ein anderes auslesbares Format exportiert werden. Verwende den <<daten/daten-exportieren/FormatDesigner#, Formatdesigner>>, um Daten zu exportieren.
====

== Was ist ein Katalog-Template?

Ein Katalog-Template stellt ein Gerüst der Daten bereit, die der Verkaufskanal entgegennehmen kann. Über Katalog-Templates gibt der Verkaufskanal also vor, welche Daten übertragen werden können.

Ein Verkaufskanal kann mehrere Katalog-Templates anbieten, zum Beispiel für verschiedene Produktkategorien (Tiernahrung, Lebensmittel, Non-Food etc.) und/oder für verschiedene Sprachen. Die Katalog-Templates werden über das Plugin des Verkaufskanals in das plentymarkets Backend geladen. Informationen dazu, welche Katalog-Templates für einen Verkaufskanal verfügbar sind, findest du in der Dokumentation des Plugins.

[NOTE]
.Keine Katalog-Templates ohne Plugin
====
Die Katalog-Templates eines Verkaufskanals werden in das Menü *Daten » Kataloge* geladen, wenn du das Plugin des Verkaufskanals bereitstellst.
====

== Variantendaten mit Eigenschaften pflegen

Mit <<artikel/artikel-verwalten#3000, Eigenschaften des Bereichs Artikel>> speicherst du Daten an Varianten, für die es standardmäßig keine Datenfelder im plentymarkets Backend gibt.

==== Beispiel 1: Durchmesserangaben

*Anwendungsfall:* +
An den Verkaufskanal können die Variantendaten *Durchmesser* und *Durchmesser Einheit* übergeben werden. Durchmesserangaben können standardmäßig nicht im plentymarkets Backend gespeichert werden.

*Vorgehensweise:* +
Um Durchmesserdaten trotzdem an den Verkaufskanal zu übergeben, empfehlen wir die in <<tabelle-durchmesser>> beschriebenen Einstellungen.

[[tabelle-durchmesser]]
.Beispiel 1: Durchmesserangaben
[cols="1,3"]
|====
|Datenfeld Verkaufskanal |Eigenschaften in plentymarkets

2+| *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*

|*Durchmesser Einheit*
a|* Eine Eigenschaft *Durchmesser Einheit* erstellen: +
Bereich: *Artikel* +
Typ: *Auswahl*
* Werte speichern, zum Beispiel *cm* und *mm*

|*Durchmesser*
a|* Eine Eigenschaft *Durchmesser* erstellen: +
Bereich: *Artikel* +
Typ: *Kommazahl*

2+|*Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen*

|*Durchmesser Einheit*
a|* Das Tab *Eigenschaften* öffnen.
* Die Eigenschaft *Durchmesser Einheit* hinzufügen.
* Die Einheit aus der Dropdown-Liste wählen.

|*Durchmesser*
a|* Das Tab *Eigenschaften* öffnen.
* Die Eigenschaft *Durchmesser* hinzufügen.
* Den Durchmesser in der für die Eigenschaft *Durchmesser Einheit* gewählten Einheit eingeben.

2+|*Daten » Kataloge » Katalog öffnen*

|*Durchmesser Einheit*
a|* Aus der Dropdown-Liste *Quelle* die Option *Eigenschaft » Durchmesser Einheit* wählen.

|*Durchmesser*
a|* Aus der Dropdown-Liste *Quelle* die Option *Eigenschaft » Durchmesser* wählen.
|====


==== Beispiel 2: Markennamen

*Anwendungsfall:* +
An den Verkaufskanal kann die Marke von Produkten übergeben werden. Standardmäßig können Hersteller, aber keine Markennamen im plentymarkets Backend gespeichert werden.

*Vorgehensweise:* +
Wenn die Hersteller in deinem System nicht den Markennamen der Produkte widerspiegeln, pflegst du die Marken als Eigenschaften. Wir empfehlen die in <<tabelle-marken>> beschriebenen Einstellungen, um Marken als Eigenschaften an den Verkaufskanal zu übergeben.

[[tabelle-marken]]
.Beispiel 2: Markenangaben
[cols="1,3"]
|====
|Datenfeld Verkaufskanal |Eigenschaften in plentymarkets

2+| *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*

|*Marke*
a|* Die Eigenschaft *Marke* erstellen: +
Bereich: *Artikel* +
Typ: *Kurztext*

2+|*Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen*

|*Marke*
a|* Tab *Texte* öffnen.
* Die Eigenschaft *Marke* hinzufügen.
* Den Markennamen eingeben.

2+|*Daten » Kataloge » Katalog öffnen*

a|* Aus Dropdown-Liste *Marke* die Marke wählen.
a|* Aus Dropdown-Liste *Quelle* die Option *Eigenschaft » Marke* wählen.
* In das Feld *Value* den Markennamen eingeben. +
*_Hinweis:_* Auf dem Verkaufskanal wird das Produkt unter dem Markennamen des Verkaufskanals veröffentlicht.
|====


== Kataloge verwalten

Nachdem du ein Plugin bereitgestellt hast, das Katalog-Templates verfügbar macht, wird im plentymarkets Backend das Menü *Daten » Kataloge* sichtbar. In diesem Menü erstellst, bearbeitest und löschst du Kataloge.

=== Katalog erstellen

Gehe wie unten beschrieben vor, um einen Katalog zu erstellen.

[.instruction]
Katalog erstellen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalogübersicht wird angezeigt.
. Klicke auf *Katalog erstellen*.
. Gib einen Namen für den Katalog ein.
. Wähle ein Katalog-Template aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Katalog wird erstellt. +
→ Der Katalog wird zur weiteren Bearbeitung geöffnet.

=== Datenquellen zuordnen

Nachdem du einen Katalog erstellt hast, wird dieser Katalog geöffnet. Links werden die Daten des Verkaufskanals angezeigt. Pflichtfelder sind mit Sternchen gekennzeichnet. Rechts davon siehst du für jedes Datenfeld des Verkaufskanals eine Dropdown-Liste. Über diese Dropdown-Listen ordnest du den Datenfeldern des Verkaufskanals eine oder mehrere plentymarkets Datenquellen zu.

Je nachdem, um welche Produktdaten es sich handelt, wird als Datenquelle entweder ein Datenfeld oder ein Wert zugeordnet. Im oberen Bereich der Liste ordnest du Datenfelder zu. Du legst zum Beispiel fest, welches Datenfeld in plentymarkets das Gewicht von Varianten enthält, das an den Verkaufskanal übertragen werden soll. Im unteren Bereich ordnest du Werte zu. Du weist zum Beispiel der Verkaufskanalkategorie "Tierfutter" deine plentymarkets Kategorie "Tiernahrung" zu.

Gehe wie unten beschrieben vor, um den Datenfeldern des Verkaufskanals eine plentymarkets Datenquelle zuzuordnen.

[.instruction]
Datenquellen zuordnen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalogübersicht wird angezeigt.
. Klicke auf den Katalog. +
→ Der Katalog wird geöffnet. +
→ Links werden die Datenfelder des Verkaufskanals angezeigt. +
*_Tipp:_* Pflichtfelder sind mit Sternchen gekennzeichnet. +
→ In der Mitte werden Dropdown-Listen mit plentymarkets Datenquellen angezeigt. +
. Wähle für die Datenfelder des Verkaufskanals eine plentymarkets Quelle aus der Dropdown-Liste. +
*_Hinweis:_* Informationen zu den Zieldatenfeldern erhältst du im Plugin des Verkaufskanals. <<tabelle-katalog-felder>> enthält Informationen zu den plentymarkets Datenquellen und dazu, wie du diese Datenquellen zuordnest. +
. Um einem Datenfeld eine weitere plentymarkets Quelle zuzuordnen, klickst du ganz rechts auf *Quelle hinzufügen*. +
→ Eine neue Zeile wird eingeblendet. +
*_Hinweis:_* Auch wenn du einem Datenfeld mehr als eine Datenquelle zuordnest, wird nur ein Wert übertragen. Die Daten werden in der Reihenfolge der Zuordnung geprüft. Wenn also das erste Datenfeld keinen Wert liefert, wird das zweite Datenfeld übertragen usw.
. Nimm alle gewünschten Zuordnungen vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Zuordnungen werden gespeichert.

[[tabelle-katalog-felder]]
.Verfügbare plentymarkets Datenquellen
[cols="1,1,2"]
|====
|Typ |Verfügbare Quellen |Erläuterung

|Texte
a|* *Name 1* +
* *Name 2* +
* *Name 3* +
* *Kurzbeschreibung* +
* *Metabeschreibung* +
* *Beschreibung* +
* *Technische Daten* +
* *URL-Pfad*
|Nach Auswahl der Quelle wird eine Dropdown-Liste für die Auswahl der Sprache eingeblendet.

|Verkaufspreis
a|* Im System gespeicherte Verkaufspreise
|Der für diesen Verkaufspreis an der Variante gespeicherte Preis wird übermittelt.

|Eigenschaft
a|* Im System gespeicherte Eigenschaften
|Nach Auswahl der Quelle wird eine Dropdown-Liste für die Auswahl der Sprache eingeblendet.

|Bild
|Keine weitere Auswahl
|

|Barcode
a|* Im System gespeicherte Barcodes
|Der Code für diesen Barcode an der Variante gespeicherte Code wird übermittelt.

|SKU
|Keine weitere Auswahl
|

|Bestand
a|* *Virtuelles Gesamtlager* +
* Im System gespeicherte Lager
|Der Lagerbestand des gewählten Lagers wird an den Verkaufskanal übermittelt.

|Standardkategorie
a|* *ID* +
* *Name* +
* *Beschreibung* +
* *URL-Name* +
* *Meta-Titel* +
* *Meta-Beschreibung* +
* *Meta-Keywords*
|

|Eigenschaft
a|* Im System gespeicherte Eigenschaften
|

|Variante
a|* *Varianten-ID*
* *Ist Hauptvariante* +
* *ID der Hauptvariante* +
* *Position* +
* *Aktiv* +
* *Grundpreisanzeige* +
* *Variantennr.* +
* *Modell* +
* *Externe Varianten-ID* +
* *EK netto* +
* *Kommissionierung* +
* *WB-Beschränkung* +
* *Webshop: sichtbar wenn Netto-WB positiv* +
* *Webshop: unsichtbar wenn kein Netto-WB* +
* *Verfügbar wenn Netto-WB positiv* +
* *Nicht verfügbar wenn kein Netto-WB* +
* *Max. Bestellmenge* +
* *Min.-Bestellmenge* +
* *Intervallbestellmenge* +
* *Verfügbar bis* +
* *Erscheinungsdatum* +
* *Variantenname* +
* *Gewicht brutto g* +
* *Gewicht netto g* +
* *Breite mm* +
* *Länge mm* +
* *Höhe mm* +
* *Portoaufschlag 1* +
* *Portoaufschlag 2* +
* *VPE* +
* *Anzahl der Packstücke* +
* *Transportkosten netto* +
* *Lagerkosten netto* +
* *Zoll* +
* *Betriebskosten* +
* *Unsichtbar: in Artikelauflistung* +
* *Standard-Versandkosten*
|Der für das gewählte Datenfeld an der Variante gespeicherte Wert wird übermittelt.

|Hersteller
a|* Im System gespeicherte Hersteller
|Über Dropdown-Listen für Ziel und Quelle werden die Hersteller des Verkaufskanals einzeln den Herstellern in plentymarkets zugeordnet. Links auf *Hersteller hinzufügen* klicken, um weitere Zielhersteller zuzuordnen. +
*_Hinweis:_* Auf dem Verkaufskanal wird der Herstellername des Verkaufskanals veröffentlicht.

|Attribut
a|* Im System gespeicherte Attributwerte
|

|Kategorie
a|* Im System gespeicherte Kategorien
|Über Dropdown-Listen für Ziel und Quelle werden die Kategorien des Verkaufskanals einzeln den Kategorien in plentymarkets zugeordnet. Links auf *Kategorien hinzufügen* klicken, um weitere Zielkategorien zuzuordnen. +
*_Hinweis:_* Auf dem Verkaufskanal wird der Kategoriename des Verkaufskanals veröffentlicht.
|====


=== Katalog löschen

Gehe wie unten beschrieben vor, um einen Katalog zu löschen.

[.instruction]
Katalog löschen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalogübersicht wird angezeigt.
. Klicke auf den Katalog. +
→ Der Katalog wird geöffnet. +
. Klicke rechts oben auf *Löschen* (icon:minus-square[role="red"]). +
→ Eine Sicherheitsabfrage wird eingeblendet.
. Bestätige den Löschvorgang. +
→ Der Katalog wird gelöscht.

== Katalogdaten an Verkaufskanal übertragen

Die Kataloge im Menü *Daten » Kataloge* dienen dazu, den Datenfeldern eines Verkaufskanals die korrekten plentymarkets Datenquellen zuzuordnen. Das Übertragen der Variantendaten an den Verkaufskanal aktivierst du in den Einstellungen des Plugins des Verkaufskanals.
