= Kataloge verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Katalog, Kataloge, Katalog erstellen, Katalog verwalten, Katalog-Templates, Katalog Templates, Marktplatz, Marktplätze, Märkte, Verkaufskanal, Templates, Datenquellen, Datenquellen kombinieren, Zieldaten, Katalog kopieren, Katalog löschen, Daten übertragen, Marktplatz-Format, Standard-Format, Marktplatzformat, Standardformat, Export, Datenexport, Daten exportieren, Katalog wiederherstellen, Kataloge exportieren, Datenfeld, Datenfelder verknüpfen, Datenfelder zuordnen, Zuordnung, Katalog herunterladen, Version wiederherstellen, Datenfelder löschen, Datenspalten
:description: Im Menü *Daten » Kataloge* konfigurierst du den Export von Variantendaten an Marktplätze.
:position: 50
:url: daten/daten-exportieren/kataloge-verwalten
:id: FHQHFWO
:author: team-elasticsync

Kataloge dienen dazu, Daten für den Export im Vorhinein ideal vorzubereiten. Es wird dabei zwischen Katalogen mit Marktplatz-Formaten und Katalogen mit Standardformaten unterschieden.

Du möchtest Variantendaten für den Export an einen Verkaufskanal vorbereiten?
Verwende Kataloge <<daten/daten-exportieren/kataloge-verwalten#40, mit Marktplatz-Formaten>>, um den Export von Variantendaten an Marktplätze und andere Verkaufskanäle durchzuführen. Aktuell kannst du Kataloge nutzen, um Daten an die Marktplätze REWE, Etsy, Metro, OTTO Market und Amazon zu übertragen.

Du möchtest spezifische Daten, wie z.B. Auftrags- oder Artikeldaten aus deinem plentymarkets System exportieren? Verwende Kataloge <<daten/daten-exportieren/kataloge-verwalten#110, mit Standardformaten>>, um den Export dieser Daten durchzuführen. +
*_Hinweis_*: Die Standardformate werden nach und nach in den Katalog überführt. Zurzeit gibt es lediglich ein Demo-Format.

Auf dieser Handbuchseite erfährst du, wie du Kataloge erstellst und verwaltest. Zunächst wird näher auf Kataloge mit Marktplatz-Formaten eingegangen.


[discrete]
=== Benutzerrechte für Backend-Benutzer:innen vergeben

Benutzer:innen vom Typ *Backend* sehen nur bestimmte Bereiche und Menüs im plentymarkets Backend. Somit können sie nur eingeschränkt im System arbeiten. Sollen Mitarbeiter:innen mit dem Zugang *Backend* Kataloge sehen können, muss eine Person mit *Admin*-Zugang das im folgenden beschriebene Recht für Benutzer:innen mit dem Zugang *Backend* vergeben.

[.instruction]
Benutzerrechte für Backend-Benutzer:innen vergeben:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne das zu bearbeitende Konto.
. Aktiviere im Bereich *Berechtigungen* die Option *Daten > Datenaustausch > Export > Katalog > Anzeigen*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#10]
== Was ist ein Katalog?

Jeder Verkaufskanal benötigt unterschiedliche Produktdaten. Häufig müssen auch für verschiedene Produktkategorien (Tierfutter, Haushalt, Lebensmittel) unterschiedliche Produktdaten an denselben Verkaufskanal übermittelt werden.

Kataloge mit Marktplatz-Format ermöglichen es dir, die Informationen zu deinem Produktsortiment ganz auf die Anforderungen und die Zielgruppe eines Verkaufskanals zuzuschneiden. Denn in Katalogen mit Marktplatz-Formaten ordnest du den einzelnen Datenfeldern eines Verkaufskanals eine passende plentymarkets Datenquelle zu. Beim Übermitteln deiner Variantendaten an den Verkaufskanal werden dann die Datenfelder des Verkaufskanal mit den richtigen Daten aus plentymarkets befüllt.

Kataloge mit Marktplatz-Formaten bieten die folgenden Vorteile:

* Der Verkaufskanal gibt die Datenstruktur vor. Du weißt also genau, welche Variantendaten nötig sind, um deine Produkte über den Verkaufskanal anzubieten.
* Du bestimmst pro Verkaufskanal oder sogar pro Format, welche Variantendaten auf dem Verkaufskanal veröffentlicht werden. Über Eigenschaften kannst du zum Beispiel unterschiedliche Namen und Beschreibungen an die verschiedenen Marktplätze übertragen.

[#20]
== Was ist ein Marktplatz-Format?

Ein Marktplatz-Format stellt ein Gerüst der Daten bereit, die der Verkaufskanal entgegennehmen kann. Über Marktplatz-Formate gibt der Verkaufskanal also vor, welche Daten übertragen werden können.

Ein Verkaufskanal kann mehrere Marktplatz-Formate anbieten, zum Beispiel für verschiedene Produktkategorien (Tiernahrung, Lebensmittel, Non-Food etc.) oder für verschiedene Sprachen. Informationen dazu, welche Marktplatz-Formate für einen Verkaufskanal verfügbar sind, findest du in der Dokumentation des Verkaufskanals.

[TIP]
.Marktplatz-Format nicht gefunden?
====
Die Marktplatz-Formate bestimmter Verkaufskanäle werden erst in das Menü *Daten » Kataloge* geladen, wenn du das Plugin dieses Verkaufskanals bereitstellst.
====

[#30]
== Variantendaten mit Eigenschaften pflegen

Mit <<artikel/artikel-verwalten#3000, Eigenschaften des Bereichs Artikel>> speicherst du Daten an Varianten, für die es standardmäßig keine Datenfelder im plentymarkets Backend gibt. Im Folgenden findest du einige Beispiele dafür, wie du Eigenschaften nutzt.

==== Beispiel 1: Durchmesserangaben

*Anwendungsfall:* +
An den Verkaufskanal können die Variantendaten *Durchmesser* und *Durchmesser Einheit* übergeben werden. Durchmesserangaben können standardmäßig nicht im plentymarkets Backend gespeichert werden.

*Vorgehensweise:* +
Um Durchmesserdaten trotzdem an den Verkaufskanal zu übergeben, empfehlen wir die in <<tabelle-durchmesser>> beschriebenen Einstellungen.

[[tabelle-durchmesser]]
.Beispiel 1: Durchmesserangaben
[cols="1,3"]
|====
|Datenfeld Verkaufskanal |Eigenschaften in plentymarkets

2+| *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*

| *Durchmesser Einheit*
a| * Eine Eigenschaft *Durchmesser Einheit* erstellen: +
Bereich: *Artikel* +
Eigenschaftstyp: *Auswahl*
* Werte speichern, zum Beispiel *cm* und *mm*

| *Durchmesser*
a| * Eine Eigenschaft *Durchmesser* erstellen: +
Bereich: *Artikel* +
Eigenschaftstyp: *Kommazahl*

2+| *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen*

| *Durchmesser Einheit*
a| * Das Tab *Eigenschaften* öffnen.
* Die Eigenschaft *Durchmesser Einheit* hinzufügen.
* Die Einheit aus der Dropdown-Liste wählen.

| *Durchmesser*
a| * Das Tab *Eigenschaften* öffnen.
* Die Eigenschaft *Durchmesser* hinzufügen.
* Den Durchmesser in der für die Eigenschaft *Durchmesser Einheit* gewählten Einheit eingeben.

2+| *Daten » Kataloge » Katalog öffnen*

| *Durchmesser Einheit*
a| * Aus der Dropdown-Liste *Quelle* die Option *Eigenschaft » Durchmesser Einheit* wählen.

| *Durchmesser*
a| * Aus der Dropdown-Liste *Quelle* die Option *Eigenschaft » Durchmesser* wählen.
|====


==== Beispiel 2: Markennamen

*Anwendungsfall:* +
An den Verkaufskanal kann die Marke von Produkten übergeben werden. Standardmäßig können Hersteller:innen, aber keine Markennamen im plentymarkets Backend gespeichert werden.

*Vorgehensweise:* +
Wenn die Hersteller:innen in deinem System nicht den Markennamen der Produkte widerspiegeln, pflegst du die Marken als Eigenschaften. Wir empfehlen die in <<tabelle-marken>> beschriebenen Einstellungen, um Marken als Eigenschaften an den Verkaufskanal zu übergeben.

[[tabelle-marken]]
.Beispiel 2: Markenangaben
[cols="1,3"]
|====
|Datenfeld Verkaufskanal |Eigenschaften in plentymarkets

2+| *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*

| *Marke*
a| * Die Eigenschaft *Marke* erstellen: +
Bereich: *Artikel* +
Eigenschaftstyp: *Kurztext*

2+| *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen*

| *Marke*
a| * Tab *Texte* öffnen.
* Die Eigenschaft *Marke* hinzufügen.
* Den Markennamen eingeben.

2+| *Daten » Kataloge » Katalog öffnen*

a| * Aus Dropdown-Liste *Marke* die Marke wählen.
a| * Aus Dropdown-Liste *Quelle* die Option *Eigenschaft » Marke* wählen.
* In das Feld *Wert* den Markennamen eingeben. +
*_Hinweis:_* Auf dem Verkaufskanal wird das Produkt unter dem Markennamen des Verkaufskanals veröffentlicht.
|====

[#40]
== Kataloge mit Marktplatz-Format verwalten

Im Folgenden wird näher erläutert, wie du Kataloge mit Marktplatz-Formaten im Menü *Daten » Kataloge* erstellst und verwaltest. Lerne außerdem, wie du Datenfelder für den Export verknüpfst und zuordnest, um deine Daten wie gewünscht an einen Verkaufskanal zu übertragen.

[TIP]
.Marktplatz-Format nicht gefunden?
====
Die Marktplatz-Formate bestimmter Verkaufskanäle werden erst in das Menü *Daten » Kataloge* geladen, wenn du das Plugin dieses Verkaufskanals bereitstellst.
====

[#50]
=== Kataloge mit Marktplatz-Format erstellen

Bei einem Marktplatz-Format gibt es Datenfelder, die vom jeweiligen Marktplatz erfordert werden sowie Datenfelder, die optional sind. Gehe wie unten beschrieben vor, um einen Katalog mit einem Marktplatz-Format zu erstellen.

[#60]
==== Grundeinstellungen vornehmen

Erstelle einen Katalog und lege fest, wofür du den Katalog verwenden möchtest.

[.instruction]
Grundeinstellungen vornehmen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Klicke auf *Katalog erstellen* (icon:plus-square[role="green"]). +
→ Eine neue Ansicht wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#tabelle-grundeinstellungen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Katalog wird erstellt und das Tab *Zuordnung* wird geöffnet.

[[tabelle-grundeinstellungen]]
.Grundeinstellungen vornehmen
[cols="1,3"]
|====
|*Einstellung* |*Erläuterung*

|*Katalogname* (Pflichtfeld)
|Gib den Namen des Katalogs ein.

|*Export-Typ* (Pflichtfeld)
|Wähle den Export-Typ (z.B. Amazon) aus der Dropdown-Liste. Dabei handelt es sich um das Marktplatz-Format, das du für den Export verwenden möchtest.

|*Format-Typ* (Pflichtfeld)
|Wähle einen Format-Typ (z.B. Artikel) aus der Dropdown-Liste.

|*Format* (Pflichtfeld)
|Wähle ein Format aus der Dropdown-Liste. Dabei handelt es sich um die gewünschte Kategorie.
|====

[#70]
==== Exporteinstellungen vornehmen

Falls vorhanden, nimm die Exporteinstellungen vor. Beachte, dass diese nicht für jedes Marktzplatz-Format verfügbar sind.

[.instruction]
Exporteinstellungen vornehmen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Wähle den Katalog, für den du die Exporteinstellungen vornehmen möchtest. +
→ Der Katalog wird geöffnet.
. Klicke links auf das Tab *Einstellungen*. +
→ Die Einstellungsmöglichkeiten werden ausgeklappt.
. Klicke auf *Exporteinstellungen*. +
→ Die Exporteinstellungen werden geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#tabelle-exporteinstellungen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-exporteinstellungen]]
.Exporteinstellungen vornehmen
[cols="1,3"]
|====
|*Einstellung* |*Erläuterung*

|*Limit*
|Gib eine Zahl ein, um die maximale Anzahl an Zeilen für den Export festzulegen.

|*Bereitstellung*
|Wähle aus der Dropdown-Liste, in welcher Form du den Export bereitgestellt bekommen möchtest. +
Wenn du FTP, FTPS (coming soon) oder SFTP (coming soon) wählst, werden weitere Felder sichtbar.

|*Dateiname*
|Gib den Dateinamen ein. Es ist nicht notwendig, die Endung .csv bzw. .txt anzugeben, da das System dies automatisch tut.

|*Platzhalter Nummernkreis*
|Vergib einen Nummernkreis. Dieses Feld ist nur verfügbar, wenn du die Wildcard mit dem Platzhalter _numberRange_ nutzt. _Das Maximum des Nummernkreises ist durch die Anzahl der Stellen limitiert._

|*Server*
|Gib den Server ein. Dieses Feld ist nur sichtbar, wenn du als Bereitstellung FTP, FTPS (coming soon) oder SFTP (coming soon) gewählt hast.

|*Port*
|Gib den Port ein. Dieses Feld ist nur sichtbar, wenn du als Bereitstellung FTP, FTPS (coming soon) oder SFTP (coming soon) gewählt hast.

|*Benutzername*
|Gib den Benutzernamen ein. Dieses Feld ist nur sichtbar, wenn du als Bereitstellung FTP, FTPS (coming soon) oder SFTP (coming soon) gewählt hast.

|*Passwort*
|Gib ein Passwort ein. Dieses Feld ist nur sichtbar, wenn du als Bereitstellung FTP, FTPS (coming soon) oder SFTP (coming soon) gewählt hast.

|*Pfad*
|Gib den Pfad für den Speicherort deiner Datei ein. Dieses Feld ist nur sichtbar, wenn du als Bereitstellung FTP, FTPS (coming soon) oder SFTP (coming soon) gewählt hast.

|*Übertragung*
|Gib an, wann der Export gestartet werden soll. Wähle dazu eine Option aus der Dropdown-Liste. Bei der Option *Zeitplan* öffnet sich ein Fenster, in dem du eine Uhrzeit wählen kannst.

|*Zeitplan*
|Wähle eine Uhrzeit aus der Dropdown-Liste, zu der der Export stattfinden soll. Dieses Feld ist nur sichtbar, wenn du als Übertragung *Zeitplan* gewählt hast.
|====

[#80]
=== Datenfelder zuordnen und verknüpfen

Im Tab *Zuordnung* deines Katalogs kannst du die Datenquellen des Verkaufskanals deinen plentymarkets Datenfeldern zuordnen. Je nachdem, um welche Produktdaten es sich handelt, wird als Datenquelle entweder ein Datenfeld oder ein Wert zugeordnet. Du legst zum Beispiel fest, welches Datenfeld in plentymarkets das Gewicht von Varianten enthält, das an den Verkaufskanal übertragen werden soll. Darunter ordnest du Werte zu. Du weist zum Beispiel der Verkaufskanalkategorie "Tierfutter" deine plentymarkets Kategorie "Tiernahrung" zu.

Für den Export eines Datenfelds können beliebig viele Quellen miteinander verknüpft werden. Lege dazu weitere Quellen an und wähle ein Trennzeichen für jede Verknüpfung. Außerdem kannst du sogenannte Ausweich-Datenfelder hinzufügen. Ist ein Wert im System nicht vorhanden, kannst du hier bestimmen, welcher Wert stattdessen exportiert werden soll.

Gehe wie unten beschrieben vor, um den Datenfeldern des Verkaufskanals eine plentymarkets Datenquelle zuzuordnen.

[TIP]
====
.Genaue Zuordnung für bestimmte Datenfelder
Datenfelder wie z.B. das eines Verkaufspreises benötigen eine genauere Zuordnung, da z.B. mehrere Preise für jede Variante vorhanden sein können. Mit der Zuordnung wird ein konkreter Verkaufspreis bestimmt. Um beispielsweise mehrere Preise zu exportieren, kann das Datenfeld mehrfach hinzugefügt werden. Bei Datenfeldern, die eine genauere Zuordnung benötigen, ist unterhalb des Datenfelds eine Dropdown-Liste vorhanden. Der Standardwert ist immer vorausgewählt.
====

[NOTE]
.Keine Freitextfelder und Merkmale
====
Freitextfelder und Merkmale wurden von den Eigenschaften abgelöst. Über Kataloge kannst du deshalb keine Freitextfelder und Merkmale mehr an Verkaufskanäle übermitteln. Nutze stattdessen die Eigenschaften.
====

[.instruction]
Datenfelder zuordnen und verknüpfen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Öffne einen Katalog. +
→ Das Tab *Zuordnung* mit den Datenfeldern des Verkaufskanals wird geöffnet. +
*_Tipp_*: Pflichtfelder sind mit Sternchen gekennzeichnet.
. Klicke auf *Datenfeld hinzufügen*. +
→ Die verfügbaren plentymarkets Datenquellen werden links angezeigt.
. Klicke neben einem Datenfeld oder *Eigener Wert* auf das kleine Plus. +
→ Das Datenfeld oder das Feld für den Eigenen Wert wird in der Ansicht hinzugefügt.
. Hast du *Eigener Wert* gewählt, gib einen Wert in das Eingabefeld darunter ein.
. Um einem Datenfeld eine weitere plentymarkets Datenquelle zuzuordnen, klicke rechts auf *Datenfeld hinzufügen* (icon:link[rotate=90]). +
→ Der Bearbeitungsmodus wird geöffnet.
. Wähle beliebig viele Datenfelder oder *Eigener Wert*. Hast du *Eigener Wert* gewählt, gib einen Wert in das Eingabefeld darunter ein.
. Schließe den Bearbeitungsmodus über das X oder mit einem Klick außerhalb des Fensters.
. Klicke rechts in der Datenzeile auf *Einstellungen* (icon:cog[]), um ein Trennzeichen zu wählen. +
→ Das Fenster *Einstellungen Datenspalten* wird geöffnet.
. Wähle ein Trennzeichen aus der Dropdown-Liste oder füge ein eigenes Trennzeichen hinzu. +
. *Speichere* die Einstellungen. +
→ Die Datenfelder werden miteinander verknüpft und beim Export mit dem jeweils gewählten Trennzeichen ausgegeben. +
*_Hinweis_*: Ist in einer Verknüpfung ein Datenfeld nicht vorhanden, so werden nur die übrigen Datenfelder exportiert. +
*_Optional_*: Klicke auf *Ausweich-Datenfeld hinzufügen*, um ein Datenfeld zu wählen, das exportiert wird, falls ein anderes nicht vorhanden ist. Du kannst hier auch mehrere Datenfelder hinterlegen.
. Nimm alle gewünschten Zuordnungen vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Zuordnungen werden gespeichert.

[TIP]
.Datenfeld ersetzen
====
Möchtest du an einer bestimmten Stelle ein Datenfeld ersetzen, ohne bereits verknüpfte Datenfelder löschen und neu hinzufügen zu müssen? Dann klicke neben dem Datenfeld, das du ersetzen möchtest, auf die weiteren Aktionen (icon:ellipsis-v[]) und wähle ein neues Datenfeld.
====

[#90]
=== Datenfelder löschen

Im Tab *Zuordnung* eines Katalogs mit Marktplatz-Format kannst du einzelne oder auch mehrere Datenfelder gleichzeitig löschen. Bei Marktplatz-Formaten kannst du außerdem die gewählten Ausweich-Datenfelder wieder entfernen.

[.instruction]
Datenfelder löschen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Öffne einen Katalog mit Marktplatz-Format. +
→ Das Tab *Zuordnung* mit allen verfügbaren Datenfeldern wird geöffnet.
. Klicke rechts neben dem Datenfeld, das du löschen möchtest, auf die weiteren Aktionen (icon:ellipsis-v[]).
. Klicke auf *Datenfeld löschen* (icon:trash-o[]). +
→ Das Datenfeld wird gelöscht. +
icon:map-signs[] *_Oder_*: Klicke rechts in der Datenzeile auf *Zurücksetzen* (icon:undo[]). +
→ Alle zuvor hinzugefügten Datenfelder werden gelöscht. *_Hinweis_*: Dies funktioniert nur, wenn du gerade Datenfelder hinzugefügt und noch nicht gespeichert hast.

[#100]
=== Verfügbare plentymarkets Datenquellen

Informationen zu den Zieldatenfeldern erhältst du in der Dokumentation des Verkaufskanals. <<#tabelle-katalog-felder>> enthält Informationen zu den plentymarkets Datenquellen und dazu, wie du diese Datenquellen zuordnest.

[[tabelle-katalog-felder]]
.Verfügbare plentymarkets Datenquellen
[cols="1,1,2"]
|====
|Typ |Verfügbare Quellen |Erläuterung

|Variante
a| * *Varianten-ID*
* *Ist Hauptvariante* +
* *ID der Hauptvariante* +
* *Position* +
* *Aktiv* +
* *Grundpreisanzeige* +
* *Variantennr.* +
* *Modell* +
* *Externe Varianten-ID* +
* *EK netto* +
* *Kommissionierung* +
* *WB-Beschränkung* +
* *Webshop: sichtbar wenn Netto-WB positiv* +
* *Webshop: unsichtbar wenn kein Netto-WB* +
* *Verfügbar wenn Netto-WB positiv* +
* *Nicht verfügbar wenn kein Netto-WB* +
* *Max. Bestellmenge* +
* *Min. Bestellmenge* +
* *Intervallbestellmenge* +
* *Verfügbar bis* +
* *Erscheinungsdatum* +
* *Variantenname* +
* *Gewicht brutto g* +
* *Gewicht netto g* +
* *Breite mm* +
* *Länge mm* +
* *Höhe mm* +
* *Portoaufschlag 1* +
* *Portoaufschlag 2* +
* *VPE* +
* *Anzahl der Packstücke* +
* *Transportkosten netto* +
* *Lagerkosten netto* +
* *Zoll* +
* *Betriebskosten* +
* *Unsichtbar: in Artikelauflistung* +
* *Standard-Versandkosten* +
* *Mehrwertsteuersatz* +
* *Verfügbarkeit* +
* *Inhalt Einheit* +
* *Inhalt Menge*
|Der für das gewählte Datenfeld an der Variante gespeicherte Wert wird übermittelt.

|Attribut
a| * Im System gespeicherte Attributwerte
|Der interne Attributname wird im Data Picker verwendet.

|Barcode
a| * Im System gespeicherte Barcodes
|Der für diesen Barcode an der Variante gespeicherte Code wird übermittelt.

|Verkaufspreis
a| * Im System gespeicherte Verkaufspreise
|Der für diesen Verkaufspreis an der Variante gespeicherte Preis wird übermittelt.

|Eigenschaft
a| * Im System gespeicherte Eigenschaften
|Nach Auswahl der Quelle wird eine Dropdown-Liste für die Auswahl der Sprache eingeblendet.

|SKU
a| * *SKU* +
* *Parent-SKU*
|Der für das gewählte Datenfeld an der Variante gespeicherte Wert wird übermittelt.

|Artikel
a| * *Artikel-ID* +
* *Hersteller-ID* +
* *Herstellername* +
* *Externer Herstellername* +
* *Herstellerland-ID* +
* *Herstellerlandname*
|

|Bestand
a| * *Virtuelles Gesamtlager* +
* Im System gespeicherte Lager
|Der Lagerbestand des gewählten Lagers wird an den Verkaufskanal übermittelt.

|Artikeltext
a| * *Name 1* +
* *Name 2* +
* *Name 3* +
* *Vorschautext* +
* *Metabeschreibung* +
* *Artikeltext* +
* *Technische Daten* +
* *URL-Pfad*
|Nach Auswahl der Quelle wird eine Dropdown-Liste für die Auswahl der Sprache eingeblendet.

|Standardkategorie
a| * *Kategorie-ID* +
* *Kategoriename* +
* *Kategoriebeschreibung* +
* *URL-Name* +
* *Meta-Titel* +
* *Meta-Beschreibung* +
* *Meta-Keywords*
|

|Bild
a| * *Alle verfügbaren Bilder*
|

|ASIN
a| * *Alle* +
* *Amazon Germany* +
* *Amazon Espania* +
* *Amazon France* +
* *Amazon United Kingdom* +
* *Amazon Italy* +
* *Amazon United States*
|

|Hersteller
a| * Im System gespeicherte Hersteller:innen
|Über die Dropdown-Listen für Ziel und Quelle werden die Hersteller:innen des Verkaufskanals einzeln den Hersteller:innen in plentymarkets zugeordnet. Klicke links auf *Hersteller hinzufügen* (icon:plus-square[role="green"]), um weitere Zielhersteller:innen zuzuordnen. +
*_Hinweis:_* Auf dem Verkaufskanal wird der Hersteller:innen-Name des Verkaufskanals veröffentlicht.

|Kategorie
a| * Im System gespeicherte Kategorien
|Über die Dropdown-Listen für Ziel und Quelle werden die Kategorien des Verkaufskanals einzeln den Kategorien in plentymarkets zugeordnet. Klicke links auf *Kategorien hinzufügen* (icon:plus-square[role="green"]), um weitere Zielkategorien zuzuordnen. +
*_Hinweis:_* Auf dem Verkaufskanal wird der Kategoriename des Verkaufskanals veröffentlicht.
|====

[TIP]
.Katalogdaten an Verkaufskanal übertragen
====
Kataloge mit Marktplatz-Format im Menü *Daten » Kataloge* dienen dazu, den Datenfeldern eines Verkaufskanals die korrekten plentymarkets Datenquellen zuzuordnen. Das Übertragen der Variantendaten an den Verkaufskanal aktivierst du in den Einstellungen des Verkaufskanals.
====

[#110]
== Kataloge mit Standardformat verwalten

Mit Standardformaten kannst du Kataloge für spezifische Daten erstellen. Dazu zählen Formate wie Artikel, Aufträge etc., anhand welcher du beispielsweise Artikel- oder Auftragsdaten aus deinem plentymarkets System exportieren kannst.

[#120]
=== Kataloge mit Standardformat erstellen
Verwende Kataloge mit Standardformat, um spezifische Daten wie Artikel- oder Auftragsdaten aus deinem plentymarkets System zu exportieren. Gehe wie unten beschrieben vor, um einen Katalog mit einem Standardformat zu erstellen.

[#130]
==== Grundeinstellungen vornehmen

[.instruction]
Grundeinstellungen vornehmen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Klicke auf *Katalog erstellen* (icon:plus-square[role="green"]). +
→ Eine neue Ansicht wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#tabelle-grundeinstellungen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Katalog wird erstellt und das Tab *Einstellungen* wird geöffnet.

[[tabelle-grundeinstellungen]]
.Grundeinstellungen vornehmen
[cols="1,3"]
|====
|*Einstellung* |*Erläuterung*

|*Katalogname* (Pflichtfeld)
|Gib den Namen des Katalogs ein.

|*Export-Typ* (Pflichtfeld)
|Wähle den Export-Typ aus der Dropdown-Liste. Dabei handelt es sich um das Standardformat, das du für den Export verwenden möchtest.

|*Format-Typ* (Pflichtfeld)
|Wähle den jeweiligen Format-Typ (z.B. Artikel) aus der Dropdown-Liste. +
 *_Hinweis_*: Zurzeit ist hier nur ein Demo-Format vorhanden.

|*Format* (Pflichtfeld)
|Wähle eines der Formate aus der Dropdown-Liste.
|====

[#140]
==== Formateinstellungen vornehmen

Sobald du die Grundeinstellungen vorgenommen hast, kannst du in den Formateinstellungen neben dem Format auch die Trennzeichen festlegen. Die Formateinstellungen sind nur für Standardformate relevant.

[.instruction]
Formateinstellungen vornehmen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Wähle den Katalog, für den du die Formateinstellungen vornehmen möchtest. +
→ Der Katalog wird geöffnet.
. Klicke links auf das Tab *Einstellungen* (icon:cog[]). +
→ Die Einstellungsmöglichkeiten werden ausgeklappt.
. Klicke auf *Formateinstellungen*. +
→ Die Formateinstellungen werden geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#tabelle-formateinstellungen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-formateinstellungen]]
.Formateinstellungen vornehmen
[cols="1,3"]
|====
|*Einstellung* |*Erläuterung*

|*Format*
|Wähle das Format deiner Datei.

|*Textbegrenzer*
|Wähle einen Textbegrenzer aus der Dropdown-Liste.

|*Feldtrennzeichen*
|Wähle ein Feldtrennzeichen aus der Dropdown-Liste.

|*Dezimaltrennzeichen*
|Wähle ein Dezimaltrennzeichen aus der Dropdown-Liste.

|*Zeilenumbruch*
|Wähle die Art des Zeilenumbruchs aus der Dropdown-Liste.

|*Kopfzeile enthalten*
|Gib an, ob eine Kopfzeile in deiner Datei enthalten ist.
|====

[#150]
==== Exporteinstellungen vornehmen

Nachdem du die Grund- und Formateinstellungen vorgenommen hast, ist es jetzt an der Zeit, sich den Exporteinstellungen zu widmen. Hier legst du fest, wie dein Export bereitgestellt werden soll.

[.instruction]
Exporteinstellungen vornehmen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Klicke auf den Katalog, für den du die Exporteinstellungen vornehmen möchtest. +
→ Der Katalog wird geöffnet.
. Klicke links auf das Tab *Einstellungen* (icon:cog[]). +
→ Die Einstellungsmöglichkeiten werden ausgeklappt.
. Klicke auf *Exporteinstellungen*. +
→ Die Exporteinstellungen werden geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#tabelle-exporteinstellungen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-exporteinstellungen]]
.Exporteinstellungen vornehmen
[cols="1,3"]
|====
|*Einstellung* |*Erläuterung*

|*Limit*
|Gib eine Zahl ein, um die maximale Anzahl an Zeilen für den Export festzulegen.

|*Bereitstellung*
|Wähle aus der Dropdown-Liste, in welcher Form du den Export bereitgestellt bekommen möchtest. +
Wenn du FTP, FTPS (coming soon) oder SFTP (coming soon) wählst, werden weitere Felder sichtbar.

|*Dateiname*
|Gib den Dateinamen ein. Es ist nicht notwendig, die Endung .csv bzw. .txt anzugeben, da das System dies automatisch tut.

|*Platzhalter Nummernkreis*
|Vergib einen Nummernkreis. Dieses Feld ist nur verfügbar, wenn du die Wildcard mit dem Platzhalter _numberRange_ nutzt. _Das Maximum des Nummernkreises ist durch die Anzahl der Stellen limitiert._

|*Server*
|Gib den Server ein. Dieses Feld ist nur sichtbar, wenn du als Bereitstellung FTP, FTPS (coming soon) oder SFTP (coming soon) gewählt hast.

|*Port*
|Gib den Port ein. Dieses Feld ist nur sichtbar, wenn du als Bereitstellung FTP, FTPS (coming soon) oder SFTP (coming soon) gewählt hast.

|*Benutzername*
|Gib den Benutzernamen ein. Dieses Feld ist nur sichtbar, wenn du als Bereitstellung FTP, FTPS (coming soon) oder SFTP (coming soon) gewählt hast.

|*Passwort*
|Gib ein Passwort ein. Dieses Feld ist nur sichtbar, wenn du als Bereitstellung FTP, FTPS (coming soon) oder SFTP (coming soon) gewählt hast.

|*Pfad*
|Gib den Pfad für den Speicherort deiner Datei ein. Dieses Feld ist nur sichtbar, wenn du als Bereitstellung FTP, FTPS (coming soon) oder SFTP (coming soon) gewählt hast.

|*Übertragung*
|Gib an, wann der Export gestartet werden soll. Wähle dazu eine Option aus der Dropdown-Liste. Bei der Option *Zeitplan* öffnet sich ein Fenster, in dem du eine Uhrzeit wählen kannst.

|*Zeitplan*
|Wähle eine Uhrzeit aus der Dropdown-Liste, zu der der Export stattfinden soll. Dieses Feld ist nur sichtbar, wenn du als Übertragung *Zeitplan* gewählt hast.
|====

[#160]
=== Datenfelder verknüpfen

Auch in Katalogen mit Standardformaten kannst du mehrere Datenfelder für den Export aus deinem plentymarkets System hinzufügen und verknüpfen.

[TIP]
.Spaltenname wählen
====
Unter jedem gewählten Datenfeld befindet sich ein Eingabefeld. Gib dort den Namen ein, der als Spaltenname in der CSV-Datei angezeigt werden soll.
====

[.instruction]
Datenfelder verknüpfen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Öffne einen Katalog. +
→ Das Tab *Datenfelder* mit allen verfügbaren Datenfeldern wird geöffnet.
. Klicke links neben einem Datenfeld oder *Eigener Wert* auf das kleine Plus. +
→ Das Datenfeld oder das Feld für den Eigenen Wert wird in der Ansicht hinzugefügt.
. Hast du *Eigener Wert* gewählt, gib einen Wert in das Eingabefeld darunter ein.
. Um ein Datenfeld mit einem weiteren Datenfeld zu verknüpfen, klicke rechts auf *Datenfeld hinzufügen* (icon:link[rotate=90]). +
→ Der Bearbeitungsmodus wird geöffnet.
. Wähle beliebig viele Datenfelder oder *Eigener Wert*. Hast du *Eigener Wert* gewählt, gib einen Wert in das Eingabefeld darunter ein.
. Schließe den Bearbeitungsmodus über das X.
. Klicke rechts in der Datenzeile auf *Einstellungen* (icon:cog[]), um ein Trennzeichen zu wählen. +
→ Das Fenster *Einstellungen Datenspalten* wird geöffnet.
. Wähle ein Trennzeichen aus der Dropdown-Liste oder füge ein eigenes Trennzeichen hinzu. +
. *Speichere* die Einstellungen. +
→ Die Datenfelder werden miteinander verknüpft und beim Export mit dem jeweils gewählten Trennzeichen ausgegeben.
. Nimm alle gewünschten Verknüpfungen vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Reihenfolge der CSV-Spalten festlegen
====
Du kannst Datenzeilen beliebig verschieben und so die Reihenfolge bestimmen, in der die Datenfelder exportiert werden sollen. Klicke dafür auf das Symbol (icon:ellipsis-v[] icon:ellipsis-v[]) am linken Rand der Datenzeile und ziehe sie mit gedrückter Maustaste an den gewünschten Ort.
====

[#170]
=== Datenfelder löschen

Im Tab *Datenfelder* eines Katalogs mit Standardformat kannst du einzelne oder auch mehrere Datenfelder gleichzeitig löschen.

[.instruction]
Datenfelder löschen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Öffne einen Katalog mit Standardformat. +
→ Das Tab *Datenfelder* mit allen verfügbaren Datenfeldern wird geöffnet.
. Klicke rechts neben dem Datenfeld, das du löschen möchtest, auf die weiteren Aktionen (icon:ellipsis-v[]).
. Klicke auf *Datenfeld löschen* (icon:trash-o[]). +
→ Das Datenfeld wird gelöscht. +
icon:map-signs[] *_Oder_*: Möchtest du eine komplette Zeile löschen, klicke rechts in der Zeile auf *Datenzeile löschen* (icon:trash-o[]). +
→ Die komplette Zeile wird gelöscht. +
icon:map-signs[] *_Oder_*: Setze links einen Haken für alle mit Datenfeldern gefüllten Zeilen, die du löschen möchtest. Klicke anschließend rechts oben auf *Gewählte Datenfelder löschen* (icon:trash-o[]). +
→ Alle gewählten Datenfelder werden gelöscht.

[TIP]
====
.Katalog (de-)aktivieren und Namen ändern
Die Umschaltfläche am linken Rand in der Übersicht der Kataloge ermöglicht es dir, einen Katalog zu aktivieren oder zu deaktivieren. Den Namen eines Katalogs kannst du in den Einstellungen oben (icon:cog[role="black"]) ändern.
====

[TIP]
.Nur Pflichtfelder anzeigen
====
Standardmäßig werden sowohl Pflichtfelder (mit einem * gekennzeichnet) als auch nicht obligatorische Felder eines Katalogs angezeigt. Um nur die Pflichtfelder angezeigt zu bekommen, aktiviere die Umschaltfläche oben in den weiteren Aktionen (icon:ellipsis-v[]) des Katalogs.
====

[#180]
== Kataloge verwalten

In den folgenden Kapiteln sind Informationen zum Kopieren, Löschen und Wiederherstellen von Katalogen gegeben. Diese gelten sowohl für Marktplatz- als auch für Standardformate.

[#190]
=== Katalog kopieren

Du kannst einen Katalog kopieren und so bereits gut konfigurierte Kataloge nutzen, um schnell einen neuen Katalog anzulegen. Auch bei einem Wechsel des Formats werden bereits zugeordnete Datenfelder übernommen.
Außerdem ist es möglich, eine andere Sprache für die Kopie zu wählen.

[.instruction]
Katalog kopieren:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Klicke in der Zeile des Katalogs, den du kopieren möchtest, auf die weiteren Aktionen (icon:ellipsis-v[]) .
. Klicke auf *Kopieren* (icon:clone[]). +
icon:map-signs[] *_Oder_*: Hake den Katalog an, den du kopieren möchtest.
. Klicke oben in der Katalog-Übersicht auf *Kataloge kopieren* (icon:clone[role="yellow"]). +
→ Ein Fenster wird geöffnet.
. Wenn gewünscht, passe den automatisch vergebenen Namen für die Kopie an.
. Optional: Wähle ein anderes Format aus der Dropdown-Liste. Bereits zugeordnete Datenfelder werden dabei übernommen.
. Optional: Wähle eine andere Sprache aus der Dropdown-Liste.
. Klicke auf *Kopieren*. +
→ Der Katalog wird kopiert und in der Katalog-Übersicht angezeigt. +

[#200]
=== Mehrere Kataloge kopieren

Du kannst auch mehrere Kataloge gleichzeitig zu kopieren. Allerdings ist es in diesem Fall nicht möglich, eine Formatänderung an den Katalogen vorzunehmen oder eine andere Sprache zu wählen.

[.instruction]
Mehrere Kataloge kopieren:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Wähle die Kataloge, die du kopieren möchtest.
. Klicke auf *Kopieren* (icon:clone[role="yellow"]). +
→ Alle gewählten Kataloge werden kopiert und in der Katalog-Übersicht angezeigt. +
. Optional: Möchtest du die automatisch vergebenen Namen für die kopierten Kataloge ändern, öffne die Kataloge einzeln und passe den Namen in den Einstellungen (icon:cog[]) an.

[#210]
=== Katalog löschen

Gehe wie unten beschrieben vor, um einen Katalog zu löschen.

[.instruction]
Katalog löschen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Klicke in der Zeile des Katalogs, den du löschen möchtest, auf die weiteren Aktionen (icon:ellipsis-v[]).
. Klicke auf *Katalog löschen* (icon:trash-o[]). +
→ Eine Sicherheitsabfrage wird eingeblendet.
. Bestätige den Löschvorgang. +
→ Der Katalog wird gelöscht. +
icon:map-signs[] *_Oder_*: Öffne einen Katalog.
. Klicke oben rechts auf *Löschen* (icon:minus-square[role="red"]). +
→ Eine Sicherheitsabfrage wird eingeblendet.
. Bestätige den Löschvorgang. +
→ Der Katalog wird gelöscht.

[#220]
=== Mehrere Kataloge löschen

Gehe wie unten beschrieben vor, um mehrere Kataloge gleichzeitig zu löschen.

[.instruction]
Mehrere Kataloge löschen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Wähle die Kataloge, die du löschen möchtest.
. Klicke rechts oben auf *Löschen* (icon:minus-square[role="red"]). +
→ Eine Sicherheitsabfrage wird eingeblendet.
. Bestätige den Löschvorgang. +
→ Die Kataloge werden gelöscht.

[#230]
=== Katalog wiederherstellen

Manchmal passiert es, dass man etwas löscht und danach gerne wieder darauf zurückgreifen möchte. Bei den Katalogen ist das kein Problem. Hier erfährst du, wie ein gelöschter Katalog oder eine bestimmte Version eines Katalogs wiederhergestellt werden kann.

[#240]
==== Gelöschten Katalog wiederherstellen

In der Katalog-Übersicht ist es möglich, gelöschte Kataloge bzw. den letzten Stand eines gelöschten Katalogs wiederherzustellen.

[.instruction]
Gelöschte Kataloge wiederherstellen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Klicke auf *Gelöschten Katalog wiederherstellen* (icon:undo[role="purple"]). +
→ Ein Fenster wird geöffnet.
. Wähle einen Katalog aus der Dropdown-Liste.
. Klicke auf *Wiederherstellen*. +
→ Der Katalog wird wiederhergestellt und in der Übersicht angezeigt.

[#250]
==== Version eines Katalogs wiederherstellen

Über die weiteren Aktionen und auch in der Ansicht eines Katalogs kannst du vorherige Versionen eines Katalogs wiederherstellen.

[.instruction]
Version eines Katalogs wiederherstellen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Öffne in der Zeile des Katalogs, den du wiederherstellen möchtest, die weiteren Aktionen (icon:ellipsis-v[]).
. Klicke auf *Katalog-Version wiederherstellen* (icon:undo[]). +
icon:map-signs[] *_Oder_*: Öffne einen Katalog und klicke oben auf *Katalog-Version wiederherstellen* (icon:undo[role="orange"]). +
→ Ein Fenster wird geöffnet.
. Wähle die Version, die du wiederherstellen möchtest.
. Klicke auf *Wiederherstellen*. +
→ Die Version des Katalogs wird wiederhergestellt und in der Übersicht angezeigt.

[#260]
== Katalog exportieren

Nachdem du alle Einstellungen vorgenommen und mindestens ein Datenfeld hinzugefügt hast, kannst du einen Katalog exportieren und die Export-Datei im gewünschten Format herunterladen.

[.instruction]
Katalog exportieren:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Öffne einen Katalog.
. Klicke oben auf *Export starten* (icon:download[role="purple"]). +
icon:map-signs[] *_Oder_*: Klicke in der Zeile des Katalogs, den du exportieren möchtest, auf die weiteren Aktionen (icon:ellipsis-v[]).
. Klicke auf *Export starten*. +
→ Der Export wird gestartet.
. Sobald der Export abgeschlossen ist, bekommst du die Nachricht (icon:bell-o[]), dass die Export-Datei heruntergeladen werden kann.
. Wenn du die Export-Datei herunterladen möchtest, klicke in der Nachricht auf *Herunterladen*. +
→ Die heruntergeladene Export-Datei wird geöffnet.
