= Generating documents
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Shipping label, address label, list of delivery addresses, package number import, delivery list, barcode scanner
:description: Learn how to export the list of delivery addresses, import package numbers, set up address labels and generate delivery lists.
:position: 30

This page of the manual describes how you export the list of delivery addresses to your shipping service provider and then import the package numbers, which you receive from your shipping service provider, into your plentymarkets system. You can print shipping labels after you have registered your orders online with your shipping service provider. Furthermore, you will learn how to set up address label templates and generate delivery lists.

How you set up all other documents that are available in plentymarkets, such as invoice, order confirmation or delivery note, can be found in the <<order-processing/orders#, **Orders**>> area.

[#200]
== Exporting a list of delivery addresses

If you ship packages with a shipping service provider, then you need a list of delivery addresses. This list is an export of shipping information that you will have to hand over to your shipping service providers, so that they, in return, can provide you with valid shipping labels. This export allows to get larger quantities of packages ready for shipment quickly and easily. In the following, you will learn how to export your orders' delivery addresses into a file, which you need for your shipping service provider's software.

If you have questions about importing the file into the shipping service provider's software or about using the software itself, please contact the provider.

// p>Bereiten Sie die im Folgenden beschriebene Ereignisaktion vor.</p> <div> <ul class="accordionList openableAll"> <li> <strong class="accordionListTrigger trigger-left trigger-plus" style="color:#008EBD">Ereignisaktion einrichten</strong> <div class="accordionListContent"> <ol> <li>Öffnen Sie das Menü <strong>Einstellungen » Aufträge » Ereignisaktionen</strong>.</li> <li>Klicken Sie auf <strong>Ereignisaktion hinzufügen</strong>.<br />→ Das Fenster <strong>Neue Ereignisaktion erstellen</strong> wird geöffnet.</li> <li>Geben Sie einen Namen ein.</li> <li>Wählen Sie das <strong>Ereignis</strong> gemäß Tabelle 1.</li> <li><strong>Speichern</strong> Sie die Einstellungen.</li> <li>Nehmen Sie die Einstellungen gemäß Tabelle 1 vor.</li> <li>Setzen Sie ein Häkchen bei <strong>Aktiv</strong>.</li> <li><strong>Speichern</strong> Sie die Einstellungen.</li> </ol> </div> </li> </ul> </div> <table> <caption>Ereignisaktion zum automatischen Buchen des Warenausgangs</caption> <tr> <th>Einstellung</th> <th>Option</th> <th>Auswahl</th> </tr> <tr> <td><strong>Ereignis</strong></td> <td><strong>Auftragsänderung: Statuswechsel</strong></td> <td>Status <strong>[7] Warenausgang gebucht</strong></td> </tr> <tr> <td><strong>Filter</strong></td> <td><strong>Auftrag > Auftragstyp</strong></td> <td><strong>Auftrag</strong></td> </tr> <tr> <td><strong>Aktion</strong></td> <td><strong>Auftrag > Warenausgang buchen</strong></td> <td></td> </tr> </table
[.instruction]
Exporting a list of delivery addresses:

. Go to **Orders » Fulfilment**.
. Expand the area **List of delivery addresses**.
. Carry out the settings as desired. Pay attention to the information given in table 1.
. Click on the gear-wheel icon. +
→ You will receive a file which you should save on your computer.
. Afterwards, import the file with your shipping service provider's software.

.Settings in the **Orders » Fulfilment » Area: List of delivery addresses** menu
[cols="a,a"]
|====
|Setting |Explanation

2+|Search filter

|**Order status**
|Select the order status.

|**Owner**
|Select the owner.

|**Payment method**
|Select the payment method.

|**Shipping method**
|Select the shipping method.

|**Incoming payment**
|Select the incoming payment.

|**Data format**
|Select the data format used in your shipping service provider's software. +
If multiple shipping service providers apply to the orders, then repeat the export process for all of the relevant data formats.

|**Separator**
|Select the separator. +
Also select this separator when importing the file into your shipping service provider's software.

2+|Procedure

|**Change order status**
|Select the order status that should be assigned to the orders during export process.
|====

[TIP]
.Data format UPS WorldShip 11
====
If you generate a list of delivery addresses with the data format UPS Worldship 11, then the information contained in the **Additional address information** field will be displayed in the columns **Str2** and **Str3**. The columns can each contain 35 characters. Once the first column has been filled, the information will continue in the second column. The additional address information will only be displayed in the columns if they are empty. If the columns are not empty, then the additional address information will not be displayed.
====

[#800]
== Importing package numbers

Use the menu **Orders » Fulfilment » Tab: Import of package numbers** to easily edit large quantities of package numbers in your plentymarkets system.

The **Import of package numbers** tab is divided into the areas **CSV import** and **List import**. In the **CSV import** area, you upload a file of your shipping service provider in your plentymarkets system. In the **List import** area, you can manually enter the package numbers with the corresponding order IDs or you can import the package numbers and order IDs by using a <<order-processing/fulfilment/generating-documents#1010, **barcode scanner**>>.

[#900]
=== Importing package numbers with a CSV file

Proceed as follows to import the package numbers with a CSV file. The CSV file that you import was generated by your shipping service provider.

[.instruction]
Importing package numbers with a CSV file:

. Go to **Orders » Fulfilment**.
. Click on the **Import of package numbers** tab.
. Carry out the settings in the **CSV import** area as desired. Pay attention to the information given in table 2.
. Click on **Import**. +
→ The package number will be imported into your plentymarkets system.

.Settings in the **Orders » Fulfilment » Tab: Import of package numbers** menu
[cols="a,a"]
|====
|**Setting** |**Explanation**

|Options in the drop-down menu
a|Select an option in the drop-down menu, e.g. **Order ID**. Select the column of the CSV file that should be used to identify the packages. For example, the column that contains the **Order ID** or a different option. +
The order ID as well as the shipping package ID will be generated by your plentymarkets system. The **Customer reference** is saved in the order's **Settings** tab. +
The following options are available:
* Order ID
* Barcode order ID
* Shipping package ID
* Order and shipping package ID
* Customer reference

|**Package number**
|Select the column of the CSV file that contains the package number.

|**Field separator**
|Select the separator.

|**File**
|Click on **Browse** and select the shipping service provider's CSV file that you want to use for importing the package numbers.
|====

[#1000]
=== Manually importing package numbers

In the **Orders » Fulfilment » Tab: Import of package numbers** menu in the **List import** area, you can manually enter the package numbers with the corresponding order ID. Alternatively, you can use a barcode scanner to scan these from the packing list. You will find a description of how to use the barcode scanner in the next chapter.

[#1010]
=== Importing package numbers with the help of a barcode scanner

The outgoing items should be booked in plentymarkets once an order is finished being packed. Here, the **Status [7] Outgoing items booked** will be saved for the order and the current date will be saved as the date for the outgoing items. For example, this operation can be carried out by scanning the barcode on the invoice, delivery note, packing list or the address label. Pay attention to the correct configuration of your barcode scanner.

The following example describes the scanning process of the packing list.

[.instruction]
Importing package numbers with the help of a barcode scanner:

. Go to **Orders » Fulfilment**.
. Expand the area **Generating invoices**.
. Generate one or multiple invoices. For further information, refer to the explanations on the <<order-processing/orders/order-documents/generating-invoices#, **Generating invoices**>> page of the manual.
. Create a packing list from these invoices for all orders that need to be packed this time. For further information, refer to the explanations on the <<order-processing/orders/order-documents/packing-list#, **Packing list**>> page of the manual.
. As soon as a package has been packed, mark this order on the packing list.
. Additionally, place another small sticker with the package number (light label) underneath the order ID's barcode.
. Go to **Orders » Fulfilment**.
. Click on the **Import of package numbers** tab.
. Place the cursor in the first field in the **List import** area.
. First scan the order ID and afterwards the package number. +
→ By clicking on **Save**, the package numbers will be saved for all orders in the **Settings** tab.

Set up an event procedure in the **Settings » Orders » Event procedures** menu. Select the procedure **Order &gt; Book outgoing items** for the event **Order change &gt; Package number**. Furthermore, you can send your customers an email template including the package number and the link for tracking the package. For further information, refer to the <<basics/automation/event-procedures#, **Event procedures**>> page of the manual.

[#300]
== Setting up the address label

In contrast to shipping labels, you can precisely define which information should be displayed for address labels in plentymarkets and where it should be positioned on the label. These address labels do not yet include the shipping charges or the shipment numbers, as they were not generated by the shipping provider. Using address labels is especially recommended in certain situations. For example, when shipping books, it is sometimes possible to write book mail on the package and ship it for a cheaper price than the weight of the package. In plentymarkets, you can configure the address label templates, generate a PDF file and use it to print labels.

[TIP]
.When does it make sense to use the software of a parcel service?
====
Generate address labels in plentymarkets to send your items. If you would like to ship packages with a parcel service, then we recommend that you use the software of the parcel service in order to print shipping labels. plentymarkets supports the exchange of data with various parcel services.
====

If you have already created an address label template and saved a PDF template, continue with chapter <<order-processing/fulfilment/generating-documents#700, **Generating the address label**>>.

[#400]
=== Creating an address label template

Before being able to print address labels, you must create a template. Proceed as described below to create a new template.

[.instruction]
Creating an address label template:

. Go to **Settings » Orders » Documents » Address label**.
. Click on the **New template** tab.
. Carry out the settings as desired. Pay attention to the information given in table 3.
. **Save** the settings.

[IMPORTANT]
.Positioning with coordinates
====
The content is positioned on a label by entering coordinates (X, Y). In doing so, the starting point is assumed to be the upper left corner of the label.
====

.Settings in the **Settings » Orders » Documents » Address label menu**
[cols="a,a"]
|====
|Setting |Explanation

|**Layout title**
|Name of the address label template. This name appears in drop-down menus for selecting the template.

|**Character set**
|Select **Unicode** or **ISO-8859-1**. It may take longer to generate PDF documents if the character set "Unicode" is used.

|**Page**
|Enter values (in mm) for the **width** and **height** of the paper which you are going to use for the labels.

|**Margin**
|Enter values (in mm) for the left and the top margin on the page. +
You also need to consider the right and the lower margin when printing. Usually, the spaces are the same as for the left and top margin. For this purpose, read the information provided for the label paper as well.

|**Label**
|Enter values (in mm) for the **width** and **height** of the paper which you are going to use for the labels. +
The exact dimensions are provided with the label paper. Pay also attention to the margins as well as the dimensions of the printing paper if the paper that you print on is bigger than your label.

|**Lines per page**
|Enter the number of lines that will be generated per page.

|**Columns per page**
|Enter the number of columns that will be generated per page.

|**Order of town and postcode**
|Select the order in the drop-down menu.

|**Display town and country in capital letters in delivery address**
|Select whether the town and country should be displayed in capitals letters in the delivery address.

|**Include Germany in delivery address**
|Select whether Germany should be included in the delivery address.

|Further options, such as **Delivery address**, **Invoice address**, **Name** and **Customer ID**
|Enter numbers for the positioning.

|**Item list**
|The item list controls how item data is displayed on the label. There are two different types: **Default** and **Individual**. For further information on this two types, refer to the chapter <<order-processing/fulfilment/generating-documents#600, **Item list**>>.

|**Content of the order ID**
|Select between the **Order ID of the main order** and the **Order ID of the delivery order**.

|**Horizontal barcode**
|Enter the coordinates for positioning the barcode as well as its dimensions.

|**Info bar**
|The info bar contains all important information. Information is summarised in one line and looks like this: +
IN:Invoice No. / PM: (Payment method) / TP: Total price / Date

|**Customer characteristics**
|Enter coordinates to position the customer properties. Select the <<crm/managing-customer-data#400, **characteristic**>> from the drop-down menu. The text that was saved in the <<crm/managing-customer-data#1500, **Customers » Edit customers » Tab: Customer data » Tab: Properties**>> menu will be displayed on the address labels.

|**Free text fields 1 to 10**
|Free text fields enable you to display any desired texts which you have entered for them. +
**__Example__**: For example, one of the free text fields is frequently used to save the sender's address.
|====

Templates that you have already created can be selected and edited in the **Settings » Orders » Documents » Address label » Tab: Templates** in the drop-down menu **Template**. You also have the possibility to display a template of the label and to directly print the template in preview mode. When you delete the template, the link to the PDF template will also be deleted.

The section **PDF template** only becomes visible once you have saved a template. In this section, you can link a PDF as background template for a document. You will find a description of how to save a PDF template in the next chapter.

[#500]
=== Saving a PDF template

Once you have created an address label template, you will be able to see the **PDF template** area above the **Settings** area in the menu **Settings » Orders » Documents » Address label**. You can save one PDF template per address label template. This is useful, for example, if you want to give your address labels a specific design.

[.instruction]
Saving a PDF template:

. Go to **Settings » Orders » Documents » Address label**.
. Select the **template**.
. Click on **Browse...** next to the words **Upload**.
. Select the PDF file from your computer.
. **Save** the settings.

The next time you open the address label template, you will be able to see the **Display template** link within the **Template** line. Click on this link to view the PDF template that is saved for this address label template. If you want to save a different PDF template, then upload a new PDF file as described above. The existing PDF template will be overwritten.

[#600]
=== Item list

The item list controls how item data is displayed on the label. You can choose between the types **Default** and **Individual**.

[.subhead]
Type: Default
If you select the option **Default**, then you will also need to enter the coordinates for the item list, the font size and the font style. This controls the position of the entire item list on the labels. In contrast to the option **Individual**, the text elements such as item ID or variation number, name and quantity will be, however, automatically positioned.

[.subhead]
Type: Individual
If you select the option **Individual**, then additional options will become visible. You will be able to determine the positions on the label individually. You will also need to enter the coordinates for the item list, the font size and the font style. This controls the position of the entire item list on the labels. Furthermore, you have to decide which text elements should be displayed on the labels and you have to position these elements. The text elements are **Quantity**, **Name**, **Item ID** or **Variation No.**, **Weight (kg)**, **Value**, **Customs tariff number**, **Manufacturing country**, **Storage location** and **Limit**. Use the X coordinate, the font style and the width to specify how the individual elements should appear in the item list. Use the option **Width** to determine up to which text width (in mm) the option is displayed.

[#700]
=== Generating the address label

After you have created and saved a template for a label, you can print the label in the **Orders » Fulfilment » Address labels** menu.

[.instruction]
Generating the address label:

. Go to **Orders » Fulfilment**.
. Expand the area **Address labels**.
. Carry out the settings as desired. Pay attention to the information given in table 4.
. Click on the gear-wheel icon. +
→ The address label will be opened in a separate window and can be printed.

.Settings in the **Orders » Fulfilment » Area: Address label** menu
[cols="a,a"]
|====
|Setting |Explanation

2+|Search filter

|**Label template**
|Select a template from the drop-down menu.

|**Order status**
|Select the current status of the orders that you would like to generate address labels for.

|**Order ID**
|Enter one (or more) order IDs. Address labels will then only be generated for the specified orders. Separate multiple IDs with commas.

|**Customer ID**
|Enter one (or more) customer IDs. Address labels will then only be generated for the specified customers. Separate multiple IDs with commas.

|**Item**
|Enter one or more item IDs. Address labels will then only be generated for the specified items. Separate multiple IDs with commas.

|**Type**
|Select a type from the drop-down menu. Select the option **Order** to generate address labels for orders only. Select the option **ALL** to generate address labels for all types of orders, e.g. also for credit notes and returns.

|**Shipping service provider**
|Select the shipping service provider from the drop-down menu to generate address labels for one shipping service provider only. Select the option **ALL** to generate address labels for all shipping service providers.

|**Client (store)**
|Select the client (store) from the drop-down menu to generate address labels for one client only. Select the option **ALL** to generate address labels for all clients.

|**Warehouse**
|Select the warehouse from the drop-down menu to generate address labels for one warehouse only. Select the option **ALL** to generate address labels for all warehouses.

|**Start from line**
|Enter the number to determine which line the print should begin from. +
This option can be helpful if you use label paper. For example, if your last printing job only required the first 3 lines on a piece of label paper, then you could start the next printing job from line 4. This allows you to use the rest of the labels on the page.

|**Sorting**
|Determine the identifying feature that you would like to use for sorting the address labels that are generated. Alternatively, select the option **NONE** if you do not want to have the labels be sorted in any particular way.

|**Grouping**
|Determine which criterion you would like to use for generating and grouping the address labels. Select one of the following options: +
**one label per order** = When the address label will be generated in the order, only one label will be generated for the entire order. +
**one label per order item** = A label is created in the PDF for each order item. +
**one label per item** = A label is created in the PDF for each item in the order. +
**one label per shipping package** = A label is created in the PDF for each shipping package. These are the <<order-processing/fulfilment/preparing-the-shipment#1900, **shipping packages**>> of the order as they are displayed in the shipping centre.

|**Limit**
|Select how many orders should be edited at one time. +
The maximum number that can be selected is equal to the maximum number of orders that can be edited at once. If the number of orders that you wish to edit is larger than the limit, then the process will have to be repeated multiple times. In order to ensure that the system performs as efficiently as possible. The lowest limit is set as the default setting in most of the submenus.

2+|Procedure

|**Change order status**
|Select a new status that you would like to have assigned to the selected orders after the invoices were successfully retrieved.
|====

[NOTE]
.Using the label printer
====
It is possible to use label printers. Label rolls are used most of the time. You can generate the necessary labels in the **Settings » Orders » Documents » Address label** menu. Enter **1** for the options **Lines per page** and **Columns per page**. This way, you will end up with one label per PDF page. In this case, the label measurements would correspond to the page measurements.
====

[#1100]
== Generating the delivery list

In the **Orders » Fulfilment » Area: Delivery list** menu, you carry out settings with which you define which packages should be on the delivery list that will be generated next. For example, you can generate a delivery list for all orders that are in **Status [6] Currently being shipped** by selecting the correct search filter settings.

[.instruction]
Generating the delivery list:

. Go to **Orders » Fulfilment**.
. Expand the area **Delivery list**.
. Carry out the settings for the search filters as desired. Pay attention to the information given in table 5.
. Click on the gear-wheel icon to generate the delivery list. +
→ A file containing the data that corresponds to the search criteria entered will be listed.

.Settings in the **Orders » Fulfilment » Area: Delivery list** menu
[cols="a,a"]
|====
|Setting |Explanation

|**Order status**
|Select the status of the orders that you are searching for. Only the orders with this status will be included in the delivery list.

|**Owner**
|Select an owner for the orders that you are searching for. Alternatively, select the option **ALL**.

|**Outgoing items**
|Click in the field to open the calendar. Select a date from the calendar or manually enter the date to narrow down the orders that will be on the delivery list. The delivery list will only include orders which had their outgoing items booked that day. If no date was selected or entered, then you will search for orders where the outgoing items were not booked yet.

|**Shipping method**
|Select a shipping service provider for the orders that you are searching for. Alternatively, select the option **ALL**.

|**List number**
|Enter the number of the delivery list. This number will appear on the generated delivery list. If you are generating a delivery list for the first time, then number 1 will be set in this field by default. Every time that you generate a delivery list, this number will automatically increase by one.

|**Customer number**
|Enter the customer number. This number will appear on the generated delivery list.

|**Title**
|Enter a title for the delivery list. The title will appear on the generated delivery list.

|**Name**
|Enter the name. The name as well as the contact data (address, postcode and town) will appear on the generated delivery list.

|**Address**
|Enter own address.

|**Postcode / town**
|Enter the postcode and town.

|**Display format**
|Select the format for the delivery list. The following options can be selected: **PDF** and **CSV**.
|====

