= Pick list
:lang: de
include::{includedir}/_header.adoc[]
:position: 40

You can use plentymarkets to generate pick lists as PDF or CSV files, for example if you want to print them or import them into another software. You can display barcodes on your pick lists and these will allow you to scan items directly.

Learn more about pick list as PDF files in the following video tutorial:

video::163403681[vimeo]

== Displaying item data

Use the *pick list* menu to specify which item data should be included on your pick list, e.g. the item ID, EAN, storage location, etc.

[TIP]
.Showing and hiding fields
====
You can use the *position number* to define where on the pick list a field will be displayed. Fields without a position number will not be displayed. Simply select *Pos* as the position to not have a position.
====

[.instruction]
Displaying item data:

. Go to *Settings » Orders » Documents » Pick list*.
. Carry out the settings. Pay attention to the explanations given in the following table:
. *Save* the settings.

|====
|Setting |Explanation

|*Name*
|The name will be displayed as the column title on the pick list

|*Position*
|The position number ensures that a column will be displayed on the pick list and defines where the column will be displayed. Make sure to not set the same position twice.

|*Width*
|Defines how wide a column is. Make sure that the widht of all columns together is not wider than the page that you print your pick list on.

|*Font size*
|Defines the font size of the column title and the column text. Make sure that the font size and the column width match and that long titles are not wider than the column.

|*Font style*
|Defines whether the font will be bold or normal. Make sure that column title do not become to wide for a column because of bold font.

|*Top margin*
|Enter the top margin im mm. A larger top marging maybe required if you use a PDF template that contains the company information and the logo at the top of the page and you want to position this "header" above the pick list (see section 3 below).

|*ID barcode*
|Uses the ID of a pick list and displays it as a barcode.

|*GTIN*
|Uses the first GTIN of a variation. GTINs are created in the barcode menu and the individual GTIN is defined in a variation's data set. The GTIN barcode that you created first and that has the lowest ID therefore will be used here on the pick list.

|*GTIN barcode* +
We recommend to use the *Barcode* option instead.
|Uses the first GTIN of a variation and displays it as a barcode. GTINs are created in the barcode menu and the individual GTIN is defined in a variation's data set. The GTIN barcode that you created first and that has the lowest ID therefore will be used here on the pick list.

|*Barcode*
|Select the barcode that you wish to display on the pick list. You can choose between the variation number and all barcodes that you have set up and that have one of the following types:
*GTIN13,
*GTIN128,
*CODE128 and
*UPC

|*Storage location*
|Enter a title for the column and define what will be displayed as name for a storage location. For example, only the storage location name can be displayed or various combinations of warehouse information can be displayed, such as the rack / shelf / storage location. The quantity is displayed next to the storage location by default. Place a check mark next to the option *Do not show the quantity next to the storage location* if you do not want to display this information on the pick list.

|*Free text*
|Select a free text field that you wish to display on the pick list. +
 First, go to *Settings » Item » Free text fields* to create the free text fields. Then link the free text fields with items and enter values for the fields. This is done in the *Fields* tab of an item. +
For further information, refer to the *<<item/managing-items#70,Managing items>>* page of the manual.

|*Item description*
|Select the information that you want to be displayed as item description. The *item name* is always automatically included in the description. You can select additional information, e.g. the *storage location*, *item ID*, *external item ID*, *item number*, *EAN* and *order properties*.
|====

__Table 1: options in the *Pick list* menu__

== Uploading a PDF template

The term document template is used here to describe your store's letter paper, i.e. a page containing your company information, logo and layout elements according to your corporate design. This template needs to be in PDF format. plentymarkets makes it possible to use a document template for the pick list. In order to upload a PDF template, proceed as described below.

[.instruction]
Uploading a PDF template:

. Go to *Settings » Orders » Documents » Pick list*.
. Click on the *PDF template* tab.
. Click on the *New template* tab.
. Click on *Browse...* and select a PDF document template.
. *Save* the settings. +
→ The PDF template will now appear in the *Templates* tab. There you can see a preview of the PDF template or you can delete the template.

[TIP]
.Template contains header
====
You should place a header above the actual pick list if your template contains a header. Ensure that the top margin is high enough for your header.
====

For further information about document templates, refer to the *<<order-processing/orders/order-documents#,Documents>>* page of the manual. Specifically, refer to the section about *creating a document template*.

== Generating a single pick list

In order to create a pick list, proceed as explained below.

[.instruction]
Generating a pick list:

. Go to *Orders » Fulfilment  » Pick list*.
. Select the *status* of the orders that you wish to include in the pick list.
. Select the general *options* as well as the *file format*.
. Select a *status change* if desired.
. Click on the *gear-wheel icon* to generate the pick list.

== Deleting completed pick lists

You can either select up to 50 pick lists that are completed and delete them at the same time or you can delete all your completed pick lists at once. Pick lists that are not yet completed can not be deleted.

=== Selecting and deleting completed pick lists

Selecting the pick lists and deleting them afterwards gives you the opportunity to take a look at what you are going to delete. The pick lists that are completed will be sorted in descending order by date. Therefore the newest pick lists will be shown first.

[.instruction]
Selecting and deleting completed pick lists:

.  Go to *Orders » Fulfilment*.
.  Open the submenu *pick list*.
.  Click on the *Delete* tab.
.  Select up to 50 pick lists from the list.
. Click on *Delete pick lists*.

Next you can select again up to 50 pick lists and delete them.

=== Deleting all completed pick lists at once

Deleting all completed pick lists at once is fast and easy but if you use this option you will have no opportunity to take a look at the pick lists that will be deleted.

[.instruction]
Deleting all completed pick lists at once:

.  Go to *Orders » Fulfilment*.
.  Open the submenu *pick list*.
.  Click on the *Delete* tab.
.  Click on *Delete all completed pick lists*.
.  Click on *OK* to confirm that you want to delete all completed pick lists.
