= Preparing the shipment
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Shipping service provider, fulfilment service provider, fulfilment, countries of delivery, regions, shipping profile, shipping profiles, table of shipping charges, shipping package, shipping costs, DHL Packstation, tracking URL, cbc logistics, c.b.c logistics, DHL, DHL Easylog, DHL Freight, DHL Intraship, DHL Versenden, DHL plentymarkets Import, DHL Retoure, DHL Retoure with enclosed return labels, DHL Retoure Online, DHL Supply Chain, DHL UK, DPD, DPD Cloud Webservice, DPD DELISprint, EasyPAK, GLS, GLS Germany, Hermes, Hermes two-man handling, Hermes ProfiPaketService, Hermes professional parcel service, MyDPD Business / iloxx, NetDespatch, Royal Mail, UK Mail, Parcelforce Worldwide, Swiss Post, UPS, DHL Fulfillment, IDS Logistik, iLOPACK, Fulfilment by Amazon, FBA, CN23, CN 23, CP71, CP 71
:description: Learn how to set up shipping profiles, shipping packages and shipping service providers in plentymarkets.
:position: 10

Many sellers decide to hire a service provider to ship items on their behalf. Depending on the services that were agreed upon in your contract, the service provider may be hired to pick up the items from your business, send your items and then report the status back to your plentymarkets system.

plentymarkets allows sellers to manage their fully customised shipping processes and trigger nearly all processes automatically. Your plentymarkets system efficiently controls the entire process with the <<basics/automation/plentymarkets-client#, *plentymarkets Client*>>. It carries out everything from linking items with shipping profiles to registering shipments and printing shipping labels. The initial time that it takes to configure the settings will pay off when you have an efficient shipping process that automatically carries out routine tasks.

This page of the manual describes how you prepare the shipping process and which <<order-processing/fulfilment/preparing-the-shipment#2500, *shipping service provider-specific settings*>> you need to carry out. Some service providers offer a complete service which includes storing and packing the items. For further information, refer to the chapter <<order-processing/fulfilment/preparing-the-shipment#4700, *Overview of fulfilment service providers*>>.

[#100]
== Setting up countries of delivery

Set up the countries that you want to ship your items to in the *System » Orders » Shipping » Settings » Tab: Countries of delivery* menu. The overview contains a list of all the countries of delivery that are available in plentymarkets. The country names used in the system are displayed in the column *Standard name*. The standard name cannot be changed and will not be visible to your customers. Use the column *Name* to enter the name that you want your customers to see, e.g. an alternative spelling or an abbreviation.

[#200]
=== Editing and activating countries of delivery

Use the *Overview* tab to edit and activate the countries of delivery.

[.instruction]
Editing and activating countries of delivery:

. Go to *System » Orders » Shipping » Settings » Tab: Countries of delivery » Tab: Overview*.
. Carry out the settings as desired. Pay attention to the information given in table 1.
. *Save* the settings.

.Overview of countries of delivery in the *System » Orders » Shipping » Settings » Tab: Countries of delivery* menu
[cols="a,a"]
|====
|Setting |Explanation

|*ID*
|Internal country of delivery ID. A consecutive ID is automatically assigned by the system and cannot be changed.

|*Name (xy)*
|Enter the country name as it should appear in the online store and on documents. +
*_Important_*: The country name can be saved in various languages. In the *Filter* tab, select the language code from the drop-down menu *Language (Name)* and click on *Search*. The names that are saved for this language will be displayed. Edit the names in the column *Name (xy)* of the overview. Edit the names as desired and save the changes.

|*Standard name*
|Standard name for the country of delivery (cannot be changed)

|*Active*
|Select one of the following options: +
*Active* = The country of delivery is available. +
*Inactive* = The country of delivery is not available. +
*Backoffice is active* = Countries of delivery with this setting are only visible in your plentymarkets system and not in the online store. +
*Supplier is active* = Countries of delivery with this setting cannot be selected as the *Standard country of delivery* in the <<omni-channel/online-store/setting-up-clients/order-process#, *Settings » Client (store) » Standard » Order process » Basic settings*>> menu.

|*Warehouse*
|Select which warehouse the country of delivery should be assigned to. This warehouse will automatically be selected for orders from this country. Select *ALL* if the country of delivery should be assigned to all of the warehouses. In this case, the warehouse with the lowest ID will automatically be selected for the orders. Pay attention to the <<order-processing/orders/_basic-settings#, *warehouse settings*>> in the *System » Orders » Settings* menu as well.

|*Language*
|Select the standard country of delivery for each language. It is only possible to assign one language to a country of delivery.
|====

[#300]
=== Searching for and displaying countries of delivery

All countries of delivery are displayed in the *Overview* tab by default. Use the options in the *Filter* tab to specify which countries of delivery should be displayed in the overview.

[.instruction]
Searching for and displaying countries of delivery:

. Go to *System » Orders » Shipping » Settings » Tab: Countries of delivery » Tab: Filter*.
. Carry out the settings as desired. Pay attention to the information given in table 2.
. Click on *Search*. +
→ The countries of delivery that are found will be displayed in the *Overview* tab.

.Filter options for countries of delivery
[cols="a,a"]
|====
|Setting |Explanation

|*ID*
|Filters countries of delivery according to the internal ID of the country.

|*Name*
|Filters countries of delivery according to the name of the country.

|*Standard name*
|Filters countries of delivery according to the standard name of the country.

|*Warehouse*
|Select a warehouse if you only want to display the countries of delivery for this warehouse.

|*Active*
|*Inactive* = Only display the countries of delivery that are not activated. +
*Active* = Only display the countries of delivery that are activated. +
*Backoffice is active* = Only display countries of delivery with the setting *Backoffice is active*. +
*Supplier is active* = Only display countries of delivery with the setting *Supplier is active*.

|*Language (Name)*
|Select a language.
|====

[#400]
== Creating a region

Regions are groups of countries that have the same shipping costs.

Click on the *New region* tab and create the necessary regions by selecting the countries of delivery that belong to each region. The regions then become available and can be edited in the *Overview* tab. Carefully plan which regions you will need for grouping together your countries of delivery. This is important because shipping costs are entered into the shipping profiles for each region rather than for each country of delivery. Sellers located in the United Kingdom would likely need the following 3 regions at minimum: United Kingdom, Continental Europe and Worldwide.

[TIP]
.Have you activated the necessary countries of delivery?
====
Make sure that you activated all of the necessary countries of delivery before you create regions. A country of delivery can only be assigned to one region. After it has been assigned, it will no longer be available for other regions.
====

[.instruction]
Creating a region:

. Click on the *New region* tab. +
→ The *Available countries* column lists all of the countries of delivery that are not yet assigned to any region.
. Select the desired countries of delivery in the *Available countries* column.
. Use the arrows to move these countries of delivery to the *Selected countries* column. Use the double arrow buttons to move all of the countries from one column to the other.
. Enter a name for the region into the *Name* line.
. *Save* the settings. +
→ The newly created region will be displayed in the *Overview* tab.
. Follow the same pattern to create other regions until all countries of delivery have been assigned to a region and the list of *Available countries* is empty.

[IMPORTANT]
.Assign all countries of delivery
====
All countries of delivery must be assigned to a region. Otherwise, it is not possible to create a valid shipping profile.
====

[.subhead]
Editing a region

Proceed as follows to edit the region.

[.instruction]
Editing a region:

. Open the region in the *Overview* tab.
. Make changes to the settings as needed.
. *Save* the settings.

[IMPORTANT]
.Conditions for deleting a region
====
A region can only be deleted if it is no longer being used in the shipping profiles. If you receive an error message while deleting a region, then check whether there are still settings for this region saved within the table of shipping charges. A region can only be deleted once all of these connections have been completely removed.
====

[#500]
== Entering item bundles and return data

Use the menu *System » Orders » Shipping » Shipping service provider » Settings* to specify which data should be transferred to shipping service providers when <<item/managing-items#920, *item bundles*>> are used. You can either transmit shipping data for the basic item or for the item bundle. The item bundle setting is valid for all shipping providers that are set up in your plentymarkets system. Furthermore, use this menu to save return data for all of the <<stock-management/setting-up-a-warehouse#, *warehouses*>> in your plentymarkets system. Return data is saved for each warehouse. This menu lists the warehouses for all of your active countries of delivery.

[.instruction]
Entering item bundles and return data:

. Go to *System » Orders » Shipping » Shipping service provider » Settings*.
. Select the setting for your *item bundles*.
. Expand the warehouse in the area *Return data*.
. Enter the data.
. *Save* the settings.

[#600]
== Registering with a shipping service provider

First register with the shipping service provider in order to set up the shipping service provider in plentymarkets. Visit the shipping service provider's website for information about the registration process.

[#700]
== Setting up the interface to the shipping service provider

Set up the interface to a shipping service provider as described below. Go to the sub-chapters of the chapter <<order-processing/fulfilment/preparing-the-shipment#2500, *Overview of the shipping service providers*>> to get to know which data you have to enter in the menu of the shipping service provider.

[.instruction]
Setting up the interface to the shipping service provider:

. Go to *System » Orders » Shipping » Shipping service provider*.
. Open the menu of the shipping service provider.
. Enter the data.
. Go to the sub-chapters of the chapter <<order-processing/fulfilment/preparing-the-shipment#2500, *Overview of the shipping service providers*>> to get to know which data you have to enter in the menu of the shipping service provider.
. *Save* the settings.

[#800]
== Creating a shipping service provider

Create the shipping service provider as described below.

[.instruction]
Creating a shipping service provider:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping service provider*.
. Click on *New* in the *Overview* tab. +
→ A new line will be added at the bottom of the overview.
. Carry out the settings as desired. Pay attention to the information given in table 3.
. *Save* the settings.

.Overview in the *System » Orders » Shipping » Settings » Tab: Shipping service provider* menu
[cols="a,a"]
|====
|Setting |Explanation

|*ID*
|Internal ID of the shipping service provider. A consecutive ID is automatically assigned by the system and cannot be changed.

|*Name (xy)*
|Enter the shipping service provider name as it should appear in the shopping cart and on the invoice. You can either enter the real names of shipping service providers, e.g. DPD or DHL, or you can enter more general terms like insured shipping. This name will be visible to customers.

|*Name (back end)*
|Enter the shipping service provider name as it should appear in your system. You can either enter the real names of shipping service providers, e.g. DPD or DHL, or you can enter an alternative name that describes the shipping service provider, e.g. Swiss shipments. This name will be visible to customers.

|*Shipping service provider*
|Select the shipping service provider. This is especially important if you entered an alternative description under *Name* and/or if you did not use a tracking URL.

|*Tracking URL*
|Enter the tracking URL of the shipping service provider.
|====

[TIP]
.Tracking URL
====
Many shipping service providers allow customers to track their packages with tracking URLs. Customers see the tracking URL when they place their order or they receive the URL in an email. Enter the template variable *$TrackingURL* into your email template.

A functional tracking URL should include the package number and the recipient's postcode. Therefore, make sure that your tracking URLs include the template variables *$PaketNr* and, if necessary, *$PLZ*.

The currently valid, known tracking URLs can be found in the chapter of the shipping service provider. You can access the chapters of the shipping service providers via the <<order-processing/fulfilment/preparing-the-shipment#2500, *Overview of the shipping service providers*>> chapter.
====

[#900]
== Searching for shipping service providers

All shipping service providers are displayed in the *Overview* tab by default. Use the options in the *Filter* tab to specify which shipping service providers should be displayed in the overview. You can edit the shipping service providers at any time in the *Overview* tab.

[.instruction]
Searching for shipping service providers:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping service provider*.
. Carry out the settings in the *Filter* tab. Pay attention to the information given in table 4.
. Click on *Search*. +
→ The shipping service providers that are found will be displayed in the *Overview* tab.

.Filter options for shipping service providers
[cols="a,a"]
|====
|Setting |Explanation

|*Search*
|Perform a search. The shipping service providers that match the selected filter criteria will be displayed in the *Overview* tab.

|*Reset*
|Resets the selected filter criteria.

|*ID*
|Filters shipping service providers according to the internal ID of the provider.

|*Name*
|Filters shipping service providers according to the name of the provider.

|*Standard name*
|Filters shipping service providers according to the standard name of the provider.

|*Tracking URL*
|Filters shipping service providers according to the tracking URL of the provider.

|*Shipping service provider*
|Filters shipping service providers according to the option that was selected in the drop-down menu *Shipping service provider*.

|*Language*
|Filters shipping service providers according to the language.
|====

[#1000]
== Creating a shipping profile

The individual shipping profiles are different shipping methods, which your customers can choose later on during checkout or which are assigned automatically to certain types of orders by the online store. For example, you can offer your customers a cheap standard delivery and a more expensive express delivery. You can also set up another shipping profile for eBay listings which the system will then exclusively use for orders from the market eBay. Find tips and tricks in the sub-chapters which you can make use of when creating your shipping profiles. Afterwards, it is describes how you create <<order-processing/fulfilment/preparing-the-shipment#1500, *tables of shipping charges*>> for every shipping service provider and region.

Learn more about shipping options and shipping profiles in the following video tutorial:

[.row]
====
[.col-md-6]
=====
video::125572970[vimeo]
=====

[.col-md-6]
=====
video::187790458[vimeo]
=====
====
Now create the shipping profile for the shipping service provider. The number of shipping profiles depends on the required shipping services. Create a different shipping profile for every shipping service.

[.instruction]
Creating a shipping profile:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Click on *New*.
. Select the shipping service provider that you have just created from the drop-down menu.
. Carry out the settings as desired. Pay attention to the information given in table 5.
. *Save* the settings. +
→ The *Table of shipping charges* tab will be displayed.

.Basic settings for a shipping profile
[cols="a,a"]
|====
|Setting |Explanation

|*ID*
|The ID of the shipping profile is assigned by the system and cannot be changed. Once you have saved the shipping profile, the ID will be displayed in the *Overview* tab.

|*Shipping service provider*
|Select the shipping service provider that you have just created from the drop-down menu.

|*Name*
|The name in this field will be displayed in the online store. Select a name that should be displayed to the customer, e.g. Standard or Express.  If you operate your online store in multiple languages, then use the drop-down menu to save names for every language that you need.

|*Name (back end)*
|Enter a name for the shipping profile. The name will only appear in your system. It will not be visible for customers.

|*Flag*
|Select an icon that should be displayed in the order overview. The flag indicates which shipping profile is saved at a glance.

|*Priority*
|Determines which shipping profile will be displayed first, second, third, etc.

|*Category*
|The category option is another way to prioritise shipping profiles in the shopping cart. Category *1* is selected by default. This means that all of the shipping profiles are given the same priority. Further information can be found in the chapter <<order-processing/fulfilment/preparing-the-shipment#1300, *Tips and tricks: Category*>>.

|*Item extra shipping charge*
|Place a check mark to activate the extra shipping charges that are saved in the item data record. Up to two extra shipping charges can be saved for the item's main variation in the *Shipping* area. *Extra shipping charge 1* is added to the shipping costs for the first item. *Extra shipping charge 2* is added to the shipping costs for all additional items. Extra shipping charges are useful for large or bulky items that are particularly expensive to ship. +
Further information can be found in the chapter <<order-processing/fulfilment/preparing-the-shipment#1100, *Tips and tricks: Extra shipping charges*>>.

|*PostIdent*
|Authority verification by the Deutsche Post AG. Serves to verify customers, e.g. in connection with the proof of age for 18+ items. Place a check mark to activate this option. +
Items with an 18+ age rating have to be linked to a shipping profile that the PostIdent option was activated for.

|*Activate for new items*
|Activate if you want the shipping profile to automatically be assigned to new items. +
You should select this option for new items for at least one shipping profile. In doing so, new items will always be assigned to this shipping profile automatically. An item cannot be shipped if it is not linked to at least one shipping profile.

|*Extra charge for islands*
|Many shipping service providers charge a higher fee for island regions. The seller should not be left with these costs. Therefore, open each shipping profile and define a surcharge that is added when shipping to island regions. Shipping service providers should be able to give you a list of postcodes which incur island surcharges. Postcodes for island regions are saved in the system. They are automatically matched with the order. If you activated the extra charge for islands, then this charge will only be calculated if the system recognises this postcode as an island region. +
The island surcharge applies for each item when using the calculation type *Item shipping charge*.

|*Clients (stores)*
|Choose one of the options or select the option *ALL* if the shipping profile should apply to all online stores. +
This option will only be displayed if at least one client (store) is set up.

|*Order referrer*
|Select one or several of the options to determine possible order referrers for this shipping profile. Alternatively, select *ALL* if you want to activate all referrers.

|*Blocked payment methods*
|Select all the payment methods that should not be offered for the shipping profile. If you have shipping profiles that should not include a cash on delivery option, then make sure to select all of the options that are used in connection with cash on delivery.

|*Blocked customer classes*
|Block one or more customer classes for the shipping profile.

|*Last change*
|If you make changes to the settings, then the date will be updated here.

|*Shipping groups*
|If you want to create groups for your shipping profiles, then enter a name for a shipping group here and click on *Add*. Enter this name into every shipping profile that should belong to this group. You will end up with various groups, which contain different shipping profiles. +
*_Example_*: Shipping group A contains the shipping profiles 1 and 2. Shipping group B contains the shipping profiles 3 and 4. If you want to assign an item to shipping profiles 3 and 4, then open the item and select shipping group B from the drop-down menu in the item's *Global* tab in the *Shipping profiles* area. +
With this function, you can easily assign the shipping profile to new items.

|*Shipping identification*
|This field is currently without any function.

2+|eBay

|*Account*
|Select one or more eBay accounts or select the option *ALL*. +
*_Important_*: You need to have set up at least two accounts, otherwise this option is not visible. Further information can be found in the chapter <<order-processing/fulfilment/preparing-the-shipment#1200, *Tips and tricks: Shipping costs for orders placed on eBay*>>.

|*Listing type*
|Decide which eBay listing type you want to activate this shipping profile for.

2+|Further options

|*Express delivery*
|Activate if you want to use this shipping profile for express delivery. +
*_Important_*: Make sure that the shipping service provider offers express delivery. This is required to use the option.

|*Loyalty program*
|Select one or more loyalty programs. You can use the loyalty programs with <<omni-channel/multi-channel/ebay#6600, *eBay Plus*>> or <<omni-channel/multi-channel/amazon#4200, *Amazon*>>. +
*_Important_*: If you select a loyalty program for a shipping profile, then you will only be able to use the shipping profile for the market. It will not be possible to use the shipping profile for the online store. If, for example, the *eBay Plus* option is activated in a shipping profile, then the shipping profile will only be used for *eBay Plus* orders. Therefore, create an extra shipping profile that you only use for the loyalty program.
|====

[#1100]
=== Tips and tricks: Extra shipping charges

The following partial amounts are added together if an order includes items with extra shipping charges:

* The shipping costs that were entered into the shipping profile (basic shipping charge)
* The extra shipping charge 1 for the item with the highest extra shipping charge
* The extra shipping charge 2 for each additional item

[.subhead]
Example: Adding extra shipping charges for different items

In this example, a customer orders 2 PCs and 2 monitors. The following shipping costs are saved for the items:

*Item 1: PC*

* Basic shipping charge (shipping profile) = 3.99 EUR
* Extra shipping charge 1 = 5.00 EUR
* Extra shipping charge 2 = 3.00 EUR

*Item 2: Monitor*

* Basic shipping charge (shipping profile) = 3.99 EUR
* Extra shipping charge 1 = 4.00 EUR
* Extra shipping charge 2 = 2.00 EUR

The customer orders 2 PCs and 2 monitors. The following shipping costs are calculated for the order:

* 3.99 EUR (basic shipping charge) + 5.00 EUR (PC: extra shipping charge 1) + 3.00 EUR (PC: extra shipping charge 2) + 2.00 EUR (monitor: extra shipping charge 2) + 2.00 EUR (monitor: extra shipping charge 2) = 15.99 EUR

[.subhead]
Example: Extra shipping charges for multiple copies of the same item

In this example, a customer orders 1 PC, then 2 PCs and then 3 PCs. The following shipping costs are saved for the item:

*Item 1: PC*

* Basic shipping charge (shipping profile) = 3.99 EUR
* Extra shipping charge 1 = 5.00 EUR
* Extra shipping charge 2 = 3.00 EUR

The customer orders 1 PC, then 2 PCs and then 3 PCs. The following shipping costs are calculated for the order:

* For 1 PC: 3.99 EUR (basic shipping charge) + 5.00 EUR (extra shipping charge 1) = 8.99 EUR
* For 2 PCs: 3.99 EUR (basic shipping charge) + 5.00 EUR (extra shipping charge 1) + 3.00 EUR (extra shipping charge 2) = 11.99 EUR
* For 3 PCs: 3.99 EUR (basic shipping charge) + 5.00 EUR (extra shipping charge 1) + 3.00 EUR (extra shipping charge 2) + 3.00 EUR (extra shipping charge 2) = 14.99 EUR

[TIP]
.Calculating shipping costs with extra charges only
====
You can use the *Extra shipping charge* function to let the system calculate your shipping costs exclusively on the basis of ordered items. This is done by entering the shipping costs for each item into the item data record and setting all of the shipping prices to *zero* in the shipping profile.
====

[#1200]
=== Tips and tricks: Shipping costs for orders placed on eBay

Set up the shipping costs for orders placed on eBay in the *System » Listings » Checkout* menu. To do so, select **Transfer from eBay** or **Have it calculated by plentymarkets** under the option *Shipping costs for new orders coming from eBay*.


If shipping costs should be calculated differently for eBay than they are for orders coming from the online store, then a separate shipping profile must be created for them. In this shipping profile, select *eBay* only under the option *Order referrer*. This shipping profile has to be activated for every item that you want the setting to apply to. Thus, at least two shipping profiles are activated for these items. One is the shipping profile that contains the "normal" shipping costs and the other one is the shipping profile that contains the shipping costs for eBay.

[IMPORTANT]
.Own shipping profile per eBay account
====
If you have activated several eBay accounts in your plentymarkets system, you can define an individual shipping profile for each eBay account. Use the option *eBay account* in the *System » Orders » Shipping » Settings » Tab: Shipping profiles » Tab: Base* menu to select one of the different accounts.
====

[#1300]
=== Tips and tricks: Category

The category option is another way to prioritise shipping profiles. You can use this option to decide which shipping profiles should be displayed in the shopping cart. Category *1* is selected by default. This means that all of the shipping profiles are given the same priority.

The following rules apply:

* The shipping profile with the lowest category will always be displayed.
* For multiple items, the common shipping profile with the lowest category will be displayed.
* If the items do not have a common shipping profile, then the shipping profile with the lowest category will be selected.

[TIP]
.Creating a "replacement shipping profile"
====
Create a shipping profile that has a higher category level than the other shipping profiles. This so called "replacement shipping profile" will only be chosen if none of the others apply or if they cannot be chosen.
====

[.subhead]
Example: Selling 18+ items together with other items

You can use categories to sell items that have the shipping profile *delivery to addressee only* (e.g. items released for age 18 and older) together with other items. This is solved as follows:

*Item A*

* Shipping profile 1 (category 1)
* Shipping profile 2 (category 2)

*Item B* (18+ item)

* Shipping profile 2 (category 2)
* Shipping profile 3 (category 5)

If item A is bought alone, then shipping profile 2 will not be displayed because a shipping profile is available that has a lower category. If both items are bought together, then shipping profile 2 has the lowest common category and will therefore be the only profile that is displayed.

[#1400]
=== Tips and tricks: Shipping profile combinations that can cause errors

Make sure that all items that can be bought together have at least one common shipping profile. If there are two or more items in the shopping cart which do not have a common shipping profile, then the shipping charges will be added together for both profiles. However, only the shipping service provider with the higher priority will be displayed in the shopping cart. Shipping profiles should not be combined in this way. Such combinations cause errors to occur.

You can avoid such errors, e.g. by activating a DHL shipping profile for all items and only activating an additional shipping profile for selected items.

[.subhead]
Example: No common shipping profile

There are two items in the shopping cart which do not have a common shipping profile.

*Item A*

* DPD shipping profile
* Flat rate shipping charge of 3.95 EUR

*Item B*

* DHL shipping profile
* Flat rate shipping charge of 2.95 EUR

The priority determines the order in which shipping profiles are displayed in the checkout process in your online store. The customer sees a total shipping charge of 6.90 EUR. However, the customer only sees the shipping service provider with the higher priority in the shopping cart.

[#1500]
== Creating a table of shipping charges

Use the *Table of shipping charges* tab to enter shipping costs for a shipping profile. Save shipping charges for every region that you want to use with the shipping profile. Select the calculation type and the shipping charge. You will see additional settings for specific service providers once you have saved and reloaded the table of shipping charges. First carry out the general settings. Pay attention to the information given in table 6.

[IMPORTANT]
.Shipping service not available for every shipping service provider
====
Not every shipping service provider includes additional shipping services. If available and once you have saved and reloaded the table of shipping charges, the shipping services will be displayed in the table of shipping charges. They are displayed underneath the name of the service provider. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles* and open the shipping profile. Click on the *Table of shipping charges* tab and expand the region. The shipping services will be displayed in the lower portion of the table of shipping charges.
====

Learn more about how to create table of shipping charges and about the <<order-processing/fulfilment/preparing-the-shipment#1600, *calculation types*>> in the following video tutorial:

video::187790622[vimeo]

[.instruction]
Creating a table of shipping charges:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping profile.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. Select a calculation type from the drop-down menu. +
→ Depending on the calculation type you select, different field names will be displayed in the following.
. Carry out the settings as desired. Pay attention to the information given in table 6.
. *Save* the settings.
. Reload the table of shipping charges. +
→ Additional shipping services will be displayed, if available.
. Select the shipping service from the drop-down menu.

.Table of shipping charges for a shipping profile
[cols="a,a"]
|====
|Setting |Explanation

|*Save*
|Save the settings.

|*Copy settings to*
|Transfers the settings from one region to another. A new window will open. This window contains a drop-down menu which contains the regions. Select a region and click on *Execute*.

|*Delete link*
|Resets all settings. You have to carry out this function, e.g. before you can delete a region.

|*Calculation type*
|Select a <<order-processing/fulfilment/preparing-the-shipment#1600, *calculation type*>>. The calculation type is the basis for calculating the shipping costs.

2+|Shipping costs

|*Flat rate shipping charge*
|Enter the shipping costs. +
The field name that is displayed depends on the calculation type that was selected.

2+|Flat rates

|*No shipping costs for orders for values over*
|Enter the value of items starting from which deliveries should take place free of charge for the customer.

|*From an item value of ... +
... flat rate shipping charge of*
|In the field *From an item value of ...*, enter the value of items starting from which deliveries should take place at a fixed price. Enter the fixed price into the field *... flat rate shipping charge of*. +
This amount may not be higher than the amount that you entered for the option *No shipping costs for orders for values over*. This is because shipping is already free of charge at that point.

2+|Limitations

|*Limitation type*
|Select the limitation type. +
The standard currency is used if the item value is limited. +
The item's gross weight is used if the weight is limited.

|*Minimum value*
|Enter a value. The shipping profile is valid starting from this value. The limitation type specifies whether the value is a monetary amount, weight, number, etc. +
If you select the setting *Maximum (cubic metres)* under *Limitation type*, the value here must be entered in mm.

|*Maximum value*
|Enter a value. The shipping profile is valid up to this value. The limitation type specifies whether the value is a monetary amount, weight, number, etc. +
If you select the setting *Maximum (cubic metres)* under *Limitation type*, the value here must be entered in mm.

2+|General configuration

|*Standard package*
|Select the <<order-processing/fulfilment/preparing-the-shipment#1900, *shipping package*>> that should be used for this shipping profile. +
This option becomes visible once you save and reload the table of shipping charges.

2+|Specific settings of the shipping service provider

|e.g. *DHL Intraship/Versenden*
|The settings of the shipping service provider become visible once you save and reload the table of shipping charges.

2+|Other configurations

|*Amazon Prime*
|Only available if you have booked the Multi-Channel module.
|====

[#1600]
== Selecting a calculation type in the table of shipping charges

Calculation types in the *Table of shipping charges* tab are different ways to calculate shipping costs for items. For example, you can calculate shipping costs based on an item's weight or volume or based on the number of items that are purchased. You can select a different calculation type for each region. All of the different calculation types are explained in the section below. Table 7 contains notes that apply to the calculation types in general.

.General settings of the calculation types
[cols="a,a"]
|====
|Setting |Explanation

|*Maximum values*
|If the maximum saved value (volume, weight, price, quantity) is exceeded, then no shipping costs can be calculated. Therefore, the maximum should always be high enough.

|*Flat rates*
|A flat-rate shipping charge can be defined starting from a particular value of items. If the order reaches or exceeds this value of items, then the flat-rate shipping charge will be used for the calculation. These flat rates take priority over the values saved for weights, volumes or quantities.

|*Limitations*
|Limitations allow you to specify minimum and maximum values for each shipping profile. If an order does not meet or exceeds these values, then it will not be possible to use the shipping profile for this order. You can create another shipping profile as an alternative, e.g. a profile for a different shipping service provider. It should have values that go beyond the limitations.
|====

[TIP]
.Template variables
====
You will find <<omni-channel/online-store/cms-syntax#basics-template-variables, *template variables*>> for the various calculation types in the menu <<omni-channel/online-store/cms-syntax#web-design-itemview-container-itemviewsingleitem, *CMS » Web design » Layout » ItemView » ItemViewSingleItem*>>. The template variable *$Volumen* doesn't display dimensions, but rather the volume in cubic metres.
====

[#1610.subhead]
Calculation type: Flat rate

This calculation type treats shipping costs as total prices. In other words, regardless how many items a customer purchases, he or she will only pay the shipping costs entered here.

In this case, it would be wise to set up an extra shipping charge for each additional item. You can do so by saving <<item/managing-items#290, *extra shipping charges*>> within the items' *Shipping* area and by activating the *Item extra shipping charge* option in the *Base* tab of the shipping profile.

[#1620.subhead]
Calculation type: Weight-dependent

If you select the calculation type *Weight-dependent*, then enter the maximum gross weight in grams into the column *Maximum (g)*. Enter the corresponding shipping costs into the column *Amount (EUR)*. This way, you will create a sliding scale of shipping costs according to weight. Click on *Add* to add further graduated prices.

[#1630.subhead]
Calculation type: Volume-dependent

If you select the calculation type *Volume-dependent*, then enter the maximum volume in cubic metres into the column *Maximum (cubic metres)*. Enter the corresponding shipping costs into the column *Amount (EUR)*. This way, you will create a sliding scale of shipping costs according to the item's volume. Click on *Add* to add further graduated prices.

[WARNING]
.Dimensions must be saved for the item
====
The volume will only be calculated correctly if you saved the item's length, width and height within the main variation's *Settings* tab in the <<item/managing-items#270, *Dimensions*>> area in the *Item » Edit item » Open item* menu. It is not possible to calculate the volume if these entries are missing. Therefore, it is not possible to calculate the shipping costs based on the volume either.
====

[#1640.subhead]
Calculation type: Quantity-dependent

If you select the calculation type *Quantity-dependent*, then enter the maximum number of items into the column *Maximum (no.)*. Enter the corresponding shipping costs into the column *Amount (EUR)*. This way, you will create a sliding scale of shipping costs according to the number of items. Click on *Add* to add further graduated prices.

[#1650.subhead]
Calculation type: Price-dependent

If you select the calculation type *Price-dependent*, then enter the maximum order total into the column *Maximum (EUR)*. Enter the corresponding shipping costs into the column *Amount (EUR)*. This way, you will create a sliding scale of shipping costs according to the value of a particular item. If all of the items use the same shipping profile, then you will have a sliding scale for the total price of an entire order.

[#1660.subhead]
Calculation type: Item shipping charge

If you select the calculation type *Item shipping charge*, then the shipping costs will depend on the number of items. Depending on which amount you enter in the field *Each additional item*, the shipping costs for each additional item will increase by this amount.

[#1700]
== Calculating the shipping costs

In the *Calculate shipping costs* tab, you can configure the shipping costs that are needed for exporting items to price comparison portals. The general shipping profiles are not used for price comparison portals. Configure settings that are suitable for all of the items that are exported to price comparison portals. If these settings are not configured, then the shipping costs will be exported incorrectly or they will be exported with the entry "0".

For further information, refer to the chapter <<basics/data-exchange/exporting-data#30, *Exporting data formats for price search engines*>> on the <<basics/data-exchange/exporting-data#, *Exporting data*>> page of the manual.

Select the most general default referrer possible, e.g. *Client (store)*. Select a standard shipping region that includes all of the countries of delivery for the items that you want to export.

[TIP]
.Cash in advance payment method
====
Be sure to select the payment method *Cash in advance* so that this payment method can be used as an alternative in case the other payment methods are rejected.
====

[.instruction]
Calculating the shipping costs:

. Go to *System » Orders » Shipping » Settings » Tab: Calculate shipping costs*.
. Select the *default referrer*, *standard shipping region*, *payment method 1* and *payment method 2* for both configurations.
. *Save* the settings.

Learn more about calculating the shipping costs in the following video tutorial:

video::187828489[vimeo]

[#1800]
== Activating the shipping profile

You will not be able to ship an item with a specific shipping profile until you have opened the item data record and activated the profile. Activate at least one shipping profile per item. Otherwise the shipping costs may not be calculated correctly.

[.instruction]
Activating the shipping profile:

. Go to *Item » Edit item*.
. Open the item.
. Click on the *Global* tab.
. Activate the shipping profiles.
. *Save* the settings.

[IMPORTANT]
.Default shipping profile
====
If an order contains items for which no shipping profile was activated, then the items will be given the default shipping profile of the default online store. Select this default shipping profile in the <<omni-channel/online-store/setting-up-clients/order-process#, *Settings » Client (store) » Standard » Order process » Basic settings*>> menu. If no default shipping profile was specified, then the shipping profile with the highest priority will be used.
====

[#1900]
== Creating a shipping package

In the *System » Orders » Shipping » Shipping packages* menu, you create shipping packages for your shipping processes. You can set up shipping packages with clearly defined dimensions or you can let your plentymarkets system automatically define the size based on the item data. A standard package will automatically be assigned if you do not create a shipping package and assign it to an order. The volume of the standard package will be calculated based on the item data.

[TIP]
.Examples: Defined shipping packages and individual packaging
====
Defined shipping packages: A seller ships his/her items in two different cardboard box sizes. Therefore, he or she needs to set up two shipping packages. The volume of these packages results from the dimensions entered and saved. +
Shipping package 1: 30 cm x 25 cm x 40 cm +
Shipping package 2: 50 cm x 50 cm x 25 cm

Individual packaging: In order to ship e.g. furniture, the seller uses packaging material that will be individually cut to match the size of the item to be shipped. These materials can be corrugated card board, foil etc. The volume will be calculated based on the item data.
====

Proceed as described below to create a shipping package.

[.instruction]
Creating a shipping package:

. Go to *System » Orders » Shipping » Shipping packages*.
. Click on the *New Shipping package* tab.
. Carry out the settings as desired. Pay attention to the information given in table 8.
. *Save* the settings.

.Settings in the *New shipping package* tab
[cols="a,a"]
|====
|Setting |Explanation

|*Name*
|Enter a name.

|*Volume*
|Select *take from the shipping package* (length, width, height) or *take from the item data (total)*. +
If you select the option *take from the item data (total)*, then the lines *Length*, *Width* and *Height* are no longer visible.

|*Length*, *Width*, *Height*
|Enter the values for the dimensions of the shipping package and pay attention to the unit.

|*Unit*
|Select a unit from the drop-down menu.

|*Maximum weight (KG)*
|Enter the maximum weight in kilograms.

|*Maximum volume (total)*
|Enter the maximum volume in cubic metres. +
This value refers to the total volume of the shipping package and is the sum of the volumes of the items contained in it. This number will give you an idea of whether or not the items of an order will fit into the shipping package.

|*Client (store)*
|Select a client (store) from the drop-down menu. Select the option *ALL* if you wish to make the shipping package available for all online stores.
|====

How you edit, add or delete shipping packages is described on the <<order-processing/fulfilment/shipping-centre#, *Using the shipping centre*>> page of the manual.

[#2300]
== Controlling shipping processes with the plentymarkets Client

The <<basics/automation/plentymarkets-client#, *plentymarkets Client*>> is a tool that you can use to manage all of your shipping processes. It is possible to set up and customise very specific processes and then carry out these processes automatically. For example, you can use the procedures <<basics/automation/processes/procedures#340, *Polling*>>, <<basics/automation/processes/procedures#380, *Return label*>>, <<basics/automation/processes/procedures#390, *Return slip*>> and <<basics/automation/processes/procedures#430, *Shipping centre*>> to process your shipments.

[#2400]
== Retrieving the API log

The *Data exchange » API log » Tab: Shipping centre API log* menu contains information about shipments that were registered in the *Orders » Shipping centre* menu. Select the shipping service provider from the drop-down menu *Process* as well as a date and the processes displayed per page. Click on *Search* to display the processes.

For further information about API log entries for DHL Fulfillment and DPD Cloud Webservice, refer to the <<basics/data-exchange/api-log#, *API log*>> page of the manual.

[#2500]
== Overview of shipping service providers

Table 9 lists the shipping service providers that are available in plentymarkets. Click on the service provider in the table to jump to the sub-chapter where the specific settings of the shipping service provider are described.

[IMPORTANT]
.Shipping service not available for every shipping service provider
====
Not every shipping service provider includes additional shipping services. If available and once you have saved and reloaded the table of shipping charges, the shipping services will be displayed in the table of shipping charges. They are displayed underneath the name of the service provider. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles* and open the shipping profile. Click on the *Table of shipping charges* tab and expand the region. The shipping services will be displayed in the lower portion of the table of shipping charges.
====

.Overview of shipping service providers available in plentymarkets
[cols="a,a"]
|====
|Shipping service provider |Explanation

|<<order-processing/fulfilment/preparing-the-shipment#2600, *c.b.c. logistics*>>
|For sellers within Germany. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#2700, *DHL Easylog*>>
|For sellers within Germany. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#2800, *DHL Freight*>>
|For sellers within Germany. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#2900, *DHL Intraship/Versenden*>>
|For sellers within Germany. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#3000, *DHL plentymarkets Import*>>
|Polling format. For sellers within Germany. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#3100, *DHL Retoure with enclosed return labels*>>
|For sellers within Germany. Return: international.

|<<order-processing/fulfilment/preparing-the-shipment#3200, *DHL Retoure Online*>>
|For sellers within Germany. Return: international.

|<<order-processing/fulfilment/preparing-the-shipment#3300, *DHL Supply Chain*>>
|For sellers within Germany. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#3400, *DHL UK*>>
|For sellers within the United Kingdom. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#3500, *DPD Cloud Webservice*>>
|For sellers within Germany. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#3600, *DPD DELISprint*>>
|For sellers within Germany. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#3700, *EasyPAK*>>
|For sellers within Austria. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#3800, *GLS Germany*>>
|For sellers within Germany. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#3900, *Hermes (two-person handling)*>>
|For sellers within Germany. Shipping: Germany and Europe.

|<<order-processing/fulfilment/preparing-the-shipment#4000, *Hermes ProfiPaketService*>> (professional parcel service)
|For sellers within Germany. Shipping: Germany and Europe.

|<<order-processing/fulfilment/preparing-the-shipment#4100, *MyDPD Business / iloxx*>>
|For sellers within Germany. Shipping: Germany and Europe.

|<<order-processing/fulfilment/preparing-the-shipment#4210, *Royal Mail (via NetDespatch)*>>
|For sellers within the United Kingdom. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#4230, *UK Mail (via NetDespatch)*>>
|For sellers within the United Kingdom. Shipping: United Kingdom.

|<<order-processing/fulfilment/preparing-the-shipment#4250, *Parcelforce Worldwide*>>
|For sellers within the United Kingdom. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#4300, *Swiss Post*>>
|For sellers within Switzerland. Shipping: Switzerland.

|<<order-processing/fulfilment/preparing-the-shipment#4400, *UPS*>>
|For sellers within Germany. Shipping: international.
|====

[#2600]
=== c.b.c. logistics

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Proceed as follows to set up the interface to link:http://en.cbc-logistics.com/[*c.b.c. logistics*^] in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » CBC Logistics*.
. Enter the user and password that you received from c.b.c. logistics.
. *Save* the settings.

Now carry out the shipping service provider-specific settings for the shipping services in the table of shipping charges. These services are only visible in the table of shipping charges after you have saved the settings in the shipping profile.

[.instruction]
Setting shipping service provider-specific services:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping service provider.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. Carry out the settings in the *CBC Logistics* area. Pay attention to the information given in table 10.
. *Save* the settings.

.c.b.c. logistics shipping services in the *Table of shipping charges* tab
[cols="a,a"]
|====
|Setting |Explanation

|*Profile*
|Select the profile from the drop-down menu.

|*Sender*
|Select the profile from the drop-down menu.

|*Shipping service provider*
|Select the shipping service provider from the drop-down menu.

|*Product*
|Select the product from the drop-down menu.

|*Services*
|Select one service or the option *ALL*.
|====

[#2700]
=== DHL Easylog

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Proceed as follows to set up the interface to link:https://www.dhl.de/en/paket/geschaeftskunden/versandsoftware.html[*DHL Easylog*^] in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » DHL Easylog*.
. Enter the Data that you received from DHL.
. *Save* the settings.

[IMPORTANT]
.Sender reference numbers and cash on delivery service
====
By default, the number 1 will be displayed in the sender reference number data field *POOL_V_ABS_REFNR*. Other sender reference numbers are possible, e.g. for the payment method *cash on delivery*. Come to an agreement about these settings with the DHL support. +
For the cash on delivery service, enter the ID 114 or 134 for domestic. The ID 5311 is used by default for foreign countries.
====

Now carry out the shipping service provider-specific settings for the shipping services in the table of shipping charges. These services are only visible in the table of shipping charges after you have saved the settings in the shipping profile.

[.instruction]
Setting shipping service provider-specific services:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping service provider.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. Carry out the settings in the *DHL Easylog* area. Pay attention to the information given in table 11.
. *Save* the settings.

.Settings for the DHL Easylog interface
[cols="a,a"]
|====
|Setting |Explanation

|*DHL process*
|The process number specifies whether you are dealing with a national, European, international or express delivery.

|*DHL product*
|Different products will be available depending on the process that was selected.

|*DHL service*
|Different services, e.g. advice of delivery, transport insurance etc. will be available depending on the process that was selected.

|*DHL subscription*
|DHL subscriptions can be thought of as contracts relating to the transport services.
|====

[IMPORTANT]
.Calculating the cash on delivery amount
====
If the number of packages saved for an order is larger than one, then DHL will be given the information that the amount to be collected is the amount on the invoice divided by the number of packages.
====

[#2800]
=== DHL Freight

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Proceed as follows to set up the interface to link:http://www.dhl.de/de/logistik/frachttransport/land-schienentransport.html[*DHL Freight*^] in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » DHL Freight*.
. Carry out the settings as desired. Pay attention to the information given in table 12.
. *Save* the settings.

.Settings for the DHL Freight interface
[cols="a,a"]
|====
|Setting |Explanation

|*Subsidiary*
|Enter the three-digit abbreviation that you received from DHL.

|*Return data*
|Enter the company name.

|*Description of the goods*
|Enter the name of the industry sector.

|*Client No., FTP user, FTP password*
|Enter the data that you received from DHL.

|*FTP in/out directory*
|Activate in order to use the FTP directory structure of DHL Freight.
|====

Now carry out the shipping service provider-specific settings for the shipping services in the table of shipping charges. These services are only visible in the table of shipping charges after you have saved the settings in the shipping profile.

[.instruction]
Setting shipping service provider-specific services:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping service provider.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. Carry out the settings in the *DHL Freight* area. Pay attention to the information given in table 13.
. *Save* the settings.

.DHL Freight shipping services in the *Table of shipping charges* tab
[cols="a,a"]
|====
|Setting |Explanation

|*DHL product*
|Select one of the following products from the drop-down menu: +
*Standard* +
*Express next day* +
*Express, next day delivery before 10am* +
*Express, next day delivery before 12pm* +
*Europlus*

|*DHL franking*
|Select one of the following franking types from the drop-down menu: +
*Unfrei (postage not paid)* +
*Tax allowance country of origin* +
*Tax allowance country of delivery* +
*Free home delivery duty unpaid/nontax-paid* +
*Free home delivery duty paid/nontax-paid* +
*Free home delivery duty paid/tax-paid*
|====

[#2900]
=== DHL Intraship/Versenden

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

At the end of this chapter, you will find information about DHL export documents.

Proceed as follows to set up the interface to link:http://www.dhl.de/de/paket/geschaeftskunden/versandsoftware.html[*DHL Intraship/Versenden*^] in plentymarkets.


[IMPORTANT]
.Using the DHL Shipping (Versenden) plugin
====
Via the interface to the DHL business customer portal, you can use the function *Versenden* (shipping). The *DHL Shipping (Versenden)* plugin is available in the link:https://marketplace.plentymarkets.com/plugins/integration/DHLShipping_4871[*plentyMarketplace*^].

The interface that is integrated in plentymarkets will still be named *DHL Intraship/Versenden* until DHL informs us that all customers are using *DHL Versenden*. The interface DHL Intraship/Versenden as well as settings that relate to DHL Intraship/Versenden in other menus are valid for existing DHL Intraship customers until DHL Intraship will be turned off.
====

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » DHL Intraship/Versenden*.
. Carry out the settings as desired. Pay attention to the information given in table 14.
. *Save* the settings.

.Settings for the DHL Intraship/Versenden interface
[cols="a,a"]
|====
|Setting |Explanation

2+|Master data

|*Accounting numbers*
|Enter the accounting numbers in accordance with the DHL contract. It is possible to maintain individual return data for each accounting number. The 14-digit DHL Intraship/Versenden accounting number is composed of the following: +
*PP* = customer number; consists of the first 10 numbers of the accounting number. +
*Process* = Indicates the DHL product that the accounting number is valid for. It is made up of the two middle characters of the accounting number. +
*_Important_*: Pay attention to the explanation given in the box below the table. +
*Subscription* = The last two characters of the accounting number (only numbers or letters must be entered).

|*Login name*
|The login name may not contain any umlauts. Even if a login name with umlauts is accepted by the website, the interface may still reject it.

|*Password*
|The maximum password length is 20 characters. Although DHL technically allows you to use a longer password, you may only use a maximum of 20 characters via the plentymarkets interface. If you use a password that is longer than 20 characters, then errors will occur when transferring data with the SOAP interface.

|*Alternative telephone number for foreign customers*
|DHL typically prints the recipient's telephone number on the label when shipping to foreign countries. This allows DHL to contact the recipient if needed. If you do not want this to be the case, then save a corresponding entry such as "No Tel." or enter a string of zeros. This entry will override the foreign customer's telephone number. +
The option is also important if you did not mark the telephone number for foreign customers as a mandatory field in the layout. Otherwise DHL would reject the shipment.

|*Force label generation*
|When registering a shipment with DHL Intraship/Versenden in the shipping centre, decide whether a shipping label should be generated even if there was no data / incomplete data saved for the address. +
*Yes* = DHL will correct the incorrect data and bill you for this service (default setting). +
*No* = Not codable shipments will be rejected when trying to register them with DHL Intraship/Versenden and an error message will be displayed. The order will not be registered and plentymarkets will not generate a shipping label.

|*Email recipient*
|Select whether the customer's email address should be transferred to DHL.

2+|Return data

|*Company, Shipper address, Contact person, Bank details*
|Enter the return data.

|*Mixed calculation*
|Select whether the mixed calculation should be activated.

|*Postage for export shipping*
|Select whether customs and taxes are to be paid by the customer (DAP) or by the seller (DDP).

|*Shipping label*
|*Logo* = The logo's file size is limited to 100 KB. The logo should have an aspect ratio of 3:4 and its dimensions should be 15 x 20 mm (height x width). +
*_Important_*: Save the logo's URL with the protocol *http://*. +
*Alternatively, use address details from the following accounting number* = Select one of the accounting numbers that you have just saved from the drop-down menu.
|====

[IMPORTANT]
.DHL accounting number
====
The two middle characters of the accounting number *Process* stand for the following DHL products: DHL Paket (01), Regionalpaket AT (02), DHL Europaket (54), DHL Paket International (53), DHL Domestic Express (71) and DHL Officepack (72). +
*_Important_*: DHL Intraship/Versenden uses the number 01 for the product Regionalpaket AT. However, we use the number 02 since there can be conflicts in plentymarkets with DHL Paket. DHL Domestic Express uses the number 71 so that it does not conflict with DHL Officepack. Of course, the correct number is sent to DHL.
====

Now carry out the shipping service provider-specific settings for the shipping services in the table of shipping charges. These services are only visible in the table of shipping charges after you have saved the settings in the shipping profile.

[.instruction]
Setting shipping service provider-specific services:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping service provider.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. Carry out the settings in the *DHL Intraship/Versenden* area. Pay attention to the information given in table 15.
. *Save* the settings.

.DHL Intraship/Versenden shipping services in the *Table of shipping charges* tab
[cols="a,a"]
|====
|Setting |Explanation

|*DHL accounting number*
|Select an accounting number from the drop-down menu.

|*DHL service*
|Select one, several or *ALL* services types.
|====

[.subhead]
DHL export documents

DHL export documents are only generated for orders that are shipped with the product *DHL Paket International* and that are actually export shipments. Export shipments must contain a customs declaration, the so-called CN23 document, and a dispatch note, the so-called CP71 document. *DHL Paket International* can also be used for intra-community deliveries. However, no export documents will be generated in this case.

Export shipments may contain a maximum of 5 stock units. The individual data for each stock unit will be reported: Weight, customs tariff number, manufacturer country, item name, value of items and quantity.

If you are using the DHL Intraship/Versenden interface, you can manually generate the export documents in the *Orders » Fulfilment* menu. In order for orders to be found for the creation of export documents, they have to be successfully registered with DHL Intraship/Versenden in the *Orders » Shipping centre* menu. Furthermore, an invoice must have been generated for these orders.

[TIP]
.Export documents automatically available in the shipping centre via DHL Shipping plugin
====
If you are using the DHL Shipping plugin, export documents will automatically be available in the shipping centre next to the shipping label when you register the shipping order. This function will be available as of version 1.3. You can download the DHL Shipping plugin free of charge from the link:https://marketplace.plentymarkets.com/plugins/integration/DHLShipping_4871[*plentyMarketplace*^].
====

[.instruction]
Generating DHL export documents:

. Go to *Orders » Fulfilment*.
. Expand the *Generate DHL Intraship export documents* submenu.
. Carry out the settings as desired. Pay attention to the information given in table 16.
. Click on the gear-wheel icon.  +
→ The export documents will be generated as PDFs.

.Generating DHL Intraship export documents
[cols="a,a"]
|====
|Setting |Explanation

|*Order status*
|Select the order status of the data that you would like to generate export documents for.

|*Shipped on*
|Select the shipping date that data should be searched for.

|*Limit*
|Select the limit for generating the documents.
|====

[TIP]
.Booking outgoing items via an event procedure
====
In order to combine the generation of export documents with the booking of outgoing items set up an event procedure. To do so, go to *System » Orders » Events*. For further information, refer to the <<basics/automation/event-procedures#, *Event procedures*>> page of the manual.
====

[.subhead]
Tracking URL for DHL

The currently valid, known tracking URL for DHL is: +
*+http://nolp.dhl.de/nextt-online-public/set_identcodes.do?lang=de&zip=$PLZ&idc=$PaketNr+*.

[#3000]
=== DHL plentymarkets Import

With the <<basics/automation/processes/procedures#340, *polling format*>> DHL plentymarkets Import, you can give DHL the task of carrying out a link:https://www.dhl.de/en/paket/information/geschaeftskunden/service-alterssichtpruefung.html[*visual age check*^] when delivering your items, such as liquids for e-cigarettes. Using this polling format, you generate a CSV file for data import to DHL. Upload the file in the DHL business portal in order to register shipments and receive labels. You will need to configure the DHL business portal in order to use this service in plentymarkets. The business portal also includes the reference numbers that you will need for setting up the tables of shipping charges in plentymarkets.

Carry out the settings described below to configure the DHL service *Visual age check*:

* Carrying out settings in the DHL business portal
* Creating a property
* Carrying out the basic setting
* Linking the property to items
* Selecting the shipping options
* Generating a CSV file and uploading it to DHL

[TIP]
.Orders with age limitations
====
If an order contains items with different age limitations, then the highest age limitation will apply to the entire order. For example, if one item has a 16+ rating and another item has an 18+ rating, then the 18+ rating will be used for the entire order.
====

[.subhead]
Carrying out settings in the DHL business portal

Carry out the settings in the link:https://www.dhl-geschaeftskundenportal.de/webcenter/portal/gkpExternal?_afrLoop=2465780077903302#!%40%40%3F_afrLoop%3D2465780077903302%26_adf.ctrl-state%3D11moofew5r_4[*DHL business portal*^].

[.subhead]
Creating a property

Go to *System » Item » Properties* and create a property of the type *Selection*. Save values for the different age restrictions. For example, create the values *A16* and *A18*. Enter a name for the property, e.g. visual age check.

Further information can be found in the chapter <<item/managing-items#500, *Creating properties*>> within the <<item#, *Items*>> topic.

[.subhead]
Carrying out the basic setting

Go to *System » Item » Basic settings* and select the property that you just created for the option *Item property for visual age check*. *Save* the settings.

[.subhead]
Linking the property to items

Open every item that should have a visual age check and save the property.

[.instruction]
Linking the property to items:

. Go to *Item » Edit item » Open item » Tab: Properties*.
. Activate the property that you have just created in the area *Activate further properties*.
. *Save* the settings. +
→ The property will be displayed in the *Properties* area.
. Select the value for the item from the drop-down menu according to the age rating as created above.
. *Save* the settings.

Further information can be found in the chapter <<item/managing-items#80, *Activating properties*>> within the <<item#, *Items*>> topic.

[.subhead]
Selecting the shipping options

The service *Visual age check* is available in the table of shipping charges.

[.instruction]
Select the shipping option:

. Go to *System » Orders » Shipping » Settings*.
. Click on the *Shipping profiles* tab.
. Open the DHL shipping profile.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. In the area *DHL plentymarkets Import*, select the option *DHL Paket* from the drop-down menu *Product*.
. Activate the option *Visual age check* under *Services*.
. *Save* the settings.

[.subhead]
Generating a CSV file and uploading it to DHL

Now generate a CSV file in the plentymarkets Client or in the *Orders » Shipping centre » Tab: Polling* menu. Save the file and upload it to the DHL business portal.

[#3100]
=== DHL Retoure with enclosed return labels

Use DHL Retoure with enclosed return labels to generate labels for orders that are shipped throughout Germany with DHL. Your customers receive a fully prepared return label with their delivery. If they choose to send an item back, e.g. because of a warranty or repairs, all they have to do is pack it and affix the label. The labels are created with the help of an event procedure. They can be found and printed in the shipping centre.

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Proceed as follows to set up the interface to link:https://www.dhl.de/en/paket/geschaeftskunden/ab-200-pakete/nationaler-versand/retoure.html[*DHL RETOURE with enclosed return labels*^] in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » DHL Retoure enclosed return labels*.
. Carry out the settings as desired. Pay attention to the information given in table 17.
. *Save* the settings.

.Settings for the DHL Retoure with enclosed return labels interface
[cols="a,a"]
|====
|Setting |Explanation

|*Recipient*
|Enter the recipient's data.

|*Accounting number*
|Enter the accounting number that you received from DHL.

|*Customer code*
|Enter the customer code that you received from DHL.

|*Barcode number sequence*
|Enter the data. Always enter three digits for the street code and house number. For example, enter 010 for the house number 10.

|*Service*
|Select a service.
|====

Set up an <<basics/automation/event-procedures#, *event procedure*>> to automatically generate return labels.

[.collapseBox]
.Setting up an event procedure
--
. Go to *System » Orders » Events*.
. Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
. Enter a name.
. Select the *event* listed in table 18.
. *Save* the settings.
. Carry out the settings as desired. Pay attention to the information given in table 18.
. Place a check mark next to the option *Active*.
. *Save* the settings.
--
.Event procedure for automatically generating return labels
[cols="a,a,a"]
|====
|Setting |Option |Selection

|*Event*
|*Order generation: New order*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order*; other types as needed, e.g. warranty, repair

|*Filter 2*
|*Shipping &gt; Country of delivery*
|*Germany*

|*Filter 3*
|*Order &gt; Order warehouse* (optional)
|

|*Filter 4*
|*Order &gt; Referrer* (optional)
|

|*Procedure 1*
|*Return &gt; Generate DHL return label*
|*DHL Retoure enclosed return labels*

|*Procedure 2*
|*Order &gt; Change status* (optional)
|
|
|====

[#3200]
=== DHL Retoure Online

DHL Retoure Online allows you to generate return labels for orders with various countries of delivery. The labels are generated in the menu *Orders » Shipping centre » Tab: Return*. They can be made available to end customers in the *My account* area of the online store.

You need to have a warehouse in order to save the information about returns that you receive from DHL. There are various types of warehouses in plentymarkets. The warehouse type *Repair* is especially well-suited for returns. The setting *Warehouse assigned for repair* in the *Settings » Stock » Warehouse » Open warehouse » Settings* menu allows you to assign repair warehouses to main warehouses of the type *Sales warehouse*. When a return label is generated later, the corresponding sales or repair warehouse will be used depending on which warehouse matches the order.

If you have not yet created a warehouse, then create a warehouse or a sales and repair warehouse in the *Settings » Stock » Warehouse* menu. How to create a warehouse is described on the <<stock-management/setting-up-a-warehouse#, *Warehouse*>> page of the manual.

[IMPORTANT]
.Available warehouse types for DHL Retoure Online
====
Only *sales* and *repair* warehouses can be used for DHL Retoure Online.
====

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Proceed as follows to set up the interface to link:http://www.dhl.de/en/paket/geschaeftskunden/ab-200-pakete/nationaler-versand/retoure.html[*DHL Retoure Online*^] in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » DHL Retoure Online*.
. Carry out the settings as desired. Pay attention to the information given in table 19.
. *Save* the settings.

.Settings for the DHL Retoure Online interface
[cols="a,a"]
|====
|Setting |Explanation

|*Portal ID, User name, Password*
|Enter the data that you received from DHL.

|*Validity of assigned labels*
|Select the validity duration of the assigned labels from the drop-down menu. +
Assigned labels are those that have already been assigned to a return. Once the selected time period has ended, the labels will no longer be available for download.

|*Validity of unassigned labels*
|Select the validity duration of the unassigned labels from the drop-down menu. Once the selected time period has ended, the labels will no longer be available for download.

|*Recipient of return*
|Expand the warehouse. Enter the country-specific settings as received from DHL. If you do not enter any information for a repair warehouse and you assign the repair warehouse to a sales warehouse, then the settings for the sales warehouse will be used by default. +
In other words, it is not absolutely necessary to enter information about the sales warehouse. Doing so is simply a safety precaution. The recipient of return matches the order warehouse. Only warehouses of the types *Sales* and and *Repair* are available.
|====

Now determine whether your customers should be allowed to create returns within their own account.

[.instruction]
Allowing customers to create returns:

. Go to *Settings » Client (store) » Select store » My Account » Basic settings*.
. Select one of the options from the *Return* drop-down menu. Pay attention to the information given in table 20.
. *Save* the settings.

.Allowing customers to create returns in the *Settings » Client (store) » Select store » My Account » Basic settings* menu
[cols="a,a"]
|====
|Setting |Explanation

|*Return*
|*activated* = Customers can create returns. However, labels will not be provided. You will need to decide how you want to proceed when customers return items. For example, you can send customers the label via email. +
If you allow customers to create returns themselves, then they will be able to choose the <<order-processing/orders/managing-sales-orders#return, *reason for return*>> in their *My account* area. +
*DHL Retoure Online* = Customers can create returns, then download and print the DHL return label. +
*deactivated* = Customers may not create returns. If you select this option, then you will need to decide how your company deals with returns. For example, you may require customers to call or send an email if they want to return an item.
|====

[#3300]
=== DHL Supply Chain

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Proceed as follows to set up the interface to link:http://www.dhl.de/en/logistik/supply-chain-loesungen.html[*DHL Supply Chain*^] in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » DHL Supply Chain*.
. Carry out the settings as desired. Pay attention to the information given in table 21.
. *Save* the settings.

.Settings for the DHL Supply Chain interface
[cols="a,a"]
|====
|Setting |Explanation

|*Sender ID, FTP host, FTP user, FTP password*
|Enter the data that you received from DHL.

|*Service*
|Select a service from the drop-down menu.
|====

Now carry out the shipping service provider-specific settings for the shipping services in the table of shipping charges. These services are only visible in the table of shipping charges after you have saved the settings in the shipping profile.

[.instruction]
Setting shipping service provider-specific services:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping service provider.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. In the area *DHL Supply Chain*, select the option *One-person handling* or *Two-person handling* from the drop-down menu in the line *DHL product*.
. *Save* the settings.

[#3400]
=== DHL UK

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Proceed as follows to set up the interface to link:http://www.dhl.co.uk/en.html[*DHL UK*^] in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » DHL UK*.
. Carry out the settings as desired. Pay attention to the information given in table 22.
. *Save* the settings.

.Settings for the DHL UK interface
[cols="a,a"]
|====
|Setting |Explanation

2+|Master data

|*Site ID*
|Enter the data that you received from DHL.

|*Password*
|Enter the password that you received from DHL.

2+|Shipper accounts

|*Billing information*
|Enter the billing information.

|*Shipper address*
|Enter the shipper address.
|====

[TIP]
.Adding shipper accounts
====
After you have entered and saved the data in the areas *Billing information* and *Shipper address* in the *System » Orders » Shipping » Shipping service provider » DHL UK* menu, a new tab will be added in the *Shipper accounts* area. This tab will be named according to the shipper account number that you have entered in the *Billing information* area. You may add as many shipper accounts as you like. This is done via the tab *New*.
====

Now carry out the shipping service provider-specific settings for the shipping services in the table of shipping charges. These services are only visible in the table of shipping charges after you have saved the settings in the shipping profile.

[.instruction]
Setting shipping service provider-specific services:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping service provider.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. Carry out the settings in the *DHL UK* area. Pay attention to the information given in table 23.
. *Save* the settings.

.DHL UK shipping services in the *Table of shipping charges* tab
[cols="a,a"]
|====
|Setting |Explanation

|*Shipper account number*
|Select a shipper account number from the drop-down menu.

|*Terms of trade*
|Select a shipper account number from the drop-down menu.
|====

[#3500]
=== DPD Cloud Webservice

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

[TIP]
.Automatic assignment of the registration date to the next business day
====
If the day the order is registered is not a valid business day for DPD, the next business day will be automatically selected. +
If you register the order via the shipping centre in the *Orders » Shipping centre » Tab: Register* menu, no date must be selected under *Shipped on*. Otherwise, the order cannot be assigned automatically to the next business day.
====

Proceed as follows to set up the interface to link:https://esolutions.dpd.com/entwickler/dpd-cloud-webservice.aspx[*DPD Cloud Webservice*^] in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » DPD Cloud Webservice*.
. Carry out the settings as desired. Pay attention to the information given in table 24.
. *Save* the settings.

.Settings for the DPD Cloud Webservice interface
[cols="a,a"]
|====
|Setting |Explanation

|*User ID*
|Enter the user ID as received from DPD.

|*User token*
|Enter the user token received from DPD.

|*Additional address information on label*
|Select whether the additional address information that was entered in the delivery address, will be displayed on the DPD shipping label. DPD limits the character length to 35. +
*Add behind name* = The additional address information will be displayed behind the name. +
*Display in reference 1* = The additional address information will be displayed under *Reference 1*. +
*Do not add* = No additional address information will be displayed.

|*Do not print email address on label*
|Activate the option if the email address should not be printed on the DPD shipping label.

|====

Now carry out the shipping service provider-specific settings for the shipping services in the table of shipping charges. These services are only visible in the table of shipping charges after you have saved the settings in the shipping profile.

[.instruction]
Setting shipping service provider-specific services:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping service provider.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. In the *DPD Cloud Webservice* area, select a service from the drop-down menu in the line *Shipping service*.
. *Save* the settings.

Pay attention to the information about the shipments that you will later register for DPD Cloud Webservice via the <<order-processing/fulfilment/shipping-centre#700, *shipping centre*>>. Go to *Data exchange » API log » Tab: Shipping centre API log* to view this information. For further information about API log entries for DPD Cloud Webservice, refer to the <<basics/data-exchange/api-log#, *API log*>> page of the manual.

[.subhead]
Tracking URL for DPD

The currently valid, known tracking URL for DPD is: +
*+https://tracking.dpd.de/parcelstatus?query=[PaketNr]&locale=de_DE+*.

[#3600]
=== DPD DELISprint

Before setting up the interface to DPD DELISprint in plentymarkets, register with link:https://www.dpd.com/portal_de[*DPD*^]. DPD customers can use the DPD DELISprint program to easily create DPD parcel labels.

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Proceed as follows to set up the interface to link:https://www.dpd.com/ch/home/esolutions/clientloesungen/delisprint_6[*DPD DELISprint*^] in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » DPD DELISprint*.
. Carry out the settings as desired. Pay attention to the information given in table 25.
. *Save* the settings.

.Settings for the DPD DELISprint interface
[cols="a,a"]
|====
|Setting |Explanation

|*Shipping method*
| +
*NP - normal package* = CLASSIC shipping of normal packages +
*SP - small package* = CLASSIC shipping of small packages +
*NCP - B2C Standard parcel* = commercial shipping of normal packages +
*SCP - B2C Small parcel* = commercial shipping of small packages

|*Flex/Predict active*
|Activate to register the notification service link:https://www.dpd.com/de/home/produkte_services/zusatzleistungen/national/predict[*Predict*^] (formerly FlexDelivery) with DPD. This service is subject to additional charges. If this option is chosen, the CSV file exported from plentymarkets will contain the additional information *PRO*.
|====

[TIP]
.Payment method cash on delivery
====
The cash on delivery service will automatically be selected for orders that use the payment method *Cash on delivery* and are shipped with DPD. No further settings are required.
====

[#3700]
=== EasyPAK

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Proceed as follows to set up the interface to link:https://www.post.at/en/business.php[*EasyPAK*^] in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » EasyPAK*.
. Carry out the settings as desired. Pay attention to the information given in table 26.
. *Save* the settings.

.Settings for the EasyPAK interface
[cols="a,a"]
|====
|Setting |Explanation

|*Sender reference No., Client reference No., IBAN*
|Enter the data that you received from EasyPAK.  +
If you use the payment method cash on delivery, then it is mandatory to enter the IBAN.
|====

Now carry out the shipping service provider-specific settings for the shipping services in the table of shipping charges. These services are only visible in the table of shipping charges after you have saved the settings in the shipping profile.

[.instruction]
Setting shipping service provider-specific services:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping service provider.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. Carry out the settings in the *PAT Easypak* area. Pay attention to the information given in table 27.
. *Save* the settings.

.EasyPAK shipping services in the *Table of shipping charges* tab
[cols="a,a"]
|====
|Setting |Explanation

|*Type of contract*
|Select the type of contract.

|*Products*
|Select the product.

|*Additional services*
|Select one or more additional services.
|====

[#3800]
=== GLS Germany

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Proceed as follows to set up the interface to link:https://gls-group.eu/DE/de/home[*GLS Germany*^] in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » GLS Germany*.
. Carry out the settings as desired. Pay attention to the information given in table 28.
. *Save* the settings.

.Settings for the GLS Germany interface
[cols="a,a"]
|====
|Setting |Explanation

|*International customer number, +
National customer number, Point of acceptance*
|Enter the data that you received from GLS.
|====

[.subhead]
Tracking URL for GLS

The currently valid, known tracking URL for GLS is: +
*+http://www.gls-group.eu/276-I-PORTAL-WEB/content/GLS/DE03/DE/5004.htm?txtRefNo=[PaketNr]&txtAction=71000+*.

[#3900]
=== Hermes (two-person handling)

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

While placing their orders, customers should be able to request that their items are assembled for them. You can offer customers such a service with link:https://www.hermesworld.com/de/unsere-dienstleistungen/distribution/2-mann-handling/2-mann-handling/[*Hermes (two-person handling)*^]. In order to use this service, create an order property. Create an order property with the options *Yes* and *No*. Depending on which *property type* you select, you will be able to configure the options that your customers will later select in your online store.

[TIP]
.Interface for existing customers only
====
The interface to Hermes 2-Mann-Handling (two-man handling) can only be used by existing customers. New customers are asked to contact link:https://www.hermesworld.com/en/about-us/hermes-group/hermes-einrichtungs-service/[*HERMES Einrichtungs Service GmbH &amp; Co.KG*^].
====

[.instruction]
Creating the assembly service as an order property:

. Go to *System » Item » Properties » Tab: New property*.
. Enter a name, e.g. assembly service.
. Activate the option *Order property*.
. Select the *Property type* called *Selection*. +
→ Additional options will be displayed.
. *Save* the settings. +
→ The property will be created.
. Click on the *Properties* tab and open the property that you just created.
. Enter *Yes* into the *Name* field underneath the property type.
. *Save* the settings. +
→ An additional name field will be displayed.
. Enter *No* into this name field.
. *Save* the settings.

Now link the order property with the item.

[.instruction]
Linking the property with the item:

. Go to *Item » Edit item*.
. Open the item.
. Click on the *Properties* tab.
. Activate the property that you have just created.
. *Save* the settings.

Customers who place this item in the shopping cart will be able to select the option *Yes* or *No* from a drop-down menu.

[IMPORTANT]
.Assembly service only available when shipping with Hermes
====
The order property is linked to the item and not to the shipping service provider. If more than one shipping method is saved for the item or if other shipping service providers besides Hermes are saved for the item, then you should insert a note into the online store, which tells customers that the assembly service is only for Hermes shipments.
====

Proceed as follows to set up the interface to Hermes (two-person handling) in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » Hermes (two-person handling)*.
. Carry out the settings as desired. Pay attention to the information given in table 29.
. *Save* the settings.

.Settings for the Hermes (two-person handling) interface
[cols="a,a"]
|====
|Setting |Explanation

|*Client No., FTP host, FTP user, FTP password*
|Enter the data that you received from Hermes.

|*Assembly service*
|Select the assembly service from the drop-down menu. This option is only visible if you have created the order property and linked it with the item.
|====

Now carry out the shipping service provider-specific settings for the shipping services in the table of shipping charges. These services are only visible in the table of shipping charges after you have saved the settings in the shipping profile.

[.instruction]
Setting shipping service provider-specific services:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping service provider.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. Carry out the settings in the *Hermes (two-person handling)* area. Pay attention to the information given in table 30.
. *Save* the settings.

.Hermes (two-person handling) shipping services in the *Table of shipping charges* tab
[cols="a,a"]
|====
|Setting |Explanation

|*Delivery type*
|Select *Standard service* or *48 hour service*.  +
It is useful to divide your shipping profiles into these two categories because shipping service providers typically tier their own prices based on these categories as well. This allows you to pass on the costs to your customers.
|====

[.subhead]
Tracking URL for Hermes

The currently valid, known tracking URL for Hermes is: +
*+http://myhermes.de/wps/portal/PRIPS_DEU/SISYR?auftragsNummer=[PaketNr]+*.

[#4000]
=== Hermes ProfiPaketService (professional parcel service)

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Proceed as follows to set up the interface to link:https://profipaketservice.hlg.de/wps/portal/PROPS_DEU/Home/Start/[*Hermes (ProfiPaketService)*^] in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » Hermes (ProfiPaketService (professional parcel service))*.
. Carry out the settings as desired. Pay attention to the information given in table 31.
. *Save* the settings.

.Settings for the Hermes (ProfiPaketService) interface
[cols="a,a"]
|====
|Setting |Explanation

2+|Master data

|*Access data*
|Enter the internal name, login name and password that you received from Hermes.

|*Invoice on graduated price*
|Confirm the Hermes terms and conditions and the notice about the limitation placed on the value of a package by placing the check marks.  The Hermes service will not be available for you without this confirmation. Click on the link to see the terms and conditions.

2+|Available products

|*Internal name, Package class, Max. package weight, Net price, Countries of delivery*
|The data received from Hermes via the interface is displayed here.
|====

[.subhead]
Tracking URL for Hermes

The currently valid, known tracking URL for Hermes is: +
*+http://myhermes.de/wps/portal/PRIPS_DEU/SISYR?auftragsNummer=[PaketNr]+*.

[#4100]
=== MyDPD Business / iloxx

The shipping service provider iloxx is now part of DPD and operates under the name DPD iloxx eService GmbH. However, this change does not affect existing iloxx interfaces in plentymarkets. The new interface is now called MyDPD Business / iloxx.

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Proceed as follows to set up the interface to link:http://www.dpd.iloxx.de/home.aspx[*MyDPD Business / iloxx*^] in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » MyDPD Business / iloxx*.
. Enter the *User ID* and *User token* that you received from MyDPD Business / iloxx.
. *Save* the settings.

Now carry out the shipping service provider-specific settings for the shipping services in the table of shipping charges. These services are only visible in the table of shipping charges after you have saved the settings in the shipping profile.

[.instruction]
Setting shipping service provider-specific services:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping service provider.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. In the *MyDPD Business/iloxx* area, select a service from the drop-down menu in the line *Shipping service*.
. *Save* the settings.

[TIP]
.Printing shipping labels
====
You will be able to print the shipping label once the order has reached status *[5] Cleared for shipping*. This is done in the shipping centre within the *Label* tab. Shipping labels are generated in DIN A-6 format.
====

[.subhead]
Tracking URL for DPD

The currently valid, known tracking URL for DPD is: +
*+https://tracking.dpd.de/parcelstatus?query=[PaketNr]&locale=de_DE+*.

[#4200]
=== NetDespatch

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Proceed as follows to set up link:http://www.royalmail.com/[*Royal Mail*^] and link:https://www.ukmail.com/[*UK Mail*^] via the integrated link:http://www.netdespatch.com/[*NetDespatch*^] interface in your plentymarkets system.

[#4210]
==== Royal Mail

Proceed as follows to set up the interface to set up link:http://www.royalmail.com/[*Royal Mail*^] via the integrated link:http://www.netdespatch.com/[*NetDespatch*^] interface in your plentymarkets system.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » NetDespatch*.
. Expand the *Royal Mail settings* area.
. Carry out the settings as desired. Pay attention to the information given in table 32.
. *Save* the settings.

.Settings for the NetDespatch (Royal Mail) interface
[cols="a,a"]
|====
|Setting |Explanation

2+|Domestic

|*Interface active*
|Place a check mark to activate the interface.

|*Mode*
|Select *Trial version* or *Productive system*.

|*User name*
|Enter the user name.

|*Password*
|Enter the password.

2+|International

|*Interface active*
|Place a check mark to activate the interface.

|*Mode*
|Select *Test system* or *Productive system*.

|*User name*
|Enter the user name.

|*Password*
|Enter the password.

2+|Royal Mail account ID

|*Account ID*
|Enter the account ID.
|====

Now carry out the shipping service provider-specific settings for the shipping services in the table of shipping charges. These services are only visible in the table of shipping charges after you have saved the settings in the shipping profile.

[.instruction]
Setting shipping service provider-specific services:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping service provider.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. Carry out the settings in the *NetDespatch* area. Pay attention to the information given in table 33.
. *Save* the settings.

.NetDespatch (Royal Mail) shipping services in the *Table of shipping charges* tab
[cols="a,a"]
|====
|Setting |Explanation

|*Shipping service provider*
|Select *Royal Mail* from the drop-down menu.

|*Shipping area*
|Select *Royal Mail International* or *Royal Mail Domestic* from the drop-down menu.

|*Product group*
|Select a product group from the drop-down menu.

|*Shipping service*
|Select a shipping service from the drop-down menu. Depending on the selected shipping service, the corresponding code under *Service code* will be displayed automatically in the next line.

|*Service code*
|Depending on the shipping service selected in the previous line, the service code will be displayed here.

|*Non-delivery instruction*
|Select an option from the drop-down menu. The drop-down menu will only be displayed when you selected the setting *Royal Mail International* under *Shipping area*. The selected option determines how to proceed when the package cannot be delivered. In case of CN23 forms, selecting an option is mandatory.
|====

[#4230]
==== UK Mail

Proceed as follows to set up the interface to set up link:https://www.ukmail.com/[*UK Mail*^] via the integrated link:http://www.netdespatch.com/[*NetDespatch*^] interface in your plentymarkets system.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » NetDespatch*.
. Expand the area *UK Mail settings*.
. Carry out the settings. Pay attention to the information given in table 34.
. *Save* the settings.

.Settings for the NetDespatch (UK Mail) interface
[cols="a,a"]
|====
|Setting |Explanation

2+|Domestic

|*Interface active*
|Place a check mark to activate the interface.

|*Mode*
|Select *Trial version* or *Productive system*.

|*User name*
|Enter the user name.

|*Password*
|Enter the password.

2+|UK Mail account ID

|*Account ID*
|Enter the account ID.
|====

Now carry out the shipping service provider-specific settings for the shipping services in the table of shipping charges. These services are only visible in the table of shipping charges after you have saved the settings in the shipping profile.

[.instruction]
Setting shipping service provider-specific services:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping service provider.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. Carry out the settings in the *NetDespatch* area. Pay attention to the information given in table 35.
. *Save* the settings.

.NetDespatch (UK Mail) shipping services in the *Table of shipping charges* tab
[cols="a,a"]
|====
|Setting |Explanation

|*Shipping service provider*
|Select *UK Mail* from the drop-down menu.

|*Shipping area*
|Select *Domestic* from the drop-down menu.

|*Product group*
|Select the product group from the drop-down menu.

|*Shipping service*
|Select the shipping service from the drop-down menu. Depending on the selected shipping service, the corresponding code under *Service code* will be displayed automatically in the next line.

|*Service code*
|Depending on the shipping service selected in the previous line, the service code will be displayed here.

|*Non-delivery instruction*
|This option is only relevant in case of international shipments and is therefore not available for UK Mail.
|====

[#4250]
=== Parcelforce Worldwide

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Proceed as follows to set up the interface to link:http://www.parcelforce.com/[**Parcelforce Worldwide**^] in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » Parcelforce Worldwide*.
. Enter the contract number.
. *Save* the settings.

Now carry out the shipping service provider-specific settings for the shipping services in the table of shipping charges. These services are only visible in the table of shipping charges after you have saved the settings in the shipping profile.

[.instruction]
Setting shipping service provider-specific services:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping service provider.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. Carry out the settings in the *Parcelforce Worldwide* area. Pay attention to the information given in table 36.
. *Save* the settings.

.Parcelforce Worldwide shipping services in the *Table of shipping charges* tab
[cols="a,a"]
|====
|Setting |Explanation

|*Service*
|Select a service from the drop-down menu.

|*Additional service*
|Select an additional service from the drop-down menu. Currently, the option *Saturday delivery* is available.

|*Enhanced compensation*
|Select an option from the drop-down menu.
|====

[#4300]
=== Swiss Post

Before setting up the interface to link:https://www.post.ch/de/geschaeftlich/themen-a-z/swiss-post-gls[*Swiss Post*^] in plentymarkets, register with Swiss Post.

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Set up a technical user for Swiss Post. You need the web service barcode to do so. Request this web service from the Swiss Post as it is not available by default. This web service is free of charge. The web service will become available after a few days and you can then set up the technical user.

Proceed as follows to set up the interface to Swiss Post in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » Swiss Post*.
. Carry out the settings as desired. Pay attention to the information given in table 37.
. *Save* the settings.

.Settings for the Swiss Post interface
[cols="a,a"]
|====
|Setting |Explanation

|*Swiss Post user, Swiss Post password, Franking license No.*
|Enter the data that you received from Swiss Post.

|*Cash on delivery amount*
|Select *Starting with the first shipping package* or *Split into different shipping packages*.

|*Use new web service endpoint*
|Select *YES*. Our interface has been adapted to reflect modifications made by Swiss Post. All customers will receive new access data. Enter the access data here. Please contact Swiss Post in case of problems with the new configuration.
|====

Now carry out the shipping service provider-specific settings for the shipping services in the table of shipping charges. These services are only visible in the table of shipping charges after you have saved the settings in the shipping profile.

[.instruction]
Setting shipping service provider-specific services:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping service provider.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. Carry out the settings as desired. Pay attention to the information given in table 38.
. *Save* the settings.

.Swiss Post shipping services in the *Table of shipping charges* tab
[cols="a,a"]
|====
|Setting |Explanation

|*Service group*
|Select the service group from the drop-down menu in the *Swiss Post* area. Depending on which service group is selected, further settings will appear. +
*_Important_*: You will not be able to select a service group until you have set up the technical user.

|*Validation*
|Click on *Execute*. The selected values will be validated by Swiss Post.
|====

[#4400]
=== UPS

How you set up shipping service providers and shipping profiles and which additional settings you have to carry out and may carry out, is described in the chapters from <<order-processing/fulfilment/preparing-the-shipment#100, *Setting up countries of delivery*>> through <<order-processing/fulfilment/preparing-the-shipment#2400, *Retrieving the API log*>>. The settings described there are the basic requirements in order to carry out the settings that are specific for each shipping service provider. Therefore, first carry out the settings in the chapters mentioned above. Afterwards, continue with this chapter.

Proceed as follows to set up the interface to link:https://www.ups.com/one-to-one/register?sysid=myups&loc=de_DE&WT.svl=Footer[*UPS*^] in plentymarkets.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Shipping service provider » UPS*.
. Carry out the settings as desired. Pay attention to the information given in table 39.
. *Save* the settings.

.Settings for the UPS interface
[cols="a,a"]
|====
|Setting |Explanation

|*UPS user, UPS password, UPS customer number, Access key*
|Enter the data that you received from UPS.

|*Login*
|Select how shipping orders with multiple packages should be registered with UPS. +
*Register all together* = All packages will be registered together and will reach the recipient at the same time. +
*_Important_*: The setting *Register all together* is mandatory for cash on delivery orders with multiple packages. +
*Register separately* = Every shipping package will be registered as a separate shipping order. The recipient may receive the packages at different times.
|====

[IMPORTANT]
.Payment method cash on delivery
====
Only checks are allowed for cash on delivery shipping carried out by UPS. If you do not want to allow checks to be used, deactivate the payment method cash on delivery within the UPS shipping profile. Cash on delivery shipments will not be registered with UPS.
====

[WARNING]
.Include the recipient's telephone number for international packages
====
Include the recipient's telephone number on all packages that are being shipped to other countries.
====

Now carry out the shipping service provider-specific settings for the shipping services in the table of shipping charges. These services are only visible in the table of shipping charges after you have saved the settings in the shipping profile.

[.instruction]
Setting shipping service provider-specific services:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open the shipping service provider.
. Click on the *Table of shipping charges* tab.
. Expand the region.
. Carry out the settings in the *UPS Service* area. Pay attention to the information given in table 40.
. *Save* the settings.

.UPS shipping services in the *Table of shipping charges* tab
[cols="a,a"]
|====
|Setting |Explanation

|*Api Service*
|Select a shipping method from the drop-down menu.

|*alternative telephone number*
|Enter an alternative telephone number.
|====

[.subhead]
Tracking URL for UPS

The currently valid, known tracking URL for UPS is: +
*+http://wwwapps.ups.com/WebTracking/track?track=yes&trackNums=[PaketNr]&loc=de_de+*.

[#4500]
== Setting up an DHL Packstation

DHL runs a network of Packstations that are accessible any time of the day. Customers can choose to activate or enter a DHL Packstation or DHL post office as the delivery address. Carry out the settings for the DHL Packstation in the *Settings » Client (store) » Standard » Order process » DHL Packstation* menu.

A Packstation can only be entered as the delivery address.

[.instruction]
Setting up a DHL Packstation:

. Go to *Settings » Client (store) » Standard » Order process » DHL Packstation*.
. Carry out the settings as desired. Pay attention to the information given in table 41.
. *Save* the settings.

.Options for DHL Packstations
[cols="a,a"]
|====
|Setting |Explanation

|*Permit Packstation as the delivery address*
|Select whether entering a Packstation in a delivery address in your online store should generally be allowed or not. If this option is set to YES, which means it is activated, then the DHL Postfinder is also available for your online store. The Postfinder makes it possible for your customers to search for Packstations and post offices in the delivery address forms. +
For further information about configuring Postfinder, refer to the <<order-processing/fulfilment/preparing-the-shipment#4600, *Setting up the DHL Postfinder*>> chapter.

|*Maximum order value for Packstation*
|Enter the maximum order value that is permitted. If the maximum order value is exceeded, then the online store visitor will receive an error message when trying to place an order. +
*_Important_*: The default entry 0.00 stands for no limitation.

|*Packstation validation*
|Select whether DHL Packstations should be validated (active) or not (inactive). The data synchronisation that is carried out during the validation offers even more security and fraud protection. The customer's address data (invoice address and email address) are compared with the PostNummer. An error message will be displayed if the PostNummer does not match the customer or if the customer has been blocked.

|*Ask for PostNummer in address data*
|In the online store, customers can also enter their PostNummer for the DHL service *Postfinder*. Select whether customers should be asked to enter their PostNummer during the order process. +
The texts that are displayed in the order process are saved in the *Customer registration*, *Invoice address* and *Delivery address* submenus of the *CMS » Web design » Order process » Checkout* menu.
|====

[WARNING]
.Invoice address
====
A valid invoice address has to be saved for the customer. The Packstation data will be compared to the invoice address data. +
This way only Packstations that the person in the invoice address is registered for can be entered as delivery address. +
*Exception*: This does not apply to the order processing: You can save delivery addresses here. These addresses will not be validated.
====

Once you have set the option *Permit Packstation as the delivery address* to *YES*, both the customer and seller can enter a Packstation as the delivery address. The customer can select a Packstation in the online store and the seller can select a Packstation in the admin area.

[.instruction]
Entering the Packstation as the delivery address:

. Go to *Customers » Edit customers*.
. Open the customer whose delivery address you want to replace by a Packstation.
. Click on the *Delivery addresses* tab.
. Click on *Edit delivery address*.
. Click on *DHL Packstation*.
. Enter the PostNummer, Packstation, Postcode and town of the Packstation.
. *Save* the settings.

[#4600]
== Setting up the DHL Postfinder

This feature shows your customer a list of post offices and Packstations nearby. The list is displayed when your customer enters his or her postcode in the My account area or during the <<omni-channel/online-store/cms#web-design-editing-the-web-design-order-process-checkout, *checkout*>> process. You will then be able to use the address of a post office or Packstation directly in the delivery address.

In order to use DHL Postfinder, you must carry out settings in multiple menus. These settings are summarised on the <<omni-channel/online-store/cms#web-design-editing-the-web-design-order-process-dhl-postfinder, *DHL Postfinder*>> page of the manual.

[#4700]
== Overview of the fulfilment service providers

In plentymarkets, sellers can entrust their logistics processes to external service providers, who manage all or part of the stock and then report the status back to your plentymarkets system. These service providers also ship the item to your customers. And that all takes place automatically, without you having to do a lot. In plentymarkets you can also organise the storage of items in your own warehouses and the shipping via different service providers.

Table 42 lists all of the fulfilment service providers available in plentymarkets. Click on the service provider in the table to jump to the sub-chapter where the specific settings of the fulfilment service provider are described.

.Overview of the fulfilment service providers
[cols="a,a"]
|====
|Setting |Explanation

|<<order-processing/fulfilment/preparing-the-shipment#4800, *DHL Fulfillment*>>
|For sellers within Germany. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#5400, *IDS Logistik*>>
|For sellers within Germany. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#5500, *iLOPACK*>>
|For sellers within Germany. Shipping: international.

|<<order-processing/fulfilment/preparing-the-shipment#5600, *Fulfilment by Amazon*>>
|For sellers within Germany. Shipping: international.
|====

[#4800]
=== DHL Fulfillment

This chapter describes how to set up link:http://www.dhl.de/fulfillment[*DHL Fulfillment*^] in plentymarkets. Set up special warehouses, order statuses and reasons for return before you set up the interface. To do so, proceed as follows.

[IMPORTANT]
.Klarna orders will not be transferred to DHL Fulfillment
====
Currently, it is not possible to transfer orders that are paid with <<order-processing/payment/klarna#, *Klarna*>> to DHL Fulfillment. Only orders with a valid invoice can be transferred to DHL Fulfillment. However, Klarna only transmits the invoice to plentymarkets after outgoing items have been booked.
====

Registering the shipment with DHL Fulfillment takes place automatically via the interface. The *Data exchange » API log* menu contains information about shipments that were registered with DHL Fulfillment. For further information about API log entries for DHL Fulfillment, refer to the <<basics/data-exchange/api-log#, *API log*>> page of the manual.

[#4900.subhead]
Creating warehouses for DHL Fulfillment

First, go to *Settings » Stock » Warehouse* and create warehouses for the items processed by DHL Fulfillment. Enter the same name for all warehouses, e.g. DHL Fulfillment. Select these warehouses as the main warehouses for items that are processed by DHL Fulfillment. To do so, go to *Item » Edit item*, open the item and select the main warehouse in the *Shipping* area. For further information about creating warehouses, refer to the <<stock-management/setting-up-a-warehouse#, *Setting up a warehouse*>> page of the manual.

The following *warehouse types* can be used for configuring DHL Fulfillment:

* *Sales*
* *Storage*
* *Repair*
* *Other*

In order for the DHL Fulfillment interface to work correctly, you need at least one warehouse of the type *Sales* with *DHL Fulfillment* as the logistics type. You can create up to 4 warehouses. DHL assigns the warehouses according to the stock types that they use. For example, DHL assigns stock of the stock type *Prime Selection* to the Sales warehouse. These items are meant to be sold directly. Items with the stock type *Second Quality* are not meant to be sold and need a separate warehouse, e.g. the *Storage* warehouse. If these items were checked and are able to be sold, then they will be assigned to the stock type *Prime Selection* and moved to the Sales warehouse.

[WARNING]
.Warehouse assignment by DHL
====
DHL assigns stock to the warehouses that you created for DHL Fulfillment. Do not change any of the stocks that are intended for DHL Fulfillment.
====

DHL Fulfillment uses the following stock types:

* *Prime Selection*: First choice, intended for sale, assigned to sales warehouse
* *Second Quality*: Second choice, not intended for sale, assigned to storage warehouse
* *Damaged*: Damaged items, not intended for sale, assigned to repair warehouse
* *Blocked* and *Clearing*: Blocked items and items that need to be checked, not for sale, assigned to an extra warehouse (warehouse type: Other)

Damaged items can be returns but also items that were damaged while being moved within the warehouse or that were already damaged when they were delivered.

If you create reorders for your items in the *Stock » Reorder management » Reorders* menu, make sure that the reorder is in *Status [2] Confirmed*. Only if the reorder is in this status can it be transmitted to DHL Fulfillment. For further information about reorders, refer to the <<order-processing/orders/managing-sales-orders#, *Managing reorders*>> page of the manual.

[#5000.subhead]
Setting up order statuses

Go to *System » Orders » Order status* and set up two <<order-processing/orders/managing-sales-orders#order-status, *order statuses*>> for the orders transferred to DHL Fulfillment. Below are two examples:

* [6.5] Currently being shipped by fulfilment service provider +
→ For correctly registered orders

* [5.6] Error with fulfilment service provider +
→ For orders which could not be processed by DHL Fulfillment because of incorrect order details. Example: Item master data was not yet transferred to DHL Fulfillment.

[TIP]
.Orders in status 5.x
====
An order will automatically be transferred to DHL Fulfillment if the order is in *status 5.x* and an invoice was created for the order. The transfer interval is about every 15 minutes. The only exception is the order status that is used for the option *Order status in case of error*. Orders will not be transferred to DHL Fulfillment if they are in this status.

The *Data exchange » API log* menu contains information about shipments that were registered with DHL Fulfillment. For further information about API log entries for DHL Fulfillment, refer to the <<basics/data-exchange/api-log#, *API log*>> page of the manual.
====

If you want to create a specific workflow for processing DHL Fulfillment orders, then you should also create another status, e.g. *5.4 Preparation for fulfilment service provider* to separate DHL Fulfillment orders from other orders even before they are transferred to DHL.

[#5100.subhead]
Creating reasons for returns

If you want returns from DHL Fulfillment to be imported into your plentymarkets system, then you need to create reasons for the returns. Go to <<order-processing/orders/managing-sales-orders#return, *System » Orders » Order types » Return*>> to create reasons for returns. Then link the reasons that you created with the reasons given by DHL Fulfillment in the *System » Orders » Shipping » Fulfillment » DHL Fulfillment* menu.

[#5200.subhead]
Setting up the interface

In the interface settings, you will enter your login details, assign the order statuses and link the reasons for return.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Fulfillment » DHL Fulfillment*.
. Carry out the settings as desired. Pay attention to the information given in table 43.
. *Save* the settings.

.Settings for the DHL Fulfillment interface
[cols="a,a"]
|====
|Setting |Explanation

|*Interface active*
|Place a check mark to activate the interface. Do not activate the interface until you have configured the warehouses as described above.

|*Client designation*
|Enter the DHL Fulfillment client designation, i.e. the customer number.

|*FTP access*
|Use the test mode before you begin using the interface productively. In order to test the interface, select the option *Test mode* and enter the access data as received from DHL. The login details are different for the test mode and the productive mode. +
You will receive the login details for the productive mode once you have successfully completed the test mode. If you select the option *Productive mode*, then the check box *Delete test data* will be displayed. Activate if you want the test data to be deleted.

|*FTP login*
|Enter the login name for the FTP directory.

|*FTP password*
|Enter the password for the FTP directory.

|*Order status after notification*
|Select the order status that is to be used for the notification to DHL Fulfillment. +
*_Important*_*: The order status that has been selected here has an impact on the registration of new orders to DHL Fulfillment. This means that new orders with this status will not be taken into consideration upon registration.

|*Order status in case of error*
|Select the order status that is to be used for errors.

|*Product number format*
|Select which product number should be transferred to DHL Fulfillment. +
*SKU* = (default setting) The SKU is composed of the item ID, the price ID and the variation ID. +
*Variation number* = Select this setting if you are already using a different software to work with DHL Fulfillment and you want the stock listed in this software to be represented correctly in plentymarkets.

|*Product name*
|Select *Item name;Attribute;Variation* (default setting) or *Variation name*. This product name will then be transferred to DHL Fulfillment.

|*Expiration date, Original packaging, Fragile, Serial number*
|Select the properties that you created for transferring these item characteristics to DHL Fulfillment. For further information, refer to the <<order-processing/fulfilment/preparing-the-shipment#5300, *Transferring properties to DHL Fulfillment*>> chapter.

|*Reasons for return*
|Link the reasons for return that you created under <<order-processing/orders/managing-sales-orders#return, *System » Orders » Order types » Return*>> with the reasons given by DHL Fulfillment.
|====

[#5300.subhead]
Transferring properties to DHL Fulfillment

Transfer item characteristics such as "Fragile" or "Original packaging" to DHL Fulfillment if you want items to be handled or shipped in a certain way. The following item characteristics can be saved:

* *Expiration date*: The item will be stored in the warehouse with a mandatory expiration date. This function is controlled with the WMS options. Items that have this property also need to have an expiration date saved when recording new incoming items.
* *Original packaging*: The items will be shipped individually in their original packaging.
* *Fragile*: Additional packaging materials will be used when the item is boxed up. This function is controlled with the WMS options.
* *Serial number*: The serial number is scanned while the item is boxed up. DHL Fulfillment transmits this serial number to plentymarkets along with the shipping confirmation so that the serial number can be printed on the invoice and can be used by customers (e.g. for documentation, coupons).

Go to *System » Item » Properties*. Create the properties *Expiration date*, *Original packaging* and *Fragile* in your system. Assign them to the property type *No*. Create the property *Serial number* and assign it to the property type *Selection*. Give it the following three values: *SN* (Used for scanning an item's serial numbers), *SNK* (Used for scanning ranges of serial numbers per item) and *SNK2* (Used for scanning ranges of serial numbers per order item).

After you have created the properties, link these properties to items within the item's *Properties* tab. Finally, go to *System » Orders » Shipping » Fulfillment » DHL Fulfillment* and use the drop-down menus to select the properties that you created. Further information can be found in the <<item/managing-items#500, *Creating properties*>> chapter within the <<item#, *Items*>> topic.

Before transmitting the order to DHL Fulfillment, the recipient's address will be checked with respect to a valid form and structure; i.e. plentymarkets will check for example if all mandatory fields such as the name have been filled out. +
If the address contains faulty HTML signs and/or invalid signs that will not be accepted by the API, these signs will be corrected. If, however, the address contains an error that cannot be corrected, the order will not be transmitted. This will prevent a disturbance within the process since DHL Fulfillment cannot retrieve invalid and/or faulty XML files from the FTP server.

[#5400]
=== IDS Logistik

Before setting up the interface to IDS Logistik in plentymarkets, register with link:http://www.ids-logistik.de[*IDS Logistik*^].

Then create the fulfilment service provider in the *System » Orders » Shipping » Settings » Tab: Shipping service provider* menu. Select *Others* from the *Shipping service provider* drop-down menu. Further information can be found in the chapter <<order-processing/fulfilment/preparing-the-shipment#800, *Creating a shipping service provider*>>.

Afterwards, you create the shipping profile in the *System » Orders » Shipping » Settings* menu. Carry out the settings as described in the chapter <<order-processing/fulfilment/preparing-the-shipment#1000, *Creating a shipping profile*>>.

Proceed as follows to set up the interface to IDS Logistik.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Fulfillment» IDS Logistik*.
. Carry out the settings as desired. Pay attention to the information given in table 44.
. *Save* the settings.

.Settings for the IDS Logistik interface
[cols="a,a"]
|====
|Setting |Explanation

|*Depot number, standard 800*
|Enter the depot number that you received from IDS Logistik. Standard: 800

|*Sender customer number, field: SCN (four-digit)*
|Enter the four-digit sender customer number.

|*Shipment number (four-digit)*
|Enter the four-digit shipment number that you received from IDS Logistik.

|*Delivery note number*
|Decide whether the delivery note number should be transferred. If it should, then specify which value should be used. +
Select one of the following options: +
*Item ID +
Item number +
External item ID +
Do not transfer +
[Free text field 1 to 20]*

|*Content*
|Decide whether the content should be transferred. If it should, then specify which value should be used. +
Options: +
*Item ID +
Item number +
External item ID +
Do not transfer +
[Free text field 1 to 20]*

|*Recipient customer number, field: CN*
|Select the recipient's *customer number* or *order number*.

|*Transferred items (maximum 99)*
|Enter the number of items that should be transferred (maximum 99).

|*Key for note 1 / 2*
|Decide which (if any) note should be transferred to IDS Logistik.

|*Order type*
|Select *Courier collection* or *Delivery order*.

|*Transfer mobile phone numbers*
|Decide whether the recipient's mobile phone number should be transferred to IDS Logistik or not.

|*Number of digits for order No., min. 16*
|The order number is exported in a CSV file from the <<order-processing/fulfilment/generating-documents#200, *list of delivery addresses*>>. It includes the following parameters: +
-IDS specific ID (3 digits) +
- Customer number (4 digits) +
- plentymarkets order number (6 digits) +
- Number of colli (2 digits) +
- Check digit (1 digit) +
*Example*: 800 6913 000001 00 0 +
16 is entered by default. This number of digits is adequate for a 6-digit order number. +
Enter a higher value if the number of digits is not sufficient. Enter e.g. 17 if you use a 7-digit order number.
|====

[#5500]
=== iLOPACK

Before setting up the interface to iLOPACK in plentymarkets, register with link:http://www.ilopack.de/[*iLOPACK*^].

Then create the fulfilment service provider in the *System » Orders » Shipping » Settings » Tab: Shipping service provider* menu. Select *Others* from the *Shipping service provider* drop-down menu. Further information can be found in the chapter <<order-processing/fulfilment/preparing-the-shipment#800, *Creating a shipping service provider*>>.

Afterwards, you create the shipping profile in the *System » Orders » Shipping » Settings* menu. Carry out the settings as described in the chapter <<order-processing/fulfilment/preparing-the-shipment#1000, *Creating a shipping profile*>>.

Proceed as follows to set up the interface to iLOPACK. Below the table, it is described how to set up the data transfer to iLOPACK.

[.instruction]
Setting up the interface:

. Go to *System » Orders » Shipping » Fulfillment» iLopack*.
. Carry out the settings as desired. Pay attention to the information given in table 45.
. *Save* the settings.

.Settings for the iLOPACK interface
[cols="a,a"]
|====
|Setting |Explanation

|*iLopack user ID*
|Enter the user ID that you received from iLopack.

|*Default warehouse*
|Select a default warehouse for orders that you ship with iLopack.

|*Filter by main warehouse*
|Activate if an item will only be included if the warehouse that was selected as default warehouse is this item's main warehouse.
|====

[.subhead]
Setting up data transfer to iLOPACK

In the *Orders » Fulfilment » ilopack data transfer* menu, you set up the data transfer to the fulfilment service provider iLOPACK. During data transfer, CSV files will be generated for iLOPACK. These files will be automatically saved in a folder on the FTP server. iLOPACK can then access this folder.

[.instruction]
Setting up data transfer to iLOPACK:

. Go to *Orders » Fulfilment » ilopack data transfer*.
. Carry out the settings as desired. Pay attention to the information given in table 46.
. Click on the gear-wheel icon to generate the CSV file.

.Settings in the *Orders » Fulfilment » ilopack data transfer* menu
[cols="a,a"]
|====
|Setting |Explanation

|*Data*
|Select whether *Orders* or *Item master data* should be transferred.

|*Client (store)*
|Select a client (store) or select the option *ALL*.

|*Order status*
|Select the order status of the data that you would like to export.

|*Warehouse*
|Select one of the warehouses or select the option *ALL*.

|*Change order status*
|Select the order status that you want the data to change to after the data transfer.
|====

[#5600]
=== Fulfilment by Amazon

The abbreviation FBA stands for Fulfilment by Amazon, a service from Amazon where Amazon takes care of the entire stock management and logistics. Refer to the chapter <<omni-channel/multi-channel/amazon#3300, *Using the FBA service by Amazon*>> on the <<omni-channel/multi-channel/amazon#, *Amazon*>> page of the manual. This chapter describes which settings you need to carry out.

== Amazon Prime

Use filters to make sure that orders with shipping conditions for Amazon Prime will be separately treated in plentymarkets. Furthermore, you can create shipping labels for Amazon Prime orders via the Amazon Merchant Fulfilment API. Refer to the chapter <<omni-channel/multi-channel/amazon#4200, *Editing Amazon Prime orders*>> on the <<omni-channel/multi-channel/amazon#, *Amazon*>> page of the manual. This chapter describes which settings you need to carry out.
