= Vorstellung von ElasticSync
:lang: de
include::{includedir}/_header.adoc[]
:position: 10
:url: videos/datenuebernahme/einstieg/vorstellung-elasticsync

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|Was ist ElasticSync? Und was hat das Ganze mit Kommunikation zu tun? Dieses Einführungsvideo erklärt dir, was Kommunikation mit dem Im- und Export von Daten zu tun hat. Schaue dir also auch die übrigen Videos zum Thema an, um mehr über ElasticSync zu erfahren!
|<<videos/datenuebernahme/einstieg/vorstellung-elasticsync#video, Vorstellung von ElasticSync (1:29)>>
|===
//end::einleitung[]

video::321725010[vimeo]

// tag::transkript[]
[.collapseBox]
.Transkript
--
Auf einige Dinge im Online-Handel hast Du als Händler leider
keinen Einfluss.

Grafik 01 - Eine Kugel rollt ins Bild rein und werft den Stapel über einen
Haufen.

Beispielsweise auf die Inflation.
Hin und wieder erhöhen deine Lieferanten deshalb die Preise
um das ein oder andere Prozent.

Grafik 01 - Auf die Kugel erscheint vielleicht ein Pfeil nach oben oder 2% Und dann ist es eben deine Aufgabe die Einkaufspreise
anzupassen um dieser Preiserhöhung gerecht zu werden.
Fade to CSV file Genau jetzt wirst du es wahrscheinlich mit einer Tabelle zu
tun bekommen, die du entweder selber erstellt oder von
deinem Lieferanten gesendet bekommen hast.

Put cursor in supplier item number field
Link einblenden - Not realistic? This bare-bones example helps you learn the
basic concept. See more realistic examples once you know the basics.

In jedem Fall enthält die Datei deines Lieferanten so wichtige
Informationen wie die Artikel-ID...
Put cursor in item name field ...den Artikelname...
Put cursor in EK field ...und den neue Einkaufspreis.
Fade to plenty with ElasticSync menu already open Die Daten selber kannst du ganz einfach mit einem Sync in

dein System importieren...

Mouseover "Data > ElasticSync" ...in dem du das ElasticSync-Menü öffnest.
Click on plus icon ...und diesen Button klickst.

Grafik 02 - Stichpunktliste
Tell us about your file
Find and update the items
Start the import

In diesem Video teilen wir die Konfiguration eines Syncs in
drei einfache Schritte auf:
Zunächst werden grundlegende Einstellung zur Verarbeitung
der CSV-Datei hinterlegt.
Danach legen wir fest, welche Elemente in das System
importiert und welche Informationen aktualisiert werden.
Abschließend wird der Import gestartet.

Enter name "SupplierName - new purchase prices"
Flag 1 einblenden

Soweit so gut.
Zuerst legen wir den Sync selber an und geben ihm einen
sinnvollen Namen.

Open "Type" drop-down Anschließend gibst du an, welcher Datentyp importiert

werden sollen.

Select "Items" Wir wollen ja den Einkaufspreis aktualisieren. Dafür wählen

wir den Typ Artikel.

Callout "import" on right side Als nächstes stellst du hier auf der rechten Seite ein...
Overlay - CSV file ist links zu sehen ...wie die Datei aufgebaut ist, die du in dein System

importieren willst.

Mouseover "Header row included"
Overlay - Header line is highlighted (image above without rows 1-3)

Du gibst zum Beispiel an, ob deine Tabelle eine Kopfzeile
hat...

Uncheck "Header row included"
Overlay - Header line disappears (image above without rows 1-4)

...oder nicht.

Enter "Start at line" = 4
Overlay - First three lines of file are irrelevant (see image above)

Mit dieser Option kannst du festlegen, ab welcher Zeile die für
den Import relevanten Daten in der Datei hinterlegt sind.

Open "Data type" drop-down
Overlay - Save as CSV file pop-up

Und weiter gehts.
Hier legst du dann fest, um welchen Datentypen es sich bei
deiner Tabelle handelt.

Select "CSV" Aktuell ist es nur möglich csv-Dateien ins System zu
importieren. In Zukunft wird es aber auch möglich sein
xml-Dateien zu importieren.

Open "Charset" drop-down
Overlay - Export Text File pop-up

Jetzt legst du noch fest, welcher Zeichensatz in der Datei
verwendet wird.

Select "Automatisch erkennen" Alternativ kannst du diesen aber auch vom System erkennen

lassen.

Set "Delimiter" = Comma
Overlay - Export Text File pop-up

Abschließend legst du hier das Feldtrennzeichen...

Set "Enclosure" = "
Overlay - Export Text File pop-up

.... sowie das Texttrennzeichen der Datei fest.

Fade back to plenty Genug der grauen Theorie.
Open "Source" drop-down Deine Datei kann jetzt in dein System geladen werden.
Mouseover FTP Den Upload kannst du entweder über einen FTP-Server...
Mouseover SFTP ...einen sicheren FTP-Server...
Mouseover HTTP ...oder über einen HTTP-Server, also mit einem externen Link

abwickeln.

Select SFTP Wählst du hier die Option FTP oder SFTP-Server...
Fade to host, user name and password filled in (was sollen wir als Beispiel
zeigen?)

...musst du für die Kommunikation natürlich auch die
Zugangsdaten zu dem jeweiligen Server hinterlegen.
Enter path supplier-files/ Dann gibst du an, wo sich die Datei befindet...
Enter file name price-list-20-02-2019.csv ...und wie sie benannt ist.
Choose HTTP Andererseits kannst du auch HTTP-Server nutzen...
Mouseover "External URL" ...wenn deine Dateien beispielsweise bei einem
Cloudspeicherdienst wie Googledrive oder Dropbox
gespeichert sind....

Mouseover "URL" ...und du die URL der Datei kennst.
Choose "File upload" Natürlich ist es auch möglich die Datei selber in dein System

zu laden...

Click on the three dots ...wenn du sie auf deine Rechner gespeichert hast.
Click on the upload icon; Select file; Click "Open"; Click on the file name (no
check mark); Click "Select"

--------------------------

Authentication? Soll man das erwähnen?
Save Sobald du alle grundlegende Einstellungen hinterlegt hast,
wirst du zu einem anderen Menü weitergeleitet...

Mouseover "Matching", then "Mapping"
Flag 2 einblenden

...und siehst dich mit der Frage konfrontiert, was eigentlich
der Unterschied zwischen Abgleich und Zuordnung ist.
Fade to CSV file Gut, nehmen wir uns doch einen Moment Zeit und überlegen,
wie wir vorgehen würden, wenn wir die Preise von Hand
aktualisieren müssten.

Highlight "supplier item number" column Wahrscheinlich nimmst du dir die Artikel-ID,...
Fade to "Item > Edit item"; Search for item with the "Supplier variation number"
field

... suchst nach dem Artikel...
Open item ...und öffnest ihn...
Click on "Supplier" tab in lower row; Change purchase price to ????? ...um dann den Einkaufspreis anzupassen.
Fade back to ElasticSync menu Weißt du was? Mit ElasticSync ist der Ablauf genau gleich!
Mouseover "Matching" Das wird benutzt, um den richtigen Artikel im Abgleich

System zu finden.

Mouseover "Mapping" Den Bereich nutzt du dann um den Einkaufspreis Zuordnung

zu aktualisieren.
Click on "Matching" Und auf gehts!
Mouseover the search fields and end so that cursor is over "Supplier variation
number"
Overlay - plenty item search

Du entscheidest, welches Feld du nutzen willst....

Click in field and choose "supplier item number" header
Overlay - CSV file

....anschließend wählst du die Spalte der CSV-Datei aus, die
den entsprechenden Wert enthält.

Click on preview icon Bei Bedarf kannst du hier die Vorschau-Funktion nutzen,

welche dir die Entscheidung erleichtert.

Fade back to "Item > Edit item" Okay, wir denken nochmal an die händische Änderung der

Einkaufspreise.

Search for supplier item number with no results Wie würdest du vorgehen, wenn du einen Artikel im System
nicht finden kannst. Oder mit anderen Worten, wenn dein
Lieferant einen neuen Artikel anbietet, es aber noch keinen
Datensatz dazu in deinem System gibt?

Mouseover "New" button Ich könnte mir vorstellen, dass du den Artikel entweder
überspringst oder einen neuen Datensatz in plentymarkets
anlegst.

Fade back to "Matching" with mouseover "Import new, update existing data" Und genau dafür ist diese Option da.
Mouseover "Only update existing data" Sag plentymarkets einfach, ob vorhandene Datensätze

aktualisiert oder...

Mouseover "Only import new data" ...neue Daten importiert werden sollen...
Mouseover and select "Import new, update existing data" ...alternative kann auch beides passieren.
Save Super, plentymarkets hat jetzt genug Informationen um deine

Artikel zu finden.

Click on "Mapping" Die Frage ist: Was willst du nun mit deinen Artikeln machen?
Click on plus icon In unserem Beispiel...
Enter name "update purchase price" ...wollen wir den Einkaufspreis aktualisieren.
Enter position 1 Name und Position spielen erstmal nur eine untergeordnete

Rolle.

Save and screen changes Du solltest dich hier auf deinen Fokus auf diesen Bereich hier
legen. Hier sagst du deinem System nämlich, was es mit den
gefundenen Artikeln machen soll.

Fade to CSV file with purchase price column highlighted Für unser Beispiel nehmen wir also die Spalte mit dem

Einkaufspreis...

Fade to plenty item and "Supplier" tab ...und und speichern diesen Einkaufspreis am Artikel.
Fade to ElasticSync Und auch hier macht der ElasticSync genau das selbe.
Choose purchase price column as source Du wählst die Spalte mit dem entsprechenden Wert aus...
Scroll all the way down and choose "Supplier > Purchase price"; Click on
check mark to confirm

...und speicherst den neuen Wert.

Click in "Target" field to again show drop-down Natürlich gibt es in plentymarkets unzählige Datenfelder.
Diese kannst du hier im Menü auswählen. Bist du dir mal
nicht sicher, welches das richtige Feld ist...
Fade to item data record is opened ...kann es hilfreich sein, wenn du in das entsprechende
plentymarkets-Menü navigierst und schaust, welche
Datenfelder dort zu finden sind...

Fade to online manual
Link einblenden - https://knowledge.plentymarkets.com/en/data/importing-data
/ElasticSync#1930

...oder du hilfst dir mit einem Blick in unser Handbuch, in dem
alle wesentlichen Datenfelder mit einer Erklärung und
mögliche verpflichtend anzugebende Werte aufgeführt sind.

Fade back to ElasticSync -----------
Add new field Du kannst hier natürlich auch mehrere Felder hinterlegen...
Activate one row ...und sie, für den Fall, dass du nur einige für den speziellen

Import benötigst, deaktivieren und aktivieren.

Open "Source" drop-down and mouseover "Own value", "Regular expression"
and "Own assignment"

Sind dir eigentlich die Optionen im Bereich der Quelle
aufgefallen?Dir ist wahrscheinlich bemerkt, dass dies keine
Spalten aus der CSV-Datei sein können. Aber wofür kannst
du diese Optionen dann nutzen?

Mouseover "Own Value" Mit den Optionen hier hast du die Möglichkeit weitere Daten

hinzuzufügen...

Mouseover "Regular expression" and "Own assignment" ...oder Daten aus deiner CSV-Datei händisch zu ändern. Aber
keine Sorge, diese Funktionen werden in einem separaten
Video schritt für schritt erklärt.

Click on filter icon up top; Click on + Filter Zu guter Letzt kannst du hier noch Filter hinzufügen.
Source = item number, Rule = Greater than, Value = 199, Operator = And; Rul
e = Less than, Value = 300

So kannst du beispielsweise nur Informationen zu Artikeln
importieren, die über eine bestimmte ID verfügen.

Save ----------
Click on name of sync in the breadcrumbs
Flag 3 einblenden

Sobald du bereit bist den Import zu starten...
Click on "Settings" ...navigierst du zurück in dieses Menü....
Open "Interval" drop-down and choose 20 minutes ...und legst fest, wie häufig der Sync automatisch gestartet

werden soll.
Save -----------
Click on "Sync" in the breadcrumbs Anschließend empfehlen wir dir dieses Icon zu klicken...
Click on test icon ...und so den Import selber zu testen. Dadurch werden nur
die ersten zehn Zeilen importiert und du kannst sicherstellen,
ob der Import korrekt läuft. Wenn sich irgendwo ein Fehler
eingeschlichen haben sollte musst du eben nicht hunderte
Artikel nachbearbeiten.

Click on play icon Wenn du mit dem Ergebnis des Tests zufrieden bist kannst
du mit diesem Button den eigentlichen Import starten.
Grafik 04 - In einem Kreis steht das Wort Händler. Bevor wir zum Ende kommen noch ein kleiner Hinweis.
Grafik 04 - Wie ein Mindmap erscheint eine Verbindung zu einem zweiten
Kreis, worauf "Lieferant" steht.

Wir haben uns angeschaut, wie du die Preise EINES
Lieferanten anpassen kannst.

Grafik 04 - Es erscheinen mehrere Verbindungen zu mehrere Lieferanten Aber vielleicht hast du ja mehr als einen Lieferanten.
Grafik 04 - Jede Lieferant kriegt eine Verbindung zu einem weiteren Kreis mit
dem Wort "CSV" drauf.

Und jeder Lieferant stellt dir eine andere CSV-Datei zur
Verfügung.

Fade back to "Syncs" in the breadcrumbs Es wäre natürlich ziemlich aufwendig für jeden Lieferanten

einen eigenen Sync anzulegen.

Place check next to sync; Click on copy icon Die Zeit kannst du dir natürlich sparen in dem du deine Syncs

kopierst...

Open copy of sync ...und nach Bedarf bearbeitest.
Place check next to mapping; Click on copy icon Gleiches gilt natürlich auch für den Zuordnung. Einfach

kopieren...

Mouseover name of copy ...Einstellungen bearbeiten...
Click to deactivate copy ...und nach Bedarf aktivieren und deaktivieren.
Grafik 05 - ElasticSync Logo ist mitten im Bild zu sehen Glückwunsch! Der erste Schritt im Bereich ElasticSync ist

gegangen.

Grafik 05 - Weitere Icons erscheinen um das ElasticSync Logo herum Nachdem du dich mit dem Tool vertraut gemacht hast schaue
dir doch auch die übrigen Videos zum Thema ElasticSync an.
Hier findest du viele praktische Beispiele für deine tägliche
Arbeit genauso wie Videos mit zusätzlichen Features!
--
//end::transkript[]
