= FTP access
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Webshop, Mandant, FTP-Zugang
:position: 70

To make images, PDF files and other files accessible in your online store, these files must be saved in your plentymarkets system. Upload larger amounts of data using the file transfer protocol (FTP). In order to do this, you need an FTP program, also called an "FTP client", and the FTP access data.

[IMPORTANT]
.Access to item images on AWS systems
====
Item images of plentymarkets systems hosted on AWS are moved from the FTP server to Amazon S3 storage after upload. As such, you cannot access saved item images via the FTP server.
====

[IMPORTANT]
.Custom PHP and CGI scripts
====
Due to security reasons, implementing custom PHP and CGI scripts is not permitted. If you would like third-party software to be installed, contact the plentymarkets support. Alternatively, you can turn to a classic web hosting service.
====

== FTP programs

Programs for transferring files via FTP can be found for free on the internet or for a small fee. We have gathered a small selection of FTP tools for Windows and Mac OS X:

**FTP programs for Windows**

* link:http://filezilla-project.org/[FileZilla, window="_blank"]
* link:http://www.smartftp.com/[SmartFTP, window="_blank"]

**FTP programs for Mac OS X**

* link:http://cyberduck.ch/[Cyberduck, window="_blank"]
* link:https://filezilla-project.org/download.php/[FileZilla, window="_blank"]

You can also do the following instead of working with an FTP program:

* Use the integrated file browser
* Set up an FTP connection as a Windows network resource

== Setting up FTP access

You need the following information to set up a connection to a your plentymarkets system and transfer files with an FTP program:

* Host/server
* User name
* Password

The server and user name are already saved in your system. Select a secure password.

[.instruction]
Setting up FTP access:

. Go to **Settings » Client (store) » Global settings » FTP access**.
. Make a note of the entry listed under host (e.g. ftp01.plenty-store.co.uk).
. Make a note of the entry listed in the line **user name**.
. Enter a Password.
. **Save** the settings. +
→ The password is activated. You can access the FTP server after around 60 minutes.

[TIP]
.Tip
====
Instead of using the name of the host, you can derive an alternative host name from your domain.  Make sure that you include the dot: +
URL: http://www.my-store.co.uk +
FTP: ftp.my-store.co.uk
====

== Accessing the FTP server via an FTP program

Now save the access data that you noted down in the FTP program. If you are asked for a port while setting up the connection, enter the default value **21** or leave this field blank. Once you have saved the access data, connect to the FTP server to gain access to the server's file system. Now you can use FTP to upload files onto the server or download them onto your computer. Additionally, you can create and open directories and rename or delete directories and files. For security reasons, it makes sense to close the FTP connection after transferring files. For further information, refer to the documentation of the FTP program used.

[TIP]
.Problems connecting?
====
When using these settings, connection problems usually are related to special network settings (e.g. Proxy Server, Firewalls) or to the particular characteristics of your online service. If you encounter problems, contact your network administrator first and/or call your online service's hotline!
====

== Accessing files via Webspace tool

Instead of working with an FTP program, you also can change data with our webspace tool, which you can access by going to **CMS » Webspace**. For further information about using the ajaxplorer, refer to our link:https://www.plentymarkets.co.uk/-plentymarkets-4-120-Nun-mit-komfortablem-Dateibrowser/b-138/[**blog entry**] on this topic (German).
