= Importing data
:lang: en
include::{includedir}/_header.adoc[]
:position: 20

This page of the manual deals with the manual data import in the **Data » Dynamic import** menu. Importing data is recommended if you want to add new items, customer data or stock etc. to your plentymarkets system and you already have this data available in digital format. Note that a single import is limited to 6,000 data records. +
In the last chapters of this page of the manual, you can find practical examples.

[#10]
== Creating data formats

The data format that you want to import must correspond with the configuration of the data format in plentymarkets. This will ensure that your data is assigned correctly. This also includes that the spelling of the data fields matches the spelling in plentymarkets. You will find the names of the data fields on the subpages of the <<basics/data-exchange/data-formats#, Data formats>> page of the manual. Pay attention to the information about mandatory fields and synchronisation fields. You can create the import file with the help of a spreadsheet program.

You can facilitate this work step considerably by exporting the data format in a file in advance. Then, you edit your data in the file and re-import it into your system. This procedure is only possible for data formats that are suitable for both import and export. For further information about handling export and import files, refer to the chapter <<basics/data-exchange/exporting-data#05, Customising a file for data exchange>> on the **Exporting data** page of the manual. Proceed as described below to export your data in a file:

[.instruction]
Creating a data format:

. Go to **Data » Dynamic export**.
. Click on the **New Data format** tab.
. Select a **Data format type** from the drop-down menu.
. If needed, change the **Data format name** that is automatically created.
. Activate the data fields that should be contained in the export file.
. Select one **Import procedure** per data field. +
→ Information about the synchronisation fields can be found on the subpages of the <<basics/data-exchange/data-formats#, data format>> page of the manual.
. If needed, select a **Filter** or **Procedures**.
. **Save** the data format. +
→ The order of the data fields will change according to the position numbers that were entered.

[TIP]
.Selecting import procedures for data fields[#25]
====
For the data fields of a data format, the import procedures **Synchronisation** and **Import** are available. +
With the setting **Import**, the data will be imported regardless of whether data is already available in the system or not. This means that data might be overwritten during the import. With the setting **Synchronisation**, the data field will be synchronised with the data that is already available in the system before the import is carried out. This means that data will only be imported if no data is available in the system at all.
====

[#20]
== Carrying out the dynamic import

The dynamic data import takes place within the **Data » Dynamic import** menu. Here, you can import either data formats that you created in the **Data » Dynamic export** menu (so called customer formats) or data formats that you created yourself. In addition to the customer formats, three special import formats are available in the **Data » Dynamic import** menu in the drop-down menu **Format**:

* the **IncomingItems** special format that you use to import incoming items
* the **ItemAttribute** special format that you use to link items and attributes
* the **ItemParcelServicePreset** special format that you use to import shipping profiles

The special formats are import formats and are therefore only available in the **Data » Dynamic import** menu. You import the special formats exactly the same way as you import the other data formats. How to import data formats is described in the following.

[NOTE]
.Check and adjust names in the column headers
====
If you want to import data from an external system or a file that you created yourself, then the column headers in the file must exactly match the spelling of the data fields (field names) in plentymarkets. +
If plentymarkets cannot assign the import to the selected export type, then the import will be cancelled and an error message will be displayed. You will find the error message in the **Processing status** area. Check the column headers that are listed in the file to be imported and make changes to these headers if necessary.
====

[.instruction]
Importing data with the dynamic import:

. Go to **Data » Dynamic import**.
. Carry out the settings as desired. Pay attention to the information given in table 1.
. Click on **Import**.
. Check whether the imported data was created in the system.

[IMPORTANT]
.Processing status
====
After you have imported the file, you will receive a message in the **Processing status** area. In case the data lines were successfully imported, the number of the imported lines will be displayed. If an error occurs, the entry **0** will be displayed along with an error message. Check the field separator or encoding of the file. The file should always be UTF-8 encoded.
====

Note that the available settings depend on the data format you have selected for the import. For the data format **Stock** e.g., you select a **warehouse** and the **barcode** instead of a synchronisation option. The settings as they are described in table 1 are displayed for most of the data formats.

.Settings of the **Data » Dynamic import** menu
[cols="a,a"]
|====
|Setting |Explanation

|**Field separator**
|Select the field separator that is set in the import file.

|**Format**
|Select the data format that you prepared for the data import. +
**__Note__**: Depending on which data format you selected here, the settings change.

|**If there is no match during the synchronisation**
|Select one of the following options:  +
**Create a new data record** = If the data that you want to import doesn't exist in the system yet. +
**Skip data record** = If existing data should not be overwritten during the synchronisation.

|**File**
|Select the import file from your computer.
|====

[#130]
== Importing manufacturer item data from Amazon

In the **Data » Dynamic import** menu in the area **Import of manufacturer item data from Amazon**, you have the possibility of importing your items into your plentymarkets system in the Amazon data format. To do so, proceed as described on the <<omni-channel/multi-channel/amazon#, Amazon>> page of the manual in the <<omni-channel/multi-channel/amazon#310, Importing manufacturer item data from Amazon>> chapter.

[#210]
== Importing eBay listings

You import eBay listing in the **Data » eBay listings** menu. Both a set of item master data and a listing will be created in plentymarkets. The **Processing status** area gives you access to the current status of the process during import. How you import listings is described on the <<omni-channel/multi-channel/ebay#, eBay>> page of the manual in the <<omni-channel/multi-channel/ebay#1100, Importing eBay listings>> chapter.

////
== Example of use: Creating items and editing item data

Use the *Data* menu to create items or to edit existing item data. This function is useful if you want to import item lists from your supplier into plentymarkets or adjust your item prices. First, you create the data format **Item** in the **Data » Dynamic export** menu. Then export the data in a file and edit the data within the file. Afterwards, go to *Data » Dynamic import* and import the file.

[#60]
== Example of use: Importing variations

Importing item variations does not happen automatically when you import the items. In order to create variations and import them into your plentymarkets system, the following requirements must be met:

* Items must be created
* Attributes and attribute values must be created
* Attributes must be linked with the item

If the three requirements mentioned above are met and you have already created items, attributes and attribute values and have linked them, proceed with the <<basics/data-exchange/importing-data#100, Creating variations>> chapter.

In the following chapters, you will learn how to meet the requirements with the help of import files and which data formats you have to use. Below, you will find an overview of the required data formats:

* Data format **Item** for <<basics/data-exchange/importing-data#70, importing items>>
* Data format **Attribute** for <<basics/data-exchange/importing-data#80, importing attributes and attribute values>>
* Data format **ItemAttribute** for <<basics/data-exchange/importing-data#90, linking items with attributes>>

[#70]
=== Importing items

Create items with the data format **Item**. Create the data format in the **Data » Dynamic export** menu. Pay attention to the note about mandatory fields of this data format on the <<basics/data-exchange/data-formats/item#, Item>> page of the manual.

Now import the items. The items are then available in the **Item » Edit item** menu to be edited further.

[.instruction]
Importing items:

. Go to **Data » Dynamic import**.
. Select the separator that you used when creating the file.
. Select the data format that you created for the item from the drop-down menu **Format**.
. Select an option under **If there is no match during the synchronisation**.
. Click on **Browse**.
. Select the file that you want to import.
. Click on **Import**.

[#80]
=== Importing attributes and attribute values

Attributes and attribute values are created with the data format **Attribute**. Create the data format in the **Data » Dynamic export** menu. Pay attention to the mandatory fields of this data format on the <<item/managing-items#390, Attribute>> page of the manual.

Now import the attributes and attribute values. The attributes and attribute values are then available to be edited further under <<item/managing-items#, System » Item » Attributes>>.

[.instruction]
Importing attributes and attribute values:

. Go to **Data » Dynamic import**.
. Select the separator that you used when creating the file.
. Select the data format that you created for the attribute from the drop-down menu **Format**.
. Select an option under **If there is no match during the synchronisation**.
. Click on **Browse**.
. Select the file that you want to import.
. Click on **Import**.

[#90]
=== Linking attributes with the item

The **ItemAttribute** special format serves exclusively for importing the links between attributes and items. As such, an export format is not available. You don't need to create this data format. It is available as a special format in the **Data » Dynamic import** menu. Pay attention to the explanations on the data fields given in table 4.

The mandatory fields **item_id** and **attribute_list** are used to set up the link. When setting up the link, the attributes will simultaneously be assigned to the item and activated for the item.

.Data fields of the **ItemAttribute** data format
[cols="a,a"]
|====
|Data field |Explanation

|**attribute_list**
|Attribute values. +
Hash structure: Attribute1:Value1:Surcharge;Attribute2:Value2:Surcharge +
**Attribute1** = Name of the attribute +
**Value1** = Name of the attribute value +
(Optional) **Surcharge** = Surcharge amount in Euro (Euro and cent values are separated by a period). +
__**Example**__: **Hat size:54:2.00** (Backend attribute name:Backend value name:Surcharge) Do not use a colon in the attribute name or in the name of the value. Otherwise errors will occur in the data import.

|**external_item_id**
|External item ID

|**ean**
|Item EAN for identification purposes

|**item_id**
|Item ID

|**item_no**
|Item number
|====

[IMPORTANT]
.Mandatory fields
====
Mandatory fields for the data import: **attribute_list** and **item_id**.
====

[.instruction]
Linking attributes:

. Go to **Data » Dynamic import**.
. Select the separator that you used when creating the file.
. Select the special format **ItemAttribute** from the drop-down menu **Format**.
. Select an option under **If there is no match during the synchronisation**.
. Click on **Browse**.
. Select the file that you want to import.
. Click on **Import**.

[#100]
=== Creating variations

You need the data format <<basics/data-exchange/data-formats/attributeitemvariation#, AttributeItemVariation>> in order to create variations. Activate at least the data fields **ItemID**, **PriceID**, **VariationString** and **EAN**.

Make sure that the following requirements are fulfilled:

* The item is created.
* The attributes and attribute values are created.
* Both the attributes and values are linked with the item in order to build a variation from it.

[.instruction]
Creating variations:

. Go to **Data » Dynamic import**.
. Select the field separator that you used when creating the file.
. Select the data format **ItemAttribute** from the drop-down menu **Format**.
. Select an option under **If there is no match during the synchronisation**.
. Click on **Browse**.
. Select the file that you want to import.
. Click on **Import**.
////

[#120]
== Example of use: Importing stock

You can also import the entire stock and thus overwrite the current physical stock in your plentymarkets system. To do so, use the data format <<basics/data-exchange/data-formats/stock#, Stock>>.

[WARNING]
.Stock will be deleted
====
During this process, the current physical stock is replaced with the data that is imported. In other words, your entire stock will be deleted. Reserved stock remains unaffected.

If you do not want to import your entire stock, but would rather add incoming stock via data import, then use the special format **IncomingItems** (see chapter <<basics/data-exchange/importing-data#50, Importing an incoming items data record>>).
====

If you plan on editing the import file before you import it, then use the explanations on the data fields given below as a reference. Table 6 lists some of the data fields that are contained in the exported file.

.Dynamic import; data fields of the data format **Stock**
[cols="a,a"]
|====
|Field name |Explanation

|**ItemID**
|Item ID

|**VariationEAN**
|EAN code of the variation

|**PurchasePrice**
|Purchase price

|**VariationNo**
|Variation number

|**LocationID**
|Storage location ID +
Enter the number 0 here if no storage location is available or if you don't want it to be assigned.

|**Stock**
|Stock

|**WarehouseID**
|Warehouse ID

|**VariationString**
|System name hash of the attributes and values. +
__**Example**__: "Colour:Blue;Size:XXL" +
The names of the attributes and values are used.
|====

[.instruction]
Carrying out the data import:

. Go to **Data » Dynamic import**.
. Carry out the settings as desired. Pay attention to the information given in table 7.
. Click on **Import**.

.Dynamic import; import options for the **Stock** data format
[cols="a,a"]
|====
|Setting |Explanation

|**Field separator**
|Select the separator.

|**Format**
|Select the data format **Stock** for the import.

|**Warehouse**
|Select the warehouse for the import.

|**Barcode**
|Select the barcode for the import.

|**File**
|Select the file for the import.
|====

You will receive a detailed message about the data import in the **Processing status** section in the **Data » Dynamic import** menu. The format, file name, user name and import date e.g. are displayed in this section.
