= Entwurf_ebay
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

[#1600]
==  Fahrzeugverwendungsliste einrichten

Mit link:http://pages.ebay.de/help/sell/fitment.html[**Fahrzeugverwendungslisten**, window="_blank"] können Sie Verknüpfungen zwischen den passenden Fahrzeugen und dem zu verkaufenden Artikel erstellen. Das erhöht die Verkaufschancen, da die Artikel mit der Fahrzeugverwendungsliste bevorzugt in den Suchergebnissen angezeigt werden. Im Menü **Einstellungen » Märkte » eBay » Fahrzeugverwendungsliste** erstellen, bearbeiten und löschen Sie Fahrzeugverwendungslisten.

[.instruction]
Neue Fahrzeugverwendungsliste erstellen:

.  Öffnen Sie das Menü **Einstellungen » Märkte » eBay » Fahrzeugverwendungsliste**.
. Klicken Sie auf **Neue Fahrzeugverwendungsliste**.  +
→ Das Fenster **Neue Fahrzeugverwendungsliste** wird geöffnet.
.  Tragen Sie einen Namen für Ihre Liste ein. +
→ Der Name kann im Nachhinein geändert werden.
.  Wählen Sie eine **eBay-Plattform** für die Liste.
. Wählen Sie eine **Kategorie**.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dabei die Erläuterungen in den Tabelle X.
. **Speichern** Sie die Einstellungen

.Einstellungen für neue Fahrzeugverwendungsliste
[cols="a,a"]
|====
| Einstellung | Erläuterung

2+| Suche

|**Marke/Jahr; +
Modell; +
Plattform/CCM**
| Wählen Sie die passenden Suchfilter. +
**Marke/Jahr**: Keine Mehrfachauswahl möglich. +
Bei Auswahl der eBay-Plattform **Motors** erscheint der Suchfilter **Jahr** an Stelle von **Marke**.  +
**Plattform/CCM**: Bei Auswahl der Kategorie **Motorrad** erscheint der Suchfilter **CCM** an Stelle von **Plattform**.

|**K-Type-Nr.**
| Erscheint nur bei Auswahl der Kategorie **Auto**. Wird hier die K-Type-Nr. hinzugefügt, werden die Suchfilter nicht berücksichtigt.

2+| Liste

|**Fahrzeugliste**
| Alle verfügbaren Varianten eines Fahrzeugs werden in der Liste erfasst. Die Liste ist auf 1000 Einträge begrenzt. Bei mehr als 1000 Einträgen muss eine weitere Liste für den Artikel angelegt werden.
|

|**Hinweise**
| Hinweis eintragen. Anstatt einen Hinweis einzeln für jedes Fahrzeug in der Liste einzutragen, kann der Hinweis über den grünen Pfeil rechts für alle Fahrzeuge übernommen werden.
|====

[.instruction]
Fahrzeugverwendungsliste einem Listing zuordnen:

.  Öffnen Sie das Menü **Listings » Listings bearbeiten**.
.  Öffnen Sie ein Market-Listing, um diesem eine Fahrzeugverwendungsliste zuzuordnen.
.  Öffnen Sie das Tab **Marktplatz** des gewählten Listings.
.  Klicken Sie unter **Fahrzeugverwendungsliste** auf **Hinzufügen**. +
→ Das Fenster **Fahrzeugverwendungsliste wählen** wird geöffnet.
.  Tragen Sie den Namen einer Liste oder einen Teil des Namens ein und wählen Sie eine Liste.
.  Klicken Sie auf **Auswählen**, um die Liste dem Market-Listing zuzuordnen.

[#1650]
===  Fahrzeugverwendungsliste suchen

Suchen Sie nach angelegten Fahrzeugverwendungslisten mithilfe der Filtereinstellungen im Menü **Einstellungen » Märkte » eBay » Fahrzeugverwendungsliste**. Dabei stehen Ihnen die Filtermöglichkeiten **ID**, **Name**, **Kategorie** und **eBay-Plattform** zur Verfügung.

**Click &amp; Collect für neue Listings automatisch aktivieren** Wählen, ob alle neuen Listings automatisch für Cklick und Collect zur Verfügung stehen. Click &amp; Collect kann nur für eBay UK und eBAy Australien verwendet werden. Listings können im Nachhinein bearbeitet und die Einstellung deaktiviert werden. **Click &amp; Collect****Grundeinstellungen**, **Ja** oder **Nein** wählen. +
**Grundeinstellungen** = Die im Menü **<<multi-channel/ebay#65, Einstellungen » Märkte » eBay » Grundeinstellungen » Tab: Kontoeinstellungen >>** bei der Einstellung **Click &amp; Collect für neue Listings automatisch aktivieren** gewählte Option wird verwendet. **Grundeinstellungen** ist vorausgewählt. +
**Ja** = Click &amp; Collect für das Listing aktivieren. +
**Nein** = Click &amp; Collect für das Listing deaktivieren. **Click &amp; Collect** Eine Click &amp; Collect-Einstellung oder **ALLE** wählen. [#7010]
==  Click &amp; Collect at Argos einrichten

Richten Sie Click &amp; Collect at Argos ein, um die Vorteile auch mit plentymarkets nutzen zu können. Mit Click &amp; Collect at Argos können Käufer ihre Bestellungen, die sie über eBay UK oder eBay Australien gekauft haben, bequem in einer der vielen Argos Filialen im Vereinigten Königreich und in Australien abholen. Weitere Informationen zu Click &amp; Collect at Argos finden Sie direkt bei link:http://sellercentre.ebay.co.uk/click-and-collect#what[**eBay**, window="_blank"]. Click &amp; Collect at Argos kann nur mit den Länderplattformen eBay UK und eBay Australien genutzt werden.

[#7020]
===  Click &amp; Collect für Listings aktivieren

Im Menü **<<multi-channel/ebay#65, Einstellungen » Märkte » eBay » Grundeinstellungen » Kontoeinstellungen >>** legen Sie fest, ob alle neu gestarteten Listings zu Click &amp; Collect gehören sollen. Listings können auch im Nachhinein bearbeitet und für Click &amp; Collect aktiviert oder deaktiviert werden.

[.instruction]
Click &amp; Collect für alle neuen Listings aktivieren:

.  Öffnen Sie das Menü **Einstellungen » Märkte » eBay » Grundeinstellungen » Kontoeinstellungen**.
.  Wählen Sie **Ja** für die Einstellung **Click &amp; Collect für neue Listings automatisch aktivieren**.
.  Nehmen Sie ggf. weitere Einstellungen gemäß Tabelle 3 **<<multi-channel/ebay#65, Kontoeinstellungen >>** vor.
. **Speichern** Sie die Einstellungen.

Anstatt alle neuen Listings für Click &amp; Collect zu aktivieren, können Listings auch einzeln aktiviert werden.

[.instruction]
Click &amp; Collect für einzelne Listings aktivieren:

.  Öffnen Sie das Menü **Listings » Listings bearbeiten**.
.  Klicken Sie auf ein eBay-Market-Listing. +
→ Das Market-Listing wird geöffnet.
.  Wechseln Sie in das Tab **Marktplatz**.
.  Wählen Sie für die Option **Click &amp; Collect** die Einstellung **Ja**, um das Listing für Click &amp; Collect zu aktivieren.
. **Speichern** Sie die Einstellungen.

Die im Menü **<<multi-channel/ebay#380, Listings » Listings bearbeiten >>** für **Click &amp; Collect** zur Auswahl stehende Option **Grundeinstellungen** ist im Tab **Marktplatz** voreingestellt. Die im Menü **Einstellungen » Märkte » eBay » Grundeinstellungen » Kontoeinstellungen** gewählte Einstellung für die Option **Click &amp; Collect für neue Listings automatisch aktivieren** wird übernommen.

[NOTE]
.Click &amp; Collect für einzelne Listings deaktivieren
====
Auch wenn Sie im Menü **Einstellungen » Märkte » eBay » Grundeinstellungen » Kontoeinstellungen** die Option **Click &amp; Collect für neue Listings automatisch aktivieren** auf **Ja** gestellt haben, können Sie einzelne Listings für Click &amp; Collect deaktivieren. Setzen Sie die Option **Click &amp; Collect** im Tab **Marktplatz** des Market-Listings auf **Nein**.
====

[#7030]
===  Click &amp; Collect für aktive Listings aktivieren

Auch bereits aktive Listings können für Click &amp; Collect freigeschaltet werden. Allerdings wird Click &amp; Collect erst beim Wiedereinstellen des Listings aktiviert. Soll das aktive Listing sofort für Click &amp; Collect aktiviert werden, muss es über die Gruppenfunktion aktualisiert werden.

Für die Aktualisierung von Listings im Menü **Listings » Aktive Listings** muss in der Gruppenfunktion die Aktion **Keine** ausgewählt sein.

[.instruction]
Aktive Listings für Click &amp; Collect per Gruppenfunktion aktualisieren:

.  Öffnen Sie das Menü **Listings » Aktive Listings**.
.  Setzen Sie Häkchen bei den Listings, die Sie aktualisieren möchten.
.  Klicken Sie auf **Gruppenfunktion**. +
→ Das Fenster **Gruppenfunktion** wird geöffnet.
.  Aktivieren Sie im Bereich **eBay-Optionen aktualisieren** die Option **Click &amp; Collect**.
.  Klicken Sie auf **Ausführen**, um die Listings zu aktualisieren.

[#7040]
===  Click &amp; Collect-Filter anwenden

In dem Menü **<<multi-channel/ebay#560, Listings » Aktive Listings >>** werden alle Ihre Listings bzw. aktiven Listings angezeigt. Diese Listings können Sie mit Filtern weiter eingrenzen und nur die Listings anzeigen, die für Click &amp; Collect aktiviert sind. Wählen Sie hierfür bei Marktplatz die Filteroption **eBay**. In der Filterliste wird die Filteroption **Click &amp; Collect** angezeigt.

Im Menü **<<auftraege/auftraege-bearbeiten#, Aufträge » Aufträge bearbeiten  >>** können Sie gezielt nach Click &amp; Collect-Aufträgen suchen. Setzen Sie den Filter **Click &amp; Collect** im Tab **Filter** auf **Ja**, um sich Click &amp; Collect-Aufträge anzeigen zu lassen.

