= OTTO_HTML
:lang: de
include::{includedir}/_header.adoc[]
:position: 10

Der Marktplatz link:https://www.otto.de/[**OTTO**, window="_blank"] ist Teil der Otto Group und eines der erfolgreichsten Online-Versandhandelsunternehmen Deutschlands. Auf dieser Handbuchseite erfahren Sie, wie Sie OTTO an Ihr plentymarkets System anbinden.

[#10]
== Bei OTTO registrieren

Bevor Sie OTTO in Ihrem plentymarkets System einrichten, müssen Sie sich zunächst auf der link:https://www.otto.de/user/register?entryPoint=loginArea[**Webseite von OTTO**, window="_blank"] registrieren. Sie erhalten daraufhin alle nötigen Partner-Daten von OTTO, die Sie für die Einrichtung in Ihrem System benötigen.

[IMPORTANT]
.OTTO verfügt über zwei Schnittstellen
====
Der Marktplatz OTTO verfügt über zwei Schnittstellen: **Cooperation** und **Integration**. +
Der Unterschied zwischen diesen beiden Schnittstellen besteht im Auftragsimport. Bei der Schnittstelle **Cooperation** übermittelt OTTO einzelne Aufträge in Ihr plentymarkets System, die Sie dann direkt an den Endkunden schicken. +
Wenn Sie die Schnittstelle **Integration** nutzen, übermittelt Ihr plentymarkets System einmal pro Tag einen Sammelauftrag an OTTO. In diesem Fall schickt OTTO dann die bestellten Artikel an den Endkunden.
====

[#20]
== OTTO in plentymarkets einrichten

Um Artikel auf OTTO anzubieten, richten Sie OTTO in plentymarkets ein. Je nachdem, ob Sie die Schnittstelle **Cooperation** oder die Schnittstelle **Integration** nutzen, nehmen Sie leicht abweichende Einstellungen vor. Im Folgenden sind die Einstellungen der Schnittstelle **Cooperation** erläutert. In Tabelle 2 finden Sie die abweichende Einstellung und Erläuterung für die Schnittstelle **Integration**.

[.instruction]
OTTO in plentymarkets einrichten:

. Öffnen Sie das Menü **Einstellungen » Märkte » Otto » Cooperation**. +
→ Das Tab **Einstellungen** wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 1.
. **Speichern** Sie die Einstellungen.

[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Schnittstellenmodus**
|**Testmodus EIN** = Schnittstelle zu OTTO ist nicht aktiv. +
**Aktivmodus EIN** = Schnittstelle zu OTTO ist aktiv. +
Die Einstellungen bzw. Einträge müssen geprüft werden, bevor der Aktivmodus aktiviert wird.

2+|Vertriebspartner-Information

|**Lieferantenkennzeichen**
|Lieferantenkennzeichen eingeben, wie von OTTO erhalten.

2+|Artikeleinstellungen

|**Artikelname**
|Wählen, welcher Artikelname an OTTO übertragen wird.

|**Artikelkurzbeschreibung**
|Wählen, welche Artikelkurzbeschreibung an OTTO übertragen wird.

|**Artikelbeschreibung**
|Wählen, welche Option als Artikelbeschreibung an OTTO übertragen wird: +
**Standardbeschreibung** = Artikelbeschreibung, die im Artikel im Tab **Texte** unter **Artikelbeschreibung** eingegeben wurde. +
**Standardbeschreibung + technische Daten** = zusätzlich zur Standardbeschreibung werden auch die technischen Daten angezeigt.

|**Schlagwort**
|**Artikel-Merkmal**, **Artikel-Keyword**, **Standardartikelname**, **Artikelname 2** oder **Artikelname 3** wählen.

|**Bestandspuffer**
|Diese Option bewirkt, dass der Bestand, der übertragen wird, um den eingegebenen Wert reduziert wird. +
**Beispiel**: Der Artikel hat einen Bestand von 50 und der Bestandspuffer soll 10 Artikel haben, damit der Artikel auf diesem Marktplatz nicht vollständig abverkauft wird. Somit wird 10 als Bestandspuffer eingegeben. Zu dem Marktplatz wird dann ein Bestandswert von 40 übertragen. +
Weitere Informationen finden Sie auf der Handbuchseite **link::/[Bestand]**.

|**Bestandsmenge für Artikel ohne Bestandsbeschränkung, falls der Bestand 0 ist**
|Zahl eingeben, die als Bestand für Artikel ohne Bestandsbeschränkung, bei denen der Bestand 0 ist, übertragen werden soll.

|**Bildposition für das Energieetikett**
|Wurde das Energieetikett nicht mit dem gleichnamigen Merkmal gespeichert, sondern als Artikelbild, hier die Ziffer der Bildposition des Artikelbildes eingeben. Details zum Energieetikett siehe Kapitel <<entwurfsseiten/entwurf-lena/otto#90, **Energieeffizienz-Merkmale erstellen** >>.

|**Fakturierende (Tage)**
|Pro Artikel muss ein Fakturierende festgelegt werden. Ist das Fakturierende nicht direkt am Artikel eingegeben, dann wird beim Artikelexport das aktuelle Datum und die Anzahl der eingestellten Tage als Fakturierende übertragen.

|**Standardlieferzeiten**
|Anzahl von Tagen für die durchschnittliche Lieferzeit der Artikel eingeben.

|**Artikel-Lieferzeit 1-5**
|Anzahl von Tagen für die Lieferzeit eingeben. +
Die Stufen entsprechen den Verfügbarkeitsstufen in plentymarkets. +
Weitere Informationen finden Sie auf der Handbuchseite **<<artikel/artikel-verwalten#190, Artikelverfügbarkeit >>**.

|**OTTO Standardprovision in Prozent**
|Höhe der Provision in Prozent eingeben.

|**SellingPoints**
|Wählen, wie viele **<<entwurfsseiten/entwurf-lena/otto#80, SellingPoints >>** an OTTO übertragen werden sollen (mind. 3, max.5).

2+|Bestelleinstellungen

|**Mindestbestellmenge**
|Minimale Bestellmenge pro Artikel eingeben.

|**Maximale Bestellmenge**
|Maximale Bestellmenge pro Artikel eingeben.

|**Auftragsstatus für Vorkasse-Storno (fehlender Zahlungseingang)**
|Status wählen, den stornierte Aufträge erhalten sollen.

2+|SFTP-Einstellungen

|**OTTO-Benutzername**
|Benutzername eingeben.

|**OTTO-Passwort**
|Passwort für den OTTO-SFTP-Server eingeben.

|**RatePAY Merchant-ID**
|Händler-ID eingeben. RatePay ist ein Payment-Anbieter und gehört zur Otto Group.

|**Die Aufträge werden bereitgestellt von**
|Diese Einstellung ist abhängig von dem Zahlungsanbieter, der bei OTTO verwendet wird.

|**Die Aufträge werden zurück gemeldet an**
|Einstellen, an wen die Versandbestätigung versendet wird. Diese Einstellung ist abhängig von dem Zahlungsanbieter, der bei OTTO verwendet wird.
|====

__Tab. 1: Einstellungen für den Marktplatz OTTO, Schnittstelle **Cooperation**__

Wenn Sie die Schnittstelle **Integration** nutzen, nehmen Sie zusätzlich zu den Einstellungen in Tabelle 1 auch die Einstellung, die in Tabelle 2 im Abschnitt **Artikeleinstellungen** beschrieben ist, vor.

[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Am Artikel hinterlegte Artikelmaße**
|Maßeinheit wählen.
|====

__Tab. 2: Einstellungen für den Marktplatz OTTO, Schnittstelle **Integration**__

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

* täglicher Artikelexport
* stündlicher Auftragsimport
* stündlicher Bestandsabgleich

[#30]
== Zahlungsart aktivieren

Aktivieren Sie die Zahlungsart **Otto Payment** wie im Folgenden beschrieben.

[.instruction]
Zahlungsart Otto Payment aktivieren:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Zahlung » Zahlungsarten**.
. Klicken Sie auf den Ordner **International &gt; Otto Payment**. +
→ Die Einstellungen für die Otto-Zahlungsart werden angezeigt.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 2.
. Setzen Sie ein Häkchen bei der Option **Aktiv**.
. **Speichern** Sie die Einstellungen.

[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Sprache**
|Folgende Optionen werden sprachabhängig gespeichert: **Name**, **Infoseite**, **Infoseite (Intern)**, **Logo** und **Logo hochladen**. Damit ist es möglich, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|**Name**
|Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|**Infoseite**
|Als Information zur Zahlungsart eine Kategorieseite vom Typ **Content** oder die URL einer Webseite eingeben.

|**Infoseite (Extern)**
|Wenn unter **Infoseite** die Einstellung **Infoseite (Extern)** gewählt wurde, hier die URL der Infoseite eingeben.

|**Lieferländer**
|Kein Lieferland wählen. +
Sie können die Zahlungsart nicht in Ihrem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig konfiguriert.

|**Mandant (Shop)**
|Webshop(s), für den/die diese Zahlungsart aktiviert sein soll.

|**Logo**
|Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
**Standardlogo anzeigen** = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
**Kein Logo anzeigen** = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
**Upload-Logo anzeigen** = Blendet die Optionen **Logoansicht** und **Logo hochladen** ein.

|**Logoansicht**
|Wenn unter **Logo** die Option **Upload-Logo anzeigen** gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|**Logo hochladen**
|Wenn unter **Logo** die Option **Upload-Logo anzeigen** gewählt wurde, hier ein externes Logo hochladen. +
Auf **Dateien hochladen** klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|**Priorität**
|Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|**Kosten: Pauschal oder Prozentual**
|Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. Wichtig: Nicht in beide Felder einen Wert eingeben.  +
Weitere Informationen finden Sie auf den Handbuchseiten **<<start/statistik#, Statistik  >>** und **<<start/statistik/allgemeine-statistiken/artikel/renner-und-penner#, Renner und Penner  >>**. Ein Beispiel für pauschale und prozentuale Kosten finden Sie auf der Handbuchseite **<<entwurfsseiten/entwurf-lena/otto#20, Grundeinstellungen >>**.
|====

__Tab. 3: Einstellungen der Zahlungsart__

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü **Einstellungen » Kunden » Kundenklassen** aktivieren oder deaktivieren Sie **erlaubte Zahlungsarten**. +
Weitere Informationen finden Sie im Kapitel **<<entwurfsseiten/entwurf-lena/otto#40, Zahlungsarten und Kundenklassen >>**.
====

Weitere Informationen finden Sie auf der Handbuchseite **link::/[Zahlungsarten]**.

[#40]
== Kategorien aktivieren

Damit Ihre Artikel auf dem Marktplatz OTTO zum Verkauf angezeigt werden, müssen Sie die Kategorien aktivieren. Die dafür erforderlichen OTTO-Warengruppen erhalten Sie von OTTO. Nehmen Sie die folgenden Einstellungen vor, damit Ihre Artikel in den <<artikel/kategorien#, **Kategorien**  >> bei OTTO angezeigt werden.

[IMPORTANT]
.Zielgruppe
====
Die Datei, die Sie von OTTO erhalten, enthält neben den Warengruppen auch Zielgruppen. Diese Zielgruppen geben Sie später am Artikel als Merkmal ein. Wie Sie diese Einstellungen vornehmen, wird im Kapitel **<<entwurfsseiten/entwurf-lena/otto#70, Merkmale erstellen >>** beschrieben.
====

[.instruction]
Kategorien aktivieren:

. Öffnen Sie das Menü **Einstellungen » Märkte » Otto » Cooperation** bzw. **Integration**.
. Wechseln Sie in das Tab **Kategorien aktivieren**.
. Geben Sie für jede Ihrer **Webshop-Kategorien** die **Warengruppe** von OTTO ein. +
→ Die Warengruppen entnehmen Sie der Datei, die Sie von OTTO erhalten haben.
. Aktivieren Sie die Kategorien.
. **Speichern** Sie die Einstellungen.

[#50]
== Artikelverfügbarkeit einstellen

Artikel, die Sie auf OTTO verkaufen möchten, müssen im Menü <<artikel/artikel-verwalten#170, **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID** >> im Tab **Verfügbarkeit** aktiviert werden.

[.instruction]
Artikelverfügbarkeit für OTTO einstellen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen**.
. Aktivieren Sie die Hauptvariante im Bereich **Verfügbarkeit**.
. Wechseln Sie in das Tab **Verfügbarkeit**.
. Klicken Sie im Bereich **Märkte** in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktivieren Sie die Option **OTTO Cooperation** oder **OTTO Integration**.
. Klicken Sie auf **Hinzufügen**. +
→ Der Marktplatz wird hinzugefügt.
. **Speichern** Sie die Einstellungen. +
→ Der Artikel ist auf OTTO verfügbar.

Die Verfügbarkeit für Varianten kann im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit** individuell angepasst werden.

[#55]
==  SKU für eine Herkunft festlegen

Im Menü <<artikel/artikel-verwalten#170, **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID** >> im Tab **Verfügbarkeit** fügen Sie marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen**.
.  Wechseln Sie in das Tab **Verfügbarkeit**.
.  Klicken Sie im Bereich **SKU** auf **Hinzufügen**. +
→ Das Bearbeitungsfenster **Neue SKU** wird angezeigt.
.  Wählen Sie eine OTTO-Herkunft.
.  Geben Sie die SKU ein.
.  Klicken Sie auf **Hinzufügen**. +
→ Die SKU wird gespeichert und angezeigt.

[#60]
== Übertragene Artikel suchen

Sie können über die Schnittstelle nach bereits an OTTO übertragene Artikel suchen. Geben Sie dazu die Artikel-ID, den Namen oder die OTTO-Nr. ein. Bei erfolgreicher Suche wird der Artikel mit der letzten Übertragungszeit an OTTO angezeigt.

[.instruction]
Übertragene Artikel suchen:

. Öffnen Sie das Menü **Einstellungen » Märkte » Otto » Cooperation** bzw. **Integration**.
. Wechseln Sie in das Tab **Artikelliste**.
. Geben Sie einen der oben genannten Suchbegriffe ein.
. Klicken Sie auf **Suchen**.  +
→ Die verfügbaren Artikel werden angezeigt.

[IMPORTANT]
.OTTO-Fehlermails beachten
====
In einigen Fällen kann es vorkommen, dass in der XML-Datei aufgeführte Artikel nicht übertragen wurden. Beachten Sie deshalb die von OTTO erhaltenen Fehlermails.
====

[#70]
== Merkmale erstellen

Zur Zuordnung der Artikel benötigen Sie die <<artikel/artikel-verwalten#480, **Merkmale** >>**article_gender**, **packstation_delivery**, **product_type** und **search_color**. Wählen Sie für diese Merkmale den Merkmaltyp **Text**.

Zur besseren Übersichtlichkeit können Sie vorab eine <<artikel/artikel-verwalten#490, **Merkmalgruppe** >> erstellen, in die Sie dann alle von Ihnen erstellten OTTO-Merkmale einsortieren.

Im Folgenden wird beschrieben, wie Sie das Merkmal **article_gender** erstellen. Erstellen Sie anschließend das Merkmal **search_color** auf die gleiche Weise, aber wählen Sie dann die Option **Suchfarbe** aus dem Dropdown-Menü **Otto-Merkmal**.

[.instruction]
Merkmal article_gender erstellen:

. Öffnen Sie das Menü **Einstellungen » Artikel » Merkmale**.
. Wechseln Sie in das Tab **Neues Merkmal**.
. Geben Sie den Namen unter **Backendname** ein.
. Wählen Sie den **Text** als **Merkmaltyp**.
. Wählen Sie die Option **Zielgruppe (Geschlecht)** aus dem Dropdown-Menü **Otto-Merkmal**. +
→ Ein weiteres Dropdown-Menü wird geöffnet.
. Wählen Sie eine Option.
. **Speichern** Sie die Einstellungen.

Im Folgenden wird beschrieben, wie Sie das Merkmal **product_type** erstellen. Die Einstellung dieses Merkmals ist Pflicht. Erstellen Sie anschließend das Merkmal **packstation_delivery** auf die gleiche Weise an.

[.instruction]
Merkmal product_type erstellen:

. Öffnen Sie das Menü **Einstellungen » Artikel » Merkmale**.
. Wechseln Sie in das Tab **Neues Merkmal**.
. Geben Sie den Namen unter **Backendname** ein.
. Wählen Sie **Text** als **Merkmaltyp**.
. **Speichern** Sie die Einstellungen.

Verknüpfen Sie anschließend die <<artikel/artikel-verwalten#80, **Merkmale** >> am Artikel und geben Sie Werte ein.

[#80]
=== SellingPoints einstellen

SellingPoints sind Produkteigenschaften, die für den Kunden einen besonderen Kaufanreiz darstellen. Sie werden direkt auf der Artikelseite bei OTTO angezeigt. Gehen Sie wie im Folgenden beschrieben vor, um die SellingPoints zu erstellen, die Sie zu OTTO übertragen. Sie können beliebig viele SellingPoints erstellen. Die Schnittstelle zu OTTO überträgt allerdings maximal 5 SellingPoints pro Artikel. Ein SellingPoint darf für OTTO aus max. 100 Zeichen bestehen, wobei Umlaute 2 Zeichen darstellen. Bei mehr als 100 Zeichen wird der Artikel nicht exportiert.

[.instruction]
SellingPoints erstellen:

. Öffnen Sie das Menü **Einstellungen » Artikel » Merkmale**.
. Wechseln Sie in das Tab **Neues Merkmal**.
. Geben Sie den Namen unter **Backendname** ein.
. Wählen Sie **Text** als **Merkmaltyp**.
. Wählen Sie aus dem Dropdown-Menü **Otto-Merkmal** die Option **SellingPoint mit Merkmalnamen** oder **SellingPoint ohne Merkmalnamen**. +
→ Der Unterschied liegt in der Art der Darstellung bei OTTO (siehe unten).
. **Speichern** Sie die Einstellungen.

[TIP]
.Beispiel: SellingPoints mit und ohne Merkmalnamen
====
SellingPoints mit Merkmalnamen werden bei OTTO folgendermaßen dargestellt: +
Material: Baumwolle +
Der gleiche SellingPoint ohne Merkmalnamen wird wie folgt dargestellt: +
Baumwolle
====

[.instruction]
SellingPoints am Artikel einstellen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab **Merkmale**.
. Aktivieren Sie das soeben erstellte Merkmal.
. **Speichern** Sie die Einstellungen. +
→ Das Merkmal wird mit dem Artikel verknüpft und ist im Bereich **Merkmale** sichtbar.
. Geben Sie unter **Wert** das eigentliche Material ein.
. **Speichern** Sie die Einstellungen. +
→ Der Wert wird als SellingPoint mit dem Artikel übertragen.

[#90]
=== Energieeffizienz-Merkmale erstellen

Für die Auszeichnung Ihrer Artikel für OTTO gemäß der neuen Verordnung der EU zur Energieeffizienzrichtlinie sind ab 1.1.2015 Angaben zur Energieeffizienz sowie die Bereitstellung von Produktdatenblättern vorgeschrieben. Erstellen Sie dazu folgende <<artikel/artikel-verwalten#500, **Merkmale** >>: **Energieeffizienzklasse**, **Energieetikett** und **Produktdatenblatt**.

[.instruction]
Merkmal Energieeffizienzklasse erstellen:

. Öffnen Sie das Menü **Einstellungen » Artikel » Merkmale**.
. Wechseln Sie in das Tab **Neues Merkmal**.
. Geben Sie den Namen unter **Backendname** ein.
. Wählen Sie den Merkmaltyp **Kein**.
. Wählen Sie die Option **Energieeffizienz** aus dem Dropdown-Menü **Otto-Merkmal**. +
→ Ein weiteres Dropdown-Menü wird geöffnet.
. Wählen Sie die Energieeffizienzklasse.
. **Speichern** Sie die Einstellungen.

Für die Merkmale Energieetikett und Produktdatenblatt wählen Sie den Merkmaltyp **Datei**. Im Dropdown-Menü **Otto-Merkmal** wählen Sie dann die Option **Energieetikett** bzw. **Produktdatenblatt**. Im Folgenden wird beispielhaft beschrieben, wie Sie das Merkmal Energieetikett erstellen. Erstellen Sie anschließend das Merkmal Produktdatenblatt auf die gleiche Weise.

[.instruction]
Merkmal Energieetikett erstellen:

. Öffnen Sie das Menü **Einstellungen » Artikel » Merkmale**.
. Wechseln Sie in das Tab **Neues Merkmal**.
. Geben Sie den Namen unter **Backendname** ein.
. Wählen Sie den Merkmaltyp **Datei**.
. Wählen Sie die Option **Energieetikett** aus dem Dropdown-Menü **Otto-Merkmal**.
. **Speichern** Sie die Einstellungen.

Die Merkmale verknüpfen Sie dann wie im Folgenden beschrieben im Tab <<artikel/artikel-verwalten#80, **Merkmale** >> eines OTTO-Artikels.

[.instruction]
Energieeffizienz-Merkmale mit OTTO-Artikel verknüpfen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab **Merkmale**.
. Aktivieren Sie die soeben erstellten Merkmale **Energieeffizienzklasse**, **Energieetikett** und **Produktdatenblatt**.
. **Speichern** Sie die Einstellungen. +
→ Die Merkmale werden mit dem Artikel verknüpft und sind im Bereich **Merkmale** sichtbar.
. Laden Sie beim Merkmal **Energieetikett** die Bilddatei des Energieetiketts hoch.
. Laden Sie beim Merkmal **Produktdatenblatt** die PDF-Datei des Produktdatenblatts hoch.
. **Speichern** Sie die Einstellungen.

Alternativ zur Verknüpfung mit dem Merkmal **Energieetikett** können Sie das Energieetikett im Tab <<artikel/artikel-verwalten#90, **Bilder** >> des Artikels speichern. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Energieetikett alternativ im Tab Bilder speichern:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab **Bilder**.
. Fügen Sie die Bilddatei des Energieetiketts entweder über **Dateien auswählen** oder per Drag &amp; Drop-Funktion hinzu.
. **Speichern** Sie die Einstellungen.
. Öffnen Sie das Menü **Einstellungen » Märkte » Otto » Cooperation** bzw. **Integration**.
. Geben Sie die Positionsnummer des Bildes im Tab **Einstellungen** bei der Option **Bildposition für das Energieetikett** ein (Tabelle 1).
. **Speichern** Sie die Einstellungen.

[#100]
== Attribute verknüpfen

Sie können maximal drei Attribute mit einem Artikel verknüpfen. Artikel werden nicht exportiert, wenn das Format der Attribute nicht den Vorgaben von OTTO entspricht.

[TIP]
.Abweichende Bezeichnung für Attribute
====
Attribute werden bei OTTO als **Dimensionen** bezeichnet.
====

[WARNING]
.Attribute nicht ändern
====
An den Attributen eines Artikels dürfen keine Änderungen vorgenommen werden, bevor das Fakturierende erreicht wurde.
====

[#110]
=== Attribute für Textilien einstellen

Bei Textilien sind die Attribute bzw. Dimensionen fest vorgegeben. Dimension 1 ist die Farbe, Dimension 2 ist die Größe. Dimension 3 ist z.B. für Sondergrößen verfügbar.

* Dimension 1: **Farbe**
* Dimension 2: **Größe (auch Schuhgrößen)**
* Dimension 3: **Jeanslänge**/**Cup-Größen**/**Sondergrößen/US- bzw. UK-Schuhgrößen**

[IMPORTANT]
.Bedingungen für Dimension 2
====
Für Dimension 2 sind keine Aufpreise möglich. +
Dimension 2 kann nicht ohne Dimension 1 verwendet werden.
====

[#120]
=== Attribute für andere Produktgruppen einstellen

Bei allen anderen Produktgruppen sollte Dimension 1 auch als Farbe gewählt werden, sofern das Attribut **Farbe** verwendet wird. Ansonsten können die Dimensionen beliebig verteilt werden.

[#130]
== Lieferscheine erstellen

Aufträge, die von OTTO an den Partner übermittelt wurden, müssen bei der Anlieferung einen Lieferschein beigefügt haben. Der Lieferschein enthält alle erforderlichen Daten, um die Lieferung einem Auftrag im System von OTTO zuordnen zu können. Des Weiteren enthält der Lieferschein alle erforderlichen Informationen zu Artikeln sowie deren Größen und Mengen, die mit der Lieferung im Lager ankommen sollen.

[IMPORTANT]
.Lieferscheine als Pflicht
====
Lieferscheine sind nur bei Version **Integration** Pflicht.
====

Der Lieferschein besteht aus den Datenebenen Lieferscheinkopf und Lieferscheinartikel. Die nachfolgend beschriebenen Daten sind vom Partner zu liefern. Wenn nicht anders beschrieben, handelt es sich um Pflichtfelder.

Lieferscheinkopf:

* Lieferanschrift
* Auftraggeber/Rechnungsanschrift
* Partner-Adressdaten
* Lieferscheinnummer +
→  Ihre Lieferscheinnummer als positive Ganzzahl.
* Datum der Lieferscheinerstellung
* OTTO-Auftragsnummer +
→  Pro Auftrag darf es ein oder mehrere Pakete geben. Es darf aber nicht Ware aus mehreren Aufträgen in demselben Paket verschickt werden.
* Datenformat +
→  5-stellige oder 6-stellige positive Ganzzahl.
* Auftragsdatum
* Partner-Auftragsnummer (optional)

Lieferscheinartikel:

* Partner-Artikelnummer +
→  Artikelnummer, unter der der Artikel in plentymarkets eingerichtet ist.
* EAN (optional)
* OTTO-Artikelnummer
* Artikelgröße (optional) +
→  Größenbezeichnung als bis zu 4 Zeichen langer String.
* Liefermenge
* Preis

[#140]
== OTTO-Tags zuordnen

Die folgende Tabelle hilft Ihnen dabei OTTO-Felder in der XML-Datei den dazugehörigen plentymarkets Feldern zuzuordnen.

[cols="a,a,a,a"]
|====
|OTTO-Feld |plentymarkets Feld |Pflichtfeld |Besonderheit

|**LKZ**
|Lieferantenkennzeichen im Menü **Einstellung » Märkte » Otto » Integration/Cooperation**
|Integration: Pflicht +
Cooperation: Pflicht
|Zeichen: 6

|**StyleNo**
|Artikel-ID im Menü **Artikel » Artikel bearbeiten**
|Integration: Pflicht +
Cooperation: Pflicht
|Zeichen: 14

|**KeyWord**
|Meta-Keyword im Menü **Artikel » Artikel bearbeiten » Tab: Texte** +
__**Alternativ**__: Merkmal vom Typ **Text** mit Verknüpfung **Schlagwort**
|Integration: Pflicht +
Cooperation: Pflicht
|Manufacturer, KeyWord, ProperName und PackagingSizeDesc dürfen zusammen max. 100 Zeichen ergeben. +
Zeichen: 64

|**LongDesc**
|Artikelbeschreibung im Menü **Einstellung » Märkte » Otto » Integration/Cooperation » Tab: Einstellungen**
|Integration: Pflicht +
Cooperation: Pflicht
|HTML-Tags: Zeilenumbruch, Unterstrichen, Aufzählung und Fett +
Zeichen: 25-3500

|**ClassOfGoods**
|Warengruppe im Menü **Einstellung » Märkte » Otto » Integration/Cooperation » Tab: Kategorien aktivieren** +
__**Alternativ**__: Merkmal vom Typ **Text** oder **Auswahl** mit Verknüpfung **Warengruppe**
|Integration: Pflicht +
Cooperation: Pflicht
|

|**Clusterattribute1...10**
|Kategorien, die im Menü **Einstellung » Märkte » Otto » Integration/Cooperation » Tab: Kategorien aktivieren** aktiv sind, einer Warengruppe zugeordnet wurden und am Artikel hinterlegt sind.
|Integration: 1 Pflicht/2-10 Optional +
Cooperation: 1 Pflicht/1-10 Optional
|Zeichen: 256

|**SellingPoint1...5**
|Merkmal vom Typ **Text** oder **Auswahl** mit Verknüpfung **SellingPoint mit Merkmalnamen** oder **SellingPoint ohne Merkmalnamen**
|Integration: 1-3 Pflicht/4-5 Optional +
Cooperation: 1-3 Pflicht/4-5 Optional
|Zeichen: 60

|**GratisAdded**
|Merkmal vom Typ **Text** oder **Auswahl** mit Verknüpfung **Gratis dazu - Kennzeichen und Text**
|Integration: Optional +
Cooperation: Optional
|Wenn GratisAdded gepflegt wird, muss auch GratisText gepflegt werden.

|**GratisText**
|Merkmal vom Typ **Text** oder **Auswahl** mit Verknüpfung **Gratis dazu - Kennzeichen und Text**
|Integration: Optional +
Cooperation: Optional
|Wenn GratisAdded gepflegt wird, muss auch GratisText gepflegt werden +
Zeichen: 300

|**Manufacturer**
|Hersteller im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Global » Grundeinstellungen** +
__**Alternativ**__: Merkmal vom Typ **Text** oder **Auswahl** mit Verknüpfung **Hersteller**
|Integration: Pflicht +
Cooperation: Optional
|Manufacturer, KeyWord, ProperName und PackagingSizeDesc dürfen zusammen max. 100 Zeichen ergeben.

|**Material**
|Merkmal vom Typ **Kein** mit Verknüpfung **Material » Materialtyp**
|Integration: Optional +
Cooperation: Optional
|

|**EcoFact**
|Merkmal vom Typ **Kein** mit Verknüpfung **ECO-Kennezichen » FSC-Kennzeichen**
|Integration: Optional +
Cooperation: Optional +
__**Wichtig:**__ Pflicht bei FSC-Artikeln
|Zeichen: 50

|**PackagingSizeDesc**
|Merkmal vom Typ **Text** oder **Auswahl** mit Verknüpfung **Packungsgröße**
|Integration: Optional +
Cooperation: Optional
|Manufacturer, KeyWord, ProperName und PackagingSizeDesc dürfen zusammen max. 100 Zeichen ergeben. +
Zeichen: 50

|**ProperName**
|Artikelname im Menü **Einstellungen » Märkte » OTTO » Integration/Cooperation » Tab: Einstellungen**
|Integration: Optional +
Cooperation: Optional
|Manufacturer, KeyWord, ProperName und PackagingSizeDesc dürfen zusammen max. 100 Zeichen ergeben.

|**OrderQuantityMin**
|Mindestbestellmenge im Menü **Einstellungen » Märkte » OTTO » Integration/Cooperation » Tab: Einstellungen**
|Integration: Pflicht +
Cooperation: Pflicht
|Zeichen: 3 (positive Ganzzahl)

|**OrderQuantityMax**
|Maximale Bestellmenge im Menü **Einstellungen » Märkte » OTTO » Integration/Cooperation » Tab: Einstellungen**
|Integration: Pflicht +
Cooperation: Pflicht
|Zeichen: 4 (positive Ganzzahl)

|**QuantityUnit**
|Inhalt im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Einstellungen » Maße**
|Integration: Optional +
Cooperation: Optional
|

|**VAT**
|Umsatzsteuer im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Einstellungen » Kosten**
|Integration: Optional +
Cooperation: Optional
|

|**Dimension1**
|Bei Varianten: Menü **Einstellungen » Artikel » Attribute » Attribut öffnen » Marktplatzvariation » OTTO** +
Bei Einzelartikeln: Merkmal vom Typ **Text** oder **Auswahl** mit Verknüpfung **Dimension 1**
|Integration: Optional +
Cooperation: Optional +
__**Wichtig:**__ Pflicht wenn SearchColor gepflegt wird.
|Unzulässige Zeichen: Klammern, Doppelpunkt und Gleichheitszeichen +
Zeichen: 25

|**Dimension3**
|Bei Varianten: Menü **Einstellungen » Artikel » Attribute » Attribut öffnen » Marktplatzvariation » OTTO** +
Bei Einzelartikeln: Merkmal vom Typ **Text** oder **Auswahl** mit Verknüpfung **Dimension 3**
|Integration: Optional +
Cooperation: Optional +
Pflicht wenn Size geplegt wird.
|Zeichen: 100

|**Dimension4**
|Bei Varianten: Menü **Einstellungen » Artikel » Attribute » Attribut öffnen » Marktplatzvariation » OTTO** +
Bei Einzelartikeln: Merkmal vom Typ **Text** oder **Auswahl** mit Verknüpfung **Dimension 4**
|Integration: Optional +
Cooperation: Optional
|Zeichen: 100

|**SearchColor**
|Merkmal vom Typ **Kein** mit Verknüpfung **Suchfarbe » Farbe** &lt; br / &gt;Alternativ: Wert aus Dimension 1 wird übernommen, wenn gepflegt und kein Merkmal vorhanden ist.
|Integration: Optional +
Cooperation: Optional
|

|**NoOfParts**
|Inhalt im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Einstellungen » Maße**
|Integration: Pflicht +
Cooperation: Entfällt
|Zeichen: 8 (positive Ganzzahl)

|**DeliveryTimeDays**
|Artikellieferzeit 1-5 im Menü **Einstellung » Märkte » Otto » Integration/Cooperation » Tab: Einstellungen** +
Fallback: Standardlieferzeiten im Menü **Einstellung » Märkte » Otto » Integration/Cooperation » Tab: Einstellungen**
|Integration: Optional +
Cooperation: Optional
|Zeichen: 2 (positive Ganzzahl)

|**ShopDelivery**
|Merkmal vom Typ **Text** oder **Auswahl** mit Verknüpfung **Packetshop-Kennzeichen**
|Integration: Pflicht +
Cooperation: Entfällt
|

|**DeliveryType**
|Wird in Abhängigkeit zu DeliveryTypeSurcharge automatisch gesetzt.
|Integration: Optional +
Cooperation: Optional
|Zeichen: 2 (positvie Ganzzahl)

|**DeliveryTypeSurcharge**
|Merkmal vom Typ **Text**, **ganze Zahl** oder **Auswahl** mit Verknüpfung **Speditionsaufschlag**
|Integration: Optional +
Cooperation: Optional
|

|**ItemNo**
|Umsatzsteuer im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Verfügbarkeit » SKU**
|Integration: Pflicht +
Cooperation: Pflicht
|Zeichen: 35

|**SalesAmountNorm**
|Inhalt im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Einstellungen » Maße**
|Integration: Optional +
Cooperation: Optional
|

|**EnergyEfficiencyLabelImage**
|Bildposition für das Energieetikett im Menü **Einstellungen » Märkte » Otto » Integration/Cooperation » Tab: Einstellungen  +
__**Alternativ:**__ Merkmal vom Typ **Text** mit Verknüpfung **Energieetikett****
|Integration: Optional +
Cooperation: Optional
|

|**FileName**
|Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Bilder +
Das Bild der ersten Position ist das Hauptbild.**
|Integration: Hauptbild Pflicht/19 weitere Bilder optional +
Cooperation: Hauptbild Pflicht/19 weitere Bilder optional
|Zeichen: 128

|**ProductDataSheet**
|Merkmal vom Typ **Datei** mit Verknüpfung **Produktdatenblatt**
|Integration: Optional +
Cooperation: Optional
|

|**EnergyEfficiencyRating**
|Merkmal vom Typ **Kein** mit Verknüpfung **Energieeffiziensklasse » Klasse**
|Integration: Optional +
Cooperation: Optional
|

|**Dimension2**
|Bei Varianten: Menü **Einstellungen » Artikel » Attribute » Attribut öffnen » Marktplatzvariation » OTTO Cooperation** +
Bei Einzelartikeln: Merkmal vom Typ **Text** oder **Auswahl** mit Verknüpfung **Dimension 2**
|Integration: Optional +
Cooperation: Optional
|Zeichen: 20

|**InvoicingStartDate**
|Erscheinungsdatum im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Einstellungen » Verfügbarkeit** +
Fallback: aktuelles Datum
|Integration: Pflicht +
Cooperation: Pflicht
|YYYY-MM-DD'T'HH:MM:SS

|**InvoicingEndDate**
|Verfügbar bis im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Einstellungen » Verfügbarkeit** +
Fallback 1: aktuelles Datum + eingegebene Tage im Menü **Einstellungen » Märkte » OTTO » Cooperation/Integration » Frakturierende (Tage) +
Fallback 2: aktuelles Datum + 7 Tage**
|Integration: Pflicht +
Cooperation: Pflicht
|YYYY-MM-DD'T'HH:MM:SS

|**SellingPrice**
|Verkaufspreis im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Einstellungen » Verkaufspreise**
|Integration: Pflicht +
Cooperation: Pflicht
|

|**SellingPriceOld**
|Verkaufspreis vom Typ Aktionspreis im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Einstellungen » Verkaufspreise**
|Integration: Pflicht +
Cooperation: Pflicht
|Zeichen: 12 inklusive 2 Nachkommastellen

|**SellingPriceMSRP**
|Verkaufspreis vom Typ UVP im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Einstellungen » Verkaufspreise**
|Integration: Optional +
Cooperation: Optional
|Zeichen: 12 inklusive 2 Nachkommastellen

|**BuyingPrice**
|wird automatisch berechnet: SellingPrice - Otto Standard Provision in Prozent (**Einstellungen » Märkte » OTTO » Cooperation/Integration » Tab: Einstellungen** = BuyingPrice
|Integration: Pflicht +
Cooperation: Pflicht
|Zeichen: 12 inklusive 2 Nachkommastellen

|**Size**
|Wert aus Dimension 2 wird übernommen, wenn gepflegt. Ansonsten wird **NONE** eingegeben.
|Integration: Pflicht +
Cooperation: Pflicht
|

|**EAN**
|Barcode im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Einstellungen**
|Integration: Pflicht +
Cooperation: Pflicht
|Zeichen: 13

|**TargetGroup**
|Merkmal vom Typ **Kein** mit Verknüpfung
|Integration: Pflicht +
Cooperation: Pflicht
|

|**Weight**
|Gewicht (Brutto) im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Einstellungen » Maße**
|Integration: Pflicht +
Cooperation: Entfällt
|

|**Width**
|Breite im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Einstellungen » Maße**
|Integration: Pflicht +
Cooperation: Entfällt
|Zeichen: 7 inklusive 3 Nachkommastellen

|**Height**
|Höhe im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Einstellungen » Maße**
|Integration: Pflicht +
Cooperation: Entfällt
|Zeichen: 7 inklusive 3 Nachkommastellen

|**Depth**
|Tiefe im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Einstellungen » Maße**
|Integration: Pflicht +
Cooperation: Entfällt
|Zeichen: 7 inklusive 3 Nachkommastellen

|**NoOfParcelUnits**
|Packstücke &gt;=0 im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Einstellungen » Versand** +
Fallback: 1
|Integration: Pflicht +
Cooperation: Entfällt
|Wenn ein Artikel in mehreren Packeten verschickt wird, muss der PackingUnit ebenfalls gepflegt werden. Nachträglich nicht anpassbar.

|**SalesAmount**
|Inhalt im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Einstellungen » Maße**
|Integration: Optional +
Cooperation: Optional +
__**Wichtig:**__ Pflicht wenn SalesAmountNorm gepflegt wird.
|
|====

