= Probleme mit Plugin-Zahlungsarten
:lang: de
include::{includedir}/_header.adoc[]
:keywords:
:position: 30
:url: payment/faq/checkliste-zahlungsart
:id: PKZQP3Y
:author: team-order-payment

Zahlungsarten wie zum Beispiel <<payment/payment-plugins/paypal#, PayPal>>, <<payment/payment-plugins/mollie#, Mollie>> oder <<payment/payment-plugins/klarna#, Klarna>> werden über Plugins in dein System eingebunden. Durch das Durchlaufen des dazugehörigen Assistenten werden die Zahlungsarten eingerichtet und sind dann in deinem System verfügbar. +
Da es dabei einiges zu beachten gibt, kommt es hin und wieder mal zu Fehlern in diesem Prozess. Die folgende Checkliste soll dir helfen, mögliche Fehlerquellen selbst zu finden und zu beheben.

[%interactive]
Checke die folgenden Einstellungen, wenn es ein Problem mit einer Zahlungsart gibt:

* [ ] Ist das Plugin korrekt <<plugins/hinzugefuegte-plugins-installieren#, installiert und bereitgestellt>>?
* [ ] Hat IO die höchste Priorität im Plugin Set?
* [ ] Ist das Plugin im Hauptmandanten installiert und bereitgestellt?
* [ ] Befindet sich das Plugin auf der aktuellsten Version? (Changelog)
* [ ] Wurde der Assistent korrekt durchlaufen? (Handbuch)
* [ ] Sind die Zugangsdaten korrekt? (Live Modus / Test Modus)
* [ ] Sind die Zahlungsarten in der Kundenklasse freigegeben?
* [ ] Sind die Zahlungsarten in den Versandprofilen gesperrt?

Konntest du alle Punkte abhaken, sollte es keine Probleme mit der Zahlungsart geben. Falls du immer noch auf Schwierigkeiten stößt, findest du weitere Informationen zu jeder Plugin-Zahlungsart im Handbuchabschnitt <<payment/payment-plugins#, Payment Plugins>> oder du fragst unsere Supporter im link:https://forum.plentymarkets.com/[Forum]{nbsp}icon:external-link[].
