:keywords: {marketplace}, Marketplace, {marketplace}.de, setting up {marketplace}, {marketplace} marketplace, multi-channel, multichannel, multi-channel {marketplace}, multichannel {marketplace}, multi channel {marketplace}
:description: Multi-Channel in plentymarkets: Set up the interface to the market {marketplace} in your plentymarkets system.

[IMPORTANT]
.Download the {marketplace} plugin
====
You need a plugin to link plentymarkets to {marketplace}. In order to use the {marketplace} plugin, download it in the link:{marketplace-url}[plentyMarketplace^]{nbsp}icon:external-link[].

To use the {marketplace} plugin, you also need the Mirakl Connector plugin. You can download Mirakl from plentyMarketplace as well.
====

:plugin: Mirakl Connector

[.collapseBox]
Installing {plugin}
--
include::../../../plugins/_textblocks/instructions/plugin-installieren-en_gb.adoc[]
--

:plugin: {marketplace}
:priority: 1

[.collapseBox]
Installing {plugin}
--
include::../../../plugins/_textblocks/instructions/plugin-installieren-en_gb.adoc[]
--

[#100]
== About {marketplace}

{marketplace-info}

To set up the connection to {marketplace}, you can either carry out the instructions on this page or check out the following webinar:

video::{marketplace-webinar-id}[youtube]

[#200]
== Registering with {marketplace}

{marketplace-registration}

[#600]
== Activating the order referrer

// Activate order referrer

:market: {marketplace}
:referrer: {marketplace}
:referrer-option: option {marketplace}

include::../../_textblocks/instructions/activate-referrer.adoc[]

[#500]
== Defining a sales price

:referrer-price: {marketplace}

include::../../_textblocks/instructions/define-sales-price.adoc[]

[#1200]
== Creating properties

Using properties, you can export fields to the marketplace that aren't defined in plentymarkets by default. You can create the properties that are specified by {marketplace} in the *Setup » Settings » Properties » Configuration* menu.

For further information on properties, refer to the <<item/settings/properties#500, Characteristics and properties>> page.

For {marketplace}, you need the following properties:

* Logistics class (Logistikklasse, <<#1210, click for details>>)
* Leadtime to ship (Versandvorlaufzeit)
* Reverse charge (Abzugsverfahren)

The properties leadtime to ship and reverse charge are created automatically with the *Selection* type.

[#1210]
=== Creating the logistics class property

For each variation, you need to export a shipping profile code to {marketplace}. You can configure shipping profiles in the Mirakl back end. For a list of shipping profiles, refer to the *Informations » Carrier costs* menu in the Mirakl back end. You can find the code in the *Logistics class* column in brackets behind the name of the logistics class.

:property: Logistics class (Logistikklasse)

include::../../_textblocks/instructions/properties-creation.adoc[]

:property: Logistics class (Logistikklasse)
:property-area: Item
:property-type: Short text
:property-name: {marketplace} logistics class

include::../../_textblocks/instructions/properties-creation-table.adoc[]

[#1300]
== Generating the API key

To create the connection for {marketplace} between plentymarkets and Mirakl, you need an API key. To generate the API key, proceed as follows:

[.instruction]
Generating the API key:

. Open the Mirakl back end.
. Click on the user icon (icon:user[]).
. Go to the *API keys* tab.
. Generate a new API key for {marketplace}.
. Copy the API key to your clipboard. You need this key to set up your {marketplace} account in plentymarkets.

[#1400]
== Carrying out account settings in the assistant

Use the *{marketplace} - Wizard* assistant in the *Setup » Assistants » Plugins » [Select plugin set]* to set up your {marketplace account in plentymarkets.

:menu-path: pass:quotes[Setup » Assistants » Plugins » [Select plugin set]]
:assistant-name: {marketplace}
:number-of-boxes: Info box

include::../../_textblocks/instructions/assistant-basic-instructions.adoc[]

// Depending on the size of the assistant, use either one collapsed box or one collapsed box for each step in the assistant.

[.collapseBox]
.Options in the assistant
--
[[table-{marketplace}-basic-settings-assistant]]
[width="100%"]
[cols="1,2a"]
|======
|Setting |Explanation

2+| Step *Authentication*

| API Environment
a| Select an API environment from the drop-down list. Get in touch with your contact person at {marketplace} to confirm which API environment you should select. +
*_Note:_* If you switch to another API environment, e.g. from Productive to Test mode, you need to generate a new <<#1300, API key>>.

| API key
| Enter the <<#1300, API key>> that you generated. +
*_Note:_* If you switch to another API environment, e.g. if you switch from Productive to Test mode, you need to generate a new <<#1300, API key>>.

2+| Step *Data exchange*

| Data exchange
| Select processes for data exchange. This selection determines which data is exchanged between plentymarkets and Mirakl.

2+| Step *Refund mapping*

| Refund mapping
a| Map the refund reasons of {marketplace} to plentymarkets order statuses.

. Click on *Add new entry*. +
→ A new line is inserted.
. From the drop-down list on the left, select the plentymarkets status.
. From the drop-down list on the right, select one of the {marketplace} refund reasons. +
The following reasons can be sent to {marketplace}: +

* `15` = Out of stock
* `16` = Cancelled by client prior to shipping
* `17` = Item returned
* `18` = Item not received
* `19` = Agreement found with the vendor

// Reasons are identical for Conrad, Voelkner and MediaMarkt

2+| Step *Cancellation mapping*

| Cancellation mapping
a|
ifeval::["{marketplace}" == "Conrad"]
include::./conrad-special.adoc[tag=mapping-cancellation]
endif::[]

ifeval::["{marketplace}" == "MediaMarkt"]
include::./mediamarkt-special.adoc[tag=mapping-cancellation]
endif::[]

ifeval::["{marketplace}" == "Voelkner"]
include::./voelkner-special.adoc[tag=mapping-cancellation]
endif::[]

2+| Step *Warehouse selection*

| Warehouse selection
| Select the warehouse you want to use for stock export.

2+| Step *Shipping profile mapping*

| Shipping profile mapping
| For each shipping profile in plentymarkets, enter the corresponding abbreviation of the shipping service provider. To find the abbreviations, go to *Information » Shipping* in Mirakl.

2+| Step *Offer properties mapping*

| Offer properties mapping
| From the drop-down list *Logistic class*, select the property *{marketplace} Logistic class*. +
The *Leadtime to ship* and *Reverse charge* properties are selected by default.

|======
--

[#800]
== About automatic data exchange

After installing and setting up the plugin, the automatic processes described in <<#data-exchange-{marketplace}>> become available:

[[data-exchange-{marketplace}]]
[cols="1,3a"]
.Frequency of data exchange
|====
|Data |Interval

2+| Item data

| Item export
| daily

| Stock synchronisation
| Every 15 minutes

| Price synchronisation
| Every 15 minutes

2+| Order data

| Order import
| Every 15 minutes

|====

[#900]
== Setting up the item export

Item data is exported to {marketplace} via marketplace catalogues. Go to *Data » Catalogs* to create catalogues. Is this your first time working with catalogues? Then read up on the basic principle of <<en/data/exporting-data/managing-catalogues, catalogues first>>.

If you want to sell your products in multiple {marketplace} product categories, create a separate catalogue for each of them. Link the {marketplace} data fields with the item data saved in plentymarkets in the marketplace format afterwards. Once you’ve activated a catalogue, plentymarkets automatically exports the catalogue templates to {marketplace} daily.

[IMPORTANT]
.Error log
====
If there’s a problem during export, you can find the related log entries on Mirakl and not the plentymarkets log.
====

[#1240]
=== Creating additional properties

If you’ve defined more than one <<item/settings/attributes#, attribute>> for any of your variations, create a property that combines these attributes. For example, if you distinguish a variation both by colour and by size, you can create a property called “Grey XL”.Then, <<item/settings/properties#1400, link these properties>> to the respective variations.

In addition to the properties described <<#1200, previously>>, you need properties for all data fields of the marketplace whose data you want to export, but that don’t exist in plentymarkets by default. For further information on the properties you need, check the documentation of the marketplace. Is this your first time working with properties? For further information, refer to the <<item/settings/properties#500, Properties>> page of the manual.

[#902]
=== Creating a catalogue in the assistant

:catalogue-assistant-name: {marketplace} Catalogue
:number-of-boxes: Info box
:mapping-fields: the
:catalogue-path: pass:quotes[*Setup » Assistants » Plugins »* _Select plugin set_]
:catalogue-note: pass:quotes[Only select bottom level categories. You can find a better overview of the category hierarchy on Miracle by going to *My account » My product data settings*.

include::../../_textblocks/instructions/catalogue-assistant-config.adoc[]

// Depending on the size of the assistant, use either one collapsed box or one collapsed box for each step in the assistant.

[.collapseBox]
.Options in the assistant
--
[[table-{marketplace}-catalogue-assistant]]
[width="100%"]
[cols="1,2a"]
|======
|Setting |Explanation

| Settings
| Select a {marketplace} category for offering your items. Then, enter a name for the corresponding category in plentymarkets. +
{catalogue-note}

|======
--

[#map-data-fields]
=== Mapping data fields in the catalogue

include::../../_textblocks/instructions/catalogue-map-data-fields.adoc[]

ifeval::["{marketplace}" == "Conrad"]
include::./conrad-special.adoc[tag=mapping-data-fields]
endif::[]

ifeval::["{marketplace}" == "MediaMarkt”]
include::./mediamarkt-special.adoc[tag=mapping-data-fields]
endif::[]

ifeval::["{marketplace}" == "Voelkner"]
include::./voelkner-special.adoc[tag=mapping-data-fields]
endif::[]

[#475]
== Linking variations to a {marketplace} catalogue category

After you created a marketplace format for {marketplace} with the *{marketplace}* assistant or manually, the property *{marketplace}* is created in your plentymarkets system. A new selection value is added to the *{marketplace} category group* property for each category selected in the *Settings* step of the assistant. In order for your variations to be exported in the appropriate catalogue, they have to be linked to the *{marketplace} category group* property in the *Properties* tab of a variation.

[.instruction]
Linking a variation to a category:

. Go to *Item » Edit item » [Open item]*.
. Click on the *Variations* tab.
. Open the variation that should be linked.
. Open the *Properties* tab.
. In the *Variation properties* area, select the property *{marketplace} category group* from the *Properties* drop-down list and click on *Add* (icon:plus-square[role="green"]). +
→ The property is added.
. Select the desired category group from the *Value* drop-down list for the *{marketplace} category group* property. +
→ The variation will be exported in this catalogue. +
*_Example:_*If you pick the value *{category-example}*, the catalogue variation is exported for the *{category-example}* category.
. Repeat steps 5 and 6 for all categories where you want to offer the variation.
. *Save* (icon:save[role="green"]) the settings.

=== Linking properties with variations and saving values

include::../../_textblocks/instructions/properties-link.adoc[]

[#{marketplace}]
=== Activating the catalogue export

:interval: Daily
:market: {marketplace}

include::../../_textblocks/instructions/catalogue-activation.adoc[]

[#700]
== Setting the variation availability

:market-availability: {marketplace}
:option-availability: {marketplace}

include::../../_textblocks/instructions/variation-availability.adoc[]

// Important: For some marketplaces, the web API needs to be activated in addition to the marketplace. Define the :web-api: attribute to include the related text.

[#480]
== Setting up event procedures

Set up an <<automation/event-procedures#, event procedure>> to automatically update the order status on {marketplace} whenever specific events occur. You can set up the following event procedures:

// Available event procedures depend on the marketplace. These are the most common ones. Make changes as needed.

ifeval::["{marketplace}" == "Conrad"]
include::./conrad-special.adoc[tag=automation-summary]
endif::[]

ifeval::["{marketplace}" == "MediaMarkt”]
include::./mediamarkt-special.adoc[tag=automation-summary]
endif::[]

ifeval::["{marketplace}" == "Voelkner"]
include::./voelkner-special.adoc[tag=automation-summary]
endif::[]

How to set up the event procedures in plentymarkets is described in the following chapters.

[IMPORTANT]
.Additional procedures
====
In addition to the event procedures listed above, the {marketplace} plugin provides several other event procedures. These procedures exist because order processing differs between plentymarkets and Mirakl.

However, we recommend that you only use the procedures described in detail.
====

ifeval::["{marketplace}" == "Conrad"]
include::./conrad-special.adoc[tag=automation-details]
endif::[]

ifeval::["{marketplace}" == "MediaMarkt”]
include::./mediamarkt-special.adoc[tag=automation-details]
endif::[]

ifeval::["{marketplace}" == "Voelkner"]
include::./voelkner-special.adoc[tag=automation-details]
endif::[]

////
TODO:

* Is there anything special about the catalogue? Update include files if necessary.

////
