= Running processes
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Carrying out processes, Client, running processes, running a process,
:position: 20

[WARNING]
.Install plentyBase
====
You need the tool plentyBase to create and run processes in the plentymarkets back end. Go to  link:https://marketplace.plentymarkets.com/plugins/externe-tools/plentyBase_5053/[plentyMarketplace^] to download the installation files.
====

== Running a process

Proceed as described below to run a process. Note that you can only see those processes that have been <<basics/automation/processes/setting-up-processes#10, assigned>> to you as a user or that have been assigned to your role. **Variable users** will only be able to see the **System » Processes** menu if they were given the appropriate right. Go to <<basics/working-with-plentymarkets/manage-users#, System » Settings » User » Accounts » Open user » Tab: Right » Tab: Menu>> and activate the right **Processes**.

[.instruction]
Running a process:

. Go to **Processes**. +
→ The available processes are displayed.
. Click a process. +
→ The process is displayed and has the status **Waiting**.
. Click **Start**. +
→ The process starts. +
→ Bars in the **Work steps** tab show the progress of the individual process steps. +
→ Depending on the process, input may be required from the user.
