= Running processes
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Carrying out processes, Client, running processes, running a process,
:position: 270

The **plentymarkets Client » Processes** menu allows you to run the processes that were created in the **<<basics/automation/processes/setting-up-processes#, Settings » Processes  >>** menu.

== Running a process

Proceed as described below to run a process. Note that you can only see those processes that have been **<<basics/automation/processes/setting-up-processes#10, assigned >>** to you as a user or that have been assigned to your role. **Variable users** will only be able to see the **Settings » Processes** menu if they were given the appropriate right. Go to **<<basics/working-with-plentymarkets/manage-users#, Settings » Basic settings » User » Accounts » Open user » Tab: Right » Tab: Menu  >>** and activate the right **Processes**.

[.instruction]
Running a process:

. Open the plentymarkets Client.
. Go to **Processes**. +
→ The available processes are displayed.
. Click a process. +
→ The process is displayed and has the status **Waiting**.
. Click **Start**. +
→ The process starts. +
→ Bars in the **Work steps** tab show the progress of the individual process steps. +
→ Depending on the process, input may be required from the user.

[IMPORTANT]
.PDF files cannot be displayed on Windows systems.
====
PDF files cannot be displayed directly in the plentymarkets Client on Windows systems.
====

