= Procedures/control elements
:lang: en
include::{includedir}/_header.adoc[]
:keywords: procedures, processes, plentyBase, control elements, procedure, process, control element
:description: Overview of the procedures and control elements that can be configured in plentymarkets.
:position: 40

This page of the manual contains information about the control elements and procedures you can add to work steps of processes in the **System » Processes** menu.

The control elements and procedures are listed in separate chapters and in alphabetical order. The information is presented based on the following pattern:

* Short explanation of the control element/procedure
* The work steps in which the control element/procedure can be used
* Any settings that are specific to this control element/procedure
* For procedures: Procedures available in case of error
* For procedures: Sub-procedures available for the procedure

The information presented on this page serves as reference for users familiar with the basic concept of plentymarkets procedures. For basic information on processes, refer to the <<basics/automation/processes/setting-up-processes#, Setting up processes>> page of the manual.


[IMPORTANT]
.Tool plentyBase required
====
To create and run processes, you need plentyBase. You can download the installation files in the link:https://marketplace.plentymarkets.com/plugins/externe-tools/plentyBase_5053/[plentyMarketplace^].
====

== Control elements

This chapter deals with the control elements that can be configured for processes. Control elements are used to control how the procedures of a work step interact with each other.

[#480]
=== General settings for control elements

Some settings are available for all control elements. The following table explains these settings. The settings **Show** and **Destination** are not available for all control elements. However, they are also described here. You can check whether or not the settings are available for a given control element by reading the explanations provided for the control element in question.

.Information on the general settings for control elements
[cols="1,3"]
|====
|Setting |Explanation

|**Position**
|Option is only visible after the control element is created. +
The procedure's current position in the work step. The procedure with the lowest position number is run first. Select a different position from the drop-down list to change the order in which the procedures are run in the work step. +
**__Tip:__** Procedures can also be moved using the context menu. To do so, right-click the procedure and select **Move up** or **Move down**.

|**Show**
|Select if the procedure should be displayed in the work step. +
**Yes** (default setting) = Procedure is shown in the **Processes** menu. +
**No** = Procedure is not shown in the **Processes** menu. The procedure runs in the background.

|**Destination**
|Select the procedure to jump to. You can You can select from the procedures available for the work step to which you are adding the control element. +
**__Tip:__** The procedure's ID is shown above the icon in the process overview. This helps you to distinguish different procedures of the same name. If you point your cursor to the procedure, the ID is displayed in the upper left corner.
|====

[#490]
=== Dialog

Use the control element **Dialog** to jump to a specific procedure. Use this query to jump to a specific point of the process. Similar to the control element Split, you can then continue with one of several options. There are several different ways to configure the control element. Add a title and leave a message for the user. The different options that the user can select are configured as Buttons.
For example, you can use the Dialog procedure to ask the user which shipping service should be used for the orders in the process. Available services will then be displayed as buttons. The user can select a service by clicking on it.

[.subhead]
Work steps

This control element can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>
* <<basics/automation/processes/work-steps#incoming-items, Incoming items>>

[.subhead]
Settings

The following table explains the additional settings of the control element: The general settings for control elements are described in <<basics/automation/processes/procedures#480, table 1>>. Because input from the user is required, the setting **Destination** is not available for this control element.

.Settings for the control element **Dialog**
[cols="1,3"]
|====
|Setting |Explanation

2+|Setting

|**Title**
|Enter a name for the question.

|**Message**
|Enter a text, e.g. a question such as "How do you want to continue?".

2+|Button

|**Add**
|Click on the **green plus icon** to add a button. You can add up to 5 buttons per dialogue.

|**Name**
|Enter a name for the button, e.g. the name of the target procedure.

|**Position**
|Determine the button's position in the dialog. +
**__Tip:__** Put the buttons in the same order as their destinations appear in the process for better usability.

|**Colour**
|Select the colour of the button from the drop-down list.
|====

[#500]
=== End

The control element **End** finishes a work step or a process. For example, the control element **End** is required to end a loop.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>
* <<basics/automation/processes/work-steps#incoming-items, Incoming items>>

[.subhead]
Settings

No additional settings are required for this control element. The general settings for control elements are described in <<basics/automation/processes/procedures#480, table 1>>. Because the control element ends the work step, the setting **Destination** is not available.

[#510]
=== Filter

The control element **Filter** opens a filter within a process. You can use it to filter specific orders and carry out a procedure for these orders. The procedure will not be carried out for those orders that do not match the filter. Once the steps have been completed, use the procedure **Reset filter** to end the filter.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings of the control element: The general settings for control elements are described in <<basics/automation/processes/procedures#480, table 1>>.

.Settings for the control element **Filter**
[cols="1,3"]
|====
|Setting |Explanation

|**Filter**
|Different filters are available. By adding filters, the number of elements decreases. For example, use the filter **Status** to filter elements that have a specific status. Only these elements will then be selected for the process.
|====

[#520]
=== Reset filter

The control element **Reset filter** closes a filter within a process. This allows you to group the filtered and non-filtered orders back together for the next work step or the next procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings of the control element: The general settings for control elements are described in <<basics/automation/processes/procedures#480, table 1>>. The setting **Destination** is not available for this control element.

.Settings for the control element **Reset filter**
[cols="1,3"]
|====
|Setting |Explanation

|**Filter**
|Set the ID of the filter that is to be reset by this control element. If you point your cursor to the procedure, the ID is displayed in the upper left corner.
|====

[#530]
=== Jump

The control element **Jump** allows you to skip to a specific part of the process. For example, you need to include a jump within a loop. This will allow you to jump back to a specific part of the process until all elements of the process have been completed.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>
* <<basics/automation/processes/work-steps#incoming-items, Incoming items>>

[.subhead]
Settings

No additional settings are required for this control element. The general settings for control elements are described in <<basics/automation/processes/procedures#480, table 1>>.

[#540]
=== Loop

A **Loop** is used to repeat a procedure or chain of procedures. It is repeated as many times as necessary until all of the elements, e.g. orders, have completed the process.

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

No additional settings are required for this control element. The general settings for control elements are described in <<basics/automation/processes/procedures#480, table 1>>.

[#550]
=== Split

A **Split** divides the process. Here you can select an option, i.e. you can save a condition for a destination. The process will continue if the element's condition, e.g. the status of an order, is not met. If the condition is met, then the order will jump to the destination that was selected.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings of the control element: The general settings for control elements are described in <<basics/automation/processes/procedures#480, table 1>>.

.Settings for the control element **Split**
[cols="1,3"]
|====
|Setting |Explanation

|**Condition**
|**applies to all** = The selected filters have to apply to all orders. +
**applies to at least one** = The selected filters have to apply to one order.

|**Filter**
|Different filters are available. By adding filters, the number of elements decreases. For example, use the filter **Status** to filter elements that have a specific status. Only these elements will then be selected for the process.
|====

== Procedures

This chapter deals with the procedures that can be configured for processes. Procedures are added to work steps. You can then add <<basics/automation/processes/sub-procedures#, sub-procedures>> to each procedure.

[#100]
=== General settings for procedures

Some settings are available for all procedures. The following table explains these settings. The setting **In case of error** is not available for all procedures. However, it is also described here. You can check whether or not the setting is available for the procedure by reading the explanations provided for the procedure in question.

.Information on the general settings for procedures
[cols="1,3"]
|====
|Setting |Explanation

|**Position**
|Option is only visible after the procedure is created. +
The procedure's current position in the work step. The procedure with the lowest position number is run first. Select a different position from the drop-down list to change the order in which the procedures are run in the work step. +
**__Tip:__** Procedures can also be moved using the context menu. To do so, right-click the procedure and select **Move up** or **Move down**.

|**Show**
|Select if the procedure should be displayed in the work step. +
**Yes** (default setting) = Procedure is shown in the **Processes** menu. +
**No** = Procedure is not shown in the **Processes** menu. The procedure runs in the background.

|**In case of error**
|Select how to continue the process <<basics/automation/processes/troubleshooting#, in case of errors>>. +
**Cancel process** = the entire process will be cancelled if an error occurs. +
**Jump to procedure** = Process continues with the selected procedure. Select the procedure from the drop-down list **Jump to procedure**. +
**Continue with next procedure** = The process continues with the next procedure.
|====

[#110]
=== Pick-up/delivery note

Use the **Pick-up/delivery note** procedure to generate pick-up/delivery notes for orders. These pick-up/delivery notes can be printed or saved with a sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

No additional settings are required for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#120]
=== Address label

The **Address label** procedure assigns a label template to an order, an order item, an item or a packing unit. The labels can then be processed with a sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

.**Address label** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Label template**
|Select the <<item/managing-items#760, label template>> from the drop-down list.

|**Assignment**
|Select how you want the label template to be assigned. +
**One label per order** = One label is generated per order. +
**One label per order item** = One label is generated per order item. +
**One label per item** = One label is generated per item. +
**One label per packing unit** = One label is generated per packing unit.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#130]
=== Offer

Use the **Offer** procedure to generate offers for the orders. These offers can be printed or saved with a sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

No additional settings are required for the procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#140]
=== Item registration

Use the **Item registration** procedure to select the box storage rack that contains the desired items. The procedure also allows you to split orders into two delivery orders during item registration.

[TIP]
.Showing coupon order items
====
Coupon redemptions are shown as separate coupon order items with the ID -1 in orders. To show these coupon order items in this procedure, open the *Item search* procedure and set the *Include coupon order items (ID -1)* option to *Yes*.
====

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>. The **In case of error** setting is not available for this procedure.

.**Item registration** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Box storage rack**
|Select the <<stock-management/setting-up-a-warehouse#, box storage rack>> that contains the items to be registered.

|**Number of items to scan individually**
|**Scan each item individually** = If more than one copy of the item is picked, each item must be scanned individually. +
1-100 = After the selected quantity of items was scanned, the rest is added automatically.

|**Close pick list automatically**
|Activate to close incomplete pick lists in the process automatically.

|**Display execute button**
|Activate to display a button in the process that allows users to jump to a different procedure.

|**Jump to procedure**
|Activate to display a button in the process that allows users to jump to a different procedure.

|**Show "Split order" button** +
(plentyBase/Terra only)
|Activate to display a button in the process that allows users to split orders. This allows you to send items in stock immediately and any items not in stock later.

|**Delivery / partial order** +
(plentyBase/Terra only)
|**Delivery order** = The main order is split into two delivery orders. The invoice and incoming payments are saved with the main order.

|**Status for 2. delivery order** +
(plentyBase/Terra only)
|Select the order status to be assigned to the new delivery order.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* None

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* None

[#150]
=== Item label

Use the **Item label** procedure along with a sub-procedure to print or save a selected label template for an item.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#incoming-items, Incoming items>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>. The **In case of error** setting is not available for this procedure.

.**Item label** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Number of labels**
|Number of the desired item labels. You can select the options **1** to **10** or **Booking quantity**. With the option **Booking quantity**, all those items will be used that were booked by a previous procedure (**Incoming items**) within the same work step.

|**Label template**
|Select a <<item/managing-items#760, label template>> from the drop-down list.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* None

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#160]
=== Item search

Use the **Item search** procedure to register items with the sub-procedure **Scan item**.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#incoming-items, Incoming items>>

[.subhead]
Settings

No additional settings are required for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>. The **In case of error** setting is not available for this procedure.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* None

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#120, Scan item>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#170]
=== Order

Use the **Order** procedure along with a sub-procedure to <<order-processing/orders/managing-sales-orders#changing-order, process orders>>. For example, you can change the status of selected orders or scan package numbers.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

No additional settings are required for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>. The **In case of error** setting is not available for this procedure.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* None

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#290, Change status>>
* <<basics/automation/processes/sub-procedures#210, Change flag>>
* <<basics/automation/processes/sub-procedures#190, Change owner>>
* <<basics/automatisierung/prozesse/subaktionen#250, Scan package number>>
* <<basics/automation/processes/sub-procedures#340, Change payment method>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>
* <<basics/automation/processes/sub-procedures#300, Change shipping service provider>>
* <<basics/automation/processes/sub-procedures#320, Change shipping profile>>
* <<basics/automation/processes/sub-procedures#130, Add order notes>>
* <<basics/automation/processes/sub-procedures#140, Remove from procedure>>
* <<basics/automation/processes/sub-procedures#310, Shipping packages>>

[#180]
=== Order confirmation

The **Order confirmation** procedure generates order confirmations for selected orders in the process. They can then e.g. be printed or saved with the corresponding sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

No additional settings are required for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#190]
=== Order search

Use the **Order search** procedure to search for individual orders that you wish to process afterwards.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>. The **In case of error** setting is not available for this procedure.

.**Order search** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Order ID**; +
**Package number**; +
**Customer ID**; **Invoice number**; +
**Customer number**; +
*External delivery note number*
|Select whether a search field should be displayed during the process. Displaying the search field makes it possible to search for this data during the process. This means that orders cannot only be searched for by their order ID but also by further parameters such as the invoice number.

|**Automatic focus**
|Select which search field you want the cursor to automatically be positioned in when starting the process. Therefore, you can directly scan or type into this search field without having to select it beforehand.

|**Loyalty program**
|Select one, several or no loyalty program to only process orders from this loyalty program or orders without a loyalty program.

|**Order type display**
|Place a check mark next to the order types that you wish to find in the order search. Non-selected order types will not be searched for and will not be displayed, even if the data entered applies to them.  +
__**Important:**__ Order types that are to be further processed need to have a check mark placed for them in the option **Order type selection**.

|**Order type selection**
|Place a check mark next to the order types that you want to be able to select and process further in the process.

|**Item table columns**
|Select which columns you want to display in the stock unit list of orders that were found by the order search.

|**Skip list if only one match**
|Only applies if the search result only consists of one order of the type selected under **Order type selection**. +
**Yes** = The order that was found will directly be processed further.  +
**No** = As with search results that include more than one order, the order will first have to be selected with a check mark before it is processed further.

|**Include coupon order items (ID -1)**
|Coupon redemptions are shown as separate coupon order items with the ID -1 in orders. Select if coupon order items (ID -1) are to be shown in procedures, e.g. in the procedures *Create/edit return* and *Item registration*. +
*Yes* = Coupon order items (ID -1) are shown.
*No* = Coupon order items (ID -1) are hidden.

|**Next stock unit**;  +
**Next order**;  +
**Edit order**; +
**Back to search**
|Set up shortcuts in order to be able to carry out these options by key sequences during the process.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* None

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* None

[#200]
=== Reorder search

Use the **Reorder search** procedure to search reorders and book their incoming items using a barcode scanner within the scan reorder sub-procedure. Also pay attention to the <<basics/automation/processes/procedures#450, Incoming items (reorder)>> procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#incoming-items, Incoming items>>

[.subhead]
Settings

No additional settings are required for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>. The **In case of error** setting is not available for this procedure.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* None

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#150, Scan reorder>>

[#210]
=== Documents

Use the **Documents** procedure to automatically print or save one document of your choice to the clipboard with the corresponding sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

.**Documents** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Document**
|Select a document. You can select PDF files that were uploaded in the <<basics/automation/processes/carrying-out-processes#, CMS » Documents>> menu. The option **Employees** must have been selected from the Rights drop-down list for these files.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#220]
=== Email

Use the **email** procedure along with a sub-procedure to send an email or play a sound.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>. The **In case of error** setting is not available for this procedure.

.**Email** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Email template**
|Select the <<crm/sending-emails#, template>> to be sent from the drop-down list.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* None

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#330, Send>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#230]
=== Finance export

Use the **Finance export** procedure to create a CSV file that can be imported into several financial accounting solutions. You can choose between two formats: **One data record per stock unit (default)** or **One data record per invoice and VAT rate**. The <<basics/data-exchange/export-import/exporting-data#10, Finance export>> can be saved with a sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

.**Finance export** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Separator**
|Select a separator for the CSV file.

|**Format**
|Select a format. +
**One data record per stock unit (default)** = Lists each stock unit of a customer individually, i.e. one line displays all of the data for one stock unit. +
**One data record per invoice and VAT rate** = one line of the export displays all of the data included in an invoice. If an invoice contains items with different tax rates, e.g. 19% and 7 %, then the data will be displayed in two lines.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#280, Save>>

[#240]
=== Entry certificate (Gelangensbestätigung)

The **Entry certificates (Gelangensbestätigung)** procedure generates entry certificates for selected orders in the process. They can then e.g. be printed or saved with the corresponding sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

No additional settings are required for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#250]
=== Credit note

The **Credit note** procedure <<order-processing/orders/order-documents/generating-credit-notes#, generates credit notes>> for selected orders in the process. They can then e.g. be printed or saved with the corresponding sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

No additional settings are required for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#260]
=== Note

Use the **Note** procedure along with a sub-procedure to show a note or play a sound.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>
* <<basics/automation/processes/work-steps#incoming-items, Incoming items>>

[.subhead]
Settings

No additional settings are required for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>. The **In case of error** setting is not available for this procedure.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* None

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#200, Show note>>
* <<basics/automation/processes/sub-procedures#240, Customer notes>>
* <<basics/automation/processes/sub-procedures#230, Order notes>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#270]
=== Adjustment form

The **Adjustment form** procedure generates adjustment forms for selected orders in the process. They can then e.g. be printed or saved with the corresponding sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

No additional settings are required for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#280]
=== Warehouse pick list

The **Warehouse pick list** procedure generates <<order-processing/orders/order-documents/warehouse-pick-list#, warehouse pick lists>> for selected orders in the process. They can then e.g. be printed or saved with the corresponding sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

.**Warehouse pick list** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Sorting**
|Select how the items should be sorted on the warehouse pick list. Warehouse pick lists are initially sorted by the racks within the warehouse. The option that is selected here will then sort the items on a rack. Orders can be sorted in **ascending** or **descending** order by: +
**order ID** = Default setting +
**Invoice number** +
**Item ID** +
**Item number** +
**Storage location position** +
__**Note:**__ Only the first item of an order is taken into consideration for the sorting.

|**Sorting of 2. level (optional)**
|Select a second sorting option. The first option may sort multiple items the same way. In other words, it may not always be completely clear which item should be sorted first, second, third, etc. In these cases, the option that was selected under **Sorting of 2. level** will be used to sort the items further. The same sorting options can be selected as above. In addition, the option **None** is available.
|====

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#290]
=== Delivery note

Use the **Delivery note** procedure to generate <<order-processing/orders/order-documents/generating-delivery-notes#, delivery notes>> for the orders. These delivery notes can be printed or saved with a sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

No additional settings are required for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#300]
=== Dunning letter

Use the **Dunning letter** procedure to generate <<order-processing/orders/order-documents/generating-dunning-letters#, dunning letters>> for the orders. These dunning letters can be printed or saved with a sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

No additional settings are required for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#310]
=== Packing list

Use the **packing list** procedure to generate a list of picked items prepared for shipping. Use it along with a sub-procedure to print or save the <<order-processing/orders/order-documents/packing-list#, packing list>>.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

.**Packing list** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Sorting**
|Select how the orders should be sorted on the packing list. Orders can be sorted in **ascending** or **descending** order by: +
**order ID** = Default setting +
**Invoice number** +
**Item ID** +
**Item number** +
**Storage location position**__**Note:**__ Only the first item of an order is taken into consideration for the sorting.

|**Sorting of 2. level (optional)**
|Select a second sorting setting. This second sorting level is useful if it is not possible to clearly sort all of the results in a particular order. For example, you can choose to sort orders by **item ID**. If several orders match a specific item ID, then these orders will be listed randomly. It is useful to then sort these orders by their **order ID**. The same sorting options can be selected as above. In addition, the option **None** is available.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#320]
=== Pick list

Use the **Pick list** procedure along with a sub-procedure to print or save a <<order-processing/orders/order-documents/pick-list#, pick list>>. The pick list is generated as part of batch picking. Orders in status **5 Cleared for shipping** and higher will be dealt with. An incoming payment has already been booked for these orders (change from status 3 to 4). In addition, the items are available (change from status 4 to 5).

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

.**Pick list** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Sorting**
|Select a sorting option from the drop-down list. Data can be sorted in **__ascending__** order by: +
**Item ID** = Default setting +
**Item number** +
**Storage location position** +
**Category name of default category**

|**Sorting of 2. level (optional)**
|Select a second sorting setting. This second sorting level is useful if it is not possible to clearly sort all of the results in a particular order. For example, you can choose to sort orders by **item ID**. If several orders match a specific item ID, then these orders will be listed randomly. It is useful to then sort these orders by their **order ID**. The same sorting options can be selected as above. In addition, the option **None** is available.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

The procedure needs at least one sub-procedure to generate a pick list. Add the sub-procedure **Save online** to generate a pick list for the plentymarkets App.

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#245, Save online>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#330]
=== Pick list search

Use the **Pick list search** procedure to search for individual pick lists that you wish to process.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>. The **In case of error** setting is not available for this procedure.

.**Pick list search** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Pick list ID**
|**Display search field** = ID can be entered and searched for during the process. +
**Do not display search field** = ID cannot be searched for directly.

|**Pick list status**
|**Display filters** = Pick lists can be searched for by status during the process. +
**Do not display filters** = Pick lists cannot be searched for by status.

|**Owner**
|**Display filters** = The pick lists of a specific owner can be searched for during the process. +
**Do not display filters** = Pick lists cannot be searched for by owner.

|**User**
|**Display filters** = The pick lists of a specific user can be searched for during the process. +
**Do not display filters** = Pick lists cannot be searched for by user.

|**Online store**
|**Display filters** = The pick lists of a specific online store can be searched for during the process. +
**Do not display filters** = Pick lists cannot be searched for by online store.

|**Warehouse**
|**Display filters** = The pick lists of a specific warehouse can be searched for during the process. +
**Do not display filters** = Pick lists cannot be searched for by warehouse.

|**Sort by**
|**Display filters** = Pick lists can be sorted in ascending or descending order during the process, e.g. by ID, Status, Created on, Edited on, etc. +
**Do not display filters** = Pick lists cannot be sorted.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* None

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* None

[#340]
=== Polling

With the **polling** procedure, you can create a <<order-processing/fulfilment/shipping-centre#1400, polling file>> in CSV format that you need for particular shipping providers. You can save this file with the Save sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

.**Polling** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Shipping service provider**
|Select the <<order-processing/fulfilment/preparing-the-shipment#800, shipping service provider>> from the drop-down list that is to receive a polling file.

|**With header**
|This is only visible if the shipping service provider **DHL EasyLog** is selected. Place a check mark if you want the polling file to be created with a header.

|**Sorting**
|Select how the orders should be sorted within the polling file. Orders can be sorted in **ascending** or **descending** order by: +
**order ID** = Default setting +
**Invoice number** +
**Item ID** +
**Item number** +
**Storage location position** +
__**Note:**__ Only the first item of an order is taken into consideration for the sorting.

|**Sorting of 2. level (optional)**
|Select a second sorting option. The first option may sort multiple orders the same way. In other words, it may not always be clear which order should be sorted first, second, third, etc. In these cases, the option that was selected here will be used to sort the orders further. The same sorting options can be selected as above. In addition, the option **None** is available.

|**Separator**
|Select a separator for the CSV file. The default separator changes depending on the shipping service provider.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#350]
=== Invoice

Use the **Invoice** procedure to generate <<order-processing/orders/order-documents/generating-invoices#, invoices>> for the orders. These invoices can be printed or saved with a sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

.**Invoice** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Invoice for delivery order** +
(plentyBase/Terra only)
|Select if invoices are to be created for orders that are split during **item registration** when delivery orders are created by clicking the **Split order** button. +
**Do not create** = An invoice is not created automatically for delivery orders. +
**Create for main order** = The invoice is created for the main order.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#360]
=== Repair slip

Use the **Repair slips** procedure to generate repair slips for the orders. These repair slips can be printed or saved with a sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

No additional settings are required for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#370]
=== Create/edit return

Use the procedure **Create/edit return** to create returns. You can also edit the number of items afterwards.

[TIP]
.Showing coupon order items
====
Coupon redemptions are shown as separate coupon order items with the ID -1 in orders. To show these coupon order items in this procedure, open the *Item search* procedure and set the *Include coupon order items (ID -1)* option to *Yes*.
====

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

You will select default settings while you configure the procedure. These default settings will be selected initially when you create returns. However, they can still be changed if needed. The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>. The **In case of error** setting is not available for this procedure.

.**Create/edit return** procedure
[cols="1,3"]
|====
|Setting |Explanation

2+|Default values: Item registration

|**Skip during process**
|**No** = The procedure will be displayed in the process and can be carried out. +
**Yes** = The procedure will be skipped while the process is carried out.

|**Item status**
|Select the item status that should be used by default when a return is created. Go to <<order-processing/orders/managing-sales-orders#return, System » Orders » Order types » Return>> to create item statuses for returns.

|**Item value**
|Enter a percentage. This percentage will be applied to returned items. This value will also be displayed once a return has been created. Simply open the <<order-processing/orders/managing-sales-orders#return, return>> and click on the **Overview** tab. You will find the value next to the stock units.

|**Note**
|Enter a note. This note will be saved in the returns.

|**Warehouse**
|Select a warehouse. Variations will be booked into this warehouse by default if the storage location of the order is not used.

|**Storage location**
|Select a storage location. Variations will be booked into this storage location by default if the storage location of the order is not used.

|**Storage location for selected order item**
|Select the warehouse in which individual order items are to be reversed. +
**Storage location of procedure settings** = The combination of **Warehouse** and **Storage location** set here (see above) will be used. +
**Storage location of order** = The order item is reversed to the warehouse saved with the order.

|**Storage location for all order items**
|Select the warehouse variations are to be reversed to if all items of an order are returned. +
**Storage location of procedure settings** = The combination of **Warehouse** and **Storage location** set here (see above) will be used. +
**Storage location of order** = The order items are reversed to the warehouses saved with the order.

|**Show Reverse stock button**
|Select to display a button in the process that allows users to save a return and reverse stock simultaneously.

|**Item table columns**
|Select column headers. These columns will be included in the data table within the return.

2+|Default values: Create return

|**Return status**
|Select a status. Returns will be assigned this status when they are first created.

|**Reason for return**
|Select a reason. Returns will receive this reason when they are first created. Go to <<order-processing/orders/managing-sales-orders#return, Settings » Orders » Order types » Return>> to create reasons for returns.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* None

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* None

[#380]
=== Return label

Use the **Return label** procedure along with a sub-procedure to automatically print or save a <<order-processing/orders/order-documents/generating-a-return-label#, return>> label.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

.**Return label** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Return type**
|Choose between <<order-processing/fulfilment/preparing-the-shipment#3200, DHL Retoure enclosed return labels and DHL Retoure Online>>. +
**DHL Retoure enclosed return labels** = Generates return labels that you enclose in the package that you send. +
**DHL Retoure Online** = Generates return labels that you can provide customers online, e.g. in their customer account.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#390]
=== Return slip

Use the **Return slip** procedure along with a sub-procedure to print or save a return slip automatically. This return slip is attached to the item in case customers might need it for a <<order-processing/orders/order-documents/generating-a-return-label#, return>>.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

No additional settings are required for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#400]
=== SEPA Pain001

Use the **SEPA Pain001** procedure to export transaction files of your <<order-processing/payment/managing-bank-details#200, SEPA direct debits>> to a ZIP file. Provide your bank with this file after you saved it with a sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

.**SEPA Pain001** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Version**
|The versions supported by banks are listed in the drop-down list. Select the version that your bank can process. If necessary, check with your bank to find out which version format is expected.

|**Transaction files**
|Select if all transaction files should be compiled into one file. In both cases, the bank will receive a ZIP file. This ZIP file contains either the combined file or the individual transaction files. If necessary, check with your bank to find out which version format is expected.

|**Accounting period**
|Set when the transaction should actually be initiated. You can select **3**, **4** or **5 days**. This calculation starts from the time when the file was uploaded.

|**IBAN**
|Enter the International Bank Account Number (IBAN).

|**BIC**
|Enter the account's Bank Identifier Code (BIC).

|**Account holder**
|Enter the account holder's first and last name.

|**Designated use**
|Enter the designated use. The designated use must include a wildcard character. +
The following wildcard characters can be used: +
*[OID]* = order ID +
*[CID]* = customer ID +
*[INV]* = invoice number +

|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#410]
=== SEPA Pain008

Use the **SEPA Pain008 procedure** to export transaction files of your <<order-processing/payment/managing-bank-details#200, SEPA direct debits>> into a ZIP file. Provide your bank with this file after you saved it with a sub-procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

.**SEPA Pain008** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Version**
|The versions supported by banks are listed in the drop-down list. Select the version that your bank can process. If necessary, check with your bank to find out which version format is expected.

|**File type**
|Select the file type that meets the requirements of your bank or online banking software. +
**ZIP archive** = A ZIP file is created that contains several compressed XML files. +
**XML** = The file is not zipped and is sent to your bank separately. +
**__Important:__** If you selected **XML** as the **File type**, you cannot select the option **Combine** because this combination would result in errors.

|**Transaction files**
|Select if all transaction files should be compiled into one file. In both cases, the bank will receive a ZIP file. This ZIP file contains either the combined file or the individual transaction files. If necessary, check with your bank to find out which version format is expected. +
**__Important:__** If you selected **XML** as the **File type**, then do not select the option **Combine**. This combination can result in errors. In this case, select the option **Do not combine**.

|**Type of mandate**
|**SEPA core direct debit** = Allows a biller to collect funds from a payer's account, provided that a signed mandate has been granted by the payer to the biller. +
**SEPA business to business direct debit** = Mandate enables business customers in the role of payers to make payments by direct debit.

|**Payment frequency**
|**One-time payment** = Standard orders +
**Recurring payment** = Regularly occurring orders such as subscription orders, etc.

|**Type of debit**
|**First debit** = A customer's first SEPA direct debit. +
**Recurring debit** = After the first debit, direct debits will be collected as recurring debits. +
You need to be able to register both types of direct debits in order for <<order-processing/payment/managing-bank-details#200, SEPA payments>> to be carried out correctly. Set up an individual process for each type of debit. Add the filter **Type of debit** to the work step to ensure that the direct debits are registered correctly.

|**Accounting period**
|Set when the transaction should actually be initiated. You can select **3**, **4** or **5 days**. This calculation starts from the time when the file was uploaded.

|**IBAN**
|Enter the International Bank Account Number (IBAN).

|**BIC**
|Enter the account's Bank Identifier Code (BIC).

|**Identification number**
|Enter the creditor identifier.

|**Account holder**
|Enter the account holder's first and last name.

|**Designated use**
|Enter the designated use. The designated use must include a wildcard character. +
The following wildcard characters can be used: +
*[OID]* = order ID +
*[CID]* = customer ID +
*[INV]* = invoice number
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#420]
=== Serial numbers

Use the **Serial numbers** procedure and the <<basics/automation/processes/sub-procedures#260, Register serial numbers>> sub-procedure to register items using a barcode scanner during the process. These items will then be assigned the <<item/managing-items#820, serial numbers>> of order items and then e.g. booked as outgoing items with another procedure.

[IMPORTANT]
.Serial numbers for selected items
====
If you only want to register serial numbers for selected items, go to the item and select **Yes** for the **Serial numbers** option in the **Other** tab. Create a filter before the procedure in the process and select the filter type **Serial number**. Within the filter select **Yes** for the option.
====

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

No additional settings are required for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>. The **In case of error** setting is not available for this procedure.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* None

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#260, Register serial numbers>>

[#430]
=== Shipping center

Use the **shipping center** procedure along with a sub-procedure to print or save a <<order-processing/fulfilment/shipping-centre#, shipping order>> automatically.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>.

.**Shipping center** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Shipping service provider**
|Select the <<order-processing/fulfilment/preparing-the-shipment#800, shipping service provider>> from the drop-down list.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* <<basics/automation/processes/procedures#170, Order>>
* <<basics/automation/processes/procedures#220, Email>>

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#180, Print>>
* <<basics/automation/processes/sub-procedures#280, Save>>
* <<basics/automation/processes/sub-procedures#350, Save to clipboard>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#440]
=== Outgoing items

Use the **Outgoing items** procedure along with a sub-procedure to book the <<stock-management/outgoing-items#, outgoing items>> of an order or reset the booking automatically.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

No additional settings are required for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>. The **In case of error** setting is not available for this procedure.

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* None

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#160, Execute booking>>
* <<basics/automation/processes/sub-procedures#170, Reset booking>>
* <<basics/automation/processes/sub-procedures#270, Sounds>>

[#450]
=== Incoming items (reorder)

The **Incoming item (reorder)** procedure books all items of a reorder at once if an order is found during the <<basics/automation/processes/procedures#200, Order search>> procedure.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#incoming-items, Incoming items>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>. The **In case of error** setting is not available for this procedure.

.**Incoming item (reorder)** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Default setting storage location**
|Select which storage location you want to be preselected in the process routine. The default setting can be changed in the process at any time. The following options are available: +
**Suggested storage location** = The setting saved for the item under **Tab: Stock » Tab: Warehouse** will be used.  +
**Available storage location** +
**Storage locations in use**
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* None

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* <<basics/automation/processes/sub-procedures#160, Execute booking>>

[#460]
=== Single incoming item

The **Single incoming item** procedure allows you to register single <<stock-management/new-incoming-items#, Incoming items>> and directly allocate the item to a storage location or print a label for it.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#incoming-items, Incoming items>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>. The **In case of error** setting is not available for this procedure.

.**Single incoming item** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Storage location scan**
|**Display** = Select this option if you want the incoming item to be allocated directly to a storage location. +
**Do not display** = Select this option if a random storage location should be allocated (also see **Default setting storage location**).

|**Purchase price**
|**Display** = The purchase price will be registered together with incoming items. +
**Do not display** = The purchase price will not be registered with incoming items.

|**EAN**
|Select whether you want a search field for item searches by GTIN to be displayed in the process or not.

|**Item ID**
|Select whether you want a search field for item searches by item ID to be displayed in the process or not.

|**Item number**
|Select whether you want a search field for item searches by item number to be displayed in the process or not.

|**Supplier item No.**
|Select whether you want a search field for item searches by supplier item number to be displayed in the process or not.

|**Full text**
|Select whether you want a search field for full text searches to be displayed in the process or not.

|**Automatic focus**
|Determines which of the search fields displayed will be selected automatically when starting the process. This is usually the search field that is used primarily.

|**Destination when finished**
|Select the procedure that the process should continue with as soon as registering incoming items is completed.

|**Default setting storage location**
|Select which storage location you want to be preselected in the process routine. The default setting can be changed in the process at any time. The following options are available: +
**Suggested storage location** = The setting saved for the item under **Tab: Stock » Tab: Warehouse** will be used.  +
**Available storage location** +
**Storage locations in use** +
**No storage location**

|**Print item label**
|Select whether item labels for incoming items are to be printed individually **After adding item**, all at once **After booking incoming items** or **not** at all.

|**Printer configuration**
|Select a printer.

|**Label template**
|Select the template you want to use for the item labels.

|**Number of labels**
|Select how many labels should be printed per item. Either select between **1** and **10** or print according to the **Booking quantity**.

|**Quick intake**
|Select if the registration of incoming items is to be streamlined. +
**No** (default setting) = The form for entering item information opens every time an item is registered. +
**Yes** = If the search result for a registered items is unique, the item is placed into the incoming items stack directly. The form for entering item information does not open. You can increase the amount by registering/scanning the item again. Click on the item in the incoming items stack to the right to edit item information after items have been added.

|**Keyboard shortcuts**
a|Keyboard shortcuts can be configured for the following functions:
* **Increase quantity**
* **Decrease quantity**
* **Apply**
* **Book incoming items**

No settings are saved by default. +
The shortcuts that are saved here take priority over the keyboard shortcuts that are saved for the user in the <<basics/working-with-plentymarkets/customise-user-account#50, user settings>>. +
If multiple tabs are available for carrying out a process, then the shortcuts for the active tab take priority.
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* None

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* None

[#470]
=== Register incoming payment

Use the **register incoming payment** procedure to register incoming payments with their date and payment method in the <<order-processing/payment/managing-payments#, Orders » Incoming payments>> menu. This provides you with an overview and a proof of payments that are saved in your system as <<order-processing/payment/managing-bank-details#200, SEPA direct debits>>.

[.subhead]
Work steps

This procedure can be selected for the following work steps:

* <<basics/automation/processes/work-steps#order-processing, Order processing>>
* <<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>

[.subhead]
Settings

The following table explains the additional settings for this procedure. The general settings for procedures are described in <<basics/automation/processes/procedures#100, table 6>>. The **In case of error** setting is not available for this procedure.

.**Register incoming payment** procedure
[cols="1,3"]
|====
|Setting |Explanation

|**Payment method**
|Select a payment method.

|**Designated use**
|Enter the designated use. The designated use must include a wildcard character. +
The following wildcard characters can be used: +
*[OID]* = order ID +
*[CID]* = customer ID +
*[INV]* = invoice number
|====

[.subhead]
Procedures in case of error

The following procedures are available in case of errors:

* None

[.subhead]
Sub-procedures

The following sub-procedures are available for this procedure:

* None
