= Installation and setup
:lang: en
include::{includedir}/_header.adoc[]
:position: 10
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:
:url: app/installation

Want your business to <<app#, profit from the plentymarkets app>>? Don’t lose any time! Start setting up the app on the appropriate hardware.

This page guides you through the installation process step-by-step and helps you complete the tasks that need to be done in advance. The settings described on this page go into effect when you begin <<app/functions#, using the app functions>>.

[#100]
== Choosing the right hardware

What do you want to use the app for? Which hardware you need depends on what you want to do with the app.

Do you want to see key performance indicators or track customer, item and order data? You only need a mobile Android or iOS device for these functions.

In addition, the plentymarkets app allows you to perform stock management tasks and to use the point of sale system plentymarkets POS. We recommend that you book a link:https://www.plentypos.de/[hardware package^] if you want to use these additional functions.

[#200]
=== Case 1: Managing company data

include::_textblocks/hardware-requirements/hardware-key-figures.adoc[]

[#300]
=== Case 2: Mobile inventory management system

include::_textblocks/hardware-requirements/hardware-mobile-inventory.adoc[]

[#400]
=== Case 3: The plentymarkets mobile POS system

include::_textblocks/hardware-requirements/hardware-pos.adoc[]

[#500]
== Downloading the app

include::_textblocks/hardware-requirements/download-links.adoc[]

[TIP]
.Is your company data safe on this device?
====
The plentymarkets app is safe in the sense that users can only <<app/installation#1200, log into the app with access data>>. But since the app can contain sensitive business data, we still recommend that you spend a few minutes thinking about security. Are your employees allowed to download the app on their own smartphones? Do your devices’ screens lock with a PIN or a password? Spend some time thinking about how your company will answer these sorts of questions.
====

[#600]
== Granting access to the app

The app will only work if you’ve link:https://www.plentymarkets.co.uk/free-trial/[booked a plentymarkets ERP system^]. In other words, users will log in with the same access data as they use for the plentyarkets system.

First, grant access to all the employees who should use the plentymarkets app. Decide which app functions each employee should be allowed to use.

[#700]
=== Creating user accounts

Do all of your employees have a plentymarkets account? If not, log into your plentymarkets system and <<basics/admin-tasks/manage-users#10, create the necessary accounts>>.

Your employees will <<app/installation#1200, log into the app>> with whichever user name and password you’ve created for them.

[TIP]
.Admin or back end account?
====
Admin users automatically have the right to access all plentymarkets functions without limitation. Think twice before you create admin accounts because they will also have the right to create, manage and edit other user accounts. +
If you want to choose which functions and menus a particular user is able to see, then create a back end account.
====

[#800]
=== Defining rights

Should your employees be able to see all the functions in the app or just a few? Maybe your cashiers should have access to the mobile POS system but not to the inventory management functions.

In your plentymarkets system, you can decide which menus and key figures should be visible for each user account.

[.instruction]
Defining app rights:

. Go to *System » System settings » Settings » User » Accounts*.
. Open a *Backend* user account. +
*_Note:_* *Admin* users automatically have the right to access all functions. As such, it’s not possible to customise the rights for an admin.
. Click on the *Mobile* tab.
. Activate the functions and key figures that the user account should have access to in the app. Note <<table-app-rights>>.
. *Save* the settings.

[[table-app-rights]]
.Defining app rights
[cols="1,3"]
|====
|Setting |Explanation

|*Visible functions*
|Which <<app/functions#, app functions>> should your employees see? Place check marks to specify which exact menus this back end user should see.

|*Incoming items
|Should your employees be able to see and edit the purchase price while <<app/functions/warehouse-management/receiving-rebooking#, receiving goods>>? Place check marks to grant the rights. +
This area is not activated unless you’ve checked the *Incoming items* option under *Visible functions*.

|*POS functions*
|Which <<pos#, POS functions>> should your employees be able to use? Place check marks to specify which exact functions this back end user should work with. +
This area is not activated unless you’ve checked the *POS* option under *Visible functions*.

|*Visible key figures*
|Which <<app/functions/key-figures#, key performance indicators>> should your employees see? Place check marks to specify which exact data this back end user should see.
|====

//Was ist mit den REST-Berechtigungen oder andere Berechtigungen?

[#900]
=== Assigning an app PIN

Will your employees share devices? Constantly logging in and out can quickly waste a lot of time. In such situations, we recommend having employees <<app/installation#1700, use a PIN to switch from one account to another>> rather than having them log in and out with their user name and password. If all of your users have their own PIN, then they can quickly switch to a different user account in the plentymarkets app.

[.instruction]
Assigning an app PIN:

. Go to *System » System settings » Settings » User » Accounts*.
. Open a user account.
. Enter an app PIN for the user. Note <<table-app-pin>>.
. Re-enter the app PIN.
. *Save* the settings.

[[table-app-pin]]
.Assigning an app PIN
[cols="1,3"]
|====
|Setting |Explanation

|*New app PIN*
a|include::_textblocks/user-rights/app-pin.adoc[]

|*Repeat app PIN*
|Re-enter the PIN.
|====

[#1000]
=== Simultaneous use

Your link:https://www.plentymarkets.co.uk/prices/[plentymarkets rate^] specifies how many users can log into plentymarkets at the same time. This limit applies to your plentymarkets back end and to the plentymarkets app.

You can do the following if you reach the user limit:

* Ask users to log out manually.
* <<basics/admin-tasks/manage-users#170, Log out users in the session management menu>>.
* <<basics/admin-tasks/manage-users#190, Increase the user limit of your plentymarkets contract>>.

[TIP]
.How many accounts can I create?
====
We only limit simultaneous use and not the number of user accounts you can create.
====

[#1100]
== Logging in and finding your way around

[#1200]
=== Logging into the app

//Kapitel 2 von POS für Kassenpersonal entweder mit include oder mit Link (da raus und nur hier)

The plentymarkets app will only work if you’ve link:https://www.plentymarkets.co.uk/free-trial/[booked a plentymarkets ERP system^]. In other words, you’ll log in with the access data that you use for your plentymarkets system.

[.instruction]
Logging into the app:

. Log into your mobile device.
. Tap on the plentymarkets app. +
→ The login screen is displayed.
. Enter the login details for your plentymarkets system. Note <<table-app-login>>.
. Tap **Login**. +
→ The start screen is displayed. +
→ You will remain logged in until you either <<app/installation#1500, log out>> or <<app/installation#1600, lock>> your user account. That means that you can open and close the app without having to log in again.


[[table-app-login]]
.Logging into the app
[cols="1,3"]
|====
|Setting |Explanation

|*Language*
|Do you want to use the app in English or German? Select a language from the drop-down list.

|*System (base URL)*
|What’s the URL for your plentymarkets system? Enter the domain without https:// or http://. For example: your-store.co.uk.

|*User*
|Which user account do you want to log in with? Enter the <<basics/admin-tasks/manage-users#30, user name>> for this account.
//(Auf die Benutzer-Seite sollte vorhanden sein: Wenn du ein neues plenty-System gebucht hast, dann bekommst du diese Benutzerdaten in eine E-Mail. Du kannst dann die Benutzername und Passwort ändern).

|*Password*
|Enter the <<basics/admin-tasks/manage-users#30, password>> for this account.
|====

[#1300]
=== Finding your way around the app

Have you logged into the plentymarkets app? Welcome! The start screen is the first menu you’ll see. Take a look at the header. Here you’ll see two important symbols:

* The pencil icon (icon:pencil[role="blue"]) in the top right corner. Tap on this symbol to set up <<app/functions/key-figures#, key performance indicators like revenue and sales figures>> on the start screen.

//Link zur Seite "Artikel, Kunden, Auftragsdaten einsehen" einbauen, sobald die Seite steht.
* The menu icon (icon:bars[role="blue"]) in the top left corner. Tap on this symbol to access the main menu. From here, you can view your item, customer and order data. You can use the app as an <<app/functions/warehouse-management#, inventory management system>>. Or you can <<pos#, ring up customers in your brick and mortar store>>.

Have you opened the main menu? Look at the header again. Now you’ll see two additional symbols in the top right corner:

* The cloud icon (icon:cloud[role="blue"]). This symbol shows whether you’re currently using the app in online or offline mode.

* The user icon (icon:user[role="blue"]). Tap on this symbol to <<app/installation#1600, lock your user account>>, <<app/installation#1700, switch to a different user account>> or <<app/installation#1500, log out of the app altogether>>.

[TIP]
.Re-load the menu
====
Swipe down to refresh the screen.
====

[#1400]
== Logging out, locking or switching the account

[#1500]
=== Logging out of the app

Proceed as follows to log out of the plentymarkets app.

[.instruction]
Logging out of the app:

. Tap on the menu icon (icon:bars[role="blue"]) in the top left corner of the app.
. Tap on *Logout*. +
→ The *Logout* window is displayed.
. Decide whether you want to re-enter your access data the next time you log in. Note <<table-app-logout>>.

[[table-app-logout]]
.Logging out of the app
[cols="1,3"]
|====
|Setting |Explanation

|*Log current user back in automatically*
|Use the toggle button to tell plentymarkets whether you want to re-enter your access data the next time you log in. +
*Activated* (icon:toggle-on[role="green"]) = Next time the app is opened, the same user account is logged in automatically. No password is necessary to log in next time the app is started. +
*Deactivated* (icon:toggle-off[role="darkGrey"]) = The user account is logged out completely and the login details are discarded. To log in again, the language, base URL and user details must be entered. +
*_Note:_* This setting is saved and applies to all users of the app.
|====

[TIP]
.Alternative approach
====
Alternatively, tap on the user icon (icon:user[role="darkGrey"]) and then on the logout icon (icon:sign-out[role="red"]). Note <<table-app-logout>>.
====

[#1600]
=== Locking and unlocking access

If you step away from the app but want to remain logged in, you can lock access to the app.

[.instruction]
Locking access:

. Tap on the menu icon (icon:bars[role="blue"]) in the top left corner of the app.
. Tap on the user icon (icon:user[role="darkGrey"]) in the top right corner. +
→ You will see a list of people who have <<app/installation#900, an app PIN>>.
. Tap on the lock icon (icon:lock[role="blue"]) in the bottom left. +
→ Access to the app is locked. +
→ Your name is shown first in the list of users.

[.instruction]
Unlocking access again:

. Tap your user account.
. Enter your PIN or your password. +
→ Access to the app is unlocked. +
*_Tip:_* You can change to a different user account even if access to the app is locked. Tap a different user account in the list to change users.

[#1700]
=== Switching to a different user account

Will your employees share devices? Constantly logging in and out can quickly waste a lot of time. Instead of having users log out, it will be faster if they use a PIN to switch from one account to another.

The user symbol (icon:user[role="darkGrey"]) at the top right shows who is currently logged in. This symbol displays the initials of whoever is currently logged in. The icon is whatever colour was chosen for this user account in the plentymarkets back end.

[.instruction]
Switching to a different user account:

. Tap on the menu icon (icon:bars[role="blue"]) in the top left corner of the app.
. Tap on the user icon (icon:user[role="darkGrey"]) in the top right corner. +
→ You will see a list of people who have <<app/installation#900, an app PIN>>. +
. Tap on the desired user account.
. If the new user is logging in for the first time, then he’ll need to enter his password. If he’s already logged in before, then he’ll be able to enter his PIN. +
→ The user account is switched.

Once you switch users, the same area of the app opens. If the new user does not have rights for this area of the app, the main menu of the app opens instead.

[TIP]
.Order details are saved
====
If you switch user accounts while ringing up a customer, then the newly logged in user will see the transaction that was started. The new user will be able to complete the transaction.
====

[#1800]
== Customising the app

Proceed as follows to customise the app.

[#1900]
=== Working with templates

Do you want to control, e.g. which information is displayed first, second, third, etc and which font size is used to display information in the app?

//Link zur Seite "Artikel- und Auftragsdaten" einbauen, sobald die Seite steht.
//Link zur Seite "mobilen Picklisten" einbauen, sobald die Seite steht.
You can create templates for several different app functions. For example, you can decide how your item and order data should be displayed in the app or what your mobile pick lists should look like.

[#2000]
=== Choosing a background image

Instead of using the default background, would you rather use a colour that matches your own corporate design? You can decide which image or colour is displayed.

[.instruction]
Changing the background image:

. Tap on the menu icon (icon:bars[role="blue"]) in the top left corner of the app.
. Tap on *Settings*.
. Tap on *Appearance*.
. Tap on a background image or a background colour. +
→ The background will change. +
. Tap on the check mark (icon:check[role="blue"]) to confirm the change.

[#2100]
== Updating the app

Are you looking forward to an upcoming feature? We’re happy to keep you in the loop about changes to the software! Each version of the app gets its own version number. You can see a record of changes in our changelog. link:https://forum.plentymarkets.com/c/changelog/changelog-app[Subscribe to the changelog^] and always stay up to date.


//Wie kommen updates rein? Automatisch über den Play-Store oder muss der Händler aktiv etwas machen?
