= eBay Feedback
:lang: en
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: reply to eBay feedback, replying to eBay feedback, answer ebay feedback
:description: Multi-Channel in plentymarkets: Set up the plugin eBay Feedback in your plentymarkets system.
:position: 20
:url: markets/ebay/ebay-plugins/ebay-feedback
:id: RUNTV0K

Use the plugin link:https://marketplace.plentymarkets.com/en/plugins/channels/marketplaces/ebayfeedback_5537[eBay Feedback^]{nbsp}icon:external-link[] to reply to eBay feedback.

[IMPORTANT]
.Required plugins
====
To use the eBay Feedback plugin, you need the following plugins:

* link:https://marketplace.plentymarkets.com/en/plugins/channels/marketplaces/ebayfeedback_5537[eBay Feedback^]{nbsp}icon:external-link[]
* link:https://marketplace.plentymarkets.com/en/plugins/channels/marktplaetze/ebayoauth2_4787[eBay OAuth2^]{nbsp}icon:external-link[]
* link:https://marketplace.plentymarkets.com/en/plugins/sales/marktplaetze/ebaysdk_4784[eBay SDK^]{nbsp}icon:external-link[]

You can download the plugins in the link:https://marketplace.plentymarkets.com/en[plentyMarketplace^]{nbsp}icon:external-link[].
====

:plugin: eBay Feedback
include::../../_textblocks/instructions/plugin-installation.adoc[]

:plugin: eBay OAuth2
include::../../_textblocks/instructions/plugin-installation.adoc[]

:plugin: eBay SDK
include::../../_textblocks/instructions/plugin-installation.adoc[]

== Setting up the ticket import

Unanswered feedback is retrieved once a day. In order for the eBay feedback to be imported to your plentymarkets system, a ticket import must be set up. Use the menu *Setup » Markets » eBay » Feedback* to set up the ticket import.

You can choose which feedback types should be imported into your plentymarkets system. The feedback types *Positive*, *Neutral*, and *Negative* are available.

[.instruction]
Setting up the eBay feedback ticket import:

1. Go to *Setup » Markets » eBay » Feedback*.
2. In the *Settings* area, activate the option *Activate import*.
3. In the *Import feedback type* area, activate the feedback types that you want to import. +
*_Tip:_* The feedback types *Positive*, *Neutral*, and *Negative* are available. You can select one, several or all feedback types for the import.
4. In the *Ticket settings* area, select a *Client* from the drop-down list.
5. In the *Ticket settings* area, select a *Ticket role* from the drop-down list.
6. In the *Ticket settings* area, select a *Ticket type* from the drop-down list.
7. In the *Ticket settings* area, select a *Ticket status* from the drop-down list.
8. In the *User* area, activate the option *User*.
9. *Save* the settings.


== Replying to eBay feedback

Enter your reply to the eBay feedback in the ticket. Use the menu *Setup » CRM » Ticket system » Events* to create an event procedure to transfer your replies to eBay.

[.instruction]
Setting up an event procedure:

1. Go to *Setup » CRM » Ticket system » Events*.
2. Click on *Add event procedure*.
3. Enter a for the event procedure.
4. Select an event from the drop-down list, e.g. *New message from employee*.
5. *Save* the settings.
6. Click on *Add filter* and select the filters you want.
7. Click on *Add procedure*.
8. Add *Plugins > Answer eBay feedback*.
9. Place a check mark next to the option *Active*.
10. *Save* the settings.

== Linking tags to eBay feedback

It is possible to link tags to eBay feedback. n order to link your tags to eBay feedback types, you have to activate those tags for the ticket system first. This is done in the *Setup » Settings » Tags* menu.

[.instruction]
Activating tags for the ticket system:

1. Go to *Setup » Settings » Tags*.
2. Click on the tag that you want to activate for the ticket system.
3. Activate the option *Ticket system*.
4. *Save* the settings.

[.instruction]
Linking tags to eBay feedback:

1. Go to *Setup » Markets » eBay » Feedback*. +
→ The feedback types *Positive*, *Neutral*, and *Negative* are shown on the right-hand side.
2. Click on the feedback type that you want to link to a tag. +
→ A drop-down list containing your tags opens.
3. From the drop-down list, select the tag that you want to link to the eBay feedback type.
4. *Save* the settings.

== Assigning rights

Assign the required rights for the eBay Feedback plugin.

=== Setting owner rights for the ticket system

Users must have owner rights in order to create tickets for the feedback import. Go to *Setup » Settings » User » Accounts* to assign owner rights.

[.instruction]
Setting owner rights for the ticket system:

1. Go to *Setup » Settings » User » Accounts*.
2. Open the *user account*.
3. Click on the *Owner* tab.
4. Activate the option *Ticket*.
5. *Save* the settings.

=== Assigning rights for back end users

Users of the user class *Back end* need menu rights to use the *eBay Feedback* plugin.

Use the *Setup » Settings » User » Accounts » User account » Tab: Right* menu to assign rights.

TIP: Use the filter function to search for users of the user class *Back end*. To do so, go to the tab *Filter* and select the filter *Back end* within the drop-down list *Class*. Click on *Search*.

[.instruction]
Assigning rights for back end users:

1. Go to *Setup » Settings » User » Accounts*.
2. Click on the *user* that you want to give rights to.
3. Go to *Tab: Right » Tab: Menu*.
4. Activating the required rights:
  - Settings » Markets » eBay » *Feedback*
  - CRM » *Ticket system*
5. *Save* the settings.
