= E-mail when item becomes available
:lang: en
// include::{includedir}/_header.adoc[]
:description: plentymarkets informs interested parties when an item becomes available
:position: 10

==  Sending an e-mail to a customer once an item is available

Sometimes items are temporarily out of stock and can not be delivered. Customers should be allowed to save their e-mail addresses if they are interested in purchasing an item that can not be delivered at the moment. The e-mail address is then used to inform the customer once the item is back in stock. The e-mail should only be sent once, rather than every time the item's net stock is positive. This case example demonstrates how all this is done.

==  Creating an e-mail template

First, create an **<<omni-channel/online-store/cms-syntax#email-email, e-mail template>>**. Once the item is back in stock, this e-mail will be sent to all of the customers who saved their e-mail addresses. Below, you will find a list of template variables and template functions that can be used for this e-mail template. We also provide you with an example text, which you can customize as needed.

Possible template variables and template functions for an e-mail template regarding item availability:

[cols="a,a"]
|====
| Variable/function | Explanation

|**$ItemASIN**
| Amazon Standard Ident Number (ASIN) of the item

|**$ItemEAN**
| International item number (EAN)

|**$ItemImageURL**
| Item image URL

|**$ItemISBN**
| Item ISBN code

|**$ItemModel**
| Item model name

|**$ItemName**
| Item name

|**$ItemNumber**
| Item number

|**$ItemPrice**
| Gross item price

|**$ItemPriceNet**
| Net item price

|**$ItemProducerName**
| Item manufacturer

|**$VariantName**
| Item variation

|**{% Link_Item($ItemID) %}**
| Link to the item in the online store
|====

__Table 1: possible template variables and template functions for an e-mail template regarding item availability__

An example text for the e-mail template is displayed below. You can customize this example text to meet your needs. Open the e-mail template and insert this text into the tab **Content » Text in HTML format**. Proceed as described below to save this text or a different text for the e-mail template.

[.instruction]
Saving text for the e-mail template:

.  Create a new **<<omni-channel/online-store/cms-syntax#email-email, e-mail template>>** in HTML format.
.  Copy the example text (__Message__). Open the tab **E-mail message » Content » Text in HTML format** with the syntax editor and insert the text into the text field.
.  Edit the example text and the HTML formatting to meet your needs.
.  Copy the second example. Open the tab **Item list** with the syntax editor and insert the example into the text field.

[.instruction]
Message

[source,plenty]
----
include::assets/EX-EN-E-Mail-Template-Item-Availability.html[]

----

[.instruction]
Item list

[source,plenty]
----
include::assets/EX-EN-E-Mail-Template-Item-Availability-Item-List.html[]

----

==  Linking an e-mail template for automatic e-mailing

Now link the e-mail template with the option **Notification when item is in stock**. Once the item is back in stock, the template is sent to all interested parties who saved their e-mail addresses. To do so, proceed as follows.

[.instruction]
Linking an e-mail template for automatic e-mailing:

.  Go to **System » Client » Select client » Email » Automatic**.
.  Select the e-mail template from the drop-down menu **Notification when item is in stock**.

==  Editing an inserting the example code for the form

Next you need to insert a form into your design. This form is displayed if an item can not be delivered. At minimum, this form should consist of an entry field and a button. Interested parties enter their e-mail addresses into the field. By clicking on the button, the interested party agrees to receiving an e-mail when the item becomes available. The REST call **/rest/positive_stock_notification/** saves the e-mail address and notifies all of the saved e-mail addresses once the item's net stock is positive.

Further below, you will find an example code which is suited to our responsive design **Callisto Light**. Use this code as the basis for inserting the form in your design. Edit the code to meet your needs before you use it in your online store. Proceed as described below to insert the example code in your design.

[.instruction]
Inserting example code into the design:

.  Edit the example code to adjust it to your requirements.
.  Copy the code to the clipboard (**Ctrl + C** or **Cmd + C**).
.  Go to **CMS » Web design » Layout » ItemView » ItemViewSingleItem**.
.  Insert the code example at an appropriate position of the template.

[source,plenty]
----
include::assets/EX-EN-REST-positive-stock-notification.html[]

----

Activate the option **Client check** under **Attribute availability** in the menu **System » Client » Select client » Item layouts » Settings** and add the following code example to dynamically show or hide the previously created form depending on the availability of the variation.

[.instruction]
Inserting example code into the design:

.  Edit the example code to adjust it to your requirements.
.  Copy the code to the clipboard (**Ctrl + C** or **Cmd + C**).
.  Go to **CMS » Web design » Layout » ItemView » ItemViewSingleItem**.
. Search for the code line **$(window).on('variationChanged', function(event, variation) {**.
.  Insert the code example below the code line.

[source,plenty]
----
include::assets/EX-EN-REST-positive-stock-notification-dynamic.html[]

----
