////
zuletzt bearbeitet 30.12.2020
////

Artikeldaten werden in plentymarkets zentral verwaltet.
Das heißt, dass du deine Produktdaten zuerst in plentymarkets einpflegst, um die Ware anschließend auf diversen <<maerkte#, Marktplätzen>>, im eigenen <<webshop#, plentyShop>> und im <<pos#, stationären Laden>> zu verkaufen.

Müssen Daten, wie z.B. die Beschreibung oder der Preis eines Artikels, zu einem späteren Zeitpunkt geändert werden, musst du diese Daten lediglich zentral in plentymarkets ändern.
Die Änderung kann automatisch auf allen genutzten Vertriebskanälen angezeigt werden.

[#100]
== Einführung in die Artikelstruktur

Du bist neu bei plentymarkets? Bevor du deine Daten einpflegst, lerne die Artikelstruktur kennen! Die Einführung bietet dir einen Überblick über das Thema und beantwortet deine grundlegenden Fragen:

* Was ist der Unterschied zwischen <<artikel/einleitung/struktur#, Artikeln und Varianten>>?
* Wie funktioniert die <<artikel/einleitung/vererbung#, Vererbung>>?
* Wo finde ich meine <<artikel/einleitung/suche#100, Artikel im Backend>>?
* Kann ich auch ein paar <<artikel/einleitung/suche#900, Beispielartikel>> sehen?

[#200]
== Vorbereitende Einstellungen

//tag::vorbereitung[]
Zu deinen Artikeldaten gehören diverse Angaben, wie z.B. Kategorien, Preise und Hersteller.
Bevor du aber einen Artikel in eine bestimmte Kategorie einsortieren kannst, muss die Kategorie erst einmal in plentymarkets existieren.
Bevor du den Hersteller eines Artikels auswählen kannst, müssen die Herstellerdaten in plentymarkets vorhanden sein.
//end::vorbereitung[]

Nachdem du solche <<artikel/einstellungen#, vorbereitenden Einstellungen>> einmalig in plentymarkets gespeichert hast, kannst du sie daraufhin auf alle zutreffenden Artikel und Varianten anwenden.

include::../../einleitung/struktur.adoc[tag=systemeinstellungen-liste]

[#300]
== Import, Export und manuelle Anlage von Artikeldaten

//tag::import-export-anlage[]

////
Link <<Assistenten>> ändern sobald neue Seiten-Struktur steht. Prüfe auf dieser Seite und Basis-Seite, dass die Assistenten richtig benannt wurden.
////

Bist du bereit, deine Artikeldaten in plentymarkets einzupflegen? Hierfür stehen dir einige Tools zur Verfügung. Am einfachsten importierst du deine Artikel- und Variantendaten mit Hilfe eines <<willkommen/assistenten#, Assistenten>>.

Es ist aber auch möglich, Produktdaten <<artikel/import-export-anlage/anlage/neue-artikel#, manuell in plentymarkets zu erstellen>> oder Produktdaten zwischen deinem plentymarkets System und anderen, externen Systemen auszutauschen. Du kannst Artikeldatensätze z.B.:

* aus vorhandenen <<maerkte/ebay/ebay-einrichten#11000, eBay-Listings>> importieren.
* in CSV-Dateien pflegen und anschließend <<artikel/import-export-anlage/import#, importieren>>.
* aus externen Systemen mit der <<daten/rest-api#, REST-API>> importieren.
* aus deinem plentymarkets-System <<artikel/import-export-anlage/export#, exportieren>>.
//end::import-export-anlage[]

[#400]
== Darstellung im plentyShop

//tag::darstellung-webshop[]
Sobald deine Artikeldaten in plentymarkets vorhanden sind, geht es mit dem Verkauf weiter.
plentymarkets enthält einen kostenlosen <<webshop#, Webshop>>, aus dem du deine Artikel vertreiben kannst.

In diesem Themenbereich findest du schnelle Hilfe, falls deine <<artikel/webshop/checkliste-artikel-anzeige#, Artikel nicht im plentyShop angezeigt werden>> oder deine <<artikel/webshop/checkliste-kategorien-anzeige#, Kategorien nicht im plentyShop angezeigt werden>>.
Du lernst außerdem, wie du zusätzliche Funktionen einrichtest, um Artikel genau nach deiner Vorstellung zu präsentieren:

* <<artikel/webshop/suchleiste#, Suchleiste>>
* <<artikel/frontend-artikelsuche-verwalten#, Suchfilter>>
* <<artikel/webshop/cross-selling#, Cross-Selling>>
* <<artikel/webshop/shop-aktionen#, Shop-Aktionen>>
//end::darstellung-webshop[]

[#500]
== Anwendungsfälle

//tag::anwendungsfaelle[]
Hast du einen bestimmten Anwendungsfall im Sinn?
In diesem Themenbereich lernst du:

//* Artikeldaten in mehreren Sprachen zu pflegen
* <<artikel/anwendungsfaelle/multipacks-pakete-sets#, Produkte zu kombinieren>> und als Verkaufseinheit anzubieten
* <<artikel/anwendungsfaelle/personalisierte-artikel#, Personalisierte Artikel>> in deinem plentyShop zu verkaufen
* <<artikel/anwendungsfaelle/gratiszugaben#, Gratisartikel und Werbegeschenke>> zu einer Bestellung hinzuzufügen
* Mit Artikeln zu arbeiten, die <<artikel/anwendungsfaelle/seriennummern#, Seriennummern oder Lizenzschlüssel>> haben
* <<artikel/anwendungsfaelle/aenderungen#, Änderungen an Artikeln nachzuvollziehen>>, d.h. den ganzen Lebensweg eines Artikels zu verfolgen
* Das <<artikel/anwendungsfaelle/suchverhalten#, vordefinierte Artikelsuchverhalten>> im plentymarkets Backend zu modifizieren
//end::anwendungsfaelle[]
