Artikeldaten werden in plentymarkets zentral verwaltet. Das heißt, dass du deine Produktdaten zuerst in plentymarkets einpflegen musst, um die Ware anschließend auf diversen <<maerkte#, Marktplätzen>>, im eigenen <<webshop#, Webshop>> und im <<pos#, stationären Laden>> zu verkaufen.

Müssen Daten, wie z.B. die Beschreibung oder der Preis eines Artikels, zu einem späteren Zeitpunkt geändert werden, musst du diese Daten lediglich zentral in plentymarkets ändern. Die Änderung erscheint automatisch auf allen genutzten Vertriebskanälen.

[#100]
== Einführung in die Artikelstruktur

Du bist neu bei plentymarkets? Bevor du deine Daten einpflegst, lerne die Artikelstruktur kennen! Die Einführung bietet dir einen Überblick über das Thema und beantwortet deine grundlegenden Fragen:

* Was ist der Unterschied zwischen <<artikel/einleitung/struktur#, Artikeln und Varianten>>?
* Wie funktioniert die <<artikel/einleitung/vererbung#, Vererbung>>?
* Wie kann ich <<artikel/einleitung/suche#100, nach Artikeln suchen>>?
* Kann ich auch ein paar <<artikel/einleitung/suche#900, Beispielartikel>> sehen?

[#200]
== Vorbereitende Einstellungen

Zu deinen Artikeldaten gehören diverse Angaben, wie z.B. Kategorien, Preise, Hersteller, Beschreibungstexte und Bilder. Manchmal ist allerdings ein bisschen Vorarbeit nötig.

Bevor du einen Artikel in eine bestimmte Kategorie einsortieren kannst, muss die Kategorie erst einmal in plentymarkets existieren. Bevor du den Hersteller eines Artikels auswählen kannst, müssen die Herstellerdaten in plentymarkets vorhanden sein.

Nachdem du solche <<artikel/einstellungen#, vorbereitenden Einstellungen>> einmalig in plentymarkets gespeichert hast, kannst du sie daraufhin auf alle zutreffenden Artikel und Varianten anwenden.

[#300]
== Import, Export und manuelle Erstellung von Artikeldaten

//Link <<Assistenten>> ändern sobald neue Seiten-Struktur steht. Prüfe auf dieser Seite und Basis-Seite, dass die Assistenten richtig benannt wurden.
Bist du bereit, deine Artikeldaten in plentymarkets einzupflegen? Hierfür stehen dir einige Tools zur Verfügung. Am einfachsten importierst du deine Artikel- und Variantendaten mit Hilfe eines <<basics/assistenten#, Assistenten>>.

//Link <<artikel/artikel-verwalten#20, manuell in plentymarkets zu erstellen>> ändern sobald neue Seiten-Struktur steht
Es ist aber auch möglich, Produktdaten <<artikel/artikel-verwalten#20, manuell in plentymarkets zu erstellen>> oder Produktdaten zwischen deinem plentymarkets System und anderen, externen Systemen auszutauschen. Du kannst Artikeldatensätze z.B.:

* aus vorhandenen <<maerkte/ebay/ebay-einrichten#11000, eBay-Listings>> importieren.
* in CSV-Dateien pflegen und mit <<daten/daten-importieren/ElasticSync#, ElasticSync>> importieren.
* aus externen Systemen mit der <<basics/admin-aufgaben/rest-api#, REST-API>> importieren.
* mit dem <<daten/daten-exportieren/FormatDesigner#, FormatDesigner>> aus plentymarkets exportieren.

[#400]
== Darstellung von Artikeln im Webshop

Sobald deine Artikeldaten in plentymarkets vorhanden sind, geht es mit dem Verkauf weiter. plentymarkets enthält einen kostenlosen <<webshop#, Webshop>>, aus dem du deine Artikel vertreiben kannst.

In diesem Themenbereich findest du schnelle Hilfe, falls deine <<artikel/webshop/checkliste-artikel-anzeige#, Artikel>> oder <<artikel/webshop/checkliste-kategorien-anzeige#, Kategorien nicht im Webshop angezeigt>> werden. Du lernst außerdem, wie du zusätzliche Funktionen einrichtest, um Artikel genau nach deiner Vorstellung zu präsentieren:

* <<artikel/frontend-artikelsuche-verwalten#, Facettensuche>>
* <<artikel/webshop/cross-selling#, Cross-Selling>>
* <<artikel/webshop/shop-aktionen#, Shop-Aktionen>>

[#500]
== Anwendungsfälle

Hast du einen bestimmten Anwendungsfall im Sinn? In diesem Themenbereich lernst du:

//Diese 3 Links anpassen, sobald neue Seiten-Struktur steht
* <<artikel/artikel-verwalten#420, Artikeldaten in mehreren Sprachen>> zu pflegen
* <<artikel/multipacks-pakete-sets-verwalten#, Produkte zu kombinieren>> und als Verkaufseinheit anzubieten
* <<artikel/artikel-verwalten#4300, Gratisartikel und Werbegeschenke>> zu einer Bestellung hinzuzufügen
