= Listing
:lang: de
include::{includedir}/_header.adoc[]
:keywords: FormatDesigner, Format-Typen, Export, Data, Listing, eBay, Hood, ricardo
:description: Mit Formaten des Typs Listing exportierst du Listings.
:position: 140
:url: daten/daten-exportieren/FormatDesigner/format-typen/listing
:author: team-multi-channel
:id: AHTOWEL

Mit Formaten des Typs *Listing* exportierst du Listings.

[#100]
== Listing

In <<#tabelle-listing>> werden Felder erläutert, die für den Export von Listing-Daten zur Verfügung stehen.

[[tabelle-listing]]
.Felder für Export von Listings
[cols="1,3"]
|====
|Feld |Erläuterung

|id
|

|itemID
|

|stockDependenceTypeId
|

|typeId
|

|unitCombinationId
|
|====

[#200]
== ListingMarket

In <<#tabelle-listing-market>> werden Felder erläutert, die für den Export von Market-Listings zur Verfügung stehen.

[[tabelle-listing-market]]
.Felder für Export von Market-Listings
[cols="1,3"]
|====
|Feld |Erläuterung

|allVariations
|

|createdAt
|

|credentialsId
|

|directoryId
|

|duration
|

|enabled
|

|id
|

|listingId
|

|quantity
|

|referrerId
|

|updatedAt
|

|variationId
|

|verified
|
|====

[#300]
== ListingMarketDate

In <<#tabelle-listing-market-date>> werden Felder erläutert, die für den Export von Market-Listing-Daten zur Verfügung stehen.

[[tabelle-listing-market-date]]
.Felder für Export von Market-Listing-Daten
[cols="1,3"]
|====
|Feld |Erläuterung

|date
|Wert für das Datum des Market-Listings. Mögliche Zuordnungen: +
Letzte Preisänderung +
Letzter Einstellversuch +
Startzeit +
Endzeit
|====

[#400]
== ListingMarketInfo

In <<#tabelle-listing-market-info>> werden Felder erläutert, die für den Export von Market-Listing-Daten zur Verfügung stehen.

[[tabelle-listing-market-info]]
.Felder für Export von Market-Listing-Daten
[cols="1,3"]
|====
|Feld |Erläuterung

|code
|

|createdAt
|

|id
|

|listingMarketId
|

|message
|

|type
|
|====

[#500]
== ListingMarketPrice

In <<#tabelle-listing-market-price>> werden Felder erläutert, die für den Export von Market-Listing-Preisen zur Verfügung stehen.

[[tabelle-listing-market-price]]
.Felder für Export von Market-Listing-Preisen
[cols="1,3"]
|====
|Feld |Erläuterung

|currency
|

|value
|Wert für den Preis des Market-Listings. Mögliche Zuordnungen: +
Startpreis +
Festpreis +
Mindestpreis +
SCO-Mindestpreis
|====

[#600]
== ListingMarketProperty

In <<#tabelle-listing-market-property>> werden Felder erläutert, die für den Export von Market-Listing-Eigenschaften zur Verfügung stehen.

[[tabelle-listing-market-property]]
.Felder für Export von Market-Listing-Eigenschaften
[cols="1,3"]
|====
|Feld |Erläuterung

|value
|Listing-Eigenschaft. Mögliche Zuordnungen: +
Versandprofil-ID +
Auftragsstatus +
Layout-Vorlagen-ID +
Anzahl der Bilder +
Lager-ID +
Grundpreisangabe ergänzen +
Mehrwertsteuersatz +
MwSt.-Land +
Sprache +
Anzahl je Posten +
Als Artikelnummer übertragen +
Wiedereingestellte externe Listing-ID +
Second Chance Offer +
Sonderaktion +
UUID +
Listing fehlerhaft +
Mit allen Varianten listen +
Listing beenden +
Erstellt durch +
Zahlungsarten +
Kategorie-ID 1 +
Kategorie-ID 2 +
Shop-Kategorie-ID 1 +
Shop-Kategorie-ID 2 +
Shop-Kategorie-ID 3 +
Zusatzoptionen +
Fahrzeugverwendungslisten-ID +
eBay parallel aktive Market-Listings +
eBay-Privat-Auktion +
eBay-Galerietyp +
eBay-Premium-Angebot +
eBay UVP übertragen +
eBay-Besucherzähler +
eBay-Zustands-ID +
eBay-Zustandsbeschreibung +
eBay-Preisvorschlag +
eBay-Mindestpreis ablehnen +
eBay-Mindestpreis annehmen +
eBay Plus +
eBay Click & Collect +
eBay-Bilderservice verwenden +
Ansicht auf Hood-Shop-Startseite +
Hood-Versandrabatt +
Hood-Lieferzeit bei Bestand ab (in Tagen) +
Hood-Lieferzeit bei Bestand bis (in Tagen) +
Hood-Lieferzeit ohne Bestand ab (in Tagen) +
Hood-Lieferzeit ohne Bestand bis (in Tagen) +
ricardo-Garantie-ID +
ricardo-Lieferkonditionen +
ricardo-Verfügbarkeits-ID
ricardo-Lieferkosten +
ricardo-Zahlungskondition-ID +
ricardo-Erhöhungsschritt +
ricardo-Zustands-ID +
ricardo Anzahl Reaktivierungen +
ricardo Separate Lieferkosten für jeden einzelnen Artikel +
ricardo-Packungsgröße +
ricardo Alternative Sprache verwenden +
ricardo-Template-ID +
ricardo Reaktivierung bis Ausverkauf
|====

[#700]
== ListingMarketSpecific

In <<#tabelle-listing-market-specific>> werden Felder erläutert, die für den Export von Market-Listing-Merkmalen zur Verfügung stehen.

[[tabelle-listing-market-specific]]
.Felder für Export von Market-Listing-Merkmalen
[cols="1,3"]
|====
|Feld |Erläuterung

|id
|

|listingMarketId
|

|name
|

|value
|
|====

[#800]
== ListingMarketText

In <<#tabelle-listing-market-text>> werden Felder erläutert, die für den Export von Market-Listing-Texten zur Verfügung stehen.

[[tabelle-listing-market-text]]
.Felder für Export von Market-Listing-Texten
[cols="1,3"]
|====
|Feld |Erläuterung

|description
|

|id
|

|lang
|

|listingMarketId
|

|subtitle
|

|title
|
|====

[#900]
== ListingProperty

In <<#tabelle-listing-property>> werden Felder erläutert, die für den Export von Listing-Eigenschaften zur Verfügung stehen.

[[tabelle-listing-property]]
.Felder für Export von Listing-Eigenschaften
[cols="1,3"]
|====
|Feld |Erläuterung

|value
|Wert für Listing-Eigenschaft. Mögliche Zuordnungen: +
An Artikelpreis binden +
Anzahl je Posten +
Als Artikelnummer übertragen
|====

[#1000]
== custom_value

Für den Export von eigenen Werten stehen die in <<#tabelle-custom-value>> aufgelisteten Felder zur Verfügung.

[[tabelle-custom-value]]
.Felder für Export von eigenen Werten
[cols="1,3"]
|====
|Feld |Erläuterung

|custom_value
|
|====

[#1100]
== date

 Für den Export des aktuellen Datums steht das in <<#tabelle-date>> aufgeführte Feld zur Verfügung. Weitere Informationen findest du link:https://www.php.net/manual/de/function.date.php[hier^].

[[tabelle-date]]
.Feld für Export des aktuellen Datums
[cols="1,3"]
|====
|Feld |Erläuterung

|date
|
|====
