name: Linting
on:
  pull_request:
    branches: [ master ]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Vale
      uses: errata-ai/vale-action@v1.2.0
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
