name: lint-manual

on:
  pull_request:
    branches: [ master ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: Vale Linter
      uses: errata-ai/vale-action@v1.2.0
      env: ${{secrets.VALE_ACTION}}
