name: Linting
on:
  pull_request:
    branches: [ master ]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Vale
      uses: gaurav-nelson/github-action-vale-lint@0.1.0
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
