= real.de
:lang: en
include::{includedir}/_header.adoc[]
:description: Multi-Channel in plentymarkets: Set up the interface to the market real,de in your plentymarkets system.
:position: 1

link:https://www.real.de.de[*real.de*^] is one of the largest fixed price markets in Germany. You can sell items in various product categories on real.de. real.de also processes payments for you. In other words, you are neither charged with payment costs nor do you have to worry about debt collection.

[#10]
== Registering with real.de

In order to use the real.de interface, you have to register your real.de user account as a seller account. To do this, go to the *link:https://www.real.de.[real.de website^]* and save your VAT number in the *Mein Konto* (My account) area. Please note that the real.de website is currently only available in German.

[#20]
== Setting up real.de in plentymarkets

Set up real.de in plentymarkets to offer items on real.de. In order to set up real.de in plentymarkets, you need your real.de interface access data. You can set up a real.de account for each online store or client (store).

[.instruction]
Setting up the access for real.de:

. Go to *System » Markets » real.de » Settings*.
. Open the submenu of the online store that you want to set up access for.
. Carry out the settings as desired. Pay attention to the information given in table 1.
. *Save* the settings.

[cols="a,a"]
|====
|Setting |Explanation

|*Active*
|*Yes* = The real.de interface is active. +
*No* = The interface is inactive.

|*Client Key*
|Enter the client key that you received from real.de.

|*Secret Key*
|Enter the secret key that you received from real.de.

|*Transfer the availability of the items*
|Select *Yes* or *No*. +
*Yes* = The item's *availability* will be transferred. +
*No* = The item's *availability* will not be transferred.

|*Incoming payment*
|This setting applies to the order import. Orders are imported either as paid or not paid. Regardless of this setting, items will immediately be cleared for shipping when they have sufficient stock. With the setting *open*, one could also set the order to paid when the actual incoming payment from real.de is received. In this way, real.de could be tested.

|*Comments on items*
|Set up *free text fields* for item comments here or assign this function to the *Global item comment* field.

|*Global item comment*
|Here you can enter a text that will be displayed with every offer.

|*Item quantity for items that are not limited to stock*
|Items for which *no limitation* has been selected in the *<<stock-management/managing-stocks#, Stock>>*  tab of an item will be offered on real.de with the quantity entered here. As soon as an item has been sold, the quantity saved here will be newly transmitted for sale at the next full hour.

|*Price column "lowest automatic price"*
|Select the price column for the lowest automatic price, i.e. the lowest price which you want to offer the item for. +
The lowest price of the item must be entered in the field of the selected price column. +
*Important*: The lowest automatic price does not go into effect for item variations which have surcharges for attributes. In this case, *deactivate* the lowest automatic price. If you would like to use the lowest automatic price, then create each variation as a separate item with a defined price column for the lowest automatic price.

|*Shipping service provider mapping*
|After the shipment has been confirmed, this option allows real.de to use the package number in order to send the customer an email with the correct tracking link. +
*Important*: You have to assign each of your service providers to one of the service providers from the drop-down menu.

|*Items with flags only*
|*All items* = All items will be exported. +
*All items with flag 1* or *2* = All items with this flag will be exported. +
*All items without flag 1* or *2* = All items without this flag will be exported. +
Select one particular flag = Only items with this flag will be exported.

|*Generate cache file (Inventory)*
|Select *Yes* or *No*. +
*Yes* = Stock will be saved in the cache daily.  +
*No* = Stock will not be saved in the cache. +
*Note:* We recommend using the option *yes*, since bigger stock changes may result in errors.

|*Add technical data to the item description*
|Select whether the technical data saved in the *Texts* tab of an item should be added to the item description for real.de. *Yes* is selected by default.

|*Preview all items*
|This option will create a preview of your items for real.de.

|*Item file preview*
|This option will create a preview of the item file.
|====

__Table 1: settings for the market real.de__

Connecting to this market allows for the following automatic processes to take place:

* hourly stock and price synchronisation
* daily item export
* hourly order import
* hourly transfer of the flag *Cancelled* or *Sent* to real.de +
→ *Sent* will be transferred after the outgoing items have been booked. *Cancelled* will be transferred when the status reaches 8 or 8.x.
* export of surcharges for attribute values (item variations)
* Transfer of the description text saved in the *Texts* tab
* transfer of the technical data selected in table 1
* image export selected in the item's *Images* tab

[#30]
== Setting the item availability

Items have to be available for real.de. This is done in the *Availability* tab of an item within the *<<item/managing-items#40, Item » Edit item » Tab: Variation ID>>* menu.

[.instruction]
Setting the item availability for real.de:

. Open the *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings* menu.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the *Markets* section in the selection field.  +
→ A list with all available markets will be displayed.
. Activate the option *real.de*.
. Activate the option *Web API*.
. Click on *Add*. +
→ The Market will be added.
. *Save* the settings.  +
→ The item is available on real.de.

The availability for variations can be individually edit in the *Item » Edit item » Open item » Tab: Variation ID » Open variation » Tab: Availability* menu.

[.subhead]
Further requirements for the item availability
In order for your items to be available on the market real.de, the following requirements must also be met:

* If you are working with item variations, then click on the *<<stock-management/managing-stocks#, Stock>>* tab of the item and make sure that the limitation is not set to *No limitation*.sein.
* You are required to specify an EAN or ISBN. Otherwise, the item will not be transferred to real.de.

[#40]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer real.de. This price will be displayed on real.de.

[.instruction]
Creating a sales price for real.de:

. Open the menu *System » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a checkmark next to the referrer *real.de*.
. *Save* the settings.

[#50]
== Linking properties

In order to use *<<item/managing-items#480, properties>>*  for the real.de market, these properties have to be linked with real.de.

[.instruction]
Linking the property:

. Go to *System » Item » Properties*.
. Expand the property.
. Activate the option *real.de*.
. *Save* the settings.

[#60]
== Linking categories

Link your online store categories to the real.de categories in order to display your items in these categories. Further items from the linked category will be assigned automatically.

[.instruction]
Linking categories:

. Go to *System » Markets » real.de » Category link*.
. Click on *Search*.  +
→ The *Select category* window will open.
. Select the real.de category that best matches your online store category.
. Click on *Accept*. +
→ The ID and category path of the real.de category will be displayed.
. If you already know the ID of the real.de category, enter it directly into the *Market category* field to link it to your online store category.
. *Save* the settings.

[IMPORTANT]
.Subcategories do not have to be linked
====
In some cases, your subcategories may not match the real.de subcategories. In this case, link your items with real.de's corresponding main category. real.de will automatically assign your items to a subcategory. You should not transfer items to real.de that were not assigned to a real.de category.
====

[#70]
== Linking real.de attributes as properties

real.de attributes are linked as properties. Create a new property for each real.de attribute and link it with real.de. The following example describes how to create the real.de attribute *ean* and link it with real.de. +
Afterwards, create the real.de attributes *title*, *description*, *manufacturer* and *picture* in the same way. Select the property type *File* for the real.de attribute *picture*. Select the property type *Text* for the other real.de attributes.

[WARNING]
.Mandatory entries for the item export
====
The real.de attributes *ean*, *title*, *description*, *manufacturer* and *picture* are mandatory entries for the item export.
====

[.instruction]
Creating a property:

. Go to *System » Item » Properties*.
. Click on the *New property* tab.
. Enter *ean* in the *Back end name* field. +
→ This name will be displayed in the item data record when linking properties.
. Enter a name in the *Webshop* field. +
→ This name is used in the item overview.
. Select the *Property type*.
. Activate the option *real.de*.
. *Save* the settings.

[#80]
== Activating the payment method

Activate the *<<order-processing/payment#, payment method>>*  *real.de Payment* as described below.

[.instruction]
Activating real.de Payment:

. Go to *System » Orders » Payment » Methods*.
. Click on the folder *DE &gt;  real.de Payment*.  +
→ The settings for the real.de payment method will be displayed.
. Carry out the settings as desired. Pay attention to the information given in table 2.
. Place a check mark next to the option *Active*.
. *Save* the settings.

[cols="a,a"]
|====
|Setting |Explanation

|*Language*
|The following options are saved for the language selected: *Name*, *Info page*, *Info page (internal)*, *Logo* and *Upload logo*. This makes it possible to enter values for these options in various languages. The values for a language will be activated as soon as a buyer selects the language in the online store.

|*Name*
|Enter the name that should be displayed in the online store and on invoices etc.

|*Info page*
|Select a category page of the type *content* or enter the URL of a website to provide information about the payment method.

|*Info page (external)*
|If you selected the option *Info page (external)* under *Info page*, then enter the URL of the info page here.

|*Countries of delivery*
|Do not select a country of delivery. +
You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely configured.

|*Logo*
|Select one of the following options for displaying the logo: +
*Show standard logo* = The logo that is saved in plentymarkets for this payment method will be displayed.  +
*Do not show a logo* = The logo that is saved in plentymarkets for this payment method will not be displayed. +
*Show upload logo* = The options *Logo view* and *Upload logo* will be displayed.

|*Logo view*
|If *Show upload logo* was selected from the *Logo* drop-down menu, then the logo that was uploaded will be displayed here.

|*Upload logo*
|If *Show upload logo* was selected from the *Logo* drop-down menu, then you will be able to upload an external logo here. +
Click on *Upload files* and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG and JPG.

|*Priority*
|Select the priority for displaying the payment method in the online store.

|*Costs: Flat rate or percentage*
|If the payment method results in additional costs, enter the percentage value or flat rate value. The choice depends on the conditions of your contract. *Important:* Do not enter a value into both fields.  +
For further information, refer to the *<<basics/statistics#, Statistics>>* and *<<basics/statistics/general-statistics/item/tops-flops#, Tops/Flops>>* pages of the manual. For an example for flat rate and percentage costs, refer to the *<<omni-channel/multi-channel/real-de#20, Basic settings>>* page of the manual.
|====

__Table 2: settings of the payment method__

[TIP]
.Permitting the payment method in customer classes
====
Go to *System » CRM » Classes* to activate or deactivate the *Permitted payment methods*.  +
For further information, refer to the *<<omni-channel/multi-channel/real-de#40, Payment methods and customer classes>>* chapter of the manual.
====

For further information, refer to the *<<order-processing/payment#, Payment methods>>*  page of the manual.

[IMPORTANT]
.No invoicing processes via event procedures
====
Invoices are transferred from real.de into your plentymarkets system. As such, it is not possible to use your system to generate your own invoices. This means that - in contrast to other markets - you cannot manage any invoicing processes via <<basics/automation/event-procedures#, *event procedures*>>.
====
