= Gratiszugaben
:lang: de
include::{includedir}/_header.adoc[]
:description: Lerne, wie du Gratisartikel oder Werbegeschenke zu einer Bestellung hinzufügst.
:url: artikel/anwendungsfaelle/gratiszugaben
:icons: font
:position: 20
:docinfodir: /workspace/manual-adoc
:docinfo1:
:table-event-procedure: <<tabelle-ereignisaktion-gratiszugabe>>

Mit Gratiszugaben generierst du höhere Umsätze in deinem Webshop, da solche Gratiszugaben dazu motivieren, mehr und öfter bei dir einzukaufen. Die grundlegende Idee ist einfach: Du bietest ab einem bestimmten Warenwert pro Einkauf eine Variante aus deinem Sortiment als Gratiszugabe an. Statt diese Variante jedem Auftrag manuell hinzuzufügen, automatisierst du diesen Vorgang in plentymarkets mit einer <<automatisierung/ereignisaktionen#, Ereignisaktion>>.

Dieses Video bietet dir eine Einführung in das Thema:

.Gratisartikel zu einer Bestellung hinzufügen
video::80183219[vimeo]

Du kannst auch Werbegeschenke hinzufügen, die du nicht in deinem Webshop verkaufen möchtest. Dazu stellst du die Variante auf *unsichtbar* und ordnest die Variante einer Kategorie zu, die nicht für den Webshop aktiviert ist.

include::../../_includes/textblocks/instructions/EA.adoc[]

[[tabelle-ereignisaktion-gratiszugabe]]
.Ereignisaktion für Gratiszugaben
[cols="1,2,2"]
|====
|Einstellung |Option |Auswahl

|**Ereignis**
|**Auftragsanlage > Neuer Auftrag**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag**

|**Filter 2**
|**Warenwert (brutto)**
|Operator wählen und Warenwert eingeben. +
*_Beispiel:_* Operator *>=*, Warenwert *50,00* = Variante wird ab 50 Euro Warenwert hinzugefügt

|*Aktion*
|*Variante &gt; Variante hinzufügen*
|ID der Variante eingeben.
|====

[TIP]
.Tipp: Gestaffeltes Bonussystem
====
Über mehrere Ereignisaktionen ist auch ein gestaffeltes Bonussystem möglich, bei dem je nach Warenwert unterschiedliche Varianten als Zugaben angeboten werden. In der ersten Ereignisaktion setzt du zum Beispiel die Filter *&gt;= 100,00 EUR* und *&lt; 200,00 EUR*. In der zweiten Ereignisaktion stellst du einen Warenwert *&gt;= 200 EUR* ein und fügst eine höherwertige Variante hinzu.
====
