= Multipacks, Artikelpakete und Sets
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Varianten gruppieren, Produkte zusammenfassen, Kombiangebote, Varianten kombinieren
:description: Erfahre, wie du Varianten in plentymarkets kombinierst, um sie im Paket zu verkaufen.
:position: 20
:url: artikel/anwendungsfaelle/multipacks-pakete-sets
:id: NXZCPXN
:author: team-item

plentymarkets bietet verschiedene Möglichkeiten, Produkte zu kombinieren und als eine Verkaufseinheit anzubieten.
//Bei einer Bestellung wird dann gleichzeitig mehr als ein Produkt in den Warenkorb gelegt.
<<table-combining-products>> vergleicht die Möglichkeiten und erläutert sie beispielhaft.

[TIP]
.Schon mit der Artikelverwaltung vertraut?
====
Diese Seite setzt voraus, dass du bereits <<artikel/einleitung#, Grundkenntnisse über die Artikelverwaltung>> in plentymarkets hast.
Beispielsweise wird angenommen, dass du:

* den <<artikel/einleitung/struktur#, Unterschied zwischen Artikeln und Varianten>> kennst.
* einige <<artikel/einstellungen#, vorbereitende Einstellungen>> in deinem System konfiguriert hast.
Zum Beispiel, dass du bereits eine <<artikel/einstellungen/kategorien#, Kategoriestruktur>> erstellt hast, <<fulfillment/versand-vorbereiten#1000, Versandprofile>> für deine Artikel eingerichtet hast, usw.
====

[[table-combining-products]]
.Produkte kombinieren und als Verkaufseinheit anbieten
[cols="1,5,1"]
|====
|Art |Erläuterung |Artikeltyp

|<<#1000, Multipack>>
a|*_Beispiel_*: 1 Flasche Wasser, eine Packung mit 6 Flaschen und eine
Packung mit 12 Flaschen.

*_Technische Angaben_*:

* Multipacks sind verschiedene Stückzahlen _derselben Variante_.
* Die Hauptvariante entspricht der _kleinsten Verkaufseinheit_ des Produkts, z.B. 1 Flasche.
* Alle weiteren Varianten sind _Kombinationen_ dieser kleinsten Verkaufseinheit, z.B. 6 oder 12 Flaschen.
//* Die Hauptvariante entspricht der Menge 1 der weiteren Varianten des Artikels.
* Bestand wird nur an der Hauptvariante verwaltet.
//* Die Varianten des Artikels entsprechen den verschiedenen Mengen der Hauptvariante.
|Multipack

|<<#2000, Paket>>
a|*_Beispiel_*: Ein Bartpflege-Kit bestehend aus einer Schere, einer Bürste, Bartöl und Bartwachs.

*_Technische Angaben_*:

* Pakete bestehen aus _unterschiedlichen Varianten_, die zusammengefasst und zu einem Paketpreis angeboten werden.
* Bestellt werden kann nur das komplette Paket. Die einzelnen Bestandteile können nicht gewählt werden.
//* Pakete bestehen aus je einer Variante verschiedener Artikel.
//* Bestellt werden kann nur das komplette Paket, die einzelnen Bestandteile können also nicht gewählt werden.
* Es ist möglich, Varianten mit _unterschiedlichen Steuersätzen_ zusammen in einem Paket anzubieten.
* Es ist auch möglich, den Paketpreis günstiger als die Summe der Einzelpreise zu definieren.
|Standard

|<<#3000, Set>>
a|*_Beispiel_*: Eine Fußballuniform bestehend aus einem Trikot, Shorts und Socken. Der Endkunde stellt sich seine eigene Uniform zusammen, indem er die gewünschte Größe und Farbe für jede der drei Komponenten auswählt.

*_Technische Angaben_*:

* Sets bestehen aus _mehreren Artikeln_ (Trikot, Shorts, Socken).
* Bei der Bestellung können Endkunden für jeden Artikel die gewünschte Variante wählen (Größe, Farbe).
* Die Hauptvariante selbst ist virtuell, kann also nicht verkauft werden.

*_Hinweis:_* Sets werden derzeit noch entwickelt.
Ab link:https://marketplace.plentymarkets.com/plugins/sales/online-shops/ceres_4697[Ceres 5] wird es möglich sein, Artikel-Sets im Webshop zu verkaufen. Es wird jedoch _nicht möglich_ sein, Artikel-Sets auf Märkten wie Amazon oder eBay zu verkaufen.
|Set
|====


[#1000]
== Multipacks

Bei einem Artikel des Typs *Multipack* entspricht die Hauptvariante der kleinsten Verkaufseinheit des Produkts. Alle weiteren Varianten des Artikels sind Kombinationen dieser kleinsten Verkaufseinheit. Der Bestand wird nur an der Hauptvariante gepflegt. Alle Varianten des Artikels haben dieselben Attribute. Das heißt, dass bei der Bestellung nicht zum Beispiel zwischen verschiedenen Farben oder Größen des Produkts gewählt werden kann. Im Onlineshop kann nur zwischen den verschiedenen Varianten gewählt werden, die der Anzahl des Produktes entspricht.

[#1100]
=== Artikel des Typs Multipack erstellen

Beim Erstellen eines neuen Multipacks wird wie bei Artikeln des Typs *Standard* automatisch eine Hauptvariante erstellt. Diese Hauptvariante ist fest mit dem Artikel des Typs *Multipack* verbunden und kann nur zusammen mit dem Artikel erstellt oder gelöscht werden. Die Hauptvariante selbst entspricht der kleinsten Verkaufseinheit des Produkts.

[.instruction]
Artikel des Typs Multipack erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke auf *Neu*. +
→ Das Tab *Neuer Artikel* wird geöffnet.
. Wähle den Typ *Multipack*.
. Nimm die weiteren Einstellungen vor. Beachte <<table-create-multipack>>.
. *Speichere* die Einstellungen. +
→ Der Artikel des Typs *Multipack* wird erstellt. +
→ Die Hauptvariante wird in einem neuen Tab geöffnet.

[TIP]
.Neuen Artikel des Typs *Multipack* in Übersicht anzeigen
====
Der neue Artikel des Typs *Multipack* ist nicht aktiv. Um neu erstellte Artikel in der Übersicht im Menü *Artikel » Artikel bearbeiten* anzuzeigen, wähle auf der linken Seite für den Filter *Aktiv* die Option *ALLE*. Klicke dann auf *Suchen*. Wie du Artikel und Varianten für den Webshop aktivierst, erfährst du im Kapitel <<artikel/artikel-verwalten#180, Verfügbarkeit einstellen>>.
====

[[table-create-multipack]]
.Artikel des Typs Multipack erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Artikeldaten*

|*Typ*
|Artikeltyp *Multipack* wählen. +
*Standard* = Erstellt einen Artikel des Typs *Standard* mit Hauptvariante. +
*Set* = Erstellt einen Artikel des Typs *Set*. +
*Multipack* = Erstellt einen Artikel des Typs *Multipack*.

|*ID*
|Die Artikel-ID ist eine eindeutige, fortlaufende Zahl, die plentymarkets zur exklusiven Zuordnung jedes Artikels benötigt. Wird dieses Feld freigelassen, vergibt plentymarkets automatisch die nächste freie ID.

|*Name*
|Namen für das Multipack eingeben. Der Name ist eine Pflichteingabe. Wie du den Namen änderst, erfährst du im Kapitel <<artikel/artikel-verwalten#50, Artikeltexte eingeben>>.

2+|*Variante » Kategorieverknüpfung*

|Kategoriewahl
|Die Kategorie wählen, in der das Multipack veröffentlicht werden soll. Alternativ auf *Neue Kategorie* klicken, um eine neue Kategorie zu erstellen.
|====

[#1300]
=== Artikel des Typs Multipack bearbeiten

Nachdem du den Artikel des Typs *Multipack* erstellt hast, nimm die weiteren Einstellungen vor. Diese Einstellungen sind identisch mit den Einstellungen für <<artikel/artikel-verwalten#30, Artikel des Typs Standard>>.

[#1400]
=== Multipack-Variante erstellen

Beim Erstellen eines Artikels des Typs *Multipack* wird immer eine Hauptvariante erstellt. Die Hauptvariante ist fest mit dem Artikel verbunden. Die Hauptvariante kann nicht gelöscht werden. Diese Hauptvariante entspricht der kleinsten Verkaufseinheit des Produkts. Alle weiteren Varianten des Artikels entsprechen dieser kleinsten Verkaufseinheit mal x. Der Bestand aller Varianten wird nur an der Hauptvariante gepflegt. Im Tab *Bestand* der weiteren Varianten des Artikels wird nur der theoretische Bestand angezeigt. Wenn sich der Bestand der Hauptvariante ändert, wird der Bestand für die anderen Varianten des Artikels neu berechnet.

[.instruction]
Multipack-Variante erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel des Typs *Multipack*.
. Wechsele in das Tab *Varianten*.
. Klicke auf *Neu*. +
→ Das Fenster *Neue Variante erstellen* wird geöffnet.
. Gib als Inhalt eine Stückzahl der Hauptvariante ein. +
*_Tipp:_* Einheit und Attribute sind nicht änderbar.
. Klicke auf *Variante erstellen*. +
→ Die Variante wird erstellt. +
→ Die Variante wird in der Variantenübersicht angezeigt.

Die Einstellungen der Variante bearbeitest du genauso wie <<artikel/artikel-verwalten#170, Varianten von Artikeln des Typs Standard>>. Beachte jedoch die folgenden Besonderheiten von Multipack-Varianten:

* Deaktiviere die Vererbung des Verkaufspreises und speichere einen eigenen Preis.
* Der Tab *Bestand* ist rein informativ. Der Bestand wird nur an der Hauptvariante gepflegt.

[#2000]
== Artikelpakete

Ein Artikelpaket besteht aus mehreren Produkten. Der Paketpreis eines Artikelpakets kann dabei günstiger sein als die Summe der Einzelpreise. Pakete filterst du im Menü *Artikel » Artikel bearbeiten* mit dem Filter *Paket*.

[#2100]
=== Artikelpaket erstellen

Im Tab *Paket* eines Artikels des Typs *Standard* erstellst du ein Artikelpaket, das sich aus mehreren Bestandteilen, den Basisartikeln, zusammensetzt. Wenn du dem geöffneten Artikel weitere Varianten hinzufügst, wird daraus ein Paket. Die Bestandteile des Pakets werden im Tab *Paket-Bestandteile* angezeigt und werden dort auch bearbeitet und gelöscht.

[.instruction]
Artikelpaket erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke auf *Neu*. +
→ Das Tab *Neuer Artikel* wird geöffnet.
. Wähle den Typ *Standard*.
. Gib einen Namen ein.
. Gib den Inhalt ein.
. Wähle eine Kategorie.
. Nimm bei Bedarf weitere Einstellungen vor. Beachte dazu die Erläuterungen zu Artikeln des Typs *Standard* auf der Handbuchseite <<artikel/artikel-verwalten#tabelle-standardartikel-erstellen, Artikel verwalten>>.
. *Speichere* die Einstellungen. +
→ Der Artikel wird erstellt. +
→ Die Hauptvariante wird in einem neuen Tab geöffnet.
. Öffne die Variante.
. Wechsele in das Tab *Paket » Variante hinzufügen*.
. Setze Häkchen bei Varianten, die du als Paketbestandteile hinzufügen möchtest.
. Klicke auf *Variante hinzufügen*. +
→ Die Bestandteile werden zum Artikelpaket hinzugefügt und im Tab *Paket-Bestandteile* angezeigt.

Verknüpfe anschließend einen Verkaufspreis mit dem Artikelpaket und gib einen Preis ein. Wie du Verkaufspreise verknüpfst, erfährst du im Kapitel <<artikel/artikel-verwalten#240, Verkaufspreise verknüpfen>>. In der Auftragsabwicklung wird dann nur der Paketpreis angegeben und die Paketbestandteile ohne Einzelpreise.

[NOTE]
.Vorhandenen Artikel als Paketartikel einrichten
====
Anstatt einen neuen Paketartikel zu erstellen, kannst du auch einen vorhandenen Artikel verwenden und diesem Paketbestandteile hinzufügen. Beachte, dass der Paketartikel, dem du Bestandteile hinzufügst, keinen eigenen Bestand haben darf.
====

[#2200]
=== Paketbestandteile bearbeiten oder löschen

Im Tab *Paket-Bestandteile* änderst du die Menge der im Artikelpaket enthaltenen Varianten, siehst den Nettowarenbestand der Varianten und löschst nicht mehr benötigte Paket-Bestandteile.

[.instruction]
Paketbestandteil löschen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Wähle für den Filter *Paket* die Einstellung *Ja*.
. Klicke auf *Suchen*. +
→ Alle Paketartikel werden in der Übersicht angezeigt.
. Öffne den Paketartikel.
. Öffne die Variante.
. Wechsele in das Tab *Paket » Paket-Bestandteile*.
. Setze Häkchen bei den Paketbestandteilen, die du löschen möchtest.
. Klicke auf *Paket-Bestandteile löschen*. +
→ Die Paketbestandteile werden aus dem Artikelpaket gelöscht.

[#2300]
=== Mehrere Pakete in einem Artikel abbilden

Artikelvarianten können zu Paketen mit verschiedenen Bestandteilen werden. Auf diese Weise gestaltest du Artikelpakete komplex und vielseitig nach Ihren Anforderungen.

[.subhead]
Beispiel für Paketvarianten: du möchtest je ein Handtuch und ein Badetuch im Paket in unterschiedlichen Farben verkaufen. Hierfür sind folgende Schritte notwendig:

* <<artikel/artikel-verwalten#400, Attribut erstellen>> mit den notwendigen Werten, zum Beispiel rot und blau
* <<artikel/artikel-verwalten#20, Artikel erstellen>>, der als Paketartikel dient, zum Beispiel Handtuchpaket
* <<artikel/artikel-verwalten#160, Varianten erstellen>> und dabei die Attributwerte verknüpfen
* Artikel für Paketbestandteile erstellen, zum Beispiel Handtuch und Badetuch
* Varianten für Paketbestandteile erstellen, zum Beispiel rotes Handtuch, blaues Handtuch etc.
* <<#2100, Paketbestandteile>> zu den Varianten des Artikelpakets hinzufügen

Auf diese Weise bietest du in deinem Webshop den Artikel *Handtuchpaket* als Paket in den Farben *Rot* und *Blau* an.

[#2400]
=== Warenbestand von Artikelpaketen einstellen

Der Warenbestand des Pakets richtet sich nach dem Paketbestandteil mit dem geringsten Bestand. Der Warenbestand dieses Paketbestandteils wird in der Artikelübersicht im Menü *Artikel » Artikel bearbeiten* in der Spalte *WB netto* angezeigt. Am Paketartikel selbst pflegst du keinen Bestand. Im Paketbestandteil im Tab *Bestand* verwaltest du den Warenbestand, buchst neue Wareneingänge, korrigierst Bestände und überblickst Zuläufe und Warenbewegungen. Weitere Informationen findest du auf der Handbuchseite <<warenwirtschaft#, Warenwirtschaft>>.

[#2500]
=== Gewicht und Einkaufspreis berechnen

Ein Artikelpaket ist eine Zusammenstellung mehrerer Bestandteile. Jeder Bestandteil verfügt wiederum über wichtige Kennzahlen, wie <<artikel/artikel-verwalten#270, Gewicht>> und <<artikel/artikel-verwalten#280, Einkaufspreis>> (EK). Aber wie setzen sich diese Kennzahlen für das Artikelpaket insgesamt zusammen?

Du kannst das Gewicht und den EK für das Artikelpaket selber eintragen. Es gibt aber auch die Möglichkeit, diese Kennzahlen automatisch berechnen zu lassen. Wie das geht, wird im Folgenden beschrieben.

[.instruction]
Gewicht und EK automatisch berechnen lassen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Wähle für den Filter *Paket* die Einstellung *Ja*.
. Klicke auf *Suchen*. +
→ Alle Artikelpakete werden in der Übersicht angezeigt.
. Öffne das Artikelpaket. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wähle die gewünschten Einstellungen im Bereich *Paket* aus. Beachte dazu die Erläuterungen in <<table-calculate-weight-purchase-price>>.
. *Speichere* die Einstellungen.
. <<basics/arbeiten-mit-plentymarkets/allgemeine-funktionen#70, Lade>> das Artikelpaket neu. +
→ Die Kennzahlen werden nun automatisch auf Basis der einzelnen Bestandteile berechnet.


[[table-calculate-weight-purchase-price]]
.Gewicht und EK automatisch berechnen lassen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Automatisch aus Paketbestandteile berechnen: EK netto*
|Nettoeinkaufspreis automatisch anhand der Bestandteile berechnen. +
Rechts im Bereich *Kosten* wird das Feld <<artikel/artikel-verwalten#280, *EK netto*>> nach Speichern und Neuladen ausgegraut.

|*Automatisch aus Paketbestandteile berechnen: GLD EK netto*
|Gleitenden Nettoeinkaufspreis automatisch anhand der Bestandteile berechnen. +
Rechts im Bereich *Kosten* wird das Feld <<artikel/artikel-verwalten#280, *GLD EK netto*>> nach Speichern und Neuladen ausgegraut.

|*Automatisch aus Paketbestandteile berechnen: Gewicht netto*
|Nettogewicht automatisch anhand der Bestandteile berechnen. +
Rechts im Bereich *Maße* wird das Feld <<artikel/artikel-verwalten#270, *Gewicht netto*>> nach Speichern und Neuladen ausgegraut.

|*Automatisch aus Paketbestandteile berechnen: Gewicht brutto*
|Buttogewicht automatisch anhand der Bestandteile berechnen. +
Rechts im Bereich *Maße* wird das Feld <<artikel/artikel-verwalten#270, *Gewicht brutto*>> nach Speichern und Neuladen ausgegraut.
|====

[TIP]
.Mehrere Artikelpakete gleichzeitig anpassen
====
Verwende die <<artikel/artikel-verwalten#330, Varianten-Gruppenfunktion oder Stapelverarbeitung>>, um Gewicht und EK für mehrere Artikelpakete gleichzeitig berechnen zu lassen.
====

[TIP]
.Berechnungsautomatik standardmäßig aktivieren
====
Willst du Gewicht und Einkaufspreis in der Regel automatisch berechnen lassen? Vielleicht hast du nur einzelne Artikel, die du von der automatischen Berechnung ausschließen möchtest. Kein Problem! Öffne das Menü *Einrichtung » Artikel » Einstellungen* und bestimme welche Kennzahlen automatisch berechnet werden sollen. Verwende dabei die Optionen *Paketautomatik für Gewicht brutto*, *Paketautomatik für Gewicht netto*, *Paketautomatik für EKs* und *Paketautomatik für GLD EKs*.
====

[TIP]
.Kennzahlen lieber händisch eintragen?
====
Möchtest du das Gewicht und den EK für deine Artikelpakete selbst eintragen? Wähle im Bereich *Paket* keine Einstellungen aus, um die Daten händisch zu pflegen. Sind keine Einstellungen ausgewählt, haben Kennzahlen der einzelnen Bestandteile keinen Einfluss auf die Kennzahlen des Artikelpakets.
====


[#3000]
== Sets

[WARNING]
.Sets werden derzeit noch entwickelt
====
Erst ab link:https://marketplace.plentymarkets.com/plugins/sales/online-shops/ceres_4697[Ceres 5] wird es möglich sein, Artikel-Sets im Webshop zu verkaufen.
Derzeit kannst du Artikel-Sets zwar im Backend erstellen und dich mit dem Konzept vertraut machen, aber du kannst sie noch nicht im Webshop darstellen.
Sobald die Set-Funktion veröffentlicht wird, werden <<bereits bestehenden Sets migriert>>.

Die Set-Funktion ist nur für den Webshop vorgesehen. Selbst nach Veröffentlichung der Funktion wird es nicht möglich sein, Artikel-Sets auf Märkten wie Amazon und eBay zu verkaufen.
====

Stell dir mal vor, du verkaufst Fußballuniformen, bestehend aus Trikots, Shorts und Socken.
Wäre es nicht genial, wenn Endkunden ihre eigenen Uniformen zusammenstellen könnten?
Also, wenn sie für jede der drei Komponenten die gewünschte Farbe und Größe wählen könnten?
Artikel-Sets machen es möglich!

Ein Set besteht aus mehreren Artikeln (Trikot, Shorts, Socken).
Bei der Bestellung können Endkunden für jeden Artikel die gewünschte Variante wählen (Farbe, Größe).

Vielleicht hilft es dir, die Artikel und Varianten, die in deinem Set vorkommen werden, zu skizzieren.

[[table-set-mind-map]]
.Welche Artikel und Varianten sollten im Set enthalten sein?
[cols="1,^,^,^", stripes=none]
|====

|*Set*
3+|Fußballbekleidung

|*Artikel im Set*
|Trikot
|Shorts
|Socken

|*Varianten pro Artikel*
a|* S und rot
* L und rot
* S und blau
* L und blau
a|* S und weiß
* L und weiß
* S und schwarz
* L und schwarz
a|* S und blau
* L und blau
* S und weiß
* L und weiß
|====

=== Wie funktionieren Setpreisen?

Das Besondere an Sets ist, dass du im Voraus nicht genau weißt, wie der Endkunde die Varianten kombinieren wird. Daher macht es keinen Sinn, Festpreise für Sets zu speichern.
Stattdessen ermittelt plentymarkets den Preis der _günstigsten wählbaren Kombination_ und speichert diese Informationen am Set.
Dieser Mindestpreis kann im Webshop und im Backend angezeigt werden. Zum Beispiel: "Ab 99,99€ verfügbar".

//Konkret am Beispiel von oben: An den Jackett-, Hosen- sowie Hemd-Varianten pflegt ihr einen Verkaufspreis, der explizit als Setpreis gekennzeichnet ist. D. h. ihr gebt für die Varianten an, mit welchem Preis diese als Setbestandteil verkauft werden sollen. Beim Hinzufügen eines neuen Setbestandteils (sowie nachts) prüfen wir dann anhand dieser Setpreise der Varianten, welches die günstigste kaufbare Konfiguration für dieses Set ist und speichern diese Information am Set als sogenannten “Ab-Preis”.

[discrete]
==== Setpreise vorbereiten

<<artikel/einstellungen/preise#200, Erstelle zunächst einen Verkaufspreis>> für Sets.
Achte darauf, dass du beim Erstellen des Verkaufspreises den Typ *Setpreis* wählst.

<<artikel/einstellungen/preise#900, Verknüpfe dann diesen Verkaufspreis>> mit allen Setbestandteilen und gib für jeden Bestandteil einen Geldbetrag ein.
Beachte, dass es sich bei den Setbestandteilen um ganz normale Varianten handelt.

[TIP]
.Können Artikel günstiger sein, wenn sie zusammen als Set gekauft werden?
====
Es ist möglich, ein Set günstiger als die Summe seiner Bestandteile zu machen.
Es gibt zwei Möglichkeiten, dies zu tun:

* Einerseits könntest du günstigere Geldbeträge für den Set-Verkaufspreis speichern als für den normalen Verkaufspreis.
* Andererseits könntest du <<einen prozentualen Rabatt eingeben>>, der für das gesamte Set gilt.
====

[#3300]
=== Neue Sets erstellen

Hast du schon überlegt, <<welche Artikel und Varianten im Set>> enthalten sein sollen?
Hast du einen <<Verkaufspreis speziell für Sets>> erstellt?
Dann bist du jetzt bereit, Sets zu erstellen!

//you can either create sets manually or you can <<import them with elasticsync>>

[discrete]
==== Artikelset manuell erstellen

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke auf *Neu*. +
→ Das Tab *Neuer Artikel* wird geöffnet.
. Nimm die Einstellungen für das Set vor. Beachte <<table-create-set-items>>.
.. Wähle den Typ *Set*.
.. Gib einen Namen für das Artikelset ein.
.. In welcher Kategorie soll das Set erscheinen? Wähle die Kategorie aus.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Artikel-Set wird erstellt. +
→ Die Hauptvariante erscheint in einem neuen Tab und <<kann jetzt weiter bearbeitet werden>>.

[TIP]
.Wofür ist die Hauptvariante gut?
====
Beim Erstellen eines neuen Sets wird automatisch eine Hauptvariante erstellt.
Diese Hauptvariante ist fest mit dem Set verbunden und kann nur zusammen mit dem Set erstellt oder gelöscht werden.
Die Hauptvariante:

* ist nur virtuell und entspricht selbst keinem physischen Produkt.
* dient lediglich als Datencontainer, zu dem du die Setbestandteile hinzufügst.
* dient zur Verwaltung der Einstellungen für das gesamte Set.
====

[[table-create-set-items]]
.Artikelset erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Bereich: Artikeldaten*

|*Typ*
a|Wähle den Typ *Set*. Viele Einstellungen verschwinden, wenn du diese Option wählst. Das Menü zeigt jetzt nur noch die Einstellungen, die für Sets relevant sind.

Die anderen Optionen in der Dropdown-Liste sind für andere Anwendungsfälle vorgesehen:

* *Standard* = Erstellt einen <<artikel/artikel-verwalten#20, normalen Artikel>> oder ein <<Artikelpaket>>.
* *Set* = Erstellt ein Artikelset.
* *Multipack* = Erstellt einen <<Multipack-Artikel>>.

//|*ID*
//|Die Artikel-ID ist eine eindeutige, fortlaufende Zahl, die plentymarkets zur exklusiven Zuordnung jedes Artikels benötigt. Wird dieses Feld freigelassen, vergibt plentymarkets automatisch die nächste freie ID.

|*Name*
|Gib einen Namen für das Set ein. Der Name ist eine Pflichteingabe.
Es wird weiterhin möglich sein, <<den Namen zu ändern>>, nachdem du das Set erstellt hast.

2+|*Bereich: Variante » Kategorieverknüpfung*

|
|In welcher <<artikel/einstellungen/kategorien#, Kategorie>> soll das Set erscheinen? Wähle die Kategorie aus.
Klicke alternativ auf *Neue Kategorie*, um gleichzeitig eine neue Kategorie zu erstellen und das Set in diese Kategorie zu sortieren.
|====

=== Bestehende Sets bearbeiten

==== Sets suchen

<<Beim Erstellen eines neuen Artikelsets>> wird die Hauptvariante automatisch in einem neuen Tab geöffnet.
Aber wo findest du die Sets, die du schon vor einer Weile erstellt hast?

[.instruction]
Bestehende Sets suchen und öffnen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Schau dir die Filter links an.
. Setze den Filter *Typ* auf *Set*.
. Setze den Filter *Aktiv* auf *ALLE*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die gefundenen Sets werden in der Übersicht rechts aufgelistet.
. Klicke auf ein Set, um es zu öffnen.

[#3500]
==== Bestandteile hinzufügen oder entfernen

Hast du schon entschieden, <<welche Artikel in das Set>> aufgenommen werden sollen?
Die Artikel, die du zum Set hinzufügst, sind ganz normale Artikel. Sie sind also Artikel vom Typ *Standard*.

* Wenn du einen _Artikel mit mehreren Varianten_ zum Set hinzufügst, werden deine Kunden bei der Bestellung frei wählen können, welche Variante sie kaufen möchten.
* Wenn du einen _Artikel ohne weitere Varianten_ zum Set hinzufügst, d.h. einen Artikel, der nur eine Hauptvariante hat, dann werden deine Kunden nichts auswählen können.

[.instruction]
Bestandteile zum Set hinzufügen:

. <<Suche und öffne den gewünschten Artikelset>>.
. Klicke auf den Tab *Set » Artikel hinzufügen*.
. <<artikel/einleitung/suche#100, Suche nach den Artikeln>>, die du zum Set hinzufügen möchtest. +
→ Eine Liste der Artikel wird angezeigt.
. Wähle die Artikel (icon:check-square[role="blue"]), die Bestandteile des Sets sein sollen.
. Klicke auf *Artikel hinzufügen*. +
→ Die Artikel werden zum Set hinzugefügt und sind nun auch im Tab *Einstellungen* aufgelistet.

[TIP]
.Bestandteile wieder entfernen
====
Bestandteile, die bereits zum Set hinzugefügt wurden, werden im Tab *Set » Einstellungen* aufgelistet.
Hier kannst du auch Bestandteile entfernen, die nicht länger Teil des Sets sein sollten.
Wähle die Artikel (icon:check-square[role="blue"]), die du aus dem Setartikel entfernen möchtest und klicke auf icon:minus-circle[role="red"] *Bestandteile löschen*.
====

[#3800]
==== Warenbestand verwalten

Der Warenbestand eines Setartikels richtet sich nach der Variante des Sets mit dem geringsten Bestand. Der Warenbestand dieser Variante wird in der Artikelübersicht im Menü *Artikel » Artikel bearbeiten* in der Spalte *WB netto* angezeigt. Am Artikel des Typs *Set* selbst pflegst du keinen Bestand. Den Warenbestand verwaltest du stattdessen im Tab *Bestand* der Setbestandteile.
Weitere Informationen zur Bestandsverwaltung findest du im Kapitel <<warenwirtschaft#, Warenwirtschaft>>.

[#3700]
==== Optional: Rabatte festlegen

Standardmäßig ergibt sich der Preis eines Artikelsets aus der Summe der Einzelpreise der Setbestandteile. Du hast jedoch die Möglichkeit, einen Rabatt in % auf den Gesamtpreis des Sets zu gewähren.

[.instruction]
Rabatt für ein Artikelset speichern:

. <<Suche und öffne den gewünschten Artikelset>>.
. Klicke auf den Tab *Set » Einstellungen*.
. Trage in das Feld *Rabatt* einen Prozentsatz ein. Der Gesamtpreis wird um diesen Prozentsatz rabbatiert.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Rabatt wird angewendet.

[#3600]
==== Optional: Minimale oder maximale Bestellmenge festlegen

Bleiben wir beim <<obigen Beispiel>> und nehmen wir an, dass du Fussballuniformen, bestehend aus einem Trikot, Shorts und Socken, verkaufst.
Aber jetzt nehmen wir an, du möchtest das Set _nur an ganze Fussballmannschaften_ verkaufen. Mit anderen Worten: du willst das Set nur an jemanden verkaufen, der bereit ist, mindestens 10 Trikots, Shorts und Socken auf einmal zu kaufen.
In diesem Fall handelt es sich um eine _Mindestbestellmenge_.

Jeder Spieler soll seine eigene Größe wählen können, und der Torwart soll sein Trikot in einer anderen Farbe bestellen können, um sich vom Rest der Mannschaft zu unterscheiden.
Es spielt keine Rolle, für welche Varianten sich der Kunde entscheidet. Wichtig ist nur, dass der Kunde eine zulässige Anzahl von jedem Artikel bestellt.

[.instruction]
Zulässige Menge eines Setbestandteils festlegen:

. <<Suche und öffne den gewünschten Artikelset>>.
. Klicke auf den Tab *Set » Einstellungen*. +
→ Eine Liste der Bestandteile des Sets wird angezeigt.
. Aktiviere (icon:toggle-on[role="green"]) die Option *Bestellmengen möglich*. +
→ Die Felder sind dadurch nicht mehr ausgegraut.
. Gib die maximale und minimale Bestellmenge für jeden Bestandteil ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

//info-box: was macht man (was trägt man ein) wenn man nur bei 1 der Bestandteile eine Mindestbestellmenge hinterlegen will? Was macht man wenn man nur eine Mindestbestellmenge aber keine Maximalbestellmenge haben will?

=== Verzeichnis der Optionen im Artikelset

//edit the names of tables. Currently they all have the same name

Dieses Kapitel dient nur als Referenz. Es gibt einen Überblick über die diversen Einstellungen und Optionen, die in einem Set zu finden sind.
Die Erläuterungen verweisen so oft wie möglich auf andere Stellen im Handbuch, wo die jeweilige Option im Kontext erklärt wird.

==== Tab: Global

[[table-edit-set-items]]
.Artikel des Typs Set bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Erlöskonto*
|<<auftraege/buchhaltung#800, Erlöskonto>> eingeben.

|*Altersfreigabe*
|Altersfreigabe für den Artikel des Typs *Set* wählen. Dabei die Altersfreigabe der Variante mit der höchsten Altersfreigabe wählen. Für den Versand von Artikeln mit *Altersfreigabe 18* muss ein <<fulfillment/versand-vorbereiten#1000, Versandprofil>> verknüpft sein, bei dem die Option *PostIdent* aktiviert ist.

//|*Gutschein*
//|Wählen, ob <<auftraege/gutscheine#, Gutscheine>> für das Set *möglich* oder *verboten* sind, oder ob das Set *nur mit Gutschein kaufbar* ist.

|*Versandpaket*
|<<fulfillment/versand-vorbereiten#1900, Versandpaket>> verwenden. Versandpakete haben festgelegte Maße. Wenn du die Maße des Artikels im Tab *Einstellungen* des Artikels des Typs *Set* eingibst, erfolgt automatisch die Zuordnung des passenden Versandpakets.

|*Seriennummer*
|<<artikel/anwendungsfaelle/seriennummern#, Seriennummern>> zur eindeutigen Kennzeichnung jedes verkauften Sets verwenden. Seriennummern gewährleisten die Rückverfolgbarkeit von Artikeln im Fehler- oder Problemfall.

|*Versandprofile*
|Ein, mehrere oder *ALLE* <<fulfillment/versand-vorbereiten#1000, Versandprofile>> aktivieren. Standardmäßig ist kein Versandprofil aktiviert. Mindestens ein Versandprofil aktivieren, da sonst ungewollte Effekte bei der Versandkostenberechnung auftreten können. Wenn ein Auftrag Artikel enthält, bei denen kein Versandprofil aktiviert wurde, wird das Standard-Versandprofil aus dem Standard-Webshop für die Artikel verwendet. Wenn kein Standard-Versandprofil festgelegt ist, wird das Versandprofil mit der höchsten Priorität verwendet.

|*Shop-Aktion*
|<<artikel/webshop/shop-aktionen#200, Callisto-Shop-Aktion>> oder *Keine* wählen. Sets können als Shop-Aktionen in deinem Webshop dargestellt werden. +
*Sonderangebot* = Stellt eine Liste von Sonderangeboten dar. +
*Neuheit* = Stellt eine Liste der neuesten Artikel dar. +
*Top-Artikel* = Stellt eine Liste der meistverkauften Artikel dar.

|*Artikelbewertung*
|Erstbewertung von *1* bis *5* oder *1* bis *10* für das Set eingeben. Wenn du Artikelbewertungen verwendest, wird der eingegebene Wert als Erstbewertung des Sets angezeigt. Der Wert wird nach jeder Bewertung automatisch auf einen Durchschnittswert angepasst. Den Bewertungsbereich legst du im Menü *Einrichtung » Mandant » Global » Feedback » Tab: Artikel* unter *Maximale Bewertungspunkte* fest.

|*Artikelbild*
|Auf das Bild klicken, um das Tab *Bilder* aufzurufen.
|====

==== Tab: Set

[[table-edit-set-items]]
.Artikel des Typs Set bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Tab: Set*

|*Tab: Einstellungen* +
*Tab: Artikel hinzufügen*
|Artikel <<#3500, hinzufügen>>, <<#3600, ändern>> und <<#3900, löschen>>.
|====

==== Tab: Varianten-ID

[[table-edit-set-items]]
.Artikel des Typs Set bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+| Tab: Einstellungen

|*Tab: Einstellungen*
|Einstellungen entsprechen den Einstellungen für Artikel des Typs *Standard*, siehe <<artikel/artikel-verwalten#230, Verfügbarkeit von Varianten einstellen>> und <<artikel/artikel-verwalten#250, Barcodes verknüpfen>>. Auf das Bild klicken, um das Tab *Bilder* aufzurufen.

|*Tab: Kategorien*
|Einstellungen entsprechen den Einstellungen für Artikel des Typs *Standard*, siehe <<artikel/artikel-verwalten#300, Zusätzliche Kategorien verknüpfen>>.

|*Tab: Verfügbarkeit*
|In der Spalte *Verfügbar* Häkchen bei den Mandanten setzen, in denen das Set verfügbar sein soll.
|====

==== Tab: Texte

[[table-edit-set-items]]
.Artikel des Typs Set bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Tab: Texte*

|Texte
|Einstellungen entsprechen den Einstellungen für Artikel des Typs *Standard*, siehe <<artikel/artikel-verwalten#50, Artikeltexte eingeben>>.
|====

==== Tab: Bilder

[[table-edit-set-items]]
.Artikel des Typs Set bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Tab: Bilder*

|Bilder
|Bilder des Sets hochladen. Im Webshop werden außerdem die Bilder der Varianten des Sets angezeigt. Die weiteren Einstellungen entsprechen den Einstellungen für Artikel des Typs *Standard*, siehe <<artikel/artikel-verwalten#90, Artikelbilder hochladen>>.

//2+|*Tab: Media*

//|Media
//|Einstellungen entsprechen den Einstellungen für Artikel des Typs *Standard*, siehe <<artikel/artikel-verwalten#110, Dateien zum Download bereitstellen>>.
|====

////
=== Artikelsets mit ElasticSync anlegen und verwalten

==== Sets mit ElasticSync importieren

==== Bestandteile mit ElasticSync hinzufügen oder entfernen

==== Weitere Einstellungen mit ElasticSync bearbeiten
////

=== Was passiert mit bereits angelegten Sets?

Wir werden bereits angelegte Sets migrieren. Hier die wichtigsten Änderungen:

* Bestände werden entfernt
* mit Sets verknüpfte Preise werden entfernt und wie oben beschrieben durch “Ab-Preise” ersetzt
* Bestandsautomatiken werden entfernt
* Pakete werden aus Sets entfernt
* Sets werden aus Paketen entfernt

=== Artikel-Sets im Webshop darstellen
