= Seriennummern
:lang: de
include::{includedir}/_header.adoc[]
:description: Lerne, wie du Seriennummern zur eindeutigen Kennzeichnung jedes verkauften Artikels einrichtest.
:url: artikel/anwendungsfaelle/seriennummern
:position: 30
:table-event-procedure: <<tabelle-ereignisaktion-seriennummern-zuordnen>>

Eine Seriennummer ist eine alphanumerische Zeichenkette, die ein einzelnes Exemplar eines Artikels eindeutig kennzeichnet.
Seriennummern ermöglichen die Rückverfolgbarkeit eines verkauften Artikels im Fehler- oder Problemfall und erleichtern somit das Aufspüren von gestohlenen oder gefälschten Produkten. Beispiele für Artikel mit Seriennummern sind Autos, Elektronik und Haushaltsgeräte.

Stell dir zum Beispiel vor, du verkaufst Mobiltelefone. Dein Hersteller versieht jedes Handy mit einer eindeutigen Seriennummer.
Jedes Mal, wenn du eines der Handys verkaufst, soll plentymarkets protokollieren, _welches Exemplar_ verkauft wurde.
Mit anderen Worten soll plentymarkets festhalten, welche Seriennummer welcher Bestellung entspricht.
So bleibt deine Firma auf der sicheren Seite. Falls dein Kunde den Artikel zurückschickt, kannst du die Seriennummer prüfen und sicherstellen, dass du keine Fälschung erhältst.

[#100]
== Pool von Seriennummern aufbauen

[#200]
=== Seriennummern im Artikeldatensatz eingeben

Erstelle zuerst einen Pool von Seriennummern in plentymarkets. Stell dir zum Beispiel vor, du verkaufst Elektronikartikel und hast gerade 50 Exemplare eines Handys von deinem Hersteller erhalten. Jedes Exemplar hat eine eigene Seriennummer. Zuerst gibst du alle 50 Seriennummern in plentymarkets ein.
Damit erstellst du einen Pool von verfügbaren Seriennummern für diesen Artikel.

Wie viele Seriennummern möchtest du eingeben? Wenn du nur wenige Seriennummern eingeben möchtest, dann empfiehlt es sich, diese _manuell_ in den Artikeldatensatz einzugeben. Wenn du aber große Mengen an Seriennummern eingeben möchtest, dann ist es wahrscheinlich schneller, sie mit einem Tool namens ElasticSync zu _importieren_.

[.instruction]
Seriennummer manuell eingeben:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#100, Suche>> und öffne den Artikel.
. Klicke in der obere Symbolleiste auf das Symbol *Seriennummern* icon:item_serial_number[set=plenty]. +
→ Das Fenster *Seriennummern* wird geöffnet.
. Gib unter *Neue Seriennummern* eine Seriennummer ein.
. *Speichere* (icon:save[role="green"]) die Seriennummer oder drücke die Enter-Taste, um die Seriennummer zu speichern.

[TIP]
.Seriennummern mit ElasticSync importieren
====
Nutze <<daten/daten-importieren/ElasticSync#sync-seriennummer, ElasticSync>>, wenn du große Mengen an Seriennummern auf einmal eingeben möchtest. Verwende dazu das <<daten/daten-importieren/sync-typen/elasticSync-artikel#sync-seriennummer, Seriennummer>> Zuordnungsfeld innerhalb des *Artikel* Sync-Typs.
====

[#300]
=== Erstellte Seriennummern suchen, bearbeiten oder löschen

Sobald du eine <<Seriennummer eingegeben>> hast, wird sie dir in der Übersicht angezeigt:

* _Freie Seriennummern_ werden in grün dargestellt, d.h. Seriennummern, die noch keinem bestimmten Auftrag entsprechen.
* _Verwendete Seriennummern_ werden in rot dargestellt, d.h. Seriennummern, die bereits einem bestimmten Auftrag entsprechen. Die Auftrags-ID wird mit angezeigt.

==== Seriennummer suchen

Im oberen Bereich des Pop-up-Fensters suchst du gezielt nach Seriennummern.

//Im oberen Bereich des Fensters *Seriennummern* suchst du gezielt nach Seriennummern und bearbeitest bestehende Seriennummern.

[.instruction]
Seriennummer suchen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#100, Suche>> und öffne den Artikel.
. Klicke in der obere Symbolleiste auf das Symbol *Seriennummern* icon:item_serial_number[set=plenty]. +
→ Das Fenster *Seriennummern* wird geöffnet.
. Lege mit der Dropdown-Liste *Status* fest, ob du nach allen, freien oder verwendeten Seriennummern suchen möchtest.
. *_Optional:_* Gib die gesuchte Seriennummer in das Suchfeld ein.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die gefilterten Seriennummern werden angezeigt.

==== Seriennummer bearbeiten

Solltest du jemals versehentlich eine falsche Seriennummer eingeben, suche einfach nach der Nummer und bearbeite sie.

[.instruction]
Seriennummer bearbeiten:

. <<Suche nach der Seriennummer>>.
. Klicke auf *Bearbeiten* (icon:pencil[role="yellow"]).
. Gib eine neue Seriennummer ein.
. *Speichere* (icon:save[role="green"]) die Seriennummer.

==== Seriennummer löschen

Seriennummern kannst du entweder einzeln löschen, oder du kannst die Dropdown-Liste *Auswahl* verwenden, um mehrere Seriennummern gleichzeitig zu löschen. Zum Beispiel alle freien Seriennummern oder alle Seriennummern, die an einem bestimmten Datum erstellt wurden.

[.instruction]
Mehrere Seriennummern gleichzeitig löschen:

. <<Suche nach den Seriennummern>>.
. Nutze die Dropdown-Liste *Auswahl*, um Seriennummern auszuwählen (icon:check-square[role="blue"]), z.B. alle Nummern, freie Nummern oder Seriennummern, die an einem bestimmten Datum erstellt wurden. +
. Klicke auf das Löschen-Symbol (icon:minus-circle[role="red"]) in der Zeile *Auswahl*.

[TIP]
.Warum funktioniert die Dropdown-Liste nicht?
====
Die Drop-Down-Liste *Auswahl* kann ziemlich verwirrend sein. Wähle zuerst eine Option aus der Dropdown-Liste. Klicke dann irgendwo außerhalb der Dropdown-Liste, so dass sie nicht mehr blau umrandet ist. Klicke schließlich nochmal auf die Dropdown-Liste. Erst dann werden die Seriennummern ausgewählt.
====

[#400]
== Seriennummern zu Bestellungen zuordnen

Jedes Mal, wenn du einen Artikel mit einer Seriennummer verkaufst, soll plentymarkets protokollieren, _welches Exemplar_ verkauft wurde. Mit anderen Worten soll plentymarkets festhalten, welche Seriennummer welcher Bestellung entspricht.

Es gibt zwei Möglichkeiten, Seriennummern zuzuordnen: mit einem <<Prozess>> oder mit einer <<Ereignisaktion>>:

* Falls deine Artikel _bereits Seriennummern haben_, empfehlen wir die Verwendung eines Prozesses.
//Stell dir zum Beispiel vor, du verkaufst Mobiltelefone. Dein Hersteller versieht jedes Handy vorab mit einer eindeutigen Seriennummer. Jedes Mal, wenn du eines der Handys verkaufst, soll plentymarkets protokollieren, welches Exemplar verkauft wurde. Mit anderen Worten soll plentymarkets festhalten, welche Seriennummer welcher Bestellung entspricht.
* Falls deine Artikel _noch keine Seriennummern haben_, empfehlen wir die Verwendung einer Ereignisaktion.
//Stell dir zum Beispiel vor, du verkaufst Software, die deine Kunden herunterladen. Die Software hat vorab keine bestimmte Seriennummer. Stattdessen wird beim Kauf eine Seriennummer vergeben.

=== Zuordnung mit einem Prozess

Falls deine Artikel _bereits Seriennummern haben_, empfehlen wir die Verwendung eines Prozesses. Stell dir zum Beispiel vor, du verkaufst Mobiltelefone. Dein Hersteller versieht jedes Handy vorab mit einer eindeutigen Seriennummer. Jedes Mal, wenn du eines der Handys verkaufst, soll plentymarkets protokollieren, welches Exemplar verkauft wurde. Mit anderen Worten soll plentymarkets festhalten, welche Seriennummer welcher Bestellung entspricht.

Dazu scannt dein Lagermitarbeiter ganz einfach die Seriennummer, während er den Artikel im Lager kommissioniert.
Die Seriennummer wird automatisch der Bestellung zugeordnet.
Die Seriennummer erscheint auch automatisch auf der Rechnung deines Kunden.

==== Welche Artikel sollen gescannt werden können?

Dein Lagermitarbeiter wird die Seriennummer eines Artikels nur dann scannen können, wenn du den Artikel zur Verfügung gestellt hast.

//Voraussetzung für die Verfügbarkeit von Seriennummern in Prozessen ist die Aktivierung der Option *Seriennummer* im Tab *Global* eines Artikels.

[.instruction]
Das Scannen eines Artikels ermöglichen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#100, Suche>> und öffne den Artikel, der gescannt werden können soll.
. Wechsele in das Tab *Global*.
. Wähle für die Option *Seriennummer* die Einstellung *Ja*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Arbeitest du mit vielen Artikeln?
====
Verwende die sogenannte <<Artikel-Gruppenfunktion>>, um die Einstellung für mehrere Artikel gleichzeitig zu speichern.
====

==== Baue den Prozess

<<Erstelle einen Kommissionierungsprozess>>, mit dem dein Lagermitarbeiter Artikel pickt und deren Seriennummern scannt.
Verwende dazu die <<automatisierung/prozesse/aktionen#420, Aktion "Seriennummer">> zusammen mit der <<automatisierung/prozesse/subaktionen#260, Subaktion "Seriennummern erfassen">>.

Das folgende Video-Tutorial enthält ein Beispiel für das Scannen von Seriennummern innerhalb eines größeren Kommissionierungsprozesses:

.Sehe, wie Seriennummern in einem Beispielprozess gescannt werden
video::229827267#t=2m49s[vimeo]

##Greift auf den Pool von Seriennummern zu? Also info-box?##

=== Zuordnung mit einer Ereignisaktion

Haben deine Artikel noch keine Seriennummern?
Dann erstelle eine Ereignisaktion, die einem Artikel automatisch eine Seriennummer zuweist, sobald der Kunde seine Bestellung vollständig bezahlt hat.
Die Seriennummer erscheint auch automatisch auf der Rechnung deines Kunden.

//Die Zuordnung der Seriennummern erfolgt automatisch über eine Ereignisaktion. Voraussetzung ist die vollständige Bezahlung des Artikels.
//Die Seriennummern werden in der Rechnung des Auftrags ausgegeben. Richte eine Ereignisaktion ein, damit automatisch eine Seriennummer zugeordnet wird, wenn der Auftrag vollständig bezahlt und in den Auftragsstatus *Zahlungseingang vollständig* versetzt wurde.

include::../../_includes/textblocks/instructions/EA.adoc[]

[[tabelle-ereignisaktion-seriennummern-zuordnen]]
.Ereignisaktion zum automatischen Zuordnen von Seriennummern
[cols="1,1,1"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Zahlung: Vollständig*
|

|*Aktion*
|*Artikel*
|*Seriennummer zuordnen*
|====

[#300]
== Seriennummern exportieren

Möchtest du Seriennummern aus deinem plentymarkets System exportieren? Willst du zum Beispiel deinem Hersteller einmal täglich eine Liste aller verwendeten Seriennummern schicken?
Nutze dazu den sogenannten <<daten/daten-exportieren/FormatDesigner#, FormatDesigner>>!
Genauer gesagt, verwende <<daten/daten-exportieren/FormatDesigner/format-typen/artikel#500, ItemSerialNumber>> innerhalb des Artikel-Formattyps.

////
Exportiere Seriennummern in einer CSV-Datei.

[.instruction]
Seriennummern exportieren:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Klicke in der Symbolleiste auf *Seriennummern*. +
→ Das Fenster *Seriennummern* wird geöffnet.
. Wähle im Bereich *Seriennummern exportieren* den Status.
. Wähle das Feldtrennzeichen.
. Klicke auf *Exportieren*. +
→ Die Seriennummern werden in einer CSV-Datei exportiert.
////

== Retouren mit Seriennummern annehmen
