= Seriennummern
:lang: de
include::{includedir}/_header.adoc[]
:description: Lerne, wie du Seriennummern zur eindeutigen Kennzeichnung jedes verkauften Artikels einrichtest.
:url: artikel/anwendungsfaelle/seriennummern
:position: 30

Eine Seriennummer ist eine alphanumerische Zeichenkette, die einen verkauften Artikel eindeutig kennzeichnet.
Seriennummern ermöglichen die Rückverfolgbarkeit eines Artikels im Fehler- oder Problemfall und erleichtern somit das Aufspüren von gestohlenen oder gefälschten Produkten. Beispiele für Artikel mit Seriennummern sind Autos, Elektronik und Haushaltsgeräte.

Stell dir zum Beispiel vor, du verkaufst Mobiltelefone. Dein Hersteller versieht jedes Handy mit einer eindeutigen Seriennummer.
Jedes Mal, wenn du eines der Handys verkaufst, soll plentymarkets protokollieren, _welches Exemplar_ verkauft wurde.
Mit anderen Worten soll plentymarkets festhalten, welche Seriennummer welcher Bestellung entspricht.
So bleibt deine Firma auf der sicheren Seite. Falls dein Kunde den Artikel zurückschickt, kannst du die Seriennummer prüfen und sicherstellen, dass du keine Fälschung erhältst.

[#100]
== Pool von Seriennummern aufbauen

[#200]
=== Seriennummern im Artikeldatensatz eingeben

Erstelle zuerst einen Pool von Seriennummern in plentymarkets. Stell dir zum Beispiel vor, du verkaufst Elektronikartikel und hast gerade 50 Exemplare eines Handys von deinem Hersteller erhalten. Jedes Exemplar hat eine eigene Seriennummer. Zuerst gibst du alle 50 Seriennummern in plentymarkets ein.
Damit erstellst du einen Pool von verfügbaren Seriennummern für diesen Artikel.

Wie viele Seriennummern möchtest du eingeben? Wenn du nur wenige Seriennummern eingeben möchtest, dann empfiehlt es sich, diese manuell in den Artikeldatensatz einzugeben. Wenn du aber große Mengen an Seriennummern eingeben möchtest, dann ist es wahrscheinlich schneller, sie mit einem Tool namens ElasticSync zu importieren.

[.instruction]
Seriennummer manuell eingeben:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#100, Suche>> und öffne den Artikel.
. Klicke in der obere Symbolleiste auf das Symbol *Seriennummern* icon:item_serial_number[set=plenty]. +
→ Das Fenster *Seriennummern* wird geöffnet.
. Gib unter *Neue Seriennummern* eine Seriennummer ein.
. *Speichere* (icon:save[role="green"]) die Seriennummer oder drücke die Enter-Taste, um die Seriennummer zu speichern.

[TIP]
.Seriennummern mit ElasticSync importieren
====
Nutze <<daten/daten-importieren/ElasticSync#sync-seriennummer, ElasticSync>>, wenn du große Mengen an Seriennummern auf einmal eingeben möchtest. Verwende dazu das <<daten/daten-importieren/sync-typen/elasticSync-artikel#sync-seriennummer, Seriennummer>> Zuordnungsfeld innerhalb des *Artikel* Sync-Typs.
====

[#300]
=== Erstellte Seriennummern suchen, bearbeiten oder löschen

Sobald du eine <<Seriennummer eingegeben>> hast, wird sie dir in der Übersicht angezeigt:

* _Freie Seriennummern_ werden in grün dargestellt, d.h. Seriennummern, die noch keinem bestimmten Auftrag entsprechen.
* _Verwendete Seriennummern_ werden in rot dargestellt, d.h. Seriennummern, die bereits einem bestimmten Auftrag entsprechen. Die Auftrags-ID wird mit angezeigt.

==== Seriennummer suchen

Im oberen Bereich des Pop-up-Fensters suchst du gezielt nach Seriennummern.

//Im oberen Bereich des Fensters *Seriennummern* suchst du gezielt nach Seriennummern und bearbeitest bestehende Seriennummern.

[.instruction]
Seriennummer suchen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Klicke in der Symbolleiste auf *Seriennummern*. +
→ Das Fenster *Seriennummern* wird geöffnet.
. Wähle den Status.
. *_Optional:_* Gib die gesuchte Seriennummer in das Suchfeld ein.
. Klicke auf *Suchen*. +
→ Die gefilterten Seriennummern werden angezeigt.
. Nimm die weiteren Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-seriennummern-bearbeiten>>

[[tabelle-seriennummern-bearbeiten]]
.Seriennummern bearbeiten
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Status*
|*ALLE*, *frei* oder *vergeben* wählen. Alle Seriennummern mit dem gewählten Status werden angezeigt.

|*Seriennummer*
|Seriennummer eingeben.

|*Auswahl*
|Aktion wählen, zum Beispiel *Alle auswählen*, um alle Seriennummern zu aktivieren. Alle aktivierten Seriennummern über *Auswahl löschen* löschen.

|*Bearbeiten*
|Seriennummer bearbeiten. Nach Änderung der Nummer speichern.

|*Löschen*
|Gewählte Seriennummer löschen.
|====

[#300]
== Seriennummern exportieren

Exportiere Seriennummern in einer CSV-Datei.

[.instruction]
Seriennummern exportieren:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Klicke in der Symbolleiste auf *Seriennummern*. +
→ Das Fenster *Seriennummern* wird geöffnet.
. Wähle im Bereich *Seriennummern exportieren* den Status.
. Wähle das Feldtrennzeichen.
. Klicke auf *Exportieren*. +
→ Die Seriennummern werden in einer CSV-Datei exportiert.

[#400]
== Seriennummern zuordnen

Die Zuordnung der Seriennummern erfolgt automatisch über eine Ereignisaktion. Voraussetzung ist die vollständige Bezahlung des Artikels. Die Seriennummern werden in der Rechnung des Auftrags ausgegeben. Richte eine Ereignisaktion ein, damit automatisch eine Seriennummer zugeordnet wird, wenn der Auftrag vollständig bezahlt und in den Auftragsstatus *Zahlungseingang vollständig* versetzt wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Trage einen Namen ein.
. Wähle das *Ereignis* gemäß <<tabelle-ereignisaktion-seriennummern-zuordnen>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ereignisaktion-seriennummern-zuordnen>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--

[[tabelle-ereignisaktion-seriennummern-zuordnen]]
.Ereignisaktion zum automatischen Zuordnen von Seriennummern
[cols="1,1,1"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Zahlung: Vollständig*
|

|*Aktion*
|*Artikel*
|*Seriennummer zuordnen*
|====

Seriennummern kannst du auch in Prozessen verwenden. Voraussetzung für die Verfügbarkeit von Seriennummern in Prozessen ist die Aktivierung der Option *Seriennummer* im Tab *Global* eines Artikels.

[.instruction]
Seriennummern-Funktion aktivieren:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel, dessen Seriennummern du verwenden möchtest.
. Wechsele in das Tab *Global*.
. Wähle für die Option *Seriennummer* die Einstellung *Ja*.
. *Speichere* die Einstellungen.

Mit Prozessen kannst du das Erfassen von <<automatisierung/prozesse/aktionen#420, Seriennummern automatisieren>>.
