= Das Standardsuchverhalten ändern
:lang: de
include::{includedir}/_header.adoc[]
:description: Willst du die Backend Artikelsuche anpassen? Lerne, wie du die Suchfunktion in plentymarkets modifizieren kannst.
:url: artikel/anwendungsfaelle/suchverhalten
:icons: font
:position: 70
:docinfodir: /workspace/manual-adoc
:docinfo1:

Im Menü **Artikel » Artikel bearbeiten** findest du die Artikelsuche und die damit verbundene Artikelübersicht. Hier erfährst du, wie du die Artikelsuche optimal nutzt.

[#100]
== In Artikelübersicht angezeigte Preise und Barcodes anpassen

Optional kannst du in den Einstellungen festlegen, welcher Verkaufspreis und/oder welcher Barcode in den Spalten der Artikelübersicht angezeigt werden. Wenn du keine Einstellungen vornimmst, wird der erste an der Variante gespeicherte Verkaufspreis und/oder Barcode angezeigt.

[.instruction]
Artikelübersicht anpassen:

. Öffne das Menü **Einrichtung » Artikel » Einstellungen**.
. Wähle für die Option **Bevorzugter Preis in der Artikelsuche** den Verkaufspreis, der bevorzugt in der Spalte **Verkaufspreis** Artikelübersicht angezeigt werden soll. +
→ Bei Varianten, die nicht mit diesem Verkaufspreis verknüpft sind, wird einer der gespeicherten Preise angezeigt.
. Wähle für die Option **Bevorzugter Barcode in der Artikelsuche** den Barcode, der bevorzugt in der Spalte **Barcode** der Artikelübersicht angezeigt werden soll. +
→ Bei Varianten, die nicht mit diesem Barcode verknüpft sind, wird einer der gespeicherten Barcodes angezeigt.
. **Speichere** die Einstellungen.


[#200]
== Backend-Artikelsuche einrichten

Im Menü *Einrichtung » Artikel » Suche » Backend » Suchindex* nimmst du Einstellungen vor, damit Artikel in der Artikelsuche im Menü *Artikel » Artikel bearbeiten* gefunden werden. Dazu definierst du die Artikelparameter, die vom Suchindex erfasst werden sollen und somit durchsucht werden, wenn eine Backend-Suche ausgeführt wird.

Der Suchindex wird automatisch aufgebaut, wenn ein neuer Artikel erstellt wird. Wenn du Artikel importierst, wird der Suchindex über Nacht aktualisiert. Pro Vorgang werden maximal 3000 Artikel zum Suchindex hinzugefügt. Wenn mehr als 3000 Artikel im System gespeichert sind, dauert es also mehrere Nächte, bis der Suchindex aktualisiert ist.

Im Tab *Artikelstamm* siehst du, wie viele Artikel insgesamt vom Suchindex erfasst werden. Im Tab **Artikelmerkmale** siehst du, wie viele Artikel mit Merkmalen vom Suchindex erfasst werden.

Im Menü *Einrichtung » Artikel » Suche » Backend » Suchindex* kannst du die Aktualisierung des Suchindex auch manuell starten.

[NOTE]
.Alter Webshop Callisto mit Standard-Suche
====
Bei Webshops mit dem alten Design Callisto, für die im Menü *Einrichtung » Mandant » Mandant wählen » Webshop » Artikelsuche* die Option *Standard-Suche* aktiviert ist, wird der Index der Backend-Artikelsuche auch für die Artikelsuche im Frontend verwendet.
====

[#300]
=== Standardindex einrichten

Mit dem Standardindex legst du fest, welche Artikelparameter vom Suchindex erfasst und bei der Artikelsuche im Backend berücksichtigt werden. Gehe wie unten beschrieben vor, um den Standard-Index einzurichten.

[IMPORTANT]
.Änderungen am Suchindex vermeiden
====
Vermeide Änderungen am Suchindex. Nach einer Änderung wird der Suchindex neu aufgebaut. Wenn du viele Artikel hast, kann dieser Vorgang sehr lang dauern.
====

[.instruction]
Standardindex einrichten:

. Öffne das Menü *Einrichtung » Artikel » Suche » Backend » Suchindex*.
. Wechsele in das Tab *Standard-Index*.
. Aktiviere die Parameter, die bei der Artikelsuche berücksichtigt werden sollen.
. *Speichere* die Einstellungen. +
→ Die gewählten Parameter werden bei der Artikelsuche im Backend berücksichtigt.


[#400]
=== Erweiterten Index einrichten

Zusätzlich zum Standardindex erfasst du über den erweiterten Index auch Parameter, die bei der Suche berücksichtigt werden, wenn im Suchbereich des Menüs **Artikel » Artikel bearbeiten** die Option **In Beschreibung** aktiviert ist. Gehe wie unten beschrieben vor, um den erweiterten Index einzurichten.

[.instruction]
Erweiterten Index einrichten:

. Öffne das Menü *Einrichtung » Artikel » Suche » Backend » Suchindex*.
. Wechsele in das Tab *Erweiterter Index*.
. Aktiviere die Parameter, die bei der Artikelsuche berücksichtigt werden sollen, wenn im Suchbereich des Menüs *Artikel » Artikel bearbeiten* die Option *In Beschreibung* aktiviert ist.
. *Speichere* die Einstellungen. +
→ Die gewählten Parameter werden bei der Artikelsuche im Backend berücksichtigt, wenn die Option *In Beschreibung* aktiviert ist.


[#500]
=== Artikelsuchindex manuell aktualisieren

Im Menü *Einrichtung » Artikel » Suche » Backend » Suchindex » Tab: Übersicht* siehst du, wie viele Artikel im System gespeichert sind und wie viele Artikel im Suchindex enthalten sind.

Wenn ein neuer Artikel erstellt wird, wird der Suchindex automatisch aktualisiert. Wenn du Artikel importierst, wird der Suchindex über Nacht aktualisiert. Wenn Artikel schneller indiziert werden sollen, starte den Aufbau des Artikelsuchindex manuell.

Gehe wie unten beschrieben vor, um den Artikelsuchindex manuell zu aktualisieren.


[.instruction]
Artikelsuchindex manuell aktualisieren:

. Öffne das Menü *Einrichtung » Artikel » Suche » Backend » Suchindex*. +
→ Das Tab *Übersicht* wird angezeigt. +
→ *Indizierte Artikel* zeigt die Anzahl der Artikel pro Sprache, die im Suchindex enthalten sind. +
→ *Gesamtzahl der Artikel* zeigt die Anzahl der Artikel im plentymarkets System. Die Zahl schließt neu importierte und noch nicht indizierte Artikel ein.
. Wenn der Suchindex sofort aktualisiert werden soll, Klicke auf *Artikelsuchindex aufbauen*. +
→ Der Artikelsuchindex wird mit den Daten der ersten 3000 Artikel befüllt.
. Um mehr als 3000 Artikel zu indizieren, klicke erneut auf *Artikelsuchindex aufbauen*, sobald die Option wieder wählbar ist. +
→ Der Artikelsuchindex wird mit den Daten der nächsten 3000 Artikel befüllt.
. Wiederhole den Vorgang, bis alle Artikel indiziert wurden.

[#600]
=== Merkmalsuchindex manuell aktualisieren

Im Menü *Einrichtung » Artikel » Suche » Backend » Suchindex » Tab: Artikelmerkmale* siehst du, wie viele Artikel mit Merkmalen im System gespeichert sind und wie viele Artikel mit Merkmalen im Suchindex enthalten sind.

Wenn ein neuer Artikel mit Merkmalen erstellt wird, wird der Suchindex automatisch aktualisiert. Wenn du Artikel importierst, wird der Suchindex über Nacht aktualisiert. Wenn Artikel schneller indiziert werden sollen, starte den Aufbau des Merkmalsuchindex manuell.

Unabhängig davon, ob der Aufbau des Merkmalsuchindexes automatisch gestartet wird oder ob du den Merkmalsuchindex manuell aufbaust, werden pro Vorgang maximal 3000 Artikel zum Suchindex hinzugefügt. Über Nacht wird nur ein Vorgang durchgeführt. Wenn mehr als 3000 Artikel im System gespeichert sind, dauert es also mehrere Nächte, bis der Suchindex aktualisiert ist. Um Artikel schneller zum Index hinzuzufügen, baue den Merkmalsuchindex mehrmals manuell. Gehe wie unten beschrieben vor, um den Merkmalsuchindex manuell zu aktualisieren.

[.instruction]
Merkmalsuchindex manuell aktualisieren:

. Öffne das Menü *Einrichtung » Artikel » Suche » Backend » Suchindex*.
. Wechsele in das Tab *Artikelmerkmale*. +
→ *Indizierte Artikel mit Merkmalen* zeigt die Anzahl der Artikel mit Merkmalen pro Sprache, die im Suchindex enthalten sind. +
→ *Gesamtzahl der Artikel mit Merkmalen* zeigt die Anzahl der Artikel mit Merkmalen im plentymarkets System. Die Zahl schließt neu importierte und noch nicht indizierte Artikel ein.
. Wenn der Suchindex sofort aktualisiert werden soll, Klicke auf *Merkmalsuchindex aufbauen*. +
→ Der Merkmalsuchindex wird mit den Daten der ersten 3000 Artikel mit Merkmalen befüllt.
. Um mehr als 3000 Artikel mit Merkmalen zu indizieren, klicke erneut auf *Merkmalsuchindex aufbauen*, sobald die Option wieder wählbar ist. +
→ Der Merkmalsuchindex wird mit den Daten der nächsten 3000 Artikel mit Merkmalen befüllt.
. Wiederhole den Vorgang, bis alle Artikel indiziert wurden.
