= Contract
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Contract, plentymarkets, Service center
:position: 35

The menu **Start » plentymarkets account » Service center » Tab: Contract** provides you with information about your current plentymarkets contract. Here you can make changes to your contract or you may cancel your contract.

toc::[]
== Changing the contract

plentymarkets grows along with your needs. Decide for yourself how many orders you want to process with plentymarkets each month. We will provide you with the necessary system performance. The **Contract** tab allows you to make changes in your plentymarkets contract on your own once it is up and running. It makes sense to make changes, e.g. if you generate more orders than are included in your current rate. It is possible to book a higher rate at any time. If you book a lower rate, then it will go into effect once the regular duration of your current contract has ended.

[.instruction]
Changing the contract:

. Go to **Start » plentymarkets account » Service center**.
. Click on the **Contract** tab.
. Click on **System configurator**.
. Make changes to the contract information as desired.

== Canceling a contract

The **Contract** tab in the service center also contains an option for canceling your contract with plentymarkets. Click on **Cancel contract** to request that your contract be canceled.

